### PR TITLE
BF bump to 5.5.0

### PR DESCRIPTION
**Pull request by dgault**
# What this PR does

Bump bio-formats version to 5.5.0

# Testing this PR

Make sure the build is green

### CODE REVIEW

**Comment by sbesson** [comment]
In addition to reviewing the unit and integration tests, it might be useful to run a couple of imports to check the new features included in Bio-Formats 5.5.0 features are working as expected:

- [x] PerkinElmer Columbus: import a sample fileset e.g. `/ome/data_repo/curated/columbus/sero` and check a Plate is successfully created at import and that it matches http://idr.openmicroscopy.org/webclient/?show=plate-4349
- [x] Olympus OIR: import the sample files from http://downloads.openmicroscopy.org/images/Olympus-OIR/etienne/ and check the imported OIR and OME-TIFF images are matching in terms of pixels
- [x] Hamamatsu NDPIS: import the NDPIS fileset from http://downloads.openmicroscopy.org/images/Hamamatsu-NDPI/manuel/ and check that the three image channels have their name and wavelength populated and that the pixels are non-null for each channel
- [x] Andor BSD:  import `/ome/data_repo/curated/andor/qa-16928/2Ch_Z10_T10.tif` and check the acquisition date is populated

**Comment by mtbc** [comment]
Andor acquisition date looks good. I can't see any actual detail in the image: is this expected?

**Comment by mtbc** [comment]
Series 3 of the NDPIS has just a little solid block in it, hope that's expected. (A mask perhaps?)

**Comment by mtbc** [comment]
ndpis

**Comment by sbesson** [comment]
- Columbus plate import running in the background.
- https://github.com/openmicroscopy/openmicroscopy/pull/5283#issuecomment-300114440: not sure about the pixel expectation, worth trying another Andor TIFF file e.g. `/ome/data_repo/curated/andor/chris/Tucid_control_20.tif`?
- https://github.com/openmicroscopy/openmicroscopy/pull/5283#issuecomment-300115826 yes, when present, th third image of NDPI(S) filesets represents a region-active map
- https://github.com/openmicroscopy/openmicroscopy/pull/5283#issuecomment-300117179 looks great /cc @mstritt

**Comment by mtbc** [comment]
Yes, with some aggressively tight rendering settings I am managing to see image data in `Tucid_control_20.tif`, also acquisition date, thank you for the suggestion.

**Comment by mtbc** [comment]
Olympus OIR pixels are matching nicely across timepoints, e.g.,
matching

**Comment by mtbc** [comment]
PerkinElmer Columbus plate looks good. Compared with IDR.

**Review by mtbc — APPROVED** [review]

**Pull request merged**
