### PR TITLE
IDR: use new logo (rebased onto metadata54)

### PR DESCRIPTION
**Pull request by manics**
This is the same as gh-4989 gh-5230 but rebased onto metadata54.

Place the logo in the repository to prevent it being lost between upgrades.

### CODE REVIEW

**Comment by manics** [comment]
--rebased-from #5230

**Comment by joshmoore** [comment]
screen shot 2018-05-10 at 09 40 21

**Review by joshmoore — APPROVED** [review]
Thanks, @manics. I won't try to get a new build together for prod50 but may copy this file manually.

**Comment by joshmoore** [comment]
Manually applied on prod50-omeroreadwrite and the cache refreshed.

**Pull request merged**
