### PR TITLE
OMERO.web Apache 2.4 configuration

### PR DESCRIPTION
**Pull request by manics**
Apache 2.4 requires a slightly different configuration to 2.2.

This also deprecates `omero web config apache` in favour of `apache22` and `apache24`, though `apache` should still work.

### CODE REVIEW

**Comment by aleksandra-tarkowska** [comment]
tested on Mac 10.11 with Apache/2.4.16 (Unix) mod_wsgi/4.4.21 Python/2.7.10

```
###
### Apache 2.4+ stanza for OMERO.web created 2015-11-12 15:58:22.296065
###

<VirtualHost _default_:8080>

  DocumentRoot /Users/ola/OMERO/openmicroscopy/dist/lib/python/omeroweb

  WSGIDaemonProcess omeroweb_omero processes=5 threads=1 display-name=%{GROUP} user=ola python-path=/usr/local/lib/python2.7/site-packages:/Users/ola/OMERO/openmicroscopy/dist/lib/python:/Users/ola/OMERO/openmicroscopy/dist/lib/fallback:/Users/ola/OMERO/openmicroscopy/dist/lib/python/omeroweb

  WSGIProcessGroup omeroweb_omero

  WSGIScriptAlias /omero /Users/ola/OMERO/openmicroscopy/dist/lib/python/omeroweb/wsgi.py

  <Directory "/Users/ola/OMERO/openmicroscopy/dist/lib/python/omeroweb">
    Require all granted
  </Directory>

  Alias /omero/static /Users/ola/OMERO/openmicroscopy/dist/lib/python/omeroweb/static
  <Directory "/Users/ola/OMERO/openmicroscopy/dist/lib/python/omeroweb/static">
    Options -Indexes -FollowSymLinks
    Require all granted
  </Directory>

</VirtualHost>

# see https://code.google.com/p/modwsgi/wiki/ConfigurationIssues
# WSGISocketPrefix run/wsgi
WSGISocketPrefix /var/run/wsgi
```

```
$ curl -i http://omero.local:8080/omero
HTTP/1.1 301 MOVED PERMANENTLY
Date: Thu, 12 Nov 2015 15:59:19 GMT
Server: Apache/2.4.16 (Unix) mod_wsgi/4.4.21 Python/2.7.10
```

**Comment by aleksandra-tarkowska** [comment]
Apache 2.2 tomorrow

**Comment by aleksandra-tarkowska** [comment]
Tested on CentOS 6 with Apache/2.2.15, mod_wsgi 4.4.21 and Python 2.7.5 

```
###
### Stanza for OMERO.web created 2015-11-13 11:06:43.969985
###

<VirtualHost _default_:80>

  DocumentRoot /home/omero/OMERO.server-5.2.0-ice35-b12/lib/python/omeroweb

  WSGIDaemonProcess omeroweb_omero processes=5 threads=1 display-name=%{GROUP} user=omero python-path=/opt/Ice-3.5.1/python:/home/omero/OMERO.server-5.2.0-ice35-b12/lib/python:/home/omero/OMERO.server-5.2.0-ice35-b12/lib/fallback:/home/omero/OMERO.server-5.2.0-ice35-b12/lib/python/omeroweb

  WSGIProcessGroup omeroweb_omero

  WSGIScriptAlias /omero /home/omero/OMERO.server-5.2.0-ice35-b12/lib/python/omeroweb/wsgi.py

  <Directory "/home/omero/OMERO.server-5.2.0-ice35-b12/lib/python/omeroweb">
    Order allow,deny
    Allow from all
  </Directory>

  Alias /omero/static /home/omero/OMERO.server-5.2.0-ice35-b12/lib/python/omeroweb/static
  <Directory "/home/omero/OMERO.server-5.2.0-ice35-b12/lib/python/omeroweb/static">
      Options -Indexes FollowSymLinks
      Order allow,deny
      Allow from all
  </Directory>

</VirtualHost>

# see https://code.google.com/p/modwsgi/wiki/ConfigurationIssues
WSGISocketPrefix run/wsgi
# WSGISocketPrefix /var/run/wsgi
```

```
$ curl -i http://ola-test-1.docker.openmicroscopy.org/omero
HTTP/1.1 301 MOVED PERMANENTLY
Date: Fri, 13 Nov 2015 11:14:50 GMT
Server: Apache/2.2.15 (CentOS)
```

**Comment by manics** [comment]
Added a note to the Apache 2.4 template as suggested by @ximenesuk

**Comment by aleksandra-tarkowska** [comment]
@manics could you point Mac as well?

**Comment by jburel** [comment]
tested while  working centos7/apache2.4

**Comment by ximenesuk** [comment]
This was also tested by me working on ubuntu14.04/apache2.4.

**Comment by jburel** [comment]
Merging so @ximenesuk can move forward with the omero-install PR

**Pull request merged**
