### PR TITLE
Add int test for getOriginalMetadata method

### PR DESCRIPTION
**Pull request by dominikl**
Add integration test for https://github.com/ome/omero-gateway-java/pull/72 .
Simply checks if the method returns something.

### CODE REVIEW

**Comment by jburel** [comment]
Build failure https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-build/306/

**Comment by dominikl** [comment]
Sorry. Should be fixed now. How could the previous commit get a green tick, if it's already a compile error?

**Comment by jburel** [comment]
We will need to check, one job might exclude the tests?

**Comment by dominikl** [comment]
Closing again. Don't know how to test. I guess the artifical test images created for the integration test don't have any "original metadata", hence the method returns just an empty string for them.

**Comment by sbesson** [comment]
If the images created for the integration tests use the API to create the objects and then write the planes using the PixelsService, then there will indeed be no original metadata.

To test this API, you'll likely need to import an image. You should be able to use the `.fake` format which allows to create original metadata key/value pairs programmatically for testing - https://bio-formats.readthedocs.io/en/stable/developers/generating-test-images.html

**Pull request closed without merging**
