### PR TITLE
Move filter condition static string to function

### PR DESCRIPTION
**Pull request by jballanc**
This removes the static strings in `AllGroupsSecurityFilter` and
`OneGroupSecurityFilter` that define the filter condition and replaces
them with `static` methods of the same name. The only place this string
was being used in either class was in `getDefaultFilterCondition`, so
that reference has been changed to a call to the new method.

### CODE REVIEW

**Comment by mtbc** [comment]
I'm curious about the motivation; some classfile optimization issue that affects even private statics?

**Comment by jballanc** [comment]
Because of optimizations, the `static String` is inlined into the body of `defaultFilterCondition`, such that providing a different version of the filter string in a subclass has no affect unless the subclass also overrides `defaultFilterCondition`.

**Comment by mtbc** [comment]
How can the subclass override `defaultFilterCondition` when it is private? (Ah, this is some inner class thing?)

**Comment by mtbc** [comment]
I still don't understand; the static string is private so the subclass shouldn't be able to provide a different version of it. Even if inlined into `getDefaultCondition()`, when you override that method you provide a different method body anyway that can't reference `myFilterCondition`? If you happen to have some code on some branch that depends on this change and makes everything clear I'd love to see it.

(Sorry for prior version of this comment; I'm just feeling confused!)

**Comment by mtbc** [comment]
Ah! Does the subclass' class file contain a copy of the bytecode of the superclass' method (with the inlined string) even if the subclass' code oughtn't technically be able to see that string? So that's the problem this fixes?

**Comment by jballanc** [comment]
The issue is that if the subclass doesn't re-implement `getDefaultCondition()`, then calling that method bubbles up to the original class where the method *does* still contain the `private static String`. As a simple example of what I mean:

```java
// foo/Bar.java
package foo;

public class Bar {
    private static String msg = "Secret Bar message.";

    public void announce() {
        System.out.println(msg);
    }
}
```
```java
// foo/Baz.java
package foo;

public class Baz extends Bar {
    private static String msg = "Secret Baz message.";
}
```
```java
// Foo.java
import foo.Bar;
import foo.Baz;

public class Foo {
    static final public void main(String[] args) {
        System.out.println("From Bar...");
        Bar bar = new Bar();
        bar.announce();
        System.out.println("From Baz...");
        Baz baz = new Baz();
        baz.announce();
    }
}
```
```bash
> javac foo/Bar.java foo/Baz.java Foo.java
> java Foo
From Bar...
Secret Bar message.
From Baz...
Secret Bar message.
```

**Comment by mtbc** [comment]
Thank you for the minimal example! But, if I do what your PR seems to,
```java
// foo/Bar.java
package foo;

public class Bar {
    private static String msg() { return "Secret Bar message."; }

    public void announce() {
        System.out.println(msg());
    }
}
```
```java
// foo/Baz.java
package foo;

public class Baz extends Bar {
    private static String msg() { return "Secret Baz message."; }
}
```
```java
// Foo.java
import foo.Bar;
import foo.Baz;

public class Foo {
    static final public void main(String[] args) {
        System.out.println("From Bar...");
        Bar bar = new Bar();
        bar.announce();
        System.out.println("From Baz...");
        Baz baz = new Baz();
        baz.announce();
    }
}
```
```
> javac foo/Bar.java foo/Baz.java Foo.java
> java Foo
From Bar...
Secret Bar message.
From Baz...
Secret Bar message.
```
... it doesn't seem to help. I appreciate your continued patience with me!

**Comment by jballanc** [comment]
Heh, I actually just noticed that...on second inspection, I think you're right @mtbc . Just changing the string to a method seems insufficient. Back to the drawing board I suppose...

**Comment by mtbc** [comment]
`protected` is probably your friend. :smiley:

**Comment by jballanc** [comment]
Just tried `protected` and even that's insufficient. I think there's an issue with calling `static` from non-`static` scope.

**Comment by mtbc** [comment]
Yeah, has to be non-static for any useful overriding.

**Comment by mtbc** [comment]
Looking far more plausible, great.

**Comment by mtbc** [comment]
How frequently will the method be called? With the current change, we go from constructing the string once to constructing it every time.

**Comment by jballanc** [comment]
The call to `getDefaultCondition()` only happens at instantiation, which I think shouldn't be that frequent. Besides, if my understanding of JVM optimizations is correct the string should be cached at the call-site, making it functionally equivalent to the static string case (once optimizations are applied).

**Comment by mtbc** [comment]
I'd be surprised if `AllGroupsSecurityFilter.getDefaultCondition()` had any useful string caching for the result of the `String.format` in `myFilterCondition()` but if infrequent then it's not a big deal.

**Comment by dominikl** [comment]
From the code perspective this looks fine to me. Unfortunately I don't know how to test it. Is it covered by the integration tests? If it is, good to merge from my point of view.

**Comment by jballanc** [comment]
I suppose so long as the integration tests still work, that's confirmation of the default case. Using the same patch we've adjusted the test timeout on a private branch and I can confirm that the tests do, indeed, run for longer with it set. Would that be sufficient?

**Comment by jballanc** [comment]
If the server is still properly restricting group-level access, then that would imply this is working as expected. We've got a private branch with a different filter string (for a different DB) in a subclass, and it is working as expected there as well.

**Comment by dominikl** [comment]
Ok, then I think it's good to merge.

**Pull request merged**
