### PR TITLE
Update library

### PR DESCRIPTION
**Pull request by jburel**
Upgrade commons-lang to commons-lang3
This was generating an error when using the omero-ij plugin in Fiji
see https://trac.openmicroscopy.org.uk/ome/ticket/12713
Other libraries could be updated e.g. commons-collections to commons-collections4.
Either in this PR or in a follow-up one.

--no-rebase

### CODE REVIEW

**Comment by joshmoore** [comment]
We shouldn't need to add jars to the repository. Before this moves forward too far, could that be force-pushed away?

**Comment by mtbc** [comment]
:+1: This makes a lot of the methods generics-aware.

**Comment by jburel** [comment]
jar removed.
I am probably going to go ahead with the collections, we will have some UI library upgrade in a follow-up PR cc @dominikl

**Comment by sbesson** [comment]
From https://ci.openmicroscopy.org/job/OMERO-5.1-merge-integration/458/ `Blitz.log`

```
2015-02-11 04:04:06,124 ERROR [                ome.services.blitz.Entry] (      main) Error on startup.
org.springframework.beans.factory.access.BootstrapException: Unable to return specified BeanFactory instance: factory key [OMERO.blitz], from group with resource name [classpath*:beanRefContext.xml]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'OMERO.blitz' defined in URL [jar:file:/opt/hudson/workspace/OMERO-5.1-merge-integration/src/dist/lib/server/blitz.jar!/beanRefContext.xml]: Cannot resolve reference to bean 'ome.server' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ome.server' defined in URL [jar:file:/opt/hudson/workspace/OMERO-5.1-merge-integration/src/dist/lib/server/server.jar!/beanRefContext.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [ome.system.OmeroContext]: Constructor threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'internal-ome.api.IDelete' defined in URL [jar:file:/opt/hudson/workspace/OMERO-5.1-merge-integration/src/dist/lib/server/server.jar!/ome/services/service-ome.api.IDelete.xml]: Cannot resolve reference to bean 'internal-ome.api.LocalAdmin' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'internal-ome.api.IAdmin' defined in URL [jar:file:/opt/hudson/workspace/OMERO-5.1-merge-integration/src/dist/lib/server/server.jar!/ome/services/service-ome.api.IAdmin.xml]: Cannot resolve reference to bean 'passwordProvider' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'chainedPasswordProvider431' defined in URL [jar:file:/opt/hudson/workspace/OMERO-5.1-merge-integration/src/dist/lib/server/server.jar!/ome/services/service-ome.api.IAdmin.xml]: Cannot resolve reference to bean 'ldapPasswordProvider431' while setting constructor argument with key [0]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ldapPasswordProvider431' defined in URL [jar:file:/opt/hudson/workspace/OMERO-5.1-merge-integration/src/dist/lib/server/server.jar!/ome/services/service-ome.api.IAdmin.xml]: Cannot resolve reference to bean 'internal-ome.api.ILdap' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'internal-ome.api.ILdap' defined in URL [jar:file:/opt/hudson/workspace/OMERO-5.1-merge-integration/src/dist/lib/server/server.jar!/ome/services/service-ome.api.ILdap.xml]: Cannot resolve reference to bean 'contextSource' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'contextSource' defined in URL [jar:file:/opt/hudson/workspace/OMERO-5.1-merge-integration/src/dist/lib/server/server.jar!/ome/services/service-ome.api.ILdap.xml]: Cannot resolve reference to bean 'contextSourceSwapper' while setting bean property 'targetSource'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'contextSourceSwapper' defined in URL [jar:file:/opt/hudson/workspace/OMERO-5.1-merge-integration/src/dist/lib/server/server.jar!/ome/services/service-ome.api.ILdap.xml]: Cannot resolve reference to bean 'defaultContextSource' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'defaultContextSource' defined in URL [jar:file:/opt/hudson/workspace/OMERO-5.1-merge-integration/src/dist/lib/server/server.jar!/ome/services/service-ome.api.ILdap.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [org.springframework.security.ldap.DefaultSpringSecurityContextSource]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: org/apache/commons/lang/StringUtils
	at org.springframework.beans.factory.access.SingletonBeanFactoryLocator.useBeanFactory(SingletonBeanFactoryLocator.java:409) ~[org.springframework.beans.jar:3.0.1.RELEASE-A]
	at ome.system.OmeroContext.getInstance(OmeroContext.java:203) ~[common.jar:na]
	at ome.services.blitz.Entry.start(Entry.java:193) [blitz.jar:na]
	at ome.services.blitz.Entry.main(Entry.java:150) [blitz.jar:na]
```

Excluding.

**Comment by jburel** [comment]
crap one more.. a git grep didn't list it

**Comment by joshmoore** [comment]
NB: It might be that our versions of spring, hibernate, etc. will also have to be upgraded to make a change like this.

**Comment by jburel** [comment]
@joshmoore: could be, for collections other apache will have to be upgraded, so might do that in another PR instead (cf. comment above)

**Comment by sbesson** [comment]
:+1: I would suggest driving this via `breaking` first once the issue above is solved.

**Comment by jburel** [comment]
@sbesson: that was my plan after that failure.

**Comment by jburel** [comment]
* Upgraded spring to 4.0.9.RELEASE, note that to upgrade it to 4.1.x so code changes are required: classes like ```JobDetailAwareTrigger``` no longer exist.
 * Note that it fails at start up with ```Java.lang.NoClassDefFoundError: org/hibernate/type/TypeResolver```

**Comment by jburel** [comment]
spring upgrade will require a hibernate upgrade. Already various attempts w/o much success.
I have added both commons-lang and commons-lang3. No success!!

**Comment by jburel** [comment]
Not possible to upgrade across the code base.
Replaced by https://github.com/openmicroscopy/openmicroscopy/pull/3485

**Pull request closed without merging**
