### PR TITLE
updating mail notification icon

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
@gusferguson please test it on with the next built on Monday

### CODE REVIEW

**Comment by aleksandra-tarkowska** [comment]
@gusferguson I think it looks very good

**Comment by gusferguson** [comment]
@aleksandra-tarkowska 

Tested with https://trout.openmicroscopy.org/merge/webclient/ user-3

Grey icon under user settings looks fine to me.
Is the white one somewhere I can check - or is that not used at the moment?

Good to merge.

**Comment by aleksandra-tarkowska** [comment]
@gusferguson when you mouse over help white will appear ;-)

**Comment by gusferguson** [comment]
@aleksandra-tarkowska - Doh! :-) Sorry - not thinking today!

**Pull request merged**
