### PR TITLE
session cookie domain

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
1. This should help with side effect reported in https://trello.com/c/aRDoP7dC/355-omero-web-startup-review-default-ip. To test:
 - add
 ```
bin/omero config set omero.web.session_cookie_domain "localhost"
 ```
 - open private windows in your webbrowser
 - go to localhost:4080, and log in. All shoudl be as normal
 - if you have another domain configured on you machine use it, otherwise go to 127.0.0.1:4080 and log in. you should be back to your login page without any error message. that means you cookie wasn't save.

 if you remove ```omero.web.session_cookie_domain``` you should be able to log in from all possible domains assigned to the same machine

1.  This should also resolve issue reported in https://github.com/openmicroscopy/openmicroscopy/pull/3629#issuecomment-82874726. To test:
 - remove all cookies created for your local domain in your webbrowser
 - add
 ```
bin/omero config set omero.web.session_cookie_name "myowncookiename"
 ```
 - check if you log in to web cookie name has changed

cc @sbesson 

--no-rebase

### CODE REVIEW

**Comment by sbesson** [comment]
Talking to @aleksandra-tarkowska, the proposal is to have unique cookie_name per deployment on the CI server using something like:

```
bin/omero config set omero.web.session_cookie_name config_$JOB_NAME
```

Is that correct

**Comment by manics** [comment]
https://docs.djangoproject.com/en/1.7/ref/settings/#std:setting-SESSION_COOKIE_DOMAIN
Sounds like it's still tied to the top-level domain?

**Comment by manics** [comment]
Also W.R.T. the cross-domain proxy scenario, the MITM proxy could still rewrite the session cookie.

**Comment by aleksandra-tarkowska** [comment]
@manics @sbesson refered to 2. Unique cookie name should resolve issue @pwalczysko faced today. We do not have any better environment to test it then CI. It doesn't heart to have that configured anyway.

**Comment by pwalczysko** [comment]
Not sure about all the implications here, but the issue with the multiple windows/tabs logging into merge and latest is gone (thanks).

**Comment by manics** [comment]
`SESSION_COOKIE_NAME` works as expected on trout (simultaneous logins on latest and merge).

`SESSION_COOKIE_DOMAIN`: I guess there's no harm having this, but I don't think it's particularly useful if the your main aim is to guard against MITM attacks (since it's easy to bypass).

**Comment by pwalczysko** [comment]
@manics This PR is mainly useful for me I guess (possibly I am wrong) - in testing situation, it was a real pain not to be able to login simultaneously to merge and latest.

**Comment by manics** [comment]
@pwalczysko Yes, there's two changes in here though, `SESSION_COOKIE_NAME` fixes your problem.

**Comment by pwalczysko** [comment]
@manics : Ah, sorry, missed this, thanks for clarifying.

**Comment by sbesson** [comment]
@manics: so should we merge this or should we have the `SESSION_COOKIE_DOMAIN` fixed here or somewhere else?

**Comment by aleksandra-tarkowska** [comment]
@manics but that is particular useful if you would allow a cookie to be shared across

**Comment by manics** [comment]
There's probably no harm in having it.

**Pull request merged**
