### PR TITLE
Fix image simple marshal

### PR DESCRIPTION
**Pull request by chris-allan**
Fix a typo bug found in `ImageWrapper.simpleMarshal()` during performance testing and improvement. Unit tests included.

/cc @jballanc

### CODE REVIEW

**Comment by joshmoore** [comment]
Kicked travis (HDF5 error)

**Comment by will-moore** [comment]
I wonder if we should align ```ImageWrapper.simpleMarshal()``` which uses ```tiled``` and ```webgateway.marshal.py imageMarshal()``` which uses ```tiles```? Seems a little confusing to have the different keys.
They also use different methods to determine if they are tiled images, using image size in Blitz gateway but using ```re.requiresPixelsPyramid()``` in webgateway, but there may be good reasons for this and it's not so related to this PR.

**Comment by joshmoore** [comment]
@will-moore: good to merge, then? If so, can you create a card to track any investigation/refactoring that you want to see happen re: `imageMarshal`?

**Comment by will-moore** [comment]
Yes, good to merge.

**Comment by will-moore** [comment]
@chris-allan Where is ```ImageWrapper.simpleMarshal()``` used? What would be the effect of changing ```tiled``` to ```tiles``` for this?

**Comment by chris-allan** [comment]
Its main function as far as I'm aware is as part of the marshaling core that is used as part of various JSON calls. In working on #3695 we never investigated this more thoroughly, since we were basically removing singular usage of wrapper sub-class marshaling, but that could certainly be done.

**Pull request merged**
