### PR TITLE
Mif ij dev 5 1

### PR DESCRIPTION
**Pull request by jburel**
--rebased-from #4001

To test this PR

test 1:
 * Open a mif from local file system
 * Do not select all series.
 * Save the images to OMERO
 * After saving, Draw a roi on the image
 * Click Save ROIs.
 * Check that no dialog indicating "Do you want to import images..." pops up
 * Check that the rois are saved.

test 2:
 * Repeat the same steps with a tiff file

test 3:
 * repeat the same steps with a single file e.g. dv

-----
extra tests:

test 4:
* Open a mif from local file system
 * Do not select all series e.g. 2 series
 * Save the images to OMERO but this time Select "Images from all windows"
 * Check that the image is only imported once.

test 5:
 * Open a mif from local file system
 * Do not select all series e.g. 2 series
 * Draw some rois
 * Select the "save rois" options (not save images options).Select "Images from all windows"
 * Check that the dialog asking to import the images pops up
 * Check that the image is only imported once.

### CODE REVIEW

**Comment by sbesson** [comment]
@bramalingam: what was the results of the testing for this PR?

**Comment by bramalingam** [comment]
Test5: Do the same steps, but add ROI's at the end of that workflow to the ImagePlus window, and save ROI's to OMERO. 

Bug: This saves the ROI's but throws the "Do you want to import images..." dialog as well(which is weird). 
-- The ROI's saved window pops up first.
-- "Do you want to import images..." dialog pops up next

**Comment by jburel** [comment]
@bramalingam:Thanks ... this might also happen on develop

**Comment by bramalingam** [comment]
PR looks good to merge..! 

One edge case for ROI propagation to all planes on import was discussed with @jburel and that will be left as it is for the time being..! 

Test done (For the edge case):

Open a mif from local file system
Do not select all series.
Draw ROI's and add to ROI Manager
Save the images to OMERO
---> ROI's present all images within the MIF (in OMERO)
Clear all ROI's in the ROI Manager.
After saving, Draw a roi on the image
Click Save ROIs.
Check that no dialog indicating "Do you want to import images..." pops up
Check that the rois are saved.
--->ROI saved to the specific series/image (not propagated to all the MIF series's)

**Comment by jburel** [comment]
Comment added to https://trello.com/c/7baVQ2O0/23-testing

**Pull request merged**
