### PR TITLE
OMERO.matlab: map annotations

### PR DESCRIPTION
**Pull request by sbesson**
This PR exposes the new MapAnnotation in the OMERO.matlab toolbox

-  the `getAnnotationTypes` dictionary is extended to include maps
- a new `writeMapAnnotation` function is added to create maps from either strings or cell arrays of key/value pairs
- the `WriteData` example is extended to cover map creation/linking/retrieval

--no-rebase

### CODE REVIEW

**Comment by sbesson** [comment]
See https://ci.openmicroscopy.org/job/OMERO-5.1-merge-training/248/console

**Comment by manics** [comment]
Works as expected. Should there be a `get*MapAnnotations()` method? Or are they being deprecated to avoid too many methods?

**Comment by sbesson** [comment]
@manics: yes the `getxxxyyyAnnotations()` table is to maintain (esp. help headers of all similar files need to be updated) and the table becomes unreadable. The [documentation](http://www.openmicroscopy.org/site/support/omero5.1/developers/Matlab.html#annotations) has been modified to point at the generic `getObjectAnnotations` function as the default one.

**Comment by manics** [comment]
Good to merge then

**Pull request merged**
