### PR TITLE
web start --foreground

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
This PR allows starting OMERO.web without daemon, in docker web won't start otherwise 

```
$bin/omero web start --foreground
... gunicorn -p ...
```

```
$bin/omero web start
... gunicorn -D -p ...
```

### CODE REVIEW

**Comment by aleksandra-tarkowska** [comment]
this is not needed

**Comment by manics** [comment]
I think this would be useful for a production OMERO.web docker container (which shouldn't use systemd)

**Comment by aleksandra-tarkowska** [comment]
@manics I am not really sure if that is needed. I added shutdown script in . This only send gunicorn to stdout

```
web_1 | 0 static files copied to '/home/omero/static/web', 623 unmodified, 2 post-processed.
web_1 | Clearing expired sessions. This may take some time... [OK]
web_1 | Starting OMERO.web... [2016-04-27 06:33:44 +0000] [64] [INFO] Starting gunicorn 19.4.5
web_1 | [2016-04-27 06:33:44 +0000] [64] [INFO] Listening at: http://0.0.0.0:4080 (64)
web_1 | [2016-04-27 06:33:44 +0000] [64] [INFO] Using worker: sync
web_1 | [2016-04-27 06:33:44 +0000] [69] [INFO] Booting worker with pid: 69
web_1 | [2016-04-27 06:33:44 +0000] [72] [INFO] Booting worker with pid: 72
web_1 | [2016-04-27 06:33:44 +0000] [75] [INFO] Booting worker with pid: 75
web_1 | [2016-04-27 06:33:44 +0000] [84] [INFO] Booting worker with pid: 84
web_1 | [2016-04-27 06:33:44 +0000] [89] [INFO] Booting worker with pid: 89



web_1 | Stopping OMERO.web... [OK]
web_1 | OMERO.web WSGI workers (PID 64) killed.
web_1 | Removed stale /home/omero/workspace/OMERO-web/OMERO.web/var/django.pid
web_1 | [2016-04-27 06:33:55 +0000] [64] [INFO] Handling signal: term
web_1 | [2016-04-27 07:33:55 +0000] [72] [INFO] Worker exiting (pid: 72)
web_1 | [2016-04-27 07:33:55 +0000] [84] [INFO] Worker exiting (pid: 84)
web_1 | [2016-04-27 07:33:55 +0000] [75] [INFO] Worker exiting (pid: 75)
web_1 | [2016-04-27 07:33:55 +0000] [89] [INFO] Worker exiting (pid: 89)
web_1 | [2016-04-27 07:33:55 +0000] [69] [INFO] Worker exiting (pid: 69)
web_1 | [2016-04-27 06:33:55 +0000] [64] [INFO] Shutting down: Master
web_1 | [OK]
web_1 | Stopping OMERO.web... [NOT STARTED]
```

**Comment by aleksandra-tarkowska** [comment]
As far as I understood docker by default won't handle proper cleanup. It will just sent SIGTERM but that is not enough. `django.pid` won't be removed and web will fail on startup (and that is what we want). I am guessing server is similar, it should be stopped properly. I hope that make sense.

**Comment by aleksandra-tarkowska** [comment]
I would vote after closing this PR and not allowing this.

**Comment by manics** [comment]
That cleanup script is fine for a dev container, but the best-practice for a production docker image is to have a single process in the foreground. If SIGTERM isn't enough, what changes are required to OMERO.web to handle it?

**Comment by aleksandra-tarkowska** [comment]
I pushed the pid cleanup

**Comment by aleksandra-tarkowska** [comment]
anyway that will be useful for debugging why web doesn't start

**Comment by manics** [comment]
Works nicely:

```
[omero@5e3fc27ba3df ~]$ OMERO.server/bin/omero web start
Post-processed 'omeroweb.viewer.min.css' as 'omeroweb.viewer.min.css'
Post-processed 'omeroweb.viewer.min.js' as 'omeroweb.viewer.min.js'

0 static files copied to '/home/omero/OMERO.server/lib/python/omeroweb/static', 623 unmodified, 2 post-processed.
Clearing expired sessions. This may take some time... [OK]
Starting OMERO.web... [OK]

[omero@5e3fc27ba3df ~]$ OMERO.server/bin/omero web restart --foreground
Stopping OMERO.web... [OK]
OMERO.web WSGI workers (PID 943) killed.
Removed stale /home/omero/OMERO.server/var/django.pid
Post-processed 'omeroweb.viewer.min.css' as 'omeroweb.viewer.min.css'
Post-processed 'omeroweb.viewer.min.js' as 'omeroweb.viewer.min.js'

0 static files copied to '/home/omero/OMERO.server/lib/python/omeroweb/static', 623 unmodified, 2 post-processed.
Clearing expired sessions. This may take some time... [OK]
Starting OMERO.web... [2016-04-28 16:09:40 +0000] [994] [INFO] Starting gunicorn 19.4.5
[2016-04-28 16:09:40 +0000] [994] [INFO] Listening at: http://127.0.0.1:4080 (994)
[2016-04-28 16:09:40 +0000] [994] [INFO] Using worker: sync
[2016-04-28 16:09:40 +0000] [999] [INFO] Booting worker with pid: 999
[2016-04-28 16:09:41 +0000] [1004] [INFO] Booting worker with pid: 1004
[2016-04-28 16:09:41 +0000] [1009] [INFO] Booting worker with pid: 1009
[2016-04-28 16:09:41 +0000] [1014] [INFO] Booting worker with pid: 1014
[2016-04-28 16:09:41 +0000] [1016] [INFO] Booting worker with pid: 1016

^CCancelled
[2016-04-28 16:09:45 +0000] [994] [INFO] Handling signal: int
[omero@5e3fc27ba3df ~]$ [2016-04-28 17:09:45 +0000] [1016] [INFO] Worker exiting (pid: 1016)
[2016-04-28 17:09:45 +0000] [1004] [INFO] Worker exiting (pid: 1004)
[2016-04-28 17:09:45 +0000] [1009] [INFO] Worker exiting (pid: 1009)
[2016-04-28 17:09:45 +0000] [1014] [INFO] Worker exiting (pid: 1014)
[2016-04-28 17:09:45 +0000] [999] [INFO] Worker exiting (pid: 999)
[2016-04-28 16:09:45 +0000] [994] [INFO] Shutting down: Master
```

**Pull request merged**
