### PR TITLE
Bump Bio-Formats version to 5.2.1

### PR DESCRIPTION
**Pull request by sbesson**
### What this PR does

Following the  [public release of Bio-Formats 5.2.0](https://www.openmicroscopy.org/community/viewtopic.php?f=11&t=8101), this PR bumps the version consumed by OMERO to the final version.

## Testing this PR

From the merge server, check:

- the dependencies under `share/server/dependencies.html` list the correct versions of Bio-Formats components
- `bin/omero import -f test.fake` reports the correct version of Bio-Formats

### CODE REVIEW

**Comment by mtbc** [comment]
Testing locally, this works just fine for me. :+1:

**Comment by mtbc** [comment]
```
Bioformats version: 5.2.0 revision: ed9c5f73b765604199c5d64bec36ff8cc6ee392e date: 17 August 2016
```

**Comment by mtbc** [comment]
On `dependencies.html` everything is "Revision: 5.2.0" (latest has "5.2.0-m5"). Good to merge.

**Comment by sbesson** [comment]
Last commit should bump Bio-Formats version to 5.2.1

**Comment by mtbc** [comment]
Now all "Revision: 5.2.1" and,
```
Bioformats version: 5.2.1 revision: 0bc799913f4f10afbfeb1e2806185bab68873c34 date: 24 August 2016
```
Good to merge.

**Comment by mtbc** [comment]
(The yellow OMERO-DEV-merge-build is nothing to do with this.)

**Comment by jburel** [comment]
Merging before tagging

**Pull request merged**
