### PR TITLE
admin diagnostics: report byte file sizes for small log files

### PR DESCRIPTION
**Pull request by mtbc**
# What this PR does

Reports sizes of small log files in bytes.

# Testing this PR

`bin/omero admin diagnostics` with some small non-empty log files.

# Related reading

https://github.com/openmicroscopy/openmicroscopy/pull/5901#pullrequestreview-174784794

### CODE REVIEW

**Comment by mtbc** [comment]
I expect "1 bytes" to be unlikely enough to not be worth clutter to make "1 byte".

**Review by manics — APPROVED** [review]
Looks fine to me:
```
Log files:  Blitz-0.log                    n/a
Log files:  DropBox.log                    102.0 KB
Log files:  FileServer.log                 104.0 MB
Log files:  Indexer-0.log                  n/a
Log files:  MonitorServer.log              n/a
Log files:  Processor-0.log                n/a
Log files:  Tables-0.log                   n/a
Log files:  TestDropBox.log                2.0 GB
Log files:  master.err                     2 bytes
Log files:  master.out                     empty
Log files:  Total size                     2252.44 MB
```
Though if `1 bytes` bothers you you could use just `B`

**Comment by joshmoore** [comment]
:+1: for `B`

**Review by manics — APPROVED** [review]
```
Log dir:    /tmp/OMERO.py-5.4.9-160-75d1efb-ice36-b296/var/log exists
Log files:  Blitz-0.log                    n/a
Log files:  DropBox.log                    102.0 KB
Log files:  FileServer.log                 104.0 MB
Log files:  Indexer-0.log                  n/a
Log files:  MonitorServer.log              n/a
Log files:  Processor-0.log                n/a
Log files:  Tables-0.log                   n/a
Log files:  TestDropBox.log                2.0 GB
Log files:  master.err                     2 B
Log files:  master.out                     empty
Log files:  Total size                     2252.44 MB
```

**Pull request merged**
