### PR TITLE
Config big image zoom

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
the same as https://github.com/openmicroscopy/openmicroscopy/pull/3627/

Test with local server:
 - Import a big (pyramid) image
 - View image in fullviewer. Expected behaviour: Zoom level is set automatically to a reasonable value.
 - Set the zoom level property to zero with ```omero config set omero.client.viewer.initial_zoom_level 0``` and restart the server
 - Open the image in fullviewer; the initial zoom level should be zoomed out as far as possible (make sure it's the same for Web and Insight)
 - Change the property with ```omero config set omero.client.viewer.initial_zoom_level 5``` and restart the server
 - Open the image again in fullviewer; now the initial zoom level should be 100% 

Make sure Web and Insight show the same

NOTE: please make sure you log out before changing omero config value. Server config is loaded on login once

### CODE REVIEW

**Comment by dominikl** [comment]
Does this mean I can close #3627 ?

**Comment by aleksandra-tarkowska** [comment]
I think if your is merged these commits will disappear.

**Comment by will-moore** [comment]
This seems to be working fine. Minor points:
 - The default "reasonable value" is the same as ```initial_zoom_level 0 ``` so there's no change after setting that.
 - In Insight with ```initial_zoom_level 0 ``` the bird's eye view area doesn't quite cover the whole region of the bird's eye thumbnail, even though we're fully zoomed out, so it's not quite in sync (see screenshot).
 - With ```initial_zoom_level 5 ``` Insight has a much bigger window (fills screen) whereas web has the same size window as before.

These seem unrelated to the config functionality, so I think this is good to merge.

screen shot 2015-04-14 at 16 28 36

**Comment by dominikl** [comment]
I wait for this PR being merged, then I'll close mine #3685 ; will fix the Insight issues noticed by @will-moore and @rleigh-dundee in a follow-up PR.

**Comment by aleksandra-tarkowska** [comment]
@dominikl no problem.

Anyone else has any comments? or is fine now?

**Comment by will-moore** [comment]
Fine by me

**Pull request merged**
