### PR TITLE
More gateway methods

### PR DESCRIPTION
**Pull request by dominikl**
Ongoing PR to add some more useful methods to the Gateway.
No particular test/review yet, just keep an eye on the integration tests to stay green.

### CODE REVIEW

**Comment by dominikl** [comment]
--exclude Has to be rebased after #4316 has been merged (conflict)

**Comment by joshmoore** [comment]
Worth discussing the general "OMERO.java gateway process" like https://trac.openmicroscopy.org/ome/ticket/4772 ?

**Comment by jburel** [comment]
@joshmoore, @dominikl: The approach taken is:
 * methods
 * tests
 * training
 * Documentation

Steps usually listed on cards. Happy to formalize that a bit more so we do not lose information or miss a step

**Comment by joshmoore** [comment]
@jburel : certainly sounds good. Guess I was also wondering: "under what conditions can a method signature change?" (never? if it does, what happens to the gateway version number, etc)

**Comment by jburel** [comment]
@dominikl: we should have a more generic method that just ```createDataset```

**Comment by jburel** [comment]
The default port should be set using ```omero.constants.GLACIER2PORT```.
to finish https://github.com/ome/minimal-omero-client/pull/10, I will need to adjust the login sequence.

**Comment by dominikl** [comment]
Closing in favor of  #4344 and #4347

**Pull request closed without merging**
