### PR TITLE
RobotFramework (Bug fix): Create Group And User.Check Admin Edit Self

### PR DESCRIPTION
**Pull request by bramalingam**
Check if the Integration tests pass.

### CODE REVIEW

**Comment by bramalingam** [comment]
@sbesson @will-moore : The integration tests seem to be passing? Is there anything else that needs checking here?

**Comment by sbesson** [comment]
@bramalingam: looks good thanks. Waiting for a few consecutive runs of the robot job to check the stability. We are also sorting out the merging workflow /cc @joshmoore @jburel

**Comment by will-moore** [comment]
@bramalingam Looks, good. Thanks

**Comment by bramalingam** [comment]
@sbesson, @jburel  : Any updates on this? I guess its been stable for the past couple of days.

**Comment by sbesson** [comment]
Given https://ci.openmicroscopy.org/view/Failing/job/OMERO-5.1-merge-robotframework/203/robot/Web%20&%20Web/Web_1/Webadmin%20Create%20Group%20And%20User/ and https://ci.openmicroscopy.org/view/Failing/job/OMERO-5.1-merge-robotframework/203/robot/Web%20&%20Web/Web/Webadmin%20Create%20Group%20And%20User/, merging this.

**Pull request merged**
