### PR TITLE
have C++ code use new graph requests

### PR DESCRIPTION
**Pull request by mtbc**
C++ tests run by CI should remain green.

*Update*: Also, now C++ standalone chgrp tool is updated. Just use plain typenames, no "/"-prefix.

--no-rebase

### CODE REVIEW

**Comment by sbesson** [comment]
From https://ci.openmicroscopy.org/view/Failing/job/OMERO-5.1-merge-cpp/label=gretzky35/379/console

```
06:14:48 /opt/hudson/workspace/OMERO-5.1-merge-cpp/src/components/tools/OmeroCpp/test/integration/delete.cpp:38: error: reference to 'LongList' is ambiguous
06:14:48 /opt/hudson/workspace/OMERO-5.1-merge-cpp/src/components/tools/OmeroCpp/cppbuild/components/tools/OmeroCpp/gen/omero/System.h:191: error: candidates are: typedef class std::vector<long int, std::allocator<long int> > omero::sys::LongList
06:14:48 /opt/hudson/workspace/OMERO-5.1-merge-cpp/src/components/tools/OmeroCpp/cppbuild/components/tools/OmeroCpp/gen/omero/Collections.h:78: error:                 typedef class std::vector<long int, std::allocator<long int> > omero::api::LongList
06:14:48 /opt/hudson/workspace/OMERO-5.1-merge-cpp/src/components/tools/OmeroCpp/test/integration/delete.cpp:38: error: reference to 'LongList' is ambiguous
06:14:48 /opt/hudson/workspace/OMERO-5.1-merge-cpp/src/components/tools/OmeroCpp/cppbuild/components/tools/OmeroCpp/gen/omero/System.h:191: error: candidates are: typedef class std::vector<long int, std::allocator<long int> > omero::sys::LongList
06:14:48 /opt/hudson/workspace/OMERO-5.1-merge-cpp/src/components/tools/OmeroCpp/cppbuild/components/tools/OmeroCpp/gen/omero/Collections.h:78: error:                 typedef class std::vector<long int, std::allocator<long int> > omero::api::LongList
06:14:48 /opt/hudson/workspace/OMERO-5.1-merge-cpp/src/components/tools/OmeroCpp/test/integration/delete.cpp:38: error: expected ';' before 'imageIds'
06:14:48 /opt/hudson/workspace/OMERO-5.1-merge-cpp/src/components/tools/OmeroCpp/test/integration/delete.cpp:42: error: 'imageIds' was not declared in this scope
06:14:54 gmake[2]: *** [components/tools/OmeroCpp/test/integration/CMakeFiles/integration.dir/delete.cpp.o] Error 1
06:14:54 gmake[2]: Leaving directory `/opt/hudson/workspace/OMERO-5.1-merge-cpp/src/components/tools/OmeroCpp/cppbuild'
06:14:54 gmake[1]: Leaving directory `/opt/hudson/workspace/OMERO-5.1-merge-cpp/src/components/tools/OmeroCpp/cppbuild'
06:14:54 gmake[1]: *** [components/tools/OmeroCpp/test/integration/CMakeFiles/integration.dir/all] Error 2
```

Excluding

**Comment by mtbc** [comment]
Gah, naturally, `./build.py build-all test-compile-all release-cpp` passes fine for me locally (gcc 4.9.1).

**Comment by mtbc** [comment]
Ah, some googling suggests that this is fixed in gcc 4.6, but,
```
mtbcarroll@gretzky:~$ g++ --version
g++ (Ubuntu 4.4.3-4ubuntu5.1) 4.4.3
```
Ouch.

**Comment by mtbc** [comment]
I'm not sure which machine I am meant to be looking at, so, for completeness:
```
[mtbcarroll@ome-ci-c6-05 ~]$ gcc --version
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-11)
```

**Comment by sbesson** [comment]
The latter system (`c6-05`) is the one that fails the build. Accordingly to our own internal [requirements](https://www.openmicroscopy.org/site/support/omero5.1/sysadmins/version-requirements.html#gcc), `gcc 4.4` is marked as deprecated on 5.1.x and dropped on 5.2.x. So I would vote for a workaround for the time being if this is not too time consuming and capture somewhere we should revert to your initial implementation on 5.2.x.

**Comment by mtbc** [comment]
Okay; created https://trello.com/c/192yknHq/474-revert-ancient-gcc-workaround. Please remove `exclude` and we'll try again.

**Comment by rleigh-dundee** [comment]
The code changes look OK, though I'm not very familiar with the graphs code.

Stylistically, are the command members intended to be directly modifiable i.e. `targetObjects`, `childOptions`, `groupId` etc. as opposed to be set through method calls?

Green in https://ci.openmicroscopy.org/job/OMERO-5.1-merge-cpp-cmake/280/ with passing chgrp tests, so looks like it should be good to merge.

**Comment by mtbc** [comment]
Stylistically: I was just following the pattern from the previous code. I have no idea what we usually do in C++ with these Ice-generated objects, but we usually directly modify them in Java and Python.

**Comment by joshmoore** [comment]
Comments made on the card made by @rleigh-dundee. Merging.

**Comment by mtbc** [comment]
(What card? Thanks for merging though!)

**Comment by joshmoore** [comment]
https://trello.com/c/Bdy4Wq8d/472-c-helpers-for-new-graph-requests

**Pull request merged**
