### PR TITLE
doc build cleanup

### PR DESCRIPTION
**Pull request by jburel**
# What this PR does
Clean up the ``rules.xml`` and unify with B-F sphinx command

# Testing this PR
Run the command ``ant release-docs`` or ``./build.py release-docs``
This will create a zip under ``target/docs``, unzip the result and check few files under ``api`` 

# Related reading
https://trello.com/c/SnUesylG/505-ditching-docs-pdfs

### CODE REVIEW

**Comment by sbesson** [comment]
@jburel is that effectively replacing https://github.com/openmicroscopy/openmicroscopy/blob/v5.3.0-m7/build.xml#L455 which is performing the zipping of the Javadoc HTML documentation?

**Comment by jburel** [comment]
We will remove the zipping step in ``rules`` and only keep the cleaning

**Comment by dominikl** [comment]
I guess it's not related to this PR, but I'm getting a `java.lang.NoClassDefFoundError`
```
BUILD FAILED
/Users/dlindner/Repositories/sccmerges/openmicroscopy/build.xml:55: java.lang.NoClassDefFoundError: org/apache/oro/text/regex/MalformedPatternException
	at org.apache.ivy.plugins.matcher.GlobPatternMatcher.newMatcher(GlobPatternMatcher.java:55)
	at org.apache.ivy.plugins.matcher.AbstractPatternMatcher.getMatcher(AbstractPatternMatcher.java:44)
...
```
I'm I missing something, outdated ant (1.9.4) maybe?

**Comment by mtbc** [comment]
Hope not, 1.9.4 isn't all that old!

**Comment by jburel** [comment]
Could you check if you can see ``oro`` in ``.m2/repository``

**Comment by dominikl** [comment]
I had a strange `oro` directory in my maven repo `.m2/repository//oro/oro` (double slash). Deleted it. But still same `NoClassDefFoundError`. However when I run `./build.py release-docs` the docs and zip file ~~(tested with scc's merge branch, which includes https://github.com/openmicroscopy/ome-documentation/pull/1601 )~~ are built like expected.

Update: As the last commit removes zipping, I'm actually a bit surprised about the zip file.

**Comment by jburel** [comment]
Which command did you use to trigger the error?

**Comment by dominikl** [comment]
Like the description says `ant release-docs`. I get the same error with other targets, too, eg. `ant clean`. Definitely a problem of my local ant. Have to pass on the PR review to someone else.

**Comment by jburel** [comment]
I used  ant version 1.9.4 and did not see the problem

**Comment by jburel** [comment]
@dominikl: clarification
``Update: As the last commit removes zipping, I'm actually a bit surprised about the zip file.
``

The last commit was removed since it was introducing another ``zip`` file. 
The initial full zip file with all the docs is kept

**Comment by jburel** [comment]
The diff I can see between the usage of  ``ant`` and ``build`` is ``versions.ant=1.8.0`` in ``omero.properties``

**Comment by will-moore** [comment]
Build works fine and the zip looks good. Good to merge.
```
$ ./build.py release-docs
...
release-docs:
Building zip: /Users/wmoore/Desktop/OMERO/openmicroscopy/target/OMERO.docs-5.3.0-m8-ice35-SNAPSHOT.zip

BUILD SUCCESSFUL
Total time: 14 minutes 49 seconds
```

**Pull request merged**
