### PR TITLE
adding login params for autologin

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
This PR should allow passing login parameters to auto login into Insight.

JNLP file now gets host port and session ID that is minimum to log in

```
<property name="jnlp.omero.host" value="trout...org"/>
<property name="jnlp.omero.port" value="4064"/>
<property name="jnlp.omero.sessionid" value="79e4596a-bb8c-470f-8e6a-47b91ed0c5ab"/>
<property name="jnlp.omero.web.host" value="http://omero.testdomain.com:4080/"/>
```

Note: Webstat page is also available when user is **not logged in**. In this case there will be default server host and port set and no sessionid provided. These parameters should be used as a helper to choose the right server from the list.

cc: @jburel @dominikl

### CODE REVIEW

**Comment by joshmoore** [comment]
In general, big :thumbsup: for this @aleksandra-tarkowska. The only caveat that *might* arise is the need for a static webstart page so that we can sign it: https://trello.com/c/4KjZpcX2/494-sign-webstart-jnlp-file

**Comment by aleksandra-tarkowska** [comment]
@joshmoore There is nothing stopping anyone from replacing ```omero.web.webstart_template``` as long as we have signed file and test it. First lets see if params works and Insight will be able to use them.

**Comment by joshmoore** [comment]
> First lets see if params works and Insight will be able to use them.

Makes sense! (Think the hope, though, is that *we* can provide a signed one, which is going to be tricky)

**Comment by dominikl** [comment]
SessionID is now included in the jnlp properties. Good to merge.

**Comment by joshmoore** [comment]
Can I propose we leave open until we have the two working together in case there is some back and forth?

**Comment by jburel** [comment]
corresponding insight PR https://github.com/openmicroscopy/openmicroscopy/pull/3820

**Comment by joshmoore** [comment]
```
./components/tools/OmeroWeb/omeroweb/webstart/views.py:43:1: E302 expected 2 blank lines, found 1
./components/tools/OmeroWeb/omeroweb/webstart/views.py:82:1: E303 too many blank lines (3)
./components/tools/OmeroWeb/omeroweb/webstart/views.py:134:1: E302 expected 2 blank lines, found 0
```

**Comment by joshmoore** [comment]
Assuming that all testing for this PR was commented under https://github.com/openmicroscopy/openmicroscopy/pull/3820, merging.

**Pull request merged**
