### PR TITLE
Filter images by name only

### PR DESCRIPTION
**Pull request by will-moore**
This fixes the filtering of images by name, as reported by @pwalczysko: https://github.com/openmicroscopy/openmicroscopy/pull/4694#issuecomment-251083417

To test:
- Filter images in a Dataset using the filter input above thumbnails.
- If any characters are entered that are not in the image's name, that image should be filtered out.

### CODE REVIEW

**Comment by pwalczysko** [comment]
Works as expected. Ready to merge.

**Comment by jburel** [comment]
with various "filtering" changes, we should start a new series of "filtering" robot tests.
Could you add one to this PR?

**Comment by will-moore** [comment]
Tricky to add a Robot test to this PR, since without https://github.com/openmicroscopy/openmicroscopy/pull/4694 the filtering behaviour is changed. So any test I add to this PR would fail when merged with https://github.com/openmicroscopy/openmicroscopy/pull/4694.

However, if this PR was merged in, I could add Robot filtering tests to https://github.com/openmicroscopy/openmicroscopy/pull/4694 or a subsequent PR (or vice versa: merge https://github.com/openmicroscopy/openmicroscopy/pull/4694 and add tests to this PR).

**Comment by jburel** [comment]
@will-moore: understood

**Pull request merged**
