### PR TITLE
Remove deprecated setRoot(Object)

### PR DESCRIPTION
**Pull request by melissalinkert**
See https://trello.com/c/iNieNBuZ/77-remove-deprecated-methods.

--depends-on openmicroscopy/bioformats#1562

### CODE REVIEW

**Comment by rleigh-dundee** [comment]
This removal looks fine.  Please merge if green.

**Comment by sbesson** [comment]
Is the failure in https://ci.openmicroscopy.org/view/Failing/job/OMERO-5.1-breaking-build/ICE=3.4,jdk=7_LATEST,label=trout/270/ related to this PR?

**Comment by rleigh-dundee** [comment]
@sbesson I can't be sure, but I suspect it's unlikely.  If these removed methods were problematic, it should have failed to build rather than having a problem at the deployment stage.

**Comment by sbesson** [comment]
All tests are green. Merging this and the companion PR.

**Comment by melissalinkert** [comment]
--no-rebase

**Pull request merged**
