### PR TITLE
Webclient flake8 views

### PR DESCRIPTION
**Pull request by sbesson**
See https://trello.com/c/HP5YepWx/324-flake8-extension

Fixes `webclient.views` to be `flake8` compliant. Due to the large set of changes and the GitHub limits, this PR is split into small commits for reviewing ease.

--no-rebase

### CODE REVIEW

**Comment by joshmoore** [comment]
Currently reading through `git log -w --color-words -p v5.1.0..seb/webclient_flake8_views`. Haven't found any issues yet.

**Comment by joshmoore** [comment]
Finished reading. As always with these, it's hard to guarantee anything, but nothing seemed amiss.

**Comment by sbesson** [comment]
@will-moore: have you had time to review this?

**Comment by will-moore** [comment]
@sbesson - Sorry, I haven't looked at this yet and I'm away this week.

**Comment by aleksandra-tarkowska** [comment]
Delete works as expected:

firefoxscreensnapz028

**Comment by aleksandra-tarkowska** [comment]
I think we are good to go with that

**Comment by aleksandra-tarkowska** [comment]
@pwalczysko this PR might be something to consider when you will be doing final testing week, especially activity

**Comment by sbesson** [comment]
After another review, the activities section discussed above should be the only place where changes which are not strictly formatting modifications.

**Comment by jburel** [comment]
A last round of manual testing of the "Activity section" to be completed tomorrow 
since the automatic testing is limited. This won't be merged today
cc @aleksandra-tarkowska

**Comment by pwalczysko** [comment]
Activities window with scripts - BUG

  1. Missing ``info`` button - see successful run of the script ``Batch image eport`` on the same images on merge and latest trout

trout merge
screen shot 2015-04-08 at 14 54 05

trout latest
screen shot 2015-04-08 at 14 55 33

**Comment by pwalczysko** [comment]
Activities window with scripts - BUG:
2. Text in the activity is missing as in the https://github.com/openmicroscopy/openmicroscopy/pull/3674#issuecomment-90924106 as well as in more important case of Big image, see below

trout merge
screen shot 2015-04-08 at 14 42 58


trout latest

screen shot 2015-04-08 at 14 42 30

**Comment by sbesson** [comment]
@pwalczysko: thanks for the testing. Commit e0f0f9a744ab519f379acb5363fee54513b16c6b should fix the script message display in the activities panel.

**Comment by pwalczysko** [comment]
Same situation as with scripts is with send email.

trout merge
screen shot 2015-04-08 at 15 45 13
trout latest

screen shot 2015-04-08 at 15 44 52

**Comment by pwalczysko** [comment]
Email activities window - works as expected now.

**Comment by aleksandra-tarkowska** [comment]
@pwalczysko did you have a chance to look at that?

**Comment by pwalczysko** [comment]
Batch image export script message in activities - works as expected.

**Comment by pwalczysko** [comment]
All looks fine here by me.

**Comment by jburel** [comment]
Thanks all Merging so we can move forward.

**Comment by aleksandra-tarkowska** [comment]
Thank you for helping. I will rebase tomorrow

**Comment by will-moore** [comment]
Turns out that 
```
if pt.__class__ == type(True):
```
is not the same as
```
if isinstance(pt.__class__, bool):
```

It needs to be:
```
if isinstance(pt, bool):
```

Fixed in https://github.com/openmicroscopy/openmicroscopy/pull/3801

**Pull request merged**
