### PR TITLE
Download original files

### PR DESCRIPTION
**Pull request by dominikl**
There were several issues with the Download dialog, e. g. it claimed you could modify the name but didn't use the modified name ([Ticket 12784](https://trac.openmicroscopy.org.uk/ome/ticket/12784)), if multiple images were selected the first image was zipped but not the other ones, etc. With this PR the file(s) will always be zipped (name of zip file can be modified), and it also unifies the dialog when invoked from different places (Metadata panel, treeviewer, etc.). Also fixes an issue with download of file annotations from the tree viewer (previously it picked the destination folder name as file name).
Test:
- Check that download of original images (with single and multiple selection) works, initiated from all possible places (left hand side tree viewer, central data browser and right hand side metadata panel)
- Check that the download of file annotations works, from metadata panel and tree viewer (tab "Attachments", check single and multi selection)

--no-rebase

### CODE REVIEW

**Comment by pwalczysko** [comment]
On the first download I am getting
```
java.lang.Exception: java.lang.Exception: org.openmicroscopy.shoola.env.data.DSAccessException: Cannot retrieve original file
	at org.openmicroscopy.shoola.env.data.views.calls.ArchivedImageLoader$1.doCall(ArchivedImageLoader.java:160)
	at org.openmicroscopy.shoola.env.data.views.BatchCall.doStep(BatchCall.java:144)
	at org.openmicroscopy.shoola.util.concur.tasks.CompositeTask.doStep(CompositeTask.java:226)
	at org.openmicroscopy.shoola.env.data.views.CompositeBatchCall.doStep(CompositeBatchCall.java:126)
	at org.openmicroscopy.shoola.util.concur.tasks.ExecCommand.exec(ExecCommand.java:165)
	at org.openmicroscopy.shoola.util.concur.tasks.ExecCommand.run(ExecCommand.java:276)
	at org.openmicroscopy.shoola.util.concur.tasks.AsyncProcessor$Runner.run(AsyncProcessor.java:91)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.openmicroscopy.shoola.env.data.DSAccessException: Cannot retrieve original file
	at org.openmicroscopy.shoola.env.data.OMEROGateway.retrieveArchivedFiles(OMEROGateway.java:3791)
	at org.openmicroscopy.shoola.env.data.OMEROGateway.getArchivedFiles(OMEROGateway.java:3744)
	at org.openmicroscopy.shoola.env.data.OmeroDataServiceImpl.getArchivedImage(OmeroDataServiceImpl.java:511)
	at org.openmicroscopy.shoola.env.data.views.calls.ArchivedImageLoader$1.doCall(ArchivedImageLoader.java:138)
	... 7 more
Caused by: omero.InternalException
    serverStackTrace = "ome.conditions.InternalException:  Wrapped Exception: (org.springframework.orm.hibernate3.HibernateSystemException):
                        failed to lazily initialize a collection, no session or session was closed; nested exception is org.hibernate.LazyInitializationException: failed to lazily initialize a collection, no session or session was closed
                        	at org.springframework.orm.hibernate3.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:679)
                        	at org.springframework.orm.hibernate3.HibernateAccessor.convertHibernateAccessException(HibernateAccessor.java:412)
                        	at org.springframework.orm.hibernate3.HibernateTemplate.doExecute(HibernateTemplate.java:411)
                        	at org.springframework.orm.hibernate3.HibernateTemplate.execute(HibernateTemplate.java:339)
                        	at ome.logic.QueryImpl.execute(QueryImpl.java:144)
                        	at ome.logic.QueryImpl.findAllByQuery(QueryImpl.java:394)
                        	at sun.reflect.GeneratedMethodAccessor688.invoke(Unknown Source)
                        	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                        	at java.lang.reflect.Method.invoke(Method.java:606)
                        	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:307)
                        	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
                        	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
                        	at ome.security.basic.EventHandler.invoke(EventHandler.java:154)
                        	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
                        	at org.springframework.orm.hibernate3.HibernateInterceptor.invoke(HibernateInterceptor.java:111)
                        	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
                        	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:108)
                        	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
                        	at ome.tools.hibernate.ProxyCleanupFilter$Interceptor.invoke(ProxyCleanupFilter.java:249)
                        	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
                        	at ome.services.util.ServiceHandler.invoke(ServiceHandler.java:116)
                        	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
                        	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
                        	at com.sun.proxy.$Proxy80.findAllByQuery(Unknown Source)
                        	at sun.reflect.GeneratedMethodAccessor688.invoke(Unknown Source)
                        	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                        	at java.lang.reflect.Method.invoke(Method.java:606)
                        	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:307)
                        	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
                        	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
                        	at ome.security.basic.BasicSecurityWiring.invoke(BasicSecurityWiring.java:98)
                        	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
                        	at ome.services.blitz.fire.AopContextInitializer.invoke(AopContextInitializer.java:43)
                        	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
                        	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
                        	at com.sun.proxy.$Proxy80.findAllByQuery(Unknown Source)
                        	at sun.reflect.GeneratedMethodAccessor937.invoke(Unknown Source)
                        	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                        	at java.lang.reflect.Method.invoke(Method.java:606)
                        	at ome.services.blitz.util.IceMethodInvoker.invoke(IceMethodInvoker.java:179)
                        	at ome.services.throttling.Callback.run(Callback.java:56)
                        	at ome.services.throttling.InThreadThrottlingStrategy.callInvokerOnRawArgs(InThreadThrottlingStrategy.java:56)
                        	at ome.services.blitz.impl.AbstractAmdServant.callInvokerOnRawArgs(AbstractAmdServant.java:149)
                        	at ome.services.blitz.impl.QueryI.findAllByQuery_async(QueryI.java:66)
                        	at sun.reflect.GeneratedMethodAccessor936.invoke(Unknown Source)
                        	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                        	at java.lang.reflect.Method.invoke(Method.java:606)
                        	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:307)
                        	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
                        	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
                        	at omero.cmd.CallContext.invoke(CallContext.java:78)
                        	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
                        	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
                        	at com.sun.proxy.$Proxy81.findAllByQuery_async(Unknown Source)
                        	at omero.api._IQueryTie.findAllByQuery_async(_IQueryTie.java:101)
                        	at omero.api._IQueryDisp.___findAllByQuery(_IQueryDisp.java:378)
                        	at omero.api._IQueryDisp.__dispatch(_IQueryDisp.java:508)
                        	at IceInternal.Incoming.invoke(Incoming.java:159)
                        	at Ice.ConnectionI.invokeAll(ConnectionI.java:2357)
                        	at Ice.ConnectionI.dispatch(ConnectionI.java:1208)
                        	at Ice.ConnectionI.message(ConnectionI.java:1163)
                        	at IceInternal.ThreadPool.run(ThreadPool.java:302)
                        	at IceInternal.ThreadPool.access$300(ThreadPool.java:12)
                        	at IceInternal.ThreadPool$EventHandlerThread.run(ThreadPool.java:643)
                        	at java.lang.Thread.run(Thread.java:744)
                        "
    serverExceptionClass = "ome.conditions.InternalException"
    message = " Wrapped Exception: (org.springframework.orm.hibernate3.HibernateSystemException):
               failed to lazily initialize a collection, no session or session was closed; nested exception is org.hibernate.LazyInitializationException: failed to lazily initialize a collection, no session or session was closed"
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at java.lang.Class.newInstance(Class.java:438)
	at IceInternal.BasicStream.createUserException(BasicStream.java:2615)
	at IceInternal.BasicStream.access$300(BasicStream.java:12)
	at IceInternal.BasicStream$EncapsDecoder10.throwException(BasicStream.java:3099)
	at IceInternal.BasicStream.throwException(BasicStream.java:2077)
	at IceInternal.Outgoing.throwUserException(Outgoing.java:538)
	at omero.api._IQueryDelM.findAllByQuery(_IQueryDelM.java:276)
	at omero.api.IQueryPrxHelper.findAllByQuery(IQueryPrxHelper.java:769)
	at omero.api.IQueryPrxHelper.findAllByQuery(IQueryPrxHelper.java:741)
	at org.openmicroscopy.shoola.env.data.OMEROGateway.retrieveArchivedFiles(OMEROGateway.java:3788)
	... 10 more

	at org.openmicroscopy.shoola.env.ui.UserNotifierImpl.showErrorDialog(UserNotifierImpl.java:191)
	at org.openmicroscopy.shoola.env.ui.UserNotifierImpl.notifyError(UserNotifierImpl.java:291)
	at org.openmicroscopy.shoola.env.ui.UserNotifierImpl.notifyError(UserNotifierImpl.java:259)
	at org.openmicroscopy.shoola.env.ui.ActivityComponent.showException(ActivityComponent.java:413)
	at org.openmicroscopy.shoola.env.ui.ActivityComponent.actionPerformed(ActivityComponent.java:934)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3322)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2739)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by pwalczysko** [comment]
Bug: Select several images in a dv folder, one dv and 2 results of scripts (= multiselection of 3 images). Tried to download all 3 in one go.
Result: In the resulting .zip, there is just the first dv, not the other 2 images (= this was not fully fixed)

**Comment by pwalczysko** [comment]
When dv files are multiselected and downloaded in one go, it works as expected using the Metdata panel icon, I can also choose the name of the zip as expected.

**Comment by pwalczysko** [comment]
Multi-selection download from the central pane and tree works as expected when selecting ``dv`` files.

**Comment by pwalczysko** [comment]
In summary, all works here as expected except the Bug https://github.com/openmicroscopy/openmicroscopy/pull/3613#issuecomment-78902276. To repeat the bug, select a MIF image and download (lei). Possibly the bug is not caused by this PR but please consult @sbesson @joshmoore .

**Comment by dominikl** [comment]
I don't think this is related to this PR. Is it possible that there's something wrong with that particular dataset (user-4, 5.0 data)?

**Comment by sbesson** [comment]
No the error above is server-side. A rebuild will happen over lunch which should correct that.

**Comment by dominikl** [comment]
Thanks. Yes, now after the rebuild it works, can't see the exception anymore. So I think this can merged or want to test again @pwalczysko ?

**Comment by pwalczysko** [comment]
I am just trying to retest, it looks good and goes on, but needs some 3 more minutes for full satisfaction.

**Comment by pwalczysko** [comment]
All there. All correctly downloaded. ready to merge

**Pull request merged**
