### PR TITLE
Handle deleted images in shares

### PR DESCRIPTION
**Pull request by will-moore**
See: https://trac.openmicroscopy.org.uk/ome/ticket/12842
Handle deleted images in shares.

To test:
 - Put some images in a share
 - Delete one of them
 - Browse the share
 - Share should load and display all other images OK
 - Should see "Object deleted" in tree and placeholder thumbnail.

### CODE REVIEW

**Comment by pwalczysko** [comment]
Works as expected. Nice solution. Fixed also older, broken shares. Ready to merge.

**Comment by sbesson** [comment]
@will-moore: can you create a card reminding ourselves to add an integration/robot test for this scenario for 5.1.2?

**Comment by will-moore** [comment]
@sbesson Added to https://trello.com/c/ScEErwT9/222-5-1-2-follow-up

**Comment by sbesson** [comment]
Thanks. Merging.

**Pull request merged**
