### PR TITLE
Imagej roi

### PR DESCRIPTION
**Pull request by jburel**
Turn off the measurement tool when insight is used as a plugin.
Having it on leads to issue when the plugin is used in Fiji

To test:
 * add the insight-ij plugin to the plugin folder of imageJ and Fiji
 * Check that you cannot access the measurement tool.

### CODE REVIEW

**Comment by jburel** [comment]
Travis restarted. Now green

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#1052](https://ci.openmicroscopy.org/job/OME-5.1-merge-push/1052/). See the [console output](https://ci.openmicroscopy.org/job/OME-5.1-merge-push/1052/consoleText) for more details.
Possible conflicts:
  - PR #3859 jburel 'Viewer script'
    - components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ToolBar.java

**Comment by pwalczysko** [comment]
Works as expected. Both Fiji and ImageJ. Ready to merge.

**Comment by jburel** [comment]
@gusferguson: This won't require any screenshots update. Maybe mention some functionalities are not accessible when used as a plugin.

**Comment by gusferguson** [comment]
@jburel - thanks - will look at where to put it.

**Pull request merged**
