### PR TITLE
bulk import improvements (rebased from metadata52)

### PR DESCRIPTION
**Pull request by mtbc**
--rebased-from #4614 opened by @joshmoore

This PR migrates functionality from the https://github.com/IDR/idr-metadata/blob/0.0.4/screen_import.py file as well as the "mini-idr-setup-2.sh" script into bin/omero import.

New functionality includes:

*    ---bulk (Python): allow driving import via YAML files
  *        path and columns: allow for importing from tsv, csv, or txt files.
  *        include: allows for importing a relative path for shared variables
  *        continue: passes the -c flag to continue on errors
  *        dry_run: print commands rather than execute them
  *        other parameters match existing parameters, e.g. name, target, etc.
*    --output=yaml (Java) for more modern stdout

Other changes include:

*    breaking: make -f fail when no candidates are found
*    --logprefix (Python): allows prefixing the values of ---file and ---err
*    --logback (Python): for passing a logging file
*    begin exposing advanced arguments in Python (e.g. transfer, exclude)
*    deprecate underscore arguments (Java): e.g. auto_close
*    deprecate --- arguments (Python): e.g. ---file

Note: this requires installing PyYAML which should be discussed project-wide.

----

Known issues:
 * [ ]  `omero import --bulk idr0011-screenA-bulk.yml  --java-help`
 * [ ] error handling when the number of columns in yml does not match those in tsv
 * [ ] `dry-run` should be settable from the command-line
 * [ ] Generation of scripts should be possible without `omero import --bulk idr0011-screenA-bulk.yml | parallel echo omero import {} \> A\$\(printf "%03d" {#}\).sh`

### CODE REVIEW

**Comment by mtbc** [comment]
Can reopen once import options issue is addressed.

**Comment by joshmoore** [comment]
Backporting last commits to https://github.com/openmicroscopy/openmicroscopy/pull/4756

**Comment by joshmoore** [comment]
@mtbc : can you cherry-pick https://github.com/openmicroscopy/openmicroscopy/pull/4756/commits/6c66d8bf8eb690297868bdb95826765a1e305201 ?

**Comment by mtbc** [comment]
Sure.

**Comment by mtbc** [comment]
Travis, *sigh*.

**Comment by joshmoore** [comment]
And https://github.com/openmicroscopy/openmicroscopy/pull/4756/commits/53decfe9516824ef790103eb48625f318d95b518 as well. (Sorry, I didn't get that in in time for your travis fun!)

**Comment by joshmoore** [comment]
(Hopefully) Last commit https://github.com/openmicroscopy/openmicroscopy/pull/4756/commits/20fee34bff0f53edc9f06904dfd01bfd61ea5c4f pushed

**Comment by ximenesuk** [comment]
I've used this a fair bit while chasing 7 wild geese (though I have not tested it completely I expect), it has been used for IDR, it has been on breaking and the tests are passing. In light of you being away @joshmoore is it worth merging this now and addressing the identified issues later? This would allow a couple of my import/cli PRs to move ahead as they currently conflict with the work here.

**Comment by joshmoore** [comment]
No objections from me. As long as we come back to the "known issues" from the description (basically hardening this for release), I think this will be valuable as it stands.

**Comment by ximenesuk** [comment]
I'm also happy to look at the current known issues as I work on other import work.

**Comment by ximenesuk** [comment]
@sbesson @jburel Could this please be merged?

**Comment by jburel** [comment]
@ximenesuk: are the "known issues" listed on a card?

**Comment by ximenesuk** [comment]
@jburel I can't find one - @joshmoore added the issues - I can copy to a card.

**Comment by jburel** [comment]
Thanks for adding to a card.
Merging

**Comment by ximenesuk** [comment]
See: https://trello.com/c/OuWkxqzz/103-bulk-import-issues

**Pull request merged**
