### PR TITLE
Improve web deploy

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
Test nginx (no webserver needed)
```
$ dist/bin/omero web restart
Stopping OMERO.web... [NOT STARTED]
Post-processed 'omeroweb.viewer.min.css' as 'omeroweb.viewer.min.css'
Post-processed 'omeroweb.viewer.min.js' as 'omeroweb.viewer.min.js'

0 static files copied to '/Users/ola/OMERO/openmicroscopy/dist/lib/python/omeroweb/static', 618 unmodified, 2 post-processed.
Clearing expired sessions. This may take some time... [OK]
Starting OMERO.web... [OK]
```

Open localhost:4080 (you won't see statics)

```
$ dist/bin/omero web status
OMERO.web status... [RUNNING] (PID 7272)

$ cat dist/var/django.pid 
7272

$ dist/bin/omero web start
Post-processed 'omeroweb.viewer.min.css' as 'omeroweb.viewer.min.css'
Post-processed 'omeroweb.viewer.min.js' as 'omeroweb.viewer.min.js'

0 static files copied to '/Users/ola/OMERO/openmicroscopy/dist/lib/python/omeroweb/static', 618 unmodified, 2 post-processed.
Clearing expired sessions. This may take some time... [OK]
Starting OMERO.web... [FAILED] OMERO.web already started. /Users/ola/OMERO/openmicroscopy/dist/var/django.pid exists (PID: 7272)! Use 'web stop or restart' first.

$ dist/bin/omero web status
OMERO.web status... [RUNNING] (PID 7272)

$ cat dist/var/django.pid 
7272

$ dist/bin/omero web stop
Stopping OMERO.web... [OK]
OMERO.web WSGI workers (PID 7272) killed.
Removed stale /Users/ola/OMERO/openmicroscopy/dist/var/django.pid

$ dist/bin/omero web status
OMERO.web status... [NOT STARTED]

$ dist/bin/omero web stop
Stopping OMERO.web... [NOT STARTED]
```

test bad behavior, wait few sec between steps to make s

```
$ dist/bin/omero web start
Post-processed 'omeroweb.viewer.min.css' as 'omeroweb.viewer.min.css'
Post-processed 'omeroweb.viewer.min.js' as 'omeroweb.viewer.min.js'

0 static files copied to '/Users/ola/OMERO/openmicroscopy/dist/lib/python/omeroweb/static', 618 unmodified, 2 post-processed.
Clearing expired sessions. This may take some time... [OK]
Starting OMERO.web... [OK]
```

LOG IN TO WEB localhost:4080 (you won't see statics)

```
$ dist/bin/omero web status
OMERO.web status... [RUNNING] (PID 7439)

$ cat dist/var/django.pid 
7439

$ rm -f dist/var/django.pid

$ dist/bin/omero web start
Post-processed 'omeroweb.viewer.min.css' as 'omeroweb.viewer.min.css'
Post-processed 'omeroweb.viewer.min.js' as 'omeroweb.viewer.min.js'

0 static files copied to '/Users/ola/OMERO/openmicroscopy/dist/lib/python/omeroweb/static', 618 unmodified, 2 post-processed.
Clearing expired sessions. This may take some time... [OK]
Starting OMERO.web... [OK]
```

By that time it is unknown that there are any stale processes running
REFRESH WEB

```
$ cat dist/var/django.pid 
7484 <- PID will be different

$ dist/bin/omero web status
OMERO.web status... [ERROR] OMERO.web workers (PID 7484) - no such process. Use `ps aux| grep /Users/ola/OMERO/openmicroscopy/dist/var/django.pid` and kill stale processes by hand. 
[NOT STARTED]
```

```
$ dist/bin/omero web stop
Stopping OMERO.web... [ERROR] OMERO.web workers (PID 7484) - no such process. Use `ps aux| grep /Users/ola/OMERO/openmicroscopy/dist/var/django.pid` and kill stale processes by hand. 
Removed stale /Users/ola/OMERO/openmicroscopy/dist/var/django.pid
```
If you run restart instead you will get the same error:

```
$ dist/bin/omero web restart
Stopping OMERO.web... [NOT STARTED]
Post-processed 'omeroweb.viewer.min.css' as 'omeroweb.viewer.min.css'
Post-processed 'omeroweb.viewer.min.js' as 'omeroweb.viewer.min.js'

0 static files copied to '/Users/ola/OMERO/openmicroscopy/dist/lib/python/omeroweb/static', 618 unmodified, 2 post-processed.
Clearing expired sessions. This may take some time... [OK]
Starting OMERO.web... [OK]

```

```
 $ dist/bin/omero web status
OMERO.web status... [ERROR] OMERO.web workers (PID 3319) - no such process. Use `ps aux| grep /Users/ola/OMERO/openmicroscopy/dist/var/django.pid` and kill stale processes by hand. 
```
-----------------------

Test apache  (no webserver needed)

```
$ dist/bin/omero config set omero.web.application_server wsgi
$ dist/bin/omero web start
Post-processed 'omeroweb.viewer.min.css' as 'omeroweb.viewer.min.css'
Post-processed 'omeroweb.viewer.min.js' as 'omeroweb.viewer.min.js'

0 static files copied to '/Users/ola/OMERO/openmicroscopy/dist/lib/python/omeroweb/static', 618 unmodified, 2 post-processed.
Clearing expired sessions. This may take some time... [OK]
You are deploying OMERO.web using apache and mod_wsgi. Add config to Apache and reload.

$ ps aux| grep /Users/ola/OMERO/openmicroscopy/dist/var/django.pid
ola             7636   0.0  0.0  2432768    648 s000  R+   10:59am   0:00.00 grep /Users/ola/OMERO/openmicroscopy/dist/var/django.pid

$ dist/bin/omero web status
OMERO.web status... You are deploying OMERO.web using apache and mod_wsgi. Cannot check status.

$ dist/bin/omero web stop
Stopping OMERO.web... You are deploying OMERO.web using apache and mod_wsgi. Cannot check status.
```

### CODE REVIEW

**Comment by sbesson** [comment]
With the last state of this PR, the web restart command was broken for me locally:

```
sbesson@lifesci-37398:OMERO.server-5.2.0-rc1-30-f150c98-ice35-b138 $ bin/omero web start
Post-processed 'omeroweb.viewer.min.css' as 'omeroweb.viewer.min.css'
Post-processed 'omeroweb.viewer.min.js' as 'omeroweb.viewer.min.js'

0 static files copied to '/Users/sbesson/Downloads/OMERO.server-5.2.0-rc1-30-f150c98-ice35-b138/lib/python/omeroweb/static', 618 unmodified, 2 post-processed.
Clearing expired sessions. This may take some time... [OK]
Starting OMERO.web... [OK]
sbesson@lifesci-37398:OMERO.server-5.2.0-rc1-30-f150c98-ice35-b138 $ bin/omero web restart
Stopping OMERO.web... [OK]
OMERO.web WSGI workers (PID 22978) killed.
Removed stale /Users/sbesson/Downloads/OMERO.server-5.2.0-rc1-30-f150c98-ice35-b138/var/django.pid
sbesson@lifesci-37398:OMERO.server-5.2.0-rc1-30-f150c98-ice35-b138 $ 
```

**Comment by jburel** [comment]
Excluding for this afternoon build.

**Comment by aleksandra-tarkowska** [comment]
@sbesson restart should be fixed now. Description updated accordingly.

**Comment by will-moore** [comment]
```
$ dist/bin/omero web restart
Stopping OMERO.web... [NOT STARTED]
INFO:__main__:Application Starting...
INFO:root:Processing custom settings for module omeroweb.settings
...
DEBUG:omeroweb.settings:INSTALLED_APPS=[('django.contrib.staticfiles', 'django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.sessions', 'django.contrib.sites', 'omeroweb.feedback', 'omeroweb.webadmin', 'omeroweb.webclient', 'omeroweb.webgateway', 'omeroweb.webredirect', 'pipeline', u'figure', u'autotag')]
[OK]
Starting OMERO.web... [OK]
```

```
$  dist/bin/omero web status
OMERO.web status... [RUNNING] (PID 23583)

$ cat dist/var/django.pid 
23583

$ dist/bin/omero web start
INFO:__main__:Application Starting...
INFO:root:Processing custom settings for module omeroweb.settings
INFO:root:Processing custom settings for module omeroweb.settings
...
INFO:root:Processing custom settings for module autotag.settings
DEBUG:omeroweb.settings:INSTALLED_APPS=[('django.contrib.staticfiles', 'django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.sessions', 'django.contrib.sites', 'omeroweb.feedback', 'omeroweb.webadmin', 'omeroweb.webclient', 'omeroweb.webgateway', 'omeroweb.webredirect', 'pipeline', u'figure', u'autotag')]
[OK]
Starting OMERO.web... [FAILED] OMERO.web already started. /Users/wmoore/Desktop/OMERO/dist/var/django.pid exists (PID: 23583)! Use 'web stop or restart' first.

$ dist/bin/omero web stop
Stopping OMERO.web... [OK]
OMERO.web WSGI workers (PID 23583) killed.
Removed stale /Users/wmoore/Desktop/OMERO/dist/var/django.pid

$ dist/bin/omero web status
OMERO.web status... [NOT STARTED]

$ dist/bin/omero web stop
Stopping OMERO.web... [NOT STARTED]
```

At localhost:4080 I don't see statics (with ```omero.web.config debug False```)

```
$ dist/bin/omero web status
OMERO.web status... [RUNNING] (PID 23820)

$ cat dist/var/django.pid 
23820

$ rm -f dist/var/django.pid

$ dist/bin/omero web start
Post-processed 'omeroweb.viewer.min.css' as 'omeroweb.viewer.min.css'
Post-processed 'omeroweb.viewer.min.js' as 'omeroweb.viewer.min.js'

0 static files copied to '/Users/wmoore/Desktop/OMERO/dist/lib/python/omeroweb/static', 719 unmodified, 2 post-processed.
Clearing expired sessions. This may take some time... [OK]
Starting OMERO.web... [OK]

$ cat dist/var/django.pid 
23980    # different!

$ dist/bin/omero web status
OMERO.web status... [ERROR] OMERO.web workers (PID 23980) - no such process. Use `ps aux| grep /Users/wmoore/Desktop/OMERO/dist/var/django.pid` and kill stale processes by hand. 
[NOT STARTED]

$ dist/bin/omero web stop
Stopping OMERO.web... [ERROR] OMERO.web workers (PID 23980) - no such process. Use `ps aux| grep /Users/wmoore/Desktop/OMERO/dist/var/django.pid` and kill stale processes by hand. 
Removed stale /Users/wmoore/Desktop/OMERO/dist/var/django.pid
```

**Comment by will-moore** [comment]
Apache:
```
$ dist/bin/omero config set omero.web.application_server wsgi

$ dist/bin/omero web start
Post-processed 'omeroweb.viewer.min.css' as 'omeroweb.viewer.min.css'
Post-processed 'omeroweb.viewer.min.js' as 'omeroweb.viewer.min.js'

0 static files copied to '/Users/wmoore/Desktop/OMERO/dist/lib/python/omeroweb/static', 719 unmodified, 2 post-processed.
Clearing expired sessions. This may take some time... [OK]
You are deploying OMERO.web using apache and mod_wsgi. Generate apache config using 'omero web config apache' and reload web server.

$ ps aux| grep /Users/ola/OMERO/openmicroscopy/dist/var/django.pid
wmoore         24515   0.4  0.0  2423356    188 s000  R+   11:04am   0:00.00 grep /Users/ola/OMERO/openmicroscopy/dist/var/django.pid

$ dist/bin/omero web status
OMERO.web status... You are deploying OMERO.web using apache and mod_wsgi. Cannot check status.

$ dist/bin/omero web stop
Stopping OMERO.web... You are deploying OMERO.web using apache and mod_wsgi. Cannot check status.
```

**Comment by will-moore** [comment]
As far as I can see, my outputs matched the (edited) outputs in the description.
Assuming there is nothing else to test, this is good to merge.

**Comment by aleksandra-tarkowska** [comment]
@sbesson would you like to get a final go?

**Comment by aleksandra-tarkowska** [comment]
@joshmoore @sbesson anything else needed here?

**Comment by joshmoore** [comment]
Shall we give this a go through the omero-install infrastructure? That would likely require the use of `omerodev.sh`.

**Comment by sbesson** [comment]
Generally works for me. We might want to (re)test this PR within the context of the deployment effort of 5.2.1, i.e. having a minimal Web start/stop scenarios that could be tested in various containers with different web servers.

**Comment by joshmoore** [comment]
@sbesson / @manics : there's currently no "stop" or "shutdown" phase of the omero-install testing, though, right?

**Comment by sbesson** [comment]
@joshmoore: no that I know of although adding a `restart` for both server and web might be a not too expensive feature that would help here?

**Comment by aleksandra-tarkowska** [comment]
Ok let me write some unit test for that. That shouldn't be hard

**Comment by aleksandra-tarkowska** [comment]
@joshmoore @sbesson is that intentional that ``self.ctx.die`` doesn't return 1?
```
target/omero/cli.py:949: in invoke
    self.assertRC()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <omero.cli.CLI instance at 0x10bfa3290>

    def assertRC(self):
        if self.rv != 0:
>           raise NonZeroReturnCode(self.rv, "assert failed")
E           NonZeroReturnCode: assert failed

target/omero/cli.py:938: NonZeroReturnCode
```

**Comment by aleksandra-tarkowska** [comment]
@joshmoore @sbesson is that intentional when calling ``self.ctx.die``? Could I assert error code?
```
target/omero/cli.py:949: in invoke
    self.assertRC()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <omero.cli.CLI instance at 0x10bfa3290>

    def assertRC(self):
        if self.rv != 0:
>           raise NonZeroReturnCode(self.rv, "assert failed")
E           NonZeroReturnCode: assert failed

target/omero/cli.py:938: NonZeroReturnCode
```

I am still getting output message on Captured stderr call.

**Comment by joshmoore** [comment]
Passing `strict=True` in `testWebRestart` throws the `NonZeroReturnCode`. If you change it to `False`, you can check the `rv` yourself.

**Comment by aleksandra-tarkowska** [comment]
thanks @joshmoore, web start/stop/restart should be covered now in tests

**Comment by joshmoore** [comment]
https://ci.openmicroscopy.org/job/OMERO-DEV-merge-integration-python/139/ is green.

**Comment by sbesson** [comment]
:+1:

**Comment by jburel** [comment]
Added https://trello.com/c/BEZfkJsj/78-improve-web-deploy so we can follow that up in omero-install

**Pull request merged**
