### PR TITLE
test: api_error

### PR DESCRIPTION
**Pull request by jburel**
use native_str

Fix tests like

* https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/219/testReport/junit/OmeroWeb.test.integration.test_api_errors/TestErrors/test_security_violation/
* https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/219/testReport/junit/OmeroWeb.test.integration.test_api_projects/TestProjects/test_project_update/
* https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/lastCompletedBuild/testReport/OmeroWeb.test.integration.test_api_projects/TestProjects/test_project_delete/

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-push#252](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-push/252/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-push/252/consoleText) for more details.
Possible conflicts:
  - PR #6157 will-moore 'Use key instead of cmp to sort in test_api_containers'
    - components/tools/OmeroWeb/test/integration/test_api_projects.py

~~--conflicts~~ Conflict resolved in build [OMERO-push#153](https://idr-ci.openmicroscopy.org/jenkins/job/OMERO-push/153/). See the [console output](https://idr-ci.openmicroscopy.org/jenkins/job/OMERO-push/153/consoleText) for more details.

**Comment by joshmoore** [comment]
Both tests passed in merge (222) and py3 (37) but there was a conflict. Does that mean this PR is not needed?

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-push#254](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-push/254/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-push/254/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - components/tools/OmeroWeb/test/integration/test_api_projects.py

~~--conflicts~~ Conflict resolved in build [OMERO-push#256](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-push/256/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-push/256/consoleText) for more details.

**Comment by joshmoore** [comment]
@jburel : this was again not included. Can you comment?

**Comment by jburel** [comment]
I will have a look. Maybe something else fixed the tests

**Comment by jburel** [comment]
@joshmoore tests are failing so the changes are needed. 
I will sort out conflict

**Comment by joshmoore** [comment]
merge is green and the linked tests all passed in py3 build 43. :+1:

**Pull request merged**
