### PR TITLE
Handle projections of unit types

### PR DESCRIPTION
**Pull request by joshmoore**
`projection("select x.unit"...)`-style queries were failing in
IceMapper because no RType was defined to store the return value.
Rather than define multiple RTypes for each of the quantities and
their enums, the same strategy has been applied as for Permissions.
Returning a quantity object like omero.model.LengthI results in a
dictionary of values including the keys: value, unit, symbol, string.
Returning an enum produces the uppercase code enum value (as opposed
to the database/SI symbol).

#### Testing ####

In addition to the integration tests, `bin/omero hql` can be used to test the return values.
 * `select planeInfo.exposureTime.value` will return just the value (**as previously**)
 * `select cast(planeInfo.exposureTime.unit as text)` will return just the symbol, e.g. `s` (**as previously**)
 * `select planeInfo.exposureTime` will return a map of the form `{'symbol': 's', 'unit': 'SECOND', 'string': 'Time(1.2000000476837158 SECOND)', 'value': 1.2000000476837158}` (**failed before this PR**)
 * `select planeInfo.exposureTime.unit` will return just the enum as a string, i.e. 'SECOND' (**failed before this PR**)

### CODE REVIEW

**Comment by sbesson** [comment]
```
[sbesson@ome-c6100-3 OMERO-5.1-merge-deploy]$ bin/omero hql 'select pi.exposureTime from PlaneInfo pi join pi.pixels as pix join pix.image as img where img.id = 23057'
Using session 43845453-4255-4375-b5d6-8191771dab27 (user-1@trout.openmicroscopy.org:4064). Idle timeout: 10 min. Current group: private-1
 #  | Col1                                                                                                         
----+--------------------------------------------------------------------------------------------------------------
 0  | {'symbol': 's', 'unit': 'SECOND', 'string': 'Time(0.4000000059604645 SECOND)', 'value': 0.40000000596046448} 
 1  | {'symbol': 's', 'unit': 'SECOND', 'string': 'Time(0.4000000059604645 SECOND)', 'value': 0.40000000596046448} 
 2  | {'symbol': 's', 'unit': 'SECOND', 'string': 'Time(0.5 SECOND)', 'value': 0.5}                                
 3  | {'symbol': 's', 'unit': 'SECOND', 'string': 'Time(0.4000000059604645 SECOND)', 'value': 0.40000000596046448} 
 4  | {'symbol': 's', 'unit': 'SECOND', 'string': 'Time(0.5 SECOND)', 'value': 0.5}                                
 5  | {'symbol': 's', 'unit': 'SECOND', 'string': 'Time(0.5 SECOND)', 'value': 0.5}                                
 6  | {'symbol': 's', 'unit': 'SECOND', 'string': 'Time(0.5 SECOND)', 'value': 0.5}                                
 7  | {'symbol': 's', 'unit': 'SECOND', 'string': 'Time(0.5 SECOND)', 'value': 0.5}                                
 8  | {'symbol': 's', 'unit': 'SECOND', 'string': 'Time(0.4000000059604645 SECOND)', 'value': 0.40000000596046448} 
 9  | {'symbol': 's', 'unit': 'SECOND', 'string': 'Time(0.4000000059604645 SECOND)', 'value': 0.40000000596046448} 
 10 | {'symbol': 's', 'unit': 'SECOND', 'string': 'Time(0.5 SECOND)', 'value': 0.5}                                
 11 | {'symbol': 's', 'unit': 'SECOND', 'string': 'Time(0.5 SECOND)', 'value': 0.5}                                
 12 | {'symbol': 's', 'unit': 'SECOND', 'string': 'Time(0.5 SECOND)', 'value': 0.5}                                
 13 | {'symbol': 's', 'unit': 'SECOND', 'string': 'Time(0.4000000059604645 SECOND)', 'value': 0.40000000596046448} 
 14 | {'symbol': 's', 'unit': 'SECOND', 'string': 'Time(0.4000000059604645 SECOND)', 'value': 0.40000000596046448} 
 15 | {'symbol': 's', 'unit': 'SECOND', 'string': 'Time(0.5 SECOND)', 'value': 0.5}                                
 16 | {'symbol': 's', 'unit': 'SECOND', 'string': 'Time(0.4000000059604645 SECOND)', 'value': 0.40000000596046448} 
 17 | {'symbol': 's', 'unit': 'SECOND', 'string': 'Time(0.4000000059604645 SECOND)', 'value': 0.40000000596046448} 
 18 | {'symbol': 's', 'unit': 'SECOND', 'string': 'Time(0.5 SECOND)', 'value': 0.5}                                
 19 | {'symbol': 's', 'unit': 'SECOND', 'string': 'Time(0.4000000059604645 SECOND)', 'value': 0.40000000596046448} 
 20 | {'symbol': 's', 'unit': 'SECOND', 'string': 'Time(0.4000000059604645 SECOND)', 'value': 0.40000000596046448} 
 21 | {'symbol': 's', 'unit': 'SECOND', 'string': 'Time(0.4000000059604645 SECOND)', 'value': 0.40000000596046448} 
 22 | {'symbol': 's', 'unit': 'SECOND', 'string': 'Time(0.5 SECOND)', 'value': 0.5}                                
 23 | {'symbol': 's', 'unit': 'SECOND', 'string': 'Time(0.4000000059604645 SECOND)', 'value': 0.40000000596046448} 
 24 | {'symbol': 's', 'unit': 'SECOND', 'string': 'Time(0.4000000059604645 SECOND)', 'value': 0.40000000596046448} 
(25 rows)

To see details for object, enter line number.
To move ahead one page, enter 'p'
To re-display list, enter 'r'.
To quit, enter 'q' or just enter.
^CCancelled
[sbesson@ome-c6100-3 OMERO-5.1-merge-deploy]$ bin/omero hql 'select pi.exposureTime.value from PlaneInfo pi join pi.pixels as pix join pix.image as img where img.id = 23057'
Using session 43845453-4255-4375-b5d6-8191771dab27 (user-1@trout.openmicroscopy.org:4064). Idle timeout: 10 min. Current group: private-1
 #  | Col1          
----+---------------
 0  | 0.40000000596 
 1  | 0.40000000596 
 2  | 0.5           
 3  | 0.40000000596 
 4  | 0.5           
 5  | 0.5           
 6  | 0.5           
 7  | 0.5           
 8  | 0.40000000596 
 9  | 0.40000000596 
 10 | 0.5           
 11 | 0.5           
 12 | 0.5           
 13 | 0.40000000596 
 14 | 0.40000000596 
 15 | 0.5           
 16 | 0.40000000596 
 17 | 0.40000000596 
 18 | 0.5           
 19 | 0.40000000596 
 20 | 0.40000000596 
 21 | 0.40000000596 
 22 | 0.5           
 23 | 0.40000000596 
 24 | 0.40000000596 
(25 rows)

To see details for object, enter line number.
To move ahead one page, enter 'p'
To re-display list, enter 'r'.
To quit, enter 'q' or just enter.
^CCancelled
[sbesson@ome-c6100-3 OMERO-5.1-merge-deploy]$ bin/omero hql 'select pi.exposureTime.value from PlaneInfo pi join pi.pixels as pix join pix.image as img where img.id = 23057'^C
[sbesson@ome-c6100-3 OMERO-5.1-merge-deploy]$ v^C
[sbesson@ome-c6100-3 OMERO-5.1-merge-deploy]$ bin/omero hql 'select pi.exposureTime.unit as test^C
[sbesson@ome-c6100-3 OMERO-5.1-merge-deploy]$ bin/omero hql 'select pi.exposureTime.unit from PlaneInfo pi join pi.pixels as pix join pix.image as img where img.id = 23057'
Using session 43845453-4255-4375-b5d6-8191771dab27 (user-1@trout.openmicroscopy.org:4064). Idle timeout: 10 min. Current group: private-1
 #  | Col1   
----+--------
 0  | SECOND 
 1  | SECOND 
 2  | SECOND 
 3  | SECOND 
 4  | SECOND 
 5  | SECOND 
 6  | SECOND 
 7  | SECOND 
 8  | SECOND 
 9  | SECOND 
 10 | SECOND 
 11 | SECOND 
 12 | SECOND 
 13 | SECOND 
 14 | SECOND 
 15 | SECOND 
 16 | SECOND 
 17 | SECOND 
 18 | SECOND 
 19 | SECOND 
 20 | SECOND 
 21 | SECOND 
 22 | SECOND 
 23 | SECOND 
 24 | SECOND 
(25 rows)

To see details for object, enter line number.
To move ahead one page, enter 'p'
To re-display list, enter 'r'.
To quit, enter 'q' or just enter.
^CCancelled
[sbesson@ome-c6100-3 OMERO-5.1-merge-deploy]$ bin/omero hql 'select pi.exposureTime.symbol from PlaneInfo pi join pi.pixels as pix join pix.image as img where img.id = 23057'
Using session 43845453-4255-4375-b5d6-8191771dab27 (user-1@trout.openmicroscopy.org:4064). Idle timeout: 10 min. Current group: private-1
Bad query: Illegal query:select pi.exposureTime.symbol from PlaneInfo pi join pi.pixels as pix join pix.image as img where img.id = 23057
could not resolve property: exposureTime.symbol of: ome.model.core.PlaneInfo [select pi.exposureTime.symbol from ome.model.core.PlaneInfo pi join pi.pixels as pix join pix.image as img where img.id = 23057]
[sbesson@ome-c6100-3 OMERO-5.1-merge-deploy]$ bin/omero hql 'select cast(pi.exposureTime.unit as text) from PlaneInfo pi join pi.pixels as pix join pix.image as img where img.id = 23057'
Using session 43845453-4255-4375-b5d6-8191771dab27 (user-1@trout.openmicroscopy.org:4064). Idle timeout: 10 min. Current group: private-1
 #  | Col1 
----+------
 0  | s    
 1  | s    
 2  | s    
 3  | s    
 4  | s    
 5  | s    
 6  | s    
 7  | s    
 8  | s    
 9  | s    
 10 | s    
 11 | s    
 12 | s    
 13 | s    
 14 | s    
 15 | s    
 16 | s    
 17 | s    
 18 | s    
 19 | s    
 20 | s    
 21 | s    
 22 | s    
 23 | s    
 24 | s    
(25 rows)

To see details for object, enter line number.
To move ahead one page, enter 'p'
To re-display list, enter 'r'.
To quit, enter 'q' or just enter.
```

:+1:

**Comment by joshmoore** [comment]
Proposal from @chris-allan is to remove the `string` key/value from the return value as noise.

**Comment by joshmoore** [comment]
See also https://trello.com/c/vdyTStEq/330-unit-documentation for documentation improvements that will be needed separately.

**Comment by joshmoore** [comment]
Pushed.

**Comment by sbesson** [comment]
Can you also fix the integration test: https://ci.openmicroscopy.org/view/Failing/job/OMERO-5.1-merge-integration-python/lastCompletedBuild/testReport/test.integration.test_model51/TestModel51/testUnitProjections/ ?

**Comment by sbesson** [comment]
```
[hudson@ome-c6100-3 OMERO-5.1-merge-deploy]$ bin/omero hql 'select pi.exposureTime from PlaneInfo pi join pi.pixels as pix join pix.image as img where img.id = 23057'
Using session 8376881b-dd54-4a8e-8c21-f4dad8b433a4 (user-1@trout.openmicroscopy.org:4064). Idle timeout: 10 min. Current group: private-1
 #  | Col1                                                            
----+-----------------------------------------------------------------
 0  | {'symbol': 's', 'unit': 'SECOND', 'value': 0.40000000596046448} 
 1  | {'symbol': 's', 'unit': 'SECOND', 'value': 0.40000000596046448} 
 2  | {'symbol': 's', 'unit': 'SECOND', 'value': 0.5}                 
 3  | {'symbol': 's', 'unit': 'SECOND', 'value': 0.40000000596046448} 
 4  | {'symbol': 's', 'unit': 'SECOND', 'value': 0.5}                 
 5  | {'symbol': 's', 'unit': 'SECOND', 'value': 0.5}                 
 6  | {'symbol': 's', 'unit': 'SECOND', 'value': 0.5}                 
 7  | {'symbol': 's', 'unit': 'SECOND', 'value': 0.5}                 
 8  | {'symbol': 's', 'unit': 'SECOND', 'value': 0.40000000596046448} 
 9  | {'symbol': 's', 'unit': 'SECOND', 'value': 0.40000000596046448} 
 10 | {'symbol': 's', 'unit': 'SECOND', 'value': 0.5}                 
 11 | {'symbol': 's', 'unit': 'SECOND', 'value': 0.5}                 
 12 | {'symbol': 's', 'unit': 'SECOND', 'value': 0.5}                 
 13 | {'symbol': 's', 'unit': 'SECOND', 'value': 0.40000000596046448} 
 14 | {'symbol': 's', 'unit': 'SECOND', 'value': 0.40000000596046448} 
 15 | {'symbol': 's', 'unit': 'SECOND', 'value': 0.5}                 
 16 | {'symbol': 's', 'unit': 'SECOND', 'value': 0.40000000596046448} 
 17 | {'symbol': 's', 'unit': 'SECOND', 'value': 0.40000000596046448} 
 18 | {'symbol': 's', 'unit': 'SECOND', 'value': 0.5}                 
 19 | {'symbol': 's', 'unit': 'SECOND', 'value': 0.40000000596046448} 
 20 | {'symbol': 's', 'unit': 'SECOND', 'value': 0.40000000596046448} 
 21 | {'symbol': 's', 'unit': 'SECOND', 'value': 0.40000000596046448} 
 22 | {'symbol': 's', 'unit': 'SECOND', 'value': 0.5}                 
 23 | {'symbol': 's', 'unit': 'SECOND', 'value': 0.40000000596046448} 
 24 | {'symbol': 's', 'unit': 'SECOND', 'value': 0.40000000596046448} 
(25 rows)

To see details for object, enter line number.
To move ahead one page, enter 'p'
To re-display list, enter 'r'.
To quit, enter 'q' or just enter.
```

Ready to merge once the Python integration tests turn green today.

**Comment by sbesson** [comment]
https://ci.openmicroscopy.org/job/OMERO-5.1-merge-integration-python/460/ being green. Merging.

**Pull request merged**
