### PR TITLE
Small fix

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
Discovered in https://github.com/openmicroscopy/ome-documentation/pull/1244

to test:
```
bin/omero config set omero.web.application_server "wsgi"
bin/omero web config apache-wsgi
```
and check if 
```
<Directory "/Users/ola/OMERO/openmicroscopy/dist/lib/python/omeroweb/static">
```

contains just 1 ``/`` in the end

### CODE REVIEW

**Comment by manics** [comment]
@aleksandra-tarkowska Can you cherry pick https://github.com/manics/openmicroscopy/commit/d4f4fd9e9627427d944ef62bda07694ce8a21b2b

This will add some generated reference templates for wsgi.

**Comment by aleksandra-tarkowska** [comment]
Done

**Comment by manics** [comment]
@aleksandra-tarkowska sorry, I forgot to commit the import: https://github.com/openmicroscopy/openmicroscopy/commit/dedd17f06545112b7e1cfa6c4eb5bd2d74962d31

**Comment by aleksandra-tarkowska** [comment]
Done

**Comment by aleksandra-tarkowska** [comment]
all tests are passing in travis

**Comment by sbesson** [comment]
Thanks. Merging.

**Pull request merged**
