### PR TITLE
test_download: fixture IDs must be strings

### PR DESCRIPTION
**Pull request by joshmoore**
Test failure occurred with pytest-3.0.2 in devspace.

### CODE REVIEW

**Comment by joshmoore** [comment]
Closing in favor of https://github.com/openmicroscopy/openmicroscopy/pull/4858

This change will eventually be needed on the mainline, though.

**Comment by aleksandra-tarkowska** [comment]
is that PR needed if I rebased https://github.com/openmicroscopy/openmicroscopy/pull/4858 ?

**Comment by joshmoore** [comment]
Reopening due to https://10.0.51.113/job/OMERO-test-integration/lastCompletedBuild/testReport/OmeroPy.test.integration.clitest/test_download/TestDownload/

**Comment by joshmoore** [comment]
@aleksandra-tarkowska : note a second commit was necessary.

**Comment by joshmoore** [comment]
Closing in favor of @aleksandra-tarkowska's gh-4894 since that is on the mainline as well. More tests are certainly running with these commits, but still not all.

**Pull request closed without merging**
