### PR TITLE
slightly simplify graph policy rules

### PR DESCRIPTION
**Pull request by mtbc**
Enabled by #3966 uses the `OUTSIDE` graph node state less now that error-checking order does not need to be worked around. CI should remain blue and `Chgrp2`, `Delete2` should not show regressions.

### CODE REVIEW

**Comment by pwalczysko** [comment]
Delete and Chgrp actions in Insight on regions branch work as expected. Job is blue.
(not for this PR @dominikl : My regions which are inside folders do not get moved when I change group of the image - @mtbc is telling me this is due to the policy not being implemented in Insight yet.)

Ready to merge.

**Comment by mtbc** [comment]
`HierarchyMoveAndPermissionsTest.testMoveRois` illustrates the current behavior. Regarding https://trello.com/c/3EQc3guS/14-folder-related-api-methods I could certainly work on https://trello.com/c/5WFgEmPL/581-query-omero-objects-by-graph-spec for one of our milestones.

**Comment by mtbc** [comment]
To clarify: an option of `includeType={'Roi'}` will bring the ROIs but not their folders. A "list model objects containing given object" request could give you all the containing folder IDs recursively in one go if you wanted to include them in the move but of course it gets hairy if as in https://github.com/openmicroscopy/design/issues/2 ROIs from different images may be in the same folder.

**Comment by joshmoore** [comment]
@mtbc is further discussion needed here? Or would it be worth getting the proposed gateway change to see if the behavior is as intended?

**Comment by mtbc** [comment]
No more discussion needed here, no surprises. The integration testing already checks all the combinations (moving image and/or folders, with or without ROIs).

It's a bit like the situation with deleting orphaned tags: the current default makes the other alternatives easily available. I'm currently working on a `FindParents` request to provide all the Folders containing a set of ROIs, whether directly or indirectly, which should help.

**Comment by mtbc** [comment]
> My regions which are inside folders do not get moved when I change group of the image ...

Note that this PR doesn't change any of that behavior anyway, it's simply a tidying up of existing rules.

**Comment by sbesson** [comment]
All understood. Merging based on the state of the tests. We can (re)discuss the gateway graph rules tomorrow.

**Pull request merged**
