### PR TITLE
Jstree move to ome.tree.js

### PR DESCRIPTION
**Pull request by will-moore**
This moves the jsTree code to a separate js file and uses the container.html template for both the main Data page as well as the Tags page.
This means we don't have to maintain a separate container_tags.html template and all the logic for jsTree for these two pages is in a single file.

To test (NB: a lot of this is covered by Robot framework now - once that is passing, we shouldn't need to test this so deeply):
 - Need to test browsing in main Data page and Tags page, comparing data with Insight
 - Test copy, cut, paste, delete on jsTree (via toolbar and right-click menu) on Data page
 - Test filtering by user and 'All Members' in both pages

### CODE REVIEW

**Comment by gusferguson** [comment]
@will-moore 

Tested using eel and user-3 on Mac Safari and Firefox

Browsing of data and tag trees works as expected for normal and screen data.

Right-click menu in data tree
- Create New... , Edit... , Delete and Create Share... items work as expected
- the Move to Group... option gives the following error message (with a blank dialog box underlying):

400 Bad Request
nginx/1.4.2

(took markup out)

Firefox console gives:

GET
XHR
https://eel.openmicroscopy.org/merge/webclient/userdata/%7B%%20url%20'webindex'%20%%7Dfileset_check/chgrp/ [HTTP/1.1 400 Bad Request 1ms]
GET
XHR
https://eel.openmicroscopy.org/merge/webclient/userdata/%7B%%20url%20'webindex'%20%%7Dload_chgrp_groups/ [HTTP/1.1 400 Bad Request 0ms]

- none of the Rendering Settings … items work giving no error message, but the following in Firefox console - with different header for each item (see screenshot)

ReferenceError: pasteRenderingSettings is not defined
jstree<.contextmenu.items/config.renderingsettings.submenu.paste_rdef.action()
 ome.tree.js:933
$.vakata.context._execute()
 jstree.js:5324
<anonymous>
 jstree.js:5536
jQuery.event.dispatch()
 jquery-1.11.1.js:4640
jQuery.event.add/elemData.handle()
 jquery-1.11.1.js:4309
 ome.tree.js:933:33
ReferenceError: pasteRenderingSettings is not defined
jstree<.contextmenu.items/config.renderingsettings.submenu.paste_rdef.action()

webclient

**Comment by pwalczysko** [comment]
Having the same experience as Gus here. Move is not working in Firefox. The other functionalities mentioned here, browsing of data and tags are fine.

**Comment by will-moore** [comment]
Issues above should be fixed now (all Rendering setting context menu options should work).

Probably a good idea not to merge right away - in case there's other issues we might have missed (quite a big change).

**Comment by pwalczysko** [comment]
Move to another group workflow:
  - select a dataset (user-3 in RA group) with images in it
  - right-click and ``Move to...`` 
  - in the appearing dialog, select a group, then allso
  - select a pre-existing target Project
  - click OK
  - observe error

```

  File "/opt/hudson/workspace/OMERO-DEV-merge-deploy/src/dist/lib/python/omeroweb/webclient/views.py", line 4195, in getAllObjects
    fileset_ids.add(e[1].val)

AttributeError: 'NoneType' object has no attribute 'val'
```

**Comment by pwalczysko** [comment]
In summary: One bug in Move workflow still persisting https://github.com/openmicroscopy/openmicroscopy/pull/4389#issuecomment-169300688, the other behaviour as expected. But definitely we should not rush with merging.

**Comment by will-moore** [comment]
@pwalczysko That bug only showed up with chgrp of a Dataset that contained images with no fileset (created by script). I think it's been there since 5.2.0, but should be fixed now.

**Comment by pwalczysko** [comment]
@will-moore : Yes, this works now, I have moved especially the datasets containing images created by scripts -> went fine.
I suggest to wati for next week to give it a time to find out some possible inexpected bugs.
Nothing explicit is pending here though.

**Comment by pwalczysko** [comment]
Retested today. Nothing more found.  See above.

**Comment by jburel** [comment]
@pwalczysko: another round of tests?

**Comment by pwalczysko** [comment]
Bug: The small icons in the right-click context menu when creating new P/D/S are missing.
cowfish merge (with eel merge DB)
screen shot 2016-01-20 at 18 15 26
eel latest
screen shot 2016-01-20 at 18 15 51
Using Firefox 
screen shot 2016-01-20 at 18 23 55

**Comment by pwalczysko** [comment]
Trying to download image  ID 21911 from eel-merge DB (using cowfish merge client) , user-4 (a .lei 56 MIF) I get

```
Cannot download file (id:None). Traceback (most recent call last): File "/opt/hudson/workspace/OMERO-DEV-Python27-merge-deploy/src/dist/lib/python/omeroweb/webgateway/views.py", line 2105, in archived_files zipName = zip_archived_files(images, temp, zipName) File "/opt/hudson/workspace/OMERO-DEV-Python27-merge-deploy/src/dist/lib/python/omeroweb/webgateway/util.py", line 117, in zip_archived_files for chunk in a.getFileInChunks(): File "/opt/hudson/workspace/OMERO-DEV-Python27-merge-deploy/src/dist/lib/python/omero/gateway/__init__.py", line 4758, in getFileInChunks yield store.read(0, long(size)) File "/opt/hudson/workspace/OMERO-DEV-Python27-merge-deploy/src/dist/lib/python/omero/gateway/__init__.py", line 4205, in __call__ return self.handle_exception(e, *args, **kwargs) File "/opt/hudson/workspace/OMERO-DEV-Python27-merge-deploy/src/dist/lib/python/omeroweb/webclient/webclient_gateway.py", line 1993, in handle_exception e, *args, **kwargs) File "/opt/hudson/workspace/OMERO-DEV-Python27-merge-deploy/src/dist/lib/python/omero/gateway/__init__.py", line 4202, in __call__ return self.f(*args, **kwargs) File "/opt/hudson/workspace/OMERO-DEV-Python27-merge-deploy/src/dist/lib/python/omero_api_RawFileStore_ice.py", line 162, in read return _M_omero.api.RawFileStore._op_read.invoke(self, ((position, length), _ctx)) SecurityViolation: exception ::omero::SecurityViolation { serverStackTrace = ome.conditions.SecurityViolation: Download is restricted for ome.model.core.OriginalFile:Id_15928 at ome.security.policy.BinaryAccessPolicy.checkRestriction(BinaryAccessPolicy.java:210) at ome.security.policy.DefaultPolicyService.checkRestriction(DefaultPolicyService.java:83) at ome.security.basic.BasicSecuritySystem.checkRestriction(BasicSecuritySystem.java:653) at ome.services.RawFileBean.read(RawFileBean.java:413) at sun.reflect.GeneratedMethodAccessor1000.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:606) at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:307) at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) at ome.security.basic.EventHandler.invoke(EventHandler.java:154) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) at ome.tools.hibernate.SessionHandler.doStateful(SessionHandler.java:216) at ome.tools.hibernate.SessionHandler.invoke(SessionHandler.java:200) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:108) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) at ome.tools.hibernate.ProxyCleanupFilter$Interceptor.invoke(ProxyCleanupFilter.java:249) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) at ome.services.util.ServiceHandler.invoke(ServiceHandler.java:121) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202) at com.sun.proxy.$Proxy91.read(Unknown Source) at sun.reflect.GeneratedMethodAccessor1000.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:606) at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:307) at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) at ome.security.basic.BasicSecurityWiring.invoke(BasicSecurityWiring.java:93) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) at ome.services.blitz.fire.AopContextInitializer.invoke(AopContextInitializer.java:43) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202) at com.sun.proxy.$Proxy91.read(Unknown Source) at sun.reflect.GeneratedMethodAccessor2277.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:606) at ome.services.blitz.util.IceMethodInvoker.invoke(IceMethodInvoker.java:172) at ome.services.throttling.Callback.run(Callback.java:56) at ome.services.throttling.InThreadThrottlingStrategy.callInvokerOnRawArgs(InThreadThrottlingStrategy.java:56) at ome.services.blitz.impl.AbstractAmdServant.callInvokerOnRawArgs(AbstractAmdServant.java:140) at ome.services.blitz.impl.RawFileStoreI.read_async(RawFileStoreI.java:88) at ome.services.blitz.repo.RepoRawFileStoreI.read_async(RepoRawFileStoreI.java:112) at sun.reflect.GeneratedMethodAccessor2276.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:606) at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:307) at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) at omero.cmd.CallContext.invoke(CallContext.java:78) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202) at com.sun.proxy.$Proxy92.read_async(Unknown Source) at omero.api._RawFileStoreTie.read_async(_RawFileStoreTie.java:78) at omero.api._RawFileStoreDisp.___read(_RawFileStoreDisp.java:249) at omero.api._RawFileStoreDisp.__dispatch(_RawFileStoreDisp.java:420) at IceInternal.Incoming.invoke(Incoming.java:222) at Ice.ConnectionI.invokeAll(ConnectionI.java:2482) at Ice.ConnectionI.dispatch(ConnectionI.java:1258) at Ice.ConnectionI.message(ConnectionI.java:1213) at IceInternal.ThreadPool.run(ThreadPool.java:321) at IceInternal.ThreadPool.access$300(ThreadPool.java:12) at IceInternal.ThreadPool$EventHandlerThread.run(ThreadPool.java:693) at java.lang.Thread.run(Thread.java:745) serverExceptionClass = ome.conditions.SecurityViolation message = Download is restricted for ome.model.core.OriginalFile:Id_15928 } 
```

**Comment by pwalczysko** [comment]
Went through https://www.openmicroscopy.org/private/ome-internal/testing_scenarios/WebLightTesting.html using cowfish merge as webclient and eel merge as server. 

2 problems detected. https://github.com/openmicroscopy/openmicroscopy/pull/4389#issuecomment-173315748 (possibly due to this PR ?) and https://github.com/openmicroscopy/openmicroscopy/pull/4389#issuecomment-173321543 (possibly due to something else, but needs to be looked at)

**Comment by will-moore** [comment]
@pwalczysko The first issue (icons in right-click menu) is fixed. The problem with downloading image ID 21911 from eel-merge DB is not related to this PR. The error you reported (restricted download) is a policy for public repositories that don't want to allow original file download cc @aleksandra-tarkowska. I tried a bunch of other images, also owned by user-4 (while logged in as user-3) and didn't see any problems. (for image 21911 I just saw a Server Error).
```
ome.conditions.SecurityViolation: Download is restricted for ome.model.core.OriginalFile:Id_15928 at ome.security.policy.BinaryAccessPolicy.checkRestriction(BinaryAccessPolicy.java:210)
```

**Comment by pwalczysko** [comment]
To repeat the problem https://github.com/openmicroscopy/openmicroscopy/pull/4389#issuecomment-173321543
The workflow more precisely (repeated by me today as well as by @joshmoore today):
1. go to cowfish
2. login as user-4
3. search for 21911
4. browse back to Data pane
5. select Download
6. select .zip
7. observe the error in the Download window itself

**Comment by pwalczysko** [comment]
Created https://trac.openmicroscopy.org/ome/ticket/13150#ticket for https://github.com/openmicroscopy/openmicroscopy/pull/4389#issuecomment-169300688

**Comment by pwalczysko** [comment]
Retested the missing icons problem https://github.com/openmicroscopy/openmicroscopy/pull/4389#issuecomment-173315748 - on cowfish connected to eel, on eel connected to eel - works as expected.

Considering the problem https://github.com/openmicroscopy/openmicroscopy/pull/4389#issuecomment-173635505 not to be the fault of this PR, the things here look good.

**Comment by joshmoore** [comment]
@will-moore : one last comment, based on the previous discussions, is a removal of a file from `webgateway` (even if named "old") in a point release an issue?

**Comment by will-moore** [comment]
@joshmoore I'm perfectly happy to remove ```webgateway/css/header_old.css``` since I just can't imagine anyone finding it and deciding to use it, especially given it's name. I don't even think we've ever used it - probably left over from some ancient refactoring.
However, if it's a matter of principle, we could just mark it as deprecated (somehow) and remove in 5.3.0? cc @aleksandra-tarkowska.

**Comment by aleksandra-tarkowska** [comment]
I even don't know what that was for.

**Comment by joshmoore** [comment]
Merging since this is blocking @aleksandra-tarkowska then, and we can carry on the discussion elsewhere. But if there's a rule that we're telling the community, we should stick to it and use our own process for deprecating+announcing.

**Pull request merged**
