### PR TITLE
ROIs v2

### PR DESCRIPTION
**Pull request by mtbc**
Companion PR to https://github.com/openmicroscopy/bioformats/pull/1999.

* introduce SQL upgrade for OMERO 5.2
* introduce SQL upgrade for OMERO 5.3
* remove some ROI and Shape properties from model

--depends-on #4234

### CODE REVIEW

**Comment by jburel** [comment]
Ellipse: were we not supposed to remove cx and cy and replace by x and y?

**Comment by mtbc** [comment]
This PR is just a first step. It doesn't rename any properties.

**Comment by joshmoore** [comment]
Is the goal to have tests turn green before merging?

**Comment by mtbc** [comment]
I suppose that requires figuring out this docker Jenkins locale issue. They were green while this was in breaking. Not sure what the plan should be.

**Comment by mtbc** [comment]
Rewrote commit history to made SQL DB version number changes clearer.

**Comment by mtbc** [comment]
While https://trello.com/c/wDtIyhJ7/44-fix-omero-start-in-ci remains pending one may wish to run the integration tests locally.

**Comment by mtbc** [comment]
The first few commits are as from #4233.

**Comment by joshmoore** [comment]
Tested locally and commits generally look good, :thumbsup: - One concern over the lifetime of the branch will be regularly testing the multiple upgrade paths:

 * 5.1 latest to 5.3
 * 5.2 latest to 5.3
 * 5.2 merge to 5.3 (not to mention breaking...)

I'll get these merged along with the changes to the space to use `ome.regions` by default until we move to the mainline.

**Comment by joshmoore** [comment]
NB: "visible" field in Insight will need to be removed -- https://trello.com/c/zIkIfMnd/46-drop-visible-from-insight

**Pull request merged**
