### PR TITLE
Add omero.web.prefix as an alias for FORCE_SCRIPT_NAME

### PR DESCRIPTION
**Pull request by manics**
See https://trello.com/c/C5yQwFGk/374-omero-web-use-omero-web-prefix-in-place-of-omero-web-force-script-name

At the moment both `omero.web.force_script_name` and `omero.web.prefix` have the same effect for backwards compatibility.

### CODE REVIEW

**Comment by manics** [comment]
I've added `DEPRECATED_SETTINGS_MAPPINGS` and changed `process_custom_settings` to use `DEPRECATED_SETTINGS_MAPPINGS` if a key isn't in `CUSTOM_SETTINGS_MAPPINGS`.

```
omero.web.force_script_name=/deprecated-prefix
```
```
$ dist/bin/omero web restart
WARNING:root:Setting omero.web.force_script_name is deprecated, use omero.web.prefix
Stopping OMERO.web... [OK]
Django FastCGI workers (PID 39408) killed.
WARNING:root:Setting omero.web.force_script_name is deprecated, use omero.web.prefix
WARNING:root:Setting omero.web.force_script_name is deprecated, use omero.web.prefix
Post-processed 'omeroweb.viewer.min.css' as 'omeroweb.viewer.min.css'
Post-processed 'omeroweb.viewer.min.js' as 'omeroweb.viewer.min.js'

0 static files copied, 600 unmodified, 2 post-processed.
Starting OMERO.web... [OK]
```

```
omero.web.force_script_name=/deprecated-prefix
omero.web.prefix=/new-prefix
```
```
$ dist/bin/omero web restart
ERROR:root:omero.web.prefix and its deprecated key omero.web.force_script_name are both set, using omero.web.prefix
Stopping OMERO.web... [OK]
Django FastCGI workers (PID 39423) killed.
ERROR:root:omero.web.prefix and its deprecated key omero.web.force_script_name are both set, using omero.web.prefix
ERROR:root:omero.web.prefix and its deprecated key omero.web.force_script_name are both set, using omero.web.prefix
Post-processed 'omeroweb.viewer.min.css' as 'omeroweb.viewer.min.css'
Post-processed 'omeroweb.viewer.min.js' as 'omeroweb.viewer.min.js'

0 static files copied, 600 unmodified, 2 post-processed.
Starting OMERO.web... [OK]
```

```
omero.web.force_script_name=/deprecated-prefix
omero.web.debug=True
```
```
$ dist/bin/omero web restart
WARNING:root:Setting omero.web.force_script_name is deprecated, use omero.web.prefix
Stopping OMERO.web... WARNING:root:Setting omero.web.force_script_name is deprecated, use omero.web.prefix
INFO:__main__:Application Starting...
INFO:root:Processing custom settings for module omeroweb.settings
INFO:root:Processing custom settings for module omeroweb.settings
WARNING:root:Setting omero.web.force_script_name is deprecated, use omero.web.prefix
INFO:root:Processing custom settings for module omeroweb.settings
...

DEBUG:omeroweb.settings:FORCE_SCRIPT_NAME = '/deprecated-prefix' (source:default)
...
DEBUG:omeroweb.settings:FORCE_SCRIPT_NAME = '/deprecated-prefix' (deprecated:omero.web.force_script_name, Use omero.web.prefix instead.)
...
Post-processed 'omeroweb.viewer.min.css' as 'omeroweb.viewer.min.css'
Post-processed 'omeroweb.viewer.min.js' as 'omeroweb.viewer.min.js'

0 static files copied, 600 unmodified, 2 post-processed.
[OK]
Django FastCGI workers (PID 39600) killed.
Starting OMERO.web... [OK]
```
Note if only the deprecated key is set you end up with `source:default` on the first pass.

**Comment by aleksandra-tarkowska** [comment]
Ok that looks good to me. I understand that we do not need to deprecate any of DEVELOPMENT_SETTINGS_MAPPINGS, see https://github.com/openmicroscopy/openmicroscopy/pull/3340. They've never appeared live for users

**Comment by aleksandra-tarkowska** [comment]
@sbesson any suggestions here?

**Comment by sbesson** [comment]
One thing I realized while testing the merge/integration server is that any single CLI command on the server will throw a warning e.g.

```
$ bin/omero login 3410_test@localhost:24064
WARNING:root:Setting omero.web.force_script_name is deprecated, use omero.web.prefix
Password:
```

I don't know if this should be seen a feature (i.e. fix your config!) or extra noise.

**Comment by aleksandra-tarkowska** [comment]
why ```bin/omero login``` loads web settings?

**Comment by sbesson** [comment]
Because the CLI will try to load all plugins (see https://github.com/openmicroscopy/openmicroscopy/blob/develop/components/tools/OmeroPy/src/omero/cli.py#L1317)

**Comment by aleksandra-tarkowska** [comment]
@sbesson is there anything else you need here?

**Comment by sbesson** [comment]
All todos have been captured in Trello card. Merging,

**Comment by sbesson** [comment]
All 5.1 CI deployment jobs updated to use the new `omero.web.prefix`.

**Comment by manics** [comment]
--no-rebase

**Pull request merged**
