### PR TITLE
fix SQL syntax errors from database upgrade scripts

### PR DESCRIPTION
**Pull request by mtbc**
# What this PR does

@chris-allan reports syntax errors in our PL/pgSQL code. This PR fixes SQL upgrade scripts since OMERO 4.4 and ensures that upgrade to 5.3 fixes the issues for those who already upgraded.

# Testing this PR

Attempt whichever upgrade paths you like, anything from 4.4 onward to fresh databases. Ensure that the upgrade scripts introduce to the database no functions with the overquoted `%%` and, if you try upgrades from old OMERO *without* this PR, that any such overquoting is fixed by upgrading to this latest database patch 11.

# Related reading

#4201
https://github.com/openmicroscopy/openmicroscopy/pull/4793#discussion_r77590764
https://trello.com/c/2tDzi0xP/114-detect-buggy-sql-scripts
--rebased-to #4836 only https://github.com/openmicroscopy/openmicroscopy/commit/53885287e68258ab3e7d48d578aec60ca76c2e75

### CODE REVIEW

**Comment by will-moore** [comment]
Started by trying to reproduce the bug...
Created a new OMERO 4.4.12 DB and updated to 5.0 using develop
```$ psql -U omero omero44 < sql/psql/OMERO5.0__0/OMERO4.4__0.sql ```
Don't see any syntax errors in filesetentry_fileset_index_move

<details><summary>filesetentry_fileset_index_move 5.0</summary>
```
omero44=# select * from dbpatch
omero44-# ;
 id | currentpatch | currentversion | permissions |          finished          |      message      | previouspatch | previousversion | external_id 
----+--------------+----------------+-------------+----------------------------+-------------------+---------------+-----------------+-------------
  1 |            0 | OMERO4.4       |         -52 | 2016-09-07 10:10:58.774547 | Database ready.   |             0 | OMERO4.4        |            
  2 |            0 | OMERO5.0       |         -52 | 2016-09-07 10:44:04.595493 | Database updated. |             0 | OMERO4.4        |            
(2 rows)
omero44=# \df+ filesetentry_fileset_index_move
                                                                                                                 List of functions
 Schema |              Name               | Result data type | Argument data types |  Type   | Security | Volatility | Owner | Language |                                        Source code                                         | Description 
--------+---------------------------------+------------------+---------------------+---------+----------+------------+-------+----------+--------------------------------------------------------------------------------------------+-------------
 public | filesetentry_fileset_index_move | trigger          |                     | trigger | invoker  | volatile   | omero | plpgsql  |                                                                                           +| 
        |                                 |                  |                     |         |          |            |       |          |     DECLARE                                                                               +| 
        |                                 |                  |                     |         |          |            |       |          |       duplicate INT8;                                                                     +| 
        |                                 |                  |                     |         |          |            |       |          |     BEGIN                                                                                 +| 
        |                                 |                  |                     |         |          |            |       |          |                                                                                           +| 
        |                                 |                  |                     |         |          |            |       |          |       -- Avoids a query if the new and old values of x are the same.                      +| 
        |                                 |                  |                     |         |          |            |       |          |       IF new.fileset = old.fileset AND new.fileset_index = old.fileset_index THEN         +| 
        |                                 |                  |                     |         |          |            |       |          |           RETURN new;                                                                     +| 
        |                                 |                  |                     |         |          |            |       |          |       END IF;                                                                             +| 
        |                                 |                  |                     |         |          |            |       |          |                                                                                           +| 
        |                                 |                  |                     |         |          |            |       |          |       -- At most, there should be one duplicate                                           +| 
        |                                 |                  |                     |         |          |            |       |          |       SELECT id INTO duplicate                                                            +| 
        |                                 |                  |                     |         |          |            |       |          |         FROM filesetentry            
```
</details>

Now upgraded to 5.1
```psql -U omero omero44 < sql/psql/OMERO5.1__1/OMERO5.0__0.sql```

Now I see syntax errors:
<details><summary>filesetentry_fileset_index_move 5.1</summary>
```
omero44=# select * from dbpatch;
 id | currentpatch | currentversion | permissions |          finished          |      message      | previouspatch | previousversion | external_id 
----+--------------+----------------+-------------+----------------------------+-------------------+---------------+-----------------+-------------
  1 |            0 | OMERO4.4       |         -52 | 2016-09-07 10:10:58.774547 | Database ready.   |             0 | OMERO4.4        |            
  2 |            0 | OMERO5.0       |         -52 | 2016-09-07 10:44:04.595493 | Database updated. |             0 | OMERO4.4        |            
  3 |            1 | OMERO5.1       |         -52 | 2016-09-07 11:57:35.467874 | Database updated. |             0 | OMERO5.0        |            
(3 rows)

omero44=# \df+ filesetentry_fileset_index_move
                                                                                                                 List of functions
 Schema |              Name               | Result data type | Argument data types |  Type   | Security | Volatility | Owner | Language |                                        Source code                                         | Description 
--------+---------------------------------+------------------+---------------------+---------+----------+------------+-------+----------+--------------------------------------------------------------------------------------------+-------------
 public | filesetentry_fileset_index_move | trigger          |                     | trigger | invoker  | volatile   | omero | plpgsql  |                                                                                           +| 
        |                                 |                  |                     |         |          |            |       |          |     DECLARE                                                                               +| 
        |                                 |                  |                     |         |          |            |       |          |       duplicate INT8;                                                                     +| 
        |                                 |                  |                     |         |          |            |       |          |     BEGIN                                                                                 +| 
        |                                 |                  |                     |         |          |            |       |          |                                                                                           +| 
        |                                 |                  |                     |         |          |            |       |          |       -- Avoids a query if the new and old values of x are the same.                      +| 
        |                                 |                  |                     |         |          |            |       |          |       IF new.fileset = old.fileset AND new.fileset_index = old.fileset_index THEN         +| 
        |                                 |                  |                     |         |          |            |       |          |           RETURN new;                                                                     +| 
        |                                 |                  |                     |         |          |            |       |          |       END IF;                                                                             +| 
        |                                 |                  |                     |         |          |            |       |          |                                                                                           +| 
        |                                 |                  |                     |         |          |            |       |          |       -- At most, there should be one duplicate                                           +| 
        |                                 |                  |                     |         |          |            |       |          |       SELECT id INTO duplicate                                                            +| 
        |                                 |                  |                     |         |          |            |       |          |         FROM filesetentry                                                                 +| 
        |                                 |                  |                     |         |          |            |       |          |        WHERE fileset = new.fileset AND fileset_index = new.fileset_index                  +| 
        |                                 |                  |                     |         |          |            |       |          |       OFFSET 0                                                                            +| 
        |                                 |                  |                     |         |          |            |       |          |        LIMIT 1;                                                                           +| 
        |                                 |                  |                     |         |          |            |       |          |                                                                                           +| 
        |                                 |                  |                     |         |          |            |       |          |       IF duplicate IS NOT NULL THEN                                                       +| 
        |                                 |                  |                     |         |          |            |       |          |           RAISE NOTICE 'Remapping filesetentry %% via (-1 - oldvalue )', duplicate;       +| 
        |                                 |                  |                     |         |          |            |       |          |           UPDATE filesetentry SET fileset_index = -1 - fileset_index WHERE id = duplicate;+| 
        |                                 |                  |                     |         |          |            |       |          |       END IF;                                                                             +| 
        |                                 |                  |                     |         |          |            |       |          |                                                                                           +| 
        |                                 |                  |                     |         |          |            |       |          |       RETURN new;                                                                         +| 
        |                                 |                  |                     |         |          |            |       |          |     END;                                                                                   | 
(1 row)
```
</details>

**Comment by will-moore** [comment]
After checking out this branch and restoring my omero44 DB from dump, I repeated the upgrade steps above and found that the filesetentry function doesn't contain the syntax errors:

<details><summary> filesetentry_fileset_index_move 5.1</summary>
```
omero44_from_dump=# select * from dbpatch;
 id | currentpatch | currentversion | permissions |          finished          |      message      | previouspatch | previousversion | external_id 
----+--------------+----------------+-------------+----------------------------+-------------------+---------------+-----------------+-------------
  1 |            0 | OMERO4.4       |         -52 | 2016-09-07 10:10:58.774547 | Database ready.   |             0 | OMERO4.4        |            
  2 |            0 | OMERO5.0       |         -52 | 2016-09-07 12:21:24.647757 | Database updated. |             0 | OMERO4.4        |            
  3 |            1 | OMERO5.1       |         -52 | 2016-09-07 12:22:24.872515 | Database updated. |             0 | OMERO5.0        |            
(3 rows)

omero44_from_dump=# \df+ filesetentry_fileset_index_move
                                                                                                                 List of functions
 Schema |              Name               | Result data type | Argument data types |  Type   | Security | Volatility | Owner | Language |                                        Source code                                         | Description 
--------+---------------------------------+------------------+---------------------+---------+----------+------------+-------+----------+--------------------------------------------------------------------------------------------+-------------
 public | filesetentry_fileset_index_move | trigger          |                     | trigger | invoker  | volatile   | omero | plpgsql  |                                                                                           +| 
        |                                 |                  |                     |         |          |            |       |          |     DECLARE                                                                               +| 
        |                                 |                  |                     |         |          |            |       |          |       duplicate INT8;                                                                     +| 
        |                                 |                  |                     |         |          |            |       |          |     BEGIN                                                                                 +| 
        |                                 |                  |                     |         |          |            |       |          |                                                                                           +| 
        |                                 |                  |                     |         |          |            |       |          |       -- Avoids a query if the new and old values of x are the same.                      +| 
        |                                 |                  |                     |         |          |            |       |          |       IF new.fileset = old.fileset AND new.fileset_index = old.fileset_index THEN         +| 
        |                                 |                  |                     |         |          |            |       |          |           RETURN new;                                                                     +| 
        |                                 |                  |                     |         |          |            |       |          |       END IF;                                                                             +| 
        |                                 |                  |                     |         |          |            |       |          |                                                                                           +| 
        |                                 |                  |                     |         |          |            |       |          |       -- At most, there should be one duplicate                                           +| 
        |                                 |                  |                     |         |          |            |       |          |       SELECT id INTO duplicate                                                            +| 
        |                                 |                  |                     |         |          |            |       |          |         FROM filesetentry                                                                 +| 
        |                                 |                  |                     |         |          |            |       |          |        WHERE fileset = new.fileset AND fileset_index = new.fileset_index                  +| 
        |                                 |                  |                     |         |          |            |       |          |       OFFSET 0                                                                            +| 
        |                                 |                  |                     |         |          |            |       |          |        LIMIT 1;                                                                           +| 
        |                                 |                  |                     |         |          |            |       |          |                                                                                           +| 
        |                                 |                  |                     |         |          |            |       |          |       IF duplicate IS NOT NULL THEN                                                       +| 
        |                                 |                  |                     |         |          |            |       |          |           RAISE NOTICE 'Remapping filesetentry % via (-1 - oldvalue )', duplicate;        +| 
        |                                 |                  |                     |         |          |            |       |          |           UPDATE filesetentry SET fileset_index = -1 - fileset_index WHERE id = duplicate;+| 
        |                                 |                  |                     |         |          |            |       |          |       END IF;                                                                             +| 
        |                                 |                  |                     |         |          |            |       |          |                                                                                           +| 
        |                                 |                  |                     |         |          |            |       |          |       RETURN new;                                                                         +| 
        |                                 |                  |                     |         |          |            |       |          |     END;                                                                                   | 
(1 row)

```
</details>

So that seems to be fixed.
Now I'll try to upgrade the "broken" DB above to 5.3 patch11...

**Comment by will-moore** [comment]
```
psql -U omero omero44 < sql/psql/OMERO5.2__0/OMERO5.1__1.sql
psql -U omero omero44 < sql/psql/OMERO5.3DEV__11/OMERO5.2__0.sql
```
```filesetentry_fileset_index_move``` now seems to have the ```%%``` syntax corrected:

<details><summary>filesetentry_fileset_index_move 5.3_11</summary>
```
omero44=# select * from dbpatch;
 id | currentpatch | currentversion | permissions |          finished          |      message      | previouspatch | previousversion | external_id 
----+--------------+----------------+-------------+----------------------------+-------------------+---------------+-----------------+-------------
  1 |            0 | OMERO4.4       |         -52 | 2016-09-07 10:10:58.774547 | Database ready.   |             0 | OMERO4.4        |            
  2 |            0 | OMERO5.0       |         -52 | 2016-09-07 10:44:04.595493 | Database updated. |             0 | OMERO4.4        |            
  3 |            1 | OMERO5.1       |         -52 | 2016-09-07 11:57:35.467874 | Database updated. |             0 | OMERO5.0        |            
  4 |            0 | OMERO5.2       |         -52 | 2016-09-07 12:28:13.696795 | Database updated. |             1 | OMERO5.1        |            
  5 |           11 | OMERO5.3DEV    |         -52 | 2016-09-07 12:28:51.174182 | Database updated. |             0 | OMERO5.2        |            
(5 rows)

omero44=# \df+ filesetentry_fileset_index_move
                                                                                                                 List of functions
 Schema |              Name               | Result data type | Argument data types |  Type   | Security | Volatility | Owner | Language |                                        Source code                                         | Description 
--------+---------------------------------+------------------+---------------------+---------+----------+------------+-------+----------+--------------------------------------------------------------------------------------------+-------------
 public | filesetentry_fileset_index_move | trigger          |                     | trigger | invoker  | volatile   | omero | plpgsql  |                                                                                           +| 
        |                                 |                  |                     |         |          |            |       |          |     DECLARE                                                                               +| 
        |                                 |                  |                     |         |          |            |       |          |       duplicate INT8;                                                                     +| 
        |                                 |                  |                     |         |          |            |       |          |     BEGIN                                                                                 +| 
        |                                 |                  |                     |         |          |            |       |          |                                                                                           +| 
        |                                 |                  |                     |         |          |            |       |          |       -- Avoids a query if the new and old values of x are the same.                      +| 
        |                                 |                  |                     |         |          |            |       |          |       IF new.fileset = old.fileset AND new.fileset_index = old.fileset_index THEN         +| 
        |                                 |                  |                     |         |          |            |       |          |           RETURN new;                                                                     +| 
        |                                 |                  |                     |         |          |            |       |          |       END IF;                                                                             +| 
        |                                 |                  |                     |         |          |            |       |          |                                                                                           +| 
        |                                 |                  |                     |         |          |            |       |          |       -- At most, there should be one duplicate                                           +| 
        |                                 |                  |                     |         |          |            |       |          |       SELECT id INTO duplicate                                                            +| 
        |                                 |                  |                     |         |          |            |       |          |         FROM filesetentry                                                                 +| 
        |                                 |                  |                     |         |          |            |       |          |        WHERE fileset = new.fileset AND fileset_index = new.fileset_index                  +| 
        |                                 |                  |                     |         |          |            |       |          |       OFFSET 0                                                                            +| 
        |                                 |                  |                     |         |          |            |       |          |        LIMIT 1;                                                                           +| 
        |                                 |                  |                     |         |          |            |       |          |                                                                                           +| 
        |                                 |                  |                     |         |          |            |       |          |       IF duplicate IS NOT NULL THEN                                                       +| 
        |                                 |                  |                     |         |          |            |       |          |           RAISE NOTICE 'Remapping filesetentry % via (-1 - oldvalue )', duplicate;        +| 
        |                                 |                  |                     |         |          |            |       |          |           UPDATE filesetentry SET fileset_index = -1 - fileset_index WHERE id = duplicate;+| 
        |                                 |                  |                     |         |          |            |       |          |       END IF;                                                                             +| 
        |                                 |                  |                     |         |          |            |       |          |                                                                                           +| 
        |                                 |                  |                     |         |          |            |       |          |       RETURN new;                                                                         +| 
        |                                 |                  |                     |         |          |            |       |          |     END;                                                                                   | 
(1 row)

```
</details>

However, I haven't checked "ALL" of the DB for similar syntax errors. Only that one function.

**Comment by mtbc** [comment]
@rleigh-codelibre: for manual testing I'd suggest:

* Without this PR, upgrade from 4.4 to 5.3__10; use this PR to upgrade to patch 11; use `pg_dump -s` to verify that no `%%` remain. Make sure you can still import.
* With this PR, upgrade from 4.4 to 5.2; use `pg_dump -s` to verify that no `%%` remain. Make sure you can still import.

but anything else you think of is of course good because it might be something I didn't already try!

**Comment by rleigh-codelibre** [comment]
This all seems to work correctly to me, and the diffs also look fine.  I think this is all good to merge.

**Comment by mtbc** [comment]
Thank you. Removed from breaking.

**Comment by rleigh-codelibre** [comment]
The CI looks happy and there have been no changes since I last tested.  So I think it's good to merge.

**Comment by joshmoore** [comment]
"This merge commit was added into this branch cleanly." -- :thumbsup:

**Pull request merged**
