### PR TITLE
Use 5.0 versions of OMERO and Homebrew formulas

### PR DESCRIPTION
**Pull request by sbesson**
See also https://github.com/sbesson/openmicroscopy/commit/4321538e4f0abb0db6ca26c54a3ca9911afac526. This PR modifies the `OMERO-homebrew-install.sh` installation script under `dev_5_0` to use the new formulas introduced by https://github.com/ome/homebrew-alt/pull/70.

--no-rebase

### CODE REVIEW

**Comment by sbesson** [comment]
See https://ci.openmicroscopy.org/job/OME-5.0-merge-homebrew/666/

**Comment by joshmoore** [comment]
So looks good and is what I had in mind. Guess the only worry is that now nothing is testing/verifying the non-versioned formulae. Do we just live with that for the moment?

**Comment by sbesson** [comment]
Agreed, I see 2 ways to tackle this:
- either make the formulas names configurable and extend the testing matrix of the daily job
- or at the `homebrew-alt` level add some checkpoint (Travis?) ensuring `omero` and `omero5x` only differ by the class definition line

**Comment by joshmoore** [comment]
The latter seems sufficient. And then when we move to omero51 etc. travis only needs to be bumped.

**Comment by sbesson** [comment]
See last commits on https://github.com/ome/homebrew-alt/pull/70

**Pull request merged**
