### PR TITLE
Merge develop into regions

### PR DESCRIPTION
**Pull request by dominikl**
This PR merges all the recent develop PRs including Ice 3.6. The last merge commit should fix a trivial conflict related to the rebasing of the `getROICount` PR.

### CODE REVIEW

**Comment by mtbc** [comment]
No remaining changes after `ImageDataViewImpl` conflict. Duplicate removed in https://github.com/openmicroscopy/openmicroscopy/pull/4623/commits/1b6e56fdfdd549be4f8ad554d4982e4ff0667e9f indeed already has same method in `regions`. Once we get a successful run of http://regions-ci.docker.openmicroscopy.org:8080/ I'd say we are good to merge.

**Comment by sbesson** [comment]
Discussed with @jburel @dominikl @mtbc, it seems that porting the Ice 3.6 PR will require additional test modifications similar to the ones done in #4594 (for the tests added specifically for OMERO 5.3.0). @mtbc will investigate these tests. In the meantime, we should be able to fix the conflicts between `develop` and `regions` without including Ice 3.6 into the question by merging cda8446 into `regions`. Closing this PR to re-open a new one.

**Comment by dominikl** [comment]
Replaced by #4632

**Comment by sbesson** [comment]
Tested the ROI count functionality. Worked as expected. All integration tests are passing. Merging.

**Pull request merged**
