### PR TITLE
Update z for lifetime

### PR DESCRIPTION
**Pull request by jburel**
Update z when viewing lifetime images.
See https://trac.openmicroscopy.org.uk/ome/ticket/12445

To test
 * Import the following image  ```skyking/li-flim/samples/sample-extended.fli```
 * Open the preview. Move the z-slider, make sure the image is updated
 * Open the image in the main viewer. Move the z-slider, make sure the image is updated
 * Also check that in the status bar, after small t there is not in bracket (55null)

### CODE REVIEW

**Comment by mtbc** [comment]
Travis is complaining.

**Comment by jburel** [comment]
??

**Comment by mtbc** [comment]
Some kind person must have given it a kick. :smiley:

**Comment by mtbc** [comment]
Working much better, thank you, and looks to match the changes I see in web as I slide the bars. Good to merge.

**Comment by mtbc** [comment]
Still a `null` visible:
null-t

**Comment by jburel** [comment]
@mtbc: sorry about that, i did not push the commit fixing the display.

**Comment by mtbc** [comment]
No problem, much better now: 
null-t :+1:

**Comment by mtbc** [comment]
So, I'm happy once Travis is.

**Comment by jburel** [comment]
Actually the fact that the units is null raised another question.
This does not have to be done for 5.1.
The units is actually in the modulo annotation itself e.g. ps. We may want to review such use case later on 
cc @joshmoore @imunro @dominikl

**Comment by jburel** [comment]
Merging this PR, and will add item for discussion about modulo and units.

**Comment by jburel** [comment]
card created see https://trello.com/c/kg1tpddJ/49-modulo-and-units

**Comment by jburel** [comment]
--no-rebase

**Pull request merged**
