### PR TITLE
Annotation backlinks

### PR DESCRIPTION
**Pull request by mtbc**
# What this PR does

Add backlinks from annotations to those objects that they annotate.
# Testing this PR

Query via HQL using backlink properties (e.g., `SELECT a.imageLinks FROM Annotation a WHERE ...`) to make sure that they work as desired.
--breaking for now
--depends-on #4807
--exclude due to https://ci.openmicroscopy.org/job/OMERO-DEV-breaking-integration-python/621/testReport/
# Related reading

https://trello.com/c/d4U7CqV3/495-annotation-objectlinks

### CODE REVIEW

**Comment by mtbc** [comment]
It's possible that the extra generated code has blown Travis' little mind.

**Comment by mtbc** [comment]
Also CI's: `javac` OOMs. Gah! I guess this PR's for testing locally then. Also try DB upgrade paths:
* fresh DB
* from earlier 5.3 patch
* from 5.2

**Comment by jburel** [comment]
Same failure when building locally
``
 RoiResult r = serviceFactory.getRoiService().findByImage(img.getId().getValue(), new RoiOptions());
                                                        ^
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.String.concat(String.java:2020)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:364)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.sun.tools.javac.main.Main.resourceMessage(Main.java:610)
	at com.sun.tools.javac.main.Main.compile(Main.java:543)
	at com.sun.tools.javac.main.Main.compile(Main.java:381)
	at com.sun.tools.javac.main.Main.compile(Main.java:370)
	at com.sun.tools.javac.main.Main.compile(Main.java:361)
	at com.sun.tools.javac.Main.compile(Main.java:56)
	at com.sun.tools.javac.Main.main(Main.java:42)

``

**Comment by mtbc** [comment]
Ouch! It's fine for me locally; I wonder which option increases `javac`'s heap size?

**Comment by mtbc** [comment]
(It's a pity I can't remove a bunch of deprecated classes in this same PR. :smiley:)

**Comment by mtbc** [comment]
In my `etc/local.properties` is,
```
javac.maxmem=4g
javadoc.maxmem=4g
```
Perhaps these are what allow me to build.

**Comment by mtbc** [comment]
I seem to be able to build Blitz just fine without these, but would it be acceptable for this PR to bump them up to 2GB in `etc/build.properties`? They haven't been increased since April 2013.

**Comment by jburel** [comment]
``build-dev`` passed with:
``
javac.maxmem=4g
javadoc.maxmem=4g 
package-extra=false
``

**Comment by jburel** [comment]
Tested the following:

* Fresh db creation
* upgrade from 5.3.10 to 5.3.11
* upgrade from 5.2 to 5.3.11

**Comment by mtbc** [comment]
#4807 seems to have fixed Jenkins at least.

**Comment by joshmoore** [comment]
> On my laptop this PR causes my build-dev time to be half as long again as usual.

That sounds scary. I assume all/mostly in the `blitz/` component?

**Comment by jburel** [comment]
We will not include this PR in the m3 tag as indicated on https://trello.com/c/hGtzG74u/94-5-3-0-m3-db
This problem requires further investigation.

**Comment by mtbc** [comment]
@jburel: :+1:
@joshmoore: Pretty sure but I'll check.

**Comment by jburel** [comment]
For people preparing standup, to clarify: the upgrade/creation of DB works, the problem is the build time.

**Comment by mtbc** [comment]
@joshmoore: This PR extends my `build-dev` time from 366s to 508s, an increase of 142s. The bulk of this is indeed spent in compiling blitz's classes which took 46s before and 158s after, a large increase of 112s.

**Comment by mtbc** [comment]
I tried slipping `<compilerarg value="-XDcompilePolicy=bytodo"/>` into the `javac` in `lifecycle.xml` but it didn't help.

**Comment by mtbc** [comment]
Tried with latest Oracle 1.8.0_102-b14, still slow.

**Comment by mtbc** [comment]
This PR causes Blitz to grow by adding 540 classes (names attached) to the autogenerated omero.model package.
[classes.txt](https://github.com/openmicroscopy/openmicroscopy/files/451977/classes.txt)

**Comment by mtbc** [comment]
* 270 of these classes, some of the callbacks, just extend another without adding anything.
* 162 of these classes, the rest of the callbacks, just get a proxy, get something from it, and provide it in their response.
* 54 of these classes, the holders, just create a trivial class whose field holds a given list.
* 54 of these classes, the helpers, read and write lists.

**Comment by mtbc** [comment]
Some googling suggests that https://bugs.openjdk.java.net/browse/JDK-8051946 may be relevant and is fixed in https://jdk9.java.net/download/.

**Comment by mtbc** [comment]
@jburel fixed the OMERO build for JDK 9 and this PR much extends build time even with Oracle JDK build 9-ea+133. So much for that hypothesis.

**Comment by mtbc** [comment]
I have no good way to proceed at present.

**Pull request closed without merging**
