### PR TITLE
Roi annotations

### PR DESCRIPTION
**Pull request by dominikl**
This is @jburel 's ROI Annotations PR #3928 rebased onto decoupling branch

--exclude for now until decoupling is merged into develop
--breaking

### CODE REVIEW

**Comment by jburel** [comment]
@dominikl:conflict

**Comment by dominikl** [comment]
Thanks @jburel , fixed the typo; unfortunately after rebase (to resolve the merge conflict) and push -f your comment disappeared.

**Comment by jburel** [comment]
@dominikl: no problem

**Comment by mtbc** [comment]
To preserve PR discussion one may `git fetch origin ; git merge remotes/origin/develop` or similar rather than rebasing; then the push needn't be forced.

**Comment by pwalczysko** [comment]
Problems detected on the original PR https://github.com/openmicroscopy/openmicroscopy/pull/3928#issuecomment-121631222 and https://github.com/openmicroscopy/openmicroscopy/pull/3928#issuecomment-121634150 - probably worth to retest these workflows after the exclude label is removed.

**Comment by jburel** [comment]
Closing for now.
This will come after decoupling
see also gh-3928

**Pull request closed without merging**
