### PR TITLE
Add test_table_bitmask

### PR DESCRIPTION
**Pull request by will-moore**
Tests for PR: https://github.com/ome/omero-web/pull/308

Updated today after discussion with @kkoz

### CODE REVIEW

**Comment by will-moore** [comment]
@kkoz Fixed this test and added testing of the `col_name` parameter.

**Comment by jburel** [comment]
--exclude

**Comment by will-moore** [comment]
Tests are currently passing at https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/931/testReport/OmeroWeb.test.integration.test_table/TestOmeroTables/

**Comment by joshmoore** [comment]
Did this get missed for merge?

**Comment by will-moore** [comment]
Yes - please merge.

**Comment by jburel** [comment]
Yes, Thanks for spotting
Merging

**Pull request merged**
