### PR TITLE
Use omero web config nginx-development in homebrew install

### PR DESCRIPTION
**Pull request by manics**
Part 2 of https://github.com/openmicroscopy/openmicroscopy/pull/3326 (separate PR due to conflict)

--no-rebase
--depends-on #3326

### CODE REVIEW

**Comment by mtbc** [comment]
Travis failure.

**Comment by jburel** [comment]
restarted

**Comment by mtbc** [comment]
Failed again.

**Comment by sbesson** [comment]
Excluding since the Homebrew job currently tests 5.1.0-m3 which does not contain this change.

**Comment by sbesson** [comment]
To be opened against https://github.com/ome/omero-install post 5.1.0-m4 release.

**Pull request closed without merging**
