### PR TITLE
Fix long lines wrapping in generated rST configuration

### PR DESCRIPTION
**Pull request by sbesson**
This PR should fix the long comma-separated properties display in the generated Sphinx configuration and unify the formatting of the default values (using single back quotes).

To test this PR, build the Sphinx documentation including the auto-generated branch https://github.com/snoopycrimecop/ome-documentation/tree/dev_5_0/merge/autogen and check long properties e.g. `omero.search.excludes` are properly wrapped when resizing the window.

This also unifies the `config_parser.py` and `web_parser.py` into a single `PropertyParser` with multiple `parse_xxx` methods.

### CODE REVIEW

**Comment by joshmoore** [comment]
Hmmm...looking at these, do we need to refactor out to a helper method?

**Comment by sbesson** [comment]
Definitely. @aleksandra-tarkowska is there a reason why we have a separate `web_parser.py`. You okay if I move the class to `config_parser.py` ?

**Comment by aleksandra-tarkowska** [comment]
@sbesson sure, that is not a problem

**Comment by sbesson** [comment]
See https://github.com/snoopycrimecop/ome-documentation/commit/a70a517bbc237256edf37a3e879d8de1beef71c5

**Comment by sbesson** [comment]
Also built for review at https://www.openmicroscopy.org/site/support/omero5.1-staging/sysadmins/config.html

**Comment by rleigh-dundee** [comment]
The code changes and generated docs look fine to me.  Good to merge.

**Comment by hflynn** [comment]
Yep, much improved, thanks! Good to merge from me too.

**Pull request merged**
