### PR TITLE
slack notification

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
This PR allows to set up custom notification using slack using http://django-slack.readthedocs.io/

To test:

- `pip install django_slack`
- generate your token https://api.slack.com/web#authentication
- set up config:

 ```
 bin/omero config set omero.web.debug false
 bin/omero config set omero.notify.slack.enabled true
 bin/omero config set omero.notify.slack.token "xoxp-123token..."
 bin/omero config set omero.notify.slack.channel "#logs"
 bin/omero config set omero.notify.slack.username "abc"
 ```
- add weberror app for testing
- start web and enjoy slack :)

Additional testing: I also cleaned up email notification
-  set the following:

 ```
bin/omero config set omero.web.debug False
bin/omero config set omero.mail.config true
```
 *mail config is not named `enabled` but `config` because property name is matching server side property*

- add weberror app for testing
- set mail config https://www.openmicroscopy.org/site/support/omero5.2/sysadmins/mail.html or use local SMTP mock (you will not get real email, just console output):
    - set ```bin/omero config set omero.mail.from "your@email``` and ```bin/omero config set omero.mail.host "localhost"```
    - run in new console SMTP mock ```sudo python -m smtpd -n -c DebuggingServer localhost:25```. *Email message will be shown as a plane text on your console.*
- set your email in ```bin/omero config set omero.web.admins '[["Username", "your@email"]]'```
- try to get HTTP500 and 404 (must come from broken link in template, do not access random url) and see if you received both errors by email

**NOTE:** property name change `omero.slack.*` to `omero.notify.slack.*`

### CODE REVIEW

**Comment by aleksandra-tarkowska** [comment]
--rebased-to #4699

**Comment by manics** [comment]
internal 404 links work as expected.

`omero.slack.fail_silently=false` doesn't seem to report errors anywhere- I tried setting an incorrect channel name:

```
omero.slack.channel=#nonexistent-channel
omero.slack.enabled=true
omero.slack.fail_silently=false
omero.slack.username="xxx \\ yyy"
```

**Comment by manics** [comment]
Also successfully tested email notifications for 404s.

Note I'm testing with https://github.com/openmicroscopy/openmicroscopy/pull/4699

**Comment by manics** [comment]
What's the plan for this? Merge and deploy at the next IDR release?

**Comment by joshmoore** [comment]
Except for the few remaining API (i.e. property naming) discussions on the mainline, I could see merging this and then adapting the config between metadata52 and develop as needed.

**Comment by aleksandra-tarkowska** [comment]
could we agree on property name https://github.com/openmicroscopy/openmicroscopy/pull/4699#issuecomment-224321671?

**Comment by aleksandra-tarkowska** [comment]
if we are not sure, then I will move them to DEVELOPMENT section to make the invisible.

**Comment by manics** [comment]
I vote for `omero.notify.slack`

**Pull request closed without merging**
