### PR TITLE
web requirements

### PR DESCRIPTION
**Pull request by atarkowska**
# What this PR does

reduce requirements.txt to minimum

# Testing this PR

check if non of the jobs failed

# Related reading

--depends-on https://github.com/openmicroscopy/management_tools/pull/328

### CODE REVIEW

**Comment by aleksandra-tarkowska** [comment]
--exclude

**Comment by aleksandra-tarkowska** [comment]
excluding until https://trello.com/c/IpCSdO5Q/2951-default-ice-version

**Comment by jburel** [comment]
one question on management_tools w.r.t. redis

**Comment by jburel** [comment]
Changes match what was discussed. Looks good

**Comment by jburel** [comment]
We will a final change when omero-marshal is released but that can be done in another PR

**Comment by jburel** [comment]
merging

**Pull request merged**
