### PR TITLE
Read only tables develop

### PR DESCRIPTION
**Pull request by jburel**
# What this PR does

Rebased gh-4916

HDF5 tables that are copied into place, read-only, should still be accessible via the OMERO.tables API.

# Testing this PR

1. Create an OMERO.tables file (e.g. with populate_metadata)
2. `chmod a-w` on the file under `/OMERO/Files`
3. Try to open the file via `openTable`
4. Without this PR, the open will fail with an `IOError`. With this PR, the file will be opened but not be writable.

# Related reading

* https://trello.com/c/H0tV3G7h/5-read-only-omero-tables
* https://trello.com/c/cKEf9iDK/240-other-metadata52-rebases

cc @joshmoore @manics

### CODE REVIEW

**Comment by jburel** [comment]
Back to normal
https://ci.openmicroscopy.org/job/OMERO-DEV-merge-integration-python/490/ is green

**Comment by pwalczysko** [comment]
Will need one more day at least to test this.

**Comment by jburel** [comment]
@pwalczysko: no problem

**Comment by pwalczysko** [comment]
Did the setup locally as described in the header of this PR (this PR is included).
Created the tables file on ``mias/frans/siRNA..`` plate, noted the ID (620) and did the ``chmod a-w``.
After ``bin/omero shell --login`` I used the sequence of commands as on the Trello card. My output was

```
In [1]: client
Out[1]: <omero.clients.BaseClient at 0x110fc0a50>

In [2]: import tables

In [3]: table = client.sf.sharedResources().openTable(omero.model.OriginalFileI(620, False))

In [4]: table
Out[4]: A9CEC001-140B-4420-ACBE-BA0F0668F533 -t -e 1.0 @ Tables-0.TablesAdapter

In [5]: table.close()
```

I think this shows that the positive test (with this PR) passes. Is there a need to do the bug repetition without this PR ?

Edit: consulted it, the test should suffice. Ready to merge FMPOV.

**Pull request merged**
