### PR TITLE
use narrower reflective operation exception

### PR DESCRIPTION
**Pull request by mtbc**
Should be no change in behavior, largely tested by if the code compiles at all.

--no-rebase as Java 6 does not offer `ReflectiveOperationException`

### CODE REVIEW

**Comment by jburel** [comment]
All files modified.
This is Java 1.7 specific.
see gh-4015 for 1.7 being the minimum

**Comment by mtbc** [comment]
So basically, good once #4015 is good?

**Comment by jburel** [comment]
@mtbc: yes.

**Comment by mtbc** [comment]
:+1: Makes sense.

**Pull request merged**
