### PR TITLE
View well

### PR DESCRIPTION
**Pull request by jburel**
Keep origin of the image i.e. if the image is going from Well sample
This will allow the loading of ROI measurements when the mt is opened. cc @joshmoore 
To test;
 * Make sure you can open a standard image (right-click ,toolbar, double click, right-hand panel: general/preview)
* Make sure you can open an image from well sample (right-click , double click, right-hand panel)

To test the roi measurements section, the annotation will either have to be linked to plate cc @manics  or @joshmoore will open a PR to adjust the query in ROIService

@manics has linked the file to the plate
Looking closely at the query, the table also needs to be linked to the roi in order to work. This could potentially imply a lot of links
@manics is going to add the links to the roi so we can test it. This will not be part of the IDR import script

### CODE REVIEW

**Comment by manics** [comment]
All ROIs in http://dogfish.openmicroscopy.org/webclient/?show=plate-151 should now be linked to the table

**Comment by jburel** [comment]
Still no luck, no measurement returns when using ```getRoiMeasurements```

**Comment by joshmoore** [comment]
--rebased-to #3938

**Comment by sbesson** [comment]
Excluding in order to test the Java gateway work.

**Pull request closed without merging**
