### PR TITLE
prevent from editing map annotations in batch_annotation pane

### PR DESCRIPTION
**Pull request by atarkowska**
# What this PR does

partial rebase from https://github.com/openmicroscopy/openmicroscopy/pull/4923
only commits related to metadata panel

# Testing this PR

1. Login to web
2. Select multiple images
3. check if editing mode is not available on key-value pairs. Maps should be present

### CODE REVIEW

**Comment by pwalczysko** [comment]
This PR might have introduced a regression in Right-hand-pane when multiselection of objects is performed, see https://github.com/openmicroscopy/openmicroscopy/pull/4910#issuecomment-261908493

**Comment by atarkowska** [comment]
@joshmoore, @eleanorwilliams heads up, @will-moore added quickly a way to display which map belongs to which object (when multiple selected). Do we want to style it, move to tooltip?

firefoxscreensnapz019

**Comment by eleanorwilliams** [comment]
Not sure we would want to show this to IDR users, but would be useful for us to see.  In the case of mapr, would it display multiple sources if the de-duplicated annotation is linked to many images or would it show the first one the annotation was linked to?

**Comment by atarkowska** [comment]
@eleanorwilliams try http://10.0.51.150/web/webclient/?show=screen-3|screen-102, Certainly I will update mapr to do similar :)

**Comment by atarkowska** [comment]
@jburel this PR has a wrong label, in case it matters

**Comment by joshmoore** [comment]
Fixed the label; it doesn't have any impact in terms of builds but to prevent confusion.

**Comment by atarkowska** [comment]
tested in https://github.com/openmicroscopy/openmicroscopy/pull/4923#issuecomment-263884540 (this is a partial rebase PR to keep two branches in line)

**Comment by joshmoore** [comment]
Looks good. Thanks, @aleksandra-tarkowska. This will be in the upcoming 0.3.1 release.

**Pull request merged**
