### PR TITLE
chgrp 'not included' warning

### PR DESCRIPTION
**Pull request by will-moore**
See: http://trac.openmicroscopy.org/ome/ticket/12965
Webclient warns when you will lose lined annotations or child objects during chgrp.

Test setup:
 - Add a bunch of annotations to P/D/I S/P/W - including some which ARE expected to chgrp with the data (Comments, MapAnnotations etc) and some of which are NOT expected to chgrp with the data, e.g. Tags, Multi-linked Files, Comments.
 - Also put some images in multiple Datasets (so that when you chgrp one Dataset, some images will be left behind).
 - Also, perform an image projection or Images_From_ROIs script or Channel_Offsets script so that some images will give an error on chgrp.
 - Also, find a Multi-Image Fileset.

 To test, try chgrp with different selections of your P/D/I S/PW data and you should be warned if:
 - You try to move a P/D/S that will not include some child data (E.g. if images in multiple Datasets - you will get a message showing the number of Images, and a tool-tip of all their names) - see screenshot.
 - Your chgrp will lose annotations from the Data - warning will name the tags and files and will simply number the Comments and any Others.
 - Trying to split a MIF, you will see the existing warning and have the "Move All" button. The warning of lost annotations etc should apply to ALL the images in the Fileset (not just the ones you chose to move).
 - If you try to move an image that has been projected etc, you should see a warning with suitable links to the images in question and the "OK" button will be hidden.

screen shot 2015-09-14 at 17 13 45

screen shot 2015-09-15 at 10 42 06

### CODE REVIEW

**Comment by jburel** [comment]
This PR touches several files including gateway.
@will-moore could you add some tests? so the PR can be considered.

**Comment by will-moore** [comment]
@jburel Yes - I was certainly intending to add robot and web tests, but wanted to get other 5.1.4 PRs open first.
This PR doesn't actually modify the Blitz Gateway itself (just the web sub-class of it).

**Comment by jburel** [comment]
understood

**Comment by pwalczysko** [comment]
In the warning in the second screenshot in the header, the formulation goes:
``...may not move....``
Replace with something more definite like
``...will not move...``
or 
``...not possible to move``

**Comment by will-moore** [comment]
@pwalczysko That message comes from the server - I'm just displaying it!
I guess I could replace "may not move" with "Cannot move", but there are probably a bunch of other server errors I could be getting here? @mtbc?

**Comment by pwalczysko** [comment]
screen shot 2015-09-16 at 14 51 21

In the screenshot above, 2 issues:

  - as it is now displayed, it makes the impression that the ``No Project`` line somehow continues in the sense of ``No Project will be moved`` - this is not the case and is confusing (needs probably some reformatting ? 

  - Why do I get the warning that ``0 Files`` are not being moved ? (inconsistent with other entities, like Comments, when no problem is there, no warning is displayed)

**Comment by mtbc** [comment]
Yes, certainly other server errors may come up. It's "may" rather than "can" or "will" because it is about permissions. The server *could* do such a move if it really wanted. It is like that while my children certainly may not secretly spit food out behind the chair, they certainly can, and I hope will not.

**Comment by will-moore** [comment]
"You cannot do that move here" (even if you could do it in some other way). But this message is not about permissions, it's about multiple images linked to the same instrument.

**Comment by pwalczysko** [comment]
@mtbc : I guess we shouild give the user more certainty - imho in the situation which he is at the timepoint of the warning, this does mean Cannot, Will not and will be executed as such, no ifs or buts ? (admin might later do this and that, but this is of no concern actually . I think this comment just reiterates what @will-moore just wrote above.

**Comment by mtbc** [comment]
It's permissions that prevent the cross-group link issue underlying this.

@pwalczysko: These messages from the server are intended for developers, not for end users, they just happen to be the best we have at the moment. This is https://trello.com/c/F4cAE0k3/358-graphexception-subclasses again.

**Comment by mtbc** [comment]
@pwalczysko: "may" has multiple meanings: possibility and permission are distinct meanings of it (there are also others).

**Comment by mtbc** [comment]
So, part of the discussion on the card relates to that the server *could* give some subclass of the exception in certain situations that clients could recognize and describe however they like. It'd not be trivial, and is outwith this PR, but it's certainly something that could happen if prioritized sufficiently.

**Comment by will-moore** [comment]
@pwalczysko I think all your issues above are now fixed:

screen shot 2015-09-16 at 15 31 31

**Comment by pwalczysko** [comment]
All other tests passed. @will-moore will have a look at the commits tomorrow.
Some failed travis checks reported above.

**Comment by pwalczysko** [comment]
All good here from the UI point of view. Good to merge after the test fixing commits (the last two) are okayed.

**Comment by will-moore** [comment]
I started to look at robot tests for this (see below) but since this will involve adding new methods for traversal of the old jsTree, it seems best to hold off on this for 5.1.4 and add these tests to 5.2 where we have new robot keywords for working with the new jsTree.
Instead, I'll look at web integration tests.

Started work on robot setup script, to create suitable data for chgrp warnings...
```
MIF_IMAGE_NAME=${MIF_IMAGE_NAME:-mif&series=3.fake}
...
# Create Dataset with MIF images for chgrp
chgrpDs=$(bin/omero obj new Dataset name='Chgrp')
for (( k=1; k<=3; k++ ))
do
  bin/omero import -d $chgrpDs $MIF_IMAGE_NAME --debug ERROR
done
# Put this Dataset into two Projects (to test chgrp warning)
chgrpPr1=$(bin/omero obj new Project name='Chgrp1')
chgrpPr2=$(bin/omero obj new Project name='Chgrp2')
bin/omero obj new ProjectDatasetLink parent=$chgrpPr1 child=$chgrpDs
bin/omero obj new ProjectDatasetLink parent=$chgrpPr2 child=$chgrpDs
```

**Comment by will-moore** [comment]
The last commit fixes a bug where (for example) a single Dataset is in 2 Projects and you try to Move 1 of the Projects to another group.

**Comment by sbesson** [comment]
The assert in the new integration test failed (type conversion) - see https://ci.openmicroscopy.org/view/Failing/job/OMERO-5.1-merge-integration-web/436/testReport/test.integration.test_chgrp/TestChgrp/test_chgrp_dry_run_user_/

**Comment by will-moore** [comment]
Test: Single Dataset in 2 Projects - try to Move 1 of the Projects - see if message displays as expected (only 1 Project will move).

**Comment by mtbc** [comment]
https://ci.openmicroscopy.org/job/OMERO-5.1-merge-integration-web/lastCompletedBuild/testReport/test.integration.test_chgrp/TestChgrp/ :+1:

**Comment by gusferguson** [comment]
@will-moore 

Tested using trout merge user-3 read-only-1 and read-annotate-1
Behaves as expected.
Good to merge.

**Pull request merged**
