### PR TITLE
Lut webclient

### PR DESCRIPTION
**Pull request by will-moore**
# What this PR does

This adds Look-up Table (LUT) support in webclient, equivalent to #4764 in Insight.

# To test

This needs a full test of rendering settings, including selection of LUTs. Including:
 - Click colorpicker button, choose regular color (Red, Green etc) OR LUT OR pick with colorpicker.
 - Save, Undo/Redo, Apply To All
 - Copy / Paste of rendering settings (in Preview Pane and tree right-click menu)
 - Open Full image viewer (use button in Preview pane - current (unsaved) settings should be applied in full viewer) and test colorpicker & LUTs here too.

Webgateway API changes: cc @chris-allan 
I have added "lut" to the ```channelMarshal()``` so we have that in the ```imgData``` json if LUT is set:
```
channels: [
    {
        lut: "orange_hot.lut",
        color: "0000FF",
        emissionWave: 457,
        label: "DAPI",
        window: {
            max: 1323,
            end: 996,
            start: 172,
            min: 0
        },
        active: true
    },
```
For rendering images and elsewhere in the JavaScript code, I have used the LUT string in place of the color string since these are mutually exclusive:
E.g.  ``` ?c=1|172:996$16_colors.lut,2|23:1330$00FF00 ```
NB: LUT names containing ```, | $ :``` would break the parsing of this string. Will look into this more.

The Blitz Gateway changes handle this in ```image.setActiveChannels()``` where the ```colors``` parameter can include "cool.lut" strings as well as"FF0000".

ChannelWrapper has a ```getLut()``` which returns the name of the LUT.

Channel Buttons:
I have tried a couple of different approaches for rendering channel buttons with LUTs. If buttons are beside slider (which shows LUT) then maybe we don't need button to have LUT background since text is harder to read. However, in Image Viewer window, channel buttons aren't shown beside sliders. Here I have tried to use the centre of a "stretched" LUT as background, since this provides a smoother background color (allowing label to be read) which still giving an indication of the LUT. 
Thoughts?

screen shot 2016-08-02 at 13 42 35

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#400](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/400/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/400/consoleText) for more details.
Possible conflicts:
  - PR #4703 will-moore 'histograms'
    - components/tools/OmeroWeb/omeroweb/webgateway/static/webgateway/js/omero_image.js
  - PR #4766 will-moore 'Rgb to hex'
    - components/tools/OmeroWeb/omeroweb/webgateway/static/webgateway/js/omero_image.js

**Comment by will-moore** [comment]
Rebased on top of https://github.com/openmicroscopy/openmicroscopy/pull/4766 to fix merge conflicts.

**Comment by will-moore** [comment]
Last commit allows LUT names with any characters except comma. E.g. ```re.d$g-r|e:en.lut``` is parsed as a color / lut name.

**Comment by gusferguson** [comment]
@will-moore 

Tested using https://cowfish.openmicroscopy.org/webmerge/webclient/ user-3 read-only-1 Safari
Also tested on iPad Safari.

Selection of LUT as channel colour is not changing the colour of the channel at all in either Preview or Full Viewer or thumbnails - has the backend not been implemented yet?

With all selections - colour, LUT, color picker, all save, save to all, copy, paste and undo are working as expected in Preview, Full Viewer and data tree right-click menu

Background of buttons to left of slider are all appearing grey with LUT selected - do not reflect LUT - I think this is probably the best approach as the slider shows the LUT.
I think the button background “stretch” in the full-viewer to be a good compromise, although with darker LUTs the text is lost - as it is with pure blue colour etc.

Issues:

Tested using ID 24755:
- changed colour on top 3 channels using basic colours - red - blue - white - worked as expected
- fourth channel used “colour picker” selection - behaved as expected - colour changed successfully
- returned to other channels - on clicking colour picker icon, only “color picker” palette offered - if colour selected - click OK - no change to colour of channel
- cannot get default menu to appear for any channel - stuck in  “color picker” palette for all channels - see screenshot 1
- only changes to fourth channel are saved on clicking OK
- had to close and reopen client to reset - does not reset with Save or with selecting another image
- reproducible for any channel selection
- only when testing in Full Viewer did I see the large text “Hide Color Picker” above the colour wheel - as it is blue in this location
- returning to Preview pane, saw text above wheel, but it is far from obvious and does not look clickable.

This is the first time I have "got stuck” in the color picker palette and it is a bad interaction trap
- I think the colour picker palette should not be default after it has been selected once and particularly not after saving or changing image
- I could not reproduce the selection in the colour pickernot being saved that I experienced the first time, but it definitely happened.

The drop-down menu presented on clicking the colour picker on a channel is not returning to the default position after a different channel or new image are selected - if you have scrolled down to the bottom of the LUT list, it shows at that position at every selection afterwards.
Presuming this is deliberate, I can see how it might be useful if you were wanting to select the same LUT for different images in the dataset as it means you don’t have to scroll to it each time, but I think a few other people’s opinions need to be sought, as I would prefer it to default to original.

**Comment by gusferguson** [comment]
Screenshots of above issue:

screenshot 1

**Comment by jburel** [comment]
The backend changes are in "breaking" at the moment due to some tests failures. 
I should be able to remove it out of breaking this evening.

**Comment by will-moore** [comment]
@gusferguson @dominikl @jburel I tried using ```opacity 0.3``` for LUT backgrounds and it seems to work OK. All buttons now consistent (and range slider has LUT/color background over it's full length (same as Insight)

screen shot 2016-08-05 at 09 27 04

**Comment by jburel** [comment]
@will-moore: I think that will work for the button

**Comment by gusferguson** [comment]
@will-moore - I think that works well for indicating that it is an LUT.

**Comment by will-moore** [comment]
@gusferguson that last commit should improve showing of colorpicker. Now, we always show the list of colors and LUTs when the dialog is opened. The positioning of the dialog should also be better (not too low on screen now).

**Comment by gusferguson** [comment]
@will-moore 

Tested with https://cowfish.openmicroscopy.org/webmerge/webclient/ user-3

I think the behaviour of the colour picker is now as expected.
All other functionality behaving as expected.

Good to merge from my POV.

**Comment by jburel** [comment]
the static png representing the lut will need to be regenerated https://github.com/openmicroscopy/openmicroscopy/pull/4753/commits/686da3f909a04b9e5a946ecc6da83b1f34f8d57d
Another reason to find a better solution.

**Comment by jburel** [comment]
@will-moore: I have added few more luts see https://github.com/openmicroscopy/openmicroscopy/pull/4753/commits/14a23d3e4cdece8f3023037126cb2a9d0a60dd2c

**Comment by pwalczysko** [comment]
RFE: Why do I have to click here (see screenshot below) onto the text (the line is not enough, i.e. when clicking next to a short-named LUT texts like "cool", nothing happens). With this is connected: there is no feedback whether or not my click was effective or not other than the actual change of the LUT in the image and slider.

screen shot 2016-08-10 at 15 40 16

**Comment by pwalczysko** [comment]
The Histogram on the LUT is grey (not coloured).

**Comment by pwalczysko** [comment]
Other than the two RFEs https://github.com/openmicroscopy/openmicroscopy/pull/4767#issuecomment-238899461 and https://github.com/openmicroscopy/openmicroscopy/pull/4767#issuecomment-238888678 all good here.

**Comment by will-moore** [comment]
@pwalczysko I've fixed the clicking on LUT - even with short names you can click anywhere on the line. And added a hover effect to make this clearer.
For the histogram, I don't think we want to color the whole histogram with stripes like a LUT (would also be very tricky), so we just need to use a default color. However, I notice that the histogram color is not updating when channel color is changed - so I'll look into that on #4703.

**Comment by pwalczysko** [comment]
Is the robot failure somehow connected with this work ? https://ci.openmicroscopy.org/job/OMERO-DEV-merge-robotframework/358/robot/

**Comment by gusferguson** [comment]
@will-moore 

Colour/LUT selection much better with changes above.

Note: Histogram issue being addressed in https://github.com/openmicroscopy/openmicroscopy/pull/4703 - which failed Travis so histograms not present in this build.

Good to merge.

**Comment by jburel** [comment]
knows issue added to https://trello.com/c/9iAe3Sg9/95-lut-support

**Comment by jburel** [comment]
Thanks all merging

**Pull request merged**
