### PR TITLE
Pyramid generation

### PR DESCRIPTION
**Pull request by jburel**
# What this PR does

Propagate BF change to OMERO pyramid generation

# Testing this PR

Import QA https://www.openmicroscopy.org/qa2/qa/feedback/18868/

# Related reading

https://trello.com/c/o3Ro0GXT/24-omero-import-large-tiffs-issue

cc @sbesson @dominikl @dgault

### CODE REVIEW

**Comment by sbesson** [comment]
NB: https://github.com/openmicroscopy/bioformats/pull/2319/commits/884bb81aa078180d259d235d8b7c03417447a8a4 is the commit released in Bio-Formats 5.2.0 where TiffWriter was updated to retrieve the value of `PixelBigEndian` rather than `PixelsBinDataBigEndian`

**Comment by dominikl** [comment]
Looks good! But I guess code review needs a bioformats person.

**Comment by dgault** [comment]
This change makes sense from a Bio-Formats perspective. When we did the last batch of code generation work we added Bin Data to the generation process rather than previously hardcoded functions. The hardcoded functions originally had logic when retrieving and setting `PixelsBinDataBigEndian` to read and write the BigEndian value to and from Pixels instead. 

The updated behaviour here matches those changes and looks to be correct.

**Comment by jburel** [comment]
Thanks @dgault and @dominikl for review
Merging

**Comment by pwalczysko** [comment]
@jburel So ``bin/omero admin removepyramids --little-endian`` is not working.

```
bin/omero admin removepyramids --little-endian
usage: bin/omero admin [-h] <subcommand> ...
bin/omero admin: error: argument <subcommand>: invalid choice: 'removepyramids'

choose from:
	checkice, checkupgrade, checkwindows, cleanse, deploy, diagnostics, 
	email, events, fixpyramids, ice, jvmcfg, log, reindex, restart, 
	restartasync, rewrite, sessionlist, start, startasync, status, 
	stop, stopasync, waitdown, waitup
```

Did you mean ``bin/omero admin fixpyramids`` ? (Re: testing sheet https://docs.google.com/spreadsheets/d/1lI4jVmocE-DuQhxS_EMqjcI2UeNrAoIq1TgM5HlIPnY/edit#gid=1254367109 line 10

**Comment by jburel** [comment]
``bin/omero admin removepyramids --little-endian`` has not been merged yet and it has to be run  against devspace server.
that's why it is on hold for the testing
see https://github.com/openmicroscopy/openmicroscopy/pull/5659

**Pull request merged**
