### PR TITLE
5.1.4 version history (rebased onto develop)

### PR DESCRIPTION
**Pull request by hflynn**
This is the same as gh-4198 but rebased onto develop.

----

Initial stab at picking out relevant content. Will add blog post link for webstart once I get that sorted, hopefully later today.

### CODE REVIEW

**Comment by hflynn** [comment]
--rebased-from #4198

**Comment by hflynn** [comment]
I assumed we were keeping the doc complete even though 5.1.4 won't exist on this branch.

**Comment by sbesson** [comment]
:+1:

**Comment by sbesson** [comment]
Deployed at https://www.openmicroscopy.org/site/support/omero5.2-staging/users/history.html.

**Pull request merged**
