### PR TITLE
Deprecated methods

### PR DESCRIPTION
**Pull request by jburel**
Replace usage of Chgrp by Chgrp2, Delete by Delete2
and remove usage of deleteObjects method.
To test
Check that https://ci.openmicroscopy.org/job/OMERO-5.1-merge-integration-java/ is green

### CODE REVIEW

**Comment by dominikl** [comment]
Looks fine to me, integration tests are passing. Found some deprecated method/class usages in tests which are marked as broken, or in methods which are - as far as I could see - just used by broken tests, guess that's fine.
Only 'issues' I could find are:
- Found one not-broken test with deprecated method usage: `testDeleteImageViewedByOtherWithThumbnailOnDiskRWRW()`, see `DeleteServiceFilesTest.java:697`
- `CreatePojosFixture2.deleteAllPojos()` (line 167) uses deprecated `iUpdate.deleteObject(..)` but is not used anywhere, could be removed
- `AnnotationDeleteTest` and `DeleteServicePermissionsTest` still import deprecated `omero.cmd.Delete`, but not used, could be removed, too.

**Comment by jburel** [comment]
@dominikl:everything should now be removed.

**Comment by dominikl** [comment]
Looks good. Just the Delete and DeleteRsp imports can be removed from `DeleteServiceFilesTest.java
`, being a bit nit-picky ;)

**Comment by jburel** [comment]
@dominikl: thanks. Will remove that.

**Comment by jburel** [comment]
@dominikl: done

**Comment by dominikl** [comment]
Then it's good to merge, I think. Tests were passing this morning and the removed unused import statements in the last commit really shouldn't affect the tests in any way.

**Comment by jburel** [comment]
@dominikl: added an extra commit, ref in the header of a method no longer used.

**Comment by dominikl** [comment]
Looks fine. Integration test job also still passing. Good to merge.

**Comment by sbesson** [comment]
https://ci.openmicroscopy.org/job/OMERO-5.1-merge-integration-java/414/ is green. Thanks.

**Pull request merged**
