### PR TITLE
Cleanup outdated quickstart doc files

### PR DESCRIPTION
**Pull request by sbesson**
See https://trac.openmicroscopy.org.uk/ome/ticket/1702

All the installation files have been moved to https://github.com/ome/omero-install

### CODE REVIEW

**Comment by manics** [comment]
`docs/hudson/OMERO-start.bat` references `docs\QUICKSTART.bat`, so it should probably go, along with `docs/hudson/OMERO-start.sh`

**Comment by joshmoore** [comment]
:thumbsup: Likely much `docs/hudson` can go.

**Comment by sbesson** [comment]
Additional cleanup in `docs/hudson` in the last commit. This should got through one more round of the merge CI stack to make sure we did not remove any used file.

**Comment by manics** [comment]
Merge builds look good.

**Pull request merged**
