### PR TITLE
Deprecate projection ui

### PR DESCRIPTION
**Pull request by jburel**
# What this PR does

This PR is solely to visualize the projection along T

Not for review:
TEST PR

# Testing this PR

 * Log in as user-1
 * open ``5.0 data/ome-tiff/multi-channel-4D-series.ome.tif`` in the viewer
 * go to the projection tab, move the z-sliders
The z-interval is used to set the t-interval to project

Only the projection preview has been modified

# Related reading

See https://github.com/openmicroscopy/openmicroscopy/pull/5042

@mtbc @dominikl

### CODE REVIEW

**Comment by mtbc** [comment]
With `2chZT.lsm` when I "click here to create a projection preview" it says that "An error has occurred while projecting the data" and the viewer is then hung.

**Comment by jburel** [comment]
Due to the change I made, you can only use some specific images: number of t > number of z and both greater than 1.
You can validate with the image indicated in the description

**Comment by mtbc** [comment]
Yes, with `multi-channel-4D-series.ome.tif` it is working fine. Just wasn't sure if the other issue was a problem with this PR or the other!

**Comment by jburel** [comment]
Closing this PR. "Visual inspection" done today by @mtbc

**Pull request closed without merging**
