### PR TITLE
Feedback upgrade

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
This PR upgrades url library to send feedback

To test:
- open private/incognito window to avoid web browser cache.
- go to https://eel.openmicroscopy.org/merge/weberror/error_500/ | https://cowfish.openmicroscopy.org/merge/weberror/error_500/
- send feedback
- check new feedback in https://qa.staging.openmicroscopy.org/

cc @sbesson @pwalczysko

### CODE REVIEW

**Comment by pwalczysko** [comment]
Test both feedback and error on 

  - eel merge
  - burbot merge

**Comment by pwalczysko** [comment]
Testing feedback: 
  - eel merge -> Pass
  - burbot merge -> Fail (via url not possible to access, via the form in the UI I get ``    Feedback could not been sent. Please contact administrator.``

**Comment by sbesson** [comment]
Tested on burbot/latest using 5.1.4 ([deployment job](https://ci.openmicroscopy.org/view/DEV/job/OMERO-DEV-latest-deploy-win2012/11/) - QA 16873) and 5.2.0-rc1 ([deployment job](https://ci.openmicroscopy.org/view/DEV/job/OMERO-DEV-latest-deploy-win2012/12/) - QA 16874). Feedback was correctly sent to HTTP in both cases. No regression from that point of view.

Given the current state of the feeback app, adding support for HTTPS feedback on Windows is not a blocker for 5.2.0. It should be fixed before QA3 is put into production though.

**Comment by aleksandra-tarkowska** [comment]
@sbesson I'd argue about that because the same library is used by upgrade check. If registry go to https we will be missing windows from stats then

**Comment by sbesson** [comment]
@aleksandra-tarkowska: absolutely. My comment really applies to registry and feedback but the registry migration will likely precede the QA migration and this PR will be tested as part of this effort.

**Comment by mtbc** [comment]
Since latest commit is further testing needed?

**Comment by aleksandra-tarkowska** [comment]
Sorry for got about this PR. Yes let's test it properly. I will resist it on Monday

**Comment by pwalczysko** [comment]
Testing on eel merge :  going to the ...error_500 link I get
screen shot 2015-12-01 at 10 15 50

**Comment by pwalczysko** [comment]
Testing on cowfish: all as expected.

**Comment by pwalczysko** [comment]
In summary: 
  - eel -> total failure
  - cowfish -> full success

**Comment by aleksandra-tarkowska** [comment]
@pwalczysko https://eel.openmicroscopy.org/merge/weberror/error_500/ works, which url did you go to exactly?

**Comment by aleksandra-tarkowska** [comment]
@pwalczysko wrote:
> https://eel.openmicroscopy.org/weberror//error_500/
> this one gets 404
> that is what I tried

That is oncorrect URL, you are missing ``merge`` and you got double ``//``

**Comment by pwalczysko** [comment]
@aleksandra-tarkowska : Thanks for updating the header. With the correct url on eel, I get the correct result.
All good here.
Ready to merge.

**Comment by sbesson** [comment]
@aleksandra-tarkowska: all looks good. Has this been tested against production upgrade (http) yet or should we have a temporary management_tools PR to check that tomorrow?

**Comment by jburel** [comment]
Merging, to be tested during rc1. i.e. make sure that feedback goes to qa.
cc @pwalczysko

**Pull request merged**
