### PR TITLE
add backlinks to images and wells from annotations

### PR DESCRIPTION
**Pull request by mtbc**
This PR adds properties `imageLinks` and `wellLinks` to `Annotation` in the OMERO model and bumps the database to `5.2` patch `1`.

### CODE REVIEW

**Comment by mtbc** [comment]
So, the trick is, try to get Travis to pass early on a Saturday morning!

**Comment by atarkowska** [comment]
also @jburel restarts works 100% :)

**Comment by joshmoore** [comment]
--exclude

**Comment by aleksandra-tarkowska** [comment]
no need to exclude, my fault not including db upgrade :)

**Comment by joshmoore** [comment]
I have a number of import test failures on 10.0.51.113:

```
   serverExceptionClass = "ome.conditions.OptimisticLockException"
    message = "Object of class [ome.model.annotations.ImageAnnotationLink] with identifier [1138]: optimistic locking failed; nested exception is org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect): [ome.model.annotations.ImageAnnotationLink#1138]"
    backOff = 0
    at ome.formats.OMEROMetadataStoreClient.updatePixels(OMEROMetadataStoreClient.java:2303)
```

Not absolutely sure they're related but this is the only merged PR at the moment.

**Comment by mtbc** [comment]
In a local build of basically develop-latest plus this change, import seems to be working fine for me and the obvious integration tests pass. I don't know how to probe 10.0.51.113: which tests are failing? I'll try building the metadata52-based version locally...

_Update:_ import seems pretty good on metadata52 too, I'm guessing there's a specific way to trigger this one.

**Comment by atarkowska** [comment]
This PR is causing import and delete test regression, since it has been merged to the build these 2 tests are failing on m52

see https://10.0.51.106:8443/job/OMERO-test-integration/94/testReport/

```
Error Message

AttributeError: 'NoneType' object has no attribute 'id'

Stacktrace

self = <test.integration.test_delete.TestDelete object at 0x7c2c590>

    def test5793(self):
        uuid = self.ctx.sessionUuid
    
        img = self.new_image(name="delete tagset test")
    
        tag = omero.model.TagAnnotationI()
        tag.textValue = rstring("tag %s" % uuid)
        tag = self.update.saveAndReturnObject(tag)
    
        img.linkAnnotation(tag)
        img = self.update.saveAndReturnObject(img)
    
        tagset = omero.model.TagAnnotationI()
        tagset.textValue = rstring("tagset %s" % uuid)
        tagset.linkAnnotation(tag)
        tagset = self.update.saveAndReturnObject(tagset)
    
        tag = tagset.linkedAnnotationList()[0]
    
        command = Delete2(targetObjects={"Annotation": [tagset.id.val]})
        handle = self.client.sf.submit(command)
        self.waitOnCmd(self.client, handle)
    
        assert not self.query.find("TagAnnotation", tagset.id.val)
>       assert tag.id.val == self.query.find(
            "TagAnnotation", tag.id.val).id.val
E       AttributeError: 'NoneType' object has no attribute 'id'

test/integration/test_delete.py:393: AttributeError
```

and 

```
Error Message

AssertionError: object #0 (::omero::cmd::ERR) {     category = ::omero::cmd::Delete2     name = graph-fail     parameters =      {         key = stacktrace         value = java.lang.NullPointerException                   key = message         value =      } }

Stacktrace

self = <test.integration.test_delete.TestDelete object at 0x7c49250>

    def testDeleteComment(self):
        comment = omero.model.CommentAnnotationI()
        comment = self.update.saveAndReturnObject(comment)
        images = list()
        # Single Comment linked to 3 Images and 3 Datasets
        for i in range(0, 3):
            img = self.new_image(name="testDeleteComment")
            img.linkAnnotation(comment)
            images.append(self.update.saveAndReturnObject(img))
            ds = self.make_dataset("testDeleteComment")
            ds.linkAnnotation(comment)
            self.update.saveAndReturnObject(ds)
    
        cid = comment.id.val
        assert self.query.find("CommentAnnotation", cid)
    
        # Remove comment from first image
        linkIds = []
        for l in images[0].copyAnnotationLinks():
            linkIds.append(l.id.val)
        command = Delete2(targetObjects={"ImageAnnotationLink": linkIds})
        handle = self.client.sf.submit(command)
>       self.waitOnCmd(self.client, handle)

test/integration/test_delete.py:256: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <test.integration.test_delete.TestDelete object at 0x7c49250>
client = <omero.clients.BaseClient object at 0x7cd5b90>
handle = 1d1e296b-252b-4271-a9a3-e9642e869ba1/IHandle1d3130b9-0c5d-4431-85f0-d43abaf95c98 -t -e 1.0:tcp -h 172.17.0.11 -p 34113 -t 60000
loops = 10, ms = 500, passes = True

    def waitOnCmd(self, client, handle, loops=10, ms=500, passes=True):
        """
            Wait on an omero.cmd.HandlePrx to finish processing
            and then assert pass or fail. The callback is returned
            for accessing the Response and Status elements.
            """
        callback = omero.callbacks.CmdCallbackI(client, handle)
        callback.loop(loops, ms)  # throws on timeout
        rsp = callback.getResponse()
        is_ok = isinstance(rsp, OK)
>       assert passes == is_ok, str(rsp)
E       AssertionError: object #0 (::omero::cmd::ERR)
E       {
E           category = ::omero::cmd::Delete2
E           name = graph-fail
E           parameters = 
E           {
E               key = stacktrace
E               value = java.lang.NullPointerException
E       
E               
E               key = message
E               value = 
E           }
E       }

../../tests/python/library/__init__.py:525: AssertionError
```

**Comment by mtbc** [comment]
Thank you @aleksandra-tarkowska for the pointer! While I'm not sure what's going on there it is probably fixable with some graph traversal fiddling. However, thanks to a discussion @jburel had yesterday with @mporter-gre, I am now realizing that the `OptimisticLockException` reported by @joshmoore may well lead to rather more regressions: when adjusting and resaving model objects from clients, now we may have another collection that one has to worry about unloading or replacing its holder with a proxy or whatever, so this PR may well cause a whole raft of subtle issues with code that was previously fine. I don't know if I'm being too pessimistic on that count.

**Comment by mtbc** [comment]
@joshmoore: You'd agree that this may break client-side code due to requiring extra management of object graph references?

**Comment by joshmoore** [comment]
I would have thought that for most use cases the right thing should just happen. I don't know of specific collection handling for each collection of each object type.

**Comment by mtbc** [comment]
Hmm, I'm worried about the `OptimisticLockException`s from methods like`OMEROMetadataStoreClient.updatePixels` with the underlying `StaleObjectStateException` that CI currently shows.

**Comment by joshmoore** [comment]
Understood, but that code I'd assume fairly internal & advanced. In fact, it may be using direct collection methods. cc: @chris-allan

**Comment by chris-allan** [comment]
Agreed. I would not expect any individual who is not deeply familiar with the internals to be calling those methods.

**Comment by aleksandra-tarkowska** [comment]
--exclude

**Comment by mtbc** [comment]
`clitest/test_import.py` shows failures with `TestImport.testTargetArgument`, I would guess in trying to add the annotation from `TemplateImportTarget.load`, but in trying to understand what is going on I am lost in a twisty maze of metadata store.

**Pull request closed without merging**
