### PR TITLE
CLI web cleanup

### PR DESCRIPTION
**Pull request by sbesson**
This PR does some basic cleanup to the `WebControl` class:

- adds internal `_get_python_dir()` and `_get_templates_dir()` method
- uses monkeypatching instead of defining hidden arguments for testing the templates generation in unit tests
- cleans up the deprecated selenium library/selenium tests and selenium subcommand
- runs `self.clearsessions()` at every start of OMERO.web

--no-rebase

### CODE REVIEW

**Comment by will-moore** [comment]
@sbesson Not sure what the implications of these changes are (apart from selenium cleanup). Any particular testing you want done?

**Comment by sbesson** [comment]
@will-moore: the major change of this PR should be the adding of `clearsessions()` to the `web start`, `web iis` and `web restart` commands so that tarting a Web client should clear expired Django sessions.

**Comment by chris-allan** [comment]
Simplifying and unifying the CLI infrastructure and getting rid of old, unmaintained cruft is highly appreciated @sbesson. The changes look good to me architecturally.

**Comment by sbesson** [comment]
@will-moore @aleksandra-tarkowska: any concern on these changes?

**Comment by will-moore** [comment]
@sbesson Nope, no concern.

**Comment by aleksandra-tarkowska** [comment]
@sbesson no comments, fine with me

**Comment by sbesson** [comment]
As reported by @kennethgillen, the `clearsessions` on start/restart can have some impact on some production servers which need to be documented and/or logged while running the command.

**Pull request merged**
