### PR TITLE
remove list of image formats from OMERO code

### PR DESCRIPTION
**Pull request by mtbc**
# What this PR does

This PR removes the obsolete list of image formats from the OMERO object mapping which is easier than needlessly maintaining it. #4837 ensures that all currently valid formats are still available as `Format` instances. The upgrade script ensures that obsolete formats that are used by legacy data remain `Format` instances.

# Testing this PR

test one:

1. Start from a fresh database using `OMERO5.3DEV__12.sql` generated by `omero/bin db script`.
1. Observe that the `format` table is empty.
1. Start the server.
1. Observe that the `format` table is now comprehensively populated.

test two:

1. Start from an older database with some images imported.
1. Run the database upgrade to patch 12.
1. Observe that the `format` table retains entries only for the formats of the imported images.
1. Start the server.
1. Observe that the `format` table is now comprehensively populated.

### CODE REVIEW

**Comment by jburel** [comment]
1. Test one works as expected
1.  Test two:
  * Imported 2 images a dv and a tiff
  * Run upgrade script successfully
  * 2 entries in the format table: Deltavision and TiffDelegate
  * Cannot restart the server 
``

Caused by: ome.conditions.InternalException: 
***************************************************************************************
DB version (OMERO5.3DEV__12) does not match omero.properties (OMERO5.3DEV__11). Please apply a db upgrade.
See http://www.openmicroscopy.org/site/support/omero5.2/sysadmins/server-upgrade.html
***************************************************************************************
``

**Comment by mtbc** [comment]
This PR has omero.properties with omero.db.patch=12 -- step 4 from test two needs a server with this PR included. Sorry if the instructions were too terse!

**Comment by jburel** [comment]
@mtbc: thanks I misunderstood.
I will do it again

**Comment by mtbc** [comment]
Thanks! Sorry for the trouble.

**Comment by jburel** [comment]
I had to remove ``DB check DBMappedEnumCheck`` row in the configuration table to get it to work
otherwise the ``format`` table is not re-populated, it will only contain the formats of the imported images

**Comment by mtbc** [comment]
Thanks for discovering that. Happens when upgrading from a server that used the same Bio-Formats.

**Comment by jburel** [comment]
@mtbc: i will run test 2 again with your latest commit

**Comment by mtbc** [comment]
@jburel observes that test two is split into: from previous 5.3 patch 11, and from previous major 5.2.

**Comment by jburel** [comment]
Test 2 from 5.3 patch 11 works now with the last commit

Todo test 2b: from 5.2 to 5.3 patch 12

**Comment by jburel** [comment]
Test 2b: start from 5.2 server 
 
 * import a dv
 * stop server
 * upgrade DB ``YOU HAVE SUCCESSFULLY UPGRADED YOUR DATABASE TO VERSION OMERO5.3DEV__12``
 * Check DB 
``
select * from format;
 id | permissions |    value    | external_id 
----+-------------+-------------+-------------
 19 |         -52 | Deltavision |            
(1 row)
``
* restarted the server. DB is populated with the formats.

**Comment by jburel** [comment]
Taking out of breaking

**Comment by mtbc** [comment]
May now want to look at the OMERO-DEV-merge-deploy DB to check that the format table looks healthily full.

**Comment by dominikl** [comment]
Tested locally, works like expected! 👍  (not checked the DB on eel though)

**Comment by mtbc** [comment]
```
$ echo "SELECT COUNT(*) FROM format" | ssh eel.openmicroscopy.org psql -U omero OMERO-DEV-merge-deploy
 count 
-------
   241
(1 row)
```

**Comment by jburel** [comment]
hummm, I don't think that the value I had in my DB I think it was  `196`

**Comment by mtbc** [comment]
Possibly there is some old data imported into eel with its format string no longer reported by Bio-Formats as a current one? If you still have your DB lying around feel free to e-mail me it or attach it here and I'll take a quick look to see how it differs from eel's, in case that gives any clues.

**Comment by mtbc** [comment]
Taking a look now at what eel has extra.

**Comment by mtbc** [comment]
Yeah, a fresh DB gets 196. eel seems to have a ton of odd formats like "Companion/GIF" and "Companion/JPEG" which I guess were added without knowing which formats have companion files.

**Comment by jburel** [comment]
I see. Is it something we want to fix during the upgrade?

**Comment by mtbc** [comment]
It should have been fixed. The upgrade script doesn't take proper account of images with null formats. I'll push another commit.

**Comment by mtbc** [comment]
To illustrate the problem that needed fixing:

```
OMERO-DEV-merge-deploy=# SELECT id FROM format WHERE id NOT IN (NULL);
 id 
----
(0 rows)
```

**Comment by mtbc** [comment]
If desired I could run the DELETEs from the updated upgrade scripts on eel later today and then have it repopulate with the next merge build.

**Comment by jburel** [comment]
If the entries are not valid, that will make sense

**Comment by mtbc** [comment]
Will list for tomorrow then so we can check what happened.

**Comment by mtbc** [comment]
```
OMERO-DEV-merge-deploy=# SELECT count(id) FROM format;
 count 
-------
   241
(1 row)

OMERO-DEV-merge-deploy=# DELETE FROM format WHERE id NOT IN (SELECT DISTINCT format FROM image WHERE format IS NOT NULL) AND external_id IS NULL;
DELETE 185
OMERO-DEV-merge-deploy=# DELETE FROM configuration WHERE name = 'DB check DBEnumCheck';
DELETE 1
OMERO-DEV-merge-deploy=# SELECT count(id) FROM format;
 count 
-------
    56
(1 row)
```

We'll check it again tomorrow.

**Comment by mtbc** [comment]
```
OMERO-DEV-merge-deploy=# SELECT count(id) FROM format;
 count 
-------
   196
(1 row)
```

**Comment by mtbc** [comment]
To see this morning's adding look for `EnsureEnum` in eel's `/opt/hudson/workspace/OMERO-DEV-merge-deploy/src/dist/var/log/Blitz-0.log`.

**Comment by jburel** [comment]
``
2016-10-06 04:20:27,715 INFO  [            ome.services.util.EnsureEnum](main) adding to database new enumeration value Format.FilePattern
2016-10-06 04:20:27,804 INFO  [       ome.security.basic.CurrentDetails](main) Adding log:INSERT,class ome.model.enums.Format,275
2016-10-06 04:20:27,806 INFO  [            ome.services.util.EnsureEnum](main) adding to database new enumeration value Format.Companion/FilePattern
2016-10-06 04:20:27,809 INFO  [       ome.security.basic.CurrentDetails](main) Adding log:INSERT,class ome.model.enums.Format,276
2016-10-06 04:20:27,810 INFO  [            ome.services.util.EnsureEnum](main) adding to database new enumeration value Format.Zip
2016-10-06 04:20:27,814 INFO  [       ome.security.basic.CurrentDetails](main) Adding log:INSERT,class ome.model.enums.Format,277
2016-10-06 04:20:27,825 INFO  [            ome.services.util.EnsureEnum](main) adding to database new enumeration value Format.Fits
2016-10-06 04:20:27,828 INFO  [       ome.security.basic.CurrentDetails](main) Adding log:INSERT,class ome.model.enums.Format,278
2016-10-06 04:20:27,829 INFO  [            ome.services.util.EnsureEnum](main) adding to database new enumeration value Format.PCX
2016-10-06 04:20:27,832 INFO  [       ome.security.basic.CurrentDetails](main) Adding log:INSERT,class ome.model.enums.Format,279
2016-10-06 04:20:27,833 INFO  [            ome.services.util.EnsureEnum](main) adding to database new enumeration value Format.GIF
2016-10-06 04:20:27,838 INFO  [       ome.security.basic.CurrentDetails](main) Adding log:INSERT,class ome.model.enums.Format,280
...

2016-10-06 04:20:28,661 INFO  [       ome.security.basic.CurrentDetails](main) Adding log:INSERT,class ome.model.enums.Format,414
2016-10-06 04:20:28,697 INFO  [                 org.perf4j.TimingLogger](main) start[1475724026931] time[1766] tag[omero.call.success.ome.services.util.EnsureEnum$1.doWork]
2016-10-06 04:20:28,698 INFO  [        ome.services.util.ServiceHandler](main)  Rslt:    (275, 276, 277, ... 193 more)
2016-10-06 04:20:28,770 INFO  [           ome.services.util.BaseDBCheck](main) performed DB check DBEnumCheck: done for Bio-Formats revision d7d2c4f6021c36a31a536fc36a3c950973eab1c0  
``
All good now
Merging

**Comment by mtbc** [comment]
Thank you for your help in finding the bugs. :smiley:

**Pull request merged**
