### PR TITLE
add list of ProjectionDef to RenderingDef

### PR DESCRIPTION
**Pull request by mtbc**
# What this PR does

Creates a new `ProjectionDef` list for `RenderingDef.projections`.

# Testing this PR

Note that this PR introduces a new DB patch 7.

Ensure that there are no regressions related to rendering settings.

# Related reading

https://trello.com/c/JkRcxqVU/96-z-projection-thumbnails

### CODE REVIEW

**Comment by jburel** [comment]
It might be also a good time to remove the codomain context since we have not been using it since we move the code from insight to the server.
No code uses it.
inverse intensity will be handled by the LUT
cc @joshmoore

**Comment by mtbc** [comment]
That's not in the OME-XML schema at all, right, so unaffected by imminent model freeze? Then maybe better to do in a subsequent DB patch because we should first ask mailing lists about uses, as we did for ROI keywords / namespaces?

**Comment by jburel** [comment]
not in the ome schema. 
This can obviously be done in a follow-up PR

**Comment by jburel** [comment]
I am not sure of the ``StartPlane, EndPlane`` terms, probably ``Start/End`` will be enough

**Comment by mtbc** [comment]
"start" and "end" turn out to be a rather confusing pain because they are reserved words in ISO SQL 1999 and elsewhere so, while still possible, they're tricky property values.

**Comment by jburel** [comment]
fair enough, let's add plane in that case. No point to make things more difficult than needed.

**Comment by jburel** [comment]
currently there is no way to create any of the projectionDef object using any of the methods

**Comment by mtbc** [comment]
One can fetch a RenderingDef via iQuery and add ProjectionDefs to it via iUpdate. (The rendering engine API I have no idea about, I'm afraid!)

**Comment by jburel** [comment]
Sorry I was unclear, this was more if you were planning to modify methods to create such object.

**Comment by mtbc** [comment]
Ah, I wasn't, but certainly worth breaking out on the card checklist. There is definitely server-side work to be done about rendering engine / settings stuff to support these projection definitions better, though I'm not quite sure where or what. (The HQL tweak in PixelsImpl seemed a pretty safe guess though!)

**Comment by jburel** [comment]
I have added a test to the RenderingEngineTest class:
you can run that individual test
``./build.py -f components/tools/OmeroJava/build.xml test -DMETHODS=integration.RenderingEngineTest.testRenderingEngineProjectionDef``
branch
https://github.com/jburel/openmicroscopy/tree/ProjectionDef

The test is currently failing

**Comment by jburel** [comment]
I had a look at the DB and no ``projectionDef`` saved.

**Comment by mtbc** [comment]
Excellent, thank you for adding the test. https://ci.openmicroscopy.org/job/OMERO-DEV-breaking-integration-java/lastCompletedBuildtestngreports/integration/RenderingEngineTest/testRenderingEngineProjectionDef/

**Comment by jburel** [comment]
@mtbc: ignore my comment about codomain map. No point to go over the effort of removing it since it will be removed when we rework the rendering engine

**Comment by jburel** [comment]
Ah, I missed the ``add`` method ;-)

**Comment by mtbc** [comment]
Okay, noted. :smiley:

**Comment by dominikl** [comment]
Looks alright to me 👍

**Comment by dominikl** [comment]
I'm just wondering what this `renderingdef_index` field in the database is, can't figure out where it comes from/what it is for.

**Comment by mtbc** [comment]
It arises from the `ordered="true"` in the mapping file: a RenderingDef's ProjectionDef list is kept in order because it may matter in which order multiple projections are performed.

@sbesson, should I remove the `--breaking`?

**Comment by sbesson** [comment]
Sorry coming back late to this. Assuming everyone is okay with the semantics of the new `ProjectionDef`, I would say let's get this into the merge build.

**Comment by mtbc** [comment]
See https://ci.openmicroscopy.org/job/OMERO-DEV-merge-integration-java/lastCompletedBuild/testngreports/integration/RenderingEngineTest/testRenderingEngineProjectionDef/.

**Comment by jburel** [comment]
Looks good. Thanks @mtbc

**Comment by mtbc** [comment]
Anything further to be done?

**Comment by jburel** [comment]
Not that I can think of, I will have to see when I start making the change to the Rendering engine if things need adjustment
I am currently looking at LUT in RE

**Comment by jburel** [comment]
if no objections, probably time to have it in cc @sbesson

**Comment by sbesson** [comment]
:+1:

**Pull request merged**
