### PR TITLE
Imagej mif

### PR DESCRIPTION
**Pull request by jburel**
Add support for overlay and MIF

To test
 * open  a mif in imageJ using B-F importer e.g. ```test_images_good/leica-lif/Beta Catenin.lif```
 * Make sure you select all series. 5 windows should opened
 * Draw a roi on an image e.g. series004, add it as an overlay
 * Draw a roi on an another image e.g. image001, add it as an overlay
 * Import the image to OMERO
 * Check the rois are on the correct images.

### CODE REVIEW

**Comment by pwalczysko** [comment]
Will have a look tomorrow.

**Comment by pwalczysko** [comment]
Does not work for me. 
  - Draw a region (rectangle) on Series001, add to Overlay
  - Draw a region (line) on Image001, add to Overlay
  - use ``Upload and Save to OMERO``
  - on all the images (all 5 of the series) there is only the line (= the region which was drawn the last)

**Comment by jburel** [comment]
@pwalczysko: did you have rois in manager?

**Comment by pwalczysko** [comment]
No, no ROIs in manager - I stuck to the description in the header of the PR - should I repeat using ROI Manager ?

**Comment by jburel** [comment]
@pwalczysko: it works when you select "Add image from All windows" options but not if the "add image is selected". investigating.

**Comment by jburel** [comment]
@pwalczysko: issue should be fixed.
Could you fix both options:
 * image from current window
 * images from all windows.

**Comment by pwalczysko** [comment]
Sorry, will not manage today. Will test tomorrow.

**Comment by pwalczysko** [comment]
This works as expected, both ``Image from active window`` and ``Images from all active window`` options deliver the regions as they should be.

**Comment by pwalczysko** [comment]
Updating the trello card https://trello.com/c/deNMiFvH/88-plugins-for-imagej-implementation with some issues unrelated to this PR .

Please merge.

**Comment by jburel** [comment]
@pwalczysko: Thanks I will tackle the issues reported on the card in a follow-up PR

**Comment by jburel** [comment]
--no-rebase

**Pull request merged**
