### PR TITLE
Compare full generated web configs

### PR DESCRIPTION
**Pull request by manics**
This should make it easier to review the effects of any future config changes.

Reference configs exist for each web-server with defaults, and each web-server with all options together. Combinations of options continue to be tested by the existing tests.

### CODE REVIEW

**Comment by sbesson** [comment]
```
     [exec] test/unit/clitest/test_web.py::TestWeb::testFullTemplateDefaults[nginx] PASSED
     [exec] test/unit/clitest/test_web.py::TestWeb::testFullTemplateDefaults[nginx-development] PASSED
     [exec] test/unit/clitest/test_web.py::TestWeb::testFullTemplateDefaults[apache] PASSED
     [exec] test/unit/clitest/test_web.py::TestWeb::testFullTemplateDefaults[apache-fcgi] PASSED
     [exec] test/unit/clitest/test_web.py::TestWeb::testFullTemplateWithOptions[server_type0] PASSED
     [exec] test/unit/clitest/test_web.py::TestWeb::testFullTemplateWithOptions[server_type1] PASSED
     [exec] test/unit/clitest/test_web.py::TestWeb::testFullTemplateWithOptions[server_type2] PASSED
     [exec] test/unit/clitest/test_web.py::TestWeb::testFullTemplateWithOptions[server_type3] PASSED
```

Looks good. Do we still need the per-line tests or is the goal to deprecate them in favor of the full templates tests?

**Comment by manics** [comment]
Depends whether we want to keep testing combinations of all options (would require a lot of files, by my calculations 36 for `testNginxConfig` alone) or just a few.

**Comment by sbesson** [comment]
Having full templates for each combination definitely does not scale well especially if we keep adding options in the future. I guess there is no harm in keeping both series of test. I wonder if dropping the numbered lines checks in favor of more generic `assert line in output` would simplify the maintenance of these tests since we have the full templates ones. Thoughts?

**Comment by manics** [comment]
Yes, or something in between where we drop the line numbers but check the required lines appear in the expected order. I'll have a go.

**Comment by manics** [comment]
@sbesson How do the last two commits look?

**Comment by sbesson** [comment]
Certainly works for me. As long as Travis is happy, this looks ready to merge.

**Comment by manics** [comment]
--no-rebase

**Pull request merged**
