### PR TITLE
Bio-Formats 5.3.0 integration

### PR DESCRIPTION
**Pull request by sbesson**
Following the tag/release of the first milestone of Bio-Formats 5.3.0, this PR bumps the version used by the development branch of OMERO to consume Bio-Formats 5.3.0-m1.

An extra commit has been added to clean the `specification` dependency in the OmeroJava `test.xml`. This JAR should be pulled as a transitive dependency and should not affect the outcome of the Java integration tests.

### CODE REVIEW

**Comment by mtbc** [comment]
Good to merge.

**Comment by sbesson** [comment]
As mentioned elsewhere, there might be a discussion on whether we want to merge the intermediate milestones of Bio-Formats into the OMERO development line or wait until the 5.3.0 release. Happy to go either way. /cc @jburel

**Comment by sbesson** [comment]
Discussed earlier today with @jburel and @melissalinkert. The Bio-Formats 5.3.0-m1 bump is no necessary for the upcoming 5.3.0-m5 milestone. However for the following milestone, we might want to integrate Bio-Formats into the `develop` line of OMERO to demo the JPEG-XR integration notably. Marking on hold for now and leaving the PR at 5.3.0-SNAPSHOT to test the Bio-Formats PR.

**Comment by sbesson** [comment]
Superseded by https://github.com/openmicroscopy/openmicroscopy/pull/4959

**Pull request closed without merging**
