### PR TITLE
Select next row after deleting map annotation rows

### PR DESCRIPTION
**Pull request by will-moore**
Fix issues from https://trello.com/c/Fx74klF5/17-map-annotation-schema-db

Only 1 change: Deletion of a row should select the next row (or previous row if the bottom row is deleted).

### CODE REVIEW

**Comment by gusferguson** [comment]
@will-moore 

Tested using http://trout.openmicroscopy.org/merge/webclient/ user-3 read-annotate-1

Deletion of row behaves as expected - next row selected.
From this point of view good to merge.

A couple of other issues I noticed:
- the X icon for deleting is out of alignment with the other icons in the toolbar - it looks as if it is top aligned and the others middle.
- can the toolbar be shifted a few pixels to the left so it doesn't overlap the scroll bar?
- it is possible to create empty key-value pairs - I thought this was not allowed?


safari

**Comment by will-moore** [comment]
@gusferguson Fixed the alignment of the X button and shifted the toolbar left a bit.
The + button will create a new row, which will be empty, but will not be saved unless some key or value is added.
I prefer to allow the user to create a bunch of empty rows if they want (E.g. may want to create 4 rows that they know they need, then fill them in).
I don't think we gain much by disabling the + button under certain conditions. E.g. what conditions would you disable it and how would you tell the user what they have to do to enable it again?
Spreadsheet apps allow you to create a ton of empty rows before filling them in.

**Comment by gusferguson** [comment]
@will-moore 
Happy with the empty rows if they are not being saved.

**Comment by gusferguson** [comment]
@will-moore 

Tested using http://trout.openmicroscopy.org/merge/webclient/ user-3 read-annotate-1

Looking good.
Behaves as expected.
Good to merge.

safari

**Comment by jburel** [comment]
Thanks Merging

**Comment by jburel** [comment]
--no-rebase

**Pull request merged**
