### PR TITLE
Fix CLI sessions file

### PR DESCRIPTION
**Pull request by sbesson**
Reported by @manics. The addition of last port in https://github.com/openmicroscopy/openmicroscopy/pull/3370 broke `bin/omero sessions file`.

This PR should fix this bug and add an integration test to extend our coverage.

--no-rebase

### CODE REVIEW

**Comment by manics** [comment]
`$ git grep get_current`
Looks like this will need changing too:
`components/tools/OmeroPy/src/omero/plugins/script.py:            srv, usr, uuid = store.get_current()`

**Comment by sbesson** [comment]
Doh. Thanks again Simon.

**Comment by manics** [comment]
Good to merge

**Comment by joshmoore** [comment]
Thanks, guys. Merging. Have a vague feeling that moving forward we might want to move away from multiple returns in favor a single return object.

**Comment by sbesson** [comment]
Definitely. all other places in the CLI use a safer strategy.

```
current =  store.get_current()
host = current[0]
```
I will make a card for this and try to implement it (and extend the stub integration test) for 5.1.0

**Comment by joshmoore** [comment]
Thanks, @sbesson. Not too particularly worried about `get_current()` specifically, but just our API-design strategy. (This one is clearly my fault, regardless)

**Pull request merged**
