### PR TITLE
introduce OMERO5.4DEV__0 database patch with new light admin privilege enumeration values

### PR DESCRIPTION
**Pull request by mtbc**
# What this PR does

Provides SQL for bringing "roles" work explicitly up to database patch `OMERO5.4DEV__0` and removes the scripts for OMERO5.3 DEV versions.

# Related reading

https://trello.com/c/SMclEA33/23-db-patch-omero5-4dev-0

### CODE REVIEW

**Comment by joshmoore** [comment]
* Is it now safe to assume some of the helpers like `omero_assert_db_version` and `db_pretty_version` exist?
 * If we're going for "standard, production upgrade functions" perhaps `YOU HAVE SUCCESSFULLY UPGRADED...` could be migrated as well.
 * My only specific comment related to this PR is probably that we should make sure we're happy (i.e. I still have my doubts) with `Privilege` as opposed to `Restriction`. Would be good to make sure the semantics match the name (These things tend to grow in impact over time)

**Comment by mtbc** [comment]
We always drop the helpers. We could revisit that though maybe it's nice for briefly needed functions to not hang around while the production server runs.

I think the semantics work okay as the term is always associated with a boolean; the question is more one of how one interprets the absence of a key. Still, not too late to change it if you really want, but better in a different PR as this one doesn't create the `adminprivilege` table nor the enumeration type, it just adds the values.

**Comment by mtbc** [comment]
The "you have successfully upgraded" is just a single `SELECT`; the other  functions require PL/pgSQL.

**Comment by rleigh-codelibre** [comment]
Reading through, the SQL all looks fine and good to merge on that basis.  Do you want any specific testing, or is this handled by the CI deployment?

**Comment by mtbc** [comment]
Thank you. I *think* `sql/psql/OMERO5.4DEV__0/OMERO5.3__0.sql ` may need a manual test as I don't see anything in the devspace that tries it.

**Comment by mtbc** [comment]
Created https://trello.com/c/WweS86l9/748-pack-upgrade-helpers-into-persistent-functions - happy to execute this and for others to set priority.

**Comment by mtbc** [comment]
Also created https://trello.com/c/Chfz30of/25-privileges-restrictions-naming regarding terminology.

**Comment by jburel** [comment]
```
BEGIN
CREATE FUNCTION
 omero_assert_db_version 
-------------------------
 
(1 row)

DROP FUNCTION
CREATE FUNCTION
CREATE FUNCTION
 assert_db_server_prerequisites 
--------------------------------
 
(1 row)

DROP FUNCTION
DROP FUNCTION
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
UPDATE 1
                                 status                                 
------------------------------------------------------------------------
                                                                       +
                                                                       +
                                                                       +
 YOU HAVE SUCCESSFULLY UPGRADED YOUR DATABASE TO VERSION OMERO5.4DEV__0+
                                                                       +
                                                                       +
 
(1 row)

COMMIT

```
upgraded from 5.3.0

**Comment by jburel** [comment]
Server restarted without problems
Connected using client from latest build i.e. https://10.0.51.154:8443/job/OMERO-build/16/

**Comment by jburel** [comment]
travis failure due to omero-marshal version issue
merging

**Pull request merged**
