### PR TITLE
Fixed ROI issue with floating point images

### PR DESCRIPTION
**Pull request by dominikl**
Fixes ticket [Trac 12711](https://trac.openmicroscopy.org.uk/ome/ticket/12711)

To Test:
Open/Import floating point image; open ROI tool, draw/select ROI, make sure Graph, Intensity and Result tabs are working (without PR just a warning dialog popped up, saying there was an error performing the analysis)

### CODE REVIEW

**Comment by dominikl** [comment]
This certainly is an issue in dev_5_0, too. Rebase once this has been reviewed?

**Comment by gusferguson** [comment]
@dominikl 

Tested using OMERO.insight-5.1.0-m3-755-21e9c32-ice35-b392-mac trout user-3 read-annotate-1 image emd_1003.map

Works as expected - all panes populated in ROI tool window.
Good to merge.

omero insight

**Comment by dominikl** [comment]
@pwalczysko @jburel Would be easy to rebase to dev_5_0... Rebase or is it too late?

**Comment by jburel** [comment]
@dominikl  It is a bit too late.

**Comment by sbesson** [comment]
--rebased-to #3426

**Pull request merged**
