### PR TITLE
Re-activate 'integration' for '.omero/docker srv'

### PR DESCRIPTION
**Pull request by joshmoore**
This is initially intended to fail, but will make
use of pr5998 to make the integration tests pass.

see: https://github.com/openmicroscopy/openmicroscopy/pull/5998

### CODE REVIEW

**Comment by joshmoore** [comment]
@mtbc: 140bcd727fa3879447f266e811d2814a97d9cc79 is one for us to ponder.

**Comment by mtbc** [comment]
Indeed, I've wondered if there's a good gradle-y way to reintroduce these.

**Comment by joshmoore** [comment]
I'd imagine so.

**Comment by joshmoore** [comment]
Current commit fails with:

```
self = OMERO.Glacier2/router -t -e 1.1:ssl -h omero -p 4064 -t 60000
userId = 'root', password = 'omero'
_ctx = {'omero.agent': 'OMERO.py.root_test', 'omero.client.uuid': '72944923-3b7c-4dc1-8302-ab7bc5c3955c'}
    def createSession(self, userId, password, _ctx=None):
>       return _M_Glacier2.Router._op_createSession.invoke(self, ((userId, password), _ctx))
E       ProtocolException: exception ::Ice::ProtocolException
E       {
E           reason = SSL error occurred for new outgoing connection:
E       remote address = 172.18.0.3:4064
E       sslv3 alert handshake failure: SSL alert number 40
```

Trying to get this passing with gh-5998

**Pull request closed without merging**
