### PR TITLE
ROIs v2

### PR DESCRIPTION
**Pull request by mtbc**
Companion PR to https://github.com/openmicroscopy/bioformats/pull/1973.

* introduce SQL upgrade for OMERO 5.2
* introduce SQL upgrade for OMERO 5.3
* remove Shape.visibility from model

--depends-on #4158

### CODE REVIEW

**Comment by mtbc** [comment]
Travis issues, bah.

**Comment by mtbc** [comment]
I guess I'm waiting on #4196.

**Comment by mtbc** [comment]
and again...

**Comment by sbesson** [comment]
Closing/reopening to include #4196 in the merge commit for Travis.

**Comment by mtbc** [comment]
Will reopen against regions branch.

**Comment by mtbc** [comment]
Replaced by #4232.

**Pull request closed without merging**
