### PR TITLE
Save enabled on z/t change

### PR DESCRIPTION
**Pull request by will-moore**
This fixes http://trac.openmicroscopy.org.uk/ome/ticket/12709 in web.

To test:
 - Open Preview panel
 - Change Z or T index
 - Save button should become enabled and saving should update Thumbnail etc.
 - Test same behaviour in Image Viewer.

NB: we don't have a whole undo/redo queue for Z/T changes, so after Z/T change and "Save" is enabled, if you change rendering settings then click "Undo" the Save button will become disabled again.

### CODE REVIEW

**Comment by dominikl** [comment]
Works as described. I just noticed a problem with the multichannel-4D-series.ome.tiff example file (see user-3/ome-tiff). Once you change and save the T plane, the save button for this image is always enabled (it gets disabled directly after being saved, but if you move to a different image and back again, it's enabled again without any changes). I'm not sure if this related to this PR.

**Comment by will-moore** [comment]
Fixed a couple of things there.
Now I'm checking Z/T changes "properly" so the "Save" button should be disabled if Z and T are the same as saved values and there are no unsaved rendering settings.
E.g. change Z - "Save" is enabled, then change it back, "Save" is disabled etc.

**Comment by gusferguson** [comment]
@will-moore 

Tested using trout merge user-4 read-only-1 and read-write-1.

Behaves as expected on own and other user's data in Preview and full viewer. 
Dominik's issue appears to have been resolved successfully and "proper" change is working as expected.
Good to merge.

**Comment by jburel** [comment]
@will-moore: do you have some robot tests, checking if the button is active or not after a slider move e.g. z-slider?

**Comment by will-moore** [comment]
@jburel I don't have any Robot tests for that yet, but could add it. I just need to figure out how to create multi-Z/T test images...

**Comment by gusferguson** [comment]
@will-moore - one of Iain Porter's .dvs has multiple of both - can you use a normal image?

**Comment by joshmoore** [comment]
I'd assume just a `robot&sizeZ=10&sizeT=100.fake` or similar would suffice for a robot test.

**Comment by will-moore** [comment]
Robot test added to check that 'Save' becomes enabled/disabled when Z-index changes.

**Comment by gusferguson** [comment]
@will-moore 

Retested with trout merge user-4 read-only-1 - behaves as expected.
Good to merge.

**Pull request merged**
