### PR TITLE
improving robot tests

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
cleaning up search tests, removing duplicates

### CODE REVIEW

**Comment by bramalingam** [comment]
All tests passing in one browser at-least. Looks good to merge.

**Comment by jburel** [comment]
Will merge the PR tomorrow after another round.

**Comment by jburel** [comment]
Merging this PR, more fixes to come

**Comment by aleksandra-tarkowska** [comment]
--rebased-to #4053

**Pull request merged**
