### PR TITLE
Disable extra artifacts with package-extra=false (rebased onto develop)

### PR DESCRIPTION
**Pull request by joshmoore**
This is the same as gh-3374 but rebased onto develop.

----

The -javadoc and -sources packages are currently
built by default via the package targets dependency
on package-extra. By setting package-extra=false
either on the command-line or in etc/local.properties,
these sections can be disabled. On my system, that
takes a rebuild (without clean) from 5'45" to 3'30".

/cc @jburel @sbesson 

Testing
---------
The intent is that this change should improve the overall health of travis builds. If this build is green, then likely adding it to the regular 5.0 build is fine. If all the other builds remain green (incl. release!), then things are working well. Developers may want to set `package-extra=false` locally. Note: this may cause the daily merge to fail unexpectedly since nothing will have built javadocs until that point.

### CODE REVIEW

**Comment by joshmoore** [comment]
--rebased-from #3374

**Comment by sbesson** [comment]
From my point of view, this PR is functional and the `fold` additions makes the Travis output much easier to parse. Ready to merge.

**Comment by joshmoore** [comment]
@mtbc: what kind of improvements are you seeing? Does this suffice for the moment?

**Comment by mtbc** [comment]
I've added my name to it in stand-up today: I'll take timings and report back.

**Comment by mtbc** [comment]
This morning `./build.py build-dev` took 6m47, then with `package-extra=false` it was down to 4m41. Definitely a worthwhile improvement in terms of cumulative effect across team over time. Worth adding to developer docs.

Various `FAILED DOWNLOADS` warnings for the source and javadoc; I assume they're expected and ignorable and just look scary.

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#759](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/759/). See the [console output](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/759/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - .travis.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#760](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/760/). See the [console output](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/760/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - .travis.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#761](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/761/). See the [console output](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/761/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - .travis.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#762](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/762/). See the [console output](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/762/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - .travis.yml

**Comment by joshmoore** [comment]
Excluded until I can fix the conflict.

**Comment by joshmoore** [comment]
Conflict fixed.

**Comment by sbesson** [comment]
Restarted the Travis build multiple times - seem to be fairly robust. Merging this so that subsequent PRs can benefit from the improvements. Thanks @joshmoore

**Comment by mtbc** [comment]
:+1: This morning I was watching the `build-py` target build the Blitz Javadoc!

**Pull request merged**
