### PR TITLE
13074 autoclose anotations

### PR DESCRIPTION
**Pull request by joshmoore**
Fixes the error reported by @mtbc in https://trac.openmicroscopy.org/ome/ticket/13074

To test:

```
mkdir fakes
for x in $(seq 10 20); do touch $x.fake; done
bin/omero import -- --auto_close --annotation-text foo --annotation-ns foo fakes/
bin/omero -q hql "select i.id, a.ns, count(a.id) from Image i join i.annotationLinks l join l.child a group by i.id, a.ns order by i.id desc"
```

**Without this PR** one sees:

```
 #  | Col1 | Col2                                      | Col3
----+------+-------------------------------------------+------
 0  | 144  | foo                                       | 1
 1  | 144  | openmicroscopy.org/omero/import/autoClose | 11
 2  | 143  | foo                                       | 1
 3  | 143  | openmicroscopy.org/omero/import/autoClose | 10
 4  | 142  | foo                                       | 1
 5  | 142  | openmicroscopy.org/omero/import/autoClose | 9
 6  | 141  | foo                                       | 1
 7  | 141  | openmicroscopy.org/omero/import/autoClose | 8
 8  | 140  | foo                                       | 1
 9  | 140  | openmicroscopy.org/omero/import/autoClose | 7
 10 | 139  | foo                                       | 1
 11 | 139  | openmicroscopy.org/omero/import/autoClose | 6
 12 | 138  | foo                                       | 1
 13 | 138  | openmicroscopy.org/omero/import/autoClose | 5
 14 | 137  | foo                                       | 1
 15 | 137  | openmicroscopy.org/omero/import/autoClose | 4
 16 | 136  | foo                                       | 1
 17 | 136  | openmicroscopy.org/omero/import/autoClose | 3
 18 | 135  | foo                                       | 1
 19 | 135  | openmicroscopy.org/omero/import/autoClose | 2

```

**With** this PR:
```
 #  | Col1 | Col2                                      | Col3
----+------+-------------------------------------------+------
 0  | 159  | foo                                       | 1
 1  | 159  | openmicroscopy.org/omero/import/autoClose | 1
 2  | 158  | foo                                       | 1
 3  | 158  | openmicroscopy.org/omero/import/autoClose | 1
 4  | 157  | foo                                       | 1
 5  | 157  | openmicroscopy.org/omero/import/autoClose | 1
 6  | 156  | foo                                       | 1
 7  | 156  | openmicroscopy.org/omero/import/autoClose | 1
 8  | 155  | foo                                       | 1
 9  | 155  | openmicroscopy.org/omero/import/autoClose | 1
 10 | 154  | foo                                       | 1
 11 | 154  | openmicroscopy.org/omero/import/autoClose | 1
 12 | 153  | foo                                       | 1
 13 | 153  | openmicroscopy.org/omero/import/autoClose | 1
 14 | 152  | foo                                       | 1
 15 | 152  | openmicroscopy.org/omero/import/autoClose | 1
 16 | 151  | foo                                       | 1
 17 | 151  | openmicroscopy.org/omero/import/autoClose | 1
(18 rows)
```

Note: the test_import.py test is not directly related to this change, but does speed up the time taken to run `test_import.py`

### CODE REVIEW

**Comment by jburel** [comment]
With the change made in the test, it is now difficult to know with algorithm i.e.
``test/integration/clitest/test_import.py::TestImport::testChecksumAlgorithm[args0] PASSED
test/integration/clitest/test_import.py::TestImport::testChecksumAlgorithm[args1] PASSED``

I did not notice a major change in the speed. What is the time you gained?

**Comment by joshmoore** [comment]
> I did not notice a major change in the speed. What is the time you gained?

The change is that previously there were 14 calls to import with different checksums, now there are 8. It seemed unnecessary to have both `--checksum_algorithm=X` and `--checksum-algorithm=X` for everyone one.

**Comment by jburel** [comment]
@joshmoore: understood, I read that the speed was also improved. 
Having only argX might make it harder to read if one of them failed (w/o checking the code) but I guess if it failed someone will have to debug it

**Comment by sbesson** [comment]
We should also be able to customize the name of the fixture. Happy to provide a commit to @joshmoore if he's interested.

**Comment by joshmoore** [comment]
> I read that the speed was also improved. 

Only the speed of the entire suite.

> Having only argX might make it harder to read if one of them failed (w/o checking the code) but I guess if it failed someone will have to debug it

I'm happy to re-add the naming, though I'm not overly happy with them either way (since `-` and `_` are particularly user friendly anyway)

**Comment by sbesson** [comment]
Agreed on the non-user friendliness of the default, I would vote for using `ids=` like in other parametrized methods of the class, call each fixture simply by its algorithm and have the special underscore case named `Adler-32-legacy` or `Adler-32-underscore`.

**Comment by jburel** [comment]
w/o PR
```
#  | Col1 | Col2                                      | Col3 
----+------+-------------------------------------------+------
 0  | 3693 | foo                                       | 1    
 1  | 3693 | openmicroscopy.org/omero/import/autoClose | 11   
 2  | 3692 | foo                                       | 1    
 3  | 3692 | openmicroscopy.org/omero/import/autoClose | 10   
 4  | 3691 | foo                                       | 1    
 5  | 3691 | openmicroscopy.org/omero/import/autoClose | 9    
 6  | 3690 | foo                                       | 1    
 7  | 3690 | openmicroscopy.org/omero/import/autoClose | 8    
 8  | 3689 | foo                                       | 1    
 9  | 3689 | openmicroscopy.org/omero/import/autoClose | 7    
 10 | 3688 | foo                                       | 1    
 11 | 3688 | openmicroscopy.org/omero/import/autoClose | 6    
 12 | 3687 | foo                                       | 1    
 13 | 3687 | openmicroscopy.org/omero/import/autoClose | 5    
 14 | 3686 | foo                                       | 1    
 15 | 3686 | openmicroscopy.org/omero/import/autoClose | 4    
 16 | 3685 | foo                                       | 1    
 17 | 3685 | openmicroscopy.org/omero/import/autoClose | 3    
 18 | 3684 | foo                                       | 1    
 19 | 3684 | openmicroscopy.org/omero/import/autoClose | 2    
 20 | 3683 | foo                                       | 1    
 21 | 3683 | openmicroscopy.org/omero/import/autoClose | 1 
```

**Comment by jburel** [comment]
with PR
```

 #  | Col1 | Col2                                      | Col3 
----+------+-------------------------------------------+------
 0  | 3777 | foo                                       | 1    
 1  | 3777 | openmicroscopy.org/omero/import/autoClose | 1    
 2  | 3776 | foo                                       | 1    
 3  | 3776 | openmicroscopy.org/omero/import/autoClose | 1    
 4  | 3775 | foo                                       | 1    
 5  | 3775 | openmicroscopy.org/omero/import/autoClose | 1    
 6  | 3774 | foo                                       | 1    
 7  | 3774 | openmicroscopy.org/omero/import/autoClose | 1    
 8  | 3773 | foo                                       | 1    
 9  | 3773 | openmicroscopy.org/omero/import/autoClose | 1    
 10 | 3772 | foo                                       | 1    
 11 | 3772 | openmicroscopy.org/omero/import/autoClose | 1    
 12 | 3771 | foo                                       | 1    
 13 | 3771 | openmicroscopy.org/omero/import/autoClose | 1    
 14 | 3770 | foo                                       | 1    
 15 | 3770 | openmicroscopy.org/omero/import/autoClose | 1    
 16 | 3769 | foo                                       | 1    
 17 | 3769 | openmicroscopy.org/omero/import/autoClose | 1    
 18 | 3768 | foo                                       | 1    
 19 | 3768 | openmicroscopy.org/omero/import/autoClose | 1    
 20 | 3767 | foo                                       | 1    
 21 | 3767 | openmicroscopy.org/omero/import/autoClose | 1    
 22 | 3705 | foo                                       | 1    
 23 | 3705 | openmicroscopy.org/omero/import/autoClose | 1    
 24 | 3704 | foo                                       | 1    
```

**Comment by joshmoore** [comment]
Pushed.

**Comment by jburel** [comment]
```

test/integration/clitest/test_import.py::TestImport::testChecksumAlgorithm[Adler-32-legacy] PASSED
test/integration/clitest/test_import.py::TestImport::testChecksumAlgorithm[Adler-32-underscore] PASSED
test/integration/clitest/test_import.py::TestImport::testChecksumAlgorithm[CRC-32-underscore] PASSED
test/integration/clitest/test_import.py::TestImport::testChecksumAlgorithm[File-Size-64-underscore] PASSED
test/integration/clitest/test_import.py::TestImport::testChecksumAlgorithm[MD5-128-underscore] PASSED
test/integration/clitest/test_import.py::TestImport::testChecksumAlgorithm[Murmur3-32-underscore] PASSED
test/integration/clitest/test_import.py::TestImport::testChecksumAlgorithm[Murmur3-128-underscore] PASSED
test/integration/clitest/test_import.py::TestImport::testChecksumAlgorithm[SHA1-160-underscore] PASSED
```
everything looks good.
Waiting on travis to be green then ready to merge

**Pull request merged**
