### PR TITLE
Search get only

### PR DESCRIPTION
**Pull request by will-moore**
# What this PR does

Uses ```GET``` for webclient searches, allowing search pages to be bookmarked, cached etc.
This PR is based on Ola's: #4956.

# Testing this PR

1. Robot tests cover most search scenarios (updated for changes in this PR).

 2. Try searching with the top Search field in main webclient pages: the search query will be shown in the url.

 3. Searching with the search form will load the results using a url that includes the search query (allowing it to be cached). Check that search works as expected and you can use the browser devtools "Network" tab to check the url itself if desired.

# Related reading

See https://github.com/openmicroscopy/openmicroscopy/pull/4956.
cc @joshmoore

### CODE REVIEW

**Comment by will-moore** [comment]
I'm assuming this won't go into 5.3.3 (too late).
Should I close or exclude till after the release? @jburel.

**Comment by jburel** [comment]
no need to exclude it unless it is going to break everything :-)

**Comment by jburel** [comment]
The query is not in the url when searching from the search page
it is only when I search from the top Search field

**Comment by will-moore** [comment]
@jburel Ah, yes - I think it's my description that needs modifying there. The url doesn't change when you're searching in the search form, so I guess you can't bookmark those searches. So the only benefit we have of using GET in that case is for caching of the search results, since the query is now in the url.
I'll update the description...

**Comment by jburel** [comment]
The search robot tests are passing 
The 2 failures are not related to this PR

**Comment by joshmoore** [comment]
Cheers @will-moore Pointed https://trello.com/c/nCgYaayI/361-linkable-get-url-for-search to follow-on tasks on https://trello.com/c/io5JdIAO/79-critical-link-to-search-results

**Comment by manics** [comment]
--rebased-to #5378

**Pull request merged**
