### PR TITLE
build BF manually to fix travis test

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
Attempt to fix travis build

https://travis-ci.org/openmicroscopy/openmicroscopy/builds/151222496

### CODE REVIEW

**Comment by sbesson** [comment]
As discussed with @aleksandra-tarkowska and @manics, merging this PR to restore Travis on `metadata52`

**Comment by joshmoore** [comment]
Good idea. I wonder if we could put something similar in place for the regular build. Or just get to the SNAPSHOTS to artifactory ....

**Comment by aleksandra-tarkowska** [comment]
just rebase the PR with develop branch?

**Comment by joshmoore** [comment]
> just rebase the PR with develop branch?

I meant mostly outside of travis, so that devs don't face the same problem.

**Pull request merged**
