### PR TITLE
Training flake8

### PR DESCRIPTION
**Pull request by will-moore**
# What this PR does

Ran ```futurize -w -0 *.py``` on ```examples/Training/python/```.
and then fixed ```flake8``` issues.

On top of @mtbc https://github.com/ome/openmicroscopy/pull/6129

### CODE REVIEW

**Comment by joshmoore** [comment]
[merge 212](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-training/212/console) is failing with:

```
02:19:04 TypeError: initial_value must be unicode or None, not str
```

and [py3 26](https://py3-ci.openmicroscopy.org/jenkins/job/OMERO-training/26/console) with:

```
01:59:42     print("created {} shapes".format(total_shape_count))
01:59:42   File "/home/omero/workspace/OMERO-training/omero-virtualenv/lib64/python3.6/codecs.py", line 377, in write
01:59:42     self.stream.write(data)
01:59:42 TypeError: write() argument must be str, not bytes
```

**Comment by joshmoore** [comment]
Restarted travis.

**Comment by jburel** [comment]
https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-training/222/ is green

**Comment by jburel** [comment]
13e38150b1d67c2f3e9548c046d105801e842551 should fix https://py3-ci.openmicroscopy.org/jenkins/job/OMERO-training/37/console

**Comment by joshmoore** [comment]
OMERO-training tests against the OMERO-server host rather than OMERO-test-integration. I've added `pip install tables` to the OMERO-server job configuration and expect OMERO-training to go green on the next run.

**Comment by jburel** [comment]
https://py3-ci.openmicroscopy.org/jenkins/job/OMERO-training/43/ is finally green
https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-training/224/ is green too

**Comment by joshmoore** [comment]
:tada:

**Pull request merged**
