### PR TITLE
Decoupling

### PR DESCRIPTION
**Pull request by dominikl**
Merges the decoupling (which is basically the Java Gateway PR) with develop branch

Testing: Check basic functionality of Insight client; especially perform actions which trigger parallel requests to the server. See [Trello card, Test section](https://trello.com/c/2WY5iyS7/8-java-gateway)

### CODE REVIEW

**Comment by gusferguson** [comment]
@dominikl 

Using OMERO.insight-5.1.3-m1-193-12fd548-ice35-b557-win user-3 trout read-only-1 and read-annote-1 own data and other user's data.

Problem with Preview viewer - image is tiny - about 12x12 px.
See screenshot.

Everything else seems to be normal and thumbnail loads etc fast.

parallels desktop

**Comment by gusferguson** [comment]
@dominikl - just quit and restarted Insight and Preview view pane issue not occurring now.

Not sure what the story is.

parallels desktop

**Comment by dominikl** [comment]
Yes, tried to reproduce, couldn't see it. Seems to be one of these weird random issues.

**Comment by pwalczysko** [comment]
Switch user has failed. 
Switch user: connect as user-4, have read-only on display. Switch user to user-6. User-6 default group is NOT read-annotate. Switch to this group as user-6 -> you cannot see any data of user-6 at all (fails to load).

**Comment by pwalczysko** [comment]
@dominikl has discovered a simplified workflow for https://github.com/openmicroscopy/openmicroscopy/pull/3952#issuecomment-120366508: login as user-3 and switch to user-2 on trout merge. I can perfectly reproduce his workflow.

**Comment by pwalczysko** [comment]
Disconnect and reconnect from network using cable. 
Test as per step 4. in https://www.openmicroscopy.org/private/ome-internal/testing_scenarios/ConnectionErrorHandling.html FAILED. Expected behaviour (still present on trout latest with latest insight) is that 

 - before reconnection of the cable and clicking to expand a Dataset,  a warning popup with 2 minutes countdown appears encouraging you to reconnect
 - after you reconnect, the behaviour of Insight starts to be normal, the clicked-on dataset will expand and you can continue your work (expand other datasets, open images etc.)

This completely fails with this PR. Instead, after the expansion of the Dataset without connection it shows 

screen shot 2015-07-10 at 13 23 58
 
and no warning popup.
After you reconnect the cable, Insight either throws errors on clicking on Datasets or images, or at other times, it just does not react. It does not crash though, you can quit it normally.

**Comment by pwalczysko** [comment]
Sleep tests as per step 7 of https://www.openmicroscopy.org/private/ome-internal/testing_scenarios/ConnectionErrorHandling.html failed on Win7 laptop, passed on Mac. 
   - expected behaviour is that after a wake from the sleep, Insight will work as normal
   - on windows 7, it just throws either errors when trying to open an image already expanded, or ignores expansion clicks on Datasets

**Comment by pwalczysko** [comment]
Switch user workflow works as expected now.

**Comment by pwalczysko** [comment]
Just the disconnect issues https://github.com/openmicroscopy/openmicroscopy/pull/3952#issuecomment-120402126 and sleep issues https://github.com/openmicroscopy/openmicroscopy/pull/3952#issuecomment-120405724 to do now.

**Comment by dominikl** [comment]
--exclude for now to not interfere with the Java 1.8.0_51 bugfix.

**Comment by pwalczysko** [comment]
The disconnect issues work as expected. 
The sleep issues  work as expected on Mac, on Win7 laptop Insight will not reconnect successfully after you put the computer to sleep, it just throws a number of errors after each click.

**Comment by pwalczysko** [comment]
Added one more issue to the https://trello.com/c/2WY5iyS7/8-java-gateway - the empty datasets when expanded show "Loading...".

**Comment by dominikl** [comment]
The "Loading..." node problem is fixed here: #3985  @sbesson Can you merge it once Travis is green?
If the Win7 sleep problem really is introduced by this PR then better hold off for 5.1.3, certainly can't fix this today.

**Comment by pwalczysko** [comment]
@dominikl @joshmoore @jburel : Performed 2 more sleep tests on Win7. 

  - 5.1.2 release insight 2x successfully reconnected after 1 minute sleep
  - the merge insight with this PR 2x fully failed after 1 minute sleep

**Comment by pwalczysko** [comment]
The ``Loading...`` issue is fixed, works as expected. But

The sleep issue retest on Win7 again shown that:

  - after 1 minute sleep with this PR the reconnection fully fails and number of errors occurs after trying to click onto things in Insight
  - after 1 minute sleep with 5.1.2 release Insight the reconnection progresses as expected (with the "trying to reconnect" dialog followed by gradually more and more normal behaviour with no errors thrown)

This seems like a clear regression.

**Comment by pwalczysko** [comment]
Consulted the importance of the short-sleep-on-Win7 with @mporter-gre . 

1. there are majority of Win7 comps in the college and Win8 is not in sight (possibly never will be) => Win7 is probably still the number 1 OS for our users
2. even a short-sleep failure (long ~20 mins sleep fails anyway even with 5.1.2 release) is annoying and very important detriment for user experience and short sleeps occur in real life often 

With this, I think we want to think carefully firts before merging this PR.

**Comment by dominikl** [comment]
It's still a mystery for me why this is platform dependent (and why the Gateway PR reintroduces this problem). Probably quite difficult to debug/fix, except @jburel already has an idea (I guess he fixed it initially before the Gateway work).

**Comment by joshmoore** [comment]
Excluding for 5.1.3-rc1.

**Comment by jburel** [comment]
replaced by gh-4021

**Pull request closed without merging**
