### PR TITLE
Populate identifier.

### PR DESCRIPTION
**Pull request by jburel**
To test the PR
* Select a plate or a screen
* Select the populate-metadata script.
* Check that the IDs field is populated 
see https://trac.openmicroscopy.org/ome/ticket/13160

### CODE REVIEW

**Comment by pwalczysko** [comment]
The workflow works as expected. I think this is ready to merge. 


Nevertheless, the script failed - new error as of today. @dominikl 

```
java.lang.Exception: java.lang.Exception: org.openmicroscopy.shoola.env.data.ProcessException: Cannot run script with ID:54801
	at org.openmicroscopy.shoola.env.data.views.ProcessBatchCall.doStep(ProcessBatchCall.java:101)
	at org.openmicroscopy.shoola.util.concur.tasks.CompositeTask.doStep(CompositeTask.java:226)
	at org.openmicroscopy.shoola.env.data.views.CompositeBatchCall.doStep(CompositeBatchCall.java:126)
	at org.openmicroscopy.shoola.util.concur.tasks.ExecCommand.exec(ExecCommand.java:165)
	at org.openmicroscopy.shoola.util.concur.tasks.ExecCommand.run(ExecCommand.java:276)
	at org.openmicroscopy.shoola.util.concur.tasks.AsyncProcessor$Runner.run(AsyncProcessor.java:91)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.openmicroscopy.shoola.env.data.ProcessException: Cannot run script with ID:54801
	at org.openmicroscopy.shoola.env.data.OMEROGateway.runScript(OMEROGateway.java:503)
	at org.openmicroscopy.shoola.env.data.OMEROGateway.runScript(OMEROGateway.java:6288)
	at org.openmicroscopy.shoola.env.data.OmeroImageServiceImpl.runScript(OmeroImageServiceImpl.java:1611)
	at org.openmicroscopy.shoola.env.data.views.calls.ScriptRunner$1.initialize(ScriptRunner.java:77)
	at org.openmicroscopy.shoola.env.data.views.ProcessBatchCall.doStep(ProcessBatchCall.java:99)
	... 6 more
Caused by: omero.ValidationException
    serverStackTrace = ""
    serverExceptionClass = ""
    message = "Invalid parameters:
               WRONG TYPE for "IDs": <class 'omero.rtypes.RListI'> != <class 'omero.rtypes.RStringI'>
               "
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at IceInternal.BasicStream.createUserException(BasicStream.java:2615)
	at IceInternal.BasicStream.access$300(BasicStream.java:12)
	at IceInternal.BasicStream$EncapsDecoder10.throwException(BasicStream.java:3099)
	at IceInternal.BasicStream.throwException(BasicStream.java:2077)
	at IceInternal.Outgoing.throwUserException(Outgoing.java:538)
	at omero.api._IScriptDelM.runScript(_IScriptDelM.java:520)
	at omero.api.IScriptPrxHelper.runScript(IScriptPrxHelper.java:2642)
	at omero.api.IScriptPrxHelper.runScript(IScriptPrxHelper.java:2588)
	at omero.gateway.Gateway.runScript(Gateway.java:529)
	at org.openmicroscopy.shoola.env.data.OMEROGateway.runScript(OMEROGateway.java:499)
	... 10 more

	at org.openmicroscopy.shoola.env.ui.UserNotifierImpl.showErrorDialog(UserNotifierImpl.java:189)
	at org.openmicroscopy.shoola.env.ui.UserNotifierImpl.notifyError(UserNotifierImpl.java:289)
	at org.openmicroscopy.shoola.env.ui.UserNotifierImpl.notifyError(UserNotifierImpl.java:257)
	at org.openmicroscopy.shoola.env.ui.ActivityComponent.showException(ActivityComponent.java:403)
	at org.openmicroscopy.shoola.env.ui.ActivityComponent.actionPerformed(ActivityComponent.java:924)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by pwalczysko** [comment]
After debugging with @manics : 
   - it seems that the problem is connected to the line 185 of the ``populate_metadata.py`` itself where 
```
scripts.String(
            "IDs", optional=False, grouping="2",
            description="List of Image IDs to process."),
```
   - compare this with the same place of ``Batch_Image_Export.py``, line 523 where
```
 scripts.List(
            "IDs", optional=False, grouping="2",
            description="List of Dataset IDs or Image IDs").ofType(rlong(0)),
```
So maybe it is connected to the ID passing and thus to this PR @jburel ?

**Comment by jburel** [comment]
IDs should, in general, specify as list i.e. ```scripts.List``` instead of ```scripts.String```
I will adjust the way insight pass the parameters

**Comment by jburel** [comment]
With change https://github.com/will-moore/scripts/commit/6c8b74bc97ac8f2b32978fc85ccba74e3cf69eba
This PR is no longer required.

**Pull request closed without merging**
