### PR TITLE
logout redirects to login

### PR DESCRIPTION
**Pull request by will-moore**
When you logout, we previously tried to redirect to /webclient/. If public user was enabled for /webclient then you'd be auto logged in again (when you might have wanted to login as another user etc).
Now, we redirect to the login page.
When Public user is not enabled, the workflow is the same, since logout would then try to redirect to /webclient/ which would then redirect to /webclient/login/?url=%2Fwebclient%2F and then back to /webclient on login.

https://trello.com/c/AaY4cwkn/98-go-to-webclient-login-after-logout

# Testing this PR

1. In webclient, logout

1. Check that you are redirected to /webclient/login/  (NB: no ?url=%2Fwebclient%2F)

### CODE REVIEW

**Review by rgozim — APPROVED** [review]
Tested using public user and hitting the 'logout' button. Browser is directed to the login page, rather than back to the `/webclient` page.

**Comment by will-moore** [comment]
Still some Robot tests failing - I need to add more fixes...

**Comment by will-moore** [comment]
@jburel - The failure you're seeing at https://10.0.51.135:32776/job/OMERO-robot/22/robot/Web%20&%20Web/Web/Annotate%20Test/Test%20Search%20Results%20File%20Annotations/ should be fixed in this PR with 795bc26. Do you have this PR merged in your tests?

**Comment by will-moore** [comment]
Changing the PR target to include it in the robot tests fixed the test on Chrome: https://10.0.51.135:32776/job/OMERO-robot/24/robot/Web%20&%20Web/Web_1/Annotate%20Test/Test%20Search%20Results%20File%20Annotations/
but not on Firefox: https://10.0.51.135:32776/job/OMERO-robot/24/robot/Web%20&%20Web/Web/Annotate%20Test/Test%20Search%20Results%20File%20Annotations/

**Comment by joshmoore** [comment]
Ah, this is against `workflows` now. Shall we delay the other `public_user` items until after `5.4.2` then?

**Comment by rgozim** [comment]
Checked on web-dev-merge 👍

**Comment by jburel** [comment]
@rgozim this PR is not included in web-dev-merge

**Comment by will-moore** [comment]
Hmmm - strange. It seemed to be working earlier (clicking logout redirected to login page) when I saw @rgozim test this.
Maybe something else was going on. Will need to check but can't seem to access web-dev-merge now.

**Comment by jburel** [comment]
I can log in as user-1 w/o issue

**Comment by will-moore** [comment]
It was a problem with VPN from home.
Today, with this PR base now ```develop```, I am seeing the expected behaviour on web-dev-merge:
 - Logged-in as e.g. ```user-3```, logout button takes me to ```/webclient/login/```.

Previously this "appeared" to be working when testing logout as ```PUBLIC USER``` because the logout is a POST action that is not permitted by PUBLIC user, so the 403 redirects to login (public user is not actually logged out).
This can be seen when PUBLIC user logs out, the url they are redirected to is 
```/webclient/login/?url=%2Fwebclient%2F``` instead of simply ```/webclient/login/``` as above.

**Comment by joshmoore** [comment]
Merging for 5.4.2

**Comment by jburel** [comment]
Confirmation: Ran the robots w/o this PR and the changes were not needed

**Pull request merged**
