### PR TITLE
Ez setup fix

### PR DESCRIPTION
**Pull request by joshmoore**
Downloaded from https://bootstrap.pypa.io/ez_setup.py (which is now
deprecated) this corrects a failing build in travis. The overall
ez_setup/setuptools strategy will need to be reviewed, taking
pypa/setuptools#581 into account.

# What this PR does

Fixes the travis failure seen in https://github.com/openmicroscopy/openmicroscopy/pull/5559#issuecomment-340377649

# Testing this PR

1. Travis should be green
2. Local builds should pass

### CODE REVIEW

**Comment by mtbc** [comment]
Excellent, thank you. Is this something I can profitably --depends-on or ought I wait until it is merged?

**Comment by joshmoore** [comment]
With https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-merge-build/ now green, I'm inclined to say we should get this in. We may want to change the strategy (removing ez_setup) for 5.4.1, but it should at least get our PRs green.

**Review by sbesson — APPROVED** [review]
With the caveats mentioned in https://github.com/openmicroscopy/openmicroscopy/pull/5563#issuecomment-341641510, I second getting that in as this is currently blocking any proposed work. Is the follow-up review of `ez_setup.py` already captured as a card on the OMERO 5.4.1 board or elsewhere?

**Comment by joshmoore** [comment]
https://trello.com/c/cj2XYCzF/105-drop-or-fix-ezsetuppy :+1:

**Comment by joshmoore** [comment]
@mtbc @rgozim et al: you can close and re-open your PRs so that travis passes.

**Pull request merged**
