### PR TITLE
rewrite the policy rules for Chown2

### PR DESCRIPTION
**Pull request by mtbc**
This PR rewrites how the `Chown2` requests work to make them easier to adjust in the future. It introduces and uses a pluggable matcher for objects among the graph policy rules and adds more integration testing.

Testing: #3879 will help, especially its `--report` option. This PR should not introduce any regressions but change-owner has been rather untested anyway, so at this stage I'll be happy enough if it doesn't have obvious misbehaviors! We can fix smaller RFEs in later PRs.

### CODE REVIEW

**Comment by mtbc** [comment]
Reopen to try to placate Travis.

**Comment by mtbc** [comment]
See comments from https://github.com/openmicroscopy/openmicroscopy/pull/3879#issuecomment-114064985 on.

**Comment by ximenesuk** [comment]
This looks okay from a usage aspect. No surprises at least. I have scanned the code but if it needs a fuller review then that might be best looked at by someone else. Otherwise good to merge.

**Comment by joshmoore** [comment]
Currently, any user A can `chown` to another user B in the same rwra group. I find this surprising.

**Comment by mtbc** [comment]
@joshmoore: Only their own data, I hope? At http://downloads.openmicroscopy.org/omero/5.1.2/api/slice2html/omero/cmd/Chown2.html I appear to claim that,

> The user must be either an administrator, or the owner of the objects with the target user a member of the objects' group.

Should it be more restricted? (Maybe for a later PR though?)

**Comment by joshmoore** [comment]
Guess it depends on the difficulty (though we'll need tests one way or the other). As user B there's likely a reason I'd *not* want user A just giving me their data (imagine costing centers....)

**Comment by mtbc** [comment]
Definitely something we'll need to review with UX. Can easily tweak restrictions at least.

**Comment by mtbc** [comment]
The latest commit should fix the cross-owner container links in read-annotate groups. I'll also fix the `DetectorSettings` issue that @will-moore also noticed as part of work on this PR. It's lucky he tried that image: it has an instrument yet `Image.instrument` is null. That isn't a case I'd tested.

Various other RFEs are now captured on various Trello cards, e.g., https://trello.com/c/F4cAE0k3/358-graphexception-subclasses.

**Comment by mtbc** [comment]
Latest commit should fix the `DetectorSettings` issue.

**Comment by pwalczysko** [comment]
|Sorry for being slow on this, was doing the FLIMfit testing today.
When you say (on Standup) that the chown is to be tested the most, where is this actually exposed ? Only in command line ?

Please relist for tomorrow.

**Comment by mtbc** [comment]
Yes, command line. You can relist it too. :smiley:

**Comment by pwalczysko** [comment]
I made my comments onto https://github.com/openmicroscopy/openmicroscopy/pull/3879#issuecomment-113174289. The relevant commands Delete, Move and chown work, did just a quick test as asked for.

**Comment by mtbc** [comment]
:+1: Thank you. Regarding who should be able to chown, feel free to discuss on https://trello.com/c/PZQSlsGy/49-allow-group-owners-to-chown or I'll be happy to follow a more suitable UX card.

**Comment by mtbc** [comment]
(This PR doesn't actually change who can use `Chown2` but we can easily tweak that in followup PRs.)

**Comment by mtbc** [comment]
@pwalczysko, @will-moore: Okay to merge this then I will rebase the Chmod2 PR and we can get going on that?

**Comment by pwalczysko** [comment]
No objections to merge.

**Comment by mtbc** [comment]
Some more `Chown2` tests are coming in a later PR in https://github.com/mtbc/openmicroscopy/commit/1f1d576c62d66308de78d65a64a561904f4339ee.

**Comment by mtbc** [comment]
#3840 adds 29 more `Chown2` tests.

**Pull request merged**
