### PR TITLE
Backported UI support for float images

### PR DESCRIPTION
**Pull request by dominikl**
Gathered all UI changes for float images from develop branch together and rebased them to dev_5_0; this mainly affects the TwoKnobSlider.
Review: Check that the channel sliders work with int and float images. But also check other places where the TwoKnobSlider is used, e. g. the movie dialog.

To be able test this PR, #3366 should be included in the build.
/cc @jburel

### CODE REVIEW

**Comment by joshmoore** [comment]
Just restarted due to 247.

**Comment by dominikl** [comment]
I started Travis several times by re-comitting my last commit, it always fails. Does anyone know what the problem is?

**Comment by jburel** [comment]
Java was green,
failure on python front "The command "sudo pip install scc pytest" failed and exited with 2 during ."

**Comment by dominikl** [comment]
Ok. @joshmoore  just confirmed, that the dev_5_0 PRs will be in the merge build anyway, so shouldn't be a problem then.

**Comment by jburel** [comment]
@dominikl: user-3, looking at map file.
Full range should be turned off for double or float

**Comment by jburel** [comment]
Full range is now disabled.
I tried to Set min/max and Reset and Save from menu in Data Manager. It did not work.

**Comment by dominikl** [comment]
It actually works, but Set min/max doesn't update the thumbnail and Reset and save doesn't update the preview. Shall I try to fix that within this PR, and you exclude this PR (to get your PR merged) @jburel , or merge this one and I'll open another PR?

**Comment by dominikl** [comment]
Actually, shouldn't set min/max also be disabled for float images?

**Comment by jburel** [comment]
Why do you want to disable it?
Actually my PR does not conflict with yours.
It is probably to dangerous to fix it at the last minute

**Comment by dominikl** [comment]
Ok. Ah no, forget about the min/max disabling, just got a bit confused.

**Comment by jburel** [comment]
I was looking at a different PR, this one and #3406 are conflicting.

**Comment by dominikl** [comment]
@jburel Is there still something left, I should do within this PR? But as you want to start the RC build today, it might be already to late...

**Comment by jburel** [comment]
I think the other points are minor so I will not do anything more in this PR.
The major controls are in place so we can modify setting for float/double.
Merging

**Pull request merged**
