### PR TITLE
build: Remove support for C++ building via ant

### PR DESCRIPTION
**Pull request by rleigh-codelibre**
Drop C++ targets from the ant build

- Remove C++ targets
- `all` targets now delegate to the non-prefixed target, since they now do exactly the same thing
- Drop `-cpp` from build.py
- Remove last trace of C++ from SCons build; most was already removed

Testing:

- Check [job](https://ci.openmicroscopy.org/view/OMERO/job/OMERO-DEV-merge-cpp/) (should be no changes, since it's removals only)

See: https://trello.com/c/7rOcKabK/255-clean-up-c-build

### CODE REVIEW

**Comment by waxenegger** [comment]
https://ci.openmicroscopy.org/view/OMERO/job/OMERO-DEV-merge-cpp/440/ is green
https://ci.openmicroscopy.org/view/OMERO/job/OMERO-DEV-merge-build/534/ seems to only have warnings (if I don't misread something)

**Comment by jburel** [comment]
``<property name="env.NOMAKE" value="1"/>`` should no longer be needed

**Comment by rleigh-codelibre** [comment]
@jburel Thanks, now also removed.

**Comment by jburel** [comment]
Did you push a commit?

**Comment by rleigh-codelibre** [comment]
@jburel Oops, wrong branch.  Done now.

**Pull request merged**
