### PR TITLE
Webclient: flake8 urls

### PR DESCRIPTION
**Pull request by sbesson**
See https://trello.com/c/HP5YepWx/324-flake8-extension

This PR fixes `urls.py` to be flake8 compliant. Note the same convention as in `settings.py` is adopted i.e. urls are either preserved as single lines when possible or split across multiple-lines for each attribute.

--no-rebase

### CODE REVIEW

**Comment by will-moore** [comment]
Looks fine to me. Cheers!

**Comment by sbesson** [comment]
@will-moore: my biggest unknown was wether the multi-line raw strings with leading `r'` worked as expected. Did you test some of them?

**Comment by will-moore** [comment]
@sbesson No - didn't test anything specifically. Didn't know you had any concerns about functionality. But will test today.

**Comment by sbesson** [comment]
Sorry @will-moore, I wasn't explicit enough in the description, I would think the multi-line urls which are not tested by the Robot jobs should be tested. You may know better which ones are tested.

**Comment by will-moore** [comment]
I think most are covered by Robot tests. Tested a few more just now and didn't notice any issues.

**Comment by joshmoore** [comment]
Thanks, @will-moore.

**Pull request merged**
