### PR TITLE
Bump TestNG version to match other components of OMERO.

### PR DESCRIPTION
**Pull request by mtbc**
Seems odd to be using a different version of TestNG than most of its components. Can make testing with IDEs a bit of a pain.

### CODE REVIEW

**Comment by jburel** [comment]
more legacy than anything else

**Comment by jburel** [comment]
Thanks

**Comment by jburel** [comment]
The upgrade seems to be responsible for the failure of the test https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/317/
I am looking into it

**Comment by mtbc** [comment]
Interesting, thank you.

**Pull request merged**
