### PR TITLE
fix #11182: avoid Cartesian product of REINDEX eventlog entries

### PR DESCRIPTION
**Pull request by mtbc**
A good test is to move images like `test_images_good/bruker/wis/RA_060110.051/` and see that they go very much faster than before, but also that the resulting `REINDEX` entries in `eventlog` include all the same entities that were there without this PR but without, for that event ID, any duplication. Duplication is also eliminated for delete and much reduced for import. Also see https://github.com/openmicroscopy/openmicroscopy/pull/3286#issuecomment-70231069.

Fixes http://trac.openmicroscopy.org/ome/ticket/11182.

Also used this DB patch to fix https://trello.com/c/RjvIsota/369-review-db-trigger-fs-dir-delete and https://trello.com/c/SpdmwXBV/365-verify-postgresql-version-in-sql. (We can adjust for 9.x PostgreSQL prerequisite once that is decided outwith this PR.)

--no-rebase

### CODE REVIEW

**Comment by joshmoore** [comment]
A read through the more recent code changes seems fine. The Breaking queue has a few small failures which don't seem to be related. I'd propose trying the upgrade on a more complete DB early next week and then removing "Breaking".

**Comment by joshmoore** [comment]
Note: upgrade of nightshade copy is still running (in a screen on trout). If this is blocking anyone, might be worth removing `Breaking` before that completes.

**Comment by mtbc** [comment]
Nobody's lately mentioned wanting a DB patch number.

**Comment by mtbc** [comment]
Figured won't need *large* DB upgrade for any desired testing of more recent commits. I don't think I have anything other immediate DB work queued, until we get into rendering settings!

**Comment by joshmoore** [comment]
https://ci.openmicroscopy.org/job/OMERO-5.1-release-upgrade/VERSION=5.0.0,label=dogfish/17/console is still running. Rather than hold this up any longer, I've tested on a much smaller DB (2012-12-05-octopus) and things look fine:
 * `DELETE 3580` was the result of cleaning up the eventlogs, leaving 2537 'REINDEX' eventlogs.
 * Running the upgrade on a LATIN1 shows:

```
/tmp$ psql -v ON_ERROR_STOP=1 -a -d pr3286 -f /tmp/OMERO5.0__0.sql
...
SELECT assert_db_server_prerequisites(84000);
psql:/tmp/OMERO5.0__0.sql:72: ERROR:  OMERO database character encoding must be UTF8, not LATIN1
```

Removing `breaking`

**Comment by mtbc** [comment]
@joshmoore: Have you thoughts on what functional testing should try out in ensuring that annotations *are* still reindexed when they ought?

**Comment by joshmoore** [comment]
Previously, the issue was quite straight-forward. i.e. any modification of the annotation was simply missed on the image. So something as simple as:
 * either deleting an annotation with a unique string from an image should **not** return the image on search
 * or changing from one unique string on an image to another should **not** return for the old unique string and **should** return for the new unique string.

**Comment by mtbc** [comment]
Thank you, that makes sense.

**Comment by pwalczysko** [comment]
congrats, Bruker moved in less than a minute. Previously a matter of hours.

**Comment by pwalczysko** [comment]
I executed
  - `` psql -d OMERO-5.1-merge-deploy -c "select * from eventlog" | grep REINDEX > before_move.txt``
  - made the bruker move
  - executed `` psql -d OMERO-5.1-merge-deploy -c "select * from eventlog" | grep REINDEX > after_move.txt``
  - then

```
[hudson@ome-c6100-3 ~]$ diff after_move.txt before_move.txt 
4061,4081d4060
<  3211059 | REINDEX          |         -52 |    24579 | ome.model.core.Image                                |             | 325727
<  3211060 | REINDEX          |         -52 |    24576 | ome.model.core.Image                                |             | 325727
<  3211061 | REINDEX          |         -52 |    24575 | ome.model.core.Image                                |             | 325727
<  3211062 | REINDEX          |         -52 |    24574 | ome.model.core.Image                                |             | 325727
<  3211063 | REINDEX          |         -52 |    24573 | ome.model.core.Image                                |             | 325727
<  3211064 | REINDEX          |         -52 |    24572 | ome.model.core.Image                                |             | 325727
<  3211065 | REINDEX          |         -52 |    24571 | ome.model.core.Image                                |             | 325727
<  3211066 | REINDEX          |         -52 |    24570 | ome.model.core.Image                                |             | 325727
<  3211067 | REINDEX          |         -52 |    24569 | ome.model.core.Image                                |             | 325727
<  3211068 | REINDEX          |         -52 |    24568 | ome.model.core.Image                                |             | 325727
<  3211069 | REINDEX          |         -52 |    24567 | ome.model.core.Image                                |             | 325727
<  3211070 | REINDEX          |         -52 |    24566 | ome.model.core.Image                                |             | 325727
<  3211071 | REINDEX          |         -52 |    24565 | ome.model.core.Image                                |             | 325727
<  3211072 | REINDEX          |         -52 |    24564 | ome.model.core.Image                                |             | 325727
<  3211073 | REINDEX          |         -52 |    24563 | ome.model.core.Image                                |             | 325727
<  3211074 | REINDEX          |         -52 |    24562 | ome.model.core.Image                                |             | 325727
<  3211075 | REINDEX          |         -52 |    24561 | ome.model.core.Image                                |             | 325727
<  3211076 | REINDEX          |         -52 |    24581 | ome.model.core.Image                                |             | 325727
<  3211077 | REINDEX          |         -52 |    24580 | ome.model.core.Image                                |             | 325727
<  3211078 | REINDEX          |         -52 |    24578 | ome.model.core.Image                                |             | 325727
<  3211079 | REINDEX          |         -52 |    24577 | ome.model.core.Image                                |             | 325727
```
so are there duplications or not ? Not sure, will leave it to someone more proficient with psql.
(all done on trout/merge, db name indicated in command.

**Comment by joshmoore** [comment]
The `REINDEX` statements look ok. There's one per ID but not thousands per Image or anything similarly scary.

**Comment by mtbc** [comment]
:smiley:

**Comment by joshmoore** [comment]
Merging for the next fix. Thanks, guys.

**Pull request merged**
