### PR TITLE
in graph traversal avoid awful removeAll performance

### PR DESCRIPTION
**Pull request by mtbc**
This PR should improve the performance of model graph traversal operations without any change in behavior. @joshmoore managed to run into a performance issue that this change should fix.

--no-rebase

### CODE REVIEW

**Comment by jburel** [comment]
Do we have a test to expose that performance issue?

**Comment by mtbc** [comment]
No, I think it was related to IDR data?

**Comment by joshmoore** [comment]
The specific case was:

 * `bin/omero import` a fileset (grouped by a .screen file) which registers as SPW on the client.
 * on the server, no Plate is created, so there's a fileset with thousands of files and images but no top-level container.
 * `bin/omero delete Fileset:$ID` took quite a long time.

Likely, any synthetic fileset with many, many individual files would work.

**Comment by joshmoore** [comment]
--rebased-to #4374

**Comment by joshmoore** [comment]
Based on testing in gh-4375, I'd say this is good to merge.

**Comment by jburel** [comment]
@joshmoore @mtbc: thanks. Merging so it can be included in rc2

**Pull request merged**
