### PR TITLE
Filter rating robot tests

### PR DESCRIPTION
**Pull request by will-moore**
# What this PR does

Adds Robot tests to the filter-by-rating functionality in #4694 (not merged yet).

# Testing this PR
Check robot tests green in both browsers:
E.g. https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-merge-robotframework/467/robot/Web%20&%20Web/Web_1/Annotate%20Test/Test%20Rating/ 
AND
https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-merge-robotframework/467/robot/Web%20&%20Web/Web/Annotate%20Test/Test%20Rating/

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#533](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/533/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/533/consoleText) for more details.
Possible conflicts:
  - PR #4694 will-moore 'filter rating'
    - components/tests/ui/resources/web/tree.txt
  - PR #4924 will-moore 'Spw grid view2'
    - components/tests/ui/resources/web/tree.txt

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#534](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/534/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/534/consoleText) for more details.
Possible conflicts:
  - PR #4694 will-moore 'filter rating'
    - components/tests/ui/resources/web/tree.txt
  - PR #4924 will-moore 'Spw grid view2'
    - components/tests/ui/resources/web/tree.txt

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#535](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/535/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/535/consoleText) for more details.
Possible conflicts:
  - PR #4694 will-moore 'filter rating'
    - components/tests/ui/resources/web/tree.txt
  - PR #4924 will-moore 'Spw grid view2'
    - components/tests/ui/resources/web/tree.txt

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#536](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/536/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/536/consoleText) for more details.
Possible conflicts:
  - PR #4694 will-moore 'filter rating'
    - components/tests/ui/resources/web/tree.txt
  - PR #4924 will-moore 'Spw grid view2'
    - components/tests/ui/resources/web/tree.txt

**Comment by jburel** [comment]
see https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-merge-robotframework/482/ few failures

**Comment by will-moore** [comment]
Robot tests passing pretty well https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-merge-robotframework/521/robot/Web%20&%20Web/Web_1/Annotate%20Test/Test%20Rating/

**Comment by will-moore** [comment]
Even doing better in Chrome now too: https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-merge-robotframework/523/robot/Web%20&%20Web/Web/Annotate%20Test/Test%20Rating/

**Pull request merged**
