### PR TITLE
Search result count

### PR DESCRIPTION
**Pull request by will-moore**
RFE from Map Annotation search testing.
To test, search in web and check that result count is shown above results.
If a full page of results (500 or more) is retrieved for any data-type, the message will say:
E.g. "More than 567 results".

screen shot 2015-02-27 at 14 50 40

### CODE REVIEW

**Comment by joshmoore** [comment]
NB: server-side we have access to this value from Lucene: see https://github.com/openmicroscopy/openmicroscopy/blob/develop/components/server/src/ome/services/search/FullText.java#L372

Is it time to expose it? cc: @jburel @pwalczysko @will-moore

**Comment by pwalczysko** [comment]
@joshmoore : Cannot fully fathom from the code what the value is showing. Will it match perfectly with the number of found results (= number of lines in the results table in clients) ? If not, then no. If yes, then maybe we could show it saying ``so and so many results found, displayed so and so many``. 

cc\ @gusferguson ?

**Comment by joshmoore** [comment]
@pwalczysko : no, the code would allow you to say "in total there would be 1,000,000 results" even if you are only showing 100. Based on https://github.com/openmicroscopy/openmicroscopy/pull/3547#issuecomment-76409258, I'm thinking this is a "no", and we worry with `TOTAL_SIZE` later. (Keeping in mind that it can't be done in 5.1 unless it happens now)

**Comment by will-moore** [comment]
I don't know how often users are getting back more than 500 results per data-type, and if they are - how much do they care about the total hits? Maybe assume that this is not a priority until we hear otherwise.

@dominikl @jburel - apologies for just doing this and getting out of sync with Insight. Presumably this isn't too hard to add to Insight too?

**Comment by pwalczysko** [comment]
Yes, agree, lets just forget about the big totals - I just meant any number which tells me anything about result hits is helpful, even just to know that there are just 30 results displayed and it is worth to scroll through them or 300 and I should think about refining my query. This would be the main usecase I guess.

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#811](https://ci.openmicroscopy.org/job/OME-5.1-merge-push/811/). See the [console output](https://ci.openmicroscopy.org/job/OME-5.1-merge-push/811/consoleText) for more details.
Possible conflicts:
  - PR #3534 sbesson 'Webclient flake8 1'
    - components/tools/OmeroWeb/omeroweb/webclient/controller/search.py

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#812](https://ci.openmicroscopy.org/job/OME-5.1-merge-push/812/). See the [console output](https://ci.openmicroscopy.org/job/OME-5.1-merge-push/812/consoleText) for more details.
Possible conflicts:
  - PR #3534 sbesson 'Webclient flake8 1'
    - components/tools/OmeroWeb/omeroweb/webclient/controller/search.py

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#813](https://ci.openmicroscopy.org/job/OME-5.1-merge-push/813/). See the [console output](https://ci.openmicroscopy.org/job/OME-5.1-merge-push/813/consoleText) for more details.
Possible conflicts:
  - PR #3534 sbesson 'Webclient flake8 1'
    - components/tools/OmeroWeb/omeroweb/webclient/controller/search.py

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#814](https://ci.openmicroscopy.org/job/OME-5.1-merge-push/814/). See the [console output](https://ci.openmicroscopy.org/job/OME-5.1-merge-push/814/consoleText) for more details.
Possible conflicts:
  - PR #3534 sbesson 'Webclient flake8 1'
    - components/tools/OmeroWeb/omeroweb/webclient/controller/search.py

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#815](https://ci.openmicroscopy.org/job/OME-5.1-merge-push/815/). See the [console output](https://ci.openmicroscopy.org/job/OME-5.1-merge-push/815/consoleText) for more details.
Possible conflicts:
  - PR #3534 sbesson 'Webclient flake8 1'
    - components/tools/OmeroWeb/omeroweb/webclient/controller/search.py

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#816](https://ci.openmicroscopy.org/job/OME-5.1-merge-push/816/). See the [console output](https://ci.openmicroscopy.org/job/OME-5.1-merge-push/816/consoleText) for more details.
Possible conflicts:
  - PR #3534 sbesson 'Webclient flake8 1'
    - components/tools/OmeroWeb/omeroweb/webclient/controller/search.py

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#818](https://ci.openmicroscopy.org/job/OME-5.1-merge-push/818/). See the [console output](https://ci.openmicroscopy.org/job/OME-5.1-merge-push/818/consoleText) for more details.
Possible conflicts:
  - PR #3534 sbesson 'Webclient flake8 1'
    - components/tools/OmeroWeb/omeroweb/webclient/controller/search.py

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#819](https://ci.openmicroscopy.org/job/OME-5.1-merge-push/819/). See the [console output](https://ci.openmicroscopy.org/job/OME-5.1-merge-push/819/consoleText) for more details.
Possible conflicts:
  - PR #3534 sbesson 'Webclient flake8 1'
    - components/tools/OmeroWeb/omeroweb/webclient/controller/search.py

**Comment by joshmoore** [comment]
@will-moore : want me to remove "exclude" and you can close this so you can re-open yourself?

**Comment by will-moore** [comment]
I'll merge origin/develop and push sometime today.

**Comment by will-moore** [comment]
@joshmoore Should be OK to remove "exclude" label now, thanks.

**Comment by pwalczysko** [comment]
Works as expected. Ready to merge.

**Pull request merged**
