### PR TITLE
Robot apply rdefs

### PR DESCRIPTION
**Pull request by will-moore**
This is just a heads-up at the moment.
Will probably close it while I'm away, just in case the robot tests end up failing on CI.

This PR adds tests for a lot more functionality in the Preview Panel including "Save All". Also covers Right-click menu "Paste and Save", "Set Owner's and Save" and "Set Imported and Save".

### CODE REVIEW

**Comment by will-moore** [comment]
@bramalingam Here's my robot rendering defs PR - I'll leave it closed until I'm back, unless you want to play with it?

**Comment by will-moore** [comment]
Failing at https://ci.openmicroscopy.org/view/Failing/job/OMERO-5.1-merge-robotframework/211/console with:
```
05:50:41 Test Rdef Copy Paste Save :: Tests Copy and Paste rdef, then Save ... | FAIL |
05:50:41 WebDriverException: Message: u'unknown error: Runtime.evaluate threw exception: SyntaxError: Unexpected token ILLEGAL\n  (Session info: chrome=41.0.2272.118)\n  (Driver info: chromedriver=2.11.298611 (d1120fdf51badec2f7b63a96e19a58d4783de84d),platform=Mac OS X 10.9.5 x86_64)'
```
Should be fixed by previous commit.

**Comment by will-moore** [comment]
Failing with
```
05:57:51 Owner Group Edit :: Test group owner edit of their group.             | FAIL |
05:57:51 Selection of radio button 'permissions' should have been '0' but was '2'
```
now fixed by previous commit, since the setup.sh creates robot_group as a read-ann group.

**Comment by will-moore** [comment]
Last commit fixes latest fail on Firefox (element not visible since window is too small so the color-picker button is hidden).
```
ElementNotVisibleException: Message: u'Element is not currently visible and so may not be interacted with' ; Stacktrace: 
```

**Comment by will-moore** [comment]
Tests from this PR are now passing: https://ci.openmicroscopy.org/view/Failing/job/OMERO-5.1-merge-robotframework/213/console

**Comment by joshmoore** [comment]
Thanks, @will-moore

**Pull request merged**
