### PR TITLE
Decouple python

### PR DESCRIPTION
**Pull request by joshmoore**
This PR removes the Python source code and unit tests from underneath tools/Omero{Py,Web,FS} in favor of downloading the decoupled code (and `lib/scripts`) either from PyPI or GitHub. The goal is to have the OMERO.server and OMERO.py zips and dockers function identically to before this PR. Additional work on the decoupled PRs should then allow _ignoring_ the downloaded code that is in those zips in favor of a `pip install`ed version.

The primary downside of this PR is that merge-ci will be pinned to version 5.5.1 of the decoupled software until changes are made to merge PRs on the new repositories and download that updated code.

The current intent is that the integration tests in the main repository will continue to run until a job can be created to run the separated tests.

 * [x] remove scripts
 * [x] download scripts
 * [x] remove OmeroPy
 * [x] download OmeroPy
 * [x] remove OmeroWeb
 * [x] download OmeroWeb
 * [x] remove OmeroFS
 * [x] download OmeroFS

cc: @ome/python

### CODE REVIEW

**Comment by will-moore** [comment]
My notes on using this branch:

```
git checkout -f josh/decouple-python
ls dist/lib/python/      # still exists
rm -rf dist/lib/python/

# checked out omero-py and omero-web, then
cd omero-py
python setup.py build

cd omero-web
python setup.py build

# added .pth files to my site-packages
which python
  /Users/willadmin/Virtual/omero/bin/python
cat /Users/willadmin/Virtual/omero/lib/python2.7/site-packages/omero_py.pth
  /Users/willadmin/Desktop/PYTHON/omero-py/build/lib
cat /Users/willadmin/Virtual/omero/lib/python2.7/site-packages/omero_web.pth

# tried importing...
python
>>> import omero
>>> omero.__file__
'/Users/willadmin/Desktop/PYTHON/omero-py/build/lib/omero/__init__.pyc'
>>> import omeroweb
>>> omeroweb.__file__
'/Users/willadmin/Desktop/WEB/omero-web/build/lib/omeroweb/__init__.py'

# Try running omeroweb from source
cd omero-web
python omeroweb/manage.py runserver 4080
...
  File "/Users/willadmin/Desktop/MARSHAL/omero-marshal/omero_marshal/__init__.py", line 54, in get_schema_version
    raise Exception("Invalid OMERO version number: " + version)
Exception: Invalid OMERO version number: 5.5.dev1

# fixed with changes to omero_marshal.__init__.py
-VERSION_REGEXP = re.compile(r'^(\d+\.\d+\.\d+)')
+VERSION_REGEXP = re.compile(r'^(\d+\.\d+\.[a-z]*\d+)')
-    v = StrictVersion(m.group(1))
+    v = StrictVersion(m.group(1).replace('dev', ''))


python omeroweb/manage.py runserver 4080

gives me the login page, without any static files.
http://localhost:4080/webclient/login/ 
```

UPDATE:
omero.web.debug=True was being ignored (False) because ```OMERO_HOME``` wasn't set.
Fixed in https://github.com/joshmoore/omero-web/pull/1

**Comment by joshmoore** [comment]
Thanks for testing a omero-marshal fix, @will-moore. I went ahead and opened a PR using `pip install ...joshmoore...archive...zip` from merge-ci's OMERO-web job in order to get things running.

**Comment by will-moore** [comment]
Maybe also delete https://github.com/joshmoore/openmicroscopy/tree/decouple-python/etc/templates/web and move these to ```omero-web```.
They are needed for tests at ```test/unit/clitest/test_web.py```.

**Comment by joshmoore** [comment]
They do already exist at https://github.com/ome/omero-web/tree/master/templates but you're right they need deleting. I'll push a commit which copies them to the right location in `ome/openmicroscopy`.

**Comment by will-moore** [comment]
Ah - I realise that the ```test/unit/clitest/test_web.py``` is in ```omero-py``` not ```omero-web```.

**Comment by joshmoore** [comment]
Good catch. Should definitely also be migrated.

**Comment by joshmoore** [comment]
Waiting on a few minor reviews from @sbesson (e.g. https://github.com/ome/omero-gradle-plugins/pull/11) then will merge this PR and apply the necessary devspace changes (https://github.com/ome/devspace/pull/153) to `latest-ci`. 🤞 for a green build Monday AM.

**Comment by joshmoore** [comment]
Alright. Related PRs are all merged and changes from merge-ci have been applied to latest-ci. Merging this and re-running the latest-ci Trigger.

With the Python code removed, the excluded PRs can be updated to only contain the integration test changes. I'll update https://github.com/ome/openmicroscopy/pull/6055 to match https://github.com/ome/omero-web/pull/3 as an example.

Trigger runs:
 - https://latest-ci.openmicroscopy.org/jenkins/job/Trigger/163/

**Pull request merged**
