### PR TITLE
Matlab add colours to rois examples

### PR DESCRIPTION
**Pull request by emilroz**
Expand Matlab examples by setFillColor, setStokeColor and setTextValue.

### CODE REVIEW

**Comment by sbesson** [comment]
@emilroz: conceptually, all fine. In terms of testing, my issue while checking the output of the example script is that the `Rois.m` deletes the ROI after creating it (unrelated to this PR - likely historical). Would it be possible for you to migrate this ROI deletion block to the `DeleteData.m` example (preceded by a trivial ROI creation and upload) as part of this PR?

**Comment by emilroz** [comment]
@sbesson That should be no problem.

**Comment by sbesson** [comment]
Doh. I just realized the `Rois.m` example removed the shapes after creating them (using `removeShape`) preventing further examination. I will clean up in a follow-up PR. THanks for splitting the delete part.

**Comment by sbesson** [comment]
--no-rebase

**Pull request merged**
