### PR TITLE
Test cases for expanded user session creation abilities

### PR DESCRIPTION
**Pull request by chris-allan**
# What this PR does

Test cases for expanded user session creation abilities

### CODE REVIEW

**Comment by chris-allan** [comment]
Requires ome/omero-server#79, ome/omero-common#21, ome/omero-blitz#80 for tests to pass. Might need to be excluded until those are reviewed and merged.

/cc @joshmoore, @jburel

**Comment by joshmoore** [comment]
:+1: Looks like the status of all your PRs is green and therefore should have been merged this morning. Can you take a look at the following tests in terms of (intended) changes in functionality

 - https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/289/testReport/OmeroPy.test.integration.clitest.test_sessions/TestSessions/testTimeout/
 - https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/289/testReport/OmeroPy.test.integration.test_isession/TestISession/testUpdateSessions_who3_/

**Comment by chris-allan** [comment]
@joshmoore: I'll roll those changes into the OmeroPy PR which should be incoming today. The general position I have taken is that if the default time to idle is 0 then as a user you should be able to set whatever timeout you want and adjust it as many times as you want up or down.

I'll definitely have to look more closely at the `testUpdateSessions[who3]` failure as I'm not 100% on what it's trying to test. Probably have to look back at the original PR where it was added.

**Comment by joshmoore** [comment]
Travis failed with:

```
./components/tools/OmeroPy/test/integration/test_isession.py:1:1: E902 TokenError: EOF in multi-line statement
3691
```

**Comment by joshmoore** [comment]
Travis timed out. I've relaunched.

**Comment by chris-allan** [comment]
6fb23475390a488b62a9c6d1100ce14a2a9da14d should finally resolve the singular integration test case failure once and for all.

**Comment by chris-allan** [comment]
863cf4f46c615fcc9ba42ebb415d439517c7c23a should also bring the other test cases in line with 6fb23475390a488b62a9c6d1100ce14a2a9da14d and resolve the final test cases failures.

/cc @will-moore

**Comment by will-moore** [comment]
Travis failed with

```retrieve:
:: Apache Ivy 2.4.0 - 20141213170938 :: http://ant.apache.org/ivy/ ::
:: loading settings :: file = /src/etc/ivysettings.xml
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.ivy.util.url.IvyAuthenticator (file:/src/lib/repository/ivy-2.4.0.jar) to field java.net.Authenticator.theAuthenticator
WARNING: Please consider reporting this to the maintainers of org.apache.ivy.util.url.IvyAuthenticator
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
The build has been terminated```

**Comment by chris-allan** [comment]
So intensely frustrating. Re-started the build, hopefully it makes it in for tomorrow.

**Comment by jburel** [comment]
https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/309/ is green and has been for few days

**Comment by jburel** [comment]
Changes have now been merged. Merging the corresponding tests.

**Pull request merged**
