### PR TITLE
LocationDialog loading

### PR DESCRIPTION
**Pull request by dominikl**
Fixes [Ticket 13113](https://trac.openmicroscopy.org/ome/ticket/13113)

**Test:** Log in as user who has many projects/datasets. Open the import dialog, select a file to import, which brings up the LocationDialog. The Project and Dataset selection boxes should only show one item "Loading..." while the projects and datasets are loading. When the projects/datasets are loaded, the selection boxes should be populated. 

*This is not easy to test, I had to artifically delay the loading by adding a Thread.sleep() to the DMLoader. Created a 1000 datasets and projects for user-3/read-only, but still the loading is so fast, that you can't see the bug.*

### CODE REVIEW

**Comment by pwalczysko** [comment]
The workaround to get a slow server: take the insight client from OMERO-DEV-merge and connect to nightshade (additionally, if still too fast, work on Windows machine).
I can see the ``Loading...`` items in the P and D dropdown menus as described in the header of the PR.
But: when I ignore the Loading and go ahead and click onto ``Add to Queue`` I get

```
java.lang.Exception: Abnormal termination due to an uncaught exception.
java.lang.NullPointerException
    at org.openmicroscopy.shoola.agents.fsimporter.chooser.FileSelectionTable.addFiles(FileSelectionTable.java:570)
    at org.openmicroscopy.shoola.agents.fsimporter.chooser.ImportDialog.addFiles(ImportDialog.java:384)
    at org.openmicroscopy.shoola.agents.fsimporter.chooser.ImportDialog.showLocationDialog(ImportDialog.java:393)
    at org.openmicroscopy.shoola.agents.fsimporter.chooser.ImportDialog.propertyChange(ImportDialog.java:1651)
    at java.beans.PropertyChangeSupport.fire(Unknown Source)
    at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
    at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
    at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
    at java.awt.Component.firePropertyChange(Unknown Source)
    at javax.swing.JComponent.firePropertyChange(Unknown Source)
    at org.openmicroscopy.shoola.agents.fsimporter.chooser.FileSelectionTable.actionPerformed(FileSelectionTable.java:699)
    at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
    at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
    at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
    at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
    at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
    at java.awt.Component.processMouseEvent(Unknown Source)
    at javax.swing.JComponent.processMouseEvent(Unknown Source)
    at java.awt.Component.processEvent(Unknown Source)
    at java.awt.Container.processEvent(Unknown Source)
    at java.awt.Component.dispatchEventImpl(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Window.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$500(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)
Abnormal termination due to an uncaught exception.
java.lang.NullPointerException
    at org.openmicroscopy.shoola.agents.fsimporter.chooser.FileSelectionTable.addFiles(FileSelectionTable.java:570)
    at org.openmicroscopy.shoola.agents.fsimporter.chooser.ImportDialog.addFiles(ImportDialog.java:384)
    at org.openmicroscopy.shoola.agents.fsimporter.chooser.ImportDialog.showLocationDialog(ImportDialog.java:393)
    at org.openmicroscopy.shoola.agents.fsimporter.chooser.ImportDialog.propertyChange(ImportDialog.java:1651)
    at java.beans.PropertyChangeSupport.fire(Unknown Source)
    at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
    at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
    at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
    at java.awt.Component.firePropertyChange(Unknown Source)
    at javax.swing.JComponent.firePropertyChange(Unknown Source)
    at org.openmicroscopy.shoola.agents.fsimporter.chooser.FileSelectionTable.actionPerformed(FileSelectionTable.java:699)
    at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
    at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
    at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
    at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
    at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
    at java.awt.Component.processMouseEvent(Unknown Source)
    at javax.swing.JComponent.processMouseEvent(Unknown Source)
    at java.awt.Component.processEvent(Unknown Source)
    at java.awt.Container.processEvent(Unknown Source)
    at java.awt.Component.dispatchEventImpl(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Window.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$500(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)
Exception in thread "AWT-EventQueue-0"

    at org.openmicroscopy.shoola.env.ui.UserNotifierImpl.showErrorDialog(UserNotifierImpl.java:189)
    at org.openmicroscopy.shoola.env.ui.UserNotifierImpl.notifyError(UserNotifierImpl.java:289)
    at org.openmicroscopy.shoola.env.AbnormalExitHandler.doTermination(AbnormalExitHandler.java:147)
    at org.openmicroscopy.shoola.env.AbnormalExitHandler.terminate(AbnormalExitHandler.java:85)
    at org.openmicroscopy.shoola.env.RootThreadGroup.uncaughtException(RootThreadGroup.java:69)
    at java.awt.EventDispatchThread.processException(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by dominikl** [comment]
First I tried to disable the "add to queue" button until the projects are loaded, but then you'd always have to wait, even if you don't want to import to a specific project anyway. If you now click on "add to queue" while the projects are still loading, you can just go ahead and the file is imported like "no project"/"no dataset" had been chosen (i. e. a dataset is created automatically).

**Comment by pwalczysko** [comment]
- no crash now
  - the ``New`` buttons for P/D work as expected even when the loading did not finish yet
  - the workflow of the users though (mporter) is assuming creation of new P/D even when the list is not loaded yet and these P/Ds should be selected after the list has been loaded (just like if would be if no loading delay was happening).

**Comment by dominikl** [comment]
Yes, there's still one problem left, if you create a project/dataset (which is automatically selected of course) while the loading is still going on, the refresh when the loading is finished, wipes out the selection. That's not as easy to fix as I thought. I'm thinking about not touching the combo boxes but instead indicating the "loading" state by an additional label/icon.

**Comment by dominikl** [comment]
This has become quite an overhaul of the LocationDialog, therefore all import cases should be tested (with a slow server, e. g. nightshade):
- Simple import, "no project", "no dataset" selected
- Simple import, "no screen" selected
- Import into project which is created with "new" button, and dataset which is created with "new" button
- Import into screen, which is created with "new" button
- Import into existing project, dataset
- Import into existing screen.

Note: 
- Whenever the projects/datasets/screen are getting loaded from the server, the "loading spinner" should be shown on the top right of the LocationDialog.
- Ideally scenarios 1-4 should be tested while the data is still loading from the server.

**Comment by dominikl** [comment]
I just checked how it looks on Windows, because I switched the layout from TableLayout to GridBagLayout. Not good, the dialog looks very "compressed". I have to adjust that. Should have checked Windows and Linux, before opening the PR...

**Comment by pwalczysko** [comment]
Bug: On Mac, the "normal" insight (build b211 from today dev-merge).

  - open the Import Location dialog (after selecting an image)
  - observe that the list of Project and Datasets is loaded as expected
  - now toggle between ``Project`` and ``Screen`` buttons in the Import Location  dialog (press ``Screen``, then press ``Project`` again)
  - observe that the list of Project and Datasets is not loaded now at all (also no spinner) -> not expected
  - toggle to ``Screen`` and observe that the list of screens is not loaded either -> not expected

screen shot 2016-01-25 at 15 18 12

**Comment by pwalczysko** [comment]
Bug: After creation of new P/D/S, the list of  available P/D/S gets reordered.

  - open Import Location dialog after selecting an image
  - observe that the Project list is ordered as expected, this means that the Projects with are NOT greyed out are on the top of the list, then all the greyed out ones are beneath it (the interesting projects are on the top, the ones which you cannot use are on the bottom)
  - now create a new project inside the Import Location dialog
  - expand the list again, and observe that now the greyed out Projects are intermingled with the black ones -> not expected

Expected ordering
screen shot 2016-01-25 at 15 21 01
screen shot 2016-01-25 at 15 21 12


Not expected
screen shot 2016-01-25 at 15 25 22

**Comment by pwalczysko** [comment]
In summary for the "normal" insight: no problems, except 2 bugs https://github.com/openmicroscopy/openmicroscopy/pull/4406#issuecomment-174540312 and https://github.com/openmicroscopy/openmicroscopy/pull/4406#issuecomment-174543105 - but note that both bugs are present also on the latest build of insight, not fault of this PR.

**Comment by pwalczysko** [comment]
Standalone importer : exactly analogical problems (bugs) and pluses as in case of "normal" insight see https://github.com/openmicroscopy/openmicroscopy/pull/4406#issuecomment-174543499

**Comment by pwalczysko** [comment]
Fiji plugin importer exactly analogical problems (bugs) and pluses as in case of "normal" insight see #4406 (comment)

**Comment by pwalczysko** [comment]
Still persisting sorting problem on Dataset list only:
    - select any Project in the tree, start importer, select images, open Import Location window
    - create a new Project
    - deselect the new Project, select No Project
    - expand the Dataset list -> now the Datasets are wrongly sorted

**Comment by pwalczysko** [comment]
Works as expected. Ready to merge.

**Pull request merged**
