### PR TITLE
QA CLI

### PR DESCRIPTION
**Pull request by jburel**
Do not submit plate to QA from CLI (see https://github.com/openmicroscopy/openmicroscopy/pull/3418)

To test
 * Select a faulty plate to import
 * Select to submit logs and file
i.e.
```
bin/omero -s serverName -u userName import --report --logs --upload pathToPlate
```

### CODE REVIEW

**Comment by pwalczysko** [comment]
After executing
``bin/omero -s trout.openmicroscopy.org -u user-4 import --report --logs --upload ~/bd-pathway\ damaged/  -- --qa_baseurl=https://qa.staging.openmicroscopy.org/qa``
I get in the report
```
...
2015-02-06 10:32:12,792 39633      [      main] INFO         ome.formats.importer.ImportLibrary - Exiting on error
2015-02-06 10:32:12,793 39634      [      main] INFO      ome.formats.importer.cli.ErrorHandler - Reader: loci.formats.in.BDReader
2015-02-06 10:32:12,793 39634      [      main] INFO      ome.formats.importer.cli.ErrorHandler - instance: loci.formats.in.BDReader@9abd962
2015-02-06 10:32:13,265 40106      [      main] INFO      ome.formats.importer.cli.ErrorHandler - High-Content Screening (HCS)
2015-02-06 10:32:13,266 40107      [      main] INFO      ome.formats.importer.cli.ErrorHandler - To submit HCS data, please e-mail us.
2015-02-06 10:32:13,266 40107      [      main] INFO      ome.formats.importer.cli.ErrorHandler - Sending error report (1)...
2015-02-06 10:32:21,828 48669      [      main] INFO      ome.formats.importer.cli.ErrorHandler - Sending File(s)...
2015-02-06 10:32:23,543 50384      [      main] INFO      ome.formats.importer.cli.ErrorHandler - Sent log file.
```
There are no files submitted in the qa staging as expected.


When I import a non-SPW file (``test_images_broken/broken_images_scenario/``) the output says something about HCS as well - not sure why the file was not submitted either, just the error.

```
2015-02-06 10:43:59,182 11545      [      main] INFO      ome.formats.importer.cli.ErrorHandler - instance: loci.formats.in.OMEXMLReader@183c11f7
2015-02-06 10:43:59,336 11699      [      main] INFO      ome.formats.importer.cli.ErrorHandler - High-Content Screening (HCS)
2015-02-06 10:43:59,336 11699      [      main] INFO      ome.formats.importer.cli.ErrorHandler - To submit HCS data, please e-mail us.
2015-02-06 10:43:59,336 11699      [      main] INFO      ome.formats.importer.cli.ErrorHandler - Sending error report (2)...

==> Summary
```

**Comment by pwalczysko** [comment]
Another non-SPW file (lei with 56 images of which one is damaged MIF) worked as expected. No mention of HCS in the output and the log and file submitted in a zip.

```
2015-02-06 10:47:21,875 35853      [      main] WARN   del.enums.handlers.CorrectionEnumHandler - Unknown Correction value 'null' will be stored as "Other"
2015-02-06 10:47:21,877 35855      [      main] INFO      ome.formats.importer.cli.ErrorHandler - Light Microscopy
2015-02-06 10:47:21,877 35855      [      main] INFO      ome.formats.importer.cli.ErrorHandler - Sending error report (1)...
2015-02-06 10:47:22,885 36863      [      main] INFO      ome.formats.importer.cli.ErrorHandler - Sending File(s)...
2015-02-06 10:47:34,578 48556      [      main] INFO      ome.formats.importer.cli.ErrorHandler - Sent files and log file.

```

**Comment by pwalczysko** [comment]
It seems that some types of non-SPW files are mistakenly classified as HCS by the importer see https://github.com/openmicroscopy/openmicroscopy/pull/3442#issuecomment-73220278.

**Comment by jburel** [comment]
@pwalczysko: this is the problem with .ome file. it could be anything.

**Comment by pwalczysko** [comment]
Tested a sinle (non-.ome) file - a damaged screenshot.

```
...
2015-02-06 12:19:16,489 5943       [      main] INFO      ome.formats.importer.cli.ErrorHandler - Cannot determine domain: java.lang.NullPointerException
2015-02-06 12:19:16,489 5943       [      main] INFO      ome.formats.importer.cli.ErrorHandler - Sending error report (1)...
2015-02-06 12:19:17,509 6963       [      main] INFO      ome.formats.importer.cli.ErrorHandler - Sending File(s)...
2015-02-06 12:19:17,810 7264       [      main] INFO      ome.formats.importer.cli.ErrorHandler - Sent files.
```
So this looks as expected. Possibly just the problem of the .ome file then.

**Comment by joshmoore** [comment]
`.ome.tiff` and `.ome.xml` are definitely a problem here. I don't think we've ever found a good&fast way to handle that. /cc @melissalinkert 

Reading the code, I would have thought we had a `Reader` object somewhere so that we didn't have to do string parsing. Happy to look if you want.

**Comment by jburel** [comment]
From exception, we have ref as string to the reader used.

**Comment by melissalinkert** [comment]
Keep in mind that both of the .ome files in test_images_broken/broken_images_scenario have a Plate defined, so I would expect both to be detected as HCS/SPW.  The code appears to be correct in that setId is called before getDomains, so for truly non-HCS OME-XML/OME-TIFF it should do the right thing.

**Comment by pwalczysko** [comment]
@melissalinkert @jburel @joshmoore : After a retest, I can confirm what @melissalinkert claims above. The "normal" .ome-tiff image when damaged causes just

```
2015-02-06 15:38:16,589 19628      [      main] INFO      ome.formats.importer.cli.ErrorHandler - Reader: null
2015-02-06 15:38:16,590 19629      [      main] INFO      ome.formats.importer.cli.ErrorHandler - Cannot determine domain: java.lang.NullPointerException
2015-02-06 15:38:16,590 19629      [      main] INFO      ome.formats.importer.cli.ErrorHandler - Sending error report (1)...
2015-02-06 15:38:17,375 20414      [      main] INFO      ome.formats.importer.cli.ErrorHandler - Sending File(s)...
2015-02-06 15:38:18,088 21127      [      main] INFO      ome.formats.importer.cli.ErrorHandler - Sent files.

```
So this seems all pretty fine.

**Comment by jburel** [comment]
To avoid re-initializing the reader, it will be better to add a new field ```hasSPW``` to the exception e.g. to ```INTERNAL_EXCEPTION``` or  ```FILE_EXCEPTION```
This should be done in another PR cc @ximenesuk

**Comment by jburel** [comment]
Card created https://trello.com/c/fdAwQrhk/418-exception-add-spw-field
Merging this PR.

**Comment by jburel** [comment]
--no-rebase

**Pull request merged**
