### PR TITLE
web deplyment cmd params cleanup

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
This PR cleans up ``bin/omero web start`` args

Worker processes http://docs.gunicorn.org/en/stable/settings.html#worker-processes:
- worker (default 4, calculated  2-4 x NUM_CORES) 
 The number of worker processes for handling requests.
- worker class (sync (default), async: gevent, eventlet) 
 The type of workers to use.
- worker connections (default 1000)
 The maximum number of simultaneous clients. This setting only affects the Eventlet and Gevent worker types.
- threads (default 4, calculated 2-4 x NUM_CORES)
 The number of worker threads for handling requests. Run each worker with the specified number of threads.
- timeout (default 60s)

--excluded

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#218](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/218/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/218/consoleText) for more details.
Possible conflicts:
  - PR #4352 aleksandra-tarkowska 'wsgi-args in config'
    - components/tools/OmeroPy/src/omero/plugins/web.py

**Comment by aleksandra-tarkowska** [comment]
@manics regarding discussion in https://github.com/openmicroscopy/openmicroscopy/pull/4352 can I ask if all these params should be deprecated in favour of config ?

**Comment by manics** [comment]
I think it would be a lot nicer if they could be set in a config file.

**Comment by aleksandra-tarkowska** [comment]
by config file you mean ini or bin/omero config ?

**Comment by manics** [comment]
`bin/omero config`. Sorry that wasn't clear.

**Comment by aleksandra-tarkowska** [comment]
Closing this PR, as I will open one to support uwsgi

**Comment by joshmoore** [comment]
@aleksandra-tarkowska : what's the plan for/with uwsgi?

**Comment by aleksandra-tarkowska** [comment]
@joshmoore ``uwsgi`` is more complex then gunicorn and exposed download problem slightly better. Currently waiting for #4352 to be merged asap as is a blocker for any deployment PRs

**Comment by joshmoore** [comment]
So are you thinking we should deprecate/remove gunicorn for 5.2.2 or just have uwsgi as an option or just use for testing?

**Comment by aleksandra-tarkowska** [comment]
Have both, these are two currently used and supported tech. We should support both.

**Pull request closed without merging**
