### PR TITLE
Don't overwrite files with same names

### PR DESCRIPTION
**Pull request by dominikl**
See [Ticket 13223](https://trac.openmicroscopy.org/ome/ticket/13223), respectively point on Trello check list [Trac Tickets to consider](https://trello.com/c/ChsrJ25E/81-trac-tickets-to-consider).
**Test** workflow mentioned in ticket.

### CODE REVIEW

**Comment by mtbc** [comment]
Now if I try to attach another local file of the same name then both end up attached to the image with their differing content preserved.

**Comment by mtbc** [comment]
Attachment tooltip has useful information for figuring which is which.

**Comment by mtbc** [comment]
@kennethgillen: Is the above behavior good with you? If so, then this PR is good to merge.

**Comment by dominikl** [comment]
I think in Web it's the same behaviour, a new local file is just additionally attached not matter if a file with the same name already exists.

**Comment by sbesson** [comment]
@kennethgillen: you okay with merging this?

**Comment by kennethgillen** [comment]
👍  phenomenal folks. This is a big improvement. It'd be worth checking what the 'attached files' list shows now, as I seem to remember there was a listing of attached files available somewhere in one of the UIs. Perhaps multiple repetitions of the same filename? Not sure I remember where in the UIs I could see that, though.

**Comment by mtbc** [comment]
Yes, the name is repeated: click the little widgety things for the attachments in the metadata pane.

**Pull request merged**
