### PR TITLE
Units Conversions 3 (C++)

### PR DESCRIPTION
**Pull request by joshmoore**
Finally conversions are now supported in C++. In talking to @chris-allan, a decision was made to not try to have an arbitrary precision return type for C++. Instead, double is used. An exception will be thrown for any conversion that is simply to far out of scale to be calculable in double precision.

In addition:
 * python constructors are improved
 * pressure, length, time, and temperature equations are fix (see [ome-units](https://github.com/joshmoore/ome-units/commit/c2806c360691a9e1681a89f4ffeef3f995e1531c))
 * more tests are added (and passing)

### CODE REVIEW

**Comment by joshmoore** [comment]
Using breaking queue for an initial test run.

**Comment by joshmoore** [comment]
Re-running after fixes.

**Comment by joshmoore** [comment]
Un-breaking based on:
 * https://ci.openmicroscopy.org/view/Breaking/job/OMERO-5.1-breaking-integration-python/226/
 * https://ci.openmicroscopy.org/view/Breaking/job/OMERO-5.1-breaking-integration-java/227/
 * https://ci.openmicroscopy.org/view/Breaking/job/OMERO-5.1-breaking-cpp/187/

**Comment by rleigh-dundee** [comment]
I've had a look through.  I didn't spot anything obviously wrong.

Could we generate a comprehensive set of unit tests to get complete coverage and test all the failure cases as well?

While I didn't review the original addition of the conversion code, I am wondering why the conversions all need statically defining when the entire lot of the SI conversions could be generated and inserted into the maps in a few lines of code.

**Comment by joshmoore** [comment]
> Could we generate a comprehensive set of unit tests to get complete coverage and test all the failure cases as well?

Could do. It might be hard to know that we're not just generating mistakes into the tests though. Perhaps if someone other than me was doing it it would be marginally safer.

> While I didn't review the original addition of the conversion code, I am wondering why the conversions all need statically defining when the entire lot of the SI conversions could be generated and inserted into the maps in a few lines of code.

It's a good point. I haven't even tried special casing the SI-to-SI conversions. This was far more about the non-SI conversions which are the tricky ones.

**Comment by rleigh-dundee** [comment]
Doesn't need doing for this PR, just thought it would make things a bit easier to review and understand--it's not going to be easy to spot a single mistake in the vast quantity of generated code as it stands.

**Comment by joshmoore** [comment]
> it's not going to be easy to spot a single mistake in the vast quantity of generated code as it stands.

Definitely agreed! From my side, better to have eyes on the equations in ome-units, or help writing a hand-full of concrete tests rather than trying to generate tests.

**Comment by qidane** [comment]
Bits I have checked look fine to me.

**Comment by joshmoore** [comment]
Pushing fix for https://ci.openmicroscopy.org/view/Failing/job/OMERO-5.1-merge-cpp-win/VSARCH=x64,VSCONFIG=Debug,VSVERSION=vc100/167/console

**Comment by joshmoore** [comment]
Ah, https://ci.openmicroscopy.org/view/Failing/job/OMERO-5.1-merge-cpp-win/169/ is green (after several days of git errors). Merging. There may some final adjustments after @jburel's tests are run, but those will all be done together.

**Comment by jburel** [comment]
so far the changes have been in the stylesheet https://github.com/openmicroscopy/bioformats/pull/1665

**Pull request merged**
