### PR TITLE
Prevent NPE, download archived files

### PR DESCRIPTION
**Pull request by dominikl**
Tiny PR for fixing [Ticket 13187](https://trac.openmicroscopy.org/ome/ticket/13187)

**Test**: Download an archived image file.

### CODE REVIEW

**Comment by gusferguson** [comment]
@dominikl 

Tested using OMERO.insight-5.2.2-194-b23589f-ice35-b270-mac eel user-3

Behaves as expected.
Downloaded archived files opened locally in ImageJ.
Good to merge.

**Comment by jburel** [comment]
@dominikl: do we have archived image on eel? I don't think so.

**Comment by gusferguson** [comment]
@jburel - I just use the ones called "archived images".

**Comment by gusferguson** [comment]
@ - sorry - "archivedv" - the "nonarchivedv" won't allow download.

**Comment by dominikl** [comment]
Yes, I think so. I used images from "archived" dataset on eel/user-6 for testing. You can cross check with the insight latest build, should fail with a NPE.

**Comment by jburel** [comment]
@dominikl: thanks

**Comment by dominikl** [comment]
Might be another bug then. Do you have an example of an fs image for which the download option is disabled?

**Comment by jburel** [comment]
it should always be on for fs data. The archived on/off option was for data prior to fs.
@pwalczysko: do we have a db which such data? the nightshade dump won't be usable anymore

**Comment by pwalczysko** [comment]
@jburel 
> do we have a db which such data? 

Define ``such`` please.
In the DB which is a default on our servers, there are:
  - archived pre-fs images (``archived dv`` Datasets)
  - non-archived pre-fs images (``non-archived dv`` Datasets)
  - fs images (e.g. Project ``5.0 data``)

**Comment by jburel** [comment]
@pwalczysko: you answered my question, ``archived pre-fs images (archived dv Datasets)`` is the ``such``

**Comment by jburel** [comment]
Merging. Thanks

**Comment by pwalczysko** [comment]
You can always consult column L of the [DB setup sheet](https://docs.google.com/spreadsheets/d/1PPR86KSDFwxw47LBmhq3jW_0CfAKOVRns2YAzyqHwI0/edit#gid=0). Note that the first 3 listed DBs are full of pre-fs data, the one listed on line 7 is the default atm for eel daily builds.

**Pull request merged**
