### PR TITLE
Have disk usage give an error message when a bad class name is given

### PR DESCRIPTION
**Pull request by mtbc**
For instance, try `bin/omero fs usage Blah:1`; also check that https://ci.openmicroscopy.org/job/OMERO-5.1-merge-integration-java/lastCompletedBuild/testngreports/integration/DiskUsageTest/ passes.

--no-rebase

### CODE REVIEW

**Comment by ximenesuk** [comment]
Testing locally to modify gh-3507 I noticed that the object I get back now no longer has a value for the `message` key. I was using the `message` key before and I guess it is where I would expect an error message. Is the `message` key no longer used at all? 
```
object #0 (::omero::cmd::ERR)
{
    category = ::omero::cmd::DiskUsage
    name = class Blah is unknown
    parameters =
    {
        key = stacktrace
        value = java.lang.IllegalArgumentException
	at omero.cmd.graphs.DiskUsageI.getIdPropertyFor(DiskUsageI.java:445)
        ... [omitted]

        key = message
        value =
    }
}
```

**Comment by ximenesuk** [comment]
I've tested this in as much as I get the right responses for errors via the disk usage plugin. However, Mark has applied the use of the exception message field across a whole range of command classes. From reviewing the code all the changes look consistent but I don't know if a more thorough review is required. /cc @joshmoore

**Comment by mtbc** [comment]
I was testing them mostly by playing around with the `chgrp` and `delete` available from the CLI: for instance, one can get an error by trying them on only one of the images of a MIF. It may also be worth retesting #3440, I now realize I forgot to do that.

**Comment by ximenesuk** [comment]
Thanks. I may have to pass on any wider testing today. It may be worth re-listing tomorrow.

**Comment by ximenesuk** [comment]
The error messages look fine with the cli `delete` and `chgrp`. However, when I tried to force an error by moving part of a MIF between groups in Insight (see gh-3440) I get an exception and termination, below. /cc @dominikl @jburel @joshmoore 

```
java.lang.Exception: Abnormal termination due to an uncaught exception.
java.lang.IllegalStateException: The name should never have been be null
	at pojos.GroupData.getName(GroupData.java:150)
	at org.openmicroscopy.shoola.agents.treeviewer.util.MIFNotificationDialog.buildGUI(MIFNotificationDialog.java:184)
	at org.openmicroscopy.shoola.agents.treeviewer.util.MIFNotificationDialog.<init>(MIFNotificationDialog.java:351)
	at org.openmicroscopy.shoola.agents.treeviewer.view.TreeViewerComponent.handleSplitImage(TreeViewerComponent.java:4808)
	at org.openmicroscopy.shoola.agents.treeviewer.ImageChecker.handleResult(ImageChecker.java:119)
	at org.openmicroscopy.shoola.env.data.events.DSCallAdapter.eventFired(DSCallAdapter.java:90)
	at org.openmicroscopy.shoola.env.data.views.BatchCallMonitor$1.run(BatchCallMonitor.java:124)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Abnormal termination due to an uncaught exception.
java.lang.IllegalStateException: The name should never have been be null
	at pojos.GroupData.getName(GroupData.java:150)
	at org.openmicroscopy.shoola.agents.treeviewer.util.MIFNotificationDialog.buildGUI(MIFNotificationDialog.java:184)
	at org.openmicroscopy.shoola.agents.treeviewer.util.MIFNotificationDialog.<init>(MIFNotificationDialog.java:351)
	at org.openmicroscopy.shoola.agents.treeviewer.view.TreeViewerComponent.handleSplitImage(TreeViewerComponent.java:4808)
	at org.openmicroscopy.shoola.agents.treeviewer.ImageChecker.handleResult(ImageChecker.java:119)
	at org.openmicroscopy.shoola.env.data.events.DSCallAdapter.eventFired(DSCallAdapter.java:90)
	at org.openmicroscopy.shoola.env.data.views.BatchCallMonitor$1.run(BatchCallMonitor.java:124)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Exception in thread "AWT-EventQueue-0"

	at org.openmicroscopy.shoola.env.ui.UserNotifierImpl.showErrorDialog(UserNotifierImpl.java:191)
	at org.openmicroscopy.shoola.env.ui.UserNotifierImpl.notifyError(UserNotifierImpl.java:291)
	at org.openmicroscopy.shoola.env.AbnormalExitHandler.doTermination(AbnormalExitHandler.java:147)
	at org.openmicroscopy.shoola.env.AbnormalExitHandler.terminate(AbnormalExitHandler.java:85)
	at org.openmicroscopy.shoola.env.RootThreadGroup.uncaughtException(RootThreadGroup.java:69)
	at java.awt.EventDispatchThread.processException(EventDispatchThread.java:264)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:256)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

**Comment by ximenesuk** [comment]
I think the above means that this PR is good to merge but has knock-on effects for Insight. I don't know if there are any effects on the web client.

**Comment by mtbc** [comment]
I'll fix Insight in this PR. After all, if this PR broke it ... :smiley:

**Comment by ximenesuk** [comment]
After discussion with @mtbc it looks like this may be an unrelated bug. I will try to reproduce with today's build and then open a ticket. /cc @dominikl @jburel

**Comment by mtbc** [comment]
I don't seem to be able to reproduce this error on trout today. The error messages do still seem to work well
dialog

**Comment by ximenesuk** [comment]
In that case I'd say this PR is good to merge and with it gh-3507

**Pull request merged**
