### PR TITLE
Remove last vestiges of Ice 3.4

### PR DESCRIPTION
**Pull request by rleigh-dundee**
It's no longer being built or tested, and is no longer supported by us or by ZeroC, and has not been provided by Linux distributions for some years now.  This PR

- drops the 3.4 version from the ant build
- removes special-cased behaviour for 3.4 in OmeroCpp

--------

Testing: Check builds are green; there's nothing to test beyond that.

### CODE REVIEW

**Comment by rleigh-dundee** [comment]
Note: Travis depends on https://github.com/openmicroscopy/openmicroscopy/pull/4407 and so won't go green until this is merged.

**Comment by joshmoore** [comment]
Relaunched now that 4407 is merged.

**Comment by jburel** [comment]
We need to be careful here. I understand the rationale behind it but
Dropping ice 3.4 during a point release w/o prior clear announcement, will certainly generate issues for people who went through the upgrade process and who are still running ice 3.4.
I think we would avoid a flow of unpleasant e-mails, forum posts post 5.2.2 release
This should be announced at the same time as reducing our support for windows (server side) (blog post in preparation)
This PR should go in the breaking queue for now (i.e. 5.3).

**Comment by rleigh-dundee** [comment]
@jburel It's already dropped, and was for 5.2.0.  This is the last little piece of 3.4 support remaining.

**Comment by hflynn** [comment]
We have not made a clear specific announcement but dropping 3.4 for 5.2 was included in the consultation over https://www.openmicroscopy.org/site/support/omero5.2/sysadmins/version-requirements.html and the sysadmins what's new page does refer people there to check what version support changes have been made - and that page does list 3.4 as dropped for 5.2.
And there are no Ice 3.4 downloads for 5.2.
So we may have been somewhat quiet about it but we did essentially drop it with 5.2.

**Comment by jburel** [comment]
We certainly do not provide a version with ice 3.4 on the download page and use the term "dropped" in the requirements page. 
The term "not recommanded" should have been more appropriate than dropped. Similar to what we did for Django 1.6 vs 1.8
Since it is still possible to build from source using ice 3.4, and we have clear instructions on how to do so (see https://www.openmicroscopy.org/site/support/omero5.2/developers/installation.html). I just did a build on CentOS 6 with ice 3.4. of omero 5.2.1. 
```
su - omero -c "openmicroscopy-5.2.1/dist/bin/omero admin diagnostics"

================================================================================
OMERO Diagnostics 5.2.1-ice34
================================================================================
        
Commands:   java -version                  1.7.0     (/usr/bin/java)
Commands:   python -V                      2.6.6     (/usr/bin/python)
Commands:   icegridnode --version          3.4.2     (/usr/bin/icegridnode)
Commands:   icegridadmin --version         3.4.2     (/usr/bin/icegridadmin)
Commands:   psql --version                 9.4.5     (/usr/bin/psql)
```
So other might do the same if for some reasons they cannot upgrade to ice 3.5.
That is something that we cannot ignore.

**Comment by rleigh-dundee** [comment]
@jburel It "works" for the moment, but it's entirely untested and unsupported, and has been for months.  Maybe let's look at the usage stats and see if there are any actual users?  It was minimal for 5.1, so I'd be very surprised if there were any users of it over the last couple of months.  But the logs should show that.

**Comment by jburel** [comment]
@rleigh-dundee: True that it was minimal, but I would rather have had a clear announcement. So that there is no ambiguity. 
If people know that it is possible in the code, they will use it and ignore the doc. (We will do the same!)

**Comment by jburel** [comment]
Still some reference for example in:
* ```build.xml```, ```CMakeLists.txt ```, ```FindIce.cmake```
* ```omero_model_ElectricPotentialI.py```, ```omero_model_FrequencyI.py```, ```omero_model_LengthI.py```, ```omero_model_PowerI.py```, ```omero_model_PressureI.py```, ```omero_model_TemperatureI.py```, ```omero_model_TimeI.py```

**Comment by joshmoore** [comment]
The unit files were all code-gen'd. This is likely a good time to revive the unit code-generation and push the repo to the team. cc: @sbesson

**Comment by joshmoore** [comment]
Opened https://github.com/ome/ome-units/pull/4 which produced https://github.com/joshmoore/openmicroscopy/commit/6fb4a976708b758fbfe18adf8ba235665c575b6a

**Comment by jburel** [comment]
thanks @joshmoore, 
@rleigh-dundee could you cherry-pick the commit and clean up the rest so we can wrap up this PR

**Comment by rleigh-dundee** [comment]
Done

**Comment by jburel** [comment]
could you also look at build.xml and the other files? Thanks

**Comment by rleigh-dundee** [comment]
@jburel Done.  Note `FileIce.cmake` won't be updated--it's a copy of the CMake macro which supports all Ice versions, so it doesn't affect anything.

**Comment by jburel** [comment]
List of files to still look at:
 * ```OmeroPy/test/integration/test_model51.py```
 * ```OmeroPy/test/unit/test_model.py```
 * ```OmeroPy/src/omero/columns.py```
 * ```OmeroPy/src/IceImport.py```
 * ```OmeroPy/src/omero/plugins/admin.py```
 * ```OmeroCpp/src/omero/sys/ParametersI.h```
 * ```server/src/ome/services/sharing/make_data.py```

**Comment by rleigh-dundee** [comment]
@joshmoore The only one of the above I'm unsure of is `columns.py` line 140.  I'm not sure if the commented part is still valid or if it's ever been tested.

**Comment by joshmoore** [comment]
`columns.py` discussion got added as https://trello.com/c/ARm14UMd/628-omero-tables-unneeded-copies-ice-3-5 -- I'd assume it's ok to investigate that later.

**Comment by jburel** [comment]
Thanks @rleigh-dundee 
Merging

**Pull request merged**
