### PR TITLE
Fix layout of my_account form

### PR DESCRIPTION
**Pull request by will-moore**
# What this PR does

Fixes my-account page. See https://trello.com/c/lrHDbfX9/658-bugregerssion-css-on-user-settings-in-web-550

# Testing this PR
 - check that the "User settings" form looks not-broken.

### CODE REVIEW

**Comment by joshmoore** [comment]
@will-moore : do you have any idea what caused the regression?

**Comment by mtbc** [comment]
Regardless of Travis this PR works well for me and the code change looks sensible.

Before:

before

After:

after

**Comment by joshmoore** [comment]
Thanks, @mtbc. It would still be interesting to know if there's anything we can do (place a warning on the template, etc) to keep these things in sync. Merging.

**Comment by will-moore** [comment]
@joshmoore Sorry, I started trying to check older versions of web for when this broke, but ran into trouble trying to run and build older servers.

**Pull request merged**
