### PR TITLE
add integration tests for disk usage request

### PR DESCRIPTION
**Pull request by mtbc**
#2919, #3110 and #3271 were merged without any direct integration tests. Look for passes at https://ci.openmicroscopy.org/job/OMERO-5.1-merge-integration-java/lastCompletedBuild/testngreports/integration/integration.DiskUsageTest/.

--no-rebase

### CODE REVIEW

**Comment by ximenesuk** [comment]
This looks fine and passes locally, which is always good! The coverage looks good, is there no easy way to test for thumbnail size given a local repository?

**Comment by mtbc** [comment]
Perhaps `ManageImageBinaries`? I could give it a try.

**Comment by ximenesuk** [comment]
This all looks okay, passes locally, changes look good, etc. I don't know if @joshmoore wants to look this over before merging?

**Comment by joshmoore** [comment]
Looks great. Thanks, guys.

**Pull request merged**
