### PR TITLE
Robot fix xpath to dialog button

### PR DESCRIPTION
**Pull request by will-moore**
The buttons in the jQuery UI dialog seems to have been changed by some jQuery UI issue, which
causes a lot of tests to fail.

I previously saw this on my old laptop where tests failed (without this PR change) but it has been passing on the CI job until recently.

### CODE REVIEW

**Comment by will-moore** [comment]
Today with this fix, we have only 19 failing tests https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-merge-robotframework/203/ instead of 62 yesterday https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-merge-robotframework/202/. Will look at the remaining failures...

**Comment by will-moore** [comment]
https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-merge-robotframework/209/ Doesn't have any "robot results". @sbesson any ideas? Just re-run again?

**Comment by will-moore** [comment]
Ooops - my bad (above). Robot tests [are running again](https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-merge-robotframework/208/robot/Web%20&%20Web/Web_1/Create%20Scenario/Test%20Create%20Dataset%20Using%20Icon/), but failing with E.g.
```
ValueError: Element locator 'xpath=//div[contains(@class,'ui-dialog')][contains(@style,'display: block')]//button/span[contains(text(), 'OK')]' did not match any elements.
```
which suggests that this PR is not included. @sbesson Any ideas what's up here?

**Comment by sbesson** [comment]
@will-moore: looking at the job [console log](https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-merge-robotframework/212/console) it looks like the job is failing when populating the data for the tests:

```
05:52:03 + python lib/python/omero/util/populate_metadata.py -k 02f36117-55e8-4bb8-99de-748c6ec0cdee Plate:261 bulk_annotation.csv
05:52:03 Traceback (most recent call last):
05:52:03   File "lib/python/omero/util/populate_metadata.py", line 33, in <module>
05:52:03     import omero.clients
05:52:03 ImportError: No module named omero.clients
```

**Comment by will-moore** [comment]
@sbesson Sorry - yes, I just found that. 
I was confused because the page at https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-merge-robotframework/ links to Robot Results from a few days ago.

The problem is caused by https://github.com/openmicroscopy/openmicroscopy/pull/4446.
I previously had a line to set the $PYTHONPATH but removed it because it was failing
https://github.com/will-moore/openmicroscopy/commit/562e88f4ea82f976cf6f94bd96e8003756e362e8
and now it's failing to import.
Any idea how I can get ```dist/lib/python``` onto the PYTHONPATH?

**Comment by will-moore** [comment]
We are back to a small number of Robot tests failing: https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-merge-robotframework/217/robot/ so I think this is working now.

**Comment by will-moore** [comment]
The whole reason for the failure of Robot tests on the dialog buttons was webtagging React PR adding in Bootstrap.button(), which created dialog buttons without the extra ```span``` element.

**Comment by will-moore** [comment]
Only 1 failure now, so things are looking good: https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-merge-robotframework/221/robot/

**Comment by aleksandra-tarkowska** [comment]
Test are green https://ci.openmicroscopy.org/view/DEV/job/OMERO-DEV-merge-robotframework/224/robot/

**Comment by aleksandra-tarkowska** [comment]
Looks good to me. as test was green two days in the raw I think is good to merge

**Comment by aleksandra-tarkowska** [comment]
Looks good to me. Test are passing two days in a raw. Good to merge

**Comment by jburel** [comment]
Waiting an extra day, but certainly looks much better

**Comment by jburel** [comment]
https://ci.openmicroscopy.org/view/OMERO-DEV/job/OMERO-DEV-merge-robotframework/ is green
merging

**Pull request merged**
