### PR TITLE
Measurementtool DnD

### PR DESCRIPTION
**Pull request by dominikl**
This PR adds drag and drop support to the ROI table. There's just a little flaw, with drag and drop enabled the CTRL click multi selection sometimes doesn't work properly when clicked in the first column of the table (but fine when the other columns are used). Not sure if this is just an OSX issue. Will check with other platforms, too.

Other points fixed in this PR:
- Folders are now alphabetically sorted
- Folders can now contain sub folders as well as ROIs

(based on PR #4497)

### CODE REVIEW

**Comment by gusferguson** [comment]
@dominikl cc @pwalczysko 

Tested using OMERO.insight-5.3.0-m1-41-e798aac-ice35-b63-mac regions-omero.docker.openmicroscopy.org DB: user-14

Drag and drop single ROI to single (unnested) folder works as expected.
Drag and drop to folder with subfolders - ROI goes in at top level - i.e. violates rule of ROIs and Folders in Folder - screenshot 1
Drag and drop to expanded subfolder - error occurred while saving ROI (ROI is saved) - Measurement Tool closed
On attempting to save after ROIs at top level - got same error and ROIs disappeared from folder.
subsequently drag to nested folder gave same error - both Mac and Windows
Mac - multi-selection and drag of ROIs does not work - either shift-select or cmd-select - just reverts to single selection when drag attempted.

When testing on Windows - same deselection of multi-selected ROIs, but now getting error message for any drag and drop attempt - possibly something fallen over on the server.

id- 4908 20110209_region1_1505_atp zvi

**Comment by pwalczysko** [comment]
> ....CTRL click multi selection sometimes doesn't work properly when clicked in the first column of the table 

Confirmed on Mac Yosemite.
On Win7, I have successful Ctrl click multiselect behaviour on the first column, but the right-click menu is interfering there, so that I have to click twice for every subsequent line in the multi-select workflow in order to really select it

**Comment by pwalczysko** [comment]
When attempting D & D, for both folders and ROIs, I get only "Error occurred when saving ROIs" dialogs, both Mac and Win, both user-14 and user-15. 
Will defer testing here for later, also considering the seriousness of the bugs reported by @gusferguson

**Comment by dominikl** [comment]
Just a note: I was wondering why you get a lot of errors and I hardly get any while developing. I think that's because on my local server the ROIs and folders belong all to the user which is logged in; whereas on the regions-ci server there are folders with the same name multiple times, some owned by user-14 and some owned by user-15. For the DnD actions I don't do any permissions checking yet, that might explain the errors. I find it very hard using the regions-ci server for testing, because the same folder names are now duplicated four times (two belonging to user-14 and two belonging to user15), totally confusing.

**Comment by gusferguson** [comment]
Regarding th errors -  think something happened that caused them to start occurring - I didn't get any at the start and then after I had the first a lot of actions that were not giving errors before started giving them.

**Comment by dominikl** [comment]
The restriction that a folder can only contain folders or rois, but not both was a bit artificial, it should work fine with mixed folders, too. With the last commit I removed this restriction.

**Comment by dominikl** [comment]
If this PR and #4497 work reasonable well (ie only minor, non-disruptive issues), it'd be good to merge them and I'll open a bugfix PR later. Because then I could continue with other important features, like the filtering/selective display of folders, without spending too much time now on rather minor issues. If that's ok with you guys.

**Comment by gusferguson** [comment]
@dominikl cc @pwalczysko 

Tested using OMERO.insight-5.3.0-m1-43-7eaeac5-ice35-b64-mac El Capitan and OMERO.insight-5.3.0-m1-43-7eaeac5-ice35-b64-win Win 8.1 user 14.

Drag and drop working as expected for all types of ROI, propagated, newly draw and existing ROIs, to all folders - new and already existing, to all levels of the folder hierarchy and within folder hierarchies.

Multi-selection drag and drop working if you select lowest most - shift - click top most and then drag all without releasing. Otherwise get desolation and no drag and drop.

Happy for this PR to be merged and minor issues like mult-selection worked on in another PR.

**Comment by pwalczysko** [comment]
Experienced the same problems as @gusferguson with the multiselection. My solution was to right-click on the multiselected images and then Drag and Drop.

Bug:
Expand a folder containing subfolders, select it in the expanded state (the folders, the subfolders and yet another non-expanded folder are included in the selection). Then right-click and Drag and Drop. Observe that you get the ``OptimisticLock`` exception in the log, and in the UI you get warning dialog. Action does not go ahead.

**Comment by pwalczysko** [comment]
Also happy to merge, and deal with the bug https://github.com/openmicroscopy/openmicroscopy/pull/4520#issuecomment-195422556 and the multiselection behaviour in subsequent PR.

**Pull request merged**
