### PR TITLE
Java9

### PR DESCRIPTION
**Pull request by jburel**
Few changes in order to work with Java 9

Tested with 
``
java version "9-ea"
Java(TM) SE Runtime Environment (build 9-ea+116)
Java HotSpot(TM) 64-Bit Server VM (build 9-ea+116, mixed mode)
```

Testing on breaking to evaluate status with current  Java version

### CODE REVIEW

**Comment by joshmoore** [comment]
Along with https://github.com/openmicroscopy/openmicroscopy/pull/4636/commits/7902da7d6fbda822961050ea348d636f054216e6, https://github.com/openmicroscopy/openmicroscopy/blob/v5.2.3/components/tools/OmeroPy/src/omero/plugins/prefs.py#L51 should be removed and all uses.

**Comment by jburel** [comment]
All good on breaking this am, I will continue the cleaning and run further tests.
This PR will be closed now so @sbesson can bring back regions.

**Comment by aleksandra-tarkowska** [comment]
@jburel if you wish to test that on devspace, first step will be to fix swarm plugin to work with java9 see https://github.com/openmicroscopy/devslave-c7-docker (see travis https://travis-ci.org/openmicroscopy/devslave-c7-docker/builds/124610520)

**Comment by jburel** [comment]
I have a branch installing java9 on centos and ubuntu.
nothing urgent for now

**Pull request closed without merging**
