### PR TITLE
Django upgrade follow up

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
This is #4236 follow up PR. It fixes:
 - adds TEMPLATES settings introduced in 1.8, see https://docs.djangoproject.com/en/1.8/ref/templates/upgrading/
 - removes deprecated cache_choice (never used), see https://docs.djangoproject.com/en/1.8/releases/1.8/#cache-choices-option-of-modelchoicefield-and-modelmultiplechoicefield
 - resolve experimenter form password order issue reported in https://trac.openmicroscopy.org/ome/ticket/13063 //cc: @pwalczysko 

Testing servers: cowfish/integration and eel/merge

To test:
 - check on both servers if experimenter form fields are in the right order, see https://github.com/openmicroscopy/openmicroscopy/pull/4236#issuecomment-147668137
 - test annotation forms (comment, tag, etc.)

### CODE REVIEW

**Comment by jburel** [comment]
@aleksandra-tarkowska: travis restarted

**Comment by pwalczysko** [comment]
One more ToTest: Double-check that the ``Save to All`` problem is really gone (today's testing indicates it is gone on http://eel.openmicroscopy.org/merge/webclient/?show=dataset-2401 user-1 as well as on the leica-original 56 strong MIF - all tests passed there).

**Comment by pwalczysko** [comment]
The admin form is okay on cowfish and eel.

**Comment by pwalczysko** [comment]
``Save to All`` works in both servers and in all situations.

**Comment by pwalczysko** [comment]
Annotations in right-hand pane as expected
  - cowfish
  - eel
  - single selection
  - mulitselection

**Comment by pwalczysko** [comment]
All works except the ``Secret key`` part - to be discussed betw. @aleksandra-tarkowska and @joshmoore

**Comment by aleksandra-tarkowska** [comment]
as discussed with @joshmoore secret key will go to web plugin. This will happen in a separate PR to not block these changes

**Comment by pwalczysko** [comment]
Experimenter fields in the right order:
  - eel okay
  - cowfish okay

Annotations forms single and multiselection:
  - eel okay
  - cowfish okay

Ready to merge.

**Pull request merged**
