### PR TITLE
make search GET only

### PR DESCRIPTION
**Pull request by atarkowska**
Partial rebase of https://github.com/openmicroscopy/openmicroscopy/pull/4900 (one commit only as this commit was removed from https://github.com/openmicroscopy/openmicroscopy/pull/4923)

---

# What this PR does

This PR make general search GET only

--exclude (breaking robot tests)

### CODE REVIEW

**Comment by joshmoore** [comment]
@aleksandra-tarkowska : what do you think the status of this is?

**Comment by joshmoore** [comment]
@will-moore : is this something you would consider taking over? I think the overall goal is to make searches cacheable in case there's another way to approach that.

**Comment by will-moore** [comment]
@joshmoore, sure - I'll have a look at it...

**Comment by will-moore** [comment]
@joshmoore Want to close this PR now?

**Comment by jburel** [comment]
Replaced by https://github.com/openmicroscopy/openmicroscopy/pull/5338

**Pull request closed without merging**
