### PR TITLE
Serverside omero client properties

### PR DESCRIPTION
**Pull request by dominikl**
~~Adds a ConfigService to the Registry through which server side stored omero client properties can be requested.~~ Loads the server side omero client properties into the Registry. As first example the name for the orphaned images folder is taken from the server side omero client properties

( Note: Also removes some unused code from DataServiceFactory )

Test:
Change the name of the orphaned images folder with `./omero config set omero.client.ui.tree.orphans.name "foo"` restart server and client, make sure the modified name is shown in the client (cross check with Web).

--no-rebase

### CODE REVIEW

**Comment by joshmoore** [comment]
@dominikl : worth a chat on this?

**Comment by jburel** [comment]
sorry forgot about that PR. @dominikl

**Comment by dominikl** [comment]
Shall we have a call about this?

**Comment by jburel** [comment]
@dominikl: will tomorrow work for you?

**Comment by dominikl** [comment]
@jburel Sure, anytime tomorrow.

**Comment by dominikl** [comment]
If this is a reasonable way to retrieve the properties from the server, the 'on hold' label could be removed. Any objections?

**Comment by dominikl** [comment]
Because there was a merge conflict with #3506 , it would be good to check again, that connecting via Session ID still works.

**Comment by jburel** [comment]
It works:
 2 things
 * are you going to add other properties e.g members, owners for users display
 * we no longer have ref to Service in the gateway. in theory we should be able to connect to other services. It might be easier to load the "config" map when we first create the session.

**Comment by dominikl** [comment]
@jburel Ok, I'll overhaul this, so that the whole config map is loaded when the session is initialized.
Other properties: Is there a trello card about this (which properties exists, are supported/should be supported in the clients, etc.)?

**Comment by jburel** [comment]
@dominikl see https://trello.com/c/llOSq41B/180-common-settings-on-the-serverside

**Comment by joshmoore** [comment]
NB: @aleksandra-tarkowska also recently mentioned needing to load several properties at once. If `IConfig.getConfigValues(String prefix)` would substantially help, we could investigate.

**Comment by dominikl** [comment]
@joshmoore Yes, a method like this is definitely needed, because I can't see another way, how I should get all properties at once. I have no idea how the `ome.logic.ConfigImpl` gets the data from database and/or properties file, so probably can't make this before the 'feature freeze' tomorrow.

**Comment by joshmoore** [comment]
I'll try to look into this for tomorrow morning.

**Comment by joshmoore** [comment]
See gh-3576

**Comment by dominikl** [comment]
If I don't use a ConfigService wrapper for IConfigPrx I can't make the properties lookup via the Registry, because the Agent Registries are already initialized at the startup, but I can only load the properties after the user has logged in (session has been created). So where to put the properties (and look them up from), directly to the Container? @jburel

**Comment by jburel** [comment]
you could still use the container registry
i.e. ```registry.bind(config_string, map)``` then link to agents registry in the ```DataserviceFactory```

**Comment by dominikl** [comment]
--depends-on #3576

**Comment by joshmoore** [comment]
Sorry, @dominikl : you'll need to cherry-pick https://github.com/joshmoore/openmicroscopy/commit/a6101e74a54c30e8852a435d0c6b3122626f642f to make travis happy.

**Comment by aleksandra-tarkowska** [comment]
works as expected omero insightscreensnapz003

**Comment by jburel** [comment]
@aleksandra-tarkowska: could you also test with no property set up? This led to a NPE reported by @chris-allan

**Comment by dominikl** [comment]
Would be good if this could be merged, then I could start to tackle other tickets which need this functionality. Or is the merge postponed due to code/feature freeze for 5.1.0?

**Comment by joshmoore** [comment]
I'm not sure about the NPE status from @jburel, but otherwise, no objections from me.

**Comment by jburel** [comment]
Merging. @dominikl when adding support for other properties, add a ```if null``` check

**Pull request merged**
