### PR TITLE
getThumbnails_test

### PR DESCRIPTION
**Pull request by will-moore**
# What this PR does

Adds a test based on testing of https://github.com/openmicroscopy/openmicroscopy/pull/5207

As seen in webclient and reproduced in Python, after 'Save to All' getting thumbnail set WITH
```omero.group: -1``` fails until we get a thumbnail set WITHOUT ```omero.group: -1``` 

Test reproduces this but uses ```with pytest.raises(omero.SecurityViolation):``` to wrap the failing line.
Should be removed when the bug is fixed.

# Testing this PR

1. Test should be green.

cc @mtbc

### CODE REVIEW

**Comment by mtbc** [comment]
https://ci.openmicroscopy.org/job/OMERO-DEV-merge-integration-python/lastCompletedBuild/testReport/OmeroPy.test.integration.test_thumbnailPerms/TestThumbnailPerms/testGetThumbnailSetAfterApplySettings/

(currently "Failed: DID NOT RAISE")

**Comment by aleksandra-tarkowska** [comment]
--exclude (until Will is back)

**Comment by will-moore** [comment]
@aleksandra-tarkowska Fixed test. Should be able to include this now, thanks.

**Comment by jburel** [comment]
Removed the exclude flag

**Comment by mtbc** [comment]
... and it's now passing. :+1:

**Comment by mtbc** [comment]
--exclude for testing of #5249, #5250.

**Comment by mtbc** [comment]
Want to try adding an integration test to reproduce issue at https://github.com/openmicroscopy/openmicroscopy/pull/5207#issuecomment-295653183 ?

**Comment by will-moore** [comment]
@mtbc As far as I can see, getThumbnailSet() was failing after 'save to all' but the test I wrote for that is now passing. I'm not sure how to reproduce the latest failures, except maybe to simply add a large number of images to that same test? But if it's failing because "you can't getThumbnailSet() while thumbnails are being re-created", then we don't have a fix for that, right? So this would likely stay as a failing test which might not be very useful?
Also I could try add a failing test for shares if that would help fix the issue?

**Comment by mtbc** [comment]
Yeah, doesn't sound like it's worth it at this time, does it? Thank you for your thoughts! If there aren't any *regressions* with shares then I think we're probably good unless IDR depends on them. At least, I'm unlikely in the near future to get to investigating handling in-progress thumbnails!

**Pull request merged**
