### PR TITLE
Inplace import

### PR DESCRIPTION
**Pull request by jburel**
# What this PR does

* Remove -- when not needed
* Update QA URL

Noticed during the preparation of the workshop
See
http://docs.openmicroscopy.org/omero/5.4.6/sysadmins/in-place-import.html#inplace-import

### CODE REVIEW

**Comment by rleigh-codelibre** [comment]
These changes all look fine.  Was the dropping of `https` for `http` intentional?

**Comment by jburel** [comment]
it is intentional it is not https for qa

**Comment by joshmoore** [comment]
I think the intent here was to show using a non-default server. It may be better to go so far as to use `qa.example.com`.

**Comment by jburel** [comment]
Thanks I will update that accordingly

**Review by joshmoore — APPROVED** [review]

**Pull request merged**
