### PR TITLE
Disappearing scrollbar

### PR DESCRIPTION
**Pull request by dominikl**
Fixes the issue, that the scrollbar disappeared when the width of the left hand side pane was changed.

### CODE REVIEW

**Comment by mtbc** [comment]
Code change looks plausible, I'll give this a try on Linux and Windows tomorrow.

**Comment by pwalczysko** [comment]
The scrollbar does not dsappear anymore (at least I could not repeat this). But, testing with Insight on Mac, connected to eel with this PR  in, I have the scrollbar not fully in action down to the bottom of an expanded tree.

Workflow:
   - connect to eel as member-all-1
   - put read-annotate-1 group on display, all the data but do not display users (will give a lot of P/Ds in the tree)
   - expand couple of Projects with images 
   - expand the orphaned datasets on the bottom of the tree
   - the scrollbar is still present, but yoiu cannot scroll down enough, so that the bottom expanded datasets come into appearance -> compare screenshots (5.1.1 release insight on the same data can scroll down so that you can see the Orphaned Dataset, the insight from the eel build with this PR cannot scroll down enough)

Insight from the build with this PR

screen shot 2015-05-26 at 19 38 32


Insight from the 5.1.1 release on the same data

screen shot 2015-05-26 at 19 38 24

**Comment by joshmoore** [comment]
I went through @pwalczysko's workflow as well:

 * rc1 -- no scrollbar
 * with this PR -- scrollbar up until some predefined wall
 * with gh-3849 (rolling back `file-name`) -- scrollbar restored.

@jburel & @dominikl : leave the choice up to you guys. But either this PR (or a copy of it) will need more commits and 3849 should be closed, or this should be closed and 3849 will roll back gh-3770 for the merge build tomorrow.

**Comment by jburel** [comment]
closing. replaced by https://github.com/openmicroscopy/openmicroscopy/pull/3850

**Comment by dominikl** [comment]
Thanks @jburel . Couldn't test the PR in the build yesterday, just can't connect to VPN properly from home, have to sort this out at some point.

**Pull request closed without merging**
