### PR TITLE
show roi

### PR DESCRIPTION
**Pull request by will-moore**
# What this PR does

Supports ```webclient/?show=roi-123```.

See https://trello.com/c/Ph6glKiK/599-rfe-url-to-specific-roi
(from https://www.openmicroscopy.org/community/viewtopic.php?f=4&t=8672).

# Testing this PR:

1. Choose and ROI ID and go to ```webclient/show=roi-ID```, which should load the correct image in the webclient.
1. show test should pass

### CODE REVIEW

**Comment by jburel** [comment]
Are you still planning to add tests?

**Comment by mtbc** [comment]
Passing tests at https://ci.openmicroscopy.org/job/OMERO-DEV-merge-integration-Python27/lastCompletedBuild/testReport/OmeroWeb.test.integration.test_show/TestShow/ and https://web-proxy.openmicroscopy.org/west-ci/job/OMERO-test-integration/lastCompletedBuild/testReport/OmeroWeb.test.integration.test_show/TestShow/.

**Review by mtbc — APPROVED** [review]
> and go to `webclient/show=roi-ID`

Needed a "?" in there but once I added that this worked fine.

**Comment by kouichi-c-nakamura** [comment]
Super cool! Thanks guys!!!

**Pull request merged**
