### PR TITLE
Rf center right panel

### PR DESCRIPTION
**Pull request by bramalingam**
These tests should check at a basic level, the synchronisation between the Tree,Centre and Right panels.

@will-moore @aleksandra-tarkowska

### CODE REVIEW

**Comment by joshmoore** [comment]
Next steps here?

**Comment by jburel** [comment]
Discussed with @bramalingam, no more tests to be pushed before code freeze.
Few more tests will be added later on.
robots tests have been stable for few days. Today's failure not related to this PR

**Comment by joshmoore** [comment]
:thumbsup:

**Comment by jburel** [comment]
https://ci.openmicroscopy.org/view/OMERO-DEV/job/OMERO-DEV-merge-robotframework/ is green

**Pull request merged**
