### PR TITLE
merge latest from develop into roles branch

### PR DESCRIPTION
**Pull request by mtbc**
# What this PR does

Brings latest commits from the develop branch into the roles devspace.

# Testing this PR

Travis should start passing again.

### CODE REVIEW

**Comment by pwalczysko** [comment]
Test results on integration were not worsened by this PR. Compare https://10.0.51.154:8443/job/OMERO-test-integration/17/testReport/ and https://10.0.51.154:8443/job/OMERO-test-integration/15/testReport/

**Comment by pwalczysko** [comment]
All the commits listed here were already merged to develop.

**Comment by pwalczysko** [comment]
Ready to merge.

**Comment by mtbc** [comment]
Would be lovely to get #5242 in before this is merged. *Update:* It's now in.

**Pull request merged**
