### PR TITLE
introduce 5.2 database upgrade scripts

### PR DESCRIPTION
**Pull request by mtbc**
Introduces the SQL upgrade scripts from `OMERO5.1__1` to `OMERO 5.2DEV__0`, removes the old DEV scripts, bumps the PostgreSQL requirement up to 9.3, and fixes the typo mentioned in https://github.com/openmicroscopy/openmicroscopy/pull/4201#issuecomment-143173167.

--no-rebase

### CODE REVIEW

**Comment by joshmoore** [comment]
Otherwise, all makes sense.

**Comment by mtbc** [comment]
Gah, I probably did something dumb in the cherry-picking and rebasing and whatnot. Want me to try to unpick it and improve the commit history?

**Comment by mtbc** [comment]
This should be the same but with improved commit history.

**Comment by sbesson** [comment]
Tested the minimum requirements on a PSQL 9.2 server

```
[hudson-x@ome-c6100-2 OMERO.server-5.2.0-m1-48-4c743a6-ice35-b503]$ bin/omero db script
Using OMERO5.2DEV for version
Using 0 for patch
Please enter password for OMERO root user: 
Please re-enter password for OMERO root user: 
Saving to /homes/hudson-x/OMERO.server-5.2.0-m1-48-4c743a6-ice35-b503/OMERO5.2DEV__0.sql
[hudson-x@ome-c6100-2 OMERO.server-5.2.0-m1-48-4c743a6-ice35-b503]$ createdb -O omero test
[hudson-x@ome-c6100-2 OMERO.server-5.2.0-m1-48-4c743a6-ice35-b503]$ psql -U omero test -f OMERO5.2DEV__0.sql 
BEGIN
CREATE FUNCTION
CREATE FUNCTION
psql:OMERO5.2DEV__0.sql:56: ERROR:  PostgreSQL database server version 9.2.13 is less than OMERO prerequisite 9.3.0
psql:OMERO5.2DEV__0.sql:58: ERROR:  current transaction is aborted, commands ignored until end of transaction block
````

The typo fix in the sql script looks sensible although I do not have the bandwidth to figure out the test case allowing to reproduce the upgrade failure. Overall, this PR should be ready to move out of `breaking` assuming we are happy with the new requirements.

**Comment by mtbc** [comment]
Latest PostgreSQL is easily available via instructions at http://www.postgresql.org/download/ for many platforms so shouldn't be too onerous. Note that eel still has 9.2 but the PostgreSQL Yum Repository offers later.

**Comment by sbesson** [comment]
PG 9.3 installed on `octopus/eel`. Removing breaking label

**Comment by joshmoore** [comment]
Changes look good. Two heads up:

 * there's no `OMERO-DEV-merge-upgrade` job at the moment. i.e. this was only tested on `breaking` cc: @sbesson
 * [a next change](https://trello.com/c/EwmJfe5u/68-critical-indexing-large-annotation-changes) is looming so :+1: for this being still a DEV version. cc: @jburel re: db freeze

**Comment by sbesson** [comment]
See https://ci.openmicroscopy.org/job/OMERO-DEV-merge-upgrade/7/

**Comment by joshmoore** [comment]
:thumbsup:

**Pull request merged**
