### PR TITLE
Do not fail admin diagnostics subcommand if the server has never been started

### PR DESCRIPTION
**Pull request by sbesson**
See https://trac.openmicroscopy.org/ome/ticket/13061

This commit addresses the special case where a fresh server is downloaded and `bin/omero admin diagnostics` is called before the server is started (or minimally before the `templates.xml` file is generated for the first time).
With this change, the command should return and the memory section should simply be skipped if there is no `templates.xml` file to be parsed.

### CODE REVIEW

**Comment by ximenesuk** [comment]
Before starting a new server:
```
$ omero admin diagnostics

================================================================================
OMERO Diagnostics 5.2.0-m2-ice35-SNAPSHOT
================================================================================
...
Log dir:    /Users/colin/Work/repos/openmicroscopy/dist/var/log n/a


Error while parsing logs
...
Cannot list deployed applications.
OMERO data dir:'/OMERO'                       Exists? False	Is writable? False
OMERO temp dir:'/Users/colin/omero/tmp'       Exists? True	Is writable? True   (Size: 30550)
...
```
...a running server...
```
$ omero admin diagnostics

================================================================================
OMERO Diagnostics 5.2.0-m2-ice35-SNAPSHOT
================================================================================
...
Log dir:    /Users/colin/Work/repos/openmicroscopy/dist/var/log exists
...
OMERO SSL port:4064
OMERO TCP port:4063
OMERO data dir:'/Users/colin/var/omero/'      Exists? True	Is writable? True
OMERO temp dir:'/Users/colin/omero/tmp'       Exists? True	Is writable? True   (Size: 62383)

JVM settings: Blitz-${index}                -Xmx2576m -XX:MaxPermSize=1g -XX:+IgnoreUnrecognizedVMOptions
JVM settings: Indexer-${index}              -Xmx1717m -XX:MaxPermSize=1g -XX:+IgnoreUnrecognizedVMOptions
JVM settings: PixelData-${index}            -Xmx2576m -XX:MaxPermSize=1g -XX:+IgnoreUnrecognizedVMOptions
JVM settings: Repository-${index}           -Xmx1717m -XX:MaxPermSize=1g -XX:+IgnoreUnrecognizedVMOptions
...
```
a stopped server
```
$ omero admin diagnostics

================================================================================
OMERO Diagnostics 5.2.0-m2-ice35-SNAPSHOT
================================================================================
...
Log dir:    /Users/colin/Work/repos/openmicroscopy/dist/var/log exists
...
Cannot list deployed applications.
OMERO data dir:'/Users/colin/var/omero/'      Exists? True	Is writable? True
OMERO temp dir:'/Users/colin/omero/tmp'       Exists? True	Is writable? True   (Size: 30550)

JVM settings: Blitz-${index}                -Xmx2576m -XX:MaxPermSize=1g -XX:+IgnoreUnrecognizedVMOptions
JVM settings: Indexer-${index}              -Xmx1717m -XX:MaxPermSize=1g -XX:+IgnoreUnrecognizedVMOptions
JVM settings: PixelData-${index}            -Xmx2576m -XX:MaxPermSize=1g -XX:+IgnoreUnrecognizedVMOptions
JVM settings: Repository-${index}           -Xmx1717m -XX:MaxPermSize=1g -XX:+IgnoreUnrecognizedVMOptions
...
```

**Comment by ximenesuk** [comment]
Although not part of this PR, maybe:
```
Log dir:    /Users/colin/Work/repos/openmicroscopy/dist/var/log n/a


Error while parsing logs
...
```
could also be improved for a fresh server, ie something like 'no logs available' if the dir is not there?

**Comment by sbesson** [comment]
@ximenesuk: I can push an additional commit to handle non-existing log files

**Comment by joshmoore** [comment]
i.e. "merge"?

**Comment by ximenesuk** [comment]
```
$ omero admin diagnostics

================================================================================
OMERO Diagnostics 5.2.0-m2-ice35-SNAPSHOT
================================================================================
...
Log dir:    /Users/colin/Work/repos/openmicroscopy/dist/var/log
No logs available
...
```

Good to merge.

**Pull request merged**
