### PR TITLE
add a description template for pull requests

### PR DESCRIPTION
**Pull request by mtbc**
See https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/ -- perhaps this is a useful start for people to help them remember what to include in their pull request descriptions.

### CODE REVIEW

**Comment by ximenesuk** [comment]
This will mean no more empty PR description so will that bit of scc need to handle unedited PR descriptions? /cc @sbesson

**Comment by ximenesuk** [comment]
This seems like a good idea. Maybe there are some PRs where addressing every point may not make sense? So how strict would any support policy be or is this simply intended as a reminder to provide as much information as is useful? So would there be some supporting docs if this was merged? (And if so can we add something about descriptive PR names!?)

**Comment by mtbc** [comment]
Intended as a reminder, parts to be deleted as seems reasonable. Good idea about PR names too!

**Comment by ximenesuk** [comment]
I'm happy with the idea and the text as it stands. Maybe it is worth adding a small supporting doc at https://www.openmicroscopy.org/site/support/contributing/using-git.html#pull-requests ? But good to merge from me.

**Comment by sbesson** [comment]
Merging and we can review the template in follow-up PRs.

**Pull request merged**
