### PR TITLE
Shape attributes cleanup

### PR DESCRIPTION
**Pull request by sbesson**
See https://trello.com/c/LW8l7U8x/20-shape-attribute-renaming-cleanup

Following the [Shape property renaming](https://github.com/openmicroscopy/openmicroscopy/pull/4481), this PR reviews the usages of `cx,` `cy`, `rx` and `ry` variables in the server components and fixes one of the MATLAB functions to use the new methods.

To test this PR, check the changes make sense and there are no more occurences of `[cC][xy]` and `[rR][xy]` in the modified components.

### CODE REVIEW

**Comment by mtbc** [comment]
Thank you for handling this.

**Comment by dgault** [comment]
Renames all look good and I can find no further references to [cC][xy] or [rR][xy]

**Comment by sbesson** [comment]
Barring any last minute comment from @mtbc, I propose to get this merged and start cleaning/reviewing the other components.

**Comment by mtbc** [comment]
No blockers from me!

**Pull request merged**
