### PR TITLE
Omero reader update : Open OMERO ROIs in ImageJ

### PR DESCRIPTION
**Pull request by bramalingam**
To Test:

1) Open Insight : Add roi's to an existing OMERO image and save (All kinds of ROI's).
2) Now close Insight, and download/setup the Insight-IJ plugin, open the same OMERO image on ImageJ using this plugin.
3) Please check the "Display ROIs","Display OME-XML metadata" and "Display Metadata" checkbox's in the Bio-Formats Import options and press OK.
4) This should now open the IMAGE from OMERO in ImageJ. And the ROI's should be loaded onto the ImageJ ROI Manager.

NOTE: The label text ROI's will be displayed in the metadata, but the support for displaying the same in the ImageJ ROIManager will be done via a separate PR.

### CODE REVIEW

**Comment by pwalczysko** [comment]
This works as expected on single plane images. The text region is also okay.

**Comment by pwalczysko** [comment]
I think that the PR is okay as it does what it set out to do well.

Nevertheless, we have to think about the multi-z cases as well. Atm we have the propagated regions over z in OMERO displayed in ImageJ as multiple identical regious in the ROI manager, which have no real bearing to the particular z plane (in fact, none of the region, propagated or not does have any bearing to the particular z-plane). Is that what we want/have to accept ?

Otherwise ready to merge.

**Comment by jburel** [comment]
Need to add support for shape settings i.e. filcolor, stroke width etc.

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#713](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/713/). See the [console output](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/713/consoleText) for more details.
Possible conflicts:
  - PR #3329 jburel 'Imagej prep'
    - components/insight/SRC/org/openmicroscopy/shoola/env/ui/TaskBarManager.java

**Comment by jburel** [comment]
@bramalingam:
could you roll back your change? i.e.
```
 ImagePlus imp = IJ.getImage();
 imp.setTitle(imp.getTitle() + "--" + "omero::iid:" + id);
  IJ.log("Success" + id);
````
No need to modify the taskManager in this PR.

**Comment by bramalingam** [comment]
Yes was going to push a commit with that.

**Comment by jburel** [comment]
@bramalingam: would have been better to rewrite https://github.com/bramalingam/openmicroscopy/commit/c400ca3cb59872d7248680ae2a0aa967083d09a3

**Comment by bramalingam** [comment]
@jburel : I have checked out the TaskBarManager.java from origin/develop, so there should be no conflicts with your PR now. Would that work?

**Comment by pwalczysko** [comment]
This works as expected, except that the Properties are preserved (see excerpt from the Metadata below) but are not displayed in ImageJ (see screenshot). The text ROI works fine as well, font size preserved.

```
<ROI ID="ROI:4:0" xmlns="http://www.openmicroscopy.org/Schemas/ROI/2013-10-dev-5">
<Union>
<Shape FillColor="1073741824" ID="Shape:4:0" StrokeColor="-993737532" StrokeWidth="1.0" StrokeWidthUnit="pixel">
<Polygon Points="65,363 118,219 79,390"/>
<ROI ID="ROI:5:0" xmlns="http://www.openmicroscopy.org/Schemas/ROI/2013-10-dev-5">
<Union>
<Shape FillColor="1090453504" FontSize="20.0" FontSizeUnit="pixel" ID="Shape:5:0" StrokeColor="-1006632705" StrokeWidth="50.0" StrokeWidthUnit="pixel" Text="ggg">
<Label X="454.0" Y="457.0"/>
```
The ROIs do not have the proper line color, although it is preserved in the properties in the metadata (see excerpt above) - the lines of ROIs are uniform width and uniform color (white):

screen shot 2015-01-23 at 15 22 52

**Comment by bramalingam** [comment]
The display is happening via the Bioformats ROIHandler, and will need updating to 'display' the shape properties. If @jburel  agrees That can happen via a separate PR?

**Comment by bramalingam** [comment]
The shape display properties have been dealt with in this PR,
https://github.com/openmicroscopy/bioformats/pull/1526

**Comment by jburel** [comment]
Instead of having your own query you should use the existing queries from IAdmin
 * If the group name is specified, use ```lookupGroup```
 * and use the getMemberof method

**Comment by bramalingam** [comment]
@jburel : I've tried to address the issue, in the above commit. Please check and let me know if it looks fine.

**Comment by jburel** [comment]
@bramalingam;
```
ParametersI p = new ParametersI();
+                    p.addId(eventContext.userId);
+                    List<IObject> groupList = iQuery.findAllByQuery(
+                            "select distinct g from ExperimenterGroup as g " +
+                                    "join fetch g.groupExperimenterMap as map " +
+                                    "join fetch map.parent e " +
+                                    "left outer join fetch map.child u " +
+                                    "left outer join fetch u.groupExperimenterMap m2 " +
+                                    "left outer join fetch m2.parent p " +
+                                    "where g.id in " +
+                                    "  (select m.parent from GroupExperimenterMap m " +
+                                    "  where m.child.id = :id )", p);
+
+                    Iterator<IObject> i = groupList.iterator();
```
That's the code I was mentioning. That could be replaced by existing method

**Comment by bramalingam** [comment]
The above commit should fix @jburel 's comment.

**Comment by jburel** [comment]
@bramalingam: 
 * could you add javadoc above new methods?
* Check the color, only lines were visible.

**Comment by jburel** [comment]
Let's merge this PR, we will need a review to be sure the same things happening in the various places where we convert rois

**Comment by jburel** [comment]
--no-rebase

**Pull request merged**
