### PR TITLE
Mapannotation search fixes

### PR DESCRIPTION
**Pull request by dominikl**
Fixes the blockers discovered in todays testing session, see [GDoc](https://docs.google.com/spreadsheets/d/1nPQbPov8dwIlHswGey0K779JirYsjdEg2CKK5khtI9w/edit#gid=1171413927)

Test:
- Search for a MapAnnotation key or value, when the checkbox "Annotation" is ticked (before: no results)
- Enter an invalid expression, e. g. a term with two colons asdf:123:asdf. You should see a message dialog, saying that the search expression is invalid (before: default crash/error dialog popped up)
- Enter something in the search field in the main toolbar, hit enter. The search panel on the left should open and show the same what you've entered in the main toolbar without a trailing space.
- Annotate a plate run and then search for it (before: plate runs were ignored)
- Check that the number of search results found, is shown (beneath the search button, after search has finished)

/cc @pwalczysko 

--no-rebase

### CODE REVIEW

**Comment by dominikl** [comment]
With respect to "Search result count": After talking to @pwalczysko , I'm going to implement the same like Web #3548 , display the number of displayed results. This result lists is limited to a max number, and there isn't a way to retrieve results past this threshold anyway in Insight.

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#811](https://ci.openmicroscopy.org/job/OME-5.1-merge-push/811/). See the [console output](https://ci.openmicroscopy.org/job/OME-5.1-merge-push/811/consoleText) for more details.
Possible conflicts:
  - PR #3536 snoopycrimecop 'Update develop submodules'
    - docs/sphinx
    - components/bioformats

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#812](https://ci.openmicroscopy.org/job/OME-5.1-merge-push/812/). See the [console output](https://ci.openmicroscopy.org/job/OME-5.1-merge-push/812/consoleText) for more details.
Possible conflicts:
  - PR #3536 snoopycrimecop 'Update develop submodules'
    - docs/sphinx
    - components/bioformats

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#813](https://ci.openmicroscopy.org/job/OME-5.1-merge-push/813/). See the [console output](https://ci.openmicroscopy.org/job/OME-5.1-merge-push/813/consoleText) for more details.
Possible conflicts:
  - PR #3536 snoopycrimecop 'Update develop submodules'
    - docs/sphinx
    - components/bioformats

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#814](https://ci.openmicroscopy.org/job/OME-5.1-merge-push/814/). See the [console output](https://ci.openmicroscopy.org/job/OME-5.1-merge-push/814/consoleText) for more details.
Possible conflicts:
  - PR #3536 snoopycrimecop 'Update develop submodules'
    - docs/sphinx
    - components/bioformats

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#815](https://ci.openmicroscopy.org/job/OME-5.1-merge-push/815/). See the [console output](https://ci.openmicroscopy.org/job/OME-5.1-merge-push/815/consoleText) for more details.
Possible conflicts:
  - PR #3536 snoopycrimecop 'Update develop submodules'
    - docs/sphinx
    - components/bioformats

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#816](https://ci.openmicroscopy.org/job/OME-5.1-merge-push/816/). See the [console output](https://ci.openmicroscopy.org/job/OME-5.1-merge-push/816/consoleText) for more details.
Possible conflicts:
  - PR #3536 snoopycrimecop 'Update develop submodules'
    - docs/sphinx
    - components/bioformats

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#818](https://ci.openmicroscopy.org/job/OME-5.1-merge-push/818/). See the [console output](https://ci.openmicroscopy.org/job/OME-5.1-merge-push/818/consoleText) for more details.
Possible conflicts:
  - PR #3536 snoopycrimecop 'Update develop submodules'
    - docs/sphinx
    - components/bioformats

**Comment by dominikl** [comment]
@will-moore With 4843952 PlateAcquisitions will be included in the search index, but I don't know if OMERO.web also needs to modified to search it. Insight now performs a search for Plate and PlateAcquisition if one ticks the 'Plates' checkbox.

**Comment by joshmoore** [comment]
@dominikl @jburel @will-moore @pwalczysko : an alternative to what @dominikl has done here which may be worth discussing is to have the run metadata attached to the plate. I don't know about the workflow to tell. If we intend to eventually have a plate checkbox, then we can leave it as it is, since the data will be in the index when it comes time to add the tickbox. If we *don't* intend to have a run checkbox, then likely we just want the information on the plate itself.

**Comment by pwalczysko** [comment]
@joshmoore in the client, the Plate Run is displayed as completely, separately annotable object. It can have completely different Tags, Files, MAnnot etc. attached to it from its mother plate. The plate in its own right can have yet another set of annotations. I do not see how to "attach the annotations to the plate" - this would amount to a (big ?) rehaul of the GUIs - do not show the Run as separately annotable, with a kick-on effects on the tag tabs etc. ?? Scary.

**Comment by pwalczysko** [comment]
Note that in the UI the Plate Acquisition term is "forbidden" and replaced by the Plate Run :)

**Comment by joshmoore** [comment]
Note: Is there a proposal on the table to rename in the code? :)

**Comment by joshmoore** [comment]
> The plate in its own right can have yet another set of annotations. I do not see how to "attach the annotations to the plate" - this would amount to a (big ?) rehaul of the GUIs - do not show the Run as separately annotable, with a kick-on effects on the tag tabs etc. ?? Scary.

Ok. Then I consider what @dominikl has done correct but will leave the RFE of making this explicit in UI to someone else.

**Comment by pwalczysko** [comment]
Note: Is there a proposal on the table to rename in the code? :)

(just in case this wasn't a joke) - No - no intention either -> the code operates still with Experimenters, ExperimenterGroups and other names which are long since  banned in UIs. I think there would be a (big) problem if we would stir this ? No need for this in my opinion.

**Comment by pwalczysko** [comment]
The problem with the space is solved.

**Comment by pwalczysko** [comment]
Some issues with indexing on trout merge.
@joshmoore @sbesson . will continue possibly tomorrow.

**Comment by dominikl** [comment]
@will-moore In Insight's OMEROGateway I added this line, which means if the user has included Plates in the DataObjects to search for PlateAcquisitions are automatically added. https://github.com/openmicroscopy/openmicroscopy/pull/3547/files#diff-39fd5dd1b2b6b032a9ffa13ca0855240R5061
I guess you'll need something similar in web, too.

**Comment by pwalczysko** [comment]
@dominikl For the results count number in Insight:: Is there a reason to have the number and text so very light grey ? I think it might be in normal black font like the other texts (this is not an intermittent message like the ``Search`` text next to the spinning wheel).
Also, could you please set it a bit off from the left border of the UI ? It would help with visibility.

**Comment by pwalczysko** [comment]
Except the RFE https://github.com/openmicroscopy/openmicroscopy/pull/3547#issuecomment-77559100 all works as expected here when tested in Insight.

**Comment by pwalczysko** [comment]
@will-moore  
In Web: The ``tick the Annotate box and get the results as well`` works fine. 
What does not work is
  - search for ``::`` gives still an error  (not a nice warning)
  - Plate Runs are ignored
  - the number of search results are not shown

**Comment by pwalczysko** [comment]
In total, although there are still some issues in Web, the workflow seems fine. This PR works 100% for Insight. I guess the web problems have to be sorted in special web-PRs.

Ready to merge.

**Comment by will-moore** [comment]
Search result count PR was temporarily conflicting - should be fixed now https://github.com/openmicroscopy/openmicroscopy/pull/3548

**Comment by joshmoore** [comment]
:thumbsup:

**Pull request merged**
