### PR TITLE
Javadoc cleanup: romio and rendering

### PR DESCRIPTION
**Pull request by sbesson**
As part of the build system cleanup, this PR reviews the Javadoc warnings for the `rendering` and `romio` components of the server. 

To test this PR, check no more warning is reported for either component when running `./build.py build-default`.

### CODE REVIEW

**Comment by jburel** [comment]
In ```PlanePoint```
```
public PlanePoint vec(double x1, double x2) {
        return new PlanePoint(x1 - this.x1, x2 - this.x2);
    }
``` 
missing parameters description in doc i.e. 
```
@param x1 ...
@param x2...
 ```

**Comment by jburel** [comment]
General: 
I will also remove 
```
// Java imports

// Third-party libraries

// Application-internal dependencies
```

**Comment by sbesson** [comment]
Pushed (unless you wanted to keep the import headers when applicable?)

**Comment by jburel** [comment]
@sbesson: no, we decided to remove them to unify code.
Thanks

**Comment by jburel** [comment]
ignore comment about "swapping"
I mis-read the lines

**Comment by sbesson** [comment]
Pushed

**Comment by jburel** [comment]
no warning when generating javadoc.Merging

**Pull request merged**
