### PR TITLE
Remove deprecated methods

### PR DESCRIPTION
**Pull request by dominikl**
# What this PR does

Removes the deprecated methods from the Gateway and their usage in Insight.

# Testing this PR

- Check integration tests.
- Perform some basic/general tasks in Insight and make sure nothing's broken.
- Check the changes in Polyline and Polygon Pojos. I'm not sure about the impact of these. Before the constructor and certain methods took three points parameters and one mask parameter, now it's just one points parameter. Has that really never been used before?

### CODE REVIEW

**Comment by mtbc** [comment]
Wonder if you want to switch base branch to `roles` instead so they disappear in a major version?

**Comment by dominikl** [comment]
Oh dear, I better close, rebase, and reopen the PR.

**Comment by mtbc** [comment]
I think "edit" to the right of the PR title suffices?

Edit: Ah, sorry, too long since I last merged mainline into it.

**Comment by dominikl** [comment]
Replaced by  #5320

**Pull request closed without merging**
