### PR TITLE
JSON table CLI output (rebased onto develop)

### PR DESCRIPTION
**Pull request by manics**
This is the same as gh-4904 but rebased onto develop.

---
# What this PR does

Adds `json` to the available tabular output styles for the CLI. Also suppresses the `Previously logged in to` CLI message in quiet mode. This means the `json` table output can be piped to other processes.
# Testing this PR

Test CLI commands that have tabular output, e.g.
- `omero hql --style json ...`
- `omero user list --style json`

Try piping the `json` output into other commands, for example `jq` (The JSON version of `sed`/xpath):
- `omero user list -q --style json`
  
  ```
  [{"admin": "Yes", "last name": "root", "email": "", "owner of": "", "first name": "root", "member of": "", "ldap": "False", "active": "Yes", "login": "root", "id": "0"},
  {"admin": "", "last name": "Account", "email": "", "owner of": "", "first name": "Guest", "member of": "2", "ldap": "False", "active": "", "login": "guest", "id": "1"},
  ...
  ```
- `omero user list --style json | jq 'map(select(.["admin"]=="Yes"))'`
  
  ```
  [
    {
      "admin": "Yes",
      "last name": "root",
      "email": "",
      "owner of": "",
      "first name": "root",
      "member of": "",
      "ldap": "False",
      "active": "Yes",
      "login": "root",
      "id": "0"
    }
  ]
  ```

Read the output directly into an Ansible variable, for example this will create the Ansible variable `omero_user_list` containing a list of dictionaries with OMERO users:

```
- name: omero user | current user list
  become: yes
  become_user: "{{ omero_user_system }}"
  command: >
    {{ omero_serverdir }}/{{ omero_server_symlink }}/bin/omero user
    -s localhost
    -u {{ omero_user_admin_user }}
    -w {{ omero_user_admin_pass }}
    list
    -q
    --style json
  register: usercmd
  always_run: yes
  changed_when: False

- set_fact:
    omero_user_list: "{{ usercmd.stdout | from_json }}"
```
# Problems
- [x] `unit/test_util.py::TestJSONSTyle.testPlainModuleParsing` fails with unicode values, but I don't know whether that's a bug in the test framework, JSON, or the `TableBuilder`.

### CODE REVIEW

**Comment by manics** [comment]
--rebased-from #4904

**Comment by will-moore** [comment]
Seems to work fine:

```
$ omero user list -q --style json | grep Ben
{"admin": "", "last name": "Nevis", "email": "newtest2@emaildomain.com", "owner of": "", "first name": "Ben", "member of": "5,4,3,3053,6,4803", "ldap": "False", "active": "Yes", "login": "ben", "id": "4"},
```

Don't know what the list of CLI commands with tabular outputs is, so didn't test with any others, but his looks good.

Good to merge.

**Comment by will-moore** [comment]
I guess we also need a Docs PR, so users know about this json option?

**Comment by manics** [comment]
Yes. However this is primarily driven by the IDR at the moment, so if people are unsure this could be closed pending a later scoping discussion.

**Comment by joshmoore** [comment]
Coming late to this, the commands involved are:

```
$ git grep add_style_argument
fs.py:        images.add_style_argument()
fs.py:        repos.add_style_argument()
fs.py:        sets.add_style_argument()
fs.py:        usage.add_style_argument()
group.py:            x.add_style_argument()
group.py:        listusers.add_style_argument()
hql.py:        parser.add_style_argument()
ldap.py:        list.add_style_argument()
user.py:            x.add_style_argument()
user.py:        listgroups.add_style_argument()
```

Another example:

```
bash-4.2$ bin/omero hql --style=json "select u from Experimenter u" -q
[{"#": "0", "omeName": "root", "firstName": "root", "lastName": "root", "Id": "0", "version": "0", "ldap": "False", "Class": "ExperimenterI"},
{"#": "1", "omeName": "guest", "firstName": "Guest", "lastName": "Account", "Id": "1", "version": "0", "ldap": "False", "Class": "ExperimenterI"}]
```

and

```
bash-4.2$ bin/omero hql --style=json "select u.firstName, u.lastName from Experimenter u" -q
[{"#": "0", "Col2": "root", "Col1": "root"},
{"#": "1", "Col2": "Account", "Col1": "Guest"}]
```

Looks nice (`Col1` etc. aren't great, but that's `hql.py`'s fault). Also :+1: for the additional `-q` fix. I don't see any reason not to merge. Worst case, we can either update the format in a breaking release, or move to `json2` etc. Please do update any related docs.

**Pull request merged**
