### PR TITLE
Dropbox permissions on Linux

### PR DESCRIPTION
**Pull request by ximenesuk**
This PR attempts to fix the problem reported in https://www.openmicroscopy.org/community/viewtopic.php?f=4&t=7814

Creating a DropBox user directory with permissions that don't allow omero to read it should not cause DropBox to fail. Changing the permissions later should cause the directory to be watched. More specifically:
```
mkdir -m 300 /path/to/omero.data.dir/DropBox/username
```
should log an error in `MonitorServer.log` indicating that the directory isn't being watched. Then:
```
chmod 770 /path/to/omero.data.dir/DropBox/username
```
should log that the directory is now being watched.

--no-rebase

### CODE REVIEW

**Comment by dominikl** [comment]
Works like expected. Good to merge.

**Comment by ximenesuk** [comment]
I've found another bug here, unfortunately.

**Comment by joshmoore** [comment]
With today's merge build (and using https://github.com/ome/ome-docker/pull/9) I can definitely see:

```
2015-05-26 03:34:41,421 ERROR [             fsserver.fsPyinotifyMonitor] (Thread-4  ) Unable to add watch on: /OMERO/DropBox/root : add_watch: cannot watch /OMERO/DropBox/root WD=-1 Errno=Permission denied (EACCES)
```

It would be good to discuss what all error conditions are currently handled with https://github.com/ximenesuk/openmicroscopy/commit/39f9d12594f866f206917f2bbf5fd4149808ff23. Testing itself should be quite straight-forward.

**Comment by dominikl** [comment]
Reviewed the PR yesterday, worked for one level of hierarchy but not if a subdirectory was lacking access permissions. I'll retest it today asap.

**Comment by dominikl** [comment]
Maybe someone else should review this. Can't get Dropbox working, but might be related to my setup.
When starting up the server Dropbox.log says:
```
2015-05-26 07:03:06,454 INFO  [                             omero.utils] (MainThread) Failed to get session on attempt 5
2015-05-26 07:03:09,509 WARNI [                             omero.utils] (MainThread) Reason: exception ::Ice::NoEndpointException
{
    proxy = BlitzManager -t -e 1.1 @ BlitzAdapters
}
2015-05-26 07:03:09,518 ERROR [                        fsclient.DropBox] (MainThread) Failed to get Session: 
Traceback (most recent call last):
  File "lib/python/fsDropBox.py", line 92, in run
    retries=self.maxRetries, interval=self.retryInterval)
  File "/home/omero/OMERO.server-5.1.1-508-1b63290-ice35-b515/lib/python/omero/util/__init__.py", line 218, in internal_service_factory
    raise excpt
NoEndpointException: exception ::Ice::NoEndpointException
{
    proxy = BlitzManager -t -e 1.1 @ BlitzAdapters
}
2015-05-26 07:03:09,566 ERROR [                        fsclient.DropBox] (MainThread) Quitting
2015-05-26 07:03:10,215 INFO  [                        fsclient.DropBox] (MainThread) Exiting with exit code: -1
```
And MonitorServer.log only gives me:
```
2015-05-26 07:01:35,372 INFO  [                  fsserver.MonitorServer] (MainThread) Started OMERO.fs MonitorServer
```

**Comment by joshmoore** [comment]
**Major caveat:** changing of permissions of a directory while under the `/DropBox` directory leads to all the files being reimported. **Workaround:** disable the monitor server during permission changes. (Colin is working on a doc PR)

**Comment by dominikl** [comment]
Tested on trout, works fine.

**Comment by joshmoore** [comment]
Otherwise, I clearly get the new warning messages:
```
$ mkdir --mode=000 /OMERO/DropBox/user-1
```
produces
```
2015-05-26 08:04:08,387 ERROR [             fsserver.fsPyinotifyMonitor] (Thread-4  ) Unable to add watch on: /OMERO/DropBox/user-1 : add_watch: cannot watch /OMERO/DropBox/user-1 WD=-1 Errno=Permission denied (EACCES)
```

A few other observations:
 * an unreadable outer directory does not prevent inner directory notifications from being received.
 * an unreadable file produces an `UNREADABLE_FILE` "ERROR" in master.err (RFE)
 * for the restart workaround, it's necessary to restart DropBox *after* MonitorServer in order for the MS to start listening to files.

**Comment by ximenesuk** [comment]
See https://github.com/openmicroscopy/ome-documentation/pull/1219 for documentation.

**Pull request merged**
