### PR TITLE
switch source file line breaks to LF

### PR DESCRIPTION
**Pull request by mtbc**
We generally use Unix-style line endings but some files differ. This PR fixes (now, some of) those outliers. No change at all should be observed with OMERO's behavior. See https://github.com/openmicroscopy/openmicroscopy/pull/4148/files?w=1.

--no-rebase

### CODE REVIEW

**Comment by joshmoore** [comment]
"Showing  0 changed files  with 0 additions and 0 deletions." when viewing with `?w=1`

**Comment by sbesson** [comment]
As a heads-up, assuming this is going to conflict with the rebase of https://github.com/openmicroscopy/openmicroscopy/pull/4145, can we postpone this cleanup once the MATLAB changes are in?

**Comment by mtbc** [comment]
Rather than check for specific conflicts, have force-pushed away commits that touch any MATLAB file, or any server/blitz file (for @jburel's Javadoc work on `ome.services.*`); we can finish them up once those PRs are in.

**Comment by sbesson** [comment]
:+1: works for me

**Pull request merged**
