### PR TITLE
Show tag tagset

### PR DESCRIPTION
**Pull request by will-moore**
This fixes the links to "show" tag when tag is under a tagset or to show tagset.

To test:
 - Browse to Tag under a Tag set, copy link to it ```/webclient/?show=tag-801```, paste to a different browser (not logged in), log in as a different user (who can access the tag) and check you are taken to the tag in tag tree.
 - Repeat with a Tag set. ```/webclient/?show=tagset-801```
 - When combined with #4540 this should also work for tags (in tagset or orphaned) ```webclient/usertags/?show=tag.textValue-Bod1```
 - Also test with a Tag NOT under a Tag set.

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#275](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/275/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/275/consoleText) for more details.
Possible conflicts:
  - PR #4511 will-moore 'Show image with pagination'
    - components/tools/OmeroWeb/omeroweb/webclient/show.py

**Comment by jburel** [comment]
@will-moore: could you please add some tests?

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#276](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/276/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/276/consoleText) for more details.
Possible conflicts:
  - PR #4511 will-moore 'Show image with pagination'
    - components/tools/OmeroWeb/omeroweb/webclient/show.py

**Comment by will-moore** [comment]
@chris-allan Just writing more ```Show()``` tests, I realise that none of the ```?show=image.name``` etc will work with the new jsTree (5.2.x) since the jsTree uses ```paths_to_objects``` to get a json hierarchy for traversing to the selected object, but ```paths_to_objects``` only supports IDs, not any other attributes.

We now only use ```Show()``` class to get the owner and group that we need to switch to. We ignore the ```initially_select()``` and ```initially_open()```, since the jstree looks up everything from scratch based on the url ```?show=image-1``` parameter.

To fix this, the ```paths_to_object``` code needs to handle attributes other than ID, making use of the ```Show()``` class.

**Comment by will-moore** [comment]
@chris-allan @joshmoore @jburel. The legacy ```path``` parameter, E.g. ```webclient/?path=project-1|dataset-2|image-3``` is also broken in 5.2.x.
We need to discuss our strategy for fixing all this: combining the ```Show()``` class functionality with ```paths_to_object```.

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#277](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/277/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/277/consoleText) for more details.
Possible conflicts:
  - PR #4511 will-moore 'Show image with pagination'
    - components/tools/OmeroWeb/omeroweb/webclient/show.py

**Comment by will-moore** [comment]
@chris-allan Fix PR opened at https://github.com/openmicroscopy/openmicroscopy/pull/4540

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#278](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/278/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/278/consoleText) for more details.
Possible conflicts:
  - PR #4511 will-moore 'Show image with pagination'
    - components/tools/OmeroWeb/omeroweb/webclient/show.py

**Comment by will-moore** [comment]
Closing until https://github.com/openmicroscopy/openmicroscopy/pull/4518 is merged and can fix conflicts

**Comment by pwalczysko** [comment]
All works fine as prescribed in the header of the PR.
The only question is that 
``https://cowfish.op....y.org/merge/webclient/usertags/?show=tagset.textValue-ggg``
works, which is surprising (not totally intended). From the user perspective, this is perfectly expected and logical behaviour though. @will-moore will have a look at this case, and when okay, this is fine by me as is the whole PR.

**Comment by will-moore** [comment]
This is behaving as expected. Show.py class handles 'tagset' to produce:
```
show.initially_select = [u'tagset-23551']
```
And this is then handled by ```paths_to_tag``` to highlight tagset in tree.

So this is "good to merge" from me too.

**Pull request merged**
