### PR TITLE
More server ivy cleanup

### PR DESCRIPTION
**Pull request by sbesson**
Follow-up of recent cleanup effort, this PR keeps on removing local JARs from `lib/repository`:

- twp series of dependencies are not modified by this PR: Ice (handled in https://github.com/openmicroscopy/openmicroscopy/pull/3957) and Hibernate (handled in https://github.com/openmicroscopy/openmicroscopy/pull/3904)
- most of the other dependencies included server-side should be reviewed and switched to Maven central repository
- some dependencies resolved transitively are cleaned up from the Ivy files notably `httpmime`, `pdfbox` and `subethasmtp`

In particular, `javax` `mail` is now retrieved as a dependency of `subethasmtp` although we may want to keep a `versions.mail` property is this need to be overriden /cc @joshmoore @aleksandra-tarkowska 

To review this, PR check the dependencies report of the server under `share/server` and `share/client` with and without this PR.

### CODE REVIEW

**Comment by sbesson** [comment]
This may have caused https://ci.openmicroscopy.org/view/Failing/job/OMERO-5.1-merge-build/ICE=3.5,jdk=8_LATEST,label=trout/561/ to fail. Excluding temporarily.

**Comment by sbesson** [comment]
Found the issue, it looks like the java-getopt jar from Maven is already signed. I'll be removing it from the last commit cleanup and reinclude.

**Comment by jburel** [comment]
The following could be cleaned up:
```
components/insight/ivy.xml:    <dependency org="commons-logging" name="commons-logging" rev="${versi:ons.commons-logging}"/>
```
typo

**Comment by jburel** [comment]
The lists of jars under "conflicts" have now increased:
 * client by 1:
   * ```slf4j-api by org.slf4j```
 * server by 2:
  * ```activation by javax.activation```
  * ```slf4j-api by org.slf4j```

**Comment by jburel** [comment]
typo has been fixed.
@aleksandra-tarkowska: any opinion about ```mail``` cf. description

**Comment by aleksandra-tarkowska** [comment]
I don't have any problems with the changes although CC doesn't work.

**Comment by jburel** [comment]
CC does not seem to be related to that PR. Merging so we can clean up the insight build (drop of Java 1.6)

**Pull request merged**
