### PR TITLE
Hibernate 3.6 update (trac-2570)

### PR DESCRIPTION
**Pull request by joshmoore**
This is another attempt at gh-3181. Opening again in breaking first to see if the regular behavior is maintained.

### CODE REVIEW

**Comment by joshmoore** [comment]
There are still a number of search tests which need fixing: https://ci.openmicroscopy.org/view/Breaking/job/OMERO-5.1-breaking-integration-python/297/

**Comment by joshmoore** [comment]
Removing `exclude` since the decoupling branch is through.

**Comment by sbesson** [comment]
Note that with this PR included, https://ci.openmicroscopy.org/job/OMERO-5.1-breaking-integration-java/314/ has only 2 failures due to `LockTimeout`.

**Comment by joshmoore** [comment]
Re-excluding to get breaking build green. The test failures are coming from the fact that `IUpdate.indexOjbect` no longer works since only the `Indexer` JVM has the fix from https://github.com/joshmoore/openmicroscopy/commit/e73db4518af44c621dce93c84fab6d7c9387a836

**Comment by sbesson** [comment]
Note: spring `lib/repository` cleanup now opened against the mainline as of https://github.com/openmicroscopy/openmicroscopy/pull/4269

**Comment by joshmoore** [comment]
Closing for the moment; see https://trello.com/c/ahpjb7IY/99-hibernate-3-6

**Pull request closed without merging**
