### PR TITLE
Call setup

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
This is follow up PR #4290, which that should allow deploy with Django 1.8 https://trello.com/c/d7pYClU9/64-windows-py2-7-django-1-8-iis

### CODE REVIEW

**Comment by sbesson** [comment]
Discussed with @aleksandra-tarkowska, excluding this for now (unless it fixes a blocker) we can work on supporting Django 1.8 on Windows for 5.2.1.

**Comment by aleksandra-tarkowska** [comment]
This PR is necessary to get web working on windows otherwise ``Django - A server error occurred. Please contact the administrator`` occurs because of https://docs.djangoproject.com/en/1.8/topics/settings/#calling-django-setup-is-required-for-standalone-django-usage

**Comment by dominikl** [comment]
Tested with Windows Server 2012; without the PR I got the server error 500, with the changes of this PR OMERO.web works fine. Can't say much about the changes itself, as I don't know anything about Django.

**Comment by jburel** [comment]
Discussed with @dominikl, merging

**Pull request merged**
