### PR TITLE
Plate to QA

### PR DESCRIPTION
**Pull request by jburel**
To test 
 * Select a faulty plate
 * Click Submit
 * A dialog will pop up asking if you wish to submit the error.
 * Click no. The process should stop
 * Click Submit
 * A dialog will pop up asking if you wish to submit the error.
 * Click yes, The exception and log should be sent.

To test, use a plate under ```squig/team/jburel/broken plates from Petr```

### CODE REVIEW

**Comment by dominikl** [comment]
Works like expected, good to merge.
Just an idea for improvement (not specifically related to this PR): Would be nice if one could select the text in the MessageBox (for copying/pasting the email address from the message shown).

**Comment by jburel** [comment]
@dominikl: That will require changing the message box itself. I don't think I will do that in this PR since we are using this message box in many places.

**Comment by jburel** [comment]
CLI corresponding one has been merged. Improvement possible to exception returned.
When this is done, we can review the code.

**Comment by jburel** [comment]
--no-rebase

**Pull request merged**
