### PR TITLE
Script ui tabbing

### PR DESCRIPTION
**Pull request by will-moore**
Fixes https://trac.openmicroscopy.org/ome/ticket/12080

To test:
 - Open a script from the scripts menu
 - On opening, the "focus" should be on the first input.
 - Tab key should move you through all the fields, going to "Run Script" *before* "Cancel".

### CODE REVIEW

**Comment by gusferguson** [comment]
@will-moore 

Tested on trout merge using Mac Safari user-3 read-only-1

First field does not have focus on opening - need to tab once to get to it.
At end of all fields tab causes focus to disappear.
If tab again focus goes back to first field.

It looks as if this PR did not get into the build after all.

**Comment by will-moore** [comment]
Yeah, it seems that the PR isn't in today. However, even if it IS working, I would still expect these to happen:
```
At end of all fields tab causes focus to disappear.
If tab again focus goes back to first field.
```

**Comment by gusferguson** [comment]
@will-moore - the focus never moves on to the buttons.

**Comment by gusferguson** [comment]
@will-moore 

Tested using trout merge user-3 read-only.

When script UI opens the focus is on the first text field - bypassing any drop-down controls above the text field. Tabbing through then works fine on the remaining text fields and drop-downs. At the end of the “in window” controls focus moves somewhere (does not seem to be “Cancel” then to the “Run Script” button. If tabbing continues then the focus moves to the first control in the window even if this is a drop-down.
I am struggling to work out what should be happening here.

**Comment by will-moore** [comment]
Currently it's picking the first ```<input>``` element (not drop-down ```<select>```), which is practise is possibly more convenient since the "DataType" field is the first parameter in most scripts and should already be auto-populated. But, I guess I should fix it so that focus goes to the first input/select field in the form, since this is more understandable and consistent.
As long at focus goes to the "Run Script" before "Cancel" then this is working. That's what @joshmoore wanted I think?

**Comment by gusferguson** [comment]
@will-moore - I also noticed that theRun Script button is not highlighting when it receives focus - which is a bit disconcerting as there is a gap when you are left feeling nothing is happening. Certainly when yu reach the end of the in-window controls, tab and hit return - nothing happens. I don't know how much of this is limited by the UI framework. If Josh's RTE is fulfilled then it may well just be time to move on.

**Comment by will-moore** [comment]
@gusferguson For me the "Run Script" button does appear focussed after the last field (see screenshots from Batch Image Export).

screen shot 2015-06-22 at 21 53 12

screen shot 2015-06-22 at 21 52 56

**Comment by will-moore** [comment]
Fixed so that the first field (including "select") is selected initially.

**Comment by will-moore** [comment]
oops - Just did a push -f to the wrong branch.

**Comment by joshmoore** [comment]
You should be able to force push back whatever was here before. (would also be good to *know* if that works... :smile:)

**Comment by will-moore** [comment]
I did force push after closing this PR, but this just disabled the "Reopen" button.
Now re-opened at #3894.

**Comment by joshmoore** [comment]
Good to know. Thanks.

**Comment by gusferguson** [comment]
@will-moore 

Browser fun!

Tested using:
Mac:
Safari - does not tab to "Run Script" button or "Cancel" - just never get focus just a gap before focus returns to first element
Chrome - tabs to Cancel but focus skips Return
Firefox - works as expected

Windows:
IE 10, Firefox and Chrome all work as expected.

Windows all working - Firefox on Mac working - time to cut the losses and merge me thinks.

**Pull request closed without merging**
