### PR TITLE
Fix import in obj plugin

### PR DESCRIPTION
**Pull request by ximenesuk**
This PR tries to fix a problem seen by @aleksandra-tarkowska relating to gh-4508  This needs to be tested using Ola's workflow for deploying a server.

### CODE REVIEW

**Comment by joshmoore** [comment]
Note: I haven't yet reproduced @aleksandra-tarkowska's issue with https://github.com/ome/ome-docker/pull/31. It's currently running and `bin/omero config set` passes. Can discuss tomorrow.

(NB: `bin/omero obj` hangs)

**Comment by ximenesuk** [comment]
Looks like `bin/omero obj` has been hanging since at least `5.2.2`.

**Comment by ximenesuk** [comment]
@joshmoore this last commit fixes the hang in a very minimal way. However, I'm not sure what you intended with the `--file` option if no file was provided (the help is suppressed). I have not tested this with a file.

**Comment by aleksandra-tarkowska** [comment]
@joshmoore how do you mean?

```
$ build --rm -t omerotest .
Sending build context to Docker daemon 16.38 kB
Step 1 : FROM openmicroscopy/omero-ssh-systemd
latest: Pulling from openmicroscopy/omero-ssh-systemd
1544084fad81: Pull complete 
...
Successfully installed Django-1.8.11 argparse-1.4.0 omego-0.3.0 py-1.4.31 pytest-2.8.1 yaclifw-0.1.2
+ omego download --branch OMERO-DEV-merge-build openmicroscopy
2016-03-10 19:59:45,477 [omego.artifa] INFO  Checking https://ci.openmicroscopy.org/job/OMERO-DEV-merge-build/ICE=3.5,jdk=8_LATEST,label=octopus/256/artifact/src/target/openmicroscopy-5.2.2-97-6430659.zip
2016-03-10 19:59:45,478 [omego.fileut] INFO  Downloading https://ci.openmicroscopy.org/job/OMERO-DEV-merge-build/ICE=3.5,jdk=8_LATEST,label=octopus/256/artifact/src/target/openmicroscopy-5.2.2-97-6430659.zip
2016-03-10 19:59:59,886 [omego.artifa] INFO  Unzipping openmicroscopy-5.2.2-97-6430659.zip
...
+ /home/omero/OMERO.server/bin/omero config set omero.data.dir /OMERO
Error loading: /home/omero/OMERO.server/lib/python/omero/plugins/obj.py
Traceback (most recent call last):
  File "/home/omero/OMERO.server/lib/python/omero/cli.py", line 1368, in loadpath
    execfile(str(pathobj), loc)
  File "/home/omero/OMERO.server/lib/python/omero/plugins/obj.py", line 38, in <module>
    from omero.model import NamedValue
ImportError: cannot import name NamedValue
...
```

```
$ docker run --privileged -ti --rm -p 2222:22 --name omerotest omerotest
...
[omero@cb38d6514b1b ~]$ OMERO.server/bin/omero config get
Error loading: /home/omero/OMERO.server/lib/python/omero/plugins/obj.py
Traceback (most recent call last):
  File "/home/omero/OMERO.server/lib/python/omero/cli.py", line 1368, in loadpath
    execfile(str(pathobj), loc)
  File "/home/omero/OMERO.server/lib/python/omero/plugins/obj.py", line 38, in <module>
    from omero.model import NamedValue
ImportError: cannot import name NamedValue
omero.data.dir=/OMERO
```

**Comment by aleksandra-tarkowska** [comment]
I tested your branch directly, problem solved. I will retest with tomorrows merge build.

**Comment by ximenesuk** [comment]
I can't see anything in the original PR, https://github.com/openmicroscopy/openmicroscopy/pull/2409 that might suggest any intention. The use of `--file` with a file still passes tests.

**Comment by joshmoore** [comment]
The original intent can probably be best seen in this removed diff: https://github.com/joshmoore/openmicroscopy/commit/ba498ac073a6f2ac0abbb0f167c4e2d43e8fcea8#diff-83e58bd0991774466c00b1995f7d2fc7L255

It's suppressed, i.e. it's still possible to use, but since all the commands are no longer in one transaction (`tx`) it doesn't have the same benefit it once did and bash suffices.

**Comment by ximenesuk** [comment]
So the current fix is reasonable/not harmful?

**Comment by aleksandra-tarkowska** [comment]
To reduce time of building I just tested with omeroweb docker as the failure appeared the same way

```
+ omego download python --branch=OMERO-DEV-latest --labels ICE=3.5
2016-03-11 09:20:06,943 [omego.artifa] INFO  Checking https://ci.openmicroscopy.org/job/OMERO-DEV-latest/ICE=3.5,jdk=8_LATEST,label=octopus/228/artifact/src/target/OMERO.py-5.2.2-34-768cafd-ice35-b228.zip
2016-03-11 09:20:06,943 [omego.fileut] INFO  Downloading https://ci.openmicroscopy.org/job/OMERO-DEV-latest/ICE=3.5,jdk=8_LATEST,label=octopus/228/artifact/src/target/OMERO.py-5.2.2-34-768cafd-ice35-b228.zip
2016-03-11 09:20:07,132 [omego.artifa] INFO  Unzipping OMERO.py-5.2.2-34-768cafd-ice35-b228.zip
...
+ /home/omero/OMERO.py/bin/omero load /home/omero/omeroweb.config
Error loading: /home/omero/OMERO.py/lib/python/omero/plugins/obj.py
Traceback (most recent call last):
  File "/home/omero/OMERO.py/lib/python/omero/cli.py", line 1368, in loadpath
    execfile(str(pathobj), loc)
  File "/home/omero/OMERO.py/lib/python/omero/plugins/obj.py", line 38, in <module>
    from omero.model import NamedValue
ImportError: cannot import name NamedValue
```

using today's merge build:

```
+ omego download python --branch=OMERO-DEV-merge-build --labels ICE=3.5
2016-03-11 09:18:24,496 [omego.artifa] INFO  Checking https://ci.openmicroscopy.org/job/OMERO-DEV-merge-build/ICE=3.5,jdk=8_LATEST,label=octopus/257/artifact/src/target/OMERO.py-5.2.2-110-123d779-ice35-b257.zip
2016-03-11 09:18:24,497 [omego.fileut] INFO  Downloading https://ci.openmicroscopy.org/job/OMERO-DEV-merge-build/ICE=3.5,jdk=8_LATEST,label=octopus/257/artifact/src/target/OMERO.py-5.2.2-110-123d779-ice35-b257.zip
2016-03-11 09:18:24,679 [omego.artifa] INFO  Unzipping OMERO.py-5.2.2-110-123d779-ice35-b257.zip
...
+ /home/omero/OMERO.py/bin/omero load /home/omero/omeroweb.config
+ /home/omero/OMERO.py/bin/omero web config nginx
+ sudo cp /home/omero/omero-web.conf.tmp /etc/nginx/conf.d/omero-web.conf
```

**Comment by aleksandra-tarkowska** [comment]
I gave another try with vagrant. Using `vagrant init centos/7` I followed all the installation exactly like in a docker

```
[omero@localhost vagrant]$ omego download python --branch=OMERO-DEV-latest --labels ICE=3.5
2016-03-11 06:40:10,939 [omego.artifa] INFO  Checking https://ci.openmicroscopy.org/job/OMERO-DEV-latest/ICE=3.5,jdk=8_LATEST,label=octopus/228/artifact/src/target/OMERO.py-5.2.2-34-768cafd-ice35-b228.zip
...
lrwxrwxrwx. 1 omero omero   48 Mar 11 06:42 OMERO.py -> /home/omero/OMERO.py-5.2.2-34-768cafd-ice35-b228
...
(omeropy-virtualenv)[omero@localhost ~]$ OMERO.py/bin/omero config set omero.web.server_list '[["localhost", 4064, "omero"]]'
(omeropy-virtualenv)[omero@localhost ~]$ OMERO.py/bin/omero config set omero.web.server_list '[["localhost", 4064, "omero"]]'^C
(omeropy-virtualenv)[omero@localhost ~]$ OMERO.py/bin/omero config get
omero.web.server_list=[["localhost", 4064, "omero"]]
```

and all works, does it mean this error an a mister of docker?

**Comment by manics** [comment]
What version of python (rpm -q python)?

**Comment by aleksandra-tarkowska** [comment]
```
cowfish$ rpm -q python
python-2.7.5-34.el7.x86_64

[vagrant@localhost ~]$ rpm -q python
python-2.7.5-34.el7.x86_64

[omero@docker ~]$  rpm -q python
python-2.7.5-34.el7.x86_64
```

**Comment by joshmoore** [comment]
> So the current fix is reasonable/not harmful?

Think this means you are disabling an undocumented "feature" but it has a fallback. (`bin/omero obj` --> `bin/omero obj --file=-`) Considering it confused me, this seems safer.

**Comment by joshmoore** [comment]
@ximenesuk : do you want to try anything else with the imports in this PR?

**Comment by ximenesuk** [comment]
I'd say merge this if it works and then investigate a more general plugin-wide solution via the imports card.

**Pull request merged**
