### PR TITLE
CLI: review help command and add recursive argument

### PR DESCRIPTION
**Pull request by sbesson**
Following discussion https://github.com/openmicroscopy/openmicroscopy/pull/3507, this PR also aims to address https://trac.openmicroscopy.org/ome/ticket/10851.

Notable changes to the CLI `HelpControl` class are listed below:
- `--all/topic` are moved in a mutually exclusive group
- a `--recursive` argument is added to the parser allowing to display subcommands help
- a `--list` argument is added to the parser allowing to list all commands/subcommands
- the command title is formatted to distinguish commands and subcommands
- Sphinx compatible separators are used in case we want including this output of `bin/omero help --all --recursive` in the documentation
- unit tests are added and should be run by Travis

To test this PR, review the various versions of the command:

```
bin/omero help -h
bin/omero help --all
bin/omero help --all --recursive
bin/omero help --list
bin/omero help <command_or_topic>
bin/omero help <command_or_topic> --recursive
```

The subcommands list suggestion proposed in https://github.com/openmicroscopy/openmicroscopy/pull/3507#issuecomment-75281762 is hard to implement as it requires modifying the argparse formatter. An option would be to generate a simple list subcommands like `bin/omero config parse --keys`. Thoughts @ximenesuk ?

--no-rebase

### CODE REVIEW

**Comment by ximenesuk** [comment]
Looks good testing locally. I appreciate the limitations of `argparse`. A simple list would, I think, be useful if it can be done.

**Comment by sbesson** [comment]
@ximenesuk: `--list` argument added.

**Comment by ximenesuk** [comment]
I think the `--list` output is excellent. It may even be useful to @pwalczysko

**Comment by sbesson** [comment]
Pushed.

**Comment by ximenesuk** [comment]
Looks fine, good to merge.

**Pull request merged**
