### PR TITLE
test Security Violation

### PR DESCRIPTION
**Pull request by jburel**
Create group with correct permissions.
The permission level of the group was not correctly set.
To test:
Check that the Java tests are greeen

### CODE REVIEW

**Comment by sbesson** [comment]
Closing/reopening to include #4196 in the merge commit for Travis.

**Comment by mtbc** [comment]
https://ci.openmicroscopy.org/job/OMERO-DEV-merge-integration-java/lastCompletedBuild/testngreports/integration/PojosServiceTest/ is nicely green.

**Comment by mtbc** [comment]
The diff looks like a sensible solution.

**Comment by jburel** [comment]
--rebased-to #4204

**Pull request merged**
