### PR TITLE
Fixing Download button

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
https://github.com/openmicroscopy/openmicroscopy/pull/3543 follow up.

As long as PR #3593 is in, this should validate default settings and enable download button for image and file annotations but not allow to download plate. For custom config this can be tested as stated in #3593

**To test** go to Read-Ann group, choose user, choose own image and download. Repeat the same test in read-only and private group, try also with big image. Then test plate. Arrow button was turned on but you should see only export as, no Download.

Check if test passed
https://ci.openmicroscopy.org/view/Failing/job/OMERO-5.1-merge-integration-web/lastCompletedBuild/testReport/test.integration.test_download/TestDownload/test_spw_download/

--no-rebase

### CODE REVIEW

**Comment by joshmoore** [comment]
Should this fix https://ci.openmicroscopy.org/view/Failing/job/OMERO-5.1-merge-integration-web/271/testReport/ ?

**Comment by aleksandra-tarkowska** [comment]
@joshmoore as I understand PR #3593 Plate.getDetails...isRestricted() should return True ?

**Comment by aleksandra-tarkowska** [comment]
Tested following:

 - default config omero.policy.binary_access=+read,+write,+image,-plate:

  ```<class 'omeroweb.webclient.webclient_gateway.WellWrapper'> True
<class 'omeroweb.webclient.webclient_gateway.ImageWrapper'> True
<class 'omero.gateway.FileAnnotationWrapper'> False```

**Comment by aleksandra-tarkowska** [comment]
Tested following:

 - default config omero.policy.binary_access=+read,+write,+image,-plate:

  ```
  <class 'omeroweb.webclient.webclient_gateway.WellWrapper'> True
  <class 'omeroweb.webclient.webclient_gateway.ImageWrapper'> True
  <class 'omero.gateway.FileAnnotationWrapper'> False
```

Why image is not available?

**Comment by joshmoore** [comment]
Sorry, can you pull again from my PR?

**Comment by aleksandra-tarkowska** [comment]
As long as PR #3593 is in, this should enable download button by default for image and file annotations but not allow to download plate. For custom config test as stated in #3593

**Comment by pwalczysko** [comment]
Works as expected. Tested mine and others data in all types of groups, also logged in as admin. Ready to merge.

**Comment by sbesson** [comment]
The failing SPW test is now passing. But the fix in the last commit exposed another regression in 
https://ci.openmicroscopy.org/view/Failing/job/OMERO-5.1-merge-integration-web/lastCompletedBuild/testReport/test.integration.test_download/TestDownload/test_image_download/ for orphaned images.
Once this is fixed, this PR is ready to merge from a test perspective. As discussed with @aleksandra-tarkowska yesterday, in the perspective of 5.1.0, this `test_download` should be extended to cover other scenarios including:
- images in a P/D container as well as orphaned
- wells download

**Comment by aleksandra-tarkowska** [comment]
these should resolve issue mentioned above and add more tests
```
Mac-Book-Pro:OmeroWeb ola$ ./setup.py test -t test/integration/test_download.py
...
running build_ext
================================================= test session starts =================================================
platform darwin -- Python 2.7.2 -- py-1.4.25 -- pytest-2.6.3
collected 5 items 

test/integration/test_download.py .....

============================================== 5 passed in 15.24 seconds ==============================================
```

**Comment by aleksandra-tarkowska** [comment]
and testing attachement

**Comment by sbesson** [comment]
https://ci.openmicroscopy.org/view/Failing/job/OMERO-5.1-merge-integration-web/275/ is green. So :+1: from that perspective.

**Pull request merged**
