### PR TITLE
Uniform User/Group Menu

### PR DESCRIPTION
**Pull request by dominikl**
Fixes [Ticket 12042](https://trac.openmicroscopy.org/ome/ticket/12042)

In the user/group menu different items were used (JCheckBoxes, custom JCheckBox menu items, etc.); on OSX they appeared to look the same, but you could see the difference on Windows. With this PR only the customized JCheckBox style menu item will be used in the popup menu.

Test: Make sure that on all platforms, OSX, Windows and Linux, the user/group menu in the main toolbar has a uniform style.

--no-rebase

### CODE REVIEW

**Comment by gusferguson** [comment]
@dominikl 

Tested with user-3 
OMERO.insight-5.1.0-182-51940eb-ice35-b465-mac_Java6 - on OS10.10.2
- behaves as expected.

OMERO.insight-5.1.0-182-51940eb-ice35-b465-win - on Windows 8
- behaves as expected.

OMERO.insight-5.1.0-182-51940eb-ice35-b465-linux - on Ubuntu 14.04
- problem with the highlight colour of the text of selected users and All Users - too pale to read.
- not sure why this happens as text does not change colour on other OSs.
See screenshots.

parallels desktop 2

parallels desktop 3

parallels desktop

**Comment by dominikl** [comment]
That's strange... I'm quite sure I've not seen that on Debian. I'll check again with an Ubuntu VM, maybe I can find out, what's happening there.

**Comment by dominikl** [comment]
@gusferguson  This is a quirk of the Ubuntu window manager, does not happen with other window managers, e. g. XFCE.  Can we leave it like this? Or should I try to find a workaround for it?

**Comment by dominikl** [comment]
Actually I just found and fixed the cause for this; ready for re-review. Apart from the unified look, make sure the functionality of the user/group menu is still working.

**Comment by joshmoore** [comment]
Re-added to standup. Needs Ubuntu testing.

**Comment by gusferguson** [comment]
@dominikl 

Retested with user-3 trout build OMERO.insight-5.1.0-443-8e390c4-ice35-b476
Mac OSX 10.10.3
Windows 8
Ubuntu 14.04

Ubuntu working fine now.
Other operating systems fine as before.
Good to merge.

parallels desktop

parallels desktop

omero insight

**Comment by pwalczysko** [comment]
Tried Win7 , Mac OS X 10.8 and Ubuntu 14.04. All worked fine.

**Comment by jburel** [comment]
@dominikl: Do we have cases where data could be null?
the data.toString() will lead to a NPE

**Comment by dominikl** [comment]
@jburel No, I don't think so. Creating a DataMenuItem with `data == null` wouldn't make any sense. Without the PR an IllegalArgumentException would have been thrown in such a case. With this PR a NPE would be thrown, that's not much of a difference (and should not happen anyway).

**Comment by jburel** [comment]
@dominikl: merging.

**Pull request merged**
