### PR TITLE
Api tagged perms

### PR DESCRIPTION
**Pull request by will-moore**
This uses the ```select map( )``` format of iQuery when loading tagged data, as we already do with other jsTree data, in order to work-around the hibernate projection permissions issues.

This fixes permissions on tagged objects belonging to other users.
Also adds tests to check this.

To review:
 - Check that all tests are passing
 - Look at the queries to check they make sense (that there isn't an obviously better way than the inner ```select``` to ensure that results are distinct)?

### CODE REVIEW

**Comment by jburel** [comment]
Did you test the performance with the extra select in the map?

**Comment by will-moore** [comment]
OK, I have tagged about 2000 images with a single tag (in group 5), and have added print statements to time the query and iterating through the query.

With this query:
```
select new map(obj.id as id,
               obj.name as name,
               obj.details.owner.id as ownerId,
               obj as image_details_permissions,
               obj.fileset.id as filesetId 
             ,
             pix.sizeX as sizeX,
             pix.sizeY as sizeY,
             pix.sizeZ as sizeZ
             ,
            obj.details.creationEvent.time as date,
            obj.acquisitionDate as acqDate
            )
            from Image obj  left outer join obj.pixels pix
            join obj.annotationLinks alink
            where alink.id = (select max(alink.id)
                from ImageAnnotationLink alink
                where alink.child.id=:tid and alink.parent.id=obj.id)
        
                    order by lower(obj.name), obj.id
```

For a tag with 2000 images this takes approximately ```4 seconds```. 

Interestingly, I just tried this without specifying the group context, E.g. (group is -1 instead of 5) and the exact same query takes about ```1.3 seconds```! Any idea why this might be @joshmoore?

Now, if I remove the second select statement, replace it with
```
where alink.child.id=:tid
```
the time goes down to ```1.2 seconds``` (still with group -1).

If I use group 5 again, without the second select statement, I get about the same ```1.2 seconds```.

So, only a small amount slower (less that 10% increase) with the second select statement.

Strange that use of ```group 5``` has such a big effect on the timing when combined with the extra select statement.
Maybe we could simply ignore the group filter in the tree.py query if we're querying by tag ID?
At least for now I'll remove it from the javascript AJAX query builder.

**Comment by will-moore** [comment]
@joshmoore In general, is it better to keep group context at ```-1``` unless we actually need to filter by group? Currently jsTree is adding group context to every query, even though it doesn't need it.
I think this should be fixed, but not until #4389 is merged, since it would conflict.

**Comment by joshmoore** [comment]
Personally, this sounds like a bug somewhere. I also wouldn't expect for `group:-1` to be faster.

**Comment by will-moore** [comment]
Tried to reproduce the bug in a test, but it mostly passes (```group:-1``` is slower).

**Comment by will-moore** [comment]
So it seems that testing query performance in web today does not show the slow-down 'bug' with ```group: 5``` that I was seeing above.
I'll fix up the test (so it's not so fragile dependent on query time).

**Comment by will-moore** [comment]
I've removed the test, since it's not really valid.

**Comment by will-moore** [comment]
@joshmoore Any suggestions for how to ensure unique query results without the second select statement? Otherwise I guess we have to accept the 10% performance penalty?

**Comment by joshmoore** [comment]
@will-moore : I'm slightly lost. Could you point me to a failing test (i.e. something where non-unique results are returned but expected) that I could attempt to fix?

**Comment by will-moore** [comment]
@joshmoore That commit contains a failing test where non-unique results are returned as expected. A "fix" would just be a nicer (more performant) way to ensure unique results without the need for a second select statement.

**Comment by joshmoore** [comment]
@will-moore: could you try https://github.com/joshmoore/openmicroscopy/commit/d37772ca5acb2f2afc7f28df612a4178c1294746 ?

**Comment by will-moore** [comment]
So, tests should all be passing again. We now use a simper query in tree.py using ```distinct``` instead of a second ```select``` statement.
Check that browsing tags in web shows same data as Insight.

**Comment by dominikl** [comment]
Looks fine. Tests passed. Couldn't spot any difference between Insight and Web browsing through tags.

**Pull request merged**
