### PR TITLE
Metadata/table data url links

### PR DESCRIPTION
**Pull request by will-moore**
This is https://github.com/openmicroscopy/openmicroscopy/pull/3884 rebased onto metadata (on top of https://github.com/openmicroscopy/openmicroscopy/pull/3875).

========================================================================

See: https://trello.com/c/e4Jxa6My/11-adding-links-within-metadata

This PR provides 3 steps for adding urls to Table Data.
All parts of this are speculative and up for discussion.

- Add a 'url' description to the column name in your CSV file. Currently I'm using a double %% as the delimiter, but this could be changed? E.g.
    ``` Gene_Symbol %% url=http://www.ensembl.org/id/%s ```
 This will be parsed by the populate_metadata script, which will attempt to add the data as json in the Column description. E.g.
   Name: ```Gene_Symbol```
   Description: ``` '{"url": "http://www.ensembl.org/id/%s"}' ```

- Webgateway now adds the description to the json Table data, and attempts to parse the description as json. E.g. 
```
data: {
    rows: [
        [
        "ENSG00000117399",
        "CDC20",
        "44",
        ]
    ],
    descriptions: [
        "",
        {
        url: "http://www.ensembl.org/id/%s"
        },
        ""
    ],
    columns: [
        "Entity_Identifier",
        "Gene_Symbol ",
        "Entity_Number",
    ]
}
```

- Finally, if a description url is found, webclient uses it to create a link when displaying the gene name.

screen shot 2015-06-19 at 11 54 33

### CODE REVIEW

**Comment by will-moore** [comment]
cc @eleanorwilliams @manics Can continue the discussion of the url workflow based on this PR...

**Comment by jburel** [comment]
cf. Description you mean ```rebased onto develop```

**Comment by will-moore** [comment]
Oooops. @jburel - I rebased this onto of metadata branch and meant to open a PR against metadata branch too. That is now #3889. Closing this one.

**Comment by eleanorwilliams** [comment]
I've loaded some bulk annotation for the Sysgro-partial screen on dogfish (under Josh's name).  I renamed Entity Identifier to 'Gene Identifier' as in all the screens seen so far it seems to be a gene but made the actual column heading  'Gene Identifier %% url=http://www.ensembl.org/id/%s'.  

Is this the right format to try out?

**Pull request closed without merging**
