### PR TITLE
merge regions into develop

### PR DESCRIPTION
**Pull request by mtbc**
The work in the regions space will now be occurring on the develop branch.

--no-rebase

### CODE REVIEW

**Comment by ximenesuk** [comment]
It looks like this PR is responsible for: https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-breaking-integration-python/472/testReport/OmeroPy.test.integration.gatewaytest.test_image/TestImage/testExport/ though I'm not entirely sure why as of yet.

The related test, https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-breaking-integration-python/472/testReport/OmeroPy.test.integration.test_exporter/TestExporter/testBasic/ does pass though it accesses the export functionality slightly differently and with a different test image.

@mtbc has commented that the tests passed for him before this was rebased. Could the rebasing be causing the issue @joshmoore ?

**Comment by sbesson** [comment]
Given the stacktrace for the failing test above, I am suspecting openmicroscopy/bioformats#2168 might be causing this error. I will exclude the Bio-Formats PR for the next build since it needs some additional work /cc @melissalinkert

**Comment by ximenesuk** [comment]
Thanks @sbesson, I was initially distracted by the different results for the different tests but these may well result in slightly different calls to B-F with different data.

**Comment by sbesson** [comment]
The `sql` folder currently misses the SQL scripts for the last released DB version. So the current state of OMERO.server build from this branch fails to upgrade a `5.2__0` DB - see https://ci.openmicroscopy.org/job/OMERO-DEV-breaking-deploy/526.

**Comment by mtbc** [comment]
I guess something went wrong in the merging? It's the SQL scripts that defeated me when I tried to do it though. @joshmoore, do you know how to fix this to keep the commit history good? Happy to close this and just have you cherry-pick https://github.com/mtbc/openmicroscopy/commit/ff58b1f29d6d7a3f31cb8aebcfcf0a5980b317c7 if that's easier.

**Comment by mtbc** [comment]
(Or I'm happy to just add/rm files at the end of the history if that's acceptable!)

**Comment by joshmoore** [comment]
@mtbc : is it clear when they went lost? I.e. did I do it, in which case, it was just an oversight. Sorry!

**Comment by mtbc** [comment]
Oh! Is it just that `OMERO5.3DEV__0/OMERO5.2DEV__0.sql` now needs to be `OMERO5.3DEV__0/OMERO5.2__0.sql`? If so, I can tweak it accordingly.

**Comment by sbesson** [comment]
Looking at the final `OMERO5.2__0` and looking at this PR diff, is it reverting some of the changes made in gh-4273, e.g. https://github.com/openmicroscopy/openmicroscopy/pull/4273/files#diff-1d43a2c58465a466f624e511ecad14b3L1587 ?

**Comment by mtbc** [comment]
Good catch, thank you. I'll work on a commit to make the necessary SQL repairs, then we'll see how things are.

**Comment by mtbc** [comment]
Merges cleanly and CI seems fine. Closing in favor of #4424.

**Pull request closed without merging**
