### PR TITLE
Bump to ice 3.6.4

### PR DESCRIPTION
**Pull request by jburel**
# What this PR does

Bump ice version to 3.6.4

# Testing this PR
Check that things remain green

# Related reading

https://trello.com/c/xgoLB3Px/147-test-ice-364

### CODE REVIEW

**Comment by sbesson** [comment]
See https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-merge-daily/721/ and downstream broken builds. Additional JARs (`omero-shares`, `ice-db`)  are required to make this functional. Excluding and relaunching the CI jobs to allow the review.

**Comment by mtbc** [comment]
Does this mean that we should warn our users not to install OMERO with Ice 3.6.4?

**Comment by jburel** [comment]
some of "our jars" will need to be pushed to artifactory
omero-shares does nothing but it is needed

Let's discuss during today's call
```
<dependency org="omero" name="omero-shares" rev="${versions.ice}"/>
```
I should have been more careful but I thought we got rid of it last round

**Comment by sbesson** [comment]
Tested the build locally with Ice 3.6. I could confirm:

- `$ ./build.py -Dmaven.repo.local=/tmp/.m2/repository build-dev` builds from a clean Maven repository
- the server is correctly deployed and minimal testing using the OMERO.cli (login, import, user/group addition) works as expected

I have not tested the compatibility with Ice 3.5 and would need additional time to recreate a building environment if this is needed. From a glance, the changes look fine and effectively decouple the management of the upstream Ice dependencies (`freeze`, `ice`) from the internal Ice-dependent dependencies (`ice-db`, `omero-shares`). As noted elsewhere, we might evolve towards a separate management/renaming of the latter but this is outside the scope of this PR.

**Comment by joshmoore** [comment]
Agreed. Shall we take out of breaking then?

**Comment by joshmoore** [comment]
https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-merge-integration/793/ looks very green. Merging.

**Pull request merged**
