### PR TITLE
Plate run

### PR DESCRIPTION
**Pull request by jburel**
Allow to tag plate run from context menu
To test
 * Log in as user-3
 * Select a plate run
 * Right-click, Check the tagging menu is enabled.
 * Tag the plate run

see https://trac.openmicroscopy.org.uk/ome/ticket/12221

### CODE REVIEW

**Comment by mtbc** [comment]
Works fine, good to merge.

But, first, want to fix it for the well samples too? Same issue: can tag from metadata pane but not from tree viewer.

**Comment by jburel** [comment]
Well samples are not displayed in the tree

**Comment by mtbc** [comment]
Ha, true: I meant, right-click on thumbnail. (Grayed-out tag option.)

**Comment by jburel** [comment]
@mtbc: done

**Comment by mtbc** [comment]
(Pulled and rebuilt locally.) Works fine both for runs and fields, good to merge once Travis settles.

**Comment by jburel** [comment]
Thanks @mtbc. Merging

**Comment by jburel** [comment]
--no-rebase

**Pull request merged**
