### PR TITLE
Add `omero admin checkupgrade`

### PR DESCRIPTION
**Pull request by manics**
Add `omero admin checkupgrade`

This allows scripts to automatically determine whether an updated server is available. Sets exit code 1 if so. To test.... you'll have to override the current server version somehow, or trust the integration test.

If you want to be thorough check an invalid `omero.upgrades.url` sets an exit code that's not 0 or 1.

~~TODO. Since this is going in to 5.2 should we set a specific agent to distinguish upgrade checks from server startups. e.g. `OMERO.status`, `OMERO.upgrade`, ... ?~~

### CODE REVIEW

**Comment by joshmoore** [comment]
`diagnostics` exists. Not sure we need/want another one. @aleksandra-tarkowska?

**Comment by manics** [comment]
I'm after an easy way to know whether an upgrade is available from a script, for this PR I'm setting an exit code but if `diagnostics` has some standard parseable output that would do too.

**Comment by joshmoore** [comment]
Sorry, no objections to this change, I just meant use of the existing `diagnostics` upgrade check name.

**Comment by manics** [comment]
You mean making this a sub-command: `diagnostics --check-upgrade` ?

**Comment by joshmoore** [comment]
No, I'm only looking for the appropriate value for "server" in https://github.com/openmicroscopy/openmicroscopy/pull/4217/files#diff-57f0d9cb121726c674f02fd0bc23bd1cR1794

**Comment by manics** [comment]
OK :-). Though now that it's come up including this in another command instead of creating another top level one might be a good idea....

**Comment by manics** [comment]
Actually, I guess another subcommand of `admin` is't too bad.

@aleksandra-tarkowska What user-agent should I use when checking whether an upgrade is available?

**Comment by aleksandra-tarkowska** [comment]
@manics there is OMERO.test

**Comment by joshmoore** [comment]
@aleksandra-tarkowska : but we ignore those, no? This would be used by actual scripts in (more or less) production.

**Comment by aleksandra-tarkowska** [comment]
No we don't ignore. There is OMERO.test agent in production DB. Hit should be saved

**Comment by jburel** [comment]
@manics: are you still thinking of having this PR in 5.2.0?

**Comment by manics** [comment]
@jburel It'd be nice but not essential.

**Comment by manics** [comment]
@sbesson Integration test added (is there a nicer way of setting the ctx dir?)

**Comment by manics** [comment]
Note I'm now importing `UpgradeCheck` at the top level: https://github.com/manics/openmicroscopy/blob/admin_checkupgrade/components/tools/OmeroPy/src/omero/plugins/admin.py#L38

However I've left https://github.com/manics/openmicroscopy/blob/admin_checkupgrade/components/tools/OmeroPy/src/omero/plugins/admin.py#L1080 in because I'm not sure what's going on with the logging config. @aleksandra-tarkowska ?

**Comment by manics** [comment]
For compelteness it'd be nice to test an invalid url (e.g. `example.org/invalid/checkupgrade`) and assert `rv > 1` to be sure a failed connections is not mistaken for an upgrade

**Comment by sbesson** [comment]
Tested the latest state of this PR with a server with a non-default `omero.upgrades.url` set. `bin/omero admin checkugprade` calls to the correct upgrade URL. Tests under https://ci.openmicroscopy.org/view/DEV/job/OMERO-DEV-merge-integration-python/112/testReport/OmeroPy.test.integration.clitest.test_admin/TestAdmin/ are also passing.
Assuming we all agree with the agent used (`OMERO.test`), this looks ready to merge /cc @joshmoore @aleksandra-tarkowska . We can review the `upgradecheck` usage in the `diagnostics` command in 5.2.1.

**Comment by joshmoore** [comment]
Agreed. Not critical. It will likely have low usage initially.

**Comment by jburel** [comment]
Thanks all merging.

**Pull request merged**
