### PR TITLE
Right panel annotation tabs2

### PR DESCRIPTION
**Pull request by will-moore**
This is a follow-up to https://github.com/openmicroscopy/openmicroscopy/pull/4579 with a refactor of tag loading and a lot of other code cleanup / removal.
Also added some web tests for annotate_tags.

To test:
 - Browse all data types in tree
 - Batch annotate Tags, adding & removing Tags
 - NB: This following is all be tested by Robot tests
    - Check that only tags on all selected objects show up in right column of tag dialog
    - Adding tags to right adds to all objects
    - Moving tags to left removes from all objects
 - Descriptions are displayed in tag tooltip and long text wraps:

screen shot 2016-05-13 at 11 47 33

### CODE REVIEW

**Comment by gusferguson** [comment]
@will-moore

Tested with cowfish user-3 read-only-1

Behaves as expected.
Good to merge.

**Comment by will-moore** [comment]
This is probably casing failing test at https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-merge-integration-Python27/215/testReport/OmeroWeb.test.integration.test_csrf/TestCsrf/test_add_and_remove_comment/ Will check...

**Comment by will-moore** [comment]
To test last commit, add Comment to single object and multiple (batch) objects.
Test should also be passing.

**Comment by gusferguson** [comment]
@will-moore 

Tested with https://cowfish.openmicroscopy.org/webmerge/webclient/ user-3 read-only-1

Comments behave as expected for both single and multiple objects.
Good to merge.

**Comment by will-moore** [comment]
Last commit above removes unused load_public() and containers_icon.html. To test, check functionality of the Public tab. Create and browse shares.

**Comment by gusferguson** [comment]
@will-moore 

Tested using https://cowfish.openmicroscopy.org/webmerge/webclient/ user-3 and user-2

Share functionality behaves as expected.
Good to merge.

**Comment by aleksandra-tarkowska** [comment]
@will-moore you need to fix tests as well https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-merge-integration-Python27/lastCompletedBuild/testReport/

**Comment by jburel** [comment]
Probably need to be relisted?

**Comment by gusferguson** [comment]
@will-moore 

Tested with https://cowfish.openmicroscopy.org/webmerge/webclient/ user-3

Behaves as expected for P/D/I S/R/W.

Good to merge.

**Comment by jburel** [comment]
Cf. last commit, this needs to be synchronised w/ current work done by @aleksandra-tarkowska @pwalczysko, and @sbesson on "share tests" before removing the tests.

**Comment by will-moore** [comment]
The tests were removed because the code they test was removed because it is no-longer used.
We have share tests elsewhere that could be extended, probably in another PR?

**Comment by jburel** [comment]
discussed privately with @will-moore

**Pull request merged**
