### PR TITLE
Roi annotations

### PR DESCRIPTION
**Pull request by jburel**
Replace gh-3928

Initial changes to allow tagging of shapes.
To tag a shape
 * Select the shape
 * right-clik on shape, select the tag option
 * The standard tagging dialog will pop up
 * Select a tag and/or create a new one
 * The tags are displayed in the Inspector tab (for now)
 * Tag can be added or removed from the shapes
 * Shapes need to be saved before tagging can occur.

### CODE REVIEW

**Comment by jburel** [comment]
Travis restarted

**Comment by gusferguson** [comment]
@jburel 
Tested using OMERO.insight-5.2.0-m0-397-e000511-ice35-b60-mac eel member-all-1 private-1

On image IDs: 1902 - 1906

Getting some very strange intermittent errors.

Summary of testing:

With single ROI of any type on image:

Added single tag to single ROI - "Test 15-08-14 08:21:13"
- correct warning to save ROI first
- on saved ROI - tag added correctly and was visible in inspector for ROI and shapes
- repeat this on other images
- behaves as expected.

Added second tag
- appear as comma separated in Inspector
- behaves as expected

Added multiple tags
- appear as comma separated in Inspector
- behaves as expected

Intermittent issue when adding tags to single ROI:
- select ROI (unexpanded)
- right-click produces contextual menu as expected
- select tag —> no tagging dialog appears
- after this the first column of the Manager display appears “selected” - see screenshot 1 below (arrowed).
- if then expand ROI and select shape - contextual menu works as expected and tag is added successfully.
- note this is intermittent and never occurs if ROI is unsaved (strangely).

Multiple ROIs on an image - of any/all types:

If further ROIs are added to an image they then appear to act as a single unit:
- select single ROI - add tag - tag is added to all ROIs on the image
- tags deleted from one ROI are deleted from all ROIs - even if tag originally added to ROI when it was a single ROI (before multiple ROIs added) and tag was added separately
- multi-select ROIs and add tag and delete tag - behaves as expected

Also noted:
- text ROI added and comment saved
- add tag to text ROI
- tag and comment are then visible when all ROIs on the image when selected in Manager tab
- if the image is used to select the other ROIs then the comment does not appear in the Inspector (i.e. suspect a refresh issue)

Very difficult to work out exactly what the pattern of errors is here, may become clearer as debugging proceeds.

screenshot 1

**Comment by jburel** [comment]
@gusferguson: Thanks I will investigate the issues

**Comment by jburel** [comment]
@gusferguson:
currently tagging of ROIs is not allowed (we decided to allow tag the shapes) but to be consistent with the other options like delete/duplicate etc.
If the roi is selected and we wish to tag, all shapes will have the tags associated to it.

**Comment by gusferguson** [comment]
@jburel 

Tested using OMERO.insight-5.2.0-m0-417-5513811-ice35-b63-mac eel user-3 read-only-1

Noted that when ROI selected (not shape) - no information appears in Inspector tab

Add single rectangle to plane
- add tag - warning ROI not saved
- save ROI - then add tag successfully 
- visible in Inspector
- as expected

Propagate shape to other planes
- save
- select ROI (not shapes) add tag - existing tags shown in tag dialogue - add tags
- appears to succeed
- no tags visible in Inspector

Add tags individually to single shapes (rectangle and elipse)
- works as expected
- tags show in Inspector
- multiple tags to single shape works as expected

Multiselect shapes (elipse)
- add tags
- not shown in inspector

Create text shape
- save
- add existing tag
- not visible in inspector
- add new tag
- not visible in inspector
- new tag not visible in tag dialogue (i.e. never created)
- no error message

Propagate shape to other planes (rectangle)
- did not save
- select ROI (not shapes) add tag - no existing tags shown in tag dialogue - previously applied tag not visible on left or right side - create new tag and add - fatal crash

Stopped testing there for this round.

Error message:
java.lang.Exception: Abnormal termination due to an uncaught exception.
java.lang.NullPointerException
    at org.openmicroscopy.shoola.agents.measurement.view.MeasurementViewerComponent.setROIAnnotations(MeasurementViewerComponent.java:1149)
    at org.openmicroscopy.shoola.agents.measurement.ROIAnnotationLoader.handleResult(ROIAnnotationLoader.java:93)
    at org.openmicroscopy.shoola.env.data.events.DSCallAdapter.eventFired(DSCallAdapter.java:90)
    at org.openmicroscopy.shoola.env.data.views.BatchCallMonitor$1.run(BatchCallMonitor.java:124)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Abnormal termination due to an uncaught exception.
java.lang.NullPointerException
    at org.openmicroscopy.shoola.agents.measurement.view.MeasurementViewerComponent.setROIAnnotations(MeasurementViewerComponent.java:1149)
    at org.openmicroscopy.shoola.agents.measurement.ROIAnnotationLoader.handleResult(ROIAnnotationLoader.java:93)
    at org.openmicroscopy.shoola.env.data.events.DSCallAdapter.eventFired(DSCallAdapter.java:90)
    at org.openmicroscopy.shoola.env.data.views.BatchCallMonitor$1.run(BatchCallMonitor.java:124)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0"

    at org.openmicroscopy.shoola.env.ui.UserNotifierImpl.showErrorDialog(UserNotifierImpl.java:191)
    at org.openmicroscopy.shoola.env.ui.UserNotifierImpl.notifyError(UserNotifierImpl.java:291)
    at org.openmicroscopy.shoola.env.AbnormalExitHandler.doTermination(AbnormalExitHandler.java:147)
    at org.openmicroscopy.shoola.env.AbnormalExitHandler.terminate(AbnormalExitHandler.java:85)
    at org.openmicroscopy.shoola.env.RootThreadGroup.uncaughtException(RootThreadGroup.java:69)
    at java.awt.EventDispatchThread.processException(EventDispatchThread.java:223)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:215)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by gusferguson** [comment]
@jburel 
Using image ID: 23053
Double checking adding tags to ROIs rather than shapes.
- add rectangular ROI
- save
- propagate to 6 planes
- save
- add tag to ROI - appears successful
- click on inspector - ROI still selected - see details as if for shape - tag added
- select shape - click on inspector - details as expected - tag added
- tags on all shapes as expected
- select ROI - click on inspector - blank as expected

Save and add elipse and save
- close viewer
- reopen image in viewer
- rectangle shows on image - eclipse not visible on image (this is intermittent - appears sometimes when rectangle selected)
- rectangle is visible in manager and expanded with previously selected shape still selected
- select elipse in manager - shape in rectangle remains selected
- select shape in eclipse
- add multiple tags
- fail to add - not visible in inspector 
- add tag again - tags still in LHP of tag dialog - none in RHP
- check rectangle - tags disappeared from shapes.

Did more selection and deselection
- checked shapes in rectangle again - now have the multiple tags added to elipse on them.

Very difficult to work out what is happening.

**Comment by jburel** [comment]
@gusferguson: I figured out why annotations show up and sometimes do not... Now need to fix it ;-)

**Comment by gusferguson** [comment]
@jburel 

Tested using OMERO.insight-5.2.0-m0-479-f740b93-ice35-b65-mac user-3 read-only 1
Images: ID: 23056

Draw rectangular ROI on 1 Z and T
- select ROI
- add tag
- click on Inspector tab - see information for shape not ROI i.e. not blank as expected
- select shape - Inspector tab shows expected information
- select ROI again - Inspector tab blank - as expected
- appears to be refresh issue

With existing shape - already tagged
- propagate ROI to Z and T planes
- shape propagated successfully
- all new shapes have tag attached
- as expected.

Create new ROI - ellipse
- propagate shape to Z and T
- add tag to 1 shape
- Inspector tab as expected
- tag only added to single selected shape
- multiselect shapes - add tag
- tags on all shapes - as expected
- add multiple tags to single and multi-selected shapes - successful
- behaves as expected

Created text ROI
- tag added
- tag and comment remain in correct fields
- no weirdness with other ROIs
- tagging of text ROIs as such now behaving as expected

Removing tags from ROIs works as expected.

Noticed quite a bit of lag selecting shapes - accessing from home but a lot of performance fall off as more shapes and tags added.
A slight lag occurs with un-annotated ROIs as their numbers increase.
Comparing similar numbers of propagated ROIs with no tags attached and tags attached - I estimate the tags are more than doubling the performance lag.

May be time to get @pwalczysko to start tearing it apart as well.

**Comment by jburel** [comment]
@gusferguson: Thanks for the report. It seems that the general weirdness has been fixed.
I think I can improve the tagging refresh a bit.
Adding tags to rois implies that we need an extra call to load the annotations,

**Comment by jburel** [comment]
removing exclude label. conflicts have now been fixed.

**Comment by jburel** [comment]
@gusferguson: I will probably do the performance improvement in a follow up PR, mainly to avoid further 
conflicts
Are you happy with the functionalities?

**Comment by gusferguson** [comment]
@jburel - yes - happy with functionalities.
Good to merge from that POV.

**Comment by sbesson** [comment]
Note this is causing new Javadoc warnings

```
Standard Doclet version 1.8.0_51
Building tree for all the packages and classes...
/opt/hudson/workspace/OMERO-DEV-merge-build/src/components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/Editor.java:297: warning - @param argument "file" is not a parameter name.
/opt/hudson/workspace/OMERO-DEV-merge-build/src/components/insight/SRC/org/openmicroscopy/shoola/env/data/OmeroMetadataService.java:770: warning - @return tag cannot be used in method with void return type.
/opt/hudson/workspace/OMERO-DEV-merge-build/src/components/insight/SRC/org/openmicroscopy/shoola/env/data/views/calls/ArchivedImageLoader.java:225: warning - @param argument "imageID" is not a parameter name.
/opt/hudson/workspace/OMERO-DEV-merge-build/src/components/insight/SRC/org/openmicroscopy/shoola/env/data/views/calls/ArchivedImageLoader.java:225: warning - @param argument "name" is not a parameter name.
/opt/hudson/workspace/OMERO-DEV-merge-build/src/components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/ROITable.java:840: warning - Tag @see: can't find loadTag() in org.openmicroscopy.shoola.agents.measurement.util.roitable.ROIActionController
/opt/hudson/workspace/OMERO-DEV-merge-build/src/components/insight/SRC/org/openmicroscopy/shoola/util/roi/model/ROIShape.java:181: warning - @return tag cannot be used in method with void return type.
```

See https://ci.openmicroscopy.org/view/DEV/job/OMERO-DEV-merge-build/ICE=3.5,jdk=8_LATEST,label=octopus/77/consoleText

**Comment by jburel** [comment]
2 warnings are not related to this PR
* Editor
* ArchivedImageLoader

**Comment by jburel** [comment]
--no-rebase

**Pull request merged**
