### PR TITLE
add useful log config line to change for graphs debugging

### PR DESCRIPTION
**Pull request by mtbc**
Makes it easier to edit, whenever I want to turn on graphs debugging. Doesn't change current log level.

--no-rebase

### CODE REVIEW

**Comment by rleigh-dundee** [comment]
This looks trivially correct given that it's a simple one line config change!

**Comment by rleigh-dundee** [comment]
Works fine for me.  Please merge.

**Comment by mtbc** [comment]
Thank you! Want a look at https://github.com/openmicroscopy/ome-documentation/pull/1064 while you're at it? (-:

**Comment by mtbc** [comment]
Thanks. :smiley:

**Pull request merged**
