### PR TITLE
Travis update

### PR DESCRIPTION
**Pull request by jburel**
# What this PR does

Use trusty to build 
This is necessary to build with newer version of pytables
and newer version of ice

 * building using ``ant`` fails all the time, need to use ``./build.py``.
 * installation of python dependencies needs to be explicitly done via
``sudo apt-get`` during ``before_install:`` otherwise the dependencies will not be available to the container. This means that the python tests will fail with for example ``No module Ice``. Change ``sudo`` option to ``required``. I did not notice an increase in the build time with that change.  See https://github.com/travis-ci/travis-ci/issues/8048
 * update ``numexpr`` via pip to avoid some table test failure  e.g.
``test/unit/tablestest/test_servants.py:349:`` will fail with ``ValueError: Using `oa_ndim == 0` when `op_axes` is NULL. Use `oa_ndim == -1` or the MultiNew iterator for NumPy <1.8 compatibility``

# Testing this PR
Check that travis is green

See https://trello.com/c/gVsUkLH8/100-travis-upgrade

### CODE REVIEW

**Comment by rleigh-codelibre** [comment]
Looks generally OK.

I'm uncertain that sudo is required.  Every package you are installing is in the trusty whitelist (https://github.com/travis-ci/apt-package-whitelist) because I requested them months ago and they have been available for a while now.

Did you find what build.py is doing which makes a difference?  It's not related to sudo builds being run on different VMs?

**Comment by jburel** [comment]
without ``sudo: required`` it is not possible to install the python dependencies in ``before_install`` step.
When https://github.com/travis-ci/travis-ci/issues/8048 is resolved we will probably have to revisit. Note that using ``group:edge`` as suggested in issue did not work

**Comment by jburel** [comment]
@rleigh-codelibre works now with ant. Still unclear why it was not before (without explicit error it is tricky to figure error)

**Comment by jburel** [comment]
@sbesson comment added to this PR too

**Comment by jburel** [comment]
--rebased-to #5447

**Pull request merged**
