### PR TITLE
Upgrade settings toplinks

### PR DESCRIPTION
**Pull request by will-moore**
This was previously opened as #3579.

To test:
 - BEFORE building with this PR, set top_links to have a single link, E.g.
```
$ bin/omero config set omero.web.ui.top_links '[["Test", "www.ome.org"]]'
```
 - Webclient should only show a single 'Test' link in header.
 - Now upgrade / build with this PR and start OMERO.
 - Should see "Data", "History", "Help", "Test" links at top of webclient.
 - restart the server again and check that more links are not added!
 - Open dist/etc/grid/config.xml and check for 2 version blocks that state "5.1.0" (under 2 different ```<properties>``` blocks)

```
<property name="omero.config.version" value="5.1.0" />
```

Tests should also pass:
```
$ cd OmeroPy
$ ./setup.py test -t test/unit/test_config.py
```

--no-rebase

### CODE REVIEW

**Comment by joshmoore** [comment]
```
./components/tools/OmeroPy/test/unit/test_config.py:301:5: E303 too many blank lines (2)
```

**Comment by manics** [comment]
Does this mean we should have a follow-up PR to handle deprecated settings? https://github.com/openmicroscopy/openmicroscopy/blob/12528d24feeb269b4306c738c9437129e59729aa/components/tools/OmeroWeb/omeroweb/settings.py#L590

**Comment by will-moore** [comment]
@manics I don't think anything is being deprecated as part of this PR. I'm not sure if those ``` DEPRECATED_SETTINGS_MAPPINGS  ``` need cleaning up or are there to stay @aleksandra-tarkowska?

**Comment by manics** [comment]
@will-moore more a general question, since you've gone to the trouble of upgrading the config could we also update deprecated config names?

**Comment by pwalczysko** [comment]
@will-moore : The workflow does not work for me. The ``config.xml`` file you have sent me includes also the particulars of the ``omero.data.dir`` and the DB name which are crucial for starting the server. When I realized that my server will not start, I tried to change these values in the config.xml you delivered.

BUT to my surprise, after I have started my 5.1 server with this PR included, I ended up with the whole paragraph in the ``config.xml`` doubled. The newly added paragraph had a nicely changed 5.1 instead of the original 4.2, but also it did have the original values for the DB and omero.data.dir -> my server did not start again.

**Comment by pwalczysko** [comment]
It is kind of working. But as @will-moore says, it probably needs some more trained eye on the ``config.xml`` behaviour. I had expected behaviour with the top links, but the ``config.xml`` behaviour is something which I do not fully follow. not sure about some ``default`` and ``active`` and thus I ended up doing ``bin/omero config .... (db and pixeldata folder)`` - where is the beauty of the ``config.xml`` -copy-from-old workflow ?

**Comment by will-moore** [comment]
@joshmoore It would be good if you could review these changes since this is the first change in config.xml VERSION since 4.2.1 and I'm not sure of the strategy for updating it in the future. Thanks

**Comment by joshmoore** [comment]
```
$ diff Old-formated.xml Config-formated.xml
5c5
<       This file was generated at Thu Mar 12 22:52:31 2015 by the OmeroConfig system.
---
>       This file was generated at Fri Mar 13 08:37:26 2015 by the OmeroConfig system.
27a28
>     <property name="omero.web.ui.top_links" value="[[&quot;Test&quot;, &quot;www.ome.org&quot;]]"/>
45a47
>     <property name="omero.web.ui.top_links" value="[[&quot;Test&quot;, &quot;www.ome.org&quot;]]"/>
```

```
$ diff Config-formated.xml Upgrade-formated.xml
5c5
<       This file was generated at Fri Mar 13 08:37:26 2015 by the OmeroConfig system.
---
>       This file was generated at Fri Mar 13 08:38:06 2015 by the OmeroConfig system.
12c12
<     <property name="omero.config.version" value="4.2.1"/>
---
>     <property name="omero.config.version" value="5.1.0"/>
28c28
<     <property name="omero.web.ui.top_links" value="[[&quot;Test&quot;, &quot;www.ome.org&quot;]]"/>
---
>     <property name="omero.web.ui.top_links" value="[[&quot;Data&quot;, &quot;webindex&quot;, {&quot;title&quot;: &quot;Browse Data via Projects, Tags etc&quot;}], [&quot;History&quot;, &quot;history&quot;, {&quot;title&quot;: &quot;History&quot;}], [&quot;Help&quot;, &quot;http://help.openmicroscopy.org/&quot;, {&quot;target&quot;: &quot;new&quot;, &quot;title&quot;: &quot;Open OMERO user guide in a new tab&quot;}], [&quot;Test&quot;, &quot;www.ome.org&quot;]]"/>
31c31
<     <property name="omero.config.version" value="4.2.1"/>
---
>     <property name="omero.config.version" value="5.1.0"/>
47c47
<     <property name="omero.web.ui.top_links" value="[[&quot;Test&quot;, &quot;www.ome.org&quot;]]"/>
---
>     <property name="omero.web.ui.top_links" value="[[&quot;Data&quot;, &quot;webindex&quot;, {&quot;title&quot;: &quot;Browse Data via Projects, Tags etc&quot;}], [&quot;History&quot;, &quot;history&quot;, {&quot;title&quot;: &quot;History&quot;}], [&quot;Help&quot;, &quot;http://help.openmicroscopy.org/&quot;, {&quot;target&quot;: &quot;new&quot;, &quot;title&quot;: &quot;Open OMERO user guide in a new tab&quot;}], [&quot;Test&quot;, &quot;www.ome.org&quot;]]"/>
```

screen shot 2015-03-13 at 08 47 19

Looks good to me.

**Comment by joshmoore** [comment]
Merging. @aleksandra-tarkowska / @manics : if we want to discuss and open up a follow-up PR, :+1: At this point it should be easy to extend/adapt what @will-moore has already done.

**Pull request merged**
