### PR TITLE
Viewer compression dev 5 0

### PR DESCRIPTION
**Pull request by jburel**
Make sure the correct compression level is used when opening the viewer

To test the PR
 * Open an image. Modify the compression level e.g. set it to high
 * Close the viewer
 * Open another image, Modify the compression level e.g. to none. Check that the image is updated.

PR opened following discussion on https://github.com/openmicroscopy/openmicroscopy/pull/3366
Likely to conflict with https://github.com/openmicroscopy/openmicroscopy/pull/3378

cc @pwalczysko

### CODE REVIEW

**Comment by jburel** [comment]
--rebased-from #3369

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.0-merge-push#316](http://ci.openmicroscopy.org/job/OME-5.0-merge-push/316/). See the [console output](http://ci.openmicroscopy.org/job/OME-5.0-merge-push/316/consoleText) for more details.
Possible conflicts:
  - PR #3378 dominikl 'Backported UI support for float images'
    - components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/rnd/RendererModel.java

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.0-merge-push#317](http://ci.openmicroscopy.org/job/OME-5.0-merge-push/317/). See the [console output](http://ci.openmicroscopy.org/job/OME-5.0-merge-push/317/consoleText) for more details.
Possible conflicts:
  - PR #3378 dominikl 'Backported UI support for float images'
    - components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/rnd/RendererModel.java

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.0-merge-push#318](http://ci.openmicroscopy.org/job/OME-5.0-merge-push/318/). See the [console output](http://ci.openmicroscopy.org/job/OME-5.0-merge-push/318/consoleText) for more details.
Possible conflicts:
  - PR #3378 dominikl 'Backported UI support for float images'
    - components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/rnd/RendererModel.java

**Comment by pwalczysko** [comment]
The image from ``team/will/float-data.zip/wt_g21A2_bin3-ali.mrc`` is still a bit slow, but opens fine in both full viewer and Preview. Interestingly, when I changed the rendering from completely white (in appearance) to the original-one-like, and closed and reopened Insight, the image needed less than a second to render in full viewer and Preview. 

All fine here. 
Ready to merge.

**Pull request merged**
