### PR TITLE
Tables new API

### PR DESCRIPTION
**Pull request by joshmoore**
# What this PR does

Deprecate usage of the old PyTables API

Table creation and manipulation tested with the following version of pytables:

* 3.3.0 (Debian9)
* 3.2.x (Ubuntu16.04, CentOS 7)
* 3.1.x (ubuntu 14.04)

# Testing this PR

check that the integration tests and training examples are green

# Related reading

 * https://trello.com/c/l2UuwAee/74-tables-failure-on-debian-9-pytables-330
 * Replaces https://github.com/openmicroscopy/openmicroscopy/pull/5407

--depends-on #5409

### CODE REVIEW

**Comment by dominikl** [comment]
Will that also be available in the Java `omero.grid.TablePrx` ? Wanted to add some update methods to the gateway `TablesFacility` but couldn't find methods to add/delete rows/columns. `incr` and `decr` added with this PR seems to do that, right?

**Comment by joshmoore** [comment]
> Will that also be available in the Java omero.grid.TablePrx ?

@dominikl : no, these are only backend changes.

> add/delete rows/columns. incr and decr added with this PR seems to do that, right?

The methods weren't really added, only refactored from elsewhere. Their function is to maintain a counter of how often the file itself was opened, as opposed to column management. In general, PyTables doesn't easily provide column addition/removal. It requires recreating the file.

**Comment by will-moore** [comment]
Tests not passing yet... https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-merge-integration-python/675/testReport/junit/OmeroPy.test.integration.tablestest.test_service/

**Comment by joshmoore** [comment]
`merge-integration` is still running.

**Comment by mtbc** [comment]
```shell
$ pip freeze | grep tables
tables==3.3.0
```

With Java integration tests on a Debian 9 system I am having some trouble with `TableTest` and `TablesFacilityTest`, though they passed fine on octopus. TestNG output is on squig in `ome/team/mtbcarroll/PR-5481/index.html`. Ping me if you'd like to log into the VM where this ran so you can check its config; I may have just screwed something simple up.

**Comment by joshmoore** [comment]
Thanks, @mtbc. Things I see:

 * [x] `AttributeError: 'Table' object has no attribute 'getWhereList` - should be fixed here
 * [x] `AttributeError: 'Table' object has no attribute 'readCoordinates` - should be fixed here
 * [x] `TypeError: shape must be an integer or sequence: 4L` - perhaps https://github.com/PyTables/PyTables/issues/598#issuecomment-274154131, can you try upgrading, @mtbc ?

**Comment by mtbc** [comment]
Yes, if I upgrade to 3.4.2 then the `TablesFacilityTest` failure becomes another `getWhereList` one.

**Comment by mtbc** [comment]
(It's a pity that even Debian unstable is on tables 3.3.0 but I need to fiddle versions of other things anyway because Debian 9's packaged django stuff is too new for web.)

**Comment by jburel** [comment]
what are the issues with Django? Probably worth a card

**Comment by mtbc** [comment]
I don't know but have now created https://trello.com/c/GN2e5t9C/245-omeroweb-with-newer-django.

**Comment by jburel** [comment]
Comment added to card

**Comment by mtbc** [comment]
Taking a look at this, I've some confusion in that there are *also* `omero::grid::Table` methods `getWhereList` and `readCoordinates` in our API as listed at http://downloads.openmicroscopy.org/omero/5.4.0-m3/api/slice2html/omero/grid/Table.html and I doubt that I can rely on static checks to determine which kind of table is being called from where.

**Comment by jburel** [comment]
I have removed the exclude label.
Conflict will need to be fixed so it can be included in the build

**Comment by joshmoore** [comment]
Cherry-picked the commit from gh-5512 since they were conflicting. I think this is ready for inclusion. (Though we may need to document non-working versions of PyTables. cc: @mtbc)

**Comment by jburel** [comment]
I added  a comment while working on doc 
see https://github.com/openmicroscopy/ome-documentation/pull/1739/files#diff-4f1690607b26288b56afc5164c52dce0
Do we want something else?

**Comment by mtbc** [comment]
```
===============================================
OmeroJava.integration
Total tests run: 2391, Failures: 0, Skips: 0
===============================================

BUILD SUCCESSFUL
Total time: 66 minutes 46 seconds
mtbc@mtbc-pr-5481:~/openmicroscopy$ pip freeze | grep tables
tables==3.4.2
mtbc@mtbc-pr-5481:~/openmicroscopy$ git log -1
commit 09a2aad8468d3d7ddee152938c2ea356aa506267
Merge: 1537f5a708 bb8a484334
Author: Mark Carroll <M.T.B.Carroll@Dundee.ac.uk>
Date:   Wed Sep 20 09:27:32 2017 +0000

    Merge remote-tracking branch 'origin/pr/5481' into HEAD
mtbc@mtbc-pr-5481:~/openmicroscopy$ 
```

Earlier issue now fixed. :+1:

**Comment by jburel** [comment]
Did you install tables from pypi?
Have you tried with the "default" version on debian 9 (3.3)
I reckon it should work too

**Comment by mtbc** [comment]
I installed with `pip install tables` because I thought 3.3.0 would run into the `TypeError` at https://github.com/openmicroscopy/openmicroscopy/pull/5481#issuecomment-327146888 as at https://github.com/PyTables/PyTables/issues/598#issuecomment-274154131.

**Comment by joshmoore** [comment]
The `TypeError: shape must be an integer or sequence: 4L` issue is definitely PyTables-specific and not related to this PR.

**Comment by jburel** [comment]
in this the case we will have to indicate that 3.3 is not working in the doc.
summary is: it works on 3.1, 3.2, 3.4 but not 3.3. (default on Debian 9)

This will require also an ome-install PR so it can be reflected in the installation doc

**Comment by mtbc** [comment]
Yes, to confirm,

```
mtbc@mtbc-pr-5481:~/openmicroscopy$ ./build.py -f components/tools/OmeroJava/build.xml test -DTEST=integration/gateway/TablesFacilityTest
...
                        TypeError: shape must be an integer or sequence: 4L
...
Exception in thread "TestNGInvoker-testAddTable()"
===============================================
Ant suite
Total tests run: 8, Failures: 1, Skips: 6
===============================================
```

```
mtbc@mtbc-pr-5481:~/openmicroscopy$ pip freeze | grep tables
tables==3.3.0
mtbc@mtbc-pr-5481:~/openmicroscopy$ dpkg --status python-tables | grep ^Version
Version: 3.3.0-5
mtbc@mtbc-pr-5481:~/openmicroscopy$ 
```

**Comment by jburel** [comment]
omero-install PR https://github.com/ome/omero-install/pull/169

**Comment by jburel** [comment]
doc PR https://github.com/openmicroscopy/ome-documentation/pull/1771

**Comment by jburel** [comment]
i will check the tests tomorrow but it seems that it will be good to merge
I have opened two PR to fix the doc (installation and troubleshooting)

**Comment by jburel** [comment]
No table failure 
merging

**Pull request merged**
