### PR TITLE
Chgrp unlink warning 12965 develop

### PR DESCRIPTION
**Pull request by will-moore**
Rebased from #4165:

---------------------------

See: http://trac.openmicroscopy.org/ome/ticket/12965
Webclient warns when you will lose lined annotations or child objects during chgrp.

Test setup:
 - Add a bunch of annotations to P/D/I S/P/W - including some which ARE expected to chgrp with the data (Comments, MapAnnotations etc) and some of which are NOT expected to chgrp with the data, e.g. Tags, Multi-linked Files, Comments.
 - Also put some images in multiple Datasets (so that when you chgrp one Dataset, some images will be left behind).
 - Also, perform an image projection or Images_From_ROIs script or Channel_Offsets script so that some images will give an error on chgrp.
 - Also, find a Multi-Image Fileset.

 To test, try chgrp with different selections of your P/D/I S/PW data and you should be warned if:
 - You try to move a P/D/S that will not include some child data (E.g. if images in multiple Datasets - you will get a message showing the number of Images, and a tool-tip of all their names) - see screenshot.
 - Your chgrp will lose annotations from the Data - warning will name the tags and files and will simply number the Comments and any Others.
 - Trying to split a MIF, you will see the existing warning and have the "Move All" button. The warning of lost annotations etc should apply to ALL the images in the Fileset (not just the ones you chose to move).
 - If you try to move an image that has been projected etc, you should see a warning with suitable links to the images in question and the "OK" button will be hidden.
 - Finally, test single Dataset in 2 Projects - try to Move 1 of the Projects - see if message displays as expected (only 1 Project will move).

screen shot 2015-09-14 at 17 13 45

screen shot 2015-09-15 at 10 42 06

### CODE REVIEW

**Comment by sbesson** [comment]
--rebased-from #4165

**Comment by pwalczysko** [comment]
I am just finding out that ROIs are not listed (not even in Others). I have

screen shot 2015-09-29 at 11 24 36

**Comment by pwalczysko** [comment]
Bug: ``Move All`` button does nothing - no reaction, although the MIF workflow is initiated properly by selecting a part of the MIF. The Cancel button works fine. No crashes. No errors thrown.

**Comment by pwalczysko** [comment]
Double-checked that the ``Move All`` blocker https://github.com/openmicroscopy/openmicroscopy/pull/4222#issuecomment-144024975 is not present in 5.1 - just 5.2 specific.

**Comment by pwalczysko** [comment]
In summary, a blocker found https://github.com/openmicroscopy/openmicroscopy/pull/4222#issuecomment-144024975 - because of this, the MIF workflow has to be retested once this is fixed. The ROI issue is not solved in 5.1 either, and as this is a rebase, I would not hold the PR just for the ROIs - maybe investigate this possibility after this PR is merged.

**Comment by pwalczysko** [comment]
Additional info: Note that the ``Move All`` workflows were tested during the jstree testing. This means that https://github.com/openmicroscopy/openmicroscopy/pull/4222#issuecomment-144024975 must have appeared between then and now.

**Comment by pwalczysko** [comment]
The ``Move All`` button works fine now. The MIF workflow works fine as well.
Ready to merge.

**Pull request merged**
