### PR TITLE
TRIAL OMERO.web requirements

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
# What this PR does

This PR improve requirement files and help deploying  OMERO.web using virtualenv.

This PR is self tested by **CI-JOB https://ci.openmicroscopy.org/job/WEB-DEV-trial-deploy/**

# Testing this PR

```
$ mkdir test
$ cd test
$ virtualenv venvweb
$ source venvweb/bin/activate
(venvweb) $ pip install omego 
(venvweb) $ omego download --ice 3.6 --branch OMERO-DEV-merge-build py
(venvweb) $ mv OMERO.py[currentversion] OMERO.py
(venvweb) $ pip install -r OMERO.py/share/web/requirements-py27-trial.txt

(venvweb) $ pip install git+git://github.com/aleksandra-tarkowska/figure.git@pip_installer
(venvweb) $ OMERO.py/bin/omero config append omero.web.apps '"figure"'
(venvweb) $ OMERO.py/bin/omero config append omero.web.ui.top_links '["Figure", "figure_index", {"title": "Open Figure in new tab", "target": "figure"}]' 

(venvweb) $ pip install git+git://github.com/aleksandra-tarkowska/weberror.git@pip_installer
(venvweb) $ OMERO.py/bin/omero config append omero.web.apps '"weberror"'

(venvweb) $ OMERO.py/bin/omero web start
```

then generate nginx config and reload. Web should operate as normal

Full doc in http://www.openmicroscopy.org/site/support/omero5.3-staging/sysadmins/unix/install-web/install-web-trial.html

Check also walkthrough http://www.openmicroscopy.org/site/support/omero5.3-staging/sysadmins/unix/install-web.html

**To install webapp follow https://github.com/ome/figure/pull/168#issuecomment-244380054**

---

For more details see omeroweb-install in https://github.com/ome/omeroweb-install and travis https://travis-ci.org/ome/omeroweb-install/builds

### CODE REVIEW

**Comment by joshmoore** [comment]
Ready for rebase. Do you want to try omero-marshal and PyYAML here or do that in a follow-up?

**Comment by aleksandra-tarkowska** [comment]
sure I will add them too

**Comment by joshmoore** [comment]
See also
https://trello.com/c/6ffKXuPH/101-add-omero-marshal-to-requirements-file

**Comment by aleksandra-tarkowska** [comment]
@joshmoore rebased due to windows removal https://github.com/openmicroscopy/openmicroscopy/pull/4782

**Comment by jburel** [comment]
With a potential (likely) 5.2.6, opportunity to indicate that Apache is "deprecated".
https://trello.com/c/s3Dp1Zs5/4-apache-deprecation

**Comment by joshmoore** [comment]
What needs to happen to bring this out of breaking?

**Comment by aleksandra-tarkowska** [comment]
If no objections I could start moving https://ci.openmicroscopy.org/view/Web/job/WEB-DEV-trial-deploy/ to existing spider web

**Comment by aleksandra-tarkowska** [comment]
@joshmoore @jburel @sbesson my apology but I think I got a bit confused with what I would like to go into m4. Initially this PR would be good to have in m4 as the doc PR was already merged. Initial discussion diverted directly to drop TRIAL, that I personally wasn't after. We can decide in the next iteration if we wish to drop trial or not, but at the moment I would keep it as it is and get that in for m4, if no objections

**Comment by aleksandra-tarkowska** [comment]
apache changes removed I will open another PR to simplify rebasing for 5.2.6

**Comment by aleksandra-tarkowska** [comment]
This is now on merge

**Comment by ximenesuk** [comment]
Does the testing scenario require Ice 3.6?

**Comment by ximenesuk** [comment]
It looks like it does, in which case I am going to have to pass on testing this.

**Comment by aleksandra-tarkowska** [comment]
@ximenesuk sorry I don;t understand your comment. You need to pip install IcePy in virtualenv in isolation. This doesnt matter what is already installed on the machine. THAT IS THE WHOLE PURPOSE of that PR!

**Comment by ximenesuk** [comment]
@aleksandra-tarkowska 

```
...
(venweb)ls30778:test colin$ OMERO.py/bin/omero config append omero.web.apps '"figure"'
Traceback (most recent call last):
  File "OMERO.py/bin/omero", line 97, in <module>
    import omero.cli
  File "/Users/colin/Work/test/OMERO.py/lib/python/omero/__init__.py", line 43, in <module>
    raise Exception(msg)
Exception:

        ERROR: Ice version mismatch!

        Your OMERO code has been compiled using Ice version 3.6.2
        but you seem to have Ice version 3.5.1 installed. If you need
        help understanding this issue, please send this error message
        to the OME community:

        http://www.openmicroscopy.org/site/community

        Debugging Info:
        --------------
        VERSION=5.3.0-m3-210-be6b074-ice36-b425
        PYTHONPATH=/Users/colin/Work/test/OMERO.py/lib/python:/Users/colin/Work/test/OMERO.py/var/lib:/Users/colin/Work/test/OMERO.py/bin:/Users/colin/Work/repos/openmicroscopy/dist/lib/python:/usr/local/opt/zeroc-ice35/lib/python2.7/site-packages:/Users/colin/Work/repos/openmicroscopy/components/tests/python:/Users/colin/Work/test/venweb/lib/python27.zip:/Users/colin/Work/test/venweb/lib/python2.7:/Users/colin/Work/test/venweb/lib/python2.7/plat-darwin:/Users/colin/Work/test/venweb/lib/python2.7/plat-mac:/Users/colin/Work/test/venweb/lib/python2.7/plat-mac/lib-scriptpackages:/Users/colin/Work/test/venweb/Extras/lib/python:/Users/colin/Work/test/venweb/lib/python2.7/lib-tk:/Users/colin/Work/test/venweb/lib/python2.7/lib-old:/Users/colin/Work/test/venweb/lib/python2.7/lib-dynload:/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7:/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin:/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk:/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac:/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages:/Users/colin/Work/test/venweb/lib/python2.7/site-packages:/Users/colin/Work/test/OMERO.py/lib/fallback
```

**Comment by aleksandra-tarkowska** [comment]
Why your PYTHONPATh contains `/Users/colin/Work/repos/openmicroscopy/dist/lib/python` ?

**Comment by ximenesuk** [comment]
My PYTHONPATH contains that because it does. I will retest in a fresh terminal with the path unset.

**Comment by mtbc** [comment]
Something to note in docs though? Not everybody may be doing this on a pristine machine.

**Comment by ximenesuk** [comment]
With `PYTHONPATH` unset locally the scenario runs okay without any problem. I have not tested the steps below the scenario as I don't have `nginx` installed.

The docs look okay though I don't follow the config adjustment at http://www.openmicroscopy.org/site/support/omero5.3-staging/sysadmins/unix/install-web/install-web-trial.html#nginx-configuration Is this mean to be something that has to be adjusted in the generated file? Or elsewhere? Maybe this makes much more sense to someone familiar with `nginx`?

**Comment by aleksandra-tarkowska** [comment]
> Please provide what is in your PYTHONPATH, PATH, version of virtualenv and pip

Without answering my question above it is hard to say how your env look like.

Cowfish gives a flavour of real server and has Ice3.5 installed globally, we are running multiple integration servers 

```
$ ls -al /opt/hudson/workspace/ | grep OMERO
drwxrwxr-x  4 hudson hudson 4096 Sep 12 05:06 OMERO-DEV-breaking-integration-Python27
drwxrwxr-x  5 hudson hudson 4096 Sep  6 11:52 OMERO-DEV-merge-docs-autogen-omeroweb
drwxrwxr-x  4 hudson hudson 4096 Sep 12 03:45 OMERO-DEV-merge-integration-Python27
drwxrwxr-x  4 hudson hudson 4096 Sep 12 04:29 OMERO-DEV-Python27-merge-deploy
```

and Trial job is run in isolation 

```
+ virtualenv /opt/hudson/workspace/WEB-DEV-trial-deploy/trial-venv
New python executable in /opt/hudson/workspace/WEB-DEV-trial-deploy/trial-venv/bin/python
Installing Setuptools..............................................................................................................................................................................................................................done.
Installing Pip.....................................................................................................................................................................................................................................................................................................................................done.
+ source /opt/hudson/workspace/WEB-DEV-trial-deploy/trial-venv/bin/activate
...
++ VIRTUAL_ENV=/opt/hudson/workspace/WEB-DEV-trial-deploy/trial-venv
++ export VIRTUAL_ENV
++ _OLD_VIRTUAL_PATH=/opt/cmake/bin:/usr/local/bin:/usr/bin:/opt/texlive/2015/bin/x86_64-linux/
++ PATH=/opt/hudson/workspace/WEB-DEV-trial-deploy/trial-venv/bin:/opt/cmake/bin:/usr/local/bin:/usr/bin:/opt/texlive/2015/bin/x86_64-linux/

all the paths are set correctly.

**Comment by aleksandra-tarkowska** [comment]
@mtbc would be good to know whether `export $PATH=/path/to/OMERO.server/bin:$PATH` or any other manual manipulations affect virtualenv that we could put in the doc. At the moment I am not sure.

**Comment by ximenesuk** [comment]
@aleksandra-tarkowska 

```
ls30778:~ colin$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/bin:/usr/local/sbin:/Users/colin/bin:/Users/colin/Work/repos/openmicroscopy/dist/bin
ls30778:~ colin$ echo $PYTHONPATH
/Users/colin/Work/repos/openmicroscopy/dist/lib/python:/usr/local/opt/zeroc-ice35/lib/python2.7/site-packages/:/Users/colin/Work/repos/openmicroscopy/components/tests/python
ls30778:~ colin$ virtualenv --version
12.1.1
ls30778:~ colin$ pip --version
pip 8.1.2 from /Library/Python/2.7/site-packages (python 2.7)
```

**Comment by aleksandra-tarkowska** [comment]
@jburel https://trello.com/c/WkSDITRL/187-rfe-omero-added-to-path

**Comment by jburel** [comment]
@aleksandra-tarkowska Thanks for the card.

**Pull request merged**
