### PR TITLE
Matlab: add group support to create objects function

### PR DESCRIPTION
**Pull request by sbesson**
See https://trello.com/c/gSKqCAe2/49-omero-matlab-group-support

This PR:
- addresses some comments from https://github.com/openmicroscopy/openmicroscopy/pull/4136
- reviews the object creation functions `createXXX` and add group support to them
- improves the performance of the `createDataset/createPlate` function when linking to projects/screens by performing a single transaction instead of multiple
- extends the `WriteData` training example to cover the semantics of the `createXXX` functions and cover the annotation creation function with a group argument.

/cc @emilroz

### CODE REVIEW

**Comment by sbesson** [comment]
See https://ci.openmicroscopy.org/job/OMERO-5.1-merge-training/432/console

**Comment by imunro** [comment]
Passing non-existent Group IDs to CreateProject throws (a lot of)  java errors.

**Comment by sbesson** [comment]
Yes wrapping exceptions is captured  in https://trello.com/c/gSKqCAe2/49-omero-matlab-group-support. I will implement it across the board when all the functions have group support.

**Comment by imunro** [comment]
In https://github.com/sbesson/openmicroscopy/blob/matlab_create_objects_group/examples/Training/matlab/WriteData.m    there may to be a syntax error when writing comment annotations at e.g. line 230. The namespace needs to be in quotes 'ns' unless this is predefined somewhere but I can't find where this is done.

**Comment by sbesson** [comment]
@imunro: https://github.com/sbesson/openmicroscopy/blob/matlab_create_objects_group/examples/Training/matlab/WriteData.m#L27 ?

**Comment by imunro** [comment]
Thanks.

**Comment by imunro** [comment]
All tested and seem to work as intended. Comment changes look fine. Happy to merge. Only caveat is that , as before, disallowing the passing of group when any IDs are passed would seem to me desirable in order to simplify the API.

**Comment by sbesson** [comment]
@imunro: last of set of commits should:
- wrap server exceptions thrown by object creation functions, e.g.  `createProject(session, 'test', 'group', 1000);
- implement the API suggestion from https://github.com/openmicroscopy/ome-documentation/pull/1278#issuecomment-138988411, namely using the group context from the parent object when creating datasets/plates linked to projects/screens.

**Comment by sbesson** [comment]
See https://ci.openmicroscopy.org/view/Failing/job/OMERO-5.1-merge-training/434/consoleText

**Comment by imunro** [comment]
Re-tested  createDataset and createPlate passing any non-matching group (NB including -1)  throws an easily understood "Input group is different from the screen group." Much better.

**Comment by jburel** [comment]
``` in createPlate.m```
``` links it to the input screen. The group context is specified by the
   screen group.``` extra space before screen

**Comment by sbesson** [comment]
Pushed.

**Comment by jburel** [comment]
restarted travis

**Comment by jburel** [comment]
Merging that travis is green and minor comment fixed.

**Comment by sbesson** [comment]
--rebased-to #4160

**Pull request merged**
