### PR TITLE
travis fixes

### PR DESCRIPTION
**Pull request by mtbc**
Combines #5619 and #5620 as `--depends-on` no longer works.

### CODE REVIEW

**Comment by joshmoore** [comment]
`     [exec]         ERROR: Ice version mismatch!`

**Comment by mtbc** [comment]
Yes, no idea what that is; this PR fixes other issues. If there's a fixing commit elsewhere then happy to cherry-pick it.

**Comment by joshmoore** [comment]
Keeping this green has been a constant battle. Happy for this to go in without the Ice fix; I don't have one off-hand.

**Comment by sbesson** [comment]
Successfully tested locally while testing a change to `omero.properties`. Agreed it would be nice to restore Travis but the cost of doing it might simply be too high given the fact our next large goal will be to kill this custom branch.

**Pull request merged**
