### PR TITLE
Jnlp parameters

### PR DESCRIPTION
**Pull request by jburel**
Handle the parameters specified when using webstart
To test:
 * Log using the web client
 * Start insight from web
 * After the standard steps, insight splashscreen should only show the progress bar displayed when initializing the internal services. No username/password field
 * When completed, the application should automatically log in and the data manager should pop up.

cc @dominikl @aleksandra-tarkowska 
see gh-3810

### CODE REVIEW

**Comment by aleksandra-tarkowska** [comment]
@jburel Thanks for a quick progress. Looks like on trout is trying to connect to localhost

```
    <property name="jnlp.omero.host" value="localhost"/>
    <property name="jnlp.omero.port" value="4064"/>
    <property name="jnlp.omero.sessionid" value="8af2a5a8-6b88-48a5-9974-783c262f53b3"/>
```

I will need to review that why

**Comment by aleksandra-tarkowska** [comment]
This is because https://github.com/openmicroscopy/management_tools/blob/master/ci/config/OMERO-5.1-merge-deploy.omero Cannot sue localhost anymore

**Comment by jburel** [comment]
The last commits should:
 * hide username/password fields when a session is specified.
 * Show the fields and controls if the connection failed.
 * Display the server name specified via parameters

**Comment by joshmoore** [comment]
I haven't gotten the webstart version working yet, @jburel, but 2 questions:

 * if the session is missing/removed, will the user/password dialog reappear?
 * will testing via the CLI, e.g. by passing `-Djnlp.omero.host=....` be sufficient?

**Comment by jburel** [comment]
* If no session specified or if we fail to log in using the session idea. Then the "login fields" show up.
 * Currently reading values from System.property. If we want to specify parameters  then the code will have to be modified

**Comment by aleksandra-tarkowska** [comment]
@jburel looks like https://github.com/openmicroscopy/openmicroscopy/pull/3810#commits-pushed-6d0ae14 is working now ;-) Although I forgot to add omero.client.web.host to the jnlp, grrrr. Pushing that now

**Comment by aleksandra-tarkowska** [comment]
With the last commit insight can read web host from <property name="jnlp.omero.web.host" value="http://omero.testdomain.com:4080/"/>

**Comment by ximenesuk** [comment]
This works fine for me on my new Mac Java 8, Firefox. (On my old Mac there were too many security hurdles!) However, @mtbc seemed to have a problem so I'll let him comment here.

**Comment by mtbc** [comment]
Just as a data point, this has no effect for me on Linux with icedtea-web 1.5, I get the Insight login dialog as normal.

**Comment by jburel** [comment]
For @mtbc:
after further tests,
The host and port seem to be correctly passed but not the session id.
This results in failing to connect using the session id and in that case we fall back on login fields being displayed.

**Comment by mtbc** [comment]
I should mention, I had a surprise this morning: launched trout merge webstart (*not* from logged-in webclient), worked on trout a bit, went to switch user, and the host was "localhost" so I had to switch it back to trout. When I switched user a second time it stayed on trout.

**Comment by aleksandra-tarkowska** [comment]
Could you please try both options and open jnlp file to check exactly what was passed through. When you are logged in could you list active sessions on the server and check if session key is there?

**Comment by aleksandra-tarkowska** [comment]
Also which JVM you use?

**Comment by mtbc** [comment]
```
$ java -version
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.5) (7u79-2.5.5-1~deb8u1)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)
```

**Comment by aleksandra-tarkowska** [comment]
@jburel does it make sense to add debug mode in jnlp at some point? Could you give me some details wow that would work?

**Comment by mtbc** [comment]
Not logged in:
```
$ grep property insight.jnlp
    <property name="jnlp.omero.host" value="trout.openmicroscopy.org"/>
    <property name="jnlp.omero.port" value="4064"/>
    <property name="jnlp.omero.web.host" value="https://trout.openmicroscopy.org/merge/"/>
```
Logged in:
```
$ grep property insight.jnlp
    <property name="jnlp.omero.host" value="trout.openmicroscopy.org"/>
    <property name="jnlp.omero.port" value="4064"/>
    <property name="jnlp.omero.web.host" value=""/>
    <property name="jnlp.omero.sessionid" value="b4f6879e-9cf2-43cb-bf27-2a7f1ddde7e9"/>
```
I can't work out how to work `bin/omero sessions list` to see the active session. Can you check on trout merge?

**Comment by joshmoore** [comment]
`bin/omero sessions list` shows sessions local to your CLI. `bin/omero sessions who` shows sessions on the server.

**Comment by mtbc** [comment]
Ah, "who" needs a very recent develop! Thank you for the help.
```
user-2 | private-1 | 2015-05-20 15:52:18     | OMERO.web      | 10 min. | 386      | 2015-05-20 16:36:22 
```
looks to be the promising line.

**Comment by joshmoore** [comment]
Just a thought: do we know that one use of the session won't interfere with the other client (i.e. closing, etc)?

**Comment by aleksandra-tarkowska** [comment]
@mtbc Could you try to debug like example http://stackoverflow.com/questions/686061/how-can-i-debug-applications-under-java-web-start-jnlp

**Comment by mtbc** [comment]
@jburel seems to be on the case but I'm generally happy to type in and try things.

**Comment by aleksandra-tarkowska** [comment]
@joshmoore launching Insight with the same session key doesn't kill the session. We have just checked that with @mtbc session was alive, even more when he paste that session key to insight as a username he managed to log in. That shows another issue that when he logged out from Insight the session wasn't killed ;-)

**Comment by jburel** [comment]
@aleksandra-tarkowska: we have a card for that session problem see https://trello.com/c/NWT3qUma/430-client-del-session-still-alive

**Comment by joshmoore** [comment]
Sounds good. Thanks for this, everyone!

**Comment by mtbc** [comment]
For what it's worth, this *does* seem to work fine for me if I switch to using the `javaws` from my old Oracle JDK 6 installation.

**Comment by joshmoore** [comment]
And this works for me for local dev testing:
```
components/insight/build$ ant run -Dapp.vmparameters="-Djnlp.omero.port=14064 -Djnlp.omero.host=localhost -Djnlp.omero.sessionid=17a7..."
```

**Pull request merged**
