### PR TITLE
leak FileSystem Service

### PR DESCRIPTION
**Pull request by jburel**
# What this PR does

Close formatter to avoid leak
Notice the issue when investigating the thumbnail problem reported on https://github.com/openmicroscopy/openmicroscopy/pull/4823
Code review should be enough

### CODE REVIEW

**Comment by mtbc** [comment]
Note that these days one may also use,
```java
try (final Formatter formatter = new Formatter()) { ...
```
but this is **good to merge** as-is. :+1:

**Comment by joshmoore** [comment]
...which of course never made it into our templates.

**Comment by jburel** [comment]
@mtbc: do you want to start a list of elements we want to add to our templates on a doc card?
We have comment in passing on PR but we all tend to forget it when the time comes to edit code

**Comment by mtbc** [comment]
Created https://trello.com/c/qBBCrOs6/512-code-template-improvements.

**Comment by jburel** [comment]
@mtbc Thanks for the card, I have also changed the code to match the new template guideline :-)

**Comment by mtbc** [comment]
Code is looking good, thank you for the various improvements.

**Pull request merged**
