### PR TITLE
Initial m4 history

### PR DESCRIPTION
**Pull request by hflynn**
Will no doubt need further work - I picked a bunch of stuff from the PR list not necessarily the most relevant point.

cc/ @joshmoore @jburel @sbesson

### CODE REVIEW

**Comment by mtbc** [comment]
Looks good so far.

**Comment by hflynn** [comment]
If you have a list of those new features anywhere @pwalczysko it would be much appreciated!

**Comment by manics** [comment]
Is this meant to match up with the various What's New pages?

**Comment by hflynn** [comment]
Those are for the actual release and this is aimed at developers who want to update their code in preparation for the release so not necessarily, no.

**Comment by manics** [comment]
Technically a breaking change... though it never really worked so shouldn't have any major consequences https://github.com/openmicroscopy/openmicroscopy/pull/3249

Perhaps something like "OMERO.tables internal HDF5 format has changed"?

**Comment by hflynn** [comment]
Thanks @manics I'll add that.

**Comment by hflynn** [comment]
Anything else before I push another commit folks?

**Comment by joshmoore** [comment]
Things that occur to me:
 * for db: "image.series is now exposed in Hibernate"
 * for maps: "ui and search..."
 * "improved deletion performance" (shall I say 'vastly'? :smile:)
 * "numerous cleanups to the code incl. pep8, removal of deprecated methods & components, etc"
 * "contributions by PaulVanSchayck"

**Comment by jburel** [comment]
```
ImageJ plugin work allowing OMERO ROIs to be opened in ImageJ and ImageJ
```
Not very clear
ImageJ plugin allows: import images and save ROis to OMERO. View in imageJ rois and images stored in OMERO

**Comment by hflynn** [comment]
Further update pushed - formatting looks fine if I paste the content directly into the docs so hopefully it'll build ok.

**Comment by jburel** [comment]
We may also want to add a thanks to Luca for his contribution on roi in web

**Comment by hflynn** [comment]
i can quickly add that now

**Comment by hflynn** [comment]
Done

**Comment by sbesson** [comment]
Merging this for `5.1.0-m4` We can append to the history in a subsequent PR.

**Comment by hflynn** [comment]
--no-rebase

**Pull request merged**
