### PR TITLE
adjust graphs API to provide Collections-based Java interface

### PR DESCRIPTION
**Pull request by mtbc**
OMERO should still work, including moves and deletes, and tests should still pass: there should be no change in behavior.

*Update:* Now provides Insight with a utility class for constructing graphs requests.

--no-rebase

### CODE REVIEW

**Comment by jburel** [comment]
Requests should probably go out of insight since it will be useful for other applications.
This could be done when refactoring gateway.

**Comment by mtbc** [comment]
Agreed, it should be scooped up with the gateway when that goes wherever it's off to. (I assume it will do so naturally as the gateway will use it.)

**Comment by dominikl** [comment]
I guess once this is merged I'm going to make the switch over in Insight from Chgrp to Chgrp2, etc., right?

**Comment by mtbc** [comment]
Indeed. http://www.openmicroscopy.org/site/support/omero5.1-staging/developers/Server/GraphsMigration.html should include some useful hints, but also of course feel free to ask.

**Comment by dominikl** [comment]
Looks fine to me. Integration tests passed, did some Chgrps and Deletes, didn't notice any problems.

**Comment by joshmoore** [comment]
@dominikl : all yours, then.

**Pull request merged**
