### PR TITLE
Remove deprecated and unused external Python modules

### PR DESCRIPTION
**Pull request by sbesson**
Follow-up of https://github.com/openmicroscopy/openmicroscopy/pull/3737

This removes deprecated and/or unused external modules. To test this PR, check all tests remain green and that no functionality is affected.

--no-rebase

### CODE REVIEW

**Comment by ximenesuk** [comment]
This looks good to merge.

On the back of this should slate `argparse` for removal at some point given it is now in the standard libraries

**Comment by manics** [comment]
`argparse` isn't included as standard in Python 2.6.

**Comment by sbesson** [comment]
As @manics said, once Python 2.7 is the minimal version, we can indeed remove `argparse` from external libraries.

**Comment by ximenesuk** [comment]
Yes, I should have been clearer!

**Comment by sbesson** [comment]
Want to add this to the Python 2.7 card?

**Comment by sbesson** [comment]
Comment added to https://trello.com/c/2xsNSEWG/19-dropping-python-2-6-in-favor-2-7 by COlin. Anything else on this PR? @joshmoore ?

**Comment by joshmoore** [comment]
Happy if things are green.

**Pull request merged**
