### PR TITLE
Read only phase1

### PR DESCRIPTION
**Pull request by joshmoore**
Rebases @chris-allan 's work onto metadata52 for testing in IDR 0.4.0.

### CODE REVIEW

**Comment by chris-allan** [comment]
Added e1759a5db99c088c7ef0ba6afce8e10af494d18b to `glencoesoftware/read-only-phase1`.

/cc @dpwrussell

**Comment by joshmoore** [comment]
> Added e1759a5 to glencoesoftware/read-only-phase1.

:+1: A few more commits are going to be necessary to get the travis builds passing.

**Comment by manics** [comment]
I had a go at rebasing this PR onto `metadata53`: https://github.com/manics/openmicroscopy/tree/rebase-5213-readonly53

There was a conflict in https://github.com/manics/openmicroscopy/commit/2b1a2621498303d981e0bf3bda50602cfb9be3ad#diff-f65a871d8f192255abdff2dbaccd4d7eL131 (corresponds to https://github.com/openmicroscopy/openmicroscopy/pull/5213/commits/d60a28ad674b0f98be48ef221c7668f9dd3a4350#diff-f65a871d8f192255abdff2dbaccd4d7eL131 in this PR), the remaining commits were fine.

I won't be able to fix travis though, so do you want to rebase your PR to metadata53?

**Comment by joshmoore** [comment]
Closing in favor of https://github.com/openmicroscopy/openmicroscopy/pull/5271

**Pull request closed without merging**
