### PR TITLE
FreeSans fonts

### PR DESCRIPTION
**Pull request by will-moore**
# What this PR does

Adds FreeSans fonts for Bold and Italic styles, alongside existing FreeSans font.
Fonts are used by figure scripts and OMERO.figure for TIFF figure creation.
Bold and Italic styles needed for https://trello.com/c/BNjiEiAZ/46-labels-italics 

# Testing this PR

1. Not much to test yet, since PR for figure won't be opened until after release.

### CODE REVIEW

**Comment by will-moore** [comment]
As discussed yesterday, it would be great to get this into 5.3.1 so we are free to use these in Figure without waiting for 5.3.2. To test, I could temporarily upload the script from https://github.com/ome/omero-figure/pull/204 and check it is picking up the fonts.

**Comment by will-moore** [comment]
Just exported http://web-dev-merge.openmicroscopy.org/figure/file/17802/ as TIFF (user-3) using fonts from this PR (NB: I had to use html in the labels since python markdown seems not to be installed).
This uses Italic (oblique), Bold & BoldOblique.

screen shot 2017-04-18 at 10 41 58

**Comment by will-moore** [comment]
@pwalczysko @bramalingam I've listed this PR to test tomorrow, but if either of you have time today that would be great (since the script is uploaded just now). Just need to export the figure file above as TIFF.

**Comment by joshmoore** [comment]
What would it take for these to be in the figure repository long-term, @will-moore ?

**Comment by jburel** [comment]
Exported as pdf labels show up as bold/italic.
We will need to think of a strategy to avoid such omero-app dependency
Discussed briefly with @joshmoore this morning, letting the "app/plugin" installed the font during the installation process if not available

For script dependencies like reportlab and markdown, we will need to review that since it is not installed by default on the node

**Comment by jburel** [comment]
card created https://trello.com/c/8CiMu7uj/9-rethink-font-dependencies-for-export-script

**Comment by jburel** [comment]
merging

**Pull request merged**
