### PR TITLE
Search plate acquisition

### PR DESCRIPTION
**Pull request by will-moore**
As in Insight, searching for Plate "Runs" should work the same as for Plates.
To test:
 - Tag a plate 'Run'
 - Search for the Tag - Run should be in results
 - Click it to display in right panel
 - Click "Browse" to browse to the run.

### CODE REVIEW

**Comment by dominikl** [comment]
Search works like expected, results in Insight and Web are identical. Just a minor issue: The browse function opens the plate but doesn't populate the central panel and selects the run, like browse on an image within a dataset does.

**Comment by joshmoore** [comment]
@will-moore : are you planning on modifying the opening here or elsewhere?

**Comment by will-moore** [comment]
@joshmoore Sorry - not in this PR. It's not part of search functionality.

**Comment by joshmoore** [comment]
Ok, leaving @will-moore to note that down in trello. Merging.

**Pull request merged**
