### PR TITLE
Roi annotations

### PR DESCRIPTION
**Pull request by jburel**
Initial changes to allow tagging of shapes.
To tag a shape
 * Select the shape
 * right-clik on shape, select the tag option
 * The standard tagging dialog will pop up
 * Select a tag and/or create a new one
 * The tags are displayed in the Inspector tab (for now)
 * Tag can be added or removed from the shapes
 * Shapes need to be saved before tagging can occur.

cc @dominikl @gusferguson @aleksandra-tarkowska

### CODE REVIEW

**Comment by dominikl** [comment]
Tried to build your PR locally, got a compile error
```
/Users/dlindner/Repositories/openmicroscopy/components/insight/SRC/org/openmicroscopy/shoola/env/data/views/calls/StructuredAnnotationSaver.java:184: error: local variable toRemove is accessed from within inner class; needs to be declared final
                os.saveAnnotationData(ctx, toAdd, toRemove, userID);
```

**Comment by jburel** [comment]
@dominikl: problem should be fixed.

**Comment by mtbc** [comment]
Still some errors, e.g.,
```
/home/travis/build/openmicroscopy/openmicroscopy/components/insight/SRC/org/openmicroscopy/shoola/util/roi/model/annotation/AnnotationKeys.java:39: error: package org.openmicroscopy.shoola.env.data.util does not exist
```

**Comment by sbesson** [comment]
Note this PR is breaking some `UpdateServiceTest`. See https://ci.openmicroscopy.org/job/OMERO-5.1-breaking-integration-java/310/. Marked as excluded.

**Comment by dominikl** [comment]
The strange thing is, when checking out this PR and running the integration tests, the tests pass. Could it be a combination of this PR and other PRs in breaking build which causes the problems?

**Comment by jburel** [comment]
Run locally
```
===============================================
Ant suite
Total tests run: 46, Failures: 0, Skips: 0
===============================================

```
Removing the exclude label

**Comment by pwalczysko** [comment]
Bug: 
1. Tags get "lost" when dimensions of the ROI changes.
2. If trying to retag after such loss with the same tag, got an exception.

Workflow:
  - login to trout breaking, user-4, image 9423
  - open a dv image, it has a rectangle ROI on it
  - select the rectangle ROI, right-click, select "Tag"
  - in the dialog popping up, select an available tag, "porcine"
  - add the tag and click Save
  - go to the Inspector tab, the tag is listed there as expected
  - still in Inspector tab, change the width of the rectangle by editing the number and hit Save
  - the tag "porcine" listed in the Inspector tab vanished, the width change was respected -> NOT EXPECTED
  - click again at the same  rectangle region and right-click and select Tag
  - in the dialog, the "porcine" tag is now on the left-hand side (not chosen)
  - select it and add to right-hand side and hit Save -> ERROR occurs

```
java.lang.Exception: org.openmicroscopy.shoola.env.data.DSAccessException: Cannot access data. 
Cannot update the object.
	at org.openmicroscopy.shoola.env.data.OMEROGateway.handleException(OMEROGateway.java:869)
	at org.openmicroscopy.shoola.env.data.OMEROGateway.createObject(OMEROGateway.java:2599)
	at org.openmicroscopy.shoola.env.data.OMEROGateway.createObject(OMEROGateway.java:2577)
	at org.openmicroscopy.shoola.env.data.OmeroMetadataServiceImpl.linkAnnotation(OmeroMetadataServiceImpl.java:648)
	at org.openmicroscopy.shoola.env.data.OmeroMetadataServiceImpl.saveData(OmeroMetadataServiceImpl.java:1434)
	at org.openmicroscopy.shoola.env.data.views.calls.StructuredAnnotationSaver$1.doCall(StructuredAnnotationSaver.java:94)
	at org.openmicroscopy.shoola.env.data.views.BatchCall.doStep(BatchCall.java:144)
	at org.openmicroscopy.shoola.util.concur.tasks.CompositeTask.doStep(CompositeTask.java:226)
	at org.openmicroscopy.shoola.env.data.views.CompositeBatchCall.doStep(CompositeBatchCall.java:126)
	at org.openmicroscopy.shoola.util.concur.tasks.ExecCommand.exec(ExecCommand.java:165)
	at org.openmicroscopy.shoola.util.concur.tasks.ExecCommand.run(ExecCommand.java:276)
	at org.openmicroscopy.shoola.util.concur.tasks.AsyncProcessor$Runner.run(AsyncProcessor.java:91)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.openmicroscopy.shoola.env.data.DSAccessException: Cannot access data. 
Cannot update the object.
	at org.openmicroscopy.shoola.env.data.OMEROGateway.handleException(OMEROGateway.java:869)
	at org.openmicroscopy.shoola.env.data.OMEROGateway.saveAndReturnObject(OMEROGateway.java:2761)
	at org.openmicroscopy.shoola.env.data.OMEROGateway.createObject(OMEROGateway.java:2597)
	... 11 more
Caused by: omero.ValidationException
    serverStackTrace = "ome.conditions.ValidationException: could not insert: [ome.model.annotations.ShapeAnnotationLink]; SQL [insert into shapeannotationlink (child, creation_id, external_id, group_id, owner_id, permissions, update_id, parent, version, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; constraint [shapeannotationlink_parent_child_owner_id_key]; nested exception is org.hibernate.exception.ConstraintViolationException: could not insert: [ome.model.annotations.ShapeAnnotationLink]
                        	at org.springframework.orm.hibernate3.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:643)
                        	at org.springframework.orm.hibernate3.HibernateAccessor.convertHibernateAccessException(HibernateAccessor.java:412)
                        	at org.springframework.orm.hibernate3.HibernateInterceptor.invoke(HibernateInterceptor.java:117)
                        	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
                        	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:110)
                        	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
                        	at ome.tools.hibernate.ProxyCleanupFilter$Interceptor.invoke(ProxyCleanupFilter.java:249)
                        	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
                        	at ome.services.util.ServiceHandler.invoke(ServiceHandler.java:121)
                        	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
                        	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
                        	at com.sun.proxy.$Proxy91.saveAndReturnObject(Unknown Source)
                        	at sun.reflect.GeneratedMethodAccessor442.invoke(Unknown Source)
                        	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                        	at java.lang.reflect.Method.invoke(Method.java:606)
                        	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:319)
                        	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
                        	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
                        	at ome.security.basic.BasicSecurityWiring.invoke(BasicSecurityWiring.java:98)
                        	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
                        	at ome.services.blitz.fire.AopContextInitializer.invoke(AopContextInitializer.java:43)
                        	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
                        	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
                        	at com.sun.proxy.$Proxy91.saveAndReturnObject(Unknown Source)
                        	at sun.reflect.GeneratedMethodAccessor465.invoke(Unknown Source)
                        	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                        	at java.lang.reflect.Method.invoke(Method.java:606)
                        	at ome.services.blitz.util.IceMethodInvoker.invoke(IceMethodInvoker.java:179)
                        	at ome.services.throttling.Callback.run(Callback.java:56)
                        	at ome.services.throttling.InThreadThrottlingStrategy.callInvokerOnRawArgs(InThreadThrottlingStrategy.java:56)
                        	at ome.services.blitz.impl.AbstractAmdServant.callInvokerOnRawArgs(AbstractAmdServant.java:149)
                        	at ome.services.blitz.impl.UpdateI.saveAndReturnObject_async(UpdateI.java:64)
                        	at sun.reflect.GeneratedMethodAccessor464.invoke(Unknown Source)
                        	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                        	at java.lang.reflect.Method.invoke(Method.java:606)
                        	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:319)
                        	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
                        	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
                        	at omero.cmd.CallContext.invoke(CallContext.java:78)
                        	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
                        	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
                        	at com.sun.proxy.$Proxy92.saveAndReturnObject_async(Unknown Source)
                        	at omero.api._IUpdateTie.saveAndReturnObject_async(_IUpdateTie.java:92)
                        	at omero.api._IUpdateDisp.___saveAndReturnObject(_IUpdateDisp.java:180)
                        	at omero.api._IUpdateDisp.__dispatch(_IUpdateDisp.java:351)
                        	at IceInternal.Incoming.invoke(Incoming.java:222)
                        	at Ice.ConnectionI.invokeAll(ConnectionI.java:2482)
                        	at Ice.ConnectionI.dispatch(ConnectionI.java:1258)
                        	at Ice.ConnectionI.message(ConnectionI.java:1213)
                        	at IceInternal.ThreadPool.run(ThreadPool.java:321)
                        	at IceInternal.ThreadPool.access$300(ThreadPool.java:12)
                        	at IceInternal.ThreadPool$EventHandlerThread.run(ThreadPool.java:693)
                        	at java.lang.Thread.run(Thread.java:745)
                        "
    serverExceptionClass = "ome.conditions.ValidationException"
    message = "could not insert: [ome.model.annotations.ShapeAnnotationLink]; SQL [insert into shapeannotationlink (child, creation_id, external_id, group_id, owner_id, permissions, update_id, parent, version, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; constraint [shapeannotationlink_parent_child_owner_id_key]; nested exception is org.hibernate.exception.ConstraintViolationException: could not insert: [ome.model.annotations.ShapeAnnotationLink]"
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at IceInternal.BasicStream.createUserException(BasicStream.java:2615)
	at IceInternal.BasicStream.access$300(BasicStream.java:12)
	at IceInternal.BasicStream$EncapsDecoder10.throwException(BasicStream.java:3099)
	at IceInternal.BasicStream.throwException(BasicStream.java:2077)
	at IceInternal.Outgoing.throwUserException(Outgoing.java:538)
	at omero.api._IUpdateDelM.saveAndReturnObject(_IUpdateDelM.java:260)
	at omero.api.IUpdatePrxHelper.saveAndReturnObject(IUpdatePrxHelper.java:802)
	at omero.api.IUpdatePrxHelper.saveAndReturnObject(IUpdatePrxHelper.java:774)
	at org.openmicroscopy.shoola.env.data.OMEROGateway.saveAndReturnObject(OMEROGateway.java:2758)
	... 12 more

	at org.openmicroscopy.shoola.env.ui.UserNotifierImpl.showErrorDialog(UserNotifierImpl.java:191)
	at org.openmicroscopy.shoola.env.ui.UserNotifierImpl.notifyError(UserNotifierImpl.java:291)
	at org.openmicroscopy.shoola.env.ui.UserNotifierImpl.notifyError(UserNotifierImpl.java:259)
	at org.openmicroscopy.shoola.agents.measurement.MeasurementViewerLoader.handleException(MeasurementViewerLoader.java:153)
	at org.openmicroscopy.shoola.env.data.events.DSCallAdapter.eventFired(DSCallAdapter.java:84)
	at org.openmicroscopy.shoola.env.data.views.BatchCallMonitor$1.run(BatchCallMonitor.java:124)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by pwalczysko** [comment]
Multiple problems with removing the tags already added:
  - no refresh of the Inspector tab after apparently succesful removal of added tag
  - after clicking Save, still no refresh of the Inspector tab
  - after closing the image, although Save was clicked, the UI asks "Do you want to save changes in ROIs ?"
  - if you say Yes, and then expect that the removal of tags has been successful, it is successful only in some cases (would need to investigate that further)
  - if the tag removal was finally successful, and you try to retag the ROIs with the same tags you just removed, you get the exception above

**Comment by pwalczysko** [comment]
Note that the problems https://github.com/openmicroscopy/openmicroscopy/pull/3928#issuecomment-121631222 and https://github.com/openmicroscopy/openmicroscopy/pull/3928#issuecomment-121634150 occurred on previously saved shapes, not on newly drawn ones (did not try the newly drawn ones at all)

**Comment by jburel** [comment]
@pwalczysko:
* after closing the image, although Save was clicked, the UI asks "Do you want to save changes in ROIs ?"
This is not related to that PR, it happens as soon as you select a shape in the current release version (it has been like that from the start) Fixing that could take time

**Comment by jburel** [comment]
@pwalczysko, @dominikl 
https://github.com/openmicroscopy/openmicroscopy/pull/3951 has now a PR opened

Probably time to close mine.

**Comment by jburel** [comment]
@pwalczysko: tested the workflow https://github.com/openmicroscopy/openmicroscopy/pull/3928#issuecomment-121631222
I do not see any error.

**Comment by jburel** [comment]
@pwalczysko: I see the image you mentioned is not owned by user-4.
That will be the source of the problem

**Comment by jburel** [comment]
@dominikl: I have pushed a new commit
I cannot reproduce @pwalczysko's problem when only using the code in this PR.

**Comment by dominikl** [comment]
@jburel Also cherry-picked your last commit to #3951 .

Tested again with #3951 , couldn't reproduce any of the problems. I fixed the problems/exceptions with commit fa76430f7453a0 Previously the save rois method returned the same rois (new rois: id = -1) which were given as parameter, then adding an annotation link to a roi with id = -1 threw the ConstraintViolationException; now the saved rois are returned (with their db id set).

**Pull request closed without merging**
