### PR TITLE
introduce Chmod2 request

### PR DESCRIPTION
**Pull request by mtbc**
Uses of `Chmod` requests are now actioned by the `Chmod2` implementation. Chmod-related integration tests should pass. Also try changing group permissions from the client to make sure it works correctly. (The admin service's `changePermissions` still uses the old `Chmod` but the clients don't much use that.)

This PR *should* be suitable for 5.1 so that a 5.1.1 (or trout-latest) client can work with a 5.1.2 (or trout-merge) server and vice versa: no commits with this PR switch clients to use `Chmod2` directly.

--no-rebase

### CODE REVIEW

**Comment by mtbc** [comment]
OMERO-5.1-merge-integration-java now has 48 more passing tests. :smiley:

**Comment by mtbc** [comment]
Probably hold off extensive manual testing until the failing Python test is fixed.

**Comment by pwalczysko** [comment]
Just did a quick check connecting the ``latest`` client to ``merge`` server. Downgraded and upgraded a test group permissions couple of times. Then went into the group as a non-admin user. The group permissions behaved as  expected.

**Comment by pwalczysko** [comment]
After the fixes of @mtbc to be tested with the last bullet point of Step 2 of https://www.openmicroscopy.org/private/ome-internal/testing_scenarios/AdminGroupUserEdit.html

**Comment by mtbc** [comment]
It looks to me like the problem is with the integration test. Okay to continue with functional testing while I look at how to fix it.

**Comment by mtbc** [comment]
Yes, the chmod succeeds just fine. Where there are links to things no longer visible due to the permissions, deletions happen accordingly.

**Comment by ximenesuk** [comment]
Thanks. I'm still curious about the initial change mod.

**Comment by mtbc** [comment]
Travis failure is in `TestTables.testErrorInGet` so I doubt it's this PR's fault! It would be great if some kind person would give it a kick.

**Comment by mtbc** [comment]
Without that initial chmod, the first run-through of `testAddTagMakePrivate` goes fine, but then the second fails with a `SecurityViolation` (can't read the tag) when member1 tries to use member2's tag, exactly as if the group were already private. It's a reliably reproducible effect.

**Comment by ximenesuk** [comment]
Yes, I reproduced it myself, but isn't this the sign of a bug? Or at least a behaviour that is not fully understood?

**Comment by mtbc** [comment]
Further work to come, after discussion with @ximenesuk and @sbesson.

**Comment by mtbc** [comment]
Added some test changes that probably most properly fit with this PR. Integration tests should continue to pass.

**Comment by ximenesuk** [comment]
@mtbc I'll review these last changes once this final fix is in the build. Is there anything further to be expected?

**Comment by mtbc** [comment]
No. Could look at code and just make sure they pass in the morning?

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#967](https://ci.openmicroscopy.org/job/OME-5.1-merge-push/967/). See the [console output](https://ci.openmicroscopy.org/job/OME-5.1-merge-push/967/consoleText) for more details.
Possible conflicts:
  - PR #3739 ximenesuk 'Replace deprecated Delete/Chgrp methods in gateway'
    - components/tools/OmeroPy/test/integration/gatewaytest/test_wrapper.py
    - components/tools/OmeroPy/test/integration/gatewaytest/test_user.py
    - components/tools/OmeroPy/test/integration/gatewaytest/test_services.py

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#968](https://ci.openmicroscopy.org/job/OME-5.1-merge-push/968/). See the [console output](https://ci.openmicroscopy.org/job/OME-5.1-merge-push/968/consoleText) for more details.
Possible conflicts:
  - PR #3739 ximenesuk 'Replace deprecated Delete/Chgrp methods in gateway'
    - components/tools/OmeroPy/test/integration/gatewaytest/test_wrapper.py
    - components/tools/OmeroPy/test/integration/gatewaytest/test_user.py
    - components/tools/OmeroPy/test/integration/gatewaytest/test_services.py

**Comment by joshmoore** [comment]
Excluding this to let gh-3739 through.

**Comment by mtbc** [comment]
It's already excluded.

**Comment by mtbc** [comment]
Removed commit that conflicts with @ximenesuk's PR, that can follow separately. Remove `exclude` label?

**Comment by mtbc** [comment]
Latest commit https://github.com/openmicroscopy/openmicroscopy/commit/19c3aeef6e873594dc5156a05ad80394340da9d9 merely echoes merged change https://github.com/openmicroscopy/openmicroscopy/commit/19c3aeef6e873594dc5156a05ad80394340da9d9 for `Chmod2` too.

**Comment by joshmoore** [comment]
Done. Currently "waiting" I'll leave you to re-list as appropriate.

**Comment by mtbc** [comment]
Thank you! I'll leave those gateway test changes for another time so as not to cause any test failures that may delay #3739.

**Comment by mtbc** [comment]
The last two commits bring to `Chmod2` the fixes from https://github.com/openmicroscopy/openmicroscopy/pull/3794.

**Comment by joshmoore** [comment]
@mtbc : do I understand that now the test here is:
* user-3 imports an image into their own dataset in read-annotate-1
* user-3 creates a tag and uses it to tag the image
* user-5, a group owner, uses OMERO.web to find user-3's dataset
* user-5 **chowns** the dataset...

**Comment by mtbc** [comment]
That's a really good question. Yes, I would guess, the last step is that user-5 chowns the group to be private. Of course, user-3's tag ought not be deleted.

**Comment by mtbc** [comment]
Also worth testing:
* create some third user who also tags `user-3`'s image
* make sure that tag is unlinked but not deleted after `user-5` chmods the group to private

**Comment by pwalczysko** [comment]
Sorry, getting a bit confused here. Why @joshmoore mentions chown ? (change ownership, why ? the PR does not deal with this ?).
I am redeploying trout merge now so that we have user-1 through user-12 there, which will hopefully help me to get the test right.

Please relist for tomorrow with my name.

**Comment by pwalczysko** [comment]
(sorry, did not get earlier to this due to LDAP)

**Comment by mtbc** [comment]
No problem, the LDAP ones can be tricky to test. It is easy to mix up chown with chmod! :smiley:

**Comment by joshmoore** [comment]
Indeed! Corrected my typo.

**Comment by pwalczysko** [comment]
The test of https://github.com/openmicroscopy/openmicroscopy/pull/3773#issuecomment-100194729 passed as expected. Both a tag of user-3 on image as well as on the dataset itself were preserved when user-5 downgraded the group to private.

**Comment by pwalczysko** [comment]
Interestingly, the case https://github.com/openmicroscopy/openmicroscopy/pull/3773#issuecomment-100206543 (the downgrade of r-a to p when non-owner of the images tags an image) is not allowed in web client. Discussing with @will-moore , all what web client is doing in such cases is ``catching the OMERO security violation`` -> it results in a message as shown below.

screen shot 2015-05-12 at 10 59 36

But all this together makes not sense - the client-server binding in this workflow seems to be lacking - are we missing some pieces here ? @mtbc @joshmoore

**Comment by mtbc** [comment]
So the chmod worked fine from the CLI but not web?

**Comment by pwalczysko** [comment]
@mtbc : No, the CLI failed as well with 

```
Traceback (most recent call last):
  File "bin/omero", line 125, in <module>
    rv = omero.cli.argv()
  File "/opt/hudson/workspace/OMERO-5.1-merge-deploy/src/dist/lib/python/omero/cli.py", line 1431, in argv
    cli.invoke(args[1:])
  File "/opt/hudson/workspace/OMERO-5.1-merge-deploy/src/dist/lib/python/omero/cli.py", line 945, in invoke
    stop = self.onecmd(line, previous_args)
  File "/opt/hudson/workspace/OMERO-5.1-merge-deploy/src/dist/lib/python/omero/cli.py", line 1022, in onecmd
    self.execute(line, previous_args)
  File "/opt/hudson/workspace/OMERO-5.1-merge-deploy/src/dist/lib/python/omero/cli.py", line 1104, in execute
    args.func(args)
  File "/opt/hudson/workspace/OMERO-5.1-merge-deploy/src/dist/lib/python/omero/plugins/group.py", line 190, in perms
    c.submit(chmod)
  File "/opt/hudson/workspace/OMERO-5.1-merge-deploy/src/dist/lib/python/omero/clients.py", line 887, in submit
    closehandle=True)
  File "/opt/hudson/workspace/OMERO-5.1-merge-deploy/src/dist/lib/python/omero/clients.py", line 906, in waitOnCmd
    callback.loop(loops, ms)  # Throw LockTimeout
  File "/opt/hudson/workspace/OMERO-5.1-merge-deploy/src/dist/lib/python/omero/callbacks.py", line 251, in loop
    5000L, int(waited))
omero.LockTimeout: exception ::omero::LockTimeout
{
    serverStackTrace = None
    serverExceptionClass = None
    message = Command unfinished after 5.0 seconds
    backOff = 5000
    seconds = 5
}
```

**Comment by pwalczysko** [comment]
Insight succeeded where Web and CLI failed. The group is not Private.

**Comment by pwalczysko** [comment]
Tag was preserved but unlinked as expected in the case of https://github.com/openmicroscopy/openmicroscopy/pull/3773#issuecomment-100206543. What is surprising is the failure of Web and CLI to allow such downgrade,

**Comment by mtbc** [comment]
I suppose the integration test at https://github.com/snoopycrimecop/openmicroscopy/blob/merge/develop/latest/components/tools/OmeroJava/test/integration/chmod/PermissionsTest.java running at https://ci.openmicroscopy.org/job/OMERO-5.1-merge-integration-java/lastCompletedBuild/testngreports/integration.chmod/PermissionsTest/ actually covers a very similar case.

**Comment by joshmoore** [comment]
NB: likely should consider the lack of `--wait` setting to the CLI a BUG or strong RFE. cc: @ximenesuk

**Comment by mtbc** [comment]
Insight does seem to use `Chmod` at least in the gateway so that should have been implemented by `Chmod2` via the facade.

**Comment by mtbc** [comment]
Web still uses the admin service's `changePermissions` rather than this PR's chmod work.

**Comment by mtbc** [comment]
@pwalczysko: I think then good to merge?

**Comment by pwalczysko** [comment]
Good to merge

**Pull request merged**
