### PR TITLE
10661 dynamic params

### PR DESCRIPTION
**Pull request by joshmoore**
See: http://trac.openmicroscopy.org.uk/ome/ticket/10661#comment:7

#### Background ####

An interesting recent bug lead to the review of the `JobParams` creation. The user-4 on merge/trout was receiving an exception when trying to run `Make_Movie.py` since the chosen color was not a member of a list of the form `["White", "Red", None, "Black", None, None, None]`. What seems to have happened is that some exception (`OutOfMemory`?) caused the params themselves to be corrupted. The reason that this was only happening for user-4 (and his/her group) was that `JobParams` were being created **per group**. This unnecessary overhead was a secondary bug.

#### Implementation ####

Rather than trying to fix the 2 underlying bugs caused by caching params for each group (and trying to clean up old params, etc.), ticket 10661 suggested reloading all scripts on server start-up. This is now possible along with 2 configuration options under the `omero.scripts.cache.` namespace:

 * `spec` determines the settings for the Guava cache, i.e. how quickly will the objects be freed from memory
 * `cron` how often will a full reloading of all the scripts be attempted. One run is always performed on startup so that the initial access by any user is not delayed.

#### Functional differences ####

 * The general user should notice no differences in behavior.
 * Developers will notice that `parsejob` instances are no longer being persisted. This could conceivably be viewed as a breaking change, but considering that the job itself consists of a byte array containing the serialized form of an Ice object, it's unlikely this was of use.
 * Any script with the namespace "dynamic" (TBD) will **not** be cached, and instead will be reprocessed on each invocation. This will include sizeable overhead.
 * (**Planned**) Disabling the new configuration options will rollback to using the previous `ParamsHelper` method of storing `parsejobs` in the database.

cc: @manics @pwalczysko @rleigh-dundee @ctrueden

### CODE REVIEW

**Comment by joshmoore** [comment]
Fix pushed for user scripts. Removed breaking.

**Comment by joshmoore** [comment]
Dynamic scripts support pushed. See https://github.com/openmicroscopy/openmicroscopy/commit/9946644bc41334e5b29c5ff35136c5b404c0702f

**Comment by joshmoore** [comment]
All `(not broken)` integration tests passing as of https://github.com/joshmoore/openmicroscopy/commit/3287242035f4da16e9cb8f8ac8f357a1682edefc

**Comment by manics** [comment]
Tested with https://gist.github.com/manics/832c5ebcdf8c10f0c87b (a single parameter which is a list of datasets).

Dynamic parameters are recalculated and `namespaces` can already be passed as a keyword argument to scripts.client which makes it really easy to use. However if I run the above script, then create a new dataset, the parameters list is recalculated but if I choose the new one and run the script I get an error:
```
Dynamic Test Invalid parameters: VALUE LIST for "Object": Dataset:252 test 2 not in ['Dataset:251 test', 'Dataset:2 test-0256', 'Dataset:1 test-0128'] 
```
which suggests it's still validating the new parameter against an older cached list.

**Comment by joshmoore** [comment]
I saw the expected behavior from the command-line, but logged in as root. Writing an integration test with your gist (to be pushed later), I realized the problem: the `getParams` method is happening in the context of the root/system user for official scripts.

**Comment by joshmoore** [comment]
Pushed a fix, @manics.

**Comment by manics** [comment]
It's still not working consistently for me- it worked once after renaming a dataset, but not on subsequent additions/renames.

**Comment by joshmoore** [comment]
Can you help me to modify the test so that it fails?

**Comment by manics** [comment]
Can you cherry-pick https://github.com/manics/openmicroscopy/commit/58198743f4b9aa7420376c19f0511e95236da729 https://github.com/manics/openmicroscopy/commit/5e6740a857352fb945b7e300d322288e6c9cbc5e

```
OmeroPy$ ./setup.py test -v -t test/integration/test_scripts.py -k testDynamicUpdate
...

        contains_uuids(False, False)
        with pytest.raises(omero.ValidationException):
            run_with_param(uuid1)

        update.saveObject(self.new_dataset(name=uuid1))
        contains_uuids(True, False)
>       run_with_param(uuid1)

...
    def runScript(self, scriptID, inputs, waitSecs, _ctx=None):
>       return _M_omero.api.IScript._op_runScript.invoke(self, ((scriptID, inputs, waitSecs), _ctx))
E       ValidationException: exception ::omero::ValidationException
E       {
E           serverStackTrace =
E           serverExceptionClass =
E           message = Invalid parameters:
E       VALUE LIST for "Object": 7c88c770-a6ea-4f45-9ebe-d12504f65fb3 not in ['<No objects found>']
E
E       }
```

**Comment by joshmoore** [comment]
Done & locally testing. Thanks.

**Comment by joshmoore** [comment]
With this again not in today's build, I'd propose we push this to 5.1.3.

**Comment by joshmoore** [comment]
Build fix in `blitz/build.xml` should allow this to be included by travis. cc: @sbesson @manics

**Comment by joshmoore** [comment]
@dominikl / @jburel : https://github.com/openmicroscopy/openmicroscopy/pull/3899 will likely conflict with https://github.com/joshmoore/openmicroscopy/commit/93f68cbe899cf37af64e57c84953dce1566a5761 -- happy to discuss.

**Comment by dominikl** [comment]
@joshmoore Shouldn't be a huge conflict, I just have single line change in build.xml, the other changes won't conflict imho.

**Comment by manics** [comment]
Looks good to me

**Comment by pwalczysko** [comment]
Retested Make Movie just now. Works fine.

**Comment by sbesson** [comment]
Given all comments above, merging in order to fix the conflict with the decoupling branch. Thanks all.

**Pull request merged**
