### PR TITLE
Use precise (rebased onto metadata53)

### PR DESCRIPTION
**Pull request by manics**
This is the same as gh-5411 but rebased onto metadata53.

----

# What this PR does

specify dist

# Testing this PR

Nothing to test

### CODE REVIEW

**Comment by manics** [comment]
--rebased-from #5411

**Comment by joshmoore** [comment]
Hopefully we can go green again!

**Comment by jburel** [comment]
Since that patch, the mainline now uses trusty see https://github.com/openmicroscopy/openmicroscopy/pull/5409
That changes was not ported to metadata53
I can open a PR if it is useful

**Comment by joshmoore** [comment]
If you are happy with the state of the mainline, yes, a PR to synchronize would be useful.

**Comment by jburel** [comment]
it works fine on develop. We might have to change in few months when the problem is fixed but that should be easy.
I will open a PR today

**Comment by jburel** [comment]
This will not be possible metadata 53 is missing a requirement file specific for ice35 
this will lead to some ice version mismatch

**Comment by manics** [comment]
What are the missing requirements?

**Comment by jburel** [comment]
For 5.3.3 I had to introduce an extra file https://github.com/openmicroscopy/openmicroscopy/pull/5324 (not the best! but did not want to change everything in a point release)
otherwise web will not work with ice 3.5 (depending on installation).
and I use ``requirements-py27-all-ice35.txt`` in travis.yml
The ``requirements-py27-all.txt`` will install ``zeroc-ice`` for ice 3.6

**Comment by joshmoore** [comment]
Any reason to not also introduce the file on metadata53?

**Pull request merged**
