### PR TITLE
ROI point icon in toolbar

### PR DESCRIPTION
**Pull request by dominikl**
# What this PR does

Changes the icon for the Point ROI in the toolbar to be the same as used in the ROI table.

# Testing this PR

Check that the icon is displayed properly and is more intuitive than the previous one.

# Related reading

[RFE: anti-aliasing in measurement tool icons](http://trac.openmicroscopy.org/ome/ticket/13167)

### CODE REVIEW

**Comment by mtbc** [comment]
Good to merge.

**Comment by gusferguson** [comment]
@dominikl 

Tested with OMERO.insight-5.3.0-m2-738-9a3a362-ice35-b348-mac eel user-3

New icon as expected in toolbar.
Good to merge.

**Comment by jburel** [comment]
is the 22 icon used anywhere else?
If not we can remove it

**Comment by jburel** [comment]
@dominikl: do you want to remove the icon if no longer used?

**Comment by jburel** [comment]
@dominikl: thanks

**Pull request merged**
