### PR TITLE
Advanced email configuration

### PR DESCRIPTION
**Pull request by joshmoore**
To follow-on from the recent mail improvements, this PR introduces a few build modifications as well as listener objects to allow for a more sysadmin-directed configuration of system notifications. One of the main benefits is that it is now possible to write **integration tests** for mail behaviors.

### Deployment changes ###
 * Support `classpath*:blitz/*.xml` such that Spring bean files can be added under etc/ and be picked up automatically.
 * Support `export OMERO_PROFILE=/opt/omero-config/` as another location for XML (Note the ending slash)

### Server-side code changes ###
 * Moved MailUtil to new `ome.services.mail` package (cc: @aleksandra-tarkowska)
 * Remove `ShapeChangeMessage` (unused)
 * Remove old spring xml files
 * Add `SqlAction.getUserEmailsByGroup()`
 * Add a `ShutdownMessage` raised in `ome.services.blitz.Entry`
 * Add `subethasmtp.jar` dependency, by default the runtime doesn't access it. Uncommenting or copying a blob from `spring-cfg/mail.xml` to some other location will start up a SMTP server.

### Functional email changes ###
 * Send emails during certain events **if activated**:
    * When a new user is added @ehrenfeu
    * When a server starts
    * When a server shuts down

### Test setup ###
 * Make a new directory for placing your config files (e.g. /tmp/cfg) and subdirectory blitz (/tmp/cfg/blitz/)
 * Set that directory as a location for loading config, `export OMERO_PROFILE=/tmp/cfg/`
 * Copy the two files from etc/blitz/ and rename:
   * `mv etc/blitz/mail-server.example /tmp/cfg/blitz`
   * `mv etc/blitz/mail-senders.example /tmp/cfg/blitz`
 * Restart the server
 * Make sure `root` has a password: `bin/omero obj update Experimenter:0 email=test@localhost`

### Testing ###
 * Run: `test/integration/test_mail.py`. Note: this is being run by the CI infrastructure as well.
 * Verify that one of the actions configured (comment on image or new user) create a MapAnnotation as expected.

--no-rebase

### CODE REVIEW

**Comment by ehrenfeu** [comment]
Amazing! Would it support sending mails upon first user login as well? For us, this would be much more important than upon group creation...

**Comment by joshmoore** [comment]
@ehrenfeu: perhaps first LDAP user login, when the user is created? The other might be quite a heavy query overhead (but I can look into it).

**Comment by ehrenfeu** [comment]
@joshmoore yes, exactly this. First LDAP user login is crucial for us. For other account types, we don't care - that's anyway us actively creating them :smirk:

**Comment by joshmoore** [comment]
Makes since. It's as easy as anything else here, so happy to oblige.

**Comment by joshmoore** [comment]
Based on https://ci.openmicroscopy.org/view/Breaking/job/OMERO-5.1-breaking-trigger/314/ removing breaking.

**Comment by sbesson** [comment]
With this PR included, logs of the merge server throw errors of the following type

```
Caused by: org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [ome.system.OmeroContext]: Constructor threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'internal-ome.api.IShare' defined in class path resource [ome/services/service-ome.api.IShare.xml]: Cannot resolve reference to bean 'internal-ome.api.IAdmin' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'internal-ome.api.IAdmin' defined in class path resource [ome/services/service-ome.api.IAdmin.xml]: Cannot resolve reference to bean 'mailSender' while setting constructor argument; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'mailSender' is defined
```

**Comment by joshmoore** [comment]
@sbesson : thanks for the heads up. @pwalczysko : this is happening for Indexer and PixelData, i.e. neither of those will work with the current trout/merge build. A fix should only take 5 minutes, but would require a restart.

**Comment by joshmoore** [comment]
That fix works for me locally, @sbesson

**Comment by joshmoore** [comment]
https://ci.openmicroscopy.org/job/OMERO-5.1-merge-integration-python/390/testReport/test.integration.test_mail/TestMail/testEveryone/ -- thanks, @sbesson !

**Comment by joshmoore** [comment]
Final adjustments pushed and testing description updated. @sbesson, some CI modifications might be in order if you have no objections.

**Comment by sbesson** [comment]
Tested locally following the deployment scenario. User creation via the CLI led to the creation of map annotation .

```
2015-03-13 17:09:37,143 INFO  [        ome.services.util.ServiceHandler] (.0.1:51871)  Executor.doWork -- ome.services.mail.MapAnnotationSubethaListener.deliver[]
2015-03-13 17:09:37,201 INFO  [   o.s.mail.MapAnnotationSubethaListener] (.0.1:51871) Saved email: MapAnnotation:2
2015-03-13 17:09:37,207 INFO  [                 org.perf4j.TimingLogger] (.0.1:51871) start[1426266577143] time[63] tag[omero.call.success.ome.services.mail.MapAnnotationSubethaListener$1.doWork]
```

Additionally, integration tests are green https://ci.openmicroscopy.org/job/OMERO-5.1-merge-integration-python/393/testReport/test.integration.test_mail/. Merging this. Thanks @joshmoore. Next step is to put a scenario/documentation into place to cover these new functionalities as part of the post-code freeze testing.

**Pull request merged**
