### PR TITLE
Improve rendering of Image metadata details

### PR DESCRIPTION
**Pull request by chris-allan**
This is a fairly straight-forward change that should help improve the rendering
performance of the right-hand metadata panel for Images. Previously, in order
to get the list of Channel labels to display, the template would have to load
the image's pixels, the pixel's channels, and then each channel's logical
channel. With this change, the relevant labels are retrieved directly via HQL
query.

### Benchmarking

The following are times taken to render the complete template for the right-hand side panel. The first number in each set represents a plate with 3 wells, the last two a fully-populated plate.

* Before changes:
- 0:00:01.550193
- 0:00:02.114671
- 0:00:02.787666

* After switching to `getChannelLabels`:
- 0:00:00.118799
- 0:00:02.053346
- 0:00:02.155348

* `getChannelLabels` combined with `original_file_paths` optimizations from #3695 
- 0:00:00.085634
- 0:00:00.080752
- 0:00:00.080852

### CODE REVIEW

**Comment by will-moore** [comment]
Although you're not using the channel wrappers in the template, you still have ```{% with channels=manager.channel_metadata %}``` in the template, and the Channel wrappers are still being loaded with
```
#views.py
# Load channel metadata if appropriate
manager.channelMetadata(noRE=True)

# call this in container.py
self.channel_metadata = img.getChannels(noRE=noRE)
```

**Comment by will-moore** [comment]
NB: this code changed recently in https://github.com/openmicroscopy/openmicroscopy/pull/3733
Otherwise, code looks fine and displayed channel names are same as before.

**Comment by chris-allan** [comment]
Yep, thanks @will-moore. It's the curse of trying to port this stuff from `5.0.x` to `5.1.x`. I wanted to look at exactly that but I was bogged down by unit compatibility. I'm looking at it now so we can be sure to minimise that overhead as much as possible.

Couple more commits with respect to that to come.

**Comment by chris-allan** [comment]
Additional commits to make use of `{% with ... %}`. This results in actual caching of results and avoids repeated recreation of `WellSampleWrapper` instances.

**Comment by will-moore** [comment]
@chris-allan This line in ```container.py``` 
```
self.channel_metadata = img.getChannels(noRE=noRE)
```
is still getting called from this point in views.py when loading right panel
```
        # Load channel metadata if appropriate
        manager.channelMetadata(noRE=True)
```
even though this isn't being used. If you comment out ``` #manager.channelMetadata(noRE=True) ``` in views.py you'll see that loading right panel is faster!
So I would do this at a minimum.
Maybe the container.py code can also be removed - haven't looked too closely yet.

**Comment by chris-allan** [comment]
Yeah, I was really cautious about removing that as other people might be relying on it being in place. It's certainly not used by any of our templates.  `channel_metadata` was added to the container for metadata details in 5.1.1 as part of #3733, no? I can certainly remove it but if other people are relying on it being in place then stuff is going to break. Quite spectacularly.

Thoughts?

**Comment by chris-allan** [comment]
After further discussion with @will-moore, removed the load that is part of `webclient/views.py` in 4d541e49fe1d094f6f4453dd19ab0caf6dcb9861.

**Comment by will-moore** [comment]
@chris-allan I can't find any use of ```channel_metadata``` except in ```views.py``` when loading the Metadata panel:
```
        manager.channelMetadata()
        for theC, ch in enumerate(manager.channel_metadata):
            ...
```
You're effectively replacing #3733 which added that call.

**Comment by chris-allan** [comment]
Yep, which was added to the container interface as part of the 5.1.1 milestone. We know what's in use in our code. I'm only concerned about what someone else, out with the project, may have done while relying on the interface established where `channel_metadata` is populated and/or `channelMetadata()` has been called.

If you're happy accepting those possibilities and don't think they are a problem, then so am I.

**Comment by aleksandra-tarkowska** [comment]
Noticed about 40% better response time. Looks good to me

**Comment by sbesson** [comment]
Thanks guys.

**Pull request merged**
