### PR TITLE
OMERO Java Gateway

### PR DESCRIPTION
**Pull request by dominikl**
This is the old #3704 PR but rebased onto decoupling.

### CODE REVIEW

**Comment by dominikl** [comment]
Does anyone know why all my unit tests are lost? I cherry-picked the commits, e. g. see 567178bc83c9e , but if you check out the branch all my stuff under /components/tools/OmeroJava is missing.

**Comment by sbesson** [comment]
See failing/skipped `integration.gateway` tests at https://ci.openmicroscopy.org/view/DEV/job/OMERO-DEV-merge-integration-java/27/testngreports/

**Comment by jburel** [comment]
add  null check in case a failure occurred during connection
in tearDown

**Comment by sbesson** [comment]
Given the state of https://ci.openmicroscopy.org/view/DEV/job/OMERO-DEV-merge-integration-java/29/, mergieng this.

**Pull request merged**
