### PR TITLE
Modify group membership only

### PR DESCRIPTION
**Pull request by will-moore**
# What this PR does

Allows restricted Admins with only ```ModifyGroup``` privilege or only ```ModifyGroupMembership``` to use the edit-Group form without problems.
See https://trello.com/c/vX34H2wn/73-lightadmin-and-webadmin-ui

All the form functionality has been refactored, so needs a complete re-test:

# Testing this PR

1. Scenarios for user with only ```ModifyGroup``` privilege:
    - Create new group - Form should only show name, description & permissions (not add owners/members).
    - First omit the group name and Save, then enter the name of an existing group and Save (should see suitable error each time)
    - Then enter all valid details and Save. Should be returned to All Groups table with new Group created
    - Edit the group and try again to enter an existing group name or no group name and check for warnings.
    - Then enter valid new name and Save.
 1. [Now Login as root and create a new user who is ONLY in the above group]
 1. Scenarios for user with ```ModifyGroupMembership``` privilege:
    - Viewing webadmin/groups/ table, should see no "Create Group" button, but can edit groups.
    - Edit the group created above - Form should only show Owners and Members fields.
    - Add yourself and other users to be group members / owners & Save
    - Try to remove the user who is ONLY in this group - should see a suitable warning (and form should refresh to add user back).
    - Should be able to remove yourself from this group (but not from 'system' group).
 1. Scenarios for user with ```ModifyGroup``` AND ```ModifyGroupMembership``` privilege:
    - Create a new Group and add owners & members in one shot
    - Edit Group and Group Membership at the same time, testing Save with various invalid inputs as above.

screen shot 2017-08-17 at 10 19 11

screen shot 2017-08-17 at 10 14 47

### CODE REVIEW

**Comment by dominikl** [comment]
Test: "First omit the group name and Save, then enter the name of an existing group and Save (should see suitable error each time)"
Error is displayed, Save button gets disabled. But there's no way to get the Save button enabled again. Have to Cancel and start again. Same for 'Edit group' form.

**Comment by dominikl** [comment]
Sorry, was probably testing with the wrong branch, will use web-dev-merge.

**Comment by dominikl** [comment]
Everything works now, except:
- Test 3, "Add yourself..." Can't add myself to group, can't find user.
- Test 4, "Create a new Group and add owners & members in one shot" throws exception, see qa-staging report 9731. But edit works.

I used user 'tmpLadmin' on web-dev-merge.

**Comment by will-moore** [comment]
That bug in creating a group was also picked up by test which should be fixed by commit above https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-merge-integration-Python27/632/testReport/OmeroWeb.test.integration.test_csrf/TestCsrf/test_create_group/

**Comment by will-moore** [comment]
@dominikl I didn't seem to have any problems finding myself (tmpLadmin) to add to new group?
screen shot 2017-08-18 at 16 18 43

**Comment by dominikl** [comment]
You're right, sorry. Wasn't aware that the box works with first/lastname but not with the user name.

**Comment by will-moore** [comment]
Ah, wasn't aware of that either!

**Comment by dominikl** [comment]
Thanks, crash has been fixed, works now like expected. Good to merge from my point of view 👍

**Comment by jburel** [comment]
Do you have some robot tests?

**Comment by will-moore** [comment]
No. We never have had any robot tests since these forms don't have much/any JavaScript functionality.
But I do need to add some integration tests as in https://github.com/openmicroscopy/openmicroscopy/pull/5394

**Comment by will-moore** [comment]
New tests passing at https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-merge-integration-Python27/643/testReport/OmeroWeb.test.integration.test_webadmin/TestGroups/

**Review by mtbc — APPROVED** [review]

**Pull request merged**
