### PR TITLE
Read only tables

### PR DESCRIPTION
**Pull request by joshmoore**
# What this PR does

HDF5 tables that are copied into place, read-only, should still be accessible via the OMERO.tables API.

# Testing this PR

1. Create an OMERO.tables file (e.g. with populate_metadata)
2. `chmod a-w` on the file under `/OMERO/Files`
3. Try to open the file via `openTable`
4. Without this PR, the open will fail with an `IOError`. With this PR, the file will be opened but not be writable.

# Related reading

* https://trello.com/c/H0tV3G7h/5-read-only-omero-tables

### CODE REVIEW

**Comment by manics** [comment]
`res.openTable(omero.model.OriginalFileI(14184453,False))` returns `None`

Tables-0.log:

```
2016-11-02 19:34:28,160 INFO  [                            omero.remote] (Dummy-3   )  Meth: TablesI.getTable
2016-11-02 19:34:28,161 INFO  [                    omero.tables.TablesI] (Dummy-3   ) getTable: 14184453 {'omero.group': '-1'}
2016-11-02 19:34:28,175 INFO  [                 omero.tables.HdfStorage] (Dummy-3   ) /data/OMERO/Files/Dir-014/Dir-184/14184453 not writable (mode=a). Opening read-only
2016-11-02 19:34:28,476 INFO  [                            omero.remote] (Dummy-3   )  Excp: [Errno 9] Bad file descriptor
2016-11-02 19:34:28,477 WARNI [                            omero.remote] (Dummy-3   ) <function getTable at 0x48e50c8> raised a non-ServerError (<type 'exceptions.IOError'>): [Errno 9] Bad file descriptor
```

File exists and is readable by `omero`:

```
$ ls -l /data/OMERO/Files/Dir-014/Dir-184/14184453
lrwxrwxrwx. 1 root root 111 Nov  2 15:32 /data/OMERO/Files/Dir-014/Dir-184/14184453 -> /uod/idr/features/idr0002-heriche-condensation/screenA/tables/idr0002-heriche-condensation-screenA-plate-all.h5

$ ls -lL /data/OMERO/Files/Dir-014/Dir-184/14184453
-rw-rw-r--. 1 nobody nobody 1065853300065 Jul 13 10:26 /data/OMERO/Files/Dir-014/Dir-184/14184453

$ sudo -iu omero file -L /data/OMERO/Files/Dir-014/Dir-184/14184453
/data/OMERO/Files/Dir-014/Dir-184/14184453: Hierarchical Data Format (version 5) data
```

```
$ /home/omero/OMERO.server/bin/omero -q obj get OriginalFile:14184453
atime=
ctime=
hash=da39a3ee5e6b4b0d3255bfef95601890afd80709
hasher=ChecksumAlgorithm:6
id=14184453
mimetype=type/unknown
mtime=1478100637000
name=idr0002-heriche-condensation-screenA-plate-all.h5
path=/uod/idr/idr0002-heriche-condensation/screenA/tables/
size=1065853300065
version=
```

**Comment by joshmoore** [comment]
On the very first invocation after starting tables or only subsequent? Where are you testing?

**Comment by joshmoore** [comment]
Also, for myself:

```
./components/tools/OmeroPy/src/omero/tables.py:229:21: E122 continuation line missing indentation or outdented
./components/tools/OmeroPy/test/integration/tablestest/test_service.py:660:9: F841 local variable 'ofile' is assigned to but never used
./components/tools/OmeroPy/test/integration/tablestest/test_service.py:683:9: F841 local variable 'read_only' is assigned to but never used
./components/tools/OmeroPy/test/integration/tablestest/test_service.py:683:44: F821 undefined name 'file_path'
./components/tools/OmeroPy/test/integration/tablestest/test_service.py:687:9: E303 too many blank lines (3)
```

**Comment by manics** [comment]
```
vagrant up training-server
vagrant ssh training-server
sudo -iu omero
omego/bin/omego upgrade --sym OMERO.server --ci https://metadata-ci/ --branch OMERO-build -v

OMERO.server/bin/omero login -s localhost -u root -w omero

res = client.getSession().sharedResources()
t = res.newTable(0, 'test.h5')
# t is None
```

Tables-0.log:

```
2016-11-03 11:47:05,641 INFO  [                            omero.remote] (Dummy-3   )  Meth: TablesI.getTable
2016-11-03 11:47:05,672 INFO  [                    omero.tables.TablesI] (Dummy-3   ) getTable: 68 {'omero.group': '-1'}
2016-11-03 11:47:05,757 INFO  [                 omero.tables.HdfStorage] (Dummy-3   ) /OMERO/Files/68 not writable (mode=a). Opening read-only
2016-11-03 11:47:05,793 ERROR [                 omero.tables.HdfStorage] (Dummy-3   ) HDFStorage initialized with bad path: /OMERO/Files/68: ``/OMERO/Files/68`` does not exist
2016-11-03 11:47:05,803 INFO  [                            omero.remote] (Dummy-3   )  Excp: exception ::omero::ValidationException
{
    serverStackTrace = None
    serverExceptionClass = None
    message = HDFSt
```

File doesn't exist but `omero` user has write access:

```
[omero@localhost ~]$ ls -l /OMERO/Files/68
ls: cannot access /OMERO/Files/68: No such file or directory
[omero@localhost ~]$ touch /OMERO/Files/tmp
[omero@localhost ~]$ rm /OMERO/Files/tmp
```

Similarly on a second attempt at `newTable`.

Going back to the release OMERO works:

```
OMERO.server/bin/omero admin stop
OMERO.server-5.2.6-ice35-b35/bin/omero admin start

OMERO.server/bin/omero shell --login

res = client.getSession().sharedResources()
t = res.newTable(0, 'test.h5')
# t: 4FCDFFC3-5922-433E-A491-570756CFD0F4 -t -e 1.0 @ Tables-0.TablesAdapter
```

**Comment by manics** [comment]
And Blitz-0.log

```
2016-11-03 11:47:05,440 INFO  [       ome.security.basic.CurrentDetails] (l.Serv
er-5) Adding log:INSERT,class ome.model.core.OriginalFile,68
2016-11-03 11:47:05,443 INFO  [                 org.perf4j.TimingLogger] (l.Serv
er-5) start[1478173625422] time[21] tag[omero.call.success.ome.services.blitz.im
pl.SharedResourcesI$3.doWork]
2016-11-03 11:47:05,443 INFO  [        ome.services.util.ServiceHandler] (l.Serv
er-5)  Rslt:    ome.model.core.OriginalFile:Id_68
2016-11-03 11:47:05,444 INFO  [        ome.services.util.ServiceHandler] (l.Serv
er-5)  Executor.doWork -- ome.services.blitz.impl.SharedResourcesI.checkOriginal
FilePermissions[68]
2016-11-03 11:47:05,444 INFO  [        ome.services.util.ServiceHandler] (l.Serv
er-5)  Args:    [null, InternalSF@608195686]
2016-11-03 11:47:05,458 INFO  [         ome.security.basic.EventHandler] (l.Serv
er-5)  Auth:    user=0,group=0,event=null(User),sess=b6f0cd13-f5cc-4462-ba0e-418
92e150b06
2016-11-03 11:47:05,463 INFO  [                 org.perf4j.TimingLogger] (l.Serv
er-5) start[1478173625444] time[18] tag[omero.call.success.ome.services.blitz.im
pl.SharedResourcesI$4.doWork]
2016-11-03 11:47:05,463 INFO  [        ome.services.util.ServiceHandler] (l.Serv
er-5)  Rslt:    ome.model.core.OriginalFile:Id_68
2016-11-03 11:47:05,499 INFO  [        ome.services.blitz.fire.Registry] (l.Serv
er-5) Found 2 table services(s) : [Tables-0 -t -e 1.1 @ Tables-0.TablesAdapter,
Tables -t -e 1.1:tcp -h 10.0.2.15 -p 36128]
```

**Comment by joshmoore** [comment]
Ah, I think I see the problem. I assume I refactored my if statement but kept using my pre-existing test, i.e. I broke creation. Thanks.

**Comment by joshmoore** [comment]
Fix pushed, @manics. Sorry about that.

**Comment by manics** [comment]
portalocker has a problem with files symlinked to NFS:

```
$ git diff src/omero/tables.py
diff --git a/components/tools/OmeroPy/src/omero/tables.py b/components/tools/OmeroPy/src/omero/tables.py
index ce4184d..a694246 100644
--- a/components/tools/OmeroPy/src/omero/tables.py
+++ b/components/tools/OmeroPy/src/omero/tables.py
@@ -126,16 +126,23 @@ class HdfList(object):
                 None, None, "Parent directory does not exist: %s" % parent)

         hdffile = hdfstorage.openfile("a")
+        self.logger.info('hdffile: %s' % hdffile)
         fileno = hdffile.fileno()
+        self.logger.info('hdffile fileno: %s' % fileno)

         try:
             portalocker.lockno(
                 fileno, portalocker.LOCK_NB | portalocker.LOCK_EX)
         except portalocker.LockException:
+            self.logger.error('portalocker failed: LockException: %e' % e)
             hdffile.close()
             raise omero.LockTimeout(
                 None, None,
                 "Cannot acquire exclusive lock on: %s" % hdfpath, 0)
+        except Exception as e:
+            self.logger.error('portalocker failed: Exception: %s' % e)
+            hdffile.close()
+            raise
         except:
             hdffile.close()
             raise
@@ -148,6 +155,7 @@ class HdfList(object):
             self.__filenos[fileno] = hdfstorage
             self.__paths[hdfpath] = hdfstorage

+        self.info('hdffile: %s' % hdffile)
         return hdffile

     @locked
```

`res.openTable(omero.model.OriginalFileI(14184782))`

```
2016-11-04 17:02:08,839 INFO  [                            omero.remote] (Dummy-3   )  Meth: TablesI.getTable
2016-11-04 17:02:08,840 INFO  [                    omero.tables.TablesI] (Dummy-3   ) getTable: 14184782 {'omero.group': '-1'}
2016-11-04 17:02:08,850 INFO  [                 omero.tables.HdfStorage] (Dummy-3   ) /data/OMERO/Files/Dir-014/Dir-184/14184782 not writable (mode=a). Opening read-only
2016-11-04 17:02:08,857 INFO  [                    omero.tables.HdfList] (Dummy-3   ) hdffile: /data/OMERO/Files/Dir-014/Dir-184/14184782 (File) 'OMERO HDF Measurement Storage'
Last modif.: 'Fri Nov  4 16:30:17 2016'
Object Tree:
/ (RootGroup) 'OMERO HDF Measurement Storage'
/OME (Group) ''
/OME/ColumnDescriptions (Array(1,)) ''
/OME/ColumnTypes (Array(1,)) ''
/OME/Measurements (Table(0,)) ''

2016-11-04 17:02:08,857 INFO  [                    omero.tables.HdfList] (Dummy-3   ) hdffile fileno: 13
2016-11-04 17:02:08,857 ERROR [                    omero.tables.HdfList] (Dummy-3   ) portalocker failed: Exception: [Errno 9] Bad file descriptor
2016-11-04 17:02:08,859 INFO  [                            omero.remote] (Dummy-3   )  Excp: [Errno 9] Bad file descriptor
2016-11-04 17:02:08,859 WARNI [                            omero.remote] (Dummy-3   ) <function getTable at 0x56ea0c8> raised a non-ServerError (<type 'exceptions.IOError'>): [Errno 9] Bad file descriptor
```

I think I've ruled out all local possibilities (e.g. file permissions, file owner, local symlinks)

**Comment by joshmoore** [comment]
This is working for non-NFS mounted files but needs further work. Merging for inclusion in the 0.3.0-rc3 build.

**Comment by joshmoore** [comment]
Running into this again:

 * https://github.com/nipy/nipype/issues/1370
 * http://issues.roundup-tracker.org/issue1063890

I'm considering either detecting this error across the board and ignoring it (i.e. don't lock) or permitting an option to say to ignore it.

**Comment by joshmoore** [comment]
e.g.

```
[omero@610069be9528 ~]$ diff tables.py_old tables.py_new
138a139,146
>         except IOError, ie:
>             if ie.errno == 9:  # Bad File Descriptor (NFS)
>                 hdffile.close()
>                 hdffile = hdfstorage.openfile("r")
>                 fileno = hdffile.fileno()
>             else:
>                 hdffile.close()
>                 raise
```

**Pull request merged**
