### PR TITLE
Have DiskUsage request include contents of Folders

### PR DESCRIPTION
**Pull request by mtbc**
Tested by http://regions-ci.docker.openmicroscopy.org:8080/job/OMERO-start/lastCompletedBuild/testReport/integration/DiskUsageTest/.

### CODE REVIEW

**Comment by joshmoore** [comment]
`bin/omero fs usage Folder:252` (the only one currently in the integration DB) passes, but returns 0.0

The comment in the fs.py plugin might should be updated:

```
This command shows the total disk usage of various objects including:
ExperimenterGroup, Experimenter, Project, Dataset, Screen, Plate, Well,
WellSample, Image, Pixels, Annotation, Job, Fileset, OriginalFile.
...
```

**Comment by joshmoore** [comment]
On importing an image:

```
bash-4.1$ bin/omero import josh.fake
...
Other imported objects:
Fileset:671
Image:4835
2016-02-09 10:42:40,525 3252       [l.Client-0] INFO      ome.formats.importer.cli.ErrorHandler - Number of errors: 0

==> Summary
1 file uploaded, 1 fileset created, 1 image imported, 0 errors in 0:00:01.269
bash-4.1$ bin/omero -q obj new FolderImageLink parent=Folder:252 child=Image:4835
FolderImageLink:56
bash-4.1$ bin/omero -q fs usage Folder:252
Total disk usage: 50286 bytes in 3 files
bash-4.1$ bin/omero -q fs usage Image:4835
Total disk usage: 50286 bytes in 3 files
bash-4.1$ bin/omero -q delete Image:4835
omero.cmd.Delete2 Image:4835 ok
bash-4.1$ bin/omero -q fs usage Folder:252
```

:thumbsup: ( I assume there's no expectation that having a ROI in a folder will change the size reported? )

**Comment by mtbc** [comment]
Yes, ROIs oughtn't change the size unless you add an attachment to the ROI or its Shapes. (`DiskUsageI` doesn't actually yet look for masks with additional images though perhaps it ought.)

**Comment by joshmoore** [comment]
@mtbc et al: is that worth testing? Sorry, if not, I'm fine with this as stands.

**Comment by mtbc** [comment]
I think it remains only to confirm that my doc wording change is what you'd intended.

**Comment by joshmoore** [comment]
Yup, works for me.

**Pull request merged**
