### PR TITLE
search by annotation type

### PR DESCRIPTION
**Pull request by will-moore**
# What this PR does

See https://trello.com/c/HBZKcjw8/42-search-by-specific-annotations
This allows users to search by "File" and "Tag" annotations, not just by All annotations.

# Testing this PR

1. Find or create projects, datasets, images etc that have the same keyword in name OR Comment OR tag OR file content (e.g. add image to figure, add keyword in label and export to PDF to attach PDF to image).

 2. Search for keyword. By default you should find results with keyword in Name, Tag and File.

 3. Check the "Annotations" filter checkbox. Radio buttons should be shown, with "All annotations" checked by default. This should find results with Comment, Tag and File.

4. Check the Tag or File radio buttons. Now should only find results with Tag or File respectively.

5. Uncheck the "Annotations" checkbox to hide the radio buttons. Now we should get results for Name and Annotations as before.

screen shot 2018-01-22 at 10 55 01

### CODE REVIEW

**Comment by jburel** [comment]
@will-moore could you open it against workflows?

**Comment by will-moore** [comment]
Done - where will this be deployed for testing?

**Comment by jburel** [comment]
https://trello.com/c/hdHcpvXc/82-build-info

**Comment by jburel** [comment]
We will need some robots tests for that change
But for that we need to wait for my PR to be merged otherwise it will conflict

**Comment by jburel** [comment]
4 test failures due to this PR https://10.0.51.135:32784/job/OMERO-robot/5/
I think we should merge #5606 and take it from there

**Comment by jburel** [comment]
@will-moore I have merged the robot PR so you can now fix the tests

**Comment by pwalczysko** [comment]
Studying this setup https://github.com/openmicroscopy/openmicroscopy/pull/5631#issuecomment-359401485 there is just root/omero in the db and some ad-hoc groups/users (2 or 3). 

I created the user-1...user-12 setup, and imported 2 datasets for majority of users. But this makes me think, that considering this is a search PR, we should test on the golden db. But how to deploy it on the devspace - manually somehow copy it and unzip it in the appropriate docker (which is which one ?) @will-moore @jburel

**Comment by jburel** [comment]
we could adjust the configuration of the ``omero-server`` job

**Comment by pwalczysko** [comment]
First tests show that the functionality works as expected.

  - the checkbox on Annotations works as expected
  - the radio buttons on All Annotations, Files and Tags work as expected for Tags and All Annot.
  - the tag search (for objects tagged with multiple tags) with AND logic is now possible 

Still to test:

  - the files behaviour
  - the case of "my image is tagged with someone else's tag, do I find it ?"
  - testing on more complex DB (see my comment above)

**Comment by jburel** [comment]
@pwalczysko I can include this PR into my workflows PR (https://github.com/openmicroscopy/openmicroscopy/pull/5635) opened  again to test robot tests on CI master
so you could evaluate the remaining items

**Comment by pwalczysko** [comment]
Yes please @jburel

**Comment by jburel** [comment]
@pwalczysko done

**Comment by pwalczysko** [comment]
the additional tests https://github.com/openmicroscopy/openmicroscopy/pull/5631#issuecomment-360086350 performed on web-dev-merge (user-4, user-3, user-9). File (pdf from ppt and from Figure) as well as Tags behave as expected. The case of another user tagging my data with their tag is covered and makes sense. Filtering for my data and other users' data works as before (= as expected).

Ready to merge FMPOV.

**Comment by jburel** [comment]
Thanks @pwalczysko 
The robot tests are also passing in devspace

**Pull request merged**
