### PR TITLE
Update xercesImpl version to 2.8.1

### PR DESCRIPTION
**Pull request by melissalinkert**
See http://trac.openmicroscopy.org/ome/ticket/12287.  This updates xercesImpl from 2.6.2 to 2.8.1, as 2.8.1 is required for reading JPEG EXIF data.

--depends-on openmicroscopy/bioformats#1620

### CODE REVIEW

**Comment by pwalczysko** [comment]
All impors of the previously failing jpegs went fine.
Also opening is fine.

But the appearance is different (compared to the same images imported to 5.0, ie. octopus)
See below the 4k x 4k example (top is octopus, below is trout= with this PR on 5.1). I cannot test latest on trout, because the import will fail just as it did on friday.

screen shot 2015-02-23 at 11 39 34
screen shot 2015-02-23 at 11 39 13

**Comment by pwalczysko** [comment]
@melissalinkert @joshmoore @jburel : To be able to double check on imported images, please compare trout merge, user-4, ID: 44914, group read-write (the lower screenshot, 5.1 line) with octopus latest, user-4, ID 23605 (the upper screeenshot, 5.0 line)

**Comment by melissalinkert** [comment]
I definitely see what you mean when opening ID: 44914 in the web client.  It's also odd that the red channel minimum is set on import to 155, when 0 is expected.

The fact that only 4kx4k.jpg and 8kx8k.jpg are affected suggests that this is a pyramid (and possibly JPEG-2000 compression) issue though, not an issue with JPEGs in general.  Do 4kx4k.tif and 8kx8k.tif from test_images_good show a similar problem?  If so, that should rule out this PR as being the cause.

**Comment by sbesson** [comment]
Retested with today's merge build. Same image imports fine and renders as expected. :+1: for merging this PR, its Bio-Formats companion and bumping the submodules.

screen shot 2015-02-24 at 14 28 40
 merge build.

**Comment by pwalczysko** [comment]
Please merge.

**Comment by melissalinkert** [comment]
--no-rebase

**Pull request merged**
