### PR TITLE
Get ROI count 

### PR DESCRIPTION
**Pull request by dominikl**
Same as #4550 rebased to develop.

**Testing**: See https://github.com/openmicroscopy/openmicroscopy/pull/4602#issuecomment-214204547

### CODE REVIEW

**Comment by gusferguson** [comment]
@dominikl 

Tested with
OMERO.insight-5.2.2-393-e464f65-ice36-b292-win
OMERO.insight-5.2.2-393-e464f65-ice35-b292-win
eel user 3 read-only

There is no way to test the ROI folder count with this, as there are no folders.
Did a general check of Measurement Tool functionality - all behaves as normal except for one issue:

- graph pane selected - selection of ROI gives correct display of histogram and so on
- select different ROI - graph pane does not update - need to click second time on image to trigger update (any event - even deselecting ROI)
- appears confined to Graph pane - Inspector pane updates as expected.

I seem to remember this happening before with a PR that changed the updating in a different area.

parallels desktop

parallels desktop

**Comment by dominikl** [comment]
Sorry, I probably should have made this clearer in the PR description. It's just about the "ROI count" display in the metadata panel, nothing in the measurement tool is touched (i.e. also none of the known bugs in the tool are fixed by this PR).
screen shot 2016-04-25 at 09 25 02

**Comment by gusferguson** [comment]
@dominikl 

Retested looking at ROI count in RHP of main window.

Behaves as expected when saving or deleting ROIs in Full Viewer - updates correctly ROI number in RHP.

ROI count does not update in RHP when Yes selected on save prompt when closing Full Viewer with unsaved ROIs.

**Comment by dominikl** [comment]
Thanks @gusferguson . Fixed the issue with the last commit. ROI count should now also update, when the ROIs are saved via the Save Dialog which pops up when you close the image.

**Comment by gusferguson** [comment]
@dominikl 

Tested using OMERO.insight-5.2.2-423-d82c1c8-ice36-b294-mac eel user-3 read-only-1

Behaves as expected.
Good to merge.

**Comment by jburel** [comment]
Thanks

**Pull request merged**
