### PR TITLE
Date filter

### PR DESCRIPTION
**Pull request by jburel**
Unify date displayed in the central panel and the search by date in main search
Also remove hard-coded url

To test:
 * Check that the date displayed in the filtering dialog (central panel) matches the display of the search component.
 * Go to the search tab, Click on the info button next to text field. 
 * Check that the dialog pops up and click on the url.

--no-rebase

### CODE REVIEW

**Comment by joshmoore** [comment]
Kicked travis.

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#827](https://ci.openmicroscopy.org/job/OME-5.1-merge-push/827/). See the [console output](https://ci.openmicroscopy.org/job/OME-5.1-merge-push/827/consoleText) for more details.
Possible conflicts:
  - PR #3571 dominikl 'Right panel adjustments'
    - components/insight/SRC/org/openmicroscopy/shoola/agents/util/EditorUtil.java

**Comment by jburel** [comment]
Closing for now I will re-open when @dominikl is in.

**Comment by dominikl** [comment]
The date has the same format, link to search help website also works. But the filter by date doesn't work, ticking the 'Calendar' checkbox has no effect, filter seems to be ignored. This was broken before, not related to this PR.
Good to merge (if the broken 'filter by date' is tackled in separate PR).

**Comment by jburel** [comment]
Do we have a ticket or item on trello for the issue you mentioned?

**Comment by dominikl** [comment]
No I don't think so. Add it to [Trello - Search and Filtering](https://trello.com/c/btfp8rcP/60-search-and-filtering)?

**Comment by jburel** [comment]
That's a good place

**Comment by dominikl** [comment]
Added it to the card, will have a look at that problem later.

**Comment by dominikl** [comment]
The 'from' and 'to' field is currently not taken into account, it looks like it was intended to be used in conjunction with annotations, e. g. filter by 'has been annotated between from and to', see https://github.com/openmicroscopy/openmicroscopy/blob/c380bbe9146ec568716ddd4f531cfcd613c2d6b7/components/insight/SRC/org/openmicroscopy/shoola/env/data/OmeroMetadataServiceImpl.java#L1861

I think we could keep these fields in the UI and use them for searching for imported/acquired between from and to (implemented in a follow up PR?). Maybe it's possible to just hide this 'Calender' row for now in this PR, as it doesn't have a functionality yet?

**Comment by dominikl** [comment]
Works like expected. Good to merge!

**Comment by joshmoore** [comment]
Anything in the way of screenshots / GUI heads-up for @gusferguson ?

**Comment by jburel** [comment]
in current doc, there is no screenshot for that dialog. More an advanced filtering.

**Comment by gusferguson** [comment]
Current Help workflow not detailed enough to need to include this.

**Pull request merged**
