### PR TITLE
Fix left panel

### PR DESCRIPTION
**Pull request by rgozim**
# What this PR does

Layout changes of left panel:

- Search panel sits at top of left panel
- Search panel title and hints button sit on same vertical plane 
- Well preview (from clicking well image on centre panel) sits correctly at bottom left of left panel
- Making left panel smaller no longer causes tabs & toolbar buttons to wrap

# Testing this PR

Visually inspect listed changes of left panel.

# Related reading

Trello card:
https://trello.com/c/AVmjP5QF/102-bug-blocking-search-panel-css

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#770](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/770/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/770/consoleText) for more details.
Possible conflicts:
  - PR #5402 will-moore 'Create pds for others'
    - components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/containers.html

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#771](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/771/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/771/consoleText) for more details.
Possible conflicts:
  - PR #5402 will-moore 'Create pds for others'
    - components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/containers.html

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#772](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/772/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/772/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/containers.html

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#773](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/773/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/773/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/containers.html

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#774](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/774/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/774/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/containers.html

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#775](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/775/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/775/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/containers.html

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#776](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/776/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/776/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/containers.html

**Comment by will-moore** [comment]
Apart from the minor Z-index issue with the left-panel drag handle overlaying the Groups/Users menu (as discussed), everything is looking good.

**Comment by will-moore** [comment]
The drag handle is now correctly behind the Groups/Users chooser menu.
But, minor point, the vertical line beside the drag handle is missing now:

screen shot 2017-08-25 at 00 00 12

**Comment by jburel** [comment]
@rgozim could you look at the bug reported above so we can merge this PR for 5.4.0

**Comment by will-moore** [comment]
Either in this PR or another, we need a fix for https://github.com/openmicroscopy/openmicroscopy/pull/5403#issuecomment-324952268

**Comment by rgozim** [comment]
Should be sorted now.

**Comment by bramalingam** [comment]
Everything works as expected. Looks good to merge.

**Pull request merged**
