### PR TITLE
prevent data owners from chowning

### PR DESCRIPTION
**Pull request by mtbc**
This PR prevents data owners from chown'ing, that being a safe initial position following discussion with @joshmoore and @will-moore. Integration testing should suffice but feel free to experiment manually via the CLI to confirm.

### CODE REVIEW

**Comment by ximenesuk** [comment]
I'll look at this in light of any doc changes for the CLI plugin. And also as to whether the CLI integration tests need expanding.

**Comment by mtbc** [comment]
https://github.com/openmicroscopy/openmicroscopy/blob/develop/components/tools/OmeroJava/test/integration/chown/PermissionsTest.java is what is on the Java side.

**Comment by pwalczysko** [comment]
https://ci.openmicroscopy.org/view/5.1/job/OMERO-5.1-merge-integration-java/lastCompletedBuild/testngreports/integration.chown/ is passing.

**Comment by pwalczysko** [comment]
Logged in as user-4 to trout merge. On CLI, trying to chown my image ID 27886
As user-4 is not an owner of read-only-1 (from where the image 27886 comes) neither he is an admin, the operation failed as expected. 

```
 [pwalczysko@ome-c6100-3 OMERO-5.1-merge-deploy]$ bin/omero chown 6 Image:27886
Using session fc535f2d-c316-4a52-b22b-0261322ee105 (user-4@localhost:4064). Idle timeout: 10 min. Current group: read-only-1
omero.cmd.Chown2 Image 27886... failed: 'graph-fail'
failed: cannot process ome.model.fs.FilesetEntry[18336]: user 5 is not an owner of group 8
[pwalczysko@ome-c6100-3 OMERO-5.1-merge-deploy]$ 
```

**Comment by pwalczysko** [comment]
User-4 could not chown his image to user-7 because user-7 is not a member of read-write-1 of which user-4 is an owner of. This is probably as expected.

**Comment by pwalczysko** [comment]
User-4 did successfully chown his image to user-5, which is a member of read-write-1 group of which user-4 is an owner of. This is probably as expected as well.

**Comment by ximenesuk** [comment]
I've tried various push, pull and transfer commands with users, owners and admins. All seem to work as expected. The errors messages can sometimes be a little confusing depending when the graph traversal fails:
```
$ omero chown 4 Image:13
Created session 4af3d526-441d-467e-8cde-cc0aca171f32 (user-2@localhost:4064). Idle timeout: 10 min. Current group: private-1
omero.cmd.Chown2 Image 13... failed: 'graph-fail'
failed: not permitted to delete ome.model.fs.FilesetJobLink[61], ome.model.fs.FilesetJobLink[62], ome.model.fs.FilesetJobLink[63], ome.model.fs.FilesetJobLink[64], ome.model.fs.FilesetJobLink[65]
```
Whether these can be managed/improved by the CLI I don't know.

Otherwise things look good to me but I will make a small usage fix to the plugin in a separate PR once this is merged.

**Comment by mtbc** [comment]
https://trello.com/c/F4cAE0k3/358-graphexception-subclasses has some discussion regarding confusing error messages. It would indeed be worth working on, but won't be easy.

**Comment by ximenesuk** [comment]
One further point on the messages is this one which arises when using read-write groups:
```
$ omero chown 8 Image:19
Created session 948a0b0f-f551-4d8e-b7a1-29d091ad1775 (user-6@localhost:4064). Idle timeout: 10 min. Current group: private-1
WARNING: Image:19 belongs to user 6
omero.cmd.Chown2 Image 19... ok
```
I'm not sure how helpful this warning is given the ownership has changed. This warning is raised in https://github.com/openmicroscopy/openmicroscopy/blob/develop/components/tools/OmeroPy/src/omero/cli.py#L1804

**Comment by mtbc** [comment]
Anything further to do or test on this PR, or good to merge? (Happy to remove that warning if desired.)

**Comment by pwalczysko** [comment]
Did not detect any problems here, all good from my side.

**Comment by joshmoore** [comment]
We added the warning in general when acting on other's objects due to the newness of the RWRW case. I'd generally say let's leave that here (and merge) and we can follow up later.

**Pull request merged**
