### PR TITLE
Exclude annotations in CLI delete

### PR DESCRIPTION
**Pull request by ximenesuk**
This PR mirrors the default action in the other clients and does not delete linked annotations (File, Tag and Term) without confirmation.
```
omero delete Image:51
``` 
will delete the image but not its annotations. Whereas
```
omero delete Image:51 --include Annotation
``` 
will also delete the images annotations. Individual annotation types can be selected,
```
omero delete Image:51 --include FileAnnotation
``` 
will delete any linked FileAnnotation objects but not other types. Other annotations can be deleted in the same command,
```
omero delete Image:51 Annotation:101
``` 
will not delete linked annotations but it will delete the separate specified annotation. Individual linked annotations can be deleted by explicitly using their IDs,
```
omero delete Image:51 Annotation:51
```
will delete the linked annotation with the given id but exclude other linked annotations.

--no-rebase

### CODE REVIEW

**Comment by joshmoore** [comment]
Will the excluded objects be printing in a detailed report? I.e. so one could manually clean them up if so desired.

**Comment by ximenesuk** [comment]
As it stands, no. The report is just that which the response provides. I'm open to suggestions here. The easiest option is to do a dry-run (without the default exclusion) and then a diff on the reports after the delete. That would add an overhead to every CLI delete command but would certainly be possible.

**Comment by joshmoore** [comment]
If we do that, it would also be an option for the `rwrw--` WARNING.

**Comment by joshmoore** [comment]
* default arguments seem sensible to me.
 * `--report --dry-run` shows me the difference in the 2 runs: :+1:
 * `--include=Annotation` and `--include=FileAnnotation` (for example) do different (correct) things: :thumbsup:

Barring any further changes you want to make to the report here, I'd say *good to merge*. Since there's another report PR anyway, perhaps hold off?

**Comment by ximenesuk** [comment]
I'd be happy for this to be merged and have any extended report showing diffs as a later PR once gh-3821 is in as well.

**Comment by joshmoore** [comment]
Agreed. Merging. I'll leave you to file a RFE along these lines:

I'd suggest printing a WARNING similar to https://github.com/openmicroscopy/openmicroscopy/pull/3817 when an object is being deleted *without* passing `--include Annotation`. This should optimally be done server-side, but since insight & web are currently doing it locally, it's likely ok to start with a client-side implementation.

cc: @mtbc @jburel @will-moore

**Comment by mtbc** [comment]
Surely one doesn't usually want ``-include Annotation``? For instance, one probably wouldn't want to strip the annotations off other images that aren't being deleted. I may be coming to this late and misunderstanding.

**Comment by joshmoore** [comment]
@mtbc : agreed, but the UI has the benefit of the confirmation dialog. And until we add `--yes`-style functionality to the CLI, the best we can manage is something informational with the hope that people will use `--dry-run`.

**Comment by mtbc** [comment]
Oh! You mean, warn them about annotations that would be deleted *unless* they passed `--include=Annotation`? (Rather than warning them in general anytime they don't pass  `--include=Annotation`.)

**Comment by joshmoore** [comment]
Yes. Just a general re-education program now that `delete Image:$X` will be doing *less* than before.

**Pull request merged**
