### PR TITLE
Test new command-line options for CLI duplicate.

### PR DESCRIPTION
**Pull request by mtbc**
Provides integration testing for https://github.com/ome/omero-cli-duplicate/pull/12.

### CODE REVIEW

**Comment by joshmoore** [comment]
Are there any complex corner cases when using multiple flags?

**Comment by mtbc** [comment]
Good question. Nothing special comes to mind because the underlying code paths are fairly general. It's a good sign if the basic combinations work and it already augurs well that both `DuplicateTest` and `SpecificityClassifierTest` pass: the former also tries combinations and that latter's very much about combining type arguments like that.

**Comment by joshmoore** [comment]
:+1: thanks. Can you describe / point to a conceivable multi-flag use case?

**Comment by mtbc** [comment]
I am not sure how much I'm pushing at the envelope of "conceivable" but,
```
--reference-classes=Annotation
--duplicate-classes=BasicAnnotation,CommentAnnotation
--ignore-classes=Roi
```
should adjust duplication to,
* multiply link to annotations, reusing the existing,
* except it will duplicate some simple not-sharable ones like comments and ratings
* and omit RoIs from the duplication.

**Review by joshmoore — APPROVED** [review]
Looks good. Suggest merging with the rest of the PRs.

**Pull request merged**
