### PR TITLE
ROI example

### PR DESCRIPTION
**Pull request by jburel**
Add support for Point and Line in ROIs example.

### CODE REVIEW

**Comment by jburel** [comment]
@ximenesuk: good point. It usually prefers setter. I followed the structure already in place.
Something to discuss with @will-moore when he gets back, he might be able to remember the reason why it was done that way in the first place.

**Comment by will-moore** [comment]
I have no strong opinion. Setters is fine with me.

**Comment by jburel** [comment]
I have opted: for no setters when creating the shapes and getters when reading the shapes. So it is clear that both can be used.

**Comment by ximenesuk** [comment]
Changes look good to merge.

**Pull request merged**
