### PR TITLE
Rendering toolbar update

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
This PR cleanup stylesheets used for various toolbars. ```.toolbar``` is now in in ```ome.toolbar.css``` and can be used globally. Thanks to that rendering toolbar in right hand panel and image viewer benefits from hover, active, focus, etc styles. To test:

 - choose image, click preview tab, alter channel slider -> appropriate buttons (undo, save) should activate
 - click undo -> redu should activate, save should deactivate
 - click copy settings -> past should activate
 - choose compatible image, check if paste button is active, paste settings -> appropriate buttons (undo, save) should activate

test the same in image viewer

cc: @will-moore 

--no-rebase

### CODE REVIEW

**Comment by will-moore** [comment]
@aleksandra-tarkowska All seems to be working fine. Any change needed to include this in the omeroweb.viewer.min.css, or is that all handled automatically?

**Comment by will-moore** [comment]
I think this might have caused a bug in the ```<ul class="toolbar" > ``` buttons in basket:

screen shot 2015-02-27 at 10 05 34

Caught by Robot tests!

**Comment by aleksandra-tarkowska** [comment]
@will-moore these 2 should resolve all the issues you menationed

**Comment by aleksandra-tarkowska** [comment]
my apology I accidentally deleted remote branch

**Comment by aleksandra-tarkowska** [comment]
As @pwalczysko is going to test rendering in Week 3 could we speed that up please?

**Comment by will-moore** [comment]
@aleksandra-tarkowska Toolbars look and behave fine.
I found an unrelated bug: Preview panel in basket page is broken, but this is already broken in develop - I will fix in another PR. 
Good to merge.

screen shot 2015-03-04 at 10 16 20

**Pull request merged**
