### PR TITLE
have metadata service collate delete requests into one

### PR DESCRIPTION
**Pull request by mtbc**
# What this PR does

This PR adjusts how Insight often submits delete requests, collating deletes for many objects into a single request.

# Testing this PR

Tag a couple of hundred images and in Insight multiselect them and click in the right pane to remove tags from all the images. With this PR the unlinking should occur quite quickly. (Unlinking is deletion of a link.)

This PR's changes are more far-reaching: they affect Insight's deletion more widely. Try other bulk deletes, especially if possible mixing objects that can be deleted with ones that can't (e.g., include in multiselect some else's images or tags) to ensure there are no regressions.

# Related reading

http://trac.openmicroscopy.org/ome/ticket/13139

### CODE REVIEW

**Comment by pwalczysko** [comment]
I just did not see any situation where insight would allow you to delete at all if you multiselect things that you can delete as well as things you cannot delete. In such cases (quite rightly I would think) NO deletion from the UI is possible.

Thus, no regressions spotted by now.
Will continue testing once https://github.com/openmicroscopy/openmicroscopy/pull/4793/commits/1572baf547517733dc73c6191e1d98c18ffab165 fix is in

**Comment by pwalczysko** [comment]
The speedup thanks to this PR is as follows:
  - tag 270 images with a tag on eel merge (this PR included)
  - remove the tag from these 270 images in one go
  - takes some 2-3 seconds
  - repeat the same on eel latest (without this PR)
  -  takes around 30 seconds

**Comment by dominikl** [comment]
👍  Code looks good.

**Comment by pwalczysko** [comment]
Checked the deletion in bulk of things which you can delete together with things you cannot delete. 
  - ROIs
  - Tags
  - Attachments
Checked one permissions situation only, the admin annotating your object in read-only group
All works as expected, only the objects which you have permissions for are deleted, the others are not.

**Comment by mtbc** [comment]
Thank you for hunting these down and testing them.

**Comment by pwalczysko** [comment]
Ready to merge FMPOV.

**Comment by joshmoore** [comment]
Strategy makes sense to me.

**Pull request merged**
