### PR TITLE
add test for null file size in DB

### PR DESCRIPTION
**Pull request by jburel**
# What this PR does
Add integration test for https://github.com/ome/omero-py/pull/181

# Testing this PR

Check that the test passes

cc @joshmoore @kkoz

### CODE REVIEW

**Comment by jburel** [comment]
https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/313/ is green

**Comment by mtbc** [comment]
Should check for an "invalid size" string or somesuch?

**Comment by jburel** [comment]
sorry I am not following? you mean an invalid value in the DB e.g. -1?

**Comment by mtbc** [comment]
I was wondering what is in this `len(downloaded.lines()) == 3` and if we care.

**Comment by jburel** [comment]
We have other tests for that. For that one we do not really care about the content

**Review by manics — APPROVED** [review]
LGTM

**Pull request merged**
