### PR TITLE
Robot remote driver

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
Allow running robot tests using selenium remote server

test via selenium hub https://github.com/openmicroscopy/devspace/pull/20

test locally using:

```
dist/bin/omero --path components/tests/ui/plugins robot config --protocol http --webhost 'your_webserver' --remoteurl 'http://develop-seleniumhub.docker.openmicroscopy.org:4444/wd/hub' --dc 'browserName:${BROWSER},javascriptEnabled:True' > components/tests/ui/resources/config.txt

./build.py -f components/tests/ui/build.xml web-firefox -DTEST=view_image.txt
```

### CODE REVIEW

**Comment by aleksandra-tarkowska** [comment]
Tested via http://develop-ci.docker.openmicroscopy.org:8080/job/OMERO-robot/18/console

To run locally use selenium hub on beluga

http://develop-seleniumhub.docker.openmicroscopy.org:4444/

**Comment by aleksandra-tarkowska** [comment]
echo Running the UI tests

**Comment by will-moore** [comment]
@aleksandra-tarkowska What should the value of ```'your_webserver'``` be?

**Comment by aleksandra-tarkowska** [comment]
it is your webserver host you will run robot test against

**Comment by will-moore** [comment]
I normally run against "localhost". If I set up the config file in the same way I get 
```
$ ./build.py -f components/tests/ui/build.xml web-chrome -DTEST=view_image.txt
Buildfile: /Users/wmoore/Desktop/OMERO/openmicroscopy/components/tests/ui/build.xml
Entering /Users/wmoore/Desktop/OMERO/openmicroscopy/components/tests/ui...

web-chrome:
==============================================================================
View Image :: Tests browsing to an Image and opening Image Viewer             
==============================================================================
Test Open Viewer :: Tests double-click to open image viewer           | FAIL |
Parent suite setup failed:
Location should have been 'http://localhost:4080/webclient/login/' but was 'data:text/html,chromewebdata'
```

**Comment by aleksandra-tarkowska** [comment]
remote hub must be able to access the webserver host. `localhost` won't work

**Comment by will-moore** [comment]
After running with my IP like this:
```
$ dist/bin/omero --path components/tests/ui/plugins robot config --protocol http --webhost '14.36.12.14' --remoteurl 'http://develop-seleniumhub.docker.openmicroscopy.org:4444/wd/hub' --dc 'browserName:${BROWSER},javascriptEnabled:True' > components/tests/ui/resources/config.txt
```

The config.txt file had the ```${REMOTE_URL}``` and ```${DC}``` parameters as expected and also:
```
${USERNAME}             user
${PASSWORD}             SUPER_SECRET
${LAST NAME}            user
${FULL NAME}            user user

# Web config
${WEB HOST}             14.36.12.14
${WEB PREFIX}           
${SERVER_ID}            1
```
I manually edited this with my current_robot user credentials etc...
```
${USERNAME}             robot_user-1458946128
${PASSWORD}             ome
${LAST NAME}            robot_user-1458946128
${FULL NAME}            robot_user-1458946128 robot_user-1458946128

# Web config
${WEB HOST}             14.36.12.14
${WEB PREFIX}           :4080
${SERVER_ID}            1
```

Then ran tests which all failed with timeout:
```
./build.py -f components/tests/ui/build.xml web-chrome -DTEST=view_image.txt
Buildfile: /Users/wmoore/Desktop/OMERO/openmicroscopy/components/tests/ui/build.xml
Entering /Users/wmoore/Desktop/OMERO/openmicroscopy/components/tests/ui...

web-chrome:
==============================================================================
View Image :: Tests browsing to an Image and opening Image Viewer             
==============================================================================
[ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: WebDriverException: Message: Session [e01505c8-b65c-4ee6-aa2d-f6fa5176e739] was terminated due to SO_TIMEOUT
Stacktrace:
    at org.openqa.grid.internal.ActiveTestSessions.getExistingSession (ActiveTestSessions.java:105)
...
WebDriverException: Message: Session [e01505c8-b65c-4ee6-aa2d-f6fa5176e739] was terminated due to SO_TIMEOUT
```

**Comment by will-moore** [comment]
Updated config.txt to include port as HOST
```
${WEB HOST}             my.ip.address.here:4080
${WEB PREFIX}   
```
Now seems to work fine:
```
$ ./build.py -f components/tests/ui/build.xml web-chrome -DTEST=view_image.txt
Buildfile: /Users/wmoore/Desktop/OMERO/openmicroscopy/components/tests/ui/build.xml
Entering /Users/wmoore/Desktop/OMERO/openmicroscopy/components/tests/ui...

web-chrome:
==============================================================================
View Image :: Tests browsing to an Image and opening Image Viewer             
==============================================================================
Test Open Viewer :: Tests double-click to open image viewer           | PASS |
------------------------------------------------------------------------------
Test Prev Next Buttons                                                | PASS |
------------------------------------------------------------------------------
View Image :: Tests browsing to an Image and opening Image Viewer     | PASS |
2 critical tests, 2 passed, 0 failed
2 tests total, 2 passed, 0 failed
==============================================================================
Output:  /Users/wmoore/Desktop/OMERO/openmicroscopy/components/tests/ui/target/reports/web/chrome/output.xml
Log:     /Users/wmoore/Desktop/OMERO/openmicroscopy/components/tests/ui/target/reports/web/chrome/log.html
Report:  /Users/wmoore/Desktop/OMERO/openmicroscopy/components/tests/ui/target/reports/web/chrome/report.html

BUILD SUCCESSFUL
Total time: 1 minute 6 seconds
```

**Comment by aleksandra-tarkowska** [comment]
you should set omero.web.application_server_host and port to generate config file not alter config file manually

**Comment by aleksandra-tarkowska** [comment]
anyway default is tested vi https://ci.openmicroscopy.org/view/DEV/job/OMERO-DEV-merge-robotframework/, webhost arg is tested via http://develop-ci.docker.openmicroscopy.org:8080/job/OMERO-robot/

**Comment by joshmoore** [comment]
:+1: thanks all. @aleksandra-tarkowska : do you need develop merged into metadata52/regions before this is run in the other spaces? cc: @sbesson

**Comment by aleksandra-tarkowska** [comment]
yes, please, that must be propagated across all other branches

**Comment by joshmoore** [comment]
See https://github.com/openmicroscopy/openmicroscopy/pull/4566

**Pull request merged**
