### PR TITLE
Output test - put all to default

### PR DESCRIPTION
**Pull request by pwalczysko**
# What this PR does
As the output form of import commands changed in https://github.com/openmicroscopy/openmicroscopy/pull/4812, this PR is adjusting the import integration tests in such a manner that the new Default output is being tested in all tests. Also, 2 new explicit tests have been added, for the default option output (single image and single and multiple plates).

Give this PR a descriptive title then expand on that here.

# Testing this PR

Check the integration tests are passing.
Check the sensibility of the test additions here.

# Related reading

Note that follow-up PR(s) will add new tests for the 2 new non-default options introduced by the https://github.com/openmicroscopy/openmicroscopy/pull/4812 - A) yaml and B) legacy

### CODE REVIEW

**Comment by pwalczysko** [comment]
@ximenesuk @sbesson @jburel @joshmoore

**Comment by ximenesuk** [comment]
This looks good and other than https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-breaking-integration-python/649/ the tests are passing. Most of the failed tests are due to strict checking of the stderr output which is broken by any exceptions leaking into stderr from Bio-formats. @pwalczysko is going to push a commit that is less strict, just checking the key strings exist.

**Comment by ximenesuk** [comment]
@mtbc would you be able to re-review this on Monday? There were a couple of odd fails in https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-breaking-integration-python/649/testReport/ that I have seen before as intermittent fails but it is suspicious that they are both in the modified tests. They are not, however, in the equivalent Python 2.7 tests https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-breaking-integration-Python27/44/testReport/ which is good, I think!

**Comment by mtbc** [comment]
Sure, have listed for Monday; let's hope all passes. (Not sure if we expect OMERO-DEV-breaking-build to be fixed.)

**Comment by mtbc** [comment]
https://ci.openmicroscopy.org/job/OMERO-DEV-breaking-integration-python/lastCompletedBuild/testReport/OmeroPy.test.integration.clitest.test_import/ is now passing fine so **good to merge**.

**Comment by mtbc** [comment]
@pwalczysko: may want to remove `--breaking` so we can first give this a non-breaking merge-CI runthrough.

**Comment by pwalczysko** [comment]
Removed --breaking. Thank you.

**Comment by mtbc** [comment]
:+1: We might get our runthrough soon when OMERO-DEV-merge-daily is fixed.

**Comment by mtbc** [comment]
Yes, this PR is now in the latest merge https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/463/.

**Comment by pwalczysko** [comment]
The tests seem to have passed. https://ci.openmicroscopy.org/job/OMERO-DEV-merge-integration-python/lastCompletedBuild/testReport/OmeroPy.test.integration.clitest.test_import/TestImport/

Okay to merge @mtbc  ?

**Comment by mtbc** [comment]
Yes, good to merge.

**Pull request merged**
