### PR TITLE
render.py: new CLI plugin for dealing with rendering settings

### PR DESCRIPTION
**Pull request by joshmoore**
See the `bin/omero render -h` output and the test for expected behavior. Primary driver for the creation of `render.py` was scripting the rendering settings along with the imports so that everything could be re-done if necessary:

```
PLATE=$(bin/omero import ... | grep Plate:)
bin/omero render copy Image:1 $PLATE
```

### CODE REVIEW

**Comment by joshmoore** [comment]
This is a work-in-progress but comments on the CLI API are very welcome. cc @ximenesuk @jburel @sbesson @eleanorwilliams @pwalczysko et al.

**Comment by joshmoore** [comment]
Another semi-complete plugin being merged for 0.0.3. @ximenesuk : the methods that are implemented were used for the recent release, but some methods in the docs are not yet implemented. Likely we would just scope back the plugin and handle functions as we need them.

**Comment by pwalczysko** [comment]
Can I redo also non-Plates (i.e. images in Datasets ?) - I am asking because of the recent nightshade black thumbs problem

**Comment by joshmoore** [comment]
@pwalczysko : the plugin currently doesn't support datasets (IDR doesn't have any) but it will be quite simple (5-10 minutes) to add support when this PR is rebased to develop/dev_5_2.

**Comment by joshmoore** [comment]
--rebased-to #4430

**Pull request merged**
