### PR TITLE
OmeroCpp: Correct VS2012 build errors and warnings

### PR DESCRIPTION
**Pull request by rleigh-dundee**
Corrects LongList failure in current merge and latest builds.

Testing: Check merge job is green.

### CODE REVIEW

**Comment by rleigh-dundee** [comment]
https://ci.openmicroscopy.org/view/DEV/job/OMERO-DEV-merge-cpp-win/5/ triggered

**Comment by mtbc** [comment]
Diff looks plausible, but job is red.

**Comment by joshmoore** [comment]
Job 6 was green, and Job 7 has been green so far. Merging to latest can go green tomorrow.

**Comment by sbesson** [comment]
--no-rebase

**Pull request merged**
