### PR TITLE
Set sudo sessions timeout (rebased to dev_5_1)

### PR DESCRIPTION
**Pull request by dominikl**
Same as #4052 , rebased to dev_5_1

### CODE REVIEW

**Comment by sbesson** [comment]
Tested using OMERO.insight-5.1.3-128-a6ee1d9-ice35-b599-mac_Java7+. When importing as, a sudo session is created with a valid timeout

```
 weblitz_test_author | testAnnotationPermissions | 2015-08-25 08:08:43     | createSession  | 10 min. | 290      | 2015-08-25 08:08:48 
```

and expires after 10min of inactivity.

More generally, does anyone have a feeling for a better name for the `createSession` agent? `OMERO.sudo`? Reuse the agent of the initial client? /cc @joshmoore @jburel

**Comment by joshmoore** [comment]
`OMERO.sudo` doesn't sound too bad. If it's worth it, I can look into propagating from the calling session.

**Comment by dominikl** [comment]
--no-rebase (is already in develop #4052 )

**Comment by dominikl** [comment]
--rebased-from #4052

**Pull request merged**
