### PR TITLE
Ticket 13018 (rebased onto develop)

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
This is the same as gh-4189 but couldn't be directly rebased onto develop.

----

This PR fixes access to image when share is inactive or expired.

To test:
 - log in as ``user-1`` and share image with ``user-5``
 - log in as ``user-5`` check if image is visible in the viewer, copy the image URL ``http://host/webclient/img_detail/IMAGE_ID/``
 - log in back to ``user-1`` and deactivate share (uncheck enable in share edit form)
 - log in back to ``user-5`` and check if share is greyed out, you should also not being able to click on it. Go to the URL ``http://host/webclient/img_detail/IMAGE_ID/``, you should get 404
 - as it is impossible to create expired share check if image in ``share 17754`` (owned by ``user-1``) is not visible by ``user-5``

Then:
 - log is as user-3 and check if in a tree inactive or expired shares and discussions are not accessible in at all.

cc: @will-moore

### CODE REVIEW

**Comment by pwalczysko** [comment]
The workflow works fine as described in the header of this PR.
Nevertheless, the overall Share workflow has a develop-specific blocker (not present on trout, only on eel) - see http://trac.openmicroscopy.org/ome/ticket/13044#ticket - up to @aleksandra-tarkowska @will-moore whether they wish to deal with it here or in another PR.

**Comment by aleksandra-tarkowska** [comment]
@pwalczysko you couldn't open the share as a user because it expired. That is expected and works exactly the same as in older version. I think there were complete misunderstanding of what exactly should be tested.

**Comment by will-moore** [comment]
This is breaking a number of share and discussion tests:
https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-merge-integration-web/87/testReport/

**Comment by aleksandra-tarkowska** [comment]
@will-moore testes has to be updated accordingly

**Comment by aleksandra-tarkowska** [comment]
@pwalczysko in the first instance I misunderstood what is exactly is not working. Will fix both in this PR

**Comment by pwalczysko** [comment]
@aleksandra-tarkowska : I have activated the Share 11402 again - sorry about the confusion.

**Comment by aleksandra-tarkowska** [comment]
last commit revert deleted code from https://github.com/openmicroscopy/openmicroscopy/blob/dev_5_1/components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/public/public.html#L222

**Comment by will-moore** [comment]
All working fine. Launching image viewer from double-click on share images in tree is working.
When share is disabled, image viewer url becomes 404 and share node in tree becomes disabled.
All tests passing too. Good to merge.

**Comment by pwalczysko** [comment]
Ticket http://trac.openmicroscopy.org/ome/ticket/13044#ticket is sorted. Good to merge.

**Comment by aleksandra-tarkowska** [comment]
thank everyone

**Comment by aleksandra-tarkowska** [comment]
--rebased-from gh-4189

**Pull request merged**
