### PR TITLE
Min/Max roi

### PR DESCRIPTION
**Pull request by jburel**
To test 
 * Use one of the image listed in https://trac.openmicroscopy.org/ome/ticket/12877
You should NOT need to have to regenerate roi in imageJ

cc @pwalczysko

### CODE REVIEW

**Comment by pwalczysko** [comment]
For images, see team/pwalczysko/QA 11065/*.* or imported to trout merge, user-4, read-only-1, Project QA 11065

**Comment by jburel** [comment]
I have created rois on the few images w/o noticing any issues
The problem is not coming from rois generated in imageJ but to the min/max values of a given channel
I have not been able to reproduce the issue with the images imported by @pwalczysko.

**Comment by pwalczysko** [comment]
I could not reproduce the problem either. Even with exactly the same setup as the QA user was using, Win7, 5.1.1 clients and ij-plugin, the same image which I reimported, drawing polygon regions in IJ and saving them back. All works as expected.

**Comment by pwalczysko** [comment]
For the polygon drawing problem I have created ticket https://trac.openmicroscopy.org/ome/ticket/12883#ticket. (not related to this PR, just reported by the same user at the same time.)

We could not see any problems even reopening the original nightshade image which caused the crashes first using the merge insight. 

Ready to merge.

**Comment by pwalczysko** [comment]
cc @kennethgillen

**Pull request merged**
