### PR TITLE
Add chown command to CLI

### PR DESCRIPTION
**Pull request by ximenesuk**
Idly talking with @mtbc in Paris about Chown2 it was clear that a `chown` command would pretty much be a search and replace of the `chgrp` command. So here it is. This is mainly intended to facilitate testing of `Chown2` but is exposed in the CLI. As this is a copy of `chgrp` I may have left some of the old stuff behind, particularly in docstrings and comments.

There are some minimal integration tests: two users in the same group - transfer possible, two users in different groups - transfer not possible. There are no admin tests as yet - these need to be added. The argument parsing is not tested here as the same superclass as `chgrp` and `delete` is used and so that is tested sufficiently elsewhere.

To test try various `chown` operations between different users, different groups, etc. The `--help` text provides some examples.

### CODE REVIEW

**Comment by mtbc** [comment]
This PR is well-timed with https://trello.com/c/PfkOHANb/31-refactor-chown2 in progress. :smiley:

**Comment by will-moore** [comment]
I don't know how many of the following comments are related to this PR vv underlying chown behaviour cc @mtbc.

Trying to chown someone else's data (read-ann group) fails very silently:
```
$ omero chown 3 Dataset/Image:6102 --report
Using session d001337f-7f93-4ac0-bd35-f75f3da05746 (will@localhost:4064). Idle timeout: 10 min. Current group: read-ann
omero.cmd.Chown2 Dataset/Image 6102... ok
Steps: 4
Elapsed time: 0.08 secs.
Flags: []
```

Trying to split a MIF doesn't give a very clear message:
```
$ omero chown 4 Image:4651 --report --dry-run
Using session d001337f-7f93-4ac0-bd35-f75f3da05746 (will@localhost:4064). Idle timeout: 10 min. Current group: read-ann
omero.cmd.Chown2 Image 4651... failed: 'graph-fail'
failed: may not split file annotations that share OriginalFile[10010]
Steps: 1
Elapsed time: 0.827 secs.
Flags: [FAILURE, CANCELLED]
```

This failure below is clear enough (user not in group), but if I do the same thing with ```--dry-run``` I don't get any warning that it won't work:
```
$ omero chown 3000 Image:63 --report
Using session d001337f-7f93-4ac0-bd35-f75f3da05746 (will@localhost:4064). Idle timeout: 10 min. Current group: read-ann
omero.cmd.Chown2 Image 63... failed: 'graph-fail'
failed: cannot process ome.model.fs.FilesetEntry[34]: user 3000 is not a member of group 3
Steps: 3
Elapsed time: 0.646 secs.
Flags: [FAILURE, CANCELLED]
```

It seems a little strange that Tags, File annotations etc get changed to the new owner even in a Read-Ann group where they could happily belong to their original owner while staying linked to the Image.

Seems a bit strange that I can chown data to another user in a Private group. Partly because I lose ability to see it (which is OK) but also because it remains in my Dataset (appears as orphaned to the new user) and stops me moving Dataset to another group:
```
graph-fail stacktrace: ome.services.graphs.GraphException(message=cannot null ome.model.containers.DatasetImageLink.parent)
at ome.services.graphs.GraphTraversal.unlinkTargets(GraphTraversal.java:1379)
at omero.cmd.graphs.Chgrp2I.step(Chgrp2I.java:172)
at omero.cmd.basic.DoAllI$X.step(DoAllI.java:110)
```

In fact, even if I chown data to another user in a Read-Ann group, it remains in MY Dataset and now I don't have the ability to remove it from my Dataset. Although in this case I seem to be able to Chgrp the Dataset to another Group, leaving the image behind.

Probably makes sense that if I can't put another user's Images in my Dataset (anything other than read-edit group) that if I chown an Image to a different user it should also be removed from my Dataset.

**Comment by mtbc** [comment]
Interesting! Once #3873 is merged I'll be opening a PR that revises the server's underlying chown behaviors.

**Comment by ximenesuk** [comment]
@will-moore Thanks.  I think most of the above are manifestations of server behaviour. What's positive is that the command doesn't throw any exceptions and works. It might be that once the expected behaviour is understood some of the error messages can be more helpful?

Have you tried with the `--report` option?

The integration tests are necessarily limited because I'm not sure what is meant to happen! I think we are all waiting on @mtbc :-)

**Comment by mtbc** [comment]
Ho ho. I added a bit more chown testing in https://github.com/mtbc/openmicroscopy/commit/f819fd79 (PR coming) and perhaps @bramalingam or @jburel may improve coverage but, yes, we may not get to https://trello.com/c/PZeCDbjf/65-graphs-review-chgrp-chown-delete anytime soon and in the meantime should at least address the clearly wrong behaviors evinced.

**Comment by mtbc** [comment]
@will-moore: Some of the issues that you noticed may be addressed by #3887 but I would expect some RFEs to remain outstanding.

**Comment by joshmoore** [comment]
@ximenesuk : next steps? Re-list for Monday with gh-3887?

**Comment by ximenesuk** [comment]
@joshmoore Yes, I think so.

**Comment by ximenesuk** [comment]
Due to changes made in gh-3887 this PR would benefit from a fresh review.

**Comment by will-moore** [comment]
Improved handling of failure to move another user's data:
```
$ omero chown 3 Dataset/Image:6102 --report
Previous session expired for will on localhost:4064
Server: [localhost:4064]
Username: [will]  
Password:
Created session fad2e145-d2e0-46e2-8f37-966f2029dee9 (will@localhost:4064). Idle timeout: 10 min. Current group: read-ann
omero.cmd.Chown2 Dataset/Image 6102... failed: 'graph-fail'
failed: does not own ome.model.fs.FilesetEntry[7351]
Steps: 4
Elapsed time: 5.824 secs.
Flags: [CANCELLED, FAILURE]
```

**Comment by will-moore** [comment]
Failure to move a single image from a MIF still doesn't give a helpful error message:
```
$ omero chown 4 Image:4651 --report --dry-run
Using session fad2e145-d2e0-46e2-8f37-966f2029dee9 (will@localhost:4064). Idle timeout: 10 min. Current group: read-ann
omero.cmd.Chown2 Image 4651... failed: 'graph-fail'
failed: cannot give OriginalFile[10010] while objects using it remain
Steps: 1
Elapsed time: 3.425 secs.
Flags: [FAILURE, CANCELLED]
```

Using the dry-run flag means I don't get any warning that this will not work (user is not a member of this group)
```
$ omero chown 3000 Image:4705 --report --dry-run
Using session fad2e145-d2e0-46e2-8f37-966f2029dee9 (will@localhost:4064). Idle timeout: 10 min. Current group: read-ann
omero.cmd.Chown2 Image 4705... ok
Steps: 1
Elapsed time: 0.924 secs.
Flags: []
Included objects
  Channel:5263-5265
  Image:4705
...

$ omero chown 3000 Image:4705 --report
Using session fad2e145-d2e0-46e2-8f37-966f2029dee9 (will@localhost:4064). Idle timeout: 10 min. Current group: read-ann
omero.cmd.Chown2 Image 4705... failed: 'graph-fail'
failed: cannot process ome.model.fs.FilesetEntry[4253]: user 3000 is not a member of group 3
Steps: 3
Elapsed time: 0.633 secs.
Flags: [FAILURE, CANCELLED]
```

As above, it seems a little strange that Tags, File annotations etc get changed to the new owner even in a Read-Ann group where they could happily belong to their original owner while staying linked to the Image.

Moving an image to another owner in a Private group DOES now remove it from my Dataset.

However, it's still a bit inconsistent that it still DOESN'T remove an Image from my Dataset when I change it to another owner in a Read-Annotate group. Normally I wouldn't be allowed to add another user's image to my Dataset in Read-Annotate group, but by this chown, I can end up in the same situation, and then I can't remove the image from my Dataset.

Image named MonGb2-S7.dm3 seemed to lose DetectorSettings when moved to private group.
Will try to repeat to see what data is lost.
```
ome-mbp-108-01:OMERO wmoore$ omero chown 4 Image:4724 --report
Using session fad2e145-d2e0-46e2-8f37-966f2029dee9 (will@localhost:4064). Idle timeout: 10 min. Current group: read-ann
omero.cmd.Chown2 Image 4724... ok
Steps: 3
Elapsed time: 1.86 secs.
Flags: []
Included objects
  Channel:5290
  Image:4724
  LogicalChannel:4490
  OriginalFile:10266,10267
  Pixels:4424
  PlaneInfo:27905
  ChannelBinding:5190
  QuantumDef:4474
  RenderingDef:4474
  Thumbnail:4574
  Fileset:3672
  FilesetEntry:4272
  FilesetJobLink:14106-14110
  IndexingJob:14660
  JobOriginalFileLink:4322
  MetadataImportJob:14657
  PixelDataJob:14658
  ThumbnailGenerationJob:14659
  UploadJob:14656
  StatsInfo:5206
Deleted objects
  DetectorSettings:555
  ObjectiveSettings:908
  DatasetImageLink:11571
```

**Comment by will-moore** [comment]
Failure to move a single image within a Plate is fair enough but the error message might confuse a naive user:
```
$ omero chown 4 Image:9901 --report --dry-run
Using session fad2e145-d2e0-46e2-8f37-966f2029dee9 (will@localhost:4064). Idle timeout: 10 min. Current group: read-ann
omero.cmd.Chown2 Image 9901... failed: 'graph-fail'
failed: within Fileset[6901] may not give Image[9901] while Image[9912] remains
Steps: 1
Elapsed time: 3.086 secs.
Flags: [FAILURE, CANCELLED]
```

**Comment by mtbc** [comment]
Absolutely: the messages aren't really for the naive user. https://trello.com/c/F4cAE0k3/358-graphexception-subclasses concerns this general issue.

For the changed Tags, File annotations, were they linked solely to data being chown'd, or also annotating data that wasn't?

**Comment by will-moore** [comment]
@mtbc Tag was only linked to the Image being moved, so it didn't break any Tag-image links.

**Comment by ximenesuk** [comment]
`failed: within Fileset[6901] may not give Image[9901] while Image[9912] remains` The word `give` seems a little odd.

**Comment by mtbc** [comment]
What verb would you suggest for what chown does? ("X is to chown as move is to chgrp.")

**Comment by will-moore** [comment]
"transfer" ?

**Comment by mtbc** [comment]
Noted on card; thanks. This may fit other text better. (I wasn't prepared for how people find "give" a weird way to say "change ownership".)

I am not sure when it makes sense for detector settings to be lost. Any luck reproducing? I'll try importing a Gatan file and see how it goes with that, could easily be a simple bug there.

**Comment by ximenesuk** [comment]
In testing gh-3887 I noticed a stupid bug on my part if an `--exclude` option was used without an `--include`. This affected any commands that used this optiion. To test try one of the commands with and without one or both options.

**Comment by joshmoore** [comment]
I'm having difficulty getting `--exclude` to work at all:
```
[jamoore@ome-c6100-3 ~]$ omero -q chown --report --exclude Image --dry-run pr3879-b Dataset:3151
omero.cmd.Chown2 Dataset 3151... ok
Steps: 1
Elapsed time: 0.285 secs.
Flags: []
Included objects
  Dataset:3151
  DatasetImageLink:14251
  Channel:54551
  Image:27301
...
```

**Comment by ximenesuk** [comment]
@joshmoore is this with any of the three commands? Does the implied exclude in delete, something with a TagAnnotation, say, work?

Otherwise I'll take a deeper look and check wether this is a plugin problem or something upstream. /cc @mtbc

**Comment by joshmoore** [comment]
Same dataset/image (which you're welcome to use) now with an annotation on the image and `--exclude Annotation` still seems to do nothing.

**Comment by ximenesuk** [comment]
I'll take another look. Could you point me at your user/server?

**Comment by joshmoore** [comment]
trout/merge, group: pr3879, user: pr3879-a (and -b).

**Comment by mtbc** [comment]
> it's still a bit inconsistent that it still DOESN'T remove an Image from my Dataset when I change it to another owner in a Read-Annotate group

@will-moore: Good catch! You should find this to be fixed in the next merge build.

**Comment by ximenesuk** [comment]
I've taken a look and as far as I can seen the ChildOptions are being formed correctly by the CLI commands and passed to the server in the command. I don't know if there is any server-side logging that could verify this from the Java side of things.

The tests in `integration/clitest/test_delete.py` that check these options are not comprehensive but they do test both options and the default exclude of annotations. Those tests pass.

Might this be down to behaviour differences between the three commands?

**Comment by mtbc** [comment]
I'll take a look.

**Comment by mtbc** [comment]
If I attach a debugger to the server then a CLI `--exclude Image` is giving me an empty `this.childOptions` for `Chown2I.init(Helper)`.

**Comment by ximenesuk** [comment]
Okay, this looks like it is my problem - I clearly picked a "nice" case as my example. This also means the tests may not check the combinations sufficiently well. Leave this with me and I will create a test that reflects what @mtbc has just tried and then push a fix.

**Comment by ximenesuk** [comment]
I'm not sure what I was on when I write that bit of code but two basic errors in just a few lines. I now need to add some tests that use include/exclude with a deeper hierarchy to test more than just annotations. I'll add those tests later. Thanks both for bearing with me!

**Comment by joshmoore** [comment]
Looking much better in the rebuild:
```
[jamoore@ome-c6100-3 ~]$ omero -q chown --report --dry-run --exclude=CommentAnnotation --exclude Image pr3879-b Dataset:3151
omero.cmd.Chown2 Dataset 3151... ok
Steps: 1
Elapsed time: 0.186 secs.
Flags: []
Included objects
  Dataset:3151
Deleted objects
  DatasetImageLink:14251
```
Waiting on integration tests.

**Comment by joshmoore** [comment]
17 new passing tests:
https://ci.openmicroscopy.org/view/Failing/job/OMERO-5.1-merge-integration-python/lastCompletedBuild/testReport/test.integration.clitest.test_chown/TestChown/

**Comment by joshmoore** [comment]
To channel @sbesson : anything else needed in the way of docs, etc.?

**Comment by pwalczysko** [comment]
From the help:

```
bin/omero chown -h
usage: bin/omero chown [-h] [--wait WAIT] [--include INCLUDE]
                       [--exclude EXCLUDE] [--ordered] [--list]
                       [--list-details] [--report] [--dry-run]
                       [usr] [obj [obj ...]]

Transfer data between usrs

Transfer entire graphs of data based on the ID of the top-node.
```

1. Typo (should be Transfer data between users => exchenge ``usrs`` for ``users``
2. The last but one and the last sentence - how do they bind ? Would it be not better to put them together and reformulate ? (I mean ``Transfer entire graphs....`` is still just expanded ``Transferr data between users``
3. In the examples and header, it would be good to mention who can do what - is it that only the owner of the data can transfer ownership ? Is it that admin can transfer ownership from one user to another ? Which is the case ?

**Comment by pwalczysko** [comment]
Another typo in the help

```
that would have been transfered
    omero chown 101 Dataset:53 --dry-run --report
```
Shoud be transferred (not transfered) -> add one ``r``

**Comment by pwalczysko** [comment]
Another remark on the --help formulations:
Wouldn't it be prudent to use the word ``ownership`` in addition to the word ``transfer`` ? At least at the beginnng of the explanatory header ?

**Comment by pwalczysko** [comment]
@joshmoore @ximenesuk @mtbc : Okay, I understand now that 
1. admin can transfer ownership
2. owner of the data can transfer ownership

My suggestion would be to have the transfer ownership for admins exposed also in graphical clients. This was a request during Paris meeting.
As for the owners of the data being able to chown their data, probably the ux team should discuss whether or not this is to be kept (and put in GUIs ?) @gusferguson @jburel @will-moore . My 2p would be that for the simple non-admin users, this would be rather confusing and would not bring much, as you cannot transfer ownership to someone accross the groups.

**Comment by mtbc** [comment]
Non-admin chown (your 2) can certainly easily be removed even from server & CLI if UX decides so.

**Comment by gusferguson** [comment]
@pwalczysko - I think it was mainly group owners who wanted to be able to transfer ownership - so from my POV keeping it to group owners and admins would make sense.

**Comment by pwalczysko** [comment]
@gusferguson @mtbc : Yes, agree, but atm the group owners cannot do anything else that rank-and-file members. @mtbc is advising me though that this can be easily changed (=owners would have the same rights as admins in their particular groups regarding ownership transfer)

**Comment by will-moore** [comment]
I think we should allow users to chown their data. We allow them to delete it! Especially as the functionality is there now, I don't think we should turn it off.

**Comment by mtbc** [comment]
For group owner chown now created https://trello.com/c/PZQSlsGy/49-allow-group-owners-to-chown.

**Comment by will-moore** [comment]
Moving an image to another user in read-ann group removed it from my Dataset as expected.
```
$ omero chown ben Image:2 --report
...
Deleted objects
  DatasetImageLink:2
```

**Comment by pwalczysko** [comment]
from Help
```
Optional Arguments:
  In addition to any higher level options
```
Neither me nor @mtbc understands what ``higher level options`` are - this formulation was also never used in this help previously.

**Comment by joshmoore** [comment]
> I think we should allow users to chown their data. We allow them to delete it! Especially as the functionality is there now, I don't think we should turn it off.

@will-moore : happy to have a larger discussion, but I disagree. The fact that it's currently possible is an oversight. In terms of our permissions model (even if only loosely based on unix), forcing data onto another user is something only an admin can do.

**Comment by joshmoore** [comment]
> Neither me nor @mtbc understands what higher level options are - this formulation was also never used in this help previously.

Not that the wording can't be improved, @pwalczysko, but this refers to the the options that are listed if you do `bin/omero -h` i.e. login info. cc: @sbesson

**Comment by mtbc** [comment]
@joshmoore: Ought group owners be able to?

**Comment by mtbc** [comment]
Of course, unlike OMERO, Unix has the issue that if, as an ordinary user, I could give you one of my files, I could do so such that you couldn't actually delete the file's inode even though you own it.

**Comment by joshmoore** [comment]
> Ought group owners be able to?

Yes. They're admins in their groups.

**Comment by ximenesuk** [comment]
Wow, I leave you all alone for a day and look what happens!

**Comment by ximenesuk** [comment]
Barring typos it would be good to get some definitive take  on what to change here. Restricting to admin-only in the CLI command would be the easy step, then deciding later whether to open it up further in conjunction with UX?

@pwalczysko , @joshmoore also commented on the first two sentences being the same. I'm happy to have just a single sentence up there. This was just a side-effect of changing `chgrp` to `chown` in a fairly crude way.

**Comment by ximenesuk** [comment]
Barring typos it would be good to get some definitive take  on what to change here. Restricting to admin-only in the CLI command would be the easy step, then deciding later whether to open it up further in conjunction with UX?

@pwalczysko , @joshmoore also commented on the first two sentences being the same. I'm happy to have just a single sentence up there. This was just a side-effect of changing `chgrp` to `chown` in a fairly crude way.

**Comment by ximenesuk** [comment]
@joshmoore wrote re owners:
>Yes. They're admins in their groups.

So this would be an owner transferring data from themselves to user X where that user is in the owner's group and that is the group the data is in? But an admin would be able to transfer to user Y where that user is in any group, the data ending in user Y's default group?

It's almost seeming like there should be something like `chown user-to user-from Object:ID` too if ordinary uers can't transfer to other users.

**Comment by pwalczysko** [comment]
> So this would be an owner transferring data from themselves to user X where that user is in the owner's group and that is the group the data is in? But an admin would be able to transfer to user Y where that user is in any group, the data ending in user Y's default group?

Yes, this as well. But actually we had in mind a case where an admin would be able to transfer the ownership between any 2 users on the server. And group owner would be able to transfer the ownership between any 2 users (including himself as both acceptor and donor) in their group as long as the data are in the group this group owner owns. This would cater for the case when somebody leaves the lab and the admin and or group owner needs to "clean up" after them, which is very often asked for by users.

**Comment by pwalczysko** [comment]
> It's almost seeming like there should be something like chown user-to user-from Object:ID too if ordinary uers can't transfer to other users.

Yes, definitely, this is what I meant in my above comment actually.

**Comment by will-moore** [comment]
>It's almost seeming like there should be something like chown user-to user-from Object:ID too if ordinary uers can't transfer to other users.

You wouldn't need a "user-from" ID because the owner of the object is known.

**Comment by ximenesuk** [comment]
Yes, you are absolutely right @will-moore and that is probably how this command works anyhow - I just need more sleep!

**Comment by ximenesuk** [comment]
@pwalczysko is the help any better now? I have added the word "ownership" in a few key places but not in every example, to avoid too much extra repetition.

I have not fixed the use of "higher level options". This is used throughout the CLI help so would need to be fixed in a separate PR if a wording can be agreed upon.

I have also not clarified who can and can't `chown` data. At the moment anyone can. If it can be agreed what the constraints should be then I will modfy the help once the code is modified accordingly.

**Comment by pwalczysko** [comment]
Yes, this clarifies the help nicely. I have also built the develop + this PR locally and checked the help on my local server. All looks fine there.

**Comment by ximenesuk** [comment]
Given any further work is likely to be server-side can this PR get merged and any further changes to implementation or help follow @mtbc's work on https://trello.com/c/PZQSlsGy/49-allow-only-group-owners-to-chown

**Pull request merged**
