### PR TITLE
Immediately delete ROIs

### PR DESCRIPTION
**Pull request by dominikl**
Bugfix for [Ticket 13037](trac.openmicroscopy.org/ome/ticket/13037), [Trello - Insight: Measurement tool follow up](https://trello.com/c/DMWzJr97/6-insight-measurement-tool-follow-up)

**Test**:
Open an image with several ROIs. Make sure, deleting *single* ROIs (via context menu), deleting *multiple* ROIs (via context menu) and deleting *all* ROIs (via toolbar menu) works like expected. After each step close the full viewer and reopen it again. In every case the ROIs should get deleted immediately, no confirmation dialog should pop up when closing the full viewer.

Note: There is still a little discrepancy between ROIs and other annotation. Deleting ROIs triggers an 'activity' whereas for example removing tags does not. Might tackle this in separate PR.

### CODE REVIEW

**Comment by jburel** [comment]
remaining ```e.printStackTrace()```

**Comment by pwalczysko** [comment]
Discussed with @dominikl : The ``Delete all ROIs`` option (under the RED CROSS submenu) is still easily mistaken for ``Delete all SELECTED ROIS`` (by Dominik himself). As this was the reason for creation of the submenu in the first place, maybe a warning dialog is needed on ``Delete all`` ? 
Your opinion @gusferguson ?

**Comment by pwalczysko** [comment]
- open an image with no ROIs
   - draw couple of ROIs, do not save them
   - delete them all using context menu (or using the Delete key selecting them in the image)
   - close the full viewer
   - observe that you get a dialog ``Do you want to Save ROIs ?`` -> not expected, there should be no dialog as you did not really make any changes to the image
   - if you Delete the ROIs using ``Delete all regions`` under red cross, no dialog after closing of the image pops up

**Comment by pwalczysko** [comment]
Another bug, not necessarily caused by this PR:

   - open an image
   - draw an ROI, do not save it 
   - close the image
   - observe that you get a warning dialog, giving you the options to ``Close and save changes = Yes``,, ``Close and do not save changes = No`` and ``Do not close = Cancel``
   - close the warning dialog itself, using the red top left button on mac or the cross on windows
   - observe that the ``Yes`` option was executed, i.e. the image was closed -> expected behaviour is that the ``Cancel`` option woudl be executed, i.e. the image would be left open, no saving or closing would take place

**Comment by gusferguson** [comment]
@pwalczysko @dominikl @jburel - I really struggle with this whole interaction - if I select one or more ROI and click the red x I expect the action to only apply to the selected ROI/s. Do you want me to do a quick scoping of the whole thing?

**Comment by dominikl** [comment]
Fixed the two issues mentioned by @pwalczysko .

**Test**
1. Create an ROI (don't save it)
2. Delete the ROI again
3. Close the full viewer and make sure no "Save" dialog pops up

1. Create two ROIs (don't save them)
2. Delete one of them
3. Close the full viewer and make sure this time the "Save" dialog pops up.
4. Close the dialog via the red close icon and make sure that just the dialog is closed and nothing else happens (full viewer still open), i. e. the close via the icon has the same effect as the close when clicking on the "Cancel" option

With respect to the "Delete all ROIs" action: @pwalczysko mentioned it actually matches the ImageJ behaviour, so people might be used to it? If not, shall I leave the PR open for changing that, or shall we discuss this later and I'll open a new PR for it (if needed)?

**Comment by pwalczysko** [comment]
All works here as expected. I think the rehaul of the whole workflow is not what we should do in this PR, as this will be necessarily longer. Would recommend to merge.

**Comment by jburel** [comment]
The "red cross" issue was reported by @pwalczysko following a drop-in session
This should be addressed in a follow-up PR.
see https://trello.com/c/h0PLjn5r/54-more-roi-fixes

**Pull request merged**
