### PR TITLE
Show magnification

### PR DESCRIPTION
**Pull request by dominikl**
Show magnification (if data is available) instead of percentage zoom level. This PR basically does the same as #2291 just for Insight;
Test: also see PR #2291 and compare Insight and Web.

Fixes ticket: https://trac.openmicroscopy.org/ome/ticket/12201

### CODE REVIEW

**Comment by gusferguson** [comment]
@dominikl 

Tested using OMERO.insight-5.1.0-160-e43dd1d-ice34-b464-mac_Java7+ user-3 read-only-1.

Data: 8kx8k.jpg, UMD001_ORO.svs [Series 1], UCLAD_0000000280_2011-02-10 13_32_55Z.scn [UCLAD_0000000910 (R1)] - all in “5.0 Data"

Works as expected with JPEG - displays % rather than magnification.

With both SVS and SCN - magnification is displayed but zooming stops short of that achieved in Web. Insight only goes to 40x with SVS and Web goes to 160x - screenshot 1. With SCN - Insight goes to 0.61x and Web goes to 2.43x - although both of these magnifications look wrong intuitively - screenshot 2.

Also - with the SCN there is a marked discrepancy between the birds-eye red square in Insight and Web. When Insight is at 0.15x and Web at 2.43x - the squares in the birds-eye are the same size but obviously the area being displayed is completely different - screenshot 3.

Not sure exactly what is going on, but a couple of things are not right. 

main 3

main 2

main

**Comment by dominikl** [comment]
Thanks @gusferguson . Yes, Web offers more zoom levels than Insight. Could tackle this in another PR if this shall be unified. 
With respect to point/screenshot 2 and 3:
@aleksandra-tarkowska : Could you check Web again with the same data and confirm that Web is doing it right? Then I can try to get the same in Insight. But if it's not clear if Web is wrong or Insight or both, I don't know what to go for.

**Comment by dominikl** [comment]
@aleksandra-tarkowska or @will-moore Could you have a look at the points @gusferguson mentioned:
- "With SCN - Insight goes to 0.61x and Web goes to 2.43x - although both of these magnifications look wrong intuitively - screenshot 2." - Which client is doing it right, Insight, Web or none?
- "When Insight is at 0.15x and Web at 2.43x - the squares in the birds-eye are the same size but obviously the area being displayed is completely different - screenshot 3." - Again, which client is correct if any? In my opinion the birds eye square in Web looks a bit too big.

**Comment by dominikl** [comment]
Exclude label could be removed again. But still waiting on some feedback from @aleksandra-tarkowska and/or @will-moore .

**Comment by dominikl** [comment]
Ok, to sum this up again, there are three points:
- Web offers additional zoom levels compared to Insight. *Not affected by this PR.*
- The square in the birds eye view might not be accurate. *Not an issue of this PR, too.*
- Magnification value wrong in Web **and/or** Insight. Can someone verify this? If it is wrong in Insight I can fix it, otherwise this PR could be merged and a ticket could be opened for fixing it in Web.

**Comment by joshmoore** [comment]
Excluding to let 3779 in. To be discussed with @aleksandra-tarkowska on @dominikl's return.

**Comment by aleksandra-tarkowska** [comment]
@dominikl Before 5.1 release @melissalinkert fixed couple of issues with SCN and magnification. Are we sure the test metadata?

**Comment by aleksandra-tarkowska** [comment]
@gusferguson @dominikl @joshmoore I have jsut went through Gus's report. Looks like UCLAD_0000000280_2011-02-10 13_32_55Z.scn in 5.0 has a wrong metadata as it was imported in Dec'14. I have just re-imported to https://trout.openmicroscopy.org/merge/webclient/?show=dataset-24303 in both clients looks ok Mag x40

**Comment by aleksandra-tarkowska** [comment]
See screenshots
omero insightscreensnapz006
firefoxscreensnapz033

**Comment by aleksandra-tarkowska** [comment]
For more details please compare ```5.0 data``` / ```big-scn``` with ```big-scn reimport```

**Comment by aleksandra-tarkowska** [comment]
Although it is true that insight only goes up to 100% and web upscale full size tile and does 200% and 400%. It is a built in feature in PanoJS viewer.

**Comment by aleksandra-tarkowska** [comment]
I presume that should resolve all questions in this PR.

**Comment by dominikl** [comment]
Thanks @aleksandra-tarkowska . This actually means the PR could be merged.

**Comment by aleksandra-tarkowska** [comment]
@dominikl once you resolve merge conflict :)

**Comment by dominikl** [comment]
That's a good point... done.

**Comment by aleksandra-tarkowska** [comment]
Works as expected good to merge omero insightscreensnapz007

**Pull request merged**
