### PR TITLE
Activity icon

### PR DESCRIPTION
**Pull request by jburel**
Replace "delete" icon (red cross) by "Remove" text in activity dialog

To test;
 * Delete an image for example
 * When the action is completed. Check that  a "remove" is displayed on the row instead of the red cross icon
cc @gusferguson @kennethgillen

### CODE REVIEW

**Comment by gusferguson** [comment]
@jburel 

Tested using OMERO.insight-5.1.1-93-a7349d7-ice35-b488-mac_Java6 trout user-3 read-annotate-1

Red cross still present.

activities

**Comment by jburel** [comment]
@gusferguson: the PR does not seem to be included in the build

**Comment by gusferguson** [comment]
@jburel 

Tested using OMERO.insight-5.1.1-122-fa3f455-ice35-b490-mac_Java7+ trout user-3 

Red cross replaced by Remove link - works as expected.
Vast improvement!!
Good to merge.

activities

**Comment by jburel** [comment]
@gusferguson: Does it require some screenshots update?

**Comment by gusferguson** [comment]
@jburel - thanks - will check Help pages - will probably need at least one.

**Comment by gusferguson** [comment]
@jburel - don't seem to be any screenshots with activity window in them - so no updates required.

**Pull request merged**
