### PR TITLE
Output Image/Plate IDs from CLI import

### PR DESCRIPTION
**Pull request by ximenesuk**
# What this PR does

This PR makes the default output, i.e. what is sent to standard output, an Image or Plate ID list of the form of `Image:1,2,3,4` or `Plate:101`. It supersedes gh-4715 and is built on @joshmoore's bulk import work which was rebased onto develop in gh-4731 by @mtbc. The output added by this PR is also available explicitly using the `--output ids` option, while the legacy output is available via the `--output legacy` option. This PR does not change the out output sent to standard error such as the other imported objects and the summary.

# Testing this PR

Import some images and plates with the different output options, for example:
```
$ bin/omero import ~/Work/images/dv/IAGFP-Noc01_R3D.dv
2016-06-16 12:47:04,789 15738      [l.Client-1] INFO   ormats.importer.cli.LoggingImportMonitor - IMPORT_DONE Imported file: /Users/colin/Work/images/dv/IAGFP-Noc01_R3D.dv
Image:351
Other imported objects:
Fileset:151
2016-06-16 12:47:04,804 15753      [l.Client-1] INFO      ome.formats.importer.cli.ErrorHandler - Number of errors: 0

==> Summary
2 files uploaded, 1 fileset created, 1 image imported, 0 errors in 0:00:09.531

$ bin/omero import  ~/Work/images/dv/IAGFP-Noc01_R3D.dv --output legacy
...
2016-06-16 12:47:43,572 4497       [l.Client-0] INFO   ormats.importer.cli.LoggingImportMonitor - IMPORT_DONE Imported file: /Users/colin/Work/images/dv/IAGFP-Noc01_R3D.dv
Imported pixels:
352
Other imported objects:
Fileset:152
Image:352
2016-06-16 12:47:43,573 4498       [l.Client-0] INFO      ome.formats.importer.cli.ErrorHandler - Number of errors: 0

==> Summary
2 files uploaded, 1 fileset created, 1 image imported, 0 errors in 0:00:02.637

$ bin/omero import ~/Work/images/dv/IAGFP-Noc01_R3D.dv --output ids
2016-06-16 12:51:26,018 16230      [l.Client-1] INFO   ormats.importer.cli.LoggingImportMonitor - IMPORT_DONE Imported file: /Users/colin/Work/images/dv/IAGFP-Noc01_R3D.dv
Image:353
Other imported objects:
Fileset:153
2016-06-16 12:51:26,021 16231      [l.Client-1] INFO      ome.formats.importer.cli.ErrorHandler - Number of errors: 0

==> Summary
2 files uploaded, 1 fileset created, 1 image imported, 0 errors in 0:00:09.621
```

The yaml output should also be checked

```
$ bin/omero import ~/Work/images/dv/IAGFP-Noc01_R3D.dv --output yaml
````
See gh-4731 for more details.

It's also worth confirming that what is sent to stdout is what is expected:
```
$ bin/omero import -s localhost -u user-0 -w ome --output legacy ~/Work/images/dv/IAGFP-Noc01_R3D.dv 1> stdout.txt
...
==> Summary
2 files uploaded, 1 fileset created, 1 image imported, 0 errors in 0:00:02.637
$ cat stdout.txt
352

$ bin/omero import -s localhost -u user-0 -w ome ~/Work/images/dv/IAGFP-Noc01_R3D.dv 1> stdout.txt
...
==> Summary
2 files uploaded, 1 fileset created, 1 image imported, 0 errors in 0:00:09.531
$ cat stdout.txt
Image:351
```
MIFs should also be tried. With the legacy option a list of Pixels IDs will be output each on its own line. Without the legacy output the Image IDs should be output on a single line in the form 
```
Image:1,2,3,4,5
```

Plates should also be imported. With the legacy option a list of Pixels IDs will be output each on its own line. Without the legacy output the Plate ID should be output on a single line in the form
```
Plate:5
```

Existing CLI tests should pass

# Related reading

See: https://trello.com/c/pY5KvRPI/691-cli-return-image-id

# Work to be done

Existing tests are being made to pass by passing in the `--output legacy` by default. Ideally the tests should be refactored to work against the new default output while the legacy and yaml options should have separate tests.

### CODE REVIEW

**Comment by pwalczysko** [comment]
After executing
```
bin/omero import ~/Downloads/dv/IAGFP-Noc01_R3D.dv
```
I get
```
...
Image:26155
2016-08-31 16:08:17,505 11188      [l.Client-0] INFO      ome.formats.importer.cli.ErrorHandler - Number of errors: 0

==> Summary
2 files uploaded, 1 fileset created, 1 image imported, 0 errors in 0:00:09.440
```
instead of the output suggested in the first example in the header of this PR (i.e. the ``Other imported objects`` bit is missing)

**Comment by pwalczysko** [comment]
Analogous situation as in https://github.com/openmicroscopy/openmicroscopy/pull/4812#issuecomment-243795785  occurs when I use 
```
bin/omero import ~/Downloads/dv/IAGFP-Noc01_R3D.dv --output ids
```

**Comment by pwalczysko** [comment]
We have one failed test here https://ci.openmicroscopy.org/job/OMERO-DEV-merge-integration-python/lastCompletedBuild/testReport/OmeroPy.test.integration.tablestest.test_service/TestTables/testTicket2175/

**Comment by ximenesuk** [comment]
Sorry, my fault in the description re https://github.com/openmicroscopy/openmicroscopy/pull/4812#issuecomment-243795785 the code does not provide the other imported objects to `stderr` as the description suggests. Given that these other objects are not available otherwise (as in the yaml case) I will add them to the output.

**Comment by ximenesuk** [comment]
@pwalczysko See: https://ci.openmicroscopy.org/job/OMERO-DEV-merge-integration-python/355/

**Comment by ximenesuk** [comment]
This last commit puts back the `Other imported objects` section. This does now mean that the Image ids appear in both stdout and stderr. Is this a problem? Should there be a more sophisticated output here excluding whatever is in stdout? Should the Pixels be in the other objects?

**Comment by joshmoore** [comment]
No strong feelings but my votes would be:
 * Hide Pixels
 * Image IDs only in one (though I keep going back and forth on this)
 * What happens in the Plate case? (And in the plate+yaml case?)

**Comment by ximenesuk** [comment]
In the Plate case simply swap Image for Plate in all of the above - ie Plate would be in the Other imported objects for the default and legacy cases. Image IDs are not available in the imported object list for Plates.

**Comment by ximenesuk** [comment]
This last commit excludes Image or Plate from the Other imported objects output for the default output.

It's interesting that the summary has the Image count for a Plate but the Images are not put in to the object list further down in the import stack. Maybe they would be useful for the output for Plate imports?

**Comment by joshmoore** [comment]
> Maybe they would be useful for the output for Plate imports?

I'd assume we filtered here due to the sheer number of images that could be printed (thousands). Perhaps alleviated with your hyphenation?

**Comment by mtbc** [comment]
Not sure how much hyphenation will save us if there are multiple concurrent large plate imports.

**Comment by ximenesuk** [comment]
Yes, for a Plate in isolation hyphenation would be okay but two concurrent imports could, potentially, produce the worst case. I'm more than happy to leave well alone. Anything else can be queried given the output already provided.

**Comment by pwalczysko** [comment]
Everything here works as described by @ximenesuk in the header and comments. Integration tests are passing.

I am a bit confused about the plate behavour discussion, as the word ``well`` is suddently used in https://github.com/openmicroscopy/openmicroscopy/pull/4812#issuecomment-244310115, which I cannot refer to in the outputs or discussion. But considering that I do not have any hard opinion on the character of the output in the plate case, you can ignore this.

**Comment by pwalczysko** [comment]
The design of the tests mentioned in the header is done in https://trello.com/c/WcmCczmt/708-tests-for-new-cli-import-output

**Comment by ximenesuk** [comment]
This last commit is not essential for this PR but is to assist @pwalczysko in moving forward with the tests. It strips the log output from the stdout returned from `capfd`. This should make parsing the stdout for each output mode relatively straightforward.

**Comment by ximenesuk** [comment]
See: https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-merge-integration-python/358/testReport/OmeroPy.test.integration.clitest.test_import/TestImport/

**Comment by ximenesuk** [comment]
Just checking what else is needed here. Having this merged would allow @pwalczysko to move forward with modifying the existing tests to use the new default output. However, it may need some code review for at least this final commit.

/cc @sbesson

**Comment by joshmoore** [comment]
Nothing from my side.

**Comment by ximenesuk** [comment]
Annoyingly when this is merged in to the current develop a Slidebook exception is leaking in to the stdout:

```
test/integration/clitest/test_import.py java.lang.ClassNotFoundException: loci.formats.in.SlideBook6Reader
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_65]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_65]
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_65]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_65]
    at java.lang.Class.forName0(Native Method) ~[na:1.8.0_65]
    at java.lang.Class.forName(Class.java:264) ~[na:1.8.0_65]
    at loci.formats.ClassList.parseLine(ClassList.java:196) [formats-api.jar:5.2.1]
    at loci.formats.ClassList.parseFile(ClassList.java:258) [formats-api.jar:5.2.1]
    at loci.formats.ClassList.<init>(ClassList.java:138) [formats-api.jar:5.2.1]
    at loci.formats.ClassList.<init>(ClassList.java:122) [formats-api.jar:5.2.1]
    at loci.formats.ImageReader.getDefaultReaderClasses(ImageReader.java:78) [formats-api.jar:5.2.1]
    at ome.formats.importer.OMEROWrapper.createReader(OMEROWrapper.java:131) [blitz.jar:na]
    at ome.formats.importer.OMEROWrapper.<init>(OMEROWrapper.java:93) [blitz.jar:na]
    at ome.formats.importer.OMEROWrapper.<init>(OMEROWrapper.java:89) [blitz.jar:na]
    at ome.formats.importer.cli.CommandLineImporter.<init>(CommandLineImporter.java:145) [blitz.jar:na]
    at ome.formats.importer.cli.CommandLineImporter.main(CommandLineImporter.java:947) [blitz.jar:na]
```
which makes cleaning the log files a little redundant.

**Comment by sbesson** [comment]
Sorry, got distracted and forgot to comment on this on time. One final thought regarding the special handling of the logs in https://github.com/openmicroscopy/openmicroscopy/pull/4812/commits/44122a907c9845cbf0f54f667bad7a258c29b66c. Assuming only few tests actually require the debug output, would it make sense to turn debugging OFF by default in the generic `do_import` and remove this logic? With the new output, my impression is that the stdout output should still contain the information needed for most of the tests. This can certainly be part of the refactoring mentioned in the description and investigated in a separate PR to unlock work from @pwalczysko.

**Comment by ximenesuk** [comment]
Turning debugging OFF reduces the logs and the exception but there is still:

```
test/integration/clitest/test_import.py::TestImport::testImportSummary 09:58:05.937 [main] INFO  ome.formats.importer.ImportConfig - OMERO Version: 5.3.0-m4-ice35-SNAPSHOT
09:58:05.954 [main] INFO  ome.formats.importer.ImportConfig - Bioformats version: 5.2.1 revision: 0bc799913f4f10afbfeb1e2806185bab68873c34 date: 24 August 2016
09:58:06.265 [main] DEBUG o.s.nativelib.NativeLibraryUtil - processor is INTEL_64 os.arch is x86_64
09:58:06.265 [main] DEBUG o.s.nativelib.NativeLibraryUtil - architecture is OSX_64 os.name is mac os x
09:58:06.266 [main] DEBUG o.s.nativelib.NativeLibraryUtil - architecture is OSX_64 os.name is mac os x
09:58:06.266 [main] DEBUG o.s.nativelib.NativeLibraryUtil - platform specific path is META-INF/lib/osx_64/
09:58:06.266 [main] DEBUG o.scijava.nativelib.BaseJniExtractor - mappedLib is libturbojpeg.dylib
09:58:06.266 [main] DEBUG o.scijava.nativelib.BaseJniExtractor - URL is jar:file:/Users/colin/Work/repos/openmicroscopy/dist/lib/client/turbojpeg.jar!/META-INF/lib/osx_64/libturbojpeg.dylib
09:58:06.266 [main] DEBUG o.scijava.nativelib.BaseJniExtractor - URL path is file:/Users/colin/Work/repos/openmicroscopy/dist/lib/client/turbojpeg.jar!/META-INF/lib/osx_64/libturbojpeg.dylib
09:58:06.268 [main] DEBUG o.scijava.nativelib.BaseJniExtractor - Extracting 'jar:file:/Users/colin/Work/repos/openmicroscopy/dist/lib/client/turbojpeg.jar!/META-INF/lib/osx_64/libturbojpeg.dylib' to '/var/folders/_n/h2vd3wbx275497drx5kts8n00000gp/T/libturbojpeg8960830082579827984.dylib'
Image:9
```

**Comment by ximenesuk** [comment]
A downside of the `debug OFF` approach is that logging will be lost if the import fails.

**Comment by jburel** [comment]
Do you have a card for the ``debug OFF`` option/possible investigation?

**Comment by ximenesuk** [comment]
See https://trello.com/c/a9dQYVdZ/713-cli-import-with-debug-off

This is incidental to this PR, mainly related to the later commits to help @pwalczysko with testing. In the mean time the later commits remove logging and exception. If `debug=OFF` can produce silent output then the later commits here can be reverted.

**Comment by jburel** [comment]
Merging this PR so @pwalczysko can move forward
Card has been created

**Pull request merged**
