### PR TITLE
Adjust graphs API usage in Insight

### PR DESCRIPTION
**Pull request by dominikl**
Use the new graphs API in Insight, see #3515

Changed the OMEROGateway to use Chgrp2 instead of old Chgrp.

With respect to the other commands:
- Use of Delete2 was already added to OMEROGateway by @mtbc , right?
- Chown2: Couldn't find any reference to Chown in Insight. Is it actually used at all in Insight, @jburel ?

Test:
- Use the "Move to Group" function on different objects
- Try to delete various data types (Images, Project, Projects with Datasets, etc.)

--no-rebase

### CODE REVIEW

**Comment by mtbc** [comment]
Yes, I used `Delete2` in https://github.com/mtbc/openmicroscopy/commit/a5e0e5f2160d99305e1337b57455d8dd292c64b9.

**Comment by jburel** [comment]
@dominikl: change of ownership is not implemented in the clients yet.

**Comment by jburel** [comment]
removing exclude label and comment

**Comment by jburel** [comment]
Chown not currently used in client.

**Comment by jburel** [comment]
@dominikl: will you remove the usage of ```IUpdate.deleteObjects``` in this PR?

**Comment by dominikl** [comment]
@jburel Sure, I'll have a look at this.

**Comment by dominikl** [comment]
I couldn't find any more usages of deprecated methods in Insight, so everything should be migrated to the new graphs API by now.

**Comment by jburel** [comment]
```
deleteObject(ctx, link);
deleteObject(ctx, child);
```
in ```removeTagDescription``` could now be merged into the same delete call.

**Comment by jburel** [comment]
We might have to review the save/delete sequence of rois in another PR

**Comment by jburel** [comment]
Problem noticed when removing a tag from a project for example i.e. delete link
* Add a tag to a project (same for other object)
* Go to right-hand side.
* Click on button next to tag and click "remove"
* You need to do the action twice

**Comment by dominikl** [comment]
Thanks for spotting this. Was caused by my change to OMEROGateway.deleteObjects, wasn't aware that  not using Connector.submit(...) was intended; reverted it in the last commit.

**Comment by dominikl** [comment]
The method `removeTagDescription` wasn't used anyway, removed it.

**Comment by jburel** [comment]
@dominikl: 
problem reported by @pwalczysko while testing @bramalingam's PR
```
java.lang.Exception: java.lang.Exception: java.lang.IllegalArgumentException: type not supported
    at org.openmicroscopy.shoola.env.data.views.ProcessBatchCall.doStep(ProcessBatchCall.java:101)
    at org.openmicroscopy.shoola.util.concur.tasks.CompositeTask.doStep(CompositeTask.java:226)
    at org.openmicroscopy.shoola.env.data.views.CompositeBatchCall.doStep(CompositeBatchCall.java:126)
    at org.openmicroscopy.shoola.util.concur.tasks.ExecCommand.exec(ExecCommand.java:165)
    at org.openmicroscopy.shoola.util.concur.tasks.ExecCommand.run(ExecCommand.java:276)
    at org.openmicroscopy.shoola.util.concur.tasks.AsyncProcessor$Runner.run(AsyncProcessor.java:91)
    at java.lang.Thread.run(Thread.java:695)
Caused by: java.lang.IllegalArgumentException: type not supported
    at org.openmicroscopy.shoola.env.data.util.PojoMapper.getGraphType(PojoMapper.java:454)
    at org.openmicroscopy.shoola.env.data.OmeroDataServiceImpl.delete(OmeroDataServiceImpl.java:918)
    at org.openmicroscopy.shoola.env.data.views.calls.DataObjectRemover$1.initialize(DataObjectRemover.java:81)
    at org.openmicroscopy.shoola.env.data.views.ProcessBatchCall.doStep(ProcessBatchCall.java:99)
    ... 6 more

```

**Comment by pwalczysko** [comment]
Unfortunately, the bug with the ROIs https://github.com/openmicroscopy/openmicroscopy/pull/3623#issuecomment-89997689 not being deleted is already on trout latest as of now. It was not on trout latest this morning. This cannot be the fault of this PR.

**Comment by pwalczysko** [comment]
Created https://trac.openmicroscopy.org/ome/ticket/12818#ticket

**Comment by dominikl** [comment]
@pwalczysko I think this PR was the reason for the bug (but should be fixed by my last commit). Why it was on trout latest, I don't know...

**Comment by sbesson** [comment]
@pwalczysko: the stack trace you reported above appears to be on the client side so which server was used for testing should not matter. A contrario, I would expect the same operation using the Insight build from OMERO-5.1-latest would work against either server.

**Comment by dominikl** [comment]
Sorry, of course the bug is purely client side. Thought you meant, you used the 'latest' Insight build as well. Anyway, with todays merge build, it should be fixed. Could you re-test again @pwalczysko ?

**Comment by pwalczysko** [comment]
Yes, I thought I used the ``latest`` Insight build yesterday, or so I thought. But that was a mistake, I can see today it works both on merge and latest. All fine here. Closing the ticket.

**Comment by dominikl** [comment]
Could this PR be merged soon? Then I can use develop branch as basis for my upcoming Java Gateway branch.

**Comment by jburel** [comment]
@dominikl: I misread @pwalczysko and I assumed that there was still an issue.
Merging thanks.

**Pull request merged**
