### PR TITLE
Fix CLI import advanced-help for feedback report

### PR DESCRIPTION
**Pull request by sbesson**
Should give a more complete example of advanced report usage /cc @pwalczysko 

--no-rebase

### CODE REVIEW

**Comment by pwalczysko** [comment]
In general, I have some RFEs for completion. 

Although I think they are important, for time/workload reasons happy to merge this (and deal with the comment in 5.1.1). Please judge yourself.

**Comment by sbesson** [comment]
@pwalczysko: last commit should give a more thorough command example.

**Comment by pwalczysko** [comment]
All fine here. Works as expected.

**Comment by pwalczysko** [comment]
We just need one more rebuild to check the last commit.

**Comment by joshmoore** [comment]
Merging as a minor string modification. Thanks.

**Pull request merged**
