### PR TITLE
ImageJ import

### PR DESCRIPTION
**Pull request by jburel**
Handle file opened from URL. see https://trac.openmicroscopy.org.uk/ome/ticket/12849
To test this PR:
 * Open an image in ImageJ using File> Open Samples.
 * Import the image to OMERO using the OMERO.ij plugin
 * The image should now import.

### CODE REVIEW

**Comment by bramalingam** [comment]
Only JPEG imports work in the sample images. Tiff's and GIF images definitely throw an exception, 

```
loci.formats.UnknownFormatException: Unknown file format: /var/folders/y5/fwnjk4m927bbrrr13sx3spch000cgd/T/hela-cells-15841203427211626220tif
at loci.formats.ImageReader.getReader(ImageReader.java:190)
at loci.formats.ImageReader.setId(ImageReader.java:832)
at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:651)
at loci.formats.ChannelFiller.setId(ChannelFiller.java:223)
at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:651)
at loci.formats.ChannelSeparator.setId(ChannelSeparator.java:289)
at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:651)
at loci.formats.Memoizer.setId(Memoizer.java:649)
at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:651)
at ome.formats.importer.ImportCandidates.singleFile(ImportCandidates.java:414)
at ome.formats.importer.ImportCandidates.handleFile(ImportCandidates.java:570)
at ome.formats.importer.ImportCandidates.execute(ImportCandidates.java:371)
at ome.formats.importer.ImportCandidates.<init>(ImportCandidates.java:229)
at ome.formats.importer.ImportCandidates.<init>(ImportCandidates.java:180)
at org.openmicroscopy.shoola.env.data.OMEROGateway.getImportCandidates(OMEROGateway.java:6772)
at org.openmicroscopy.shoola.env.data.OmeroImageServiceImpl.importFile(OmeroImageServiceImpl.java:1033)
at org.openmicroscopy.shoola.env.data.views.calls.ImagesImporter.importFile(ImagesImporter.java:80)
at org.openmicroscopy.shoola.env.data.views.calls.ImagesImporter.access$000(ImagesImporter.java:55)
at org.openmicroscopy.shoola.env.data.views.calls.ImagesImporter$1.doCall(ImagesImporter.java:104)
at org.openmicroscopy.shoola.env.data.views.BatchCall.doStep(BatchCall.java:144)
at org.openmicroscopy.shoola.util.concur.tasks.CompositeTask.doStep(CompositeTask.java:226)
at org.openmicroscopy.shoola.env.data.views.CompositeBatchCall.doStep(CompositeBatchCall.java:126)
at org.openmicroscopy.shoola.util.concur.tasks.ExecCommand.exec(ExecCommand.java:165)
at org.openmicroscopy.shoola.util.concur.tasks.ExecCommand.run(ExecCommand.java:276)
at org.openmicroscopy.shoola.util.concur.tasks.AsyncProcessor$Runner.run(AsyncProcessor.java:91)
at java.lang.Thread.run(Thread.java:695)

at org.openmicroscopy.shoola.env.data.util.StatusLabel.update(StatusLabel.java:650)
at ome.formats.importer.ImportCandidates.safeUpdate(ImportCandidates.java:530)
at ome.formats.importer.ImportCandidates.singleFile(ImportCandidates.java:452)
at ome.formats.importer.ImportCandidates.handleFile(ImportCandidates.java:570)
at ome.formats.importer.ImportCandidates.execute(ImportCandidates.java:371)
at ome.formats.importer.ImportCandidates.<init>(ImportCandidates.java:229)
at ome.formats.importer.ImportCandidates.<init>(ImportCandidates.java:180)
at org.openmicroscopy.shoola.env.data.OMEROGateway.getImportCandidates(OMEROGateway.java:6772)
at org.openmicroscopy.shoola.env.data.OmeroImageServiceImpl.importFile(OmeroImageServiceImpl.java:1033)
at org.openmicroscopy.shoola.env.data.views.calls.ImagesImporter.importFile(ImagesImporter.java:80)
at org.openmicroscopy.shoola.env.data.views.calls.ImagesImporter.access$000(ImagesImporter.java:55)
at org.openmicroscopy.shoola.env.data.views.calls.ImagesImporter$1.doCall(ImagesImporter.java:104)
at org.openmicroscopy.shoola.env.data.views.BatchCall.doStep(BatchCall.java:144)
at org.openmicroscopy.shoola.util.concur.tasks.CompositeTask.doStep(CompositeTask.java:226)
at org.openmicroscopy.shoola.env.data.views.CompositeBatchCall.doStep(CompositeBatchCall.java:126)
at org.openmicroscopy.shoola.util.concur.tasks.ExecCommand.exec(ExecCommand.java:165)
at org.openmicroscopy.shoola.util.concur.tasks.ExecCommand.run(ExecCommand.java:276)
at org.openmicroscopy.shoola.util.concur.tasks.AsyncProcessor$Runner.run(AsyncProcessor.java:91)
at java.lang.Thread.run(Thread.java:695)
Caused by: loci.formats.UnknownFormatException: Unknown file format: /var/folders/y5/fwnjk4m927bbrrr13sx3spch000cgd/T/hela-cells-15841203427211626220tif
at loci.formats.ImageReader.getReader(ImageReader.java:190)
at loci.formats.ImageReader.setId(ImageReader.java:832)
at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:651)
at loci.formats.ChannelFiller.setId(ChannelFiller.java:223)
at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:651)
at loci.formats.ChannelSeparator.setId(ChannelSeparator.java:289)
at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:651)
at loci.formats.Memoizer.setId(Memoizer.java:649)
at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:651)
at ome.formats.importer.ImportCandidates.singleFile(ImportCandidates.java:414)
... 16 more
```

Looks like, its got to do with the way the image is downloaded. The extension gets added to the file name and is considered as part of the filename.

**Comment by jburel** [comment]
more commits to come

**Comment by jburel** [comment]
@bramalingam: last commit should fix the issue.

**Comment by bramalingam** [comment]
With regards to this PR, it fixes whatever we can handle from our end. Good to merge.

Limitation: 
ImageJ saves stacks as zip files on their ftp server. These images are throwing an exception when the following workflow is used.

File --> open samples --> stacks/non jpeg images.

But when I cache the images locally using,
File--> open samples --> cache locally

And then unzip the files, it extracts the original files locally. Now a regular File--> Open of the local sample file, and an upload and save to OMERO, will upload the images without any issues.

**Comment by joshmoore** [comment]
@jburel : ok to leave you to file cards/tickets & merge?

**Comment by jburel** [comment]
I will add a note on Trello card

**Comment by joshmoore** [comment]
Sounds good. Thanks.

**Comment by jburel** [comment]
added to https://trello.com/c/4mDNygGv/223-5-1-3-follow-up

**Pull request merged**
