### PR TITLE
Add 5.4.1 history

### PR DESCRIPTION
**Pull request by hflynn**
# What this PR does

Adds version history for 5.4.1 release

# Testing this PR

Proofread. If you want to test build, copy content on to the docs page manually and build the sphinx docs locally.

# Related reading

See https://github.com/orgs/openmicroscopy/projects/3? and https://trello.com/c/BTpTo3NT/30-version-history-pr

### CODE REVIEW

**Comment by hflynn** [comment]
Renders fine:
5-4-1-screenshot

**Comment by jburel** [comment]
@hflynn: could you add a new entry under CLI section for https://github.com/openmicroscopy/openmicroscopy/pull/5564

**Comment by hflynn** [comment]
@jburel pushed

**Comment by jburel** [comment]
Thanks looking good.

**Comment by hflynn** [comment]
Last commit should stop deletion of the banner on https://github.com/openmicroscopy/ome-documentation/pull/1813 once this is merged.

**Comment by jburel** [comment]
Everything is now in place.
Merging

**Pull request merged**
