### PR TITLE
Interpolate config option (rebased onto dev_5_1)

### PR DESCRIPTION
**Pull request by dominikl**
This is the same as gh-4087 but rebased onto dev_5_1.

----

Same as #4084 but for Insight. 
Test: Best to be tested in conjunction with #4084 .

### CODE REVIEW

**Comment by dominikl** [comment]
--rebased-from #4087

**Comment by jburel** [comment]
see https://github.com/openmicroscopy/openmicroscopy/pull/4155#issuecomment-139375127
for difference between the clients

**Comment by jburel** [comment]
```
     boolean isInterpolation() {
-        return interpolation;
+        if (ImViewerFactory.isInterpolation() != null)
+            return ImViewerFactory.isInterpolation();
+        else
+            return interpolationServerProperty;
     }
```
else not required

**Comment by jburel** [comment]
works as expected

**Comment by jburel** [comment]
Code comment can be handled in a follow-up PR since @dominikl is away and the matching web PR has been merged.

**Pull request merged**
