### PR TITLE
DnD move dataset

### PR DESCRIPTION
**Pull request by jburel**
Allow to move dataset out of project via DnD.
see https://trac.openmicroscopy.org/ome/ticket/11083

To test:
 * Select a dataset in a Project
 * Move the dataset out of the project using DnD
 * The action should be performed w/o dialog popping up

### CODE REVIEW

**Comment by gusferguson** [comment]
@jburel 

Tested using OMERO.insight-5.1.0-m5-281-55aa544-ice34-b432-win user-3 read-only-1
Confirmed with OMERO.insight-5.1.0-m5-281-55aa544-ice34-b432-mac_Java7+

Not working at all. 
Get + icon when dragging but nothing happens on drop - no dialog opens, no movement of dataset occurs. 
On Mac get red no icon when trying to drag and drop into orphaned or other dataset. Don't get this in Windows.

**Comment by jburel** [comment]
you cannot drop a dataset into another dataset.
The orphaned is another problem. On the ticket it was indicating dropping on user.
Does it work?

**Comment by gusferguson** [comment]
@jburel  - no does not work dropping on user.

**Comment by jburel** [comment]
humm
You will have to show me, just tested with today's build on mac and I cannot reproduce issue.

**Comment by gusferguson** [comment]
@jburel - drag and drop works fine on Mac now but still not working on Windows in Parallels. Need to test on full windows machine.

**Comment by jburel** [comment]
@gusferguson: it is working on windows, but might not be as "natural" as we look like it to be.

**Comment by gusferguson** [comment]
@jburel - Drag and Drop works on Windows - Parallels and Stand-alone if shift key is held down while D&Ding. On Windows still not getting the + icon appearing as on Mac.

Agree should merge this PR and roll the Windows issue into a thorough review of state of Drag and Drop on Mac, Windows and  Linux. Will also include any other bugs/RFEs outstanding related to D&D.

Good to merge.

**Comment by jburel** [comment]
--no-rebase

**Pull request merged**
