### PR TITLE
Allow ome tiff export

### PR DESCRIPTION
**Pull request by will-moore**
# What this PR does

Allows export of image as OME-TIFF, even if you can't download the original image file.
See https://trello.com/c/bxkT6Jla/107-export-ome-tiff-export-disabled-in-web-when-available-from-cli

# Testing this PR

Check which options are available in the 'Download' drop-down menu:

1. For small image:
     - Download - YES
     - Export as OME-TIFF - YES
1. SPW image or Well:
    - Download - NO
    - Export as OME-TIFF - YES
1. Big Image:
    - Download - YES
    - Export as OME-TIFF - NO
1. Image in Share (not owned by user):
    - Download - NO
    - Export as OME-TIFF - NO
1. Multiple Images selected:
    - Download - YES except for SPW images
    - Export as OME-TIFF - NO

### CODE REVIEW

**Comment by jburel** [comment]
Could you add some tests please? since it is something that might be easily missed later on if only done manually

**Comment by dominikl** [comment]
Works as described 👍

**Comment by joshmoore** [comment]
Nice tests!

**Comment by mtbc** [comment]
https://ci.openmicroscopy.org/job/OMERO-DEV-merge-robotframework/699/robot/Web%20&%20Web/Web_1/Center%20Right%20Panel%20Tests/Test%20Download%20Menu/ looks accusatory.

**Comment by will-moore** [comment]
Tests looking better: https://ci.openmicroscopy.org/job/OMERO-DEV-merge-robotframework/702/robot/Web%20&%20Web/Web_1/Center%20Right%20Panel%20Tests/Test%20Download%20Menu/

**Comment by will-moore** [comment]
TODO: Check help and other docs to see if they need updating with this change.

**Comment by jburel** [comment]
Help PR has been opened https://github.com/openmicroscopy/ome-help/pull/267

**Pull request merged**
