### PR TITLE
Failing test

### PR DESCRIPTION
**Pull request by jburel**
# What this PR does

Attempt to stabilize the flaky test

# Testing this PR
Check that the test is green

### CODE REVIEW

**Comment by mtbc** [comment]
OMERO-DEV-merge-integration-java is back to green this morning at least, let's see how it goes. To be honest, I am not quite sure what it is that `testDoAllTimingFinishesOnLoop` is trying to test; the description of https://github.com/openmicroscopy/openmicroscopy/commit/a527208d has clues. It might be interesting to compare this with its kin in `test_cmdcallback.py`.

**Comment by jburel** [comment]
This one has not been flaky for several runs now

**Comment by jburel** [comment]
@mtbc happy to have that merge? we can spend some time post release

**Comment by mtbc** [comment]
The test failed this morning and I am not sure what it aims to test anyway. No strong objections though: happy to go with whatever @joshmoore thinks.

**Pull request merged**
