### PR TITLE
Improve CLI upload plugin (rebased onto metadata52)

### PR DESCRIPTION
**Pull request by manics**
This is the same as gh-4772 but rebased onto metadata52.

----

# What this PR does

This PR standardises the `upload` output to be of the form `Object:id` (including multiple ids and elision if necessary). It also adds an `--annotation` option to create `FileAnnotation` objects directly from the uploaded files. The integration tests have been modified and expanded. Finally, it removes the unused `--pytable` option.

# Testing this PR

Use a locally installed server (or installation of OMERO.py) execute against a local or remote server some `upload` commands, single and multiple files, and check the output:
```
$ omero upload new.tmp new.xml
OriginalFile:93,94
$ omero obj get OriginalFile:93 name
new.tmp
$ omero upload new.tmp new.xml --annotate
FileAnnotation:10,11
$ omero obj get FileAnnotation:10 file
OriginalFile:91
$ omero obj get OriginalFile:91 name
new.tmp
```
Note that large files may take a while to upload so testing is best done with minimal files.

Note that the old-style output was:
```
$ omero upload analysis.csv
Uploaded analysis.csv as 275
```

The integration tests should pass.

# Additional discussion

Note: there was some discussion in slack as to whether the file ids should also be produced:
```
$ omero upload new.tmp new.xml --annotate
FileAnnotation:10,11
OriginalFile:91,92
```
I think this unnecessarily complicates the output given the the ids could be queried using `omero obj`.

Historically, certain file extensions are excluded according to https://github.com/openmicroscopy/openmicroscopy/blob/develop/components/tools/OmeroPy/src/omero/util/originalfileutils.py this is intended prevent image files being uploaded. The extension list is probably hopelessly out of date. Also, are there occasions when an image file may want to be uploaded? I have left this as is but it may warrant further discussion.

The removed `--pytable` option did nothing at all. There may have been an intention to have the option do something specific.

### CODE REVIEW

**Comment by manics** [comment]
--rebased-from #4772

**Comment by ximenesuk** [comment]
@joshmoore this is a PR that @manics rebased as soon as my develop PR, gh-4772, was open. Since then the scope of that PR has changed significantly. I assume Simon needed this change for IDR work. If someone could close this PR I can rebase gh-4472 and open a PR against metadata for review.

**Comment by joshmoore** [comment]
@ximenesuk : closing. Will the other work still be compatible with your changes?

**Comment by ximenesuk** [comment]
Simon didn't add anything to my PR. His rebase of my PR was when the scope of this was much wider. My now merged PR simply changes the output of the `upload`  command. Simon can now use that in a script to do the file annotation work he needs.

**Comment by joshmoore** [comment]
Understood. Guess I meant more, will your previous work still be applicable on top of the new merge point?

**Comment by ximenesuk** [comment]
I think so, the changes are fairly minimal

**Pull request closed without merging**
