### PR TITLE
static files versioning

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
Ticket https://trac.openmicroscopy.org.uk/ome/ticket/10437. This PR adds:

 - version numbers to all 3rd party JavaScripts and CSS stylesheets, for example: ```http://localhost:4080/static/3rdparty/panojs-2.0.0/PanoJS.js```

 - suffix those omero specific with omero version, for example: ```<script type="text/javascript" src="{% static "webgateway/js/ome.popup.js"|add:url_suffix %}"></script>``` creates ```http://localhost:4080/static/webgateway/js/ome.popup.js?_5.1.0-m6-ice35-SNAPSHOT```

To test:
 - search for all keywords = names of the 3rd party libraries had name changed that all links are updated. For list of keywords refer to name of the commits below *adding version number to 3rdparty/***KEYWORD**
 - test if there are no HTTP404 when loading css and js
   - image viewer
   - data manager
   - metadata panel (including: edit name, annotation forms, batch annotation)
   - tags
   - public/shares
   - basket
   - activity
   - webadmin (including: sort users, piechart, creation)
 - test examples https://github.com/aleksandra-tarkowska/openmicroscopy/tree/js_versioning/examples/Web

@will-moore @pwalczysko 

--no-rebase

### CODE REVIEW

**Comment by joshmoore** [comment]
```
./components/tools/OmeroWeb/omeroweb/custom_context_processor.py:6:34: W292 no newline at end of file
```

**Comment by sbesson** [comment]
https://ci.openmicroscopy.org/job/OMERO-5.1-breaking-integration-web/lastCompletedBuild/testReport/ is green. Breaking server redeployed. Quick fire test of the various OMERO.web components does not reveal any major breakage. To be tested tomorrow as part of the merge  build.

**Comment by pwalczysko** [comment]
On login as user-6 to trout merge (after I have logged in and out from another private window in Firefox) I get
```
Traceback (most recent call last):

  File "/opt/hudson/workspace/OMERO-5.1-merge-deploy/src/dist/lib/python/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/opt/hudson/workspace/OMERO-5.1-merge-deploy/src/dist/lib/python/omeroweb/decorators.py", line 469, in wrapped
    retval = f(request, *args, **kwargs)

  File "/opt/hudson/workspace/OMERO-5.1-merge-deploy/src/dist/lib/python/omeroweb/decorators.py", line 519, in wrapper
    context = f(request, *args, **kwargs)

  File "/opt/hudson/workspace/OMERO-5.1-merge-deploy/src/dist/lib/python/omeroweb/webclient/views.py", line 2634, in activities
    obj_data['browse_url'] = getObjectUrl(conn, v)

  File "/opt/hudson/workspace/OMERO-5.1-merge-deploy/src/dist/lib/python/omeroweb/webclient/views.py", line 2459, in getObjectUrl
    links = list(fa.getParentLinks(ptype))

AttributeError: 'NoneType' object has no attribute 'getParentLinks'


<WSGIRequest
path:/merge/webclient/activities/,
GET:<QueryDict: {}>,
POST:<QueryDict: {}>,
COOKIES:{'csrftoken': 'vqjLBBanvPXSAr0gnOgoSaTeeISXeikV',
 'sessionid': 'xzccwlzdg0phvh3gyzm53uo19fc5tbzf'},
META:{'CONTENT_LENGTH': '',
 'CONTENT_TYPE': '',
 u'CSRF_COOKIE': u'vqjLBBanvPXSAr0gnOgoSaTeeISXeikV',
 'HTTPS': 'on',
 'HTTP_ACCEPT': '*/*',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_ACCEPT_LANGUAGE': 'en-GB,en;q=0.5',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_COOKIE': 'csrftoken=vqjLBBanvPXSAr0gnOgoSaTeeISXeikV; sessionid=xzccwlzdg0phvh3gyzm53uo19fc5tbzf',
 'HTTP_HOST': 'trout.openmicroscopy.org',
 'HTTP_REFERER': 'https://trout.openmicroscopy.org/merge/webclient/',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:33.0) Gecko/20100101 Firefox/33.0',
 'HTTP_X_REQUESTED_WITH': 'XMLHttpRequest',
 'PATH_INFO': u'/webclient/activities/',
 'QUERY_STRING': '',
 'REQUEST_METHOD': 'GET',
 'SCRIPT_INFO': '/merge',
 'SCRIPT_NAME': u'/merge',
 'SERVER_NAME': 'ome-c6100-3',
 'SERVER_PORT': '443',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'wsgi.errors': <flup.server.fcgi_base.TeeOutputStream object at 0x3eebe10>,
 'wsgi.input': <flup.server.fcgi_base.InputStream object at 0x3eeb090>,
 'wsgi.multiprocess': True,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'https',
 'wsgi.version': (1, 0)}>
```

**Comment by aleksandra-tarkowska** [comment]
As discussed, that is not related. Basically there is problem when @pwalczysko opened merge in FF windows1 then latest in window2 he was kicked out from merge as cookies was messed up. I will investigate it separately

**Comment by will-moore** [comment]
OMERO.figure is failing with

```
  File "/opt/hudson/workspace/OMERO-5.1-merge-deploy/src/dist/lib/python/django/template/base.py", line 781, in _resolve_lookup
    (bit, current))  # missing attribute

VariableDoesNotExist: Failed lookup for key [url_suffix] in u"[{'False': False, 'None': None, 'True': True}, {'userFullName': u'user-3 user-3', 'scriptMissing': True}, {}]"
```
Need to investigate....

**Comment by pwalczysko** [comment]
From the morning testing summary:
  - webtagging not working see https://github.com/dpwrussell/webtagging/issues/17 and 2 other issues there (works fine on latest)
  - figure not working (works on latest)
  - no other problems detected

cc @dpwrussell

**Comment by will-moore** [comment]
The problem in OMERO.figure is caused in views.py by
```
from django.shortcuts import render_to_response
...
return render_to_response("figure/index.html", context)
```
where index.html contains:
```
{% include "webgateway/base/includes/script_src_jquery.html" %}
```

This can be fixed by importing and using the @render_response decorator
```
from omeroweb.webclient.decorators import, render_response
...
@login_required()
@render_response()
def index(request, fileId=None, conn=None, **kwargs):
...
context['template'] = "figure/index.html"
return context
```
 
This is what webtagging and OMERO.gallery do.
But any apps that do what OMERO.figure is doing will be broken.
Probably best option for now is to remove the ```url_suffix``` from webgateway/base/includes/script_src_jquery.html
and manually add version if needed.

**Comment by aleksandra-tarkowska** [comment]
@will-moore if you use render_to_response and want to take an advantage if omeroweb you should use

```
def index(request):
    context = {'scriptMissing': scriptMissing,
    'userFullName': userFullName}
    return render_to_response("figure/index.html",
                              context,
                              context_instance=RequestContext(request))
```

**Comment by aleksandra-tarkowska** [comment]
@will-moore if you use render_to_response and want to take an advantage if omeroweb you should use

```
def index(request):
    ...
    context = {'scriptMissing': scriptMissing,
               'userFullName': userFullName}
    return render_to_response("figure/index.html",
                              context,
                              context_instance=RequestContext(request))
```

This is just one possibility, the important thing is that you should process the csrf token somewhere, and ```RequestContext``` does that. It is ` mistake avoiding it. That also explain why webtagging got 403

**Comment by sbesson** [comment]
Discussed with @aleksandra-tarkowska @jburel @will-moore @pwalczysko earlier. To assess whether this PR can make it into 5.1.0-m5 in its current state, we should make sure we implement and test the corresponding fixes in our web applications, essentially `figure` and `webtagging` /cc @dpwrussell. Goal is to have staging versions of these patched apps deployed today on trout/merge. If everything works as expected, we can move forward with this PR included in m5 and have new versions of the web apps released together with `5.1.0`. Else, this PR may have to be split into multiple parts.

**Comment by aleksandra-tarkowska** [comment]
as a summary of the discussion with @sbesson and @will-moore we remove suffix from template to avoid conflict with previous version. Although this change will go into 5.1.1 once new Figure is released. Following that discussion we need to make a clear statement in our developers doc how to use common resources.

**Comment by pwalczysko** [comment]
From the UI side, all works as expected here.

**Comment by chris-allan** [comment]
While the use of `render_to_response()` in the manner outlined above certainly worked before the changes in this PR were proposed it has really never been the most robust way to render templates in view functions. We use this idiom in a single place across the entirety of OMERO.web:  `omeroweb/feedback/views.py`. At a glance it also looks like the corresponding template, `omeroweb/feedback/templates/thanks.html`, will have been broken by this PR. This should be investigated and at a minimum brought in line with the strategy used by the rest of OMERO.web.

**Any** use of context processors and the subsequent template dependence that goes along with that will have exposed these issues. These are the simple realities of the template inheritance strategy we have collectively decided to follow.

It is also worthwhile noting that the scope of change here is not limited to OMERO.web plugins. All OMERO.web view methods that deal with templates are impacted by this change. We have semi-defensively coded for these conditions with the `@render_response()` decorator added in 162b52301b943dc4cb401426f4b4019a98d2bb27:
 * https://trac.openmicroscopy.org.uk/ome/ticket/7394

Furthermore, we fairly explicitly state the need for OMERO.web template writers to use the `@render_response()` decorator in our documentation:
 * https://www.openmicroscopy.org/site/support/omero5.0/developers/Web/WritingTemplates.html#using-webclient-templates

The following page should likely be brought into alignment with that desire (it uses `render_to_response()`):
 * https://www.openmicroscopy.org/site/support/omero5.0/developers/Web/WritingViews.html

Documentation changes in openmicroscopy/ome-documentation#1148 or subsequent PR might reflect this depending on the desired endpoint for concerned developers.

**Comment by aleksandra-tarkowska** [comment]
@chris-allan thanks page was fixed already in https://github.com/openmicroscopy/openmicroscopy/pull/3635

**Comment by aleksandra-tarkowska** [comment]
thanks @chris-allan for pointing out missed places in the doc. I will review that again.

**Comment by chris-allan** [comment]
Understood. The changes in #3635 do indeed resolve any potential problems with `thanks.html` as a result of the changes proposed in this PR.

**Comment by sbesson** [comment]
Thanks all. Any last comment/veto before merging this?

**Comment by chris-allan** [comment]
Good to merge. :+1:

**Pull request merged**
