### PR TITLE
renaming mail properties to match omero.mail.*

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
https://github.com/aleksandra-tarkowska/openmicroscopy/commit/f01f975990d1ff214474cbebb2dbcfc830ab4e3b#commitcomment-9945312
This should pick up automatically email properties set for omero server

To test set:

 - debug false
 - ```bin/omero config set omero.mail.from "email@domain"```
 - ```bin/omero config set omero.mail.host "localhost"```
 - ```bin/omero config set omero.mail.port 25```
 - ```bin/omero config set omero.mail.username```
 - ```bin/omero config set omero.mail.password```
 - ```bin/omero config set omero.web.admins '[["Full Name", "email@domain"]]'```

then go to https://trout/merge/tagsearch/. There is a broken link.
For 500 test locally

cc: @joshmoore @sbesson

### CODE REVIEW

**Comment by joshmoore** [comment]
@hflynn : @aleksandra-tarkowska will open a paragraph against sysadmin/mail.txt for this.

**Comment by aleksandra-tarkowska** [comment]
```
omero.mail.config=true
omero.mail.from=email@domain.com
omero.mail.host=localhost
omero.web.admins=[["name", "name@domain.com"]]
```
sent message about broken link
```
---------- MESSAGE FOLLOWS ----------
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Subject: [OMERO.web - admin notification]Broken INTERNAL link on localhost:4080
From: email@domain.com
To: name@domain.com
Date: Tue, 24 Mar 2015 15:24:10 -0000
Message-ID: <20150324152410.16343.67119@Mac-Book-Pro.local>
X-Peer: 127.0.0.1

Referrer: http://localhost:4080/webclient/login/?url=%2Fwebclient%2F
Requested URL: /static/webgateway/css/reset.css
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:36.0) Gecko/20100101 Firefox/36.0
IP address: 127.0.0.1
------------ END MESSAGE ------------
```

**Comment by aleksandra-tarkowska** [comment]
last commit allow getting HTTP500

```
---------- MESSAGE FOLLOWS ----------
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Subject: [OMERO.web - admin notification]ERROR (EXTERNAL IP): Internal Server
 Error: /omero/webclient/login/
From: email@domain.com
To: name@domain.com
Date: Tue, 24 Mar 2015 15:59:11 -0000
Message-ID: <20150324155911.17881.24532@Mac-Book-Pro.local>
X-Peer: 127.0.0.1

Traceback (most recent call last):

  File "/openmicroscopy/dist/lib/python/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/openmicroscopy/dist/lib/python/omeroweb/webclient/views.py", line 112, in login
    raise AttributeError('myerror')

AttributeError: myerror


<WSGIRequest...>
------------ END MESSAGE ------------
```

**Comment by aleksandra-tarkowska** [comment]
@joshmoore @sbesson see https://github.com/openmicroscopy/ome-documentation/pull/1171#issuecomment-85588218

**Comment by sbesson** [comment]
Deployed on `breaking` with default mail config. Tested 500 with and without `omero.web.admins` set (email send in the first case, no email in the second case). Tested regular mail sending using webadmin. Removing `breaking`.

**Comment by joshmoore** [comment]
Thanks, @aleksandra-tarkowska. There's some question about the impact of the logging handler on each request, but we'll test that with one of the RC builds.

**Pull request merged**
