### PR TITLE
Save last change

### PR DESCRIPTION
**Pull request by will-moore**
This is a prototype for https://trello.com/c/mpUSdeUU/43-rendering-settings-applytoall

Investigation on how to apply limited rendering settings (last change) to all images in Dataset.
To test:
 - Select image from Dataset - open Preview panel
 - Adjust sliders or pick colour or change greyscale/colour
 - The 'Save Last Change' button will become enabled with change of text - tooltip gives more info
 - Clicking this button will apply last change to other images in Dataset.

### CODE REVIEW

**Comment by jburel** [comment]
Marking it as onhold so it is not listed

**Comment by gusferguson** [comment]
@will-moore - this is very confusing from a user POV! Not at all apparent how this differs from existing "Save to All".

**Comment by will-moore** [comment]
@gusferguson  Thanks for the feedback. Suggestions welcome!

**Comment by gusferguson** [comment]
@will-moore - I am struggling with this as I don't know the requirement being pursued. Where did it come from?

**Comment by jburel** [comment]
@gusferguson: we discussed it during the first scoping meeting.
Let's sit together again. I agree with you that the button is confusing I mentioned it to @will-moore yesterday.

**Pull request closed without merging**
