### PR TITLE
No thumbs jstree

### PR DESCRIPTION
**Pull request by will-moore**
This fixes a regression introduced in #4242 where images with no thumbnails are not loaded in jsTree.

To test, find images that have no thumbnail and check that they are shown in jsTree and in center panel (with place-holder "No Image" thumbnail).
Also re-test the loading of new thumbnails on jsTree refresh (not browser refresh) when new thumbnails have been created in another client (another web browser or Insight).

This PR is actually just 2 commits on top of Center panel sync: #4242, so that should be merged before this is.

### CODE REVIEW

**Comment by pwalczysko** [comment]
@will-moore : Is image in Share which has been deleted ``an image with no thumbnail`` ? What are the other ways to get such images ?

**Comment by will-moore** [comment]
@pwalczysko I'm not sure of the best way to create an image with no thumbnail. I have a couple locally from failed imports.
You can actually delete a thumbnail via CLI,
E.g. delete thumbnail for Image ID 25152:
```
$ bin/omero delete Image/Thumbnail:25152 --report
```
If you do this then you'll see that the image still appears in jsTree - but you won't see the "broken thumbnail" placeholder, since when the browser tries to get a thumbnail a new one is created!

**Comment by will-moore** [comment]
https://eel.openmicroscopy.org/merge/webclient/?show=image-25152 has no thumb and file deleted so it can't make more! (user-3)

**Comment by pwalczysko** [comment]
Works as expected. Ready to merge.

**Comment by will-moore** [comment]
@sbesson I was hoping that this PR just showed the last 2 commits after #4242 was merged. But maybe I need to merge develop into this branch? Or rebase?

**Comment by sbesson** [comment]
@will-moore so did I but something clearly happened on the GH interface. Discussing with @jburel, let's get this merged as this has been cleared and we can review less PRs tomorrow.

**Pull request merged**
