### PR TITLE
Robot test delete image in share

### PR DESCRIPTION
**Pull request by will-moore**
From comment at https://github.com/openmicroscopy/openmicroscopy/pull/3757#issuecomment-95871006

This robot test creates a share with an image, deletes the image and looks for the "Object Deleted" text on the same in in the Public tree.
To test:
 - check https://ci.openmicroscopy.org/view/Failing/job/OMERO-5.1-merge-robotframework for failures of this test.

### CODE REVIEW

**Comment by joshmoore** [comment]
2 cents:
 * :yum: for more tests!
 * `xpath=//div[@id='dataTree']//li[@rel='share']/a` seems a bit fragile though. Not sure what the policy is on adding new IDs, but this might be a case for one.

**Comment by joshmoore** [comment]
Travis kick for appbundler download.

**Comment by will-moore** [comment]
@joshmoore What's the concern about the xpath? Worried about ```rel='share'``` or ```id='dataTree' ``` changing? I don't think they are much less likely to change than a new ID. We have many other xpaths that are much longer elsewhere in robot tests.

**Comment by joshmoore** [comment]
I'm not particular worried about rel='share' or id='dataTree' changning, just more generally saying that shorter xpaths and more well-named objects that the team can make use of for writing robot tests would be a generally "Good Thing" :tm: for reducing the obfuscation.

**Comment by will-moore** [comment]
Robot tests are failing due to changes in Delete callbacks: https://github.com/joshmoore/openmicroscopy/commit/0cee8fc756e0c64532647da280e095a47d23373f?diff=unified#diff-e42f9d16e28000e8868a7d8bc361aa1aR146
@joshmoore is on the case!

**Comment by joshmoore** [comment]
Sorry about that! And thanks for the digging, @will-moore. (Kudos to the robot tests): https://github.com/openmicroscopy/openmicroscopy/pull/3815

**Comment by will-moore** [comment]
Tests using share were failing due to changes in the Share dialog in https://github.com/openmicroscopy/openmicroscopy/pull/3813
Fixed in last commit above.

**Comment by will-moore** [comment]
Test is looking good: https://ci.openmicroscopy.org/view/Failing/job/OMERO-5.1-merge-robotframework/244/robot/ @joshmoore Good to merge.

**Pull request merged**
