### PR TITLE
Changed default group name to 'active group'

### PR DESCRIPTION
**Pull request by dominikl**
Tiny PR changing the name of the 'Default Group' to 'Active Group'
See [Trello Card](https://trello.com/c/GkdpN8wD/311-rfe-change-default-group-to-active-group-in-uis)
(corresponding Web PR: #3514 )

### CODE REVIEW

**Comment by mtbc** [comment]
Also change the batch call description in `org.openmicroscopy.shoola.env.data.views.calls.AdminLoader.java`?

**Comment by jburel** [comment]
Change in UI made
Problem about changing active group still exists, does not have to be done in this PR
  * log in as a user members of at least 2 groups
  * add the 2 groups to display
  * Change the active group.

as suggested by @mtbc, maybe update the description so it is less confusing.

**Comment by dominikl** [comment]
To be more consistent I'm going to make some more changes within this PR, e. g. also change the method name in the ExperimenterData Pojo.

**Comment by jburel** [comment]
@dominikl: if you change the pojo you will need to add a new method and mark the existing one "deprecated"

**Comment by dominikl** [comment]
Thanks, nearly forgot that. The problem with the change of the active group is a bit trickier than I initially thought. I'll tackle this in another PR. But changing the logged in user's active group and confirming this via the Save button should work, what doesn't work is changing the active group and then switching to another object (which triggers the confirmation dialog, if you want to save the changes). But as I said, better to open a separate PR for that.

**Comment by dominikl** [comment]
Closing after discussion

**Pull request closed without merging**
