### PR TITLE
CLI error report

### PR DESCRIPTION
**Pull request by jburel**
In this PR:
 * Remove usage of commons-http
 * Modify submission of files: support for both http and https.
 * Fix submission of log file (server import log) when using --logs
 * If the file that failed to import the log file (if available) is also submitted.
 * A zip is created if number of files to submit > 1.

We use https://qa.staging.openmicroscopy.org to test this PR
Test 1
 * Try to import  a faulty image e.g. squig/data_repo/test_images_bad/multi-image-pixels.ome.tif . 
 * Test logs report i.e. --logs . Check that the corresponding entry has a .log file (not .zip)
```
bin/omero import -s localhost -u root -w omero -p 4064  --report --logs PATH_TO/multi-image-pixels.ome.tif
```
 * Test upload report --upload Check that the corresponding entry has .zip
```
bin/omero import -s localhost -u root -w omero -p 4064  --report --upload PATH_TO/multi-image-pixels.ome.tif
```

Test 2
 * Try to import squig/data_repo/test_images_broken/broken_images_scenario/fails_at_processing/wrong-light-source-mk3.ome
 * Test logs. Make sure that there is no NPE in console and that the error is submitted. No log file
 * Test upload. In that case, only the file should be upload since the log is not available.

The tests under blitz will have to reviewed, To be done in another PR.

### CODE REVIEW

**Comment by pwalczysko** [comment]
When passing the line in Test 1 both when importing to localhost as well as wehn importing to trout, I do not get any new entries in the qa staging. Obviously I am not clear about where to set the qa server.

**Comment by pwalczysko** [comment]
@sbesson : Re: Clent-side failure was tested with test\&physicalSizeX\=-1.fake.

How did you get the file please ? Possibly I need to update https://www.openmicroscopy.org/private/ome-internal/testing_scenarios/Qa.html

**Comment by pwalczysko** [comment]
This is for another PR, but I guess the Feedback in ``bin/omero import -- --advanced-help`` shoiuld be ``Feedback options`` as these are options and also, the examples should be written out with some (fake) imported images, just as are the other examples in the  ``bin/omero import -- --advanced-help`` , otherwise it is misleading.
```
Feedback:
  ---------

    --qa_baseurl=ARG	Specify the base URL for reporting feedback
  e.g. $ bin/omero import -- --qa_baseurl=https://qa.staging.openmicroscopy.org/qa
       $ ./importer-cli --qa_baseurl=https://qa.staging.openmicroscopy.org/qa
```

**Comment by pwalczysko** [comment]
Bug: 
When the ``fake...`` file from @sbesson 's example above is imported with ``--upload``, the feedback in qa does not have the file. 

Workflow:
   - exacute ``touch "test&physicalSizeX=-1.fake"``
   - execute ``bin/omero import test\&physicalSizeX\=-1.fake --report --upload --qa_baseurl=https://qa.staging.openmicroscopy.org/qa``
   - go to qa staging, find the newly created qa feedback, open it, scroll to the bottom - > no uploaded file is present
  - execute now ``bin/omero import test\&physicalSizeX\=-1.fake --report --upload --logs --qa_baseurl=https://qa.staging.openmicroscopy.org/qa``
  - go to qa staging, open the feedback -> now both the log and the file is present

**Comment by jburel** [comment]
Thanks @pwalczysko for the report. I will have a look.

**Comment by pwalczysko** [comment]
All the other tests passed, but note that because the ``test_images_bad`` imports without failure, we have no testing file which would have a log file to it which we could suppose to be uploaded.

In Summary:
 1 Bug
 1 RFE for testing file which would surely create a log which will be uploaded

**Comment by jburel** [comment]
try images from ```test_images_broken```

**Comment by pwalczysko** [comment]
I have found a valid log file which submits to qa staging as well
``bin/omero import ~/test_images_broken/volocity/ -s trout.o...y.org  --report --logs  --qa_baseurl=https://qa.staging.openmicroscopy.org/qa
``

**Comment by jburel** [comment]
@pwalczysko: clarification (with your example above)
```--logs``` will only upload the log if any
```--upload``` will upload the file and the log. A zip is created and submitted. no need to have the ```--logs``` option

**Comment by pwalczysko** [comment]
@jburel understood, ta. @sbesson @jburel : we definitely should reformulate the ``bin/omero import -h`` output:
```
Feedback arguments:
  Optional arguments passed strictly to Java allowing to report errors to the OME team.

  --report                              Report errors to the OME team (**)
  --upload                              Upload broken files with report (**)
  --logs                                Upload log file with report (**)
  --email EMAIL                         Email for reported errors (**)
```
is just not passing these complex options, also it is not passing the idea that ``--report`` is compulsory if you want to use ``--upload``, ``--logs`` and ``--email``

**Comment by jburel** [comment]
@pwalczysko: I have cleaned up a bit the report sent to log.
I will update the command.

**Comment by jburel** [comment]
@sbesson, @pwalczysko: I found the source of the problem
The .fake file is an empty file that why it does not get uploaded.

@pwalczysko: if you want to test with the existing build, just open the fake file in a text editor and a character e.g. 1. It will work.
I will push a commit improving error report so it is not misleading.

**Comment by pwalczysko** [comment]
@jburel @sbesson : Updated the scenario accordingly see https://github.com/openmicroscopy/ome-internal/pull/201 - I opted for not using the fake file at the end, because it anyway does not deliver a log and is harder to create. It will probably be still necessary to clarify the old versions of CLI, web and insight testing tactics in the scenario.

**Comment by sbesson** [comment]
@jburel's commit 395ab30 is only modifying the Java `importer-cli`, I will push a commit to fix the CLI import help shortly.

**Comment by pwalczysko** [comment]
Additional info: after the problems with qa staging were resolved, the zip was submitted with the command in comment  https://github.com/openmicroscopy/openmicroscopy/pull/3289#issuecomment-69324593    (see https://qa.staging.openmicroscopy.org/qa/feedback/9548/) as expected, but again, there is no mention of the ``log`` in the submission report in console, the report looks exactly like in the comment https://github.com/openmicroscopy/openmicroscopy/pull/3289#issuecomment-69324593

**Comment by jburel** [comment]
@pwalczysko: I will have a look.

**Comment by jburel** [comment]
2015-01-21 21:29:25,615 172138     [      main] INFO         ome.formats.importer.ImportLibrary - Exiting on error
2015-01-21 21:29:25,615 172138     [      main] INFO      ome.formats.importer.cli.ErrorHandler - Sending error report (1)...
2015-01-21 21:29:29,689 176212     [      main] INFO      ome.formats.importer.cli.ErrorHandler - /Users/jburel/Documents/sample_Images/test_images_broken/volocity/3 Colour.acff
2015-01-21 21:29:39,624 186147     [      main] INFO      ome.formats.importer.cli.ErrorHandler - Sent files and log file.

**Comment by jburel** [comment]
Restarted Travis

**Comment by mtbc** [comment]
Needs another kick.

**Comment by sbesson** [comment]
```
./components/tools/OmeroPy/src/omero/plugins/import.py:116:80: E501 line too long (97 > 79 characters)
./components/tools/OmeroPy/src/omero/plugins/import.py:119:80: E501 line too long (80 > 79 characters)
./components/tools/OmeroPy/src/omero/plugins/import.py:122:80: E501 line too long (85 > 79 characters)
```

**Comment by sbesson** [comment]
Can you cherry-pick https://github.com/sbesson/openmicroscopy/commit/37b8efcdceb7bd51e3f22a71670acb996fc92228 instead of e350237 as the former should be flake8 compliant?

**Comment by jburel** [comment]
@sbesson: will do when I am done with imageJ build

**Comment by pwalczysko** [comment]
The problem with the report about the submission of the log file missing https://github.com/openmicroscopy/openmicroscopy/pull/3289#issuecomment-69324593  is resolved. Now the output of the console reads

```
2015-01-23 15:45:55,388 64962      [      main] INFO      ome.formats.importer.cli.ErrorHandler - Sent files and log file.
```
Also the log file and the imported file were found at the ``ome-web-s....ing`` server as expected.
All seems fine here.

**Comment by jburel** [comment]
Merging

**Comment by jburel** [comment]
--no-rebase

**Pull request merged**
