### PR TITLE
Web requirements

### PR DESCRIPTION
**Pull request by sbesson**
See https://trello.com/c/orCdAIXU/90-requirements-txt-issues

- renames `requirements_python` as `requirements-py26`
- move Web requirements under `share/web`
- include Web requirements in OMERO.py zip

### CODE REVIEW

**Comment by manics** [comment]
This could get exponentially complex...

**Comment by sbesson** [comment]
Re the Trello card comment, I realized putting everything under a single `requirements.txt` will not work for some of the dependencies (`numpy/scipy` since one requires the other to `pip install`) or there is extra logic to install others (`matplotlib`).
Re complexity, what is your alternate suggestion? No requirements? everything driven via Sphinx doc? One requirement where we encapsulate as much as possible.

**Comment by aleksandra-tarkowska** [comment]
to be added to https://github.com/openmicroscopy/ome-documentation/pull/1305

**Comment by manics** [comment]
> Re complexity, what is your alternate suggestion? No requirements? everything driven via Sphinx doc? One requirement for the recommended platform?

I'm inclined to go for the last, but with good explanations and commented out alternatives for other configurations. That way people can easily edit the requirements files if they want.

**Comment by aleksandra-tarkowska** [comment]
I am fine with these changes. Although I am curies how to distinguish gunicorn installation if you deploy on Apache.

**Comment by joshmoore** [comment]
> I'm inclined to go for the last, but with good explanations and commented out alternatives for other configurations

So that means rather than:

```
$ find -f share/web
share/web
share/web/requirements-py26.txt
share/web/requirements.txt
```

something like:

```
$ find share.new -type f
share.new/web/apache-requirements-py26.txt
share.new/web/apache-requirements.txt
share.new/web/nginx-requirements-py26.txt
share.new/web/nginx-requirements.txt
```

?

**Comment by aleksandra-tarkowska** [comment]
Apache:
```
Django==1.6.11 or Django>=1.8,<1.9
mod_wsgi
```
Nginx:
```
Django==1.6.11 or Django>=1.8,<1.9
gunicorn
```

**Comment by manics** [comment]
How about this:

requirementspy-py27-nginx.txt
```
# This is a work in progress, filenames may change in the next version
# This file is meant to be consumed by pip:
#     pip install -r requirements-py27.txt
Django>=1.8,<1.9
gunicorn
```

requirementspy-py26-nginx.txt
```
# ...
Django==1.6.11
gunicorn
```

requirementspy-py27-apache.txt
```
# ...
Django>=1.8,<1.9
```

requirementspy-py26-apache.txt
```
# ...
Django==1.6.11
```

**Comment by sbesson** [comment]
Works for me. I can have a go at implementing this. Thoughts @aleksandra-tarkowska ?

**Comment by aleksandra-tarkowska** [comment]
This all looks great, I will add py27 to the appropriate doc sections

**Comment by aleksandra-tarkowska** [comment]
requirements**py-py**2... -> requirements-py...

**Comment by sbesson** [comment]
Tested the artifacts of https://ci.openmicroscopy.org/view/DEV/job/OMERO-DEV-merge-build/144/ICE=3.5,jdk=8_LATEST,label=octopus/. The 4 requirements files should be included under `share/web` for both the server and the python package.

**Comment by joshmoore** [comment]
Barring the possibly debatable "1.6.11" fixed version for Django this looks good. Merging to allow the other 5.2.0 PRs to continue.

**Pull request merged**
