### PR TITLE
Gatewaytest chgrp

### PR DESCRIPTION
**Pull request by will-moore**
# What this PR does

Several tests in ```gatewaytest/test_chgrp``` are failing on merge-ci but passing locally, E.g.
https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/189/testReport/junit/OmeroPy.test.integration.gatewaytest/test_chgrp/testImageChgrp/

This may be due to re-use of users and images in these tests. E.g. ```loginAsAuthor()```.
This PR instead uses newly created user and groups and new images.

### CODE REVIEW

**Comment by joshmoore** [comment]
```
./components/tools/OmeroPy/test/integration/gatewaytest/test_chgrp.py:102:80: E501 line too long (82 > 79 characters)
./components/tools/OmeroPy/test/integration/gatewaytest/test_chgrp.py:190:80: E501 line too long (80 > 79 characters)
./components/tools/OmeroPy/test/integration/gatewaytest/test_chgrp.py:191:80: E501 line too long (81 > 79 characters)
./components/tools/OmeroPy/test/integration/gatewaytest/test_chgrp.py:243:9: F841 local variable 'ctx' is assigned to but never used
./components/tools/OmeroPy/test/integration/gatewaytest/test_chgrp.py:295:17: E128 continuation line under-indented for visual indent
./components/tools/OmeroPy/test/integration/gatewaytest/test_chgrp.py:304:80: E501 line too long (82 > 79 characters)
```

**Comment by will-moore** [comment]
That last commit worked and fixed the test: https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/192/testReport/junit/OmeroPy.test.integration.gatewaytest.test_chgrp/TestChgrp/testImageChgrp/ but the other changes didn't.
Need to look at why ```conn.chgrpObjects()``` is not working...

**Comment by jburel** [comment]
excluding this PR for now

**Comment by will-moore** [comment]
As discussed with @jburel - I'll cherry-pick https://github.com/ome/openmicroscopy/pull/6113/commits/66400f6d9a7d89c74dca48bdbef54d0cbcc9a735 to new PR and close this one - JM to use branch in new PR.

**Pull request closed without merging**
