### PR TITLE
Insight build

### PR DESCRIPTION
**Pull request by jburel**
* Clean-up the ivy.xml files
 * remove usage of processing

 2 remaining ref not on maven repo
 * jhotdraw
 * tablelayout (there is an older version on maven-repo, not the one currently used.

To test:
 * Open the various clients and make sure it sill works.

--no-rebase

### CODE REVIEW

**Comment by dominikl** [comment]
Insight and Importer are still working OSX and Linux, but the Windows build gave me an error (see screenshot). It says an apache commons class is missing. Can this be related to #3485 (but actually I've checked the omero-ij plugin on Windows back then).
screen shot 2015-02-23 at 10 18 52

**Comment by dominikl** [comment]
It is definitely related to the breaking build, because current merge build works fine.
Differences are:
- OMERO.insight.exe and OMERO.insight_64.exe of the merge build are recognized as Application, the files from breaking build a recognized as executable zip file. If I click on these, I have the option to extract or run. If I select run, I get
```
java.lang.ClassNotFoundException: org.openmicroscopy.shoola.Main
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at com.exe4j.runtime.LauncherEngine.launch(Unknown Source)
	at com.exe4j.runtime.WinLauncher.main(Unknown Source)
```
- Directly running omero.insight.jar works for merge build, but with breaking build I get above mentioned error message (screenshot previous comment).

**Comment by dominikl** [comment]
Maybe Windows 8 specific issue? Don't have a Windows 7 at hand for testing.

**Comment by jburel** [comment]
@dominikl: will check windows7

**Comment by jburel** [comment]
@dominikl: no problem on window7. It works fine.

**Comment by dominikl** [comment]
Looks like it was an issue with Parallels Desktop. After installing the latest updates from Parallels and extracting the breaking build zip file again, it also works with Windows 8. Sorry for the hassle.

**Comment by jburel** [comment]
Removing Label so it is tomorrow in the merged build

**Comment by jburel** [comment]
@dominikl: Do you think the issue with Webstart during 5.0.7 release could be related to the same parallels problem?

**Comment by dominikl** [comment]
@jburel That's a good point. I'll check Webstart again on Windows 8.

**Comment by dominikl** [comment]
No, unfortunately Windows 8 webstart issue still exists. I might try again later in a VirtualBox Windows 8.

**Comment by jburel** [comment]
@aleksandra-tarkowska: removed ref to nanoxml for webstart

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#802](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/802/). See the [console output](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/802/consoleText) for more details.
Possible conflicts:
  - PR #3434 aleksandra-tarkowska 'Email properties'
    - components/tools/OmeroWeb/omeroweb/settings.py
  - Upstream changes
    - components/tools/OmeroWeb/omeroweb/settings.py

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#803](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/803/). See the [console output](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/803/consoleText) for more details.
Possible conflicts:
  - PR #3434 aleksandra-tarkowska 'Email properties'
    - components/tools/OmeroWeb/omeroweb/settings.py
  - Upstream changes
    - components/tools/OmeroWeb/omeroweb/settings.py

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#804](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/804/). See the [console output](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/804/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - components/tools/OmeroWeb/omeroweb/settings.py

**Comment by aleksandra-tarkowska** [comment]
```Created session 3d45...098 (user-1@t...:4064). Idle timeout: 10.0 min. Current group: p...1```
Windows XP: Logged in successfully using just session key as username.
Mac 10.8: Logged in successfully using just session key as username.

Just minor comment, If you past wrong session key it shows error message twice
omero insightscreensnapz001

**Comment by dominikl** [comment]
Checked webstart, works on OSX and Linux.

**Comment by pwalczysko** [comment]
@dominikl @jburel : Well, I did check the webstart on Windows on trout merge, but because it is unsigned, I got just to the dialog App Blocked by Java Security. @dominikl : how did you do it on OSX and Linux ?

**Comment by pwalczysko** [comment]
Aha, sorry, @aleksandra-tarkowska tested on windows.

**Comment by aleksandra-tarkowska** [comment]
@pwalczysko you have to add domain to your Java security prefs

**Comment by jburel** [comment]
@aleksandra-tarkowska: the window popping up twice might be related to gh-3506 but I have not been able to reproduce it.
Not related to the changes made in this PR.

**Comment by jburel** [comment]
--no-rebase

**Pull request merged**
