### PR TITLE
Ice: Use artifacts from artifactory and add support for Ice 3.6

### PR DESCRIPTION
**Pull request by rleigh-dundee**
- Use Ice jars from OME artifactory
- Delete jars and ivy files from lib/repository
- Add support for Ice 3.6 (also using jars from OME artifactory)

--------

Testing:

- Ice 3.4 and 3.5 jobs should remain green
- Ice 3.6 may be tested with the new homebrew ice formula on MacOS X.  Pushing out the Ice 3.6.0 RPMs onto the CentOS nodes is pending, then we can update the jobs to build and Ice 3.6 variant.

### CODE REVIEW

**Comment by rleigh-dundee** [comment]
@joshmoore Looks like there's an Ice 3.4 incompatibility here: https://travis-ci.org/rleigh-dundee/openmicroscopy/jobs/70410236#L9893  Do you think there's a simple way to work around this?

**Comment by joshmoore** [comment]
Specifically:
```
[nomemoryjava] /home/travis/build/rleigh-dundee/openmicroscopy/components/blitz/test/ome/services/blitz/test/mock/MockFixture.java:398: error: cannot find symbol
[nomemoryjava]         public void refreshSession_async(Glacier2.AMD_Router_refreshSession arg0, Ice.Current arg1)
[nomemoryjava]            
```
Seems odd that I would have added this for 3.6b if it wasn't working. If this class doesn't exist, then we might be forced to compile this into icemocks (or similar).

**Comment by sbesson** [comment]
Discussed earlier with @joshmoore @rleigh-dundee @manics, a workaround for this will be to try and repackage the icemock 3.4 JAR to include the missing class. If this works, we can publish this new icemock JAR to artifactory and remove the `omero-shares` and omero-icemock` JARs from `lib/repository` as part of this PR.

**Comment by rleigh-dundee** [comment]
@joshmoore @sbesson The ice34 mock class is working, so I've pushed it here and it's now green, so should be ready to test and update the merge build job to build an ice36 variant.

**Comment by sbesson** [comment]
See https://ci.openmicroscopy.org/OMERO-5.1-merge-build/ICE=3.5,jdk=8_LATEST,label=trout/559/console

```
03:56:58 /opt/hudson/workspace/OMERO-5.1-merge-build/src/components/blitz/test/ome/services/blitz/test/mock/MockFixture.java:398: error: cannot find symbol
03:56:58         public void refreshSession_async(Glacier2.AMD_Router_refreshSession arg0, Ice.Current arg1)
03:56:58                     
```

Excluding for today

**Comment by rleigh-dundee** [comment]
The last two commits update the omero-icemock jars for ice 3.4, 3.5 and 3.6 to abstract instantiation and setup of IAdminPrxHelper which has a different setup method in Ice 3.6, and to also add a mock AMD_Router_refreshSession class (missing in Ice 3.4 and 3.5).  It also updates the utest Ref.java to adjust to the Ice 3.6 methods and constructor arguments.

Tested to work by hand with all three Ice versions.

**Comment by rleigh-dundee** [comment]
https://ci.openmicroscopy.org/job/OMERO-5.1-breaking-build/ is green.  Some odd python error on marlin: https://ci.openmicroscopy.org/job/OMERO-5.1-breaking-cpp/label=marlin/281/console which looks unrelated.

**Comment by rleigh-dundee** [comment]
https://ci.openmicroscopy.org/job/OMERO-5.1-breaking-cpp/ is green, as is https://ci.openmicroscopy.org/job/OMERO-5.1-breaking-build/

**Comment by rleigh-dundee** [comment]
@joshmoore It certainly looks like the two test failures are to do with the `omero.grid.AMI_Tables_getTable` replacement, which is currently your replacement async callback.  Any thoughts on what's wrong here?

**Comment by sbesson** [comment]
Given the state of https://ci.openmicroscopy.org/view/Breaking/job/OMERO-5.1-breaking-trigger/427/ (with jdk7u85), removing breaking label.

**Comment by joshmoore** [comment]
Merge build results look promising today, but I've not yet managed to actually *use* an Ice 3.6 build locally. Despite the fact that this was going to be marked "experimental" in the docs (https://github.com/openmicroscopy/ome-documentation/pull/1231), talking to @sbesson and @jburel, it seems confusing for users to be able to *build* Ice 3.6 but not *use* it. Anyone who wants something that bleeding edge can use the merge builds.

Adding `ON_HOLD` to get 5.1.3 rc1 built.

**Comment by rleigh-dundee** [comment]
Note failure to log in on eel (to 3.5 server):

Does this ring any bells?  Are we missing something that changed for ice35 over the last few weeks?

```
2015-08-03 15:01:28,640 INFO  [o.o.shoola.env.rnd.PixelsServicesFactory] (nitializer) Heap memory usage: max 954728448 
2015-08-03 15:01:28,646 INFO  [         o.o.shoola.env.init.TaskBarInit] (nitializer) Loaded L&F: com.apple.laf.AquaLookAndFeel 
2015-08-03 15:01:31,366 DEBUG [   o.o.s.env.data.login.LoginServiceImpl] (nitializer) Failed to log onto OMERO.
Reason: Cannot log in. User credentials not valid.

Ice.UnexpectedObjectException
    reason = "expected element of type `::omero::RBool' but received '::omero::RString"
    type = "::omero::RString"
    expectedType = "::omero::RBool"
	at IceInternal.Ex.throwUOE(Ex.java:28)
	at omero.model.Experimenter$Patcher.patch(Experimenter.java:1471)
	at IceInternal.BasicStream$EncapsDecoder.unmarshal(BasicStream.java:3119)
	at IceInternal.BasicStream$EncapsDecoder10.readInstance(BasicStream.java:3481)
	at IceInternal.BasicStream$EncapsDecoder10.readPendingObjects(BasicStream.java:3408)
	at IceInternal.BasicStream.readPendingObjects(BasicStream.java:560)
	at omero.api.IAdminPrxHelper.end_lookupExperimenter(IAdminPrxHelper.java:5625)
	at omero.api.IAdminPrxHelper.lookupExperimenter(IAdminPrxHelper.java:5490)
	at omero.api.IAdminPrxHelper.lookupExperimenter(IAdminPrxHelper.java:5477)
	at org.openmicroscopy.shoola.env.data.OMEROGateway.login(OMEROGateway.java:1914)
	at org.openmicroscopy.shoola.env.data.DataServicesFactory.connect(DataServicesFactory.java:583)
	at org.openmicroscopy.shoola.env.data.login.LoginServiceImpl.attempt(LoginServiceImpl.java:134)
	at org.openmicroscopy.shoola.env.data.login.LoginServiceImpl.login(LoginServiceImpl.java:261)
	at org.openmicroscopy.shoola.env.data.login.LoginManager.login(LoginManager.java:98)
	at org.openmicroscopy.shoola.env.init.SplashScreenInit.onEnd(SplashScreenInit.java:180)
	at org.openmicroscopy.shoola.env.init.Initializer.notifyEnd(Initializer.java:189)
	at org.openmicroscopy.shoola.env.Container.runStartupProcedure(Container.java:125)
	at org.openmicroscopy.shoola.env.Container.access$000(Container.java:74)
	at org.openmicroscopy.shoola.env.Container$1.run(Container.java:170)
	at java.lang.Thread.run(Thread.java:745)

OMERO address: eel.openmicroscopy.org
User Name: user-5 -- Password: ***
org.openmicroscopy.shoola.env.data.DSOutOfServiceException: Cannot log in. User credentials not valid.

Ice.UnexpectedObjectException
    reason = "expected element of type `::omero::RBool' but received '::omero::RString"
    type = "::omero::RString"
    expectedType = "::omero::RBool"
	at IceInternal.Ex.throwUOE(Ex.java:28)
	at omero.model.Experimenter$Patcher.patch(Experimenter.java:1471)
	at IceInternal.BasicStream$EncapsDecoder.unmarshal(BasicStream.java:3119)
	at IceInternal.BasicStream$EncapsDecoder10.readInstance(BasicStream.java:3481)
	at IceInternal.BasicStream$EncapsDecoder10.readPendingObjects(BasicStream.java:3408)
	at IceInternal.BasicStream.readPendingObjects(BasicStream.java:560)
	at omero.api.IAdminPrxHelper.end_lookupExperimenter(IAdminPrxHelper.java:5625)
	at omero.api.IAdminPrxHelper.lookupExperimenter(IAdminPrxHelper.java:5490)
	at omero.api.IAdminPrxHelper.lookupExperimenter(IAdminPrxHelper.java:5477)
	at org.openmicroscopy.shoola.env.data.OMEROGateway.login(OMEROGateway.java:1914)
	at org.openmicroscopy.shoola.env.data.DataServicesFactory.connect(DataServicesFactory.java:583)
	at org.openmicroscopy.shoola.env.data.login.LoginServiceImpl.attempt(LoginServiceImpl.java:134)
	at org.openmicroscopy.shoola.env.data.login.LoginServiceImpl.login(LoginServiceImpl.java:261)
	at org.openmicroscopy.shoola.env.data.login.LoginManager.login(LoginManager.java:98)
	at org.openmicroscopy.shoola.env.init.SplashScreenInit.onEnd(SplashScreenInit.java:180)
	at org.openmicroscopy.shoola.env.init.Initializer.notifyEnd(Initializer.java:189)
	at org.openmicroscopy.shoola.env.Container.runStartupProcedure(Container.java:125)
	at org.openmicroscopy.shoola.env.Container.access$000(Container.java:74)
	at org.openmicroscopy.shoola.env.Container$1.run(Container.java:170)
	at java.lang.Thread.run(Thread.java:745)

	at org.openmicroscopy.shoola.env.data.OMEROGateway.login(OMEROGateway.java:1957)
	at org.openmicroscopy.shoola.env.data.DataServicesFactory.connect(DataServicesFactory.java:583)
	at org.openmicroscopy.shoola.env.data.login.LoginServiceImpl.attempt(LoginServiceImpl.java:134)
	at org.openmicroscopy.shoola.env.data.login.LoginServiceImpl.login(LoginServiceImpl.java:261)
	at org.openmicroscopy.shoola.env.data.login.LoginManager.login(LoginManager.java:98)
	at org.openmicroscopy.shoola.env.init.SplashScreenInit.onEnd(SplashScreenInit.java:180)
	at org.openmicroscopy.shoola.env.init.Initializer.notifyEnd(Initializer.java:189)
	at org.openmicroscopy.shoola.env.Container.runStartupProcedure(Container.java:125)
	at org.openmicroscopy.shoola.env.Container.access$000(Container.java:74)
	at org.openmicroscopy.shoola.env.Container$1.run(Container.java:170)
	at java.lang.Thread.run(Thread.java:745)
Caused by: Ice.UnexpectedObjectException
    reason = "expected element of type `::omero::RBool' but received '::omero::RString"
    type = "::omero::RString"
    expectedType = "::omero::RBool"
	at IceInternal.Ex.throwUOE(Ex.java:28)
	at omero.model.Experimenter$Patcher.patch(Experimenter.java:1471)
	at IceInternal.BasicStream$EncapsDecoder.unmarshal(BasicStream.java:3119)
	at IceInternal.BasicStream$EncapsDecoder10.readInstance(BasicStream.java:3481)
	at IceInternal.BasicStream$EncapsDecoder10.readPendingObjects(BasicStream.java:3408)
	at IceInternal.BasicStream.readPendingObjects(BasicStream.java:560)
	at omero.api.IAdminPrxHelper.end_lookupExperimenter(IAdminPrxHelper.java:5625)
	at omero.api.IAdminPrxHelper.lookupExperimenter(IAdminPrxHelper.java:5490)
	at omero.api.IAdminPrxHelper.lookupExperimenter(IAdminPrxHelper.java:5477)
	at org.openmicroscopy.shoola.env.data.OMEROGateway.login(OMEROGateway.java:1914)
	... 10 more
Failed to log onto OMERO.
Reason: Cannot log in. User credentials not valid.

Ice.UnexpectedObjectException
    reason = "expected element of type `::omero::RBool' but received '::omero::RString"
    type = "::omero::RString"
    expectedType = "::omero::RBool"
	at IceInternal.Ex.throwUOE(Ex.java:28)
	at omero.model.Experimenter$Patcher.patch(Experimenter.java:1471)
	at IceInternal.BasicStream$EncapsDecoder.unmarshal(BasicStream.java:3119)
	at IceInternal.BasicStream$EncapsDecoder10.readInstance(BasicStream.java:3481)
	at IceInternal.BasicStream$EncapsDecoder10.readPendingObjects(BasicStream.java:3408)
	at IceInternal.BasicStream.readPendingObjects(BasicStream.java:560)
	at omero.api.IAdminPrxHelper.end_lookupExperimenter(IAdminPrxHelper.java:5625)
	at omero.api.IAdminPrxHelper.lookupExperimenter(IAdminPrxHelper.java:5490)
	at omero.api.IAdminPrxHelper.lookupExperimenter(IAdminPrxHelper.java:5477)
	at org.openmicroscopy.shoola.env.data.OMEROGateway.login(OMEROGateway.java:1914)
	at org.openmicroscopy.shoola.env.data.DataServicesFactory.connect(DataServicesFactory.java:583)
	at org.openmicroscopy.shoola.env.data.login.LoginServiceImpl.attempt(LoginServiceImpl.java:134)
	at org.openmicroscopy.shoola.env.data.login.LoginServiceImpl.login(LoginServiceImpl.java:261)
	at org.openmicroscopy.shoola.env.data.login.LoginManager.login(LoginManager.java:98)
	at org.openmicroscopy.shoola.env.init.SplashScreenInit.onEnd(SplashScreenInit.java:180)
	at org.openmicroscopy.shoola.env.init.Initializer.notifyEnd(Initializer.java:189)
	at org.openmicroscopy.shoola.env.Container.runStartupProcedure(Container.java:125)
	at org.openmicroscopy.shoola.env.Container.access$000(Container.java:74)
	at org.openmicroscopy.shoola.env.Container$1.run(Container.java:170)
	at java.lang.Thread.run(Thread.java:745)

OMERO address: eel.openmicroscopy.org
User Name: user-5 -- Password: ***
org.openmicroscopy.shoola.env.data.DSOutOfServiceException: Cannot log in. User credentials not valid.

Ice.UnexpectedObjectException
    reason = "expected element of type `::omero::RBool' but received '::omero::RString"
    type = "::omero::RString"
    expectedType = "::omero::RBool"
	at IceInternal.Ex.throwUOE(Ex.java:28)
	at omero.model.Experimenter$Patcher.patch(Experimenter.java:1471)
	at IceInternal.BasicStream$EncapsDecoder.unmarshal(BasicStream.java:3119)
	at IceInternal.BasicStream$EncapsDecoder10.readInstance(BasicStream.java:3481)
	at IceInternal.BasicStream$EncapsDecoder10.readPendingObjects(BasicStream.java:3408)
	at IceInternal.BasicStream.readPendingObjects(BasicStream.java:560)
	at omero.api.IAdminPrxHelper.end_lookupExperimenter(IAdminPrxHelper.java:5625)
	at omero.api.IAdminPrxHelper.lookupExperimenter(IAdminPrxHelper.java:5490)
	at omero.api.IAdminPrxHelper.lookupExperimenter(IAdminPrxHelper.java:5477)
	at org.openmicroscopy.shoola.env.data.OMEROGateway.login(OMEROGateway.java:1914)
	at org.openmicroscopy.shoola.env.data.DataServicesFactory.connect(DataServicesFactory.java:583)
	at org.openmicroscopy.shoola.env.data.login.LoginServiceImpl.attempt(LoginServiceImpl.java:134)
	at org.openmicroscopy.shoola.env.data.login.LoginServiceImpl.login(LoginServiceImpl.java:261)
	at org.openmicroscopy.shoola.env.data.login.LoginManager.login(LoginManager.java:98)
	at org.openmicroscopy.shoola.env.init.SplashScreenInit.onEnd(SplashScreenInit.java:180)
	at org.openmicroscopy.shoola.env.init.Initializer.notifyEnd(Initializer.java:189)
	at org.openmicroscopy.shoola.env.Container.runStartupProcedure(Container.java:125)
	at org.openmicroscopy.shoola.env.Container.access$000(Container.java:74)
	at org.openmicroscopy.shoola.env.Container$1.run(Container.java:170)
	at java.lang.Thread.run(Thread.java:745)

	at org.openmicroscopy.shoola.env.data.OMEROGateway.login(OMEROGateway.java:1957)
	at org.openmicroscopy.shoola.env.data.DataServicesFactory.connect(DataServicesFactory.java:583)
	at org.openmicroscopy.shoola.env.data.login.LoginServiceImpl.attempt(LoginServiceImpl.java:134)
	at org.openmicroscopy.shoola.env.data.login.LoginServiceImpl.login(LoginServiceImpl.java:261)
	at org.openmicroscopy.shoola.env.data.login.LoginManager.login(LoginManager.java:98)
	at org.openmicroscopy.shoola.env.init.SplashScreenInit.onEnd(SplashScreenInit.java:180)
	at org.openmicroscopy.shoola.env.init.Initializer.notifyEnd(Initializer.java:189)
	at org.openmicroscopy.shoola.env.Container.runStartupProcedure(Container.java:125)
	at org.openmicroscopy.shoola.env.Container.access$000(Container.java:74)
	at org.openmicroscopy.shoola.env.Container$1.run(Container.java:170)
	at java.lang.Thread.run(Thread.java:745)
Caused by: Ice.UnexpectedObjectException
    reason = "expected element of type `::omero::RBool' but received '::omero::RString"
    type = "::omero::RString"
    expectedType = "::omero::RBool"
	at IceInternal.Ex.throwUOE(Ex.java:28)
	at omero.model.Experimenter$Patcher.patch(Experimenter.java:1471)
	at IceInternal.BasicStream$EncapsDecoder.unmarshal(BasicStream.java:3119)
	at IceInternal.BasicStream$EncapsDecoder10.readInstance(BasicStream.java:3481)
	at IceInternal.BasicStream$EncapsDecoder10.readPendingObjects(BasicStream.java:3408)
	at IceInternal.BasicStream.readPendingObjects(BasicStream.java:560)
	at omero.api.IAdminPrxHelper.end_lookupExperimenter(IAdminPrxHelper.java:5625)
	at omero.api.IAdminPrxHelper.lookupExperimenter(IAdminPrxHelper.java:5490)
	at omero.api.IAdminPrxHelper.lookupExperimenter(IAdminPrxHelper.java:5477)
	at org.openmicroscopy.shoola.env.data.OMEROGateway.login(OMEROGateway.java:1914)
	... 10 more
Exception in thread "Initializer"
 ```

**Comment by jburel** [comment]
build on mac 10.10, Java 8 ice 3.6
When restarting the server I have
```
icegridadmin: server is using a different Slice definition of `::IceGrid::Admin'
icegridadmin: server is using a different Slice definition of `::IceGrid::Node'
icegridadmin: server is using a different Slice definition of `::IceGrid::Registry'
icegridadmin: server is using a different Slice definition of `::IceGrid::ReplicaGroupDescriptor'
icegridadmin: server is using unknown Slice type `::IceLocatorDiscovery::Lookup'
icegridadmin: server is using unknown Slice type `::IceLocatorDiscovery::LookupReply'
```

**Comment by jburel** [comment]
Found the following on zeroc website:
https://doc.zeroc.com/display/Ice36/Upgrading+your+Application+from+Ice+3.5#UpgradingyourApplicationfromIce3.5-Javamappingchanges

This might explain the mapping issue noticed while logging in.

**Comment by jburel** [comment]
@rleigh-dundee: 
I have removed ice 35 from my machine. I previously only did a ```brew unlink```
This time I do not have the message with ```icegridadmin``` but it is still not possible to connect
In that case the connection is refused

so summary:
 * ice36 client against eel (ice35) mapping issue string/bool
 * ice 36 client - ice36 server. connection refused error.  java version "1.8.0_31" 
```

Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
	at IceInternal.Network.doFinishConnect(Network.java:437)
	at IceInternal.StreamSocket.connect(StreamSocket.java:96)
	at IceSSL.TransceiverI.initialize(TransceiverI.java:27)
	at Ice.ConnectionI.initialize(ConnectionI.java:1913)
	at Ice.ConnectionI.message(ConnectionI.java:940)
	at IceInternal.ThreadPool.run(ThreadPool.java:395)
```

**Comment by jburel** [comment]
Excluding this PR for now so we can concentrate on Java 1.7

The code compiles, the server will start. But it is not possible to connect to server.
More work required

**Comment by jburel** [comment]
Closing the PR, not considered for 5.2
@sbesson will cherry-pick his commit to use the artifactory
see https://trello.com/c/2qw5o7PL/27-clean-lib-repository

**Pull request closed without merging**
