### PR TITLE
Script ui tabbing 12080

### PR DESCRIPTION
**Pull request by will-moore**
This is #3881 Closed and re-opened here because of an accidental force push of a wrong branch.

----

Fixes https://trac.openmicroscopy.org/ome/ticket/12080

To test:
 - Open a script from the scripts menu
 - On opening, the "focus" should be on the first input.
 - Tab key should move you through all the fields, going to "Run Script" *before* "Cancel".

### CODE REVIEW

**Comment by will-moore** [comment]
@joshmoore Given the last comment at https://github.com/openmicroscopy/openmicroscopy/pull/3881 are you happy to merge this? It actually works OK for me on Chrome on Mac.

**Comment by joshmoore** [comment]
Very difficult to know now if this matches. If @gusferguson feels comfortable with the state of today's build matching what he tested in https://github.com/openmicroscopy/openmicroscopy/pull/3881#issuecomment-114443924, then sure.

**Comment by gusferguson** [comment]
@will-moore @joshmoore - behaves same as yesterdays build. I see Mac Chrome is tabbing to "Run Script" it just doesn't highlight it.

Good to merge.

**Comment by joshmoore** [comment]
thanks, @gusferguson (oh, and @will-moore, too :smile:)

**Pull request merged**
