### PR TITLE
ij-omero round trip dev 5 1

### PR DESCRIPTION
**Pull request by jburel**
rebased-from gh-4001

To test this PR

test 1:
 * Open a mif from local file system
 * Do not select all series.
 * Save the images to OMERO
 * After saving, Draw a roi on the image
 * Click Save ROIs.
 * Check that no dialog indicating "Do you want to import images..." pops up
 * Check that the rois are saved.

test 2:
 * Repeat the same steps with a tiff file

test 3:
 * repeat the same steps with a single file e.g. dv

-----
extra tests:

test 4:
* Open a mif from local file system
 * Do not select all series e.g. 2 series
 * Save the images to OMERO but this time Select "Images from all windows"
 * Check that the image is only imported once.

test 5:
 * Open a mif from local file system
 * Do not select all series e.g. 2 series
 * Draw some rois
 * Select the "save rois" options (not save images options).Select "Images from all windows"
 * Check that the dialog asking to import the images pops up
 * Check that the image is only imported once.

### CODE REVIEW

**Comment by sbesson** [comment]
@jburel: was this opened against the wrong branch?

**Comment by jburel** [comment]
yep

**Comment by will-moore** [comment]
@jburel @sbesson Not sure what this failed build means? https://ci.openmicroscopy.org/view/Failing/job/OMERO-unrebased-prs/773/warnings8Result/

**Comment by mtbc** [comment]
@will-moore: It's seen a rebased-to without a matching rebased-from: @jburel will add the `--` prefix in this PR description and then all will be well.

**Comment by jburel** [comment]
@will-moore: ignore. This PR was closed and had the wrong info.
Sorted

**Pull request closed without merging**
