### PR TITLE
ij-omero round trip

### PR DESCRIPTION
**Pull request by jburel**
see https://trello.com/c/shcz0N2C/22-imagej-omero-round-trip

To test this PR

test 1:
 * Open a mif from local file system
 * Do not select all series.
 * Save the images to OMERO
 * After saving, Draw a roi on the image
 * Click Save ROIs.
 * Check that no dialog indicating "Do you want to import images..." pops up
 * Check that the rois are saved.

test 2:
 * Repeat the same steps with a tiff file

test 3:
 * repeat the same steps with a single file e.g. dv

-----
extra tests:

test 4:
* Open a mif from local file system
 * Do not select all series e.g. 2 series
 * Save the images to OMERO but this time Select "Images from all windows"
 * Check that the image is only imported once.

test 5:
 * Open a mif from local file system
 * Do not select all series e.g. 2 series
 * Draw some rois
 * Select the "save rois" options (not save images options).Select "Images from all windows"
 * Check that the dialog asking to import the images pops up
 * Check that the image is only imported once.

### CODE REVIEW

**Comment by bramalingam** [comment]
Some Bug's which I noticed while testing the MIF-Overlay PR:
--IJ.log triggered somewhere post import of ROI’s
--Cannot open any image in “view mode” (in insight viewer). Shows dialog: Loading Render data: "The image could not be opened.The image is not a valied image".

Should Stand good for test2 and test3 in this PR:
--Reimporting an image from disk is allowed, whereas saving ROI’s check's if the Image is already present within OMERO.

**Comment by bramalingam** [comment]
test1:
Everything except the last step passes. i.e: "Check that the rois are saved" fails

**Comment by jburel** [comment]
@bramalingam 
You will not be able to view the roi using the internal viewer since we have disable the MT.
You need to the check the roi count and use the standalone client to view.

**Comment by jburel** [comment]
@bramalingam:
I can view the image w/o problem
 * The newly imported image from ImageJ
 * and images already imported (not via imageJ)
Which users?

**Comment by bramalingam** [comment]
@Jburel: I was using the ROICount to validate the presence or absence of ROI's within the Plugin. And I did not see any change in the numbers there.

**Comment by bramalingam** [comment]
Am able to open the images as well now post a restart of the plugin..! Very strange..!

**Comment by pwalczysko** [comment]
@jburel : Can confirm the bug in test1 reported by @bramalingam . I think what Balaji means is that when you open more than 1 image out of the MIF (but not ALL), and then draw regions on more than one of these opened images and Save ROI(s) to OMERO, the regions are not distributed on the images as drawn. 

I am having on images 2, 3, and 4 one ROI each. After Save ROIs to OMERO I have on image 2 nothing (not expected), on image 3 one ROI (expected) and on image 4 two ROIs (one ROI more than expected). This is similar to the bug reported on https://github.com/openmicroscopy/openmicroscopy/pull/4000#issuecomment-126310474, except that in the other PR one of the ROIs seems to be lost, the behaviour here is that the ROI gets relocated on another image.

**Comment by pwalczysko** [comment]
As Balaji indicated, test1 otherwise passes (no popup about reimporting the mif again). The problem is only with the sorting and preserving the ROIs.

**Comment by pwalczysko** [comment]
test2 and test3 passed as expected.

**Comment by jburel** [comment]
to test commits 5ca52d5 and d2cc2fe. Follow test 4 and test 5 in PR description

**Comment by jburel** [comment]
@pwalczysko @bramalingam: The saving of rois problem should now be fixed.
Could you retest it tomorrow and also do test 4 and 5?

**Comment by pwalczysko** [comment]
@jburel I can see failing travis checks here.

**Comment by jburel** [comment]
@pwalczysko: restarted travis. All green now

**Comment by pwalczysko** [comment]
The ROIs mixup in MIF is fixed, all ROIs present on the appropriate images.
test4 passed
test5 passed
All good here.

**Comment by jburel** [comment]
--rebased-to #4003

**Pull request merged**
