### PR TITLE
Import event container

### PR DESCRIPTION
**Pull request by jburel**
In this PR we use the import container to retrieve the domain instead of re-initializing the reader (this was taking take for some files)
To test: Import the broken file from insight and CLI ```test_image_broken/volocity/3 Colour.acff```
 * From CLI: bin/omero import --report  --logs --upload pathToFile
   * check that there is no delay after the error is printed out.
 * From insight
  * after failure. Click Submit. It should have no delay between the click and the submit dialog popping up

Also test a broken plate
 * Available plate from ```sguiq/team/jburel/broken plate from petr```

### CODE REVIEW

**Comment by dominikl** [comment]
Looks reasonable; didn't notice a delay before the submit dialog opens, also with CLI (command exits directly after error has been printed). Just some copyright date header updates missing (ErrorHandler.java, ImportLibrary.java, ImportEvent.java).

**Comment by dominikl** [comment]
I also noticed, that the failed CLI imports weren't uploaded to QA staging. Is this expected?

**Comment by jburel** [comment]
Only plate should not be submitted.

**Comment by dominikl** [comment]
No, the other image file is also not submitted, although the command line output claims so:
```
./omero import --report --logs --upload /Users/dlindner/Testing/TestImages/broken/3\ Colour.acff
...
2015-03-05 11:04:06,518 172589     [      main] INFO         ome.formats.importer.ImportLibrary - Exiting on error
2015-03-05 11:04:06,518 172589     [      main] INFO      ome.formats.importer.cli.ErrorHandler - Sending error report (1)...
2015-03-05 11:04:07,997 174068     [      main] INFO      ome.formats.importer.cli.ErrorHandler - Sending File(s)...
2015-03-05 11:04:08,701 174772     [      main] INFO      ome.formats.importer.cli.ErrorHandler - Sent files and log file.
```
But no file in QA staging. I just downloaded and started the current 5.1 merge build server locally, I didn't do any specific setup. Does the QA URL has to be setup beforehand?

**Comment by joshmoore** [comment]
@dominikl: Yes. :) https://www.openmicroscopy.org/qa2/qa/feedback/10734/

**Comment by dominikl** [comment]
Ah, thanks @joshmoore ... So Insight merge build defaults to QA staging, but the server defaults to QA.

**Comment by dominikl** [comment]
It probably has nothing to do with this PR, but the QA sent from Insight, claims that I use Java 8u31 [QA 9580](https://qa.staging.openmicroscopy.org/qa/feedback/9580/) whereas I actually have Java 8u25.
```
ls29139:openmicroscopy dlindner$ java -version
java version "1.8.0_25"
```
CLI client gets it right (so is the CLI QA report)
```
2015-03-05 11:02:42,109 88180      [      main] INFO       ome.formats.OMEROMetadataStoreClient - Server: 5.1.0
2015-03-05 11:02:42,109 88180      [      main] INFO       ome.formats.OMEROMetadataStoreClient - Client: 5.1.0-m5-191-fb93e2b-ice35-b430
2015-03-05 11:02:42,109 88180      [      main] INFO       ome.formats.OMEROMetadataStoreClient - Java Version: 1.8.0_25
```

**Comment by joshmoore** [comment]
@dominikl / @ximenesuk : what's the status here?

**Comment by jburel** [comment]
@dominikl: The java -version is not related to this PR,

**Comment by dominikl** [comment]
Looks fine to me! Didn't notice any delay before the dialog popped up.

**Comment by ximenesuk** [comment]
Sorry, missed the updates on this. I think the only outstanding issue is the copyright dates if @jburel is happy with the feedback. It would make most sense for J-M to make those changes directly on his branch if they need to be done before merging.

**Comment by joshmoore** [comment]
I'm not worried about the copyright dates (much less than not worried). Thanks all. One heads up that I hadn't though of before: this will equate to a breaking change for anyone who's implemented their own listener. We'll just need to document sensibly. cc: @hflynn (adding to doc upcoming card)

**Comment by jburel** [comment]
--no-rebase

**Pull request merged**
