### PR TITLE
display PhysicalPixelSize value only if set

### PR DESCRIPTION
**Pull request by atarkowska**
# What this PR does

Fixes invalid value displayed when PhysicalPixelSize is not set
https://trello.com/c/vQ6uJKoJ/24-pixel-sizes-in-idr0009-are-all-0

# Testing this PR

1. check images with or without Pixel sizes

### CODE REVIEW

**Comment by atarkowska** [comment]
--rebased-to #5008

**Comment by will-moore** [comment]
Tested #5008 locally - Need to handle images that only have pixel size Z set.
Also, prefer to have shorter text instead of 'not available' with more info in tooltip.

**Comment by will-moore** [comment]
Tested #5008 locally again:

Tooltip on placeholder ```-``` looks good.

screen shot 2017-01-05 at 13 05 07

If only Pixel size Z is set, this is still displayed
screen shot 2017-01-05 at 13 05 29

Good to merge.

**Comment by atarkowska** [comment]
@will-moore thanks for testing

**Comment by atarkowska** [comment]
available on http://10.0.51.135/web/webclient/?show=well-61792

**Comment by joshmoore** [comment]
Thanks all. Leaving gh-5008 open for final comments.

**Pull request merged**
