### PR TITLE
Fixed storing of ROIs from non-hyperstack images from ImageJ

### PR DESCRIPTION
**Pull request by stelfrich**
ROIs aren't imported with their correct positions to OMERO because of the weird hyperstack handling of ImageJ. This PR fixes the issue for images with the following dimensions:
* C=1, Z=1, T=5
* C=3, Z=1, T=5
* C=1, Z=3, T=5
* C=3, Z=1, T=1
* C=1, Z=3, T=1

### CODE REVIEW

**Comment by jburel** [comment]
* Formatting issue: in block
```
if (!image.isHyperStack()) {
...
}
```
(tabs used)

* in reading from overlay
```
Roi[] rois = overlay.toArray();
      
        for (Roi roi : rois) {
       	roi.setImage(image);
}
```
This should be done after the null check i.e. ```overlay == null```

**Comment by jburel** [comment]
@stelfrich: will it possible to give a scenario so we can update our testing scenario (getting long with ImageJ) cc @pwalczysko

**Comment by pwalczysko** [comment]
@stelfrich : I am pasting here a section out of our testing scenario so that you get an idea of what @jburel means and what we need. No need to be absolutely precise, but mainly the ImageJ steps, what images are being opened and how the regions are being saved would be crucial, thanks !

```
Draw a ROI specifically on a z or t plane.

    open a multi-z and multi-t image stored in OMERO in ImageJ using the ImageJ plugin
    draw several ROIs (including an ellipse) in ImageJ on a particular z/t plane(s) and add them to ROI Manager in ImageJ (Note that Overlay in ImageJ does not support t information, but does support the z information.)
    save the ROI using Save ROIs to OMERO
    Check that the ROI in OMERO is associated with the correct z/t plane(s)
....
```

**Comment by stelfrich** [comment]
Thanks @pwalczysko, I was a bit lost ;-)

This might take some time, since I can't really reproduce the issues from scratch. So the reason might as well be on our side and how we treat the data. I have an example, where ROIs are imported to OMERO but the position information is lost. Should I upload the example to OMERO.qa and reference this PR?

**Comment by pwalczysko** [comment]
@stelfrich : Definitely, yes please. Also add any info shedding light on the issue, however incidental. Thanks

**Comment by stelfrich** [comment]
I have uploaded said file to OMERO.qa with ID 11358.

**Comment by pwalczysko** [comment]
QA 11358 received. @stelfrich Thanks

**Comment by pwalczysko** [comment]
Following now the workflow in https://www.openmicroscopy.org/qa2/qa/feedback/11358/

**Comment by pwalczysko** [comment]
After following the workflow in https://www.openmicroscopy.org/qa2/qa/feedback/11358/ I am getting 

```
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at org.openmicroscopy.shoola.env.data.model.FileObject.xmlParser(FileObject.java:141)
	at org.openmicroscopy.shoola.env.data.model.FileObject.isNewImage(FileObject.java:338)
	at org.openmicroscopy.shoola.agents.fsimporter.chooser.FileSelectionTable.allowAddToQueue(FileSelectionTable.java:399)
	at org.openmicroscopy.shoola.agents.fsimporter.chooser.FileSelectionTable.addFiles(FileSelectionTable.java:581)
	at org.openmicroscopy.shoola.agents.fsimporter.chooser.ImportDialog.addImageJFiles(ImportDialog.java:1620)
	at org.openmicroscopy.shoola.agents.fsimporter.chooser.ImportDialog.propertyChange(ImportDialog.java:1683)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at java.awt.Component.firePropertyChange(Component.java:8422)
	at org.openmicroscopy.shoola.agents.fsimporter.chooser.LocationDialog.actionPerformed(LocationDialog.java:950)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2 t 5
```

I have used addition of the ROI to ROI Manager in Fiji. Did you do Overlay in your workflow please ?

**Comment by pwalczysko** [comment]
@stelfrich : Note that I am not having your fix when going through https://github.com/openmicroscopy/openmicroscopy/pull/4045#issuecomment-130740913, just trying to repeat the problem.

**Comment by stelfrich** [comment]
That's true. This is a bug that has been fixed in #4034. Try to follow the workflow with that PR to reproduce the issue.

**Comment by pwalczysko** [comment]
@stelfrich : I was not exact, it was not crash. I will try to get https://github.com/openmicroscopy/openmicroscopy/pull/4034 on board and repeat, but in the meantime I was able to import the image to OMERO and can see 12 ROIs, with no Z T info on them. How did you draw these ROIs ?

**Comment by pwalczysko** [comment]
(will continue tommorrow)

**Comment by jburel** [comment]
@pwalczysko: note that the changes pushed by @stelfrich are not included in todays' build.
We will have to check them tomorrow

**Comment by stelfrich** [comment]
> I was able to import the image to OMERO and can see 12 ROIs, with no Z T info on them.

That's exactly what I get, but it's not really the desired result.

I have, however, managed to come up with a testing scenario:
1. Create new Image (File > New > Image) with 3 slices regardless of size
2. Store image to TIFF and close original
3. Load image from TIFF
4. Add a (rectangular) ROI on each of the slices
5. Import to OMERO via Plugins > OMERO > Save Image(s) to OMERO

The result should be an image with three ROIs with Z positions 1, 2, and 3, respectively. They have however no positional information because `roi.getCPosition()` (ROIReader.java:L211) et al return 0 for this case. This is due to the fact, that CZT for ROIs is only set for hyperstacks but not for regular stacks. For regular stacks, `roi.position` is the crucial property that is never checked in the original implementation:

```
int c = roi.getCPosition();
int z = roi.getZPosition();
int t = roi.getTPosition();
if (c != 0) {
    shape.setC(c-1);
}
if (z != 0) {
    shape.setZ(z-1);
}
if (t != 0) {
    shape.setT(t-1);
}
```

**Comment by jburel** [comment]
@stelfrich: thanks for the tips we will need to review the ROIHandler too now that we have a scenario it should be easier to track that down

**Comment by stelfrich** [comment]
@jburel I have a fix for that too, although it's not thoroughly tested. Should I open a PR?

**Comment by jburel** [comment]
@stelfrich: either open a PR or point me to your branch.

**Comment by stelfrich** [comment]
@jburel Take a look at https://github.com/openmicroscopy/bioformats/pull/1934

**Comment by pwalczysko** [comment]
@stelfrich : Thanks a lot for the scenario. I have tested some workflows with your PR NOT IN to get an overview about the scope of the problem.
1. I can fully repeat the bug as you describe it in your scenario in Fiji and ImageJ. 
2. I can repeat the bug even with a stored image (without creating a new one), using our own ``test_images_good/tiff/QA images/Artificial_xyt_8bit.tif``
3. I can repeat the bug on an multi-t and multi-z ome-tiff when opened via ``File > Open``
4. On the same ome-tiff opened via ``Bio-formats importer`` the bug is not present but
5. On the image delivered by @stelfrich the ``Bio-formats importer`` workflow does not alleviate the bug, it is still present there.

**Comment by jburel** [comment]
closing replaced by https://github.com/openmicroscopy/openmicroscopy/pull/4170

**Pull request closed without merging**
