### PR TITLE
Big image export jpg config

### PR DESCRIPTION
**Pull request by will-moore**
This is the final commit from https://github.com/openmicroscopy/openmicroscopy/pull/4223 that was removed from that PR to make the PR equivalent of the 5.1.4 PR.

This PR adds the configuration of size for download of image as jpg/png/tiff.

To test:
 - Images bigger than 12k * 12k pixels (144000000) should be disabled for Download as Jpg, Png & Tiff.
 - Configure with a different number of pixels. E.g. 3000 x 3000 = 9000000
```
$ bin/omero config set omero.client.download_as.max_size 9000000
$ bin/omero admin restart
```
Now, images larger than this new size should be disabled for download.

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#111](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/111/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/111/consoleText) for more details.
Possible conflicts:
  - PR #4238 snoopycrimecop 'Bump Bio-Formats version to 5.1.5-SNAPSHOT'
    - etc/omero.properties
  - PR #4249 aleksandra-tarkowska 'Roi count limit'
    - etc/omero.properties
  - PR #4255 rleigh-dundee 'Remove Ice 3.4 support'
    - etc/omero.properties
  - Upstream changes
    - etc/omero.properties

**Comment by aleksandra-tarkowska** [comment]
Ahh that was the trick. Sorry @dominikl I wasn't aware that was the plan when you asked me to add the property.

**Comment by dominikl** [comment]
Sorry, now I'm totally confused... So this property will go in, in 5.2 and also in 5.1, but it was excluded from 5.1.4!? And still there is the issue, that OME-TIFF export is enabled for big images in Web but it then fails with the message that, big images can't be exported as OME-TIFF, is that intentional?

**Comment by jburel** [comment]
We are not planning to put in 5.1.x unless there is a strong need for it.
It was removed from 5.1.4 b/c we did not have time to adjust all the components.

**Comment by will-moore** [comment]
@dominikl As soon as conflicting PRs are merged, I will fix merge conflicts.
Then you can use the config settings as a base for similar behaviour in Insight.

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#114](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/114/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/114/consoleText) for more details.
Possible conflicts:
  - PR #4249 aleksandra-tarkowska 'Roi count limit'
    - etc/omero.properties
  - PR #4255 rleigh-dundee 'Remove Ice 3.4 support'
    - etc/omero.properties

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#115](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/115/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/115/consoleText) for more details.
Possible conflicts:
  - PR #4249 aleksandra-tarkowska 'Roi count limit'
    - etc/omero.properties
  - PR #4255 rleigh-dundee 'Remove Ice 3.4 support'
    - etc/omero.properties
  - Upstream changes
    - etc/omero.properties

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#116](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/116/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/116/consoleText) for more details.
Possible conflicts:
  - PR #4249 aleksandra-tarkowska 'Roi count limit'
    - etc/omero.properties
  - PR #4255 rleigh-dundee 'Remove Ice 3.4 support'
    - etc/omero.properties
  - Upstream changes
    - etc/omero.properties

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#117](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/117/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/117/consoleText) for more details.
Possible conflicts:
  - PR #4249 aleksandra-tarkowska 'Roi count limit'
    - etc/omero.properties
  - PR #4255 rleigh-dundee 'Remove Ice 3.4 support'
    - etc/omero.properties
  - Upstream changes
    - etc/omero.properties

**Comment by sbesson** [comment]
Requires https://github.com/openmicroscopy/openmicroscopy/pull/4249 to be merged first to fix the conflict. Excluding for now.

**Comment by jburel** [comment]
@will-moore: PR #4249  has now been merged and #4255 has been excluded.
Could you fix the conflict like that your PR will be included in the next build?

**Comment by will-moore** [comment]
Merge conflict fixed. @sbesson can you remove the 'exclude' flag again? Thanks

**Comment by jburel** [comment]
@will-moore : already done

**Comment by jburel** [comment]
* It will be nice to remove the existing extension before adding the selected extension I end with images like 8kx8k.jpg.jpeg
 * I export the image 8kx8k.jpg as jpeg then export it as png. I end up having 8kx8k.jpg.jpeg and 8kx8k.jpg (1).png This is not logical.

**Comment by jburel** [comment]
Remove my last comment, since it happens that I have an old file with png extension in folder.
We are still out of synch for OME-TIFF export between web/insight and script.

**Comment by jburel** [comment]
Discussed with @will-moore: 
 * extension "removal" low priority, not to be done here (if we decide to do it!)
 * we leave the OME-TIFF option as it is. we can revisit in 5.2.x

**Comment by jburel** [comment]
@will-moore: maybe use ```getDownloadAsMaxSizeSetting()``` as you suggested on https://github.com/ome/scripts/pull/105

**Comment by will-moore** [comment]
@jburel Is there anything else needed for this PR (leaving OME-TIFF for now).

**Comment by jburel** [comment]
I will create an item for ome-tiff test.

**Pull request merged**
