### PR TITLE
Django 1.11

### PR DESCRIPTION
**Pull request by will-moore**
# What this PR does

Updates OMERO.web to use Django 1.11.
https://trello.com/c/qOUsiP0P/43-upgrade-to-django-111

Django 1.8 support ends at start of April 2018 (see https://www.djangoproject.com/download/).

NB: Heads-up. Django 1.11 series ends in 2 years and it's the last to support Python 2.
https://docs.djangoproject.com/en/2.0/releases/1.11/
cc @joshmoore @chris-allan 

# Testing this PR

1. Not ready to be tested yet, but will need a lot!

TODO:
 - I temporarily removed Pipeline and custom forms renderer so we could push a "working" branch. Will now look to get that functionality back.

### CODE REVIEW

**Comment by jburel** [comment]
This is currently for evaluation since it will be far too much for 5.4.4 and break the apps

basically we cannot bump the version for 5.4.x, far too much

**Comment by manics** [comment]
Worth creating a separate branch so we can get a regular docker build for testing?

**Comment by will-moore** [comment]
@manics You mean a branch off develop?

**Comment by manics** [comment]
I guess somewhere 5.5/6.0 development can happen

**Comment by jburel** [comment]
Closing this PR since we will not do any work for now on Django

**Pull request closed without merging**
