### PR TITLE
fixing channel background-colour (rebased onto develop)

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
This is the same as gh-4041 but rebased onto develop.

----

This should fix channel buttons issue reported in https://trac.openmicroscopy.org/ome/ticket/12981

Test both channel buttons in Preview, Main viewer and rendering popup box in Viewer

cc: @pwalczysko

### CODE REVIEW

**Comment by aleksandra-tarkowska** [comment]
--rebased-from #4041

**Comment by jburel** [comment]
restarted travis

**Comment by pwalczysko** [comment]
Tested Firefox Win7 and Mac OS 10.10. 
Works as expected. Ready to merge

**Comment by jburel** [comment]
the following commit could be added to this PR so the test is green before merging
https://github.com/aleksandra-tarkowska/openmicroscopy/commit/3c06883ae5166f5aa523e8e8d29cd12fa2b15cdf

**Comment by aleksandra-tarkowska** [comment]
@jburel added but as mentioned in the https://github.com/openmicroscopy/openmicroscopy/pull/4050 it should be tested if test didn't fail on ``KEYWORD: Wait For Channel Color rgb(...)``. It still may fail in another location.

**Comment by jburel** [comment]
@aleksandra-tarkowska: Thanks, understood

**Comment by pwalczysko** [comment]
The robot test ``Full Name: 	Web & Web.Web.Rdef Test.Test Owners Rdef`` fails with the 
```
KEYWORD: Wait For Channel Color rgb(255, 255, 255)
Start / End / Elapsed: 	20150817 05:49:42.049 / 20150817 05:50:32.472 / 00:00:50.423
```
as read on https://ci.openmicroscopy.org/view/DEV/job/OMERO-DEV-merge-robotframework/53/robot/report/log.html#s1-s1-s5-t2.
This looks like exactly the error of which @aleksandra-tarkowska warned in https://github.com/openmicroscopy/openmicroscopy/pull/4050

**Comment by pwalczysko** [comment]
Otherwise, the UI behaviour is still as expected, but see https://github.com/openmicroscopy/openmicroscopy/pull/4048#issuecomment-131864931

**Comment by aleksandra-tarkowska** [comment]
@pwalczysko I run RDef tests from local agains eel/integration (exactly as job is doing) Looks like due to the failure on the first test second is failing as well in chrome. 

```
==============================================================================
Rdef Test :: Tests copying, pasting and applying Rendering settings.          
==============================================================================
Test Rdef Copy Paste Save :: Tests Copy and Paste rdef, then Save ... | PASS |
------------------------------------------------------------------------------
Test Owners Rdef :: Log in as non-owner and apply Imported and Own... | PASS |
------------------------------------------------------------------------------
Rdef Test :: Tests copying, pasting and applying Rendering settings.  | PASS |
```

At this moment we do not have any solution for first test ``Tests Copy and Paste rdef, then Save`` failures as that is random and only on Chrome.

**Comment by pwalczysko** [comment]
@aleksandra-tarkowska explained that the failure is not present on Firefox, thus not being a failure in code. Also her locally run robot test against eel run fine, the main suspect is outdated environment of eel here @sbesson .

Ready to merge.

**Comment by aleksandra-tarkowska** [comment]
@sbesson here is a card https://trello.com/c/NG5uBj1g/1233-upgrading-robot-related-libs-and-drivers. Happy to help.

**Pull request merged**
