### PR TITLE
Don't try to convert to referenceframe

### PR DESCRIPTION
**Pull request by dominikl**
Don't try to convert the unit for image acquisition position to reference frame, just display as it is.
Fixes [Ticket 13097](https://trac.openmicroscopy.org/ome/ticket/13097)

Test:
Display image acquisition metadata for an image which does not use reference frame as unit, e. g. eel, user-5,image id 26061 (or the images from the bug report, eel, user-5/read-write-1, Dataset name 16890)

### CODE REVIEW

**Comment by pwalczysko** [comment]
Suspected of causing the https://trac.openmicroscopy.org/ome/ticket/13099#ticket - to be testied tomorrow.

**Comment by dominikl** [comment]
Additional test:
- Make sure **Insight does not crash** when opening a ```*.dv``` image in full viewer

**Comment by pwalczysko** [comment]
Works as expected. Ready to merge.

**Comment by jburel** [comment]
@dominikl 
```value == null || value.equals("")``` the method ```isBlank``` from ```CommonsLangUtil``` could be used

**Comment by jburel** [comment]
@dominikl: thanks

**Pull request merged**
