### PR TITLE
Spw wellimages launch viewer

### PR DESCRIPTION
**Pull request by will-moore**
# What this PR does

Opens the image viewer when user double-clicks on a WellSample image in bottom panel of SPW layout.
Also fixes a minor bug loading bottom panel when double-clicking on Well.

# Testing this PR

 - Double-click on Well to launch viewer for current field and check that WellSample images have loaded in bottom panel and are not duplicated.
 - Double-click on WellSample image to open image viewer.
 - Check that other clicks on these images are still working, including shift-click / ctrl-click to select multiple images.
 - Robot test 'spw_test' should pass.

# Related reading

See https://trello.com/c/FW5KKs5Q/289-bug-no-full-viewer-when-click-on-image-in-spw-web

cc @pwalczysko

### CODE REVIEW

**Comment by pwalczysko** [comment]
The UI test: all as expected.
The robot spw_test passes.
The only question is 
screen shot 2017-03-03 at 15 52 05

If this is just flakiness of the three tests, then ready to merge FMPOV.

**Comment by will-moore** [comment]
Thanks @pwalczysko I will fix ```Test Show Well Images``` robot test...

**Comment by will-moore** [comment]
Last commit should fix robot tests.

**Comment by dominikl** [comment]
Looks alright, test passed 👍

**Pull request merged**
