### PR TITLE
Cap django-redis

### PR DESCRIPTION
**Pull request by jburel**
# What this PR does

Cap django-redis

Discussed in Slack

cc @sbesson @joshmoore

### CODE REVIEW

**Comment by jburel** [comment]
Tested on ubuntu16.04
* worked fine with ``django-redis-4.8.0``
* failed with ``django-redis-4.9.0``. In that case ``Django-1.11.10`` is installed and OMERO.web cannot start
```
ERROR: Django version 1.11.10 is not supported!
Stopping OMERO.web... [OK]
OMERO.web WSGI workers (PID 933) killed.
Removed stale /home/omero/OMERO.server/var/django.pid
ERROR: Django version 1.11.10 is not supported!
```

**Comment by jburel** [comment]
tested also with 4.4, 4.5, 4.6, 4.7, everything works

**Review by manics — APPROVED** [review]
Looks good to me.

Testing on CentOS7 suggests that if Django and django-redis are installed at the same time using an old `requirements-py27.txt` the correct version of Django is installed, so existing releases may still be OK:
```
# virtualenv x --system-site-packages
# x/bin/pip install -r /opt/omero/web/OMERO.web/share/web/requirements-py27.txt
# x/bin/pip freeze |grep -i django
Django==1.8.18
django-pipeline==1.3.20
django-redis==4.9.0
```

**Comment by manics** [comment]
For completeness this should be rebased to `metadata53`, and any apps requiring django-redis (such as mapr) should also have this fix.

**Comment by jburel** [comment]
@manics thanks for the review
merging so I can prep an rc2

**Pull request merged**
