### PR TITLE
Create pds for others

### PR DESCRIPTION
**Pull request by will-moore**
# What this PR does

Allows users with ```writeOwned``` privilege to create P/D/S belonging to other users:
https://trello.com/c/0icOEIqM/12-rfe-enable-creation-of-p-d-s-on-behalf-of-others-in-web

Also fixes linking of objects in tree so that when user with "writeOwned" moves items in the tree, the new links created belong to the same owner as the parent object.

screen shot 2017-07-31 at 11 15 20

NB: Creation of P/D/S for other users when viewing "All Members" is not yet supported. To keep this PR manageable and within time constraints of m3, support for "All Members" should be in follow-up PR.

TODO:
 - [x] Robot tests!
 - [x] Integration tests.

# Testing this PR

 - Log in as a restricted Admin with at least ```writeOwned``` privilege.
 - When viewing your own data, Create P/D/S should be identical to regular user (objects belong to you)
 - Viewing another User's data, Create P/D/S should simply indicate that the data will belong to that user (users without ```writeOwned``` should have P/D/S creation disabled as before).
 - Viewing "All Members" data, Create P/D/S is only enabled if you are a member of the Group (data will belong to you). See NB above.
 - When a user with ```writeOwned``` copies/cut/paste or drag/drops data in the tree, new links should belong to the same user as the Parent object. Can be tested by that user trying to cut links in a read-ann / read-only group. (NB: above, for new object creation, link belongs to same owner as the new data, not the parent)?
 - Test creation of new Dataset with orphaned images selected.

cc @pwalczysko

### CODE REVIEW

**Comment by jburel** [comment]
``
./components/tools/OmeroWeb/omeroweb/webclient/views.py:2565:50: E128 continuation line under-indented for visual indent
``

**Comment by pwalczysko** [comment]
>NB: above, for new object creation, link belongs to same owner as the new data, not the parent)?

Yes, this makes some sense.

**Comment by pwalczysko** [comment]
Bug1:

  - light admin with only "Write data" privilege
  - light admin logs in and goes to private group, filtering for user-2
  - light admin does not have icons for creation of P/D/S enabled until the user node is selected -> is this intended ?
  - after the P/D/S creation icons are enabled in this way, the first creation of a Project causes also the right-click menu on this Project to be enabled, but not on other Projects or Datasets -> is this intended ?
  - then a crashes can be elicited as these newly created Datasets are being dragged and dropped to the other Projects

I guess the intention here was not to enable any icons in the Private group in the first place when filtering for others' data ?

**Comment by pwalczysko** [comment]
Bug2: In Read-annotate group, of which the light admin is a member.

  - light admin has "WriteData" but nothing else
  - light admin goes to "All members" view
  - light admin drags and drops a Dataset of somebody else abd is linked to somebody else's Project to their (light admin's) project
  - observe error

Edit: I think the error is connected to the fact that light admin was trying to sever the original link by trying to drag and drop (for which they have no permissions, as they have no "Delete Data"). Note that the creation of the new link is successful, whilst the original link is not severed.

**Comment by pwalczysko** [comment]
Except for [Bug1](https://github.com/openmicroscopy/openmicroscopy/pull/5402#issuecomment-319698705) and [Bug2](https://github.com/openmicroscopy/openmicroscopy/pull/5402#issuecomment-319720091)  all tests in the header of this PR passed.

**Comment by will-moore** [comment]
@pwalczysko Those 2 bugs should be fixed (Delete link failure is silent now).
I changed the create enabled logic a bit because it was previously only allowing creation if canLink was True on the selected object which didn't make much sense (E.g. could on create Screen if selected Dataset was canLink).
Actually, if createOwned is True then we don't care about canLink since the new link is owned by the same owner as the parent, so we can always link!
Need to clarify all the use cases we are supporting.

**Comment by will-moore** [comment]
TODO: remove linking logic from this PR (only handle creation of new obj).

**Comment by pwalczysko** [comment]
Created https://trello.com/c/lEZQ4DdA/104-light-crash-in-web-when-d-d for the "delete link when you have no rights" crash. This was a pre-existing (pre-this-PR, not pre-5.4.0) bug which we missed when fixing the light crashes in web.

**Comment by pwalczysko** [comment]
Retest of all functionalities went all as expected, light admin which can or cannot delete and can or cannot write (being a group member or not), as well as normal user were tested. Checked also the Orphaned images workflow, works fine. Checked links ownership and this is as expected as well. 

Ready to merge.

**Comment by jburel** [comment]
Methods in ``webclient_gateway`` will need to be deprecated instead of removed

**Comment by will-moore** [comment]
@jburel TODOs to be done in this PR or a follow-up?

**Comment by jburel** [comment]
Too late for 5.4.0-m3
I will do the todos in this PR
minimally the tests should be added

**Comment by will-moore** [comment]
Robot and web integration tests added.

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#767](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/767/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/767/consoleText) for more details.
Possible conflicts:
  - PR #5347 will-moore 'Testlib request methods'
    - components/tools/OmeroWeb/test/integration/test_containers.py

**Comment by will-moore** [comment]
@jburel I tried to add tests without conflicting with #5347 but it obviously didn't work.
Need to get that PR in first probably.

**Comment by will-moore** [comment]
New robot test: https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-merge-robotframework/682/robot/Web%20&%20Web/Web/Create%20Scenario/Test%20Create%20Owned/
and integration test https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-merge-integration-Python27/627/testReport/OmeroWeb.test.integration.test_containers/TestContainers/test_add_owned_container/
are passing.

**Comment by will-moore** [comment]
@jburel If you're happy with this, it would be nice to merge so @rgozim can fix merge conflicts in https://github.com/openmicroscopy/openmicroscopy/pull/5428, thanks.

**Comment by jburel** [comment]
Thanks for adding the tests and marking the methods back.
Merging so @rgozim can move forward

**Pull request merged**
