### PR TITLE
Disable lineplot for tiled images

### PR DESCRIPTION
**Pull request by dominikl**
# What this PR does

Based on @will-moore 's PR #4703 .  
Just adds one commit which disables the 'Line Plot' feature for big images.
screen shot 2016-12-13 at 11 05 09

# Testing this PR

Open a big image, make sure there's no "Line Plot" checkbox.
Open a small image, make sure the "Line Plot" checkbox is there.

# Related reading

[Trello - Bug: `learning` plot error](https://trello.com/c/UWelSy4x/233-bug-learning-plot-error)

### CODE REVIEW

**Comment by dominikl** [comment]
That's strange, also the whole "Zoom" section is gone for big images... 
**Not ready for review yet**

**Comment by will-moore** [comment]
@dominikl The ```tiledImage``` parameter is not available in the context of the main viewer, only in the Preview panel.
You need to use an approach like this for full viewer: https://github.com/openmicroscopy/openmicroscopy/pull/4996/commits/fcd1cc547238e747fb15ff20fb028b4693eca9c4

**Comment by dominikl** [comment]
Yes, just found that, thanks 👍

**Comment by dominikl** [comment]
Couldn't reopen PR because I force-pushed, therefore opened a new PR, #4997

**Pull request closed without merging**
