### PR TITLE
Docker bump

### PR DESCRIPTION
**Pull request by joshmoore**
Upgrade the Docker build in this repo to match those in https://github.com/ome/ome-documentation/pull/2034

### CODE REVIEW

**Comment by joshmoore** [comment]
Green with the custom branch from https://github.com/ome/omero-test-infra/pull/51 (also green). Reverting and then getting this merged.

**Comment by sbesson** [comment]
Is 6c779cce9f1371cea368abb959cf44237c77a0d4 still expected to be merged?

**Comment by joshmoore** [comment]
If we want travis passing again ASAP, yes. There are _quite_ a number of flake8 fixes needed.

**Comment by joshmoore** [comment]
Green!

**Pull request merged**
