### PR TITLE
correct "right" typo

### PR DESCRIPTION
**Pull request by mtbc**
Trivial fix to Insight code, should be no change in behavior.

--no-rebase

### CODE REVIEW

**Comment by mtbc** [comment]
Trying to get Travis to notice this PR.

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#960](https://ci.openmicroscopy.org/job/OME-5.1-merge-push/960/). See the [console output](https://ci.openmicroscopy.org/job/OME-5.1-merge-push/960/consoleText) for more details.
Possible conflicts:
  - PR #3691 dominikl 'Show magnification'
    - components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ImViewerUI.java

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#961](https://ci.openmicroscopy.org/job/OME-5.1-merge-push/961/). See the [console output](https://ci.openmicroscopy.org/job/OME-5.1-merge-push/961/consoleText) for more details.
Possible conflicts:
  - PR #3691 dominikl 'Show magnification'
    - components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ImViewerUI.java

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#962](https://ci.openmicroscopy.org/job/OME-5.1-merge-push/962/). See the [console output](https://ci.openmicroscopy.org/job/OME-5.1-merge-push/962/consoleText) for more details.
Possible conflicts:
  - PR #3691 dominikl 'Show magnification'
    - components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ImViewerUI.java

**Comment by mtbc** [comment]
--exclude until #3691 is resolved.

**Comment by ximenesuk** [comment]
Changes look fine and Insight looks fine. Good to merge.

**Pull request merged**
