### PR TITLE
a batch of tidying up headers and imports in Java files

### PR DESCRIPTION
**Pull request by mtbc**
This is one of a series of PRs that minorly tidy the comments and imports at the start of Java source files. Nothing important should be lost and the code should still build fine.

--no-rebase

### CODE REVIEW

**Comment by jburel** [comment]
@mtbc: the changes in insight are going to conflict with the migration of the pojos.
I thought you will stick to blitz package

**Comment by mtbc** [comment]
It's for fixing the Javadoc warnings that I am focusing on the server and blitz components.

As well as avoiding `components/blitz/src/pojos` I could force-push to remove all changes to the insight component.

**Comment by jburel** [comment]
@mtbc: if you could do that, that will be great. Thanks

**Comment by jburel** [comment]
Some changes are likely to conflict with my pojos-migration
i.e. any file with pojos import e.g. PixelProcessor

**Comment by mtbc** [comment]
Agreed: I'll not open any further PRs without checking that they merge cleanly atop #4128.

**Comment by joshmoore** [comment]
LGTM, but I suggest we merge Monday after the rebuild unless it's blocking someone.

**Comment by jburel** [comment]
can be merged on monday after build.

**Pull request merged**
