### PR TITLE
A few minor CLI fixes

### PR DESCRIPTION
**Pull request by ximenesuk**
This PR is a holder for a few minor CLI fixes.

Partially
--rebased-to #4076

The first is: prevent CLI chmod from timing out when downgrading to private. See https://trello.com/c/GZCqaV5D/35-chmod-on-cli-not-usable  This fix uses the same fix as in https://github.com/openmicroscopy/openmicroscopy/pull/3853 To test a group that has some complexity: users, data, etc. should be downgraded to private on the commandline:
```
omero group perms --id XX --perms "rw----"
```

### CODE REVIEW

**Comment by ximenesuk** [comment]
For the second commit see: https://trello.com/c/R3ZYCmDV/42-cli-object-graph-lists

To test this
```
omero delete --help
```
should not show the `--list` and `--list-details` options. However,
```
omero delete --list
omero delete --list-details
```
should both still give output.

Should this now useless output also be suppressed?

Should the options be removed entirely?

**Comment by pwalczysko** [comment]
I have successfully downgraded fairly complicated groups (like read-write-1 of the chown-chmod DB, read-write-3 of the same DB, read-annotate-1 of the same DB) to private.
Unfortunately, when trying to downgrade group read-write-3b, which is like read-write-3 group, only additionally images of one user are linked to datasets of another user (non-owners), I have:
```
$ bin/omero group perms --name read-write-3b --type private
Using session d5fabef1-2256-400c-ae48-40e884c06327 (owner@localhost:4064). Idle timeout: 10 min. Current group: private-1
Traceback (most recent call last):
  File "bin/omero", line 125, in <module>
    rv = omero.cli.argv()
  File "/home/omero/OMERO.server-5.1.3-83-1a5945b-ice35-b595/lib/python/omero/cli.py", line 1431, in argv
    cli.invoke(args[1:])
  File "/home/omero/OMERO.server-5.1.3-83-1a5945b-ice35-b595/lib/python/omero/cli.py", line 945, in invoke
    stop = self.onecmd(line, previous_args)
  File "/home/omero/OMERO.server-5.1.3-83-1a5945b-ice35-b595/lib/python/omero/cli.py", line 1022, in onecmd
    self.execute(line, previous_args)
  File "/home/omero/OMERO.server-5.1.3-83-1a5945b-ice35-b595/lib/python/omero/cli.py", line 1104, in execute
    args.func(args)
  File "/home/omero/OMERO.server-5.1.3-83-1a5945b-ice35-b595/lib/python/omero/plugins/group.py", line 197, in perms
    c.submit(chmod, loops=120)
  File "/home/omero/OMERO.server-5.1.3-83-1a5945b-ice35-b595/lib/python/omero/clients.py", line 882, in submit
    closehandle=True)
  File "/home/omero/OMERO.server-5.1.3-83-1a5945b-ice35-b595/lib/python/omero/clients.py", line 913, in waitOnCmd
    raise omero.CmdError(rsp)
omero.CmdError
$ `
```

**Comment by pwalczysko** [comment]
After further investigation, https://github.com/openmicroscopy/openmicroscopy/pull/4061#issuecomment-132603984 is caused by me not having the permissions to do the action. After logging in as the owner of the group, I was able to dowgrade the group to private with no problem. 

Interestingly, the error output; in https://github.com/openmicroscopy/openmicroscopy/pull/4061#issuecomment-132603984 repeats also with group read-write-3c, which is supposed to fail on grounds of it having the projections of images made by another user. This would mean that whatever the failure, the same not-intelligible error message will occur ? Compare with the message in Web, which goes

screen shot 2015-08-19 at 14 53 27


Other than the error messages, all works fine here.

**Comment by pwalczysko** [comment]
Sorry, forgot to test the second commit.

**Comment by pwalczysko** [comment]
Apparently, the second commit is not in the build, as it was done 4 hours ago @ximenesuk ? Can test tomorrow if you relist.

**Comment by ximenesuk** [comment]
The last three commits remove the prompt is no description is provided, this brings the CLI in line with other clients. To test:
```
omero tag create
omero tag createset
```
should both prompt for a name if not provided, via the `--name` option, but not a description if not provided, via the `--desc` or `--description`.

**Comment by pwalczysko** [comment]
The workflow described in comment https://github.com/openmicroscopy/openmicroscopy/pull/4061#issuecomment-132519256 concerning the "second commit" works as expected.

**Comment by pwalczysko** [comment]
After the commit fixing the error message I have
```
[petr@LS25165 ~/Downloads/OMERO.server-5.1.3-93-420bd90-ice35-b596]$ bin/omero group perms --name ReadWrite_chmod_test --type private
Using session 7930ba61-f275-43c9-bc2a-31e611144b01 (user-4@trout.op..y.org:4064). Idle timeout: 10 min. Current group: read-only-1
Cannot change permissions for group ReadWrite_chmod_test (id=62) to rw----: object #0 (::omero::cmd::GraphException)
{
    category = ::omero::cmd::Chmod
    name = graph-fail
    parameters = 
    {
        key = stacktrace
        value = ome.services.graphs.GraphException(message=cannot process ome.model.meta.ExperimenterGroup[62]: user is not an owner of group 62)
	at ome.services.graphs.GraphTraversal.assertMayBeProcessed(GraphTraversal.java:1284)
	at ome.services.graphs.GraphTraversal.processTargets(GraphTraversal.java:1523)
	at omero.cmd.graphs.Chmod2I.step(Chmod2I.java:246)
	at omero.cmd.graphs.ChmodFacadeI.step(ChmodFacadeI.java:119)
	at omero.cmd.HandleI.steps(HandleI.java:437)
	at omero.cmd.HandleI$1.doWork(HandleI.java:365)
	at omero.cmd.HandleI$1.doWork(HandleI.java:361)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:307)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at ome.services.util.Executor$Impl$Interceptor.invoke(Executor.java:566)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at ome.security.basic.EventHandler.invoke(EventHandler.java:154)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.orm.hibernate3.HibernateInterceptor.invoke(HibernateInterceptor.java:111)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:108)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at ome.tools.hibernate.ProxyCleanupFilter$Interceptor.invoke(ProxyCleanupFilter.java:249)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at ome.services.util.ServiceHandler.invoke(ServiceHandler.java:121)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
	at com.sun.proxy.$Proxy72.doWork(Unknown Source)
	at ome.services.util.Executor$Impl.execute(Executor.java:447)
	at omero.cmd.HandleI.run(HandleI.java:359)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at ome.services.util.Executor$Impl$1.call(Executor.java:488)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

        
        key = message
        value = 
    }
    message = cannot process ome.model.meta.ExperimenterGroup[62]: user is not an owner of group 62
}
[petr@LS25165 ~/Downloads/OMERO.server-5.1.3-93-420bd90-ice35-b596]$ 
```

Which is much nicer.
Not sure whether the further commits are included in the build, so stopping there.

**Comment by ximenesuk** [comment]
The last three commits remove the prompt is no description is provided, this brings the CLI in line with other clients. To test:
```
omero tag create
omero tag createset
```
should both prompt for a name if not provided, via the `--name` option, but not a description if not provided, via the `--desc` or `--description`.

**Comment by ximenesuk** [comment]
These last two commits fix a bug in `tag list` and list empty tag sets when using the `listsets` subcommand. To test create a couple of tagsets, with one empty.
```
omero tag listsets
```
should include the empty tag set in the list.

**Comment by dominikl** [comment]
Checked last two commits, looks good, works like expected.

**Comment by dominikl** [comment]
Checked the last commits (tag(set)s creation/listing), looks good, works like expected.

**Pull request merged**
