### PR TITLE
DnD autoscroll fix

### PR DESCRIPTION
**Pull request by dominikl**
Fixes [Ticket 12959](http://trac.openmicroscopy.org/ome/ticket/12959)

First Workaround:
Autoscrolling while performing drag&drop operations on trees is basically broken, due to various Java bugs which apparently don't get fixed. This PR adds a workaround, which is mainly based on a suggestion in this [stackoverflow post](http://stackoverflow.com/questions/29126758/how-can-i-implement-a-workaround-for-the-autoscroll-during-drag-and-drop-bug-on).
It still doesn't work as neat as is it should be, but at least it works. In order to activate autoscroll, you have to drag an item to the egde of the tree's visible area.

Second Workaround:
DnD on Windows didn't work at all, also several Java issues there (DataFlavor.javaJVMLocalObjectMimeType throws an exception on Windows; objects transfered via Transferables get messed up, ...). With this PR a simple String dummy DataFlavor is used, while the actual data for the DnD action is hold in the the DnDTree itself.

**How to test:** Perform a few drag&drop operations in the left hand side tree, on OSX, Windows and Linux (as the DnD seems to be very platform specific). Cover the case where the tree is quite large, so that your desired drop location is outside of the current visible area. Make sure DnD behaves as expected.

### CODE REVIEW

**Comment by dominikl** [comment]
Sorry for the many formatting changes, it's quite hard to view the diff now...

**Comment by sbesson** [comment]
Use https://github.com/openmicroscopy/openmicroscopy/pull/4228/files?diff=split&w=1 to remove whitespace changes.

**Comment by dominikl** [comment]
Ah, thanks @sbesson !

**Comment by dominikl** [comment]
RFE from @pwalczysko : Expand the target project/dataset after the DnD action. At the moment the user is a bit lost after the DnD action, because after the automatic tree refresh the target project/dataset might not be in the exact screen location anymore; sometimes even a previously expanded project/dataset is closed after tree refresh.

I think this is not an urgent PR to get merged, so I'll try to add the improvement to the PR.

**Comment by pwalczysko** [comment]
All tests as described in this PR passed on : Mac, Win7 and Linux (Ubuntu VM). Massive improvement.
Ready to merge in case @dominikl decides not to do https://github.com/openmicroscopy/openmicroscopy/pull/4228#issuecomment-144373296

**Comment by dominikl** [comment]
@pwalczysko Implemented https://github.com/openmicroscopy/openmicroscopy/pull/4228#issuecomment-144373296 Also a look at "automatic expansion of project nodes" when hovered over within a drag action, but that a bigger issue, don't think I can implement this, certainly not within this PR.

**Comment by jburel** [comment]
```deleted == null || deleted.size() == 0``` could be replaced by Collection.isEmpty

**Comment by jburel** [comment]
remove commented out code in ```DnDTree```

**Comment by pwalczysko** [comment]
Also the last commit works as expected on Mac, Win and Linux. Ready to merge.

**Comment by jburel** [comment]
Thanks merging

**Pull request merged**
