### PR TITLE
Modify omero.properties to point merge clients at staging registry

### PR DESCRIPTION
**Pull request by sbesson**
See https://trello.com/c/ZO1JVxMy/8-registry-2-clone

### CODE REVIEW

**Comment by sbesson** [comment]
@pwalczysko: this should allow to test the `OMERO.insight`, `OMERO.importer` and `OMERO.imagej` agents following the "Registering the usage" scenario

**Comment by aleksandra-tarkowska** [comment]
Just to clarify, this PR is only opened to help local testing and will never been merged in. There needs to be some work done in clients similar to https://github.com/openmicroscopy/openmicroscopy/pull/3204

**Comment by pwalczysko** [comment]
OMERO.insight: connecting to eel, from today's OMERO-DEV-merge-build: Connected to ``staging``, I scored 2 hits by logging in using insight to eel merge. The 2 hits were caused by 1. login, 2. close insight, 3. login again

This seems as expected behaviour for insight to me.

**Comment by pwalczysko** [comment]
OMERO.importer: totally analogical setup as in Insight's case see https://github.com/openmicroscopy/openmicroscopy/pull/4321#issuecomment-155083807. Totally analogical results - seems okay.

**Comment by pwalczysko** [comment]
Insight-ij -> when going through the scenario, I scored 2 hits. This is similar to what @sbesson reports in https://github.com/openmicroscopy/ome-internal/pull/253#issuecomment-143030851. Will correct the scenario. Works as expected.

**Comment by sbesson** [comment]
Closing. Will reopen if the registry work gets reprioritized.

**Pull request closed without merging**
