### PR TITLE
OMERO.insight Java Application Bundler task for Mac OS X (rebased onto develop)

### PR DESCRIPTION
**Pull request by sbesson**
This is the same as gh-3337 but rebased onto develop.

----

This pull request adds support for the Java Application Bundler (https://java.net/projects/appbundler) and its open source fork (https://bitbucket.org/infinitekind/appbundler). This bundler and corresponding launcher are intended, at least as far as we're concerned, as a transition point for Java 1.7+ on Mac OS X.

The high level `zips` target can be run to trigger the execution of the Java Application Bundler specific `dist-osx-appbundler` task as follows:

```
./build.py -f components/insight/build.xml zips
```

You will likely find that this is best run after a current build run via `./build.py clean build`. The new `OMERO.insight.app` is then available in the following subdirectory:

```
components/insight/OUT/dist/appbundler
```

Due to the fact that execution sets the "current working directory" to the user's home directory initial testing can be performed as follows:

```
components/insight/OUT/dist/appbundler/OMERO.insight.app/Contents/MacOS/OMERO.insight \
    container.xml `pwd`/components/insight/OUT/app
```

If you have errors, launcher debugging can be turned on with an environment variable (https://java.net/projects/appbundler/lists/dev/archive/2012-11/message/2):

```
export JAVA_LAUNCHER_VERBOSE=1
```

Work will have to be done on the following before this can be merged:

* Resolving issues with the way that OMERO.insight locates configuration files

/cc @jburel, @rleigh-dundee

### CODE REVIEW

**Comment by sbesson** [comment]
--rebased-from #3337

**Comment by sbesson** [comment]
--rebased-from #3407

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#736](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/736/). See the [console output](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/736/consoleText) for more details.
Possible conflicts:
  - PR #3329 jburel 'Imagej prep'
    - components/insight/SRC/org/openmicroscopy/shoola/env/Container.java

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#737](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/737/). See the [console output](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/737/consoleText) for more details.
Possible conflicts:
  - PR #3329 jburel 'Imagej prep'
    - components/insight/SRC/org/openmicroscopy/shoola/env/Container.java

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#738](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/738/). See the [console output](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/738/consoleText) for more details.
Possible conflicts:
  - PR #3329 jburel 'Imagej prep'
    - components/insight/SRC/org/openmicroscopy/shoola/env/Container.java

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#739](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/739/). See the [console output](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/739/consoleText) for more details.
Possible conflicts:
  - PR #3329 jburel 'Imagej prep'
    - components/insight/SRC/org/openmicroscopy/shoola/env/Container.java

**Comment by rleigh-dundee** [comment]
Works fine for me on 10.10; the Java7+ apps launch and the Java6 apps fail with an error to install the old JRE.

**Comment by qidane** [comment]
On 10.10 with Java 6: 
7+: Unable to load runtime environment.
6: Login dialog as expected.

**Comment by sbesson** [comment]
Thanks. Merging.

**Pull request merged**
