### PR TITLE
Folders step 4

### PR DESCRIPTION
**Pull request by dominikl**
Implementation of https://github.com/openmicroscopy/design/issues/30

**Test**
- Make sure integration tests still pass
- Delete a folder which contains ROIs and sub folders: Make sure ROIs are orphaned and sub folders become top level folders
- Select a couple of ROIs, create a new folder via context menu: Make sure the selected ROIs are added to the newly created folder. Note: The newly created folder will be a top level folder.
- Select a ROI which is part of a Folder. Check Inspector table; the folder(s) should be mentioned there.
- Switch to Results table. Add "Folders"  to the display (via Result Wizard). Check that the folder(s) the ROIs are part of are displayed.

### CODE REVIEW

**Comment by pwalczysko** [comment]
Bug: 
Re
>Select a ROI which is part of a Folder. Check Inspector table; the folder(s) should be mentioned there.

This works for Shapes (not ROIs) as expected on the first look. But, try
    - selecting a Folder, switch to Inspector (will be empty) and back to Manager
    - select then a ROI and go again Inspector -> Manager
    - select then a Shape and go Inspector -> will be empty (not expected)
    - if the bug does not demonstrate first time, keep selecting Folders/ROIs/Shapes and alternating between Inspector and Manager tabs until it demostrates

**Comment by pwalczysko** [comment]
Bug (for another PR I guess):
    - scrolling when trying Drag and Drop of several ROIs into a folder does work only intermittenlty

**Comment by pwalczysko** [comment]
One Bug and one Bug for another PR detected. All the rest works fine. Up to @dominikl whether he wants to merge this and bugfix in another PR or split the bugs and do one here and one somewhere else.

**Comment by dominikl** [comment]
Fixed the scrolling issue in #4573

**Comment by dominikl** [comment]
Fixed the "Edit Folder" bug in here. Fixed the autoscroll DnD bug in #4577 . Would propose to tackle https://github.com/openmicroscopy/openmicroscopy/pull/4567#issuecomment-209341268 in a follow-up PR, and merge this once last commit ("Edit Folder") has been reviewed.

**Comment by pwalczysko** [comment]
editing of folders works as expected. Ready to merge.

**Pull request merged**
