### PR TITLE
Fix _execute_child on Windows Python 2.7+

### PR DESCRIPTION
**Pull request by manics**
Copied from https://github.com/mozilla/addon-sdk/pull/1379
Fixes https://trac.openmicroscopy.org.uk/ome/ticket/12320

Testing: Scripts should now work on Windows with Python 2.7 (previously they only worked on 2.6). CI server is still being setup so you'll have to test on a local VM (or wait...).

### CODE REVIEW

**Comment by manics** [comment]
--on-hold

**Comment by chris-allan** [comment]
The commit message is certainly thorough but it would probably be good to link to the bug, fix and rationale explicitly, with URLs, in the actual code.

Fix itself looks good but will obviously require Windows testing which I won't be able to provide.

**Comment by manics** [comment]
@chris-allan comment added

**Comment by chris-allan** [comment]
Looks great.

:+1:

**Comment by rleigh-dundee** [comment]
Change looks fine itself.  I can't run the server on my system since it's all set up to use virtualenvs and the server can't use them on Windows due to the way it starts up as a service and requires everything to be in the global environment for the system.  (Couldn't we allow it to run a script to customise the service environment at startup?)

**Comment by joshmoore** [comment]
> (Couldn't we allow it to run a script to customise the service environment at startup?)

Yes, and I think something similar is what we need for Docker anyway.

But merging this.

**Comment by manics** [comment]
--no-rebase

**Pull request merged**
