### PR TITLE
rename Rect to Rectangle

### PR DESCRIPTION
**Pull request by mtbc**
The OME-XML schema has "Rectangle" but OMERO has "Rect". This PR aligns OMERO with OME-XML in that respect. Everything should still keep working, especially if related to rectangle ROIs.

--depends-on https://github.com/ome/scripts/pull/104
--no-rebase

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#102](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/102/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/102/consoleText) for more details.
Possible conflicts:
  - PR #4221 mtbc 'remove ROI tests that use keywords and namespaces (rebased from dev_5_1)'
    - components/tools/OmeroPy/test/integration/test_model42.py

**Comment by dominikl** [comment]
Looks good, no problems with Rectangle ROI noticed, tests still passing, couldn't find any more references to ```omero.model.Rect```. Good to merge.

**Comment by mtbc** [comment]
Thank you! Can hold this open while I fix the `Rect` in the scripts submodule and turn OMERO-DEV-merge-integration-python green.

**Comment by mtbc** [comment]
It's green today, so all seems done here. :smiley:

**Comment by joshmoore** [comment]
I'm a bit surprised to see this in 5.2, but perhaps since the discriminator is still `/rect` this is same enough. We'll minimally need "breaking API" documentation (cc: @hflynn) which perhaps we wanted to restricted to 5.3. For discussion on @mtbc's return.

**Comment by hflynn** [comment]
I chatted to Mark about this last week. This stuff isn't really documented at the moment (there are no docs for the OMERO model where it differs from the schema), I think we could get away with just adding a note about it in the what's new for devs file under 'API breaking changes'. I'll add a comment to the relevant card.

**Comment by mtbc** [comment]
The motivation for including in 5.2 is, with plenty of ROI work planned outside my model changes, with different class names merges between develop and regions would probably have kept conflicting.

**Pull request merged**
