### PR TITLE
Bump jul-to-slf4j and jcl-over-slf4j to version 2.0.16

### PR DESCRIPTION
**Pull request by sbesson**
Motivated primarily by the regression in #6405 and https://github.com/ome/openmicroscopy/issues/6405#issuecomment-2283339623, this bumps the version of `jul-to-slf4j` and `jcl-over-slf4j` to the latest release of the 2.0.x series, currently 2.0.16. These should be compatible with the version of `slf4j-api` which is now shipped in OMERO.server.

As an additional feature, the latest version of `jul-to-slf4j` now depends on `reload4j` (rather than `log4j`) for testing purposes. This does not resolve the dependency problems raised in #6405 but it further reduces the chances of `log4j.jar` unexpectedly creeping into the binaries.

Testing should confirm that logging statements using either JCL (Apache Commons Logging, formerly Jakarta Commons Logging) or JUL (java.util.logging) as still handled via `slf4` and ultimately `logback`.

Unfortunately the biggest usage of these logging frameworks will be in third-party dependencies since the majority of the OMERO code base has been converted to using `slf4j` and `logback` over a decade ago - https://github.com/ome/openmicroscopy/pull/1006.

Within OMERO, there are still a few classes making internal use of  either JCL or JUL:
- the JVM checks in [ome.service.util.JvmSettingsCheck](https://github.com/ome/omero-server/blob/8eb311d45642163b79463c38c4b06884a637923d/src/main/java/ome/services/util/JvmSettingsCheck.java#L79) are using JCL -L85. These should be easy to test as they are logged in `Blitz-0.log` at the server startup
- `ome.util.Utils` uses JUL in its [closeQuietly](https://github.com/ome/omero-model/blob/7e89fbd253f75213d1c3c0dc9fb202ecf3296b6c/src/main/java/ome/util/Utils.java#L158-L168) API, `Utils.closeQuietly` is used in a few components to close input streams however the logging message will only appear if `close()` throws an exception so I can't think of a good scenario off-hand
- [omero.util.Resources](https://github.com/ome/omero-blitz/blob/bf9a738b0417973de01be3b2f7ccf45ee2eacd19/src/main/java/omero/util/Resources.java) uses JUL internally when adding/removing/cleaning managed entries. Here again most logging statement are at the FINEST (aka TRACE) level and only unexpected behaviors are logged at a WARNING level. This class is used in `omero.client` and the import code base primarily when calling keepAlive - https://github.com/search?q=org%3Aome+omero.util.Resources+language%3AJava&type=code&l=Java

As a follow-up all the classes above could probably be updated to use the `slf4j` API and get rid of JCL and JUL at least in the OME codebase. I'll hold on opening these until this has been tested as it could make the testing more complicated.

### CODE REVIEW

**Comment by jburel** [comment]
@sbesson Do you need/have a ticket to capture the work to follow-up?

**Comment by sbesson** [comment]
> @sbesson Do you need/have a ticket to capture the work to follow-up?

I have not done anything as I was waiting for feedback on the proposed changes first. Happy to capture as issues if this work would be up for consideration. In that case, would it be preferable to have a single issue in this repository or three issues in `omero-model`, `omero-server` and `omero-blitz`?

**Comment by jburel** [comment]
A single issue will make sense.

**Review by jburel — APPROVED** [review]

**Comment by sbesson** [comment]
> A single issue will make sense.

Opened as https://github.com/ome/openmicroscopy/issues/6416

**Pull request merged**
