### PR TITLE
Switch user quit

### PR DESCRIPTION
**Pull request by dominikl**
# What this PR does

Bugfix for [Ticket 13267](https://trac.openmicroscopy.org/ome/ticket/13267)

# Testing this PR

Connect to a server, click on "switch user", but don't log in again, instead click on "Quit". Insight should exit (before it didn't)

### CODE REVIEW

**Comment by pwalczysko** [comment]
Works as expected on Mac and Windows.  Maybe @mtbc would like to have a look on Linux ?

**Comment by mtbc** [comment]
Works fine here too. :+1:

**Comment by jburel** [comment]
I will log the exception in the error message.

**Comment by jburel** [comment]
Sorry I missed the "e" logged in the message (small screening). Merging

**Pull request merged**
