### PR TITLE
fix typo in 5.0 to 5.1 SQL upgrade character encoding error

### PR DESCRIPTION
**Pull request by mtbc**
Accidentally used .vm file quoting syntax. Now with a wrong DB character encoding, upgrade from 5.0 should give an appropriate error message.

--no-rebase unless 5.1.5

### CODE REVIEW

**Comment by rleigh-dundee** [comment]
The change is correct so long as this is never used as a template.  It would be nice if the template files had a '.sql.in' or similar suffix to distinguish them from real sql.

Note a second instance of the typo:

```
                RAISE EXCEPTION '%%', 'Directory('||OLD.id||')='||OLD.path||OLD.name||'/ is not empty!';
```

later on in this file.

**Comment by mtbc** [comment]
Thank you. I'll add something to the upgrade to 5.2 to fix this for those already on 5.1.

**Comment by rleigh-dundee** [comment]
This PR is certainly good to merge in the interim; the failure case works correctly for me.

**Comment by joshmoore** [comment]
@chris-allan points out that an upgrade from 4.4 still runs into this.

**Comment by chris-allan** [comment]
Required changes to perform a 4.4 to 5.0 upgrade using [OMERO4.4__0.sql](../tree/v5.2.5/sql/psql/OMERO5.0__0/OMERO4.4__0.sql) (from 5.2.5) on PostgreSQL 9.5.4:

```
--- OMERO4.4__0.sql.orig	2016-09-05 19:32:35.944000000 +0000
+++ OMERO4.4__0.sql	2016-09-05 19:33:26.424000000 +0000
@@ -413,7 +413,7 @@
        LIMIT 1;
 
       IF duplicate IS NOT NULL THEN
-          RAISE NOTICE ''Remapping filesetentry %% via (-1 - oldvalue )'', duplicate;
+          RAISE NOTICE ''Remapping filesetentry % via (-1 - oldvalue )'', duplicate;
           UPDATE filesetentry SET fileset_index = -1 - fileset_index WHERE id = duplicate;
       END IF;
 
@@ -442,7 +442,7 @@
        LIMIT 1;
 
       IF duplicate IS NOT NULL THEN
-          RAISE NOTICE ''Remapping filesetjoblink %% via (-1 - oldvalue )'', duplicate;
+          RAISE NOTICE ''Remapping filesetjoblink % via (-1 - oldvalue )'', duplicate;
           UPDATE filesetjoblink SET parent_index = -1 - parent_index WHERE id = duplicate;
       END IF;
 
@@ -466,7 +466,7 @@
                            LIMIT 1) THEN
 
                     -- CANCEL DELETE
-                    RAISE EXCEPTION '%%', 'Directory('||OLD.id||')='||OLD.path||OLD.name||'/ is not empty!';
+                    RAISE EXCEPTION '%', 'Directory('||OLD.id||')='||OLD.path||OLD.name||'/ is not empty!';
 
                 END IF;
             END IF;
@@ -514,7 +514,7 @@
 CREATE FUNCTION _fs_directory_mimetype() RETURNS "trigger" AS $$
     BEGIN
         IF OLD.mimetype = 'Directory' AND NEW.mimetype != 'Directory' THEN
-            RAISE EXCEPTION '%%', 'Directory('||OLD.id||')='||OLD.path||OLD.name||'/ must remain a Directory';
+            RAISE EXCEPTION '%', 'Directory('||OLD.id||')='||OLD.path||OLD.name||'/ must remain a Directory';
         END IF;
         RETURN NEW;
     END;
```

I would expect many people to have upgraded from 4.4 to 5.0 using this script It is unchanged from its December 13th, 2013 version. There is a very real possibly of having functions with syntax errors in them in such DBs. Not 100% sure as to the impact but it's probably worth investigating.

/cc @mtbc

**Comment by mtbc** [comment]
I am pretty sure that no 5.2 DBs will have such functions left in them. However, this raises the question of our duty to support scripts to upgrade from unsupported versions of OMERO. In this case, I think it's easily worth the effort to retroactively fix the upgrade scripts at the least.

**Comment by chris-allan** [comment]
If we want to continue to take the position that we're only officially supporting the latest open source version and suggest to people having problems to upgrade then I would argue that it's our duty to support them indefinitely.

Checked one of our demonstration systems that has a series of historical upgrades starting from 4.3. It is currently running 5.2.5. Definitely has functions with syntax errors in them:

```
omero=# select * from dbpatch ;
 id | currentpatch | currentversion | permissions |          finished          |                                           message                                            | previouspatch | previousversion | external_id 
----+--------------+----------------+-------------+----------------------------+----------------------------------------------------------------------------------------------+---------------+-----------------+-------------
  1 |            0 | OMERO4.3       |         -35 | 2012-03-24 22:33:37.344486 | Database ready.                                                                              |             0 | OMERO4.3        |            
  2 |            0 | OMERO4.4       |         -35 | 2012-08-23 10:59:18.537779 | Database updated.                                                                            |             0 | OMERO4.3        |            
  3 |            0 | OMERO5.0       |         -35 | 2014-04-29 10:36:16.784758 | Database updated.                                                                            |             0 | OMERO4.4        |            
  4 |            1 | OMERO5.1       |         -35 | 2015-10-16 10:14:50.226361 | Database updated.                                                                            |             0 | OMERO5.0        |            
  5 |            1 | OMERO5.1       |         -35 | 2015-10-16 10:15:32.36701  | DB check DBEnumCheck: done for Bio-Formats revision 2c9489a987f82faf503d05d0a6dfdb3dde654ab1 |             1 | OMERO5.1        |            
  6 |            1 | OMERO5.1       |         -35 | 2015-10-16 10:15:32.386953 | DB check DBUnicodeUnitsCheck: done                                                           |             1 | OMERO5.1        |            
  7 |            1 | OMERO5.1       |         -35 | 2015-10-23 10:03:25.111779 | DB check DBEnumCheck: done for Bio-Formats revision efc7a719dd9f5221203a0b2fd956c509bb1e2081 |             1 | OMERO5.1        |            
  8 |            1 | OMERO5.1       |         -35 | 2015-10-29 12:46:57.549637 | DB check DBEnumCheck: done for Bio-Formats revision 28703d67678fdb28f1c1faa06b471301e448a9a2 |             1 | OMERO5.1        |            
  9 |            1 | OMERO5.1       |         -35 | 2015-11-20 06:49:54.402629 | DB check DBEnumCheck: done for Bio-Formats revision 518016bdaf15ca9e13cc52da32022fe52397d754 |             1 | OMERO5.1        |            
 11 |            1 | OMERO5.1       |         -35 | 2015-11-23 07:46:19.436784 | DB check DBEnumCheck: done for Bio-Formats revision 05840624ab3d1d1dca14d1ccfebabcb61c42ec27 |             1 | OMERO5.1        |            
 10 |            1 | OMERO5.1       |         -35 | 2015-11-23 08:32:35.829012 | DB check DBEnumCheck: done for Bio-Formats revision eb2fec72dff8246793242815381d877e8429461e |             1 | OMERO5.1        |            
 12 |            1 | OMERO5.1       |         -35 | 2015-11-23 08:32:35.82918  | DB check DBEnumCheck: done for Bio-Formats revision eb2fec72dff8246793242815381d877e8429461e |             1 | OMERO5.1        |            
 21 |            1 | OMERO5.1       |         -35 | 2016-02-26 09:08:41.055748 | DB check DBEnumCheck: done for Bio-Formats revision 8699c906433fd7fc9b67f70ba1455b7869cc8372 |             1 | OMERO5.1        |            
 22 |            1 | OMERO5.1       |         -35 | 2016-03-17 05:28:39.428255 | DB check DBEnumCheck: done for Bio-Formats revision 7af3195495f68bb2a485d31364d39047ca618eca |             1 | OMERO5.1        |            
 14 |            1 | OMERO5.1       |         -35 | 2016-02-23 06:44:58.614286 | DB check DBEnumCheck: done for Bio-Formats revision 56177ea88a867eb7aa8b5f6199f8160e01856424 |             1 | OMERO5.1        |            
 16 |            1 | OMERO5.1       |         -35 | 2016-02-23 06:44:58.61459  | DB check DBEnumCheck: done for Bio-Formats revision 56177ea88a867eb7aa8b5f6199f8160e01856424 |             1 | OMERO5.1        |            
 13 |            1 | OMERO5.1       |         -35 | 2016-02-23 07:04:44.528447 | DB check DBEnumCheck: done for Bio-Formats revision a4a97b4cd173674770598c50fd234df4d3551e0d |             1 | OMERO5.1        |            
 15 |            1 | OMERO5.1       |         -35 | 2016-02-23 07:04:44.528631 | DB check DBEnumCheck: done for Bio-Formats revision a4a97b4cd173674770598c50fd234df4d3551e0d |             1 | OMERO5.1        |            
 18 |            1 | OMERO5.1       |         -35 | 2016-02-23 07:04:44.528735 | DB check DBEnumCheck: done for Bio-Formats revision a4a97b4cd173674770598c50fd234df4d3551e0d |             1 | OMERO5.1        |            
 17 |            1 | OMERO5.1       |         -35 | 2016-02-25 09:07:38.346845 | DB check DBEnumCheck: done for Bio-Formats revision d667ca9105481b981d3f4fd32317f8215ccf2197 |             1 | OMERO5.1        |            
 19 |            1 | OMERO5.1       |         -35 | 2016-02-25 09:07:38.347153 | DB check DBEnumCheck: done for Bio-Formats revision d667ca9105481b981d3f4fd32317f8215ccf2197 |             1 | OMERO5.1        |            
 20 |            1 | OMERO5.1       |         -35 | 2016-02-25 09:28:36.822447 | DB check DBEnumCheck: done for Bio-Formats revision 3055807954bfd8cdb42359f752e0cfa7eb3b9f75 |             1 | OMERO5.1        |            
 23 |            0 | OMERO5.2       |         -35 | 2016-09-01 15:31:50.959663 | Database updated.                                                                            |             1 | OMERO5.1        |            
 24 |            0 | OMERO5.2       |         -35 | 2016-09-01 15:33:04.117311 | DB check DBEnumCheck: done for Bio-Formats revision 956efbe5a35a04add9e4f0c755530757177f4c9f |             0 | OMERO5.2        |            
(24 rows)

omero=# \df+ filesetentry_fileset_index_move
                                                                                                                 List of functions
 Schema |              Name               | Result data type | Argument data types |  Type   | Security | Volatility | Owner | Language |                                        Source code                                         | Description 
--------+---------------------------------+------------------+---------------------+---------+----------+------------+-------+----------+--------------------------------------------------------------------------------------------+-------------
 public | filesetentry_fileset_index_move | trigger          |                     | trigger | invoker  | volatile   | omero | plpgsql  |                                                                                           +| 
        |                                 |                  |                     |         |          |            |       |          |     DECLARE                                                                               +| 
        |                                 |                  |                     |         |          |            |       |          |       duplicate INT8;                                                                     +| 
        |                                 |                  |                     |         |          |            |       |          |     BEGIN                                                                                 +| 
        |                                 |                  |                     |         |          |            |       |          |                                                                                           +| 
        |                                 |                  |                     |         |          |            |       |          |       -- Avoids a query if the new and old values of x are the same.                      +| 
        |                                 |                  |                     |         |          |            |       |          |       IF new.fileset = old.fileset AND new.fileset_index = old.fileset_index THEN         +| 
        |                                 |                  |                     |         |          |            |       |          |           RETURN new;                                                                     +| 
        |                                 |                  |                     |         |          |            |       |          |       END IF;                                                                             +| 
        |                                 |                  |                     |         |          |            |       |          |                                                                                           +| 
        |                                 |                  |                     |         |          |            |       |          |       -- At most, there should be one duplicate                                           +| 
        |                                 |                  |                     |         |          |            |       |          |       SELECT id INTO duplicate                                                            +| 
        |                                 |                  |                     |         |          |            |       |          |         FROM filesetentry                                                                 +| 
        |                                 |                  |                     |         |          |            |       |          |        WHERE fileset = new.fileset AND fileset_index = new.fileset_index                  +| 
        |                                 |                  |                     |         |          |            |       |          |       OFFSET 0                                                                            +| 
        |                                 |                  |                     |         |          |            |       |          |        LIMIT 1;                                                                           +| 
        |                                 |                  |                     |         |          |            |       |          |                                                                                           +| 
        |                                 |                  |                     |         |          |            |       |          |       IF duplicate IS NOT NULL THEN                                                       +| 
        |                                 |                  |                     |         |          |            |       |          |           RAISE NOTICE 'Remapping filesetentry %% via (-1 - oldvalue )', duplicate;       +| 
        |                                 |                  |                     |         |          |            |       |          |           UPDATE filesetentry SET fileset_index = -1 - fileset_index WHERE id = duplicate;+| 
        |                                 |                  |                     |         |          |            |       |          |       END IF;                                                                             +| 
        |                                 |                  |                     |         |          |            |       |          |                                                                                           +| 
        |                                 |                  |                     |         |          |            |       |          |       RETURN new;                                                                         +| 
        |                                 |                  |                     |         |          |            |       |          |     END;                                                                                   | 
(1 row)
```

**Comment by mtbc** [comment]
Bah, it does, that'll need a patch script too then. Opened https://trello.com/c/2tDzi0xP/114-detect-buggy-sql-scripts accordingly.

**Comment by mtbc** [comment]
(If that's our support position then we'd need support only older scripts whose problems persist into the current DB, as in this example.)

**Comment by chris-allan** [comment]
Agreed.

**Comment by mtbc** [comment]
Thank you for the heads-up. Fixed in #4822.

**Comment by chris-allan** [comment]
Just some further feedback on this. If a database has these functions with syntax errors in them, which **any** database that has been upgraded from 4.40 will have, upgrading to or restoring into PostgreSQL 9.5 will cause **all** imports to fail. The `filesetjoblink_parent_index_move` trigger throws the following error:

```
Caused by: org.postgresql.util.PSQLException: ERROR: too many parameters specified for RAISE
  Where: compilation of PL/pgSQL function "filesetjoblink_parent_index_move" near line 19
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2270) ~[postgresql.jar:9.4]
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1998) ~[postgresql.jar:9.4]
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255) ~[postgresql.jar:9.4]
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:570) ~[postgresql.jar:9.4]
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:420) ~[postgresql.jar:9.4]
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:366) ~[postgresql.jar:9.4]
        at sun.reflect.GeneratedMethodAccessor231.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_101]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_101]
        at bitronix.tm.resource.jdbc.BaseProxyHandlerClass.invoke(BaseProxyHandlerClass.java:64) ~[btm.jar:2.1.3]
        at com.sun.proxy.$Proxy8.executeUpdate(Unknown Source) ~[na:na]
        at org.hibernate.jdbc.NonBatchingBatcher.addToBatch(NonBatchingBatcher.java:46) ~[hibernate-core.jar:na]
        at org.hibernate.persister.collection.AbstractCollectionPersister.recreate(AbstractCollectionPersister.java:1207) ~[hibernate-core.jar:na]
        ... 48 common frames omitted
```

I would say we need a 5.2 targeted fix, documentation and a release ASAP.

**Comment by chris-allan** [comment]
As per the currently [supported database servers](https://www.openmicroscopy.org/site/support/omero5.2/sysadmins/version-requirements.html#postgresql), of which PostgreSQL 9.5 is not included, this is probably not as bad as I had initially thought but is likely worth a targeted fix for 5.2.6, documentation and an announcement of some sort. An optional database patch script should not be difficult to create for the limited number of functions affected.

**Comment by mtbc** [comment]
We could circulate a patch script now without waiting for 5.2.6, for 5.2.x users I think it's probably only `filesetentry_fileset_index_move` and `filesetjoblink_parent_index_move` that need fixing.

**Comment by mtbc** [comment]
Also I think it's only those for 5.1.x users. I'll see about a patch script.

**Comment by chris-allan** [comment]
Definitely might be useful to circulate a patch script now. It definitely affects 5.2.x users. That exception above is from a fully updated 5.2.5. I fixed my two functions by using the `psql` command line tool and`\ef`. Was functional but probably not an ideal way to distribute a patch more widely.

**Comment by mtbc** [comment]
Tracking progress on https://trello.com/c/lF0aMP5I/7-db-upgrade-script-errors.

**Pull request merged**
