### PR TITLE
Python lib fixes

### PR DESCRIPTION
**Pull request by joshmoore**
Few minor fixes to the Python library (and C++ where necessary to keep symmetry):

 * [x] Translate @dominikl's recent fix to `CmdCallback` to Python and C++.
 * [x] Fix use of `bin/omero config edit` with `EDITOR=mate -w`. cc: @pwalczysko 
 * [ ] ~~Change the behavior of `client.submit` and close handles automatically where possible. See https://github.com/openmicroscopy/openmicroscopy/pull/3791#issuecomment-100892988~~

### CODE REVIEW

**Comment by joshmoore** [comment]
From devteam, it's unlikely that we'll change the behavior of `client.submit` for 5.1.2. If it's not too API polluting, happy to add `submitAndWait` and `submitAndClose` and potentially deprecate the poorly named `submit`.

**Comment by ximenesuk** [comment]
```
$ EDITOR="mate -w" omero config edit
$ VISUAL=subl omero config edit
$ omero config edit #no EDITOR or VISUAL set
```
all work as expected.

**Comment by joshmoore** [comment]
Suggested merging on:
 * https://ci.openmicroscopy.org/job/OMERO-5.1-merge-cpp/413/
 * https://ci.openmicroscopy.org/job/OMERO-5.1-merge-cpp-cmake/309/
 * https://ci.openmicroscopy.org/job/OMERO-5.1-merge-cpp-win/220/ (running)

**Comment by joshmoore** [comment]
win/220 passed. Merging.

**Pull request merged**
