### PR TITLE
Fix tooltips metadata panel

### PR DESCRIPTION
**Pull request by dominikl**
Fixes some tooltips of the right hand side metadata panel, see [Trello - Insight - Right Hand Pane tooltip changes + one other issue](https://trello.com/c/POjkfKpE/392-insight-right-hand-pane-tooltip-changes-one-other-issue).

**Test**: Check that the tooltips match the proposed ones on the trello card.

Note: When testing the last point (select files for scripts), I noticed that it doesn't work with @emilroz 's "Populate metadata" script which is deployed on eel. Reason for this is, that the scripts define the FileAnnotation parameter as list of Strings, but it should be a list of Longs instead!

### CODE REVIEW

**Comment by jburel** [comment]
``Delete rating.`` ``Add tags.`` both have ``.``. The rest does not

**Comment by jburel** [comment]
Also suggested on card ``Attachments - add attachment button - Insight: “Attach a document” - should be “Attach a file"```

**Comment by jburel** [comment]
We have in several classes. Tooltip with a dot at the end. Probably not worth the effort to review all that cc @gusferguson

**Comment by gusferguson** [comment]
@dominikl 

Still some issues with tooltips.

“Filter tags and attachments.” should be “Filter annotations by user"
“Edit the description.” should be “Edit the description”
“Edit channel.” should be “Edit channel names"

**Comment by dominikl** [comment]
Yes , there are hundreds of tooltips with a dot at the end. That'd be quite a task to find and change them all. The last commit addresses the three issues of @gusferguson 's comment. Where shall we draw the line for this PR?

**Comment by gusferguson** [comment]
@dominikl - happy to leave it at that - if the RHP is all consistent now then we can address the rest as and when we are doing changes in those areas.

**Comment by jburel** [comment]
As indicated in a previous comment,  I will not spend time removing a "." in other classes.

**Pull request merged**
