### PR TITLE
OMERO.matlab: double, long and timestamp annotations

### PR DESCRIPTION
**Pull request by sbesson**
See https://www.openmicroscopy.org/community/viewtopic.php?f=6&t=7682

This Pull Request:
- adds utillity functions to the OMERO.matlab toolbox to write and retrieve double and timestamp annotations
- modifies the training setup to link the imported fake plate to the existing screen and output the screen ID in the configuration file
- extends the coverage of the `WriteData` training function to test all of the annotation functions of the toolbox

Note: this PR is a potential rebase candidate. The `MapAnnotation` will be added on `develop` only in a subsequent PR.

### CODE REVIEW

**Comment by sbesson** [comment]
See https://ci.openmicroscopy.org/job/OMERO-5.1-merge-training/193/console

**Comment by jburel** [comment]
why did you modify the dates in the header of some files?
The rule has been to only change it when the file is modified e.g. ```omponents/tools/OmeroM/src/annotations/getAnnotations.m```

**Comment by sbesson** [comment]
All the modified functions should have their `See also` header line modified to document the new functions. Happy to revert these copyright bump if that makes more sense.

**Comment by jburel** [comment]
sorry missed the addition of "getDoubleAnnotations" so it makes sense

**Comment by jburel** [comment]
since we also have longAnnotation, it will be preferable to have a more generic method

**Comment by sbesson** [comment]
Added `long` annotation functions, remaining ones currently supported are `boolean`, `term` and `list`. Is it worth adding as part of this PR or wait until there is a need for it?

**Comment by jburel** [comment]
The other types can be certainly covered in another PR.

**Comment by sbesson** [comment]
See https://ci.openmicroscopy.org/job/OMERO-5.1-merge-training/195/console

**Comment by jburel** [comment]
minor edit otherwise could to go.

**Comment by jburel** [comment]
Everything is green. Merging.

**Comment by sbesson** [comment]
--rebased-to #3316

**Pull request merged**
