### PR TITLE
render.py: new CLI plugin for dealing with rendering settings (rebased onto develop)

### PR DESCRIPTION
**Pull request by joshmoore**
This is the same as gh-4385 but rebased onto develop.

----

See the `bin/omero render -h` output and the test for expected behavior. Primary driver for the creation of `render.py` was scripting the rendering settings along with the imports so that everything could be re-done if necessary:

```
PLATE=$(bin/omero import ... | grep Plate:)
bin/omero render copy Image:1 $PLATE
```

 * [ ] https://gist.github.com/emilroz/3858429bccd3012bf478

### CODE REVIEW

**Comment by joshmoore** [comment]
--rebased-from #4385

**Comment by jburel** [comment]
in the rest of code/doc we use rendering settings not rendering definitions

**Comment by joshmoore** [comment]
Merged in develop to fix travis.

**Comment by manics** [comment]
RFE: `omero render set Image:1234 ch1:<channelname>/<min>/<max>/<RGB> ch2:<channelname>/<min>/<max>/<RGB> ...`

**Comment by manics** [comment]
Help doesn't work:

```
$ omero render copy -h
...
TypeError: unsupported operand type(s) for %: 'tuple' and 'dict'
```

**Comment by manics** [comment]
- https://github.com/openmicroscopy/openmicroscopy/pull/4542/commits/fff2bcbae3a7d098d457d512b0aec2dca76a16f5 will let you edit the rendering settings of images
- https://github.com/openmicroscopy/openmicroscopy/pull/4542/commits/0e77ab9c0ee365b033167054d3f9d609000a0c13 fixes the help message

**Comment by manics** [comment]
+ other commits on https://github.com/openmicroscopy/openmicroscopy/pull/4542

**Comment by joshmoore** [comment]
Closing in favor of gh-4542 for the moment.

**Pull request closed without merging**
