### PR TITLE
Bio-Formats 5.3.1

### PR DESCRIPTION
**Pull request by sbesson**
This PR bumps the Bio-Formats version to 5.3.1 (and eventually supersedes https://github.com/openmicroscopy/openmicroscopy/pull/5003)

For now opened as `breaking` by pointing at the `ome.staging` repository to test the release artifacts.

### CODE REVIEW

**Comment by jburel** [comment]
Tested tonight this is looking good.

**Comment by sbesson** [comment]
Last commit should resolve the OME artifactory now Bio-Formats 5.3.1 is public.

**Comment by dominikl** [comment]
Looks good. Tested fake import, log says Bioformats 5.3.1 is used
```
2016-12-20 09:18:38,245 267        [      main] INFO          ome.formats.importer.ImportConfig - OMERO Version: 5.3.0-m6-370-ac9716c-ice36-b515
2016-12-20 09:18:38,262 284        [      main] INFO          ome.formats.importer.ImportConfig - Bioformats version: 5.3.1 revision: 8411e1cf77fe2e3ea3aca50131e2ffa37743c860 date: 16 December 2016
```
Is there something else to test?

**Comment by sbesson** [comment]
@dominikl if you want to be thorough, could you try exporting a simple multi-dimensional image into OME-TIFF, re-importing it again and checking that there is no plane missing as per [the Bio-Formats 5.3.1 bug fixes](http://lists.openmicroscopy.org.uk/pipermail/ome-users/2016-December/006300.html)

**Comment by dominikl** [comment]
Tested with a multi-Z dv image, looks alright, all z planes are still there after ex-/reimport 👍

**Pull request merged**
