### PR TITLE
FileAnnotation View button

### PR DESCRIPTION
**Pull request by dominikl**
In #3604 the view menu entry was removed, because in the scope of the OMERO.Editor removal it lost it's functionality. This PR brings the menu entry (and it's functionality) back.

screen shot 2015-04-16 at 13 27 12

Test:
Attach a file to an image; use "View" to open the file with your desktop's default application for this file type.

/cc @pwalczysko

### CODE REVIEW

**Comment by pwalczysko** [comment]
Works as expected on Mac and Windows 7.
Ready to merge (thanks for putting back this nice feature !).

**Comment by joshmoore** [comment]
Does this need Linux testing as well? cc @mtbc

**Comment by mtbc** [comment]
http://trac.openmicroscopy.org.uk/ome/ticket/12028 is the ticket. I'll give it a try ...

**Comment by mtbc** [comment]
Woah, it worked. That's a pleasant surprise!

**Pull request merged**
