### PR TITLE
Use Ubuntu 14.04 for the VBox image

### PR DESCRIPTION
**Pull request by manics**
Increase bootup time, switch to Ubuntu_64. Note this image contains PostgreSQL 9.3 and Ice 3.5.

### CODE REVIEW

**Comment by sbesson** [comment]
https://ci.openmicroscopy.org/job/OMERO-5.1-breaking-build/304/ was definitely successful with this PR. Is it worth merging since the entire infrastructure (merge, latest, breaking) has now switched to Ice 3.5?

**Comment by manics** [comment]
The thing is I'm not sure whether this PR was the reason that job worked, or if it was jsut a transient VBox error. `Debian_64`->`Ubuntu_64` change is mostly to keep things tidy as I suspect VBox treats them identically, increasing the timeout may or may not help.

**Comment by manics** [comment]
And right on cue, it's started working without https://ci.openmicroscopy.org/job/OMERO-5.1-latest/ICE=3.5,jdk=8_LATEST,label=trout/

How about keep this open for a week, if the change in timeout is not needed I'll take it out.

**Comment by manics** [comment]
--rebased-to #3554

**Pull request merged**
