### PR TITLE
OmeroCpp: Update CMake support for Ice 3.6

### PR DESCRIPTION
**Pull request by rleigh-dundee**
# What this PR does

- Overall major goal is to allow building of OmeroCpp with Ice 3.6
- Upgrade to CMake 3.2 to match OME Files, allowing the use of imported targets and the dropping of the special-casing of the scripts we've embedded from upstream (FindIce)
- Drop GNUInstallDirs script; it's long been supported by all CMake versions we use
- Update FindIce to support Ice 3.6, as well as imported targets with any Ice release
- Use Ice imported targets

# Testing this PR

On Unix:

Build as normal.  It should continue to work as usual with Ice 3.5 or Ice 3.6.

On Windows:

With Python 2.7/VS2013 or 15 and Ice 3.6.2:

```
cmake -G Ninja /path/to/openmicroscopy
cmake --build .
```

It will build up until the point it tries to link omero-ice, at which point it will fail due to exceeding the maximum symbol count.  As for Ice 3.5, we'll have to look at a way to reduce the count or split the libraries further.  This will need tackling in a followup PR.  This PR adds the build support as a prerequisite to being able to do that work.

# Related reading

https://gitlab.kitware.com/cmake/cmake/merge_requests/17
https://gitlab.kitware.com/cmake/cmake/merge_requests/19
https://forums.zeroc.com/discussion/46421/slice2cpp-and-lnk1189-with-ice-3-6-2-and-vs2013-or-2015

### CODE REVIEW

**Comment by rleigh-dundee** [comment]
Green in:

- https://ci.openmicroscopy.org/job/OMERO-DEV-merge-cpp-win/235/
- https://ci.openmicroscopy.org/job/OMERO-DEV-merge-cpp/250/
- https://ci.openmicroscopy.org/job/OMERO-DEV-merge-cpp-cmake/266/

This demonstrates there are no regressions with any platforms for Ice 3.5.

**Comment by joshmoore** [comment]
Looks good, thanks, @rleigh-dundee. Was any intervention needed in the jobs to get the builds to pass (e.g. b234 -> b235)?

**Comment by rleigh-dundee** [comment]
@joshmoore Yes, I had to upgrade cmake from 3.0.1.  I thought I'd already done it months back, but it's because we never used these nodes for bioformats in the last year--they are omerocpp only and hadn't been touched since 2014.

**Comment by rleigh-dundee** [comment]
@joshmoore The upstream PRs are now reviewed, tested and merged, BTW.

**Comment by joshmoore** [comment]
Very much appreciate all the dirty work. In general, do try to leave a record of OS-level changes somewhere (a sysadmin trello card and/or gdoc). That's probably the best we can do until we have proper config-managed systems for all of this.

**Comment by rleigh-dundee** [comment]
@joshmoore The changes were recorded on the google doc for the ome-w2008r2-01/02 systems.

**Comment by joshmoore** [comment]
Excellent, thanks. Then maybe just also mention in the PR next time so we can tie everything together. Cheers.

**Pull request merged**
