### PR TITLE
Test batch annotate file

### PR DESCRIPTION
**Pull request by will-moore**
# What this PR does

Adds test for https://github.com/ome/omero-py/pull/127 which was only found by manual testing.
To test"
 - check new test is green

### CODE REVIEW

**Comment by will-moore** [comment]
Travis failed with
```
/infra/utils: line 29: /opt/omero/server/venv3/bin/activate: No such file or directory
OCI runtime exec failed: exec failed: container_linux.go:348: starting container process
caused "exec: \"/opt/omero/server/venv3/bin/python\": stat /opt/omero/server/venv3/bin/python:
no such file or directory": unknown
```

**Comment by joshmoore** [comment]
This will need my extracted commit & a travis re-run.

**Comment by will-moore** [comment]
Test is passing at https://py3-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/67/testReport/OmeroWeb.test.integration.test_annotate/TestFileAnnotations/

**Comment by joshmoore** [comment]
:+1:

**Pull request merged**
