### PR TITLE
Browse project

### PR DESCRIPTION
**Pull request by jburel**
Do not browse project with empty datasets.

see https://trac.openmicroscopy.org/ome/ticket/11952

To test
 * Select a project containing empty datasets.
 * Make sure the browse action is not enabled.

### CODE REVIEW

**Comment by pwalczysko** [comment]
Sorry, I am not sure I understand here - does this mean I will not be able to manage my P/Ds in Insight just because the datasets happen to be empty ? How would I delete them then, or how would I fill them in ?

**Comment by pwalczysko** [comment]
Aha, maybe it is just the Browse button disabled. I was horrified that I would not be able to expand a Project in the tree if Datasets are empty.

**Comment by jburel** [comment]
Just the browse button not enabled if empty dataset

**Comment by mtbc** [comment]
Works well, good to merge.

**Comment by jburel** [comment]
--no-rebase

**Pull request merged**
