### PR TITLE
Use default perms when creating var/

### PR DESCRIPTION
**Pull request by manics**
- https://trello.com/c/xDMnFnPd/498-fix-omero-web-var-permissions
- https://github.com/openmicroscopy/ome-documentation/pull/1210

Testing: server.zip should include a `var` directory. If it's deleted then when a new `var/` is created it should always have the default umask, it shouldn't matter whether you run `omero admin` or `omero web` first.

### CODE REVIEW

**Comment by joshmoore** [comment]
In general, this is as we discussed a fine change, since `etc/` is not being protected and therefore we should handle this via documentation (incl. the upgrade. cc: @hflynn). Holding off here until we've finished the doc discussion in 1210.

**Comment by manics** [comment]
This is going to conflict with https://github.com/openmicroscopy/openmicroscopy/pull/3380

**Comment by joshmoore** [comment]
Admin first: (OS2)
```
# jamoore@lifesci-30450:/tmp$ OS2/OMERO.server-5.1.1-399-3afd8dc-ice35-b505/bin/omero admin start
Creating /private/tmp/OS2/OMERO.server-5.1.1-399-3afd8dc-ice35-b505/var/master
Initializing /private/tmp/OS2/OMERO.server-5.1.1-399-3afd8dc-ice35-b505/var/log
Creating /private/tmp/OS2/OMERO.server-5.1.1-399-3afd8dc-ice35-b505/var/registry
```

Web first: (OS3)
```
...a bunch of 'copying' lines...
```

Var directories match:
```
# jamoore@lifesci-30450:/tmp$ ls -ltrad OS{2,3}/*/var
drwxr-xr-x@ 5 jamoore  wheel  170 May 19 14:04 OS2/OMERO.server-5.1.1-399-3afd8dc-ice35-b505/var
drwxr-xr-x@ 4 jamoore  wheel  136 May 19 14:06 OS3/OMERO.server-5.1.1-399-3afd8dc-ice35-b505/var
```

Subdirs match (where they overlap) and are generally sane:
```
# jamoore@lifesci-30450:/tmp$ ls -ltrad OS{2,3}/*/var/*
drwxr-xr-x  14 jamoore  wheel  476 May 19 14:04 OS2/OMERO.server-5.1.1-399-3afd8dc-ice35-b505/var/registry
drwxr-xr-x   6 jamoore  wheel  204 May 19 14:04 OS2/OMERO.server-5.1.1-399-3afd8dc-ice35-b505/var/master
drwxr-xr-x  11 jamoore  wheel  374 May 19 14:05 OS2/OMERO.server-5.1.1-399-3afd8dc-ice35-b505/var/log
drwxr-xr-x   4 jamoore  wheel  136 May 19 14:06 OS3/OMERO.server-5.1.1-399-3afd8dc-ice35-b505/var/log
-rw-r--r--   1 jamoore  wheel    6 May 19 14:06 OS3/OMERO.server-5.1.1-399-3afd8dc-ice35-b505/var/django.pid
```

:+1:

**Comment by joshmoore** [comment]
Note: results from repeating with a different umask:
```
# jamoore@lifesci-30450:/tmp$ umask 0002
...
# jamoore@lifesci-30450:/tmp$ ls -ltrad OS{4,5}/*/var
drwxr-xr-x@ 5 jamoore  wheel  170 May 19 14:10 OS4/OMERO.server-5.1.1-399-3afd8dc-ice35-b505/var
drwxr-xr-x@ 3 jamoore  wheel  102 May 19 14:11 OS5/OMERO.server-5.1.1-399-3afd8dc-ice35-b505/var
# jamoore@lifesci-30450:/tmp$ ls -ltrad OS{4,5}/*/var/*
drwxrwxr-x  14 jamoore  wheel  476 May 19 14:10 OS4/OMERO.server-5.1.1-399-3afd8dc-ice35-b505/var/registry
drwxrwxr-x   6 jamoore  wheel  204 May 19 14:10 OS4/OMERO.server-5.1.1-399-3afd8dc-ice35-b505/var/master
drwxrwxr-x  11 jamoore  wheel  374 May 19 14:10 OS4/OMERO.server-5.1.1-399-3afd8dc-ice35-b505/var/log
drwxrwxr-x   4 jamoore  wheel  136 May 19 14:11 OS5/OMERO.server-5.1.1-399-3afd8dc-ice35-b505/var/log
```

i.e. the unzip does not respect the umask.

**Pull request merged**
