### PR TITLE
Travis: use oraclejdk8

### PR DESCRIPTION
**Pull request by sbesson**
This JDK version seems to alleviate the memory issues our Travis build have been suffering from in the last few days. See https://travis-ci.org/sbesson/openmicroscopy/builds for the local tests, each build having built relaunched a few times.

/cc @aleksandra-tarkowska @joshmoore @jburel

### CODE REVIEW

**Comment by sbesson** [comment]
Relaunched twice since the initial success and Travis is still green. Thoughts about merging this and propagating to the other PRs?

**Comment by aleksandra-tarkowska** [comment]
go for

**Comment by joshmoore** [comment]
Merging to relaunch all failing travis builds.

**Comment by joshmoore** [comment]
Sadly the merge build of this into develop failed : https://travis-ci.org/openmicroscopy/openmicroscopy/jobs/107956694

**Comment by aleksandra-tarkowska** [comment]
One of my PRs still failing https://travis-ci.org/openmicroscopy/openmicroscopy/builds/107957488

**Comment by aleksandra-tarkowska** [comment]
merging develop resolved https://github.com/openmicroscopy/openmicroscopy/pull/4447

**Comment by aleksandra-tarkowska** [comment]
Seems the same issue came back, travis failing again https://travis-ci.org/openmicroscopy/openmicroscopy/jobs/109659037

**Pull request merged**
