### PR TITLE
DB changes, incl. move Pixels.params to Image.series

### PR DESCRIPTION
**Pull request by mtbc**
- new ≥0 series property on images, populated for new imports and for previously imported images
- drop params columns after checking that there is nothing odd in them, e.g.,
  - extra keys
  - wrong target filename
- prevent original file repositories from having their mimetype changed

--no-rebase

### CODE REVIEW

**Comment by mtbc** [comment]
Breaking label please.

**Comment by joshmoore** [comment]
Changes and tests (e.g. [py#192](https://ci.openmicroscopy.org/view/Failing/job/OMERO-5.1-breaking-integration-python/192/testReport/)) look good. Removing breaking.

**Comment by joshmoore** [comment]
@mtbc : this can't be merged anymore.

**Comment by mtbc** [comment]
Images should still work as before, including both old imports and new ones, and MIFs and plates.

**Comment by pwalczysko** [comment]
All works fine here. Sorry for the original scare, I was connected to a wrong port. Also the imports went fine (of plates and MIFs) and viewing was fine. There is couple of broken plates (``Experiment.exp``) in trout/merge user-4, but so there is at least one such plate in trout/latest. This might be a remnant of me testing Qa and intentionally trying to import broken plates.

**Comment by mtbc** [comment]
Thank you, @pwalczysko. (The latest commit won't invalidate your testing today, it is just to fix OMERO-5.1-merge-deploy-win.)

**Comment by ximenesuk** [comment]
Does this need further review or is that build passing sufficient?

**Comment by mtbc** [comment]
As I changed the upgrade script, I suppose somebody should again test it on Mac or Linux: just make sure that a database with imported images (including MIFs and plates) upgrades fine to patch 20, that the images are still viewable afterward.

**Comment by ximenesuk** [comment]
Running the upgrade (19->20) on a db with plates and MIFs went fine, images were still accessible via the web on the new server.

**Comment by mtbc** [comment]
Great, thank you. Merging this PR is expected to fix OMERO-5.1-breaking-upgrade.

**Comment by mtbc** [comment]
Yes, job is now green. :+1:

**Pull request merged**
