### PR TITLE
OMEROIJ_Bioformats_dependency_check

### PR DESCRIPTION
**Pull request by bramalingam**
ref : https://trac.openmicroscopy.org/ome/ticket/12925

Testing isntructions:

1) Add "OMEROIJ" plugin and bioformats_package.jar or loci-tools.jar to the plugins folder of imageJ.
2) open imageJ , "Plugins-->OMERO-->Connect to OMERO". This Should throw up the Insight login screen.

Now, rename the bioformats_package.jar (within the plugins folder) with something like,
bioformats_package-1.jar or biformats_package 1.jar or etc (concatenate any string to the name of the jar post bioformats_package or loci-tools with *.jar) and repeat the workflow specified above.

You should still get the Insight login screen.

Note : (when any string extension is added to bioformats_package or loci-tools) Without this PR the above workflow will throw a warning window  saying: can't find bioformats_package or loci-tools within the plugins folder and the login screen will not appear .

### CODE REVIEW

**Comment by jburel** [comment]
It works.
It is probably better to use the method ```removeExtension``` from ```FileNameUtils```.

**Comment by mtbc** [comment]
Does this need relisting?

**Comment by jburel** [comment]
@mtbc: my bad, I forgot to review it while @bramalingam was away. No need to relist it.

**Comment by jburel** [comment]
Retested. All working as expected after the suggested change. Merging

**Pull request merged**
