### PR TITLE
Fixed potential NPE

### PR DESCRIPTION
**Pull request by dominikl**
See [Ticket 12547](https://trac.openmicroscopy.org.uk/ome/ticket/12547)

I don't know how to test this; but a code review should be sufficient (it's just an additional check for `null`, and `password` is the only Object which could trigger a `NullPointerException` in this `toString()` method)

### CODE REVIEW

**Comment by mtbc** [comment]
Code change looks sensible. :+1: Don't know if you want to log anything if it *is* `null`?

**Comment by jburel** [comment]
I won't do anything. I need to find work I did for connection using only session id. 
we might have a ``` null``` password in that case.

**Comment by joshmoore** [comment]
Guess the question is what it means for the password to be null. If no one knows, logging at warn might make sense.

**Comment by jburel** [comment]
There is no ref to logger at that level, a ref will have to be specified  or it will have to be registered when the class is initialized.

**Comment by joshmoore** [comment]
Fair enough. Unless there's a precedent of adding "# TODO on refactoring", I'd say let's merge and move on.

**Comment by mtbc** [comment]
Fine with me.

**Pull request merged**
