### PR TITLE
improve graphs error detection for dry runs

### PR DESCRIPTION
**Pull request by mtbc**
In https://github.com/openmicroscopy/openmicroscopy/pull/3879#issuecomment-114064985 @will-moore noted that with a graph operation's `dryRun=True` he wasn't seeing an error that he would have if he'd gone ahead with the operation for real. This PR should fix a high fraction of such situations and also reduce the incidence of the confusing "cannot null" exceptions.

### CODE REVIEW

**Comment by ximenesuk** [comment]
See: https://ci.openmicroscopy.org/view/Failing/job/OMERO-5.1-merge-integration-python/502/testReport/ and https://ci.openmicroscopy.org/view/Failing/job/OMERO-5.1-merge-integration-java/499/testngreports/

With this PR:
```
$ omero delete Image/RenderingDef:21 --dry-run
Using session 030f8ff5-2b0c-4380-ace9-33af7d253e3b (user-0@localhost:4064). Idle timeout: 10 min. Current group: pg-0
omero.cmd.Delete2 Image/RenderingDef 21... failed: 'graph-fail'
failed: cannot null ome.model.display.ChannelBinding.renderingDef
```
and without this PR:
```
$ omero delete Image/RenderingDef:21 --dry-run
Using session 7e411681-7959-4db5-9db6-461d48a8c79f (user-0@localhost:4064). Idle timeout: 10 min. Current group: pg-0
omero.cmd.Delete2 Image/RenderingDef 21... ok
```

I don't know if this is improved error detection with or without `--dry-run` or a chnage in expected behaviour.

**Comment by mtbc** [comment]
--exclude for now then until potential problems can be investigated, thank you!

**Comment by mtbc** [comment]
It was a bug, thank you @ximenesuk. Now ought to be fixed.

**Comment by ximenesuk** [comment]
SkipHead commands now seems to be working okay, locally and according to integration tests.

**Comment by ximenesuk** [comment]
I'm still seeing differences in reporting between the dry run and the operation. 

In this case reported by @will-moore (splitting a MIF) the response is now okay:
```
ls30778:openmicroscopy colin$ omero chown 5  Image:286 --report --dry-run
Using session 41148f03-682a-4468-9f62-5cfe02b44d4b (user-1@localhost:4064). Idle timeout: 10 min. Current group: private-1
omero.cmd.Chown2 Image 286... failed: 'graph-fail'
failed: within Fileset[156] may not give Image[286] while Image[287] remains
Steps: 3
Elapsed time: 0.495 secs.
Flags: [FAILURE, CANCELLED]
ls30778:openmicroscopy colin$ omero chown 5  Image:286 --report
Using session 41148f03-682a-4468-9f62-5cfe02b44d4b (user-1@localhost:4064). Idle timeout: 10 min. Current group: private-1
omero.cmd.Chown2 Image 286... failed: 'graph-fail'
failed: within Fileset[156] may not give Image[286] while Image[287] remains
Steps: 5
Elapsed time: 0.32 secs.
Flags: [FAILURE, CANCELLED]
```

However, if the failure is because of permissions, I do get different results:
```
ls30778:openmicroscopy colin$ omero chown 5  Image:286,287 --report --dry-run
Using session 41148f03-682a-4468-9f62-5cfe02b44d4b (user-1@localhost:4064). Idle timeout: 10 min. Current group: private-1
omero.cmd.Chown2 Image 286,287... ok
Steps: 3
Elapsed time: 1.621 secs.
Flags: []
Included objects
  Detector:422,423
  DetectorSettings:422,423
  ...
  UploadJob:642
  StatsInfo:472,473
ls30778:openmicroscopy colin$ omero chown 5  Image:286,287 --report
Using session 41148f03-682a-4468-9f62-5cfe02b44d4b (user-1@localhost:4064). Idle timeout: 10 min. Current group: private-1
omero.cmd.Chown2 Image 286,287... failed: 'graph-fail'
failed: cannot process ome.model.fs.FilesetJobLink[230]: user 5 is not a member of group 7
Steps: 5
Elapsed time: 0.445 secs.
Flags: [FAILURE, CANCELLED]
```

**Comment by mtbc** [comment]
Thank you. I would have expected '--dry-run' to catch that error so I had better investigate.

**Comment by mtbc** [comment]
Yes, that's another check that we can avoid bypassing. Now fixed. :smiley:

**Comment by ximenesuk** [comment]
The issue cited above is now fixed.

There are still oddities of reporting but I'm not sure how fixable these are. For instance, this SkipHead delete failure message is misleading given I'm trying to delete the rendering defs of a single image in a MIF:
```
ls30778:openmicroscopy colin$ omero delete Image/RenderingDef:287 --dry-run
Using session ad02e25b-34b0-40e9-934d-a901984bfe94 (user-1@localhost:4064). Idle timeout: 10 min. Current group: private-1
omero.cmd.Delete2 Image/RenderingDef 287... failed: 'graph-fail'
failed: within Fileset[156] may not delete Image[287] while Image[286] remains
```
Or should I be able to delete this image's rendering defs?

**Comment by mtbc** [comment]
That's peculiar. I'd better investigate again. This is your own MIF and rendering settings?

**Comment by ximenesuk** [comment]
Yes, local two-image MIF with default rendering settings as imported by data owner.

**Comment by mtbc** [comment]
Confirmed. I suspect that it isn't actually a regression but I will look at fixing it within this PR.

**Comment by mtbc** [comment]
The issue here was probably again just the light testing of `SkipHead` in general, the issue you find has probably been around throughout 5.1. Thank you for the thorough testing! Fix now pushed.

**Comment by ximenesuk** [comment]
This looks fine, or at least I have run out of ways of breaking it! I'd say good to merge.

**Pull request merged**
