### PR TITLE
CLI usage warnings

### PR DESCRIPTION
**Pull request by ximenesuk**
This PR adds a couple of warnings and clarifications to CLI usage `chown` and `group perms`.

/cc @pwalczysko @mtbc @joshmoore

### CODE REVIEW

**Comment by joshmoore** [comment]
(relaunched travis after HDF5 unit test failure)

**Comment by pwalczysko** [comment]
from ``bin/omero group perms -h``:

``In private groups, only group and system administrators will be able...``
Replace ``group ... administrators`` with ``group owners and system administrators`` (we do not have the term group administrators anywhere else in user facing UIs or docs, instead we have ``Group owner``

**Comment by pwalczysko** [comment]
One wording correction https://github.com/openmicroscopy/openmicroscopy/pull/3991#issuecomment-125164431 otherwise fine.

**Comment by ximenesuk** [comment]
Fixed older usage.

**Comment by joshmoore** [comment]
:+1: I'd propose to merge once travis is green.

**Comment by mtbc** [comment]
I concur.

**Pull request merged**
