### PR TITLE
Add requirements-py26-iis.txt

### PR DESCRIPTION
**Pull request by joshmoore**
For discussion with https://github.com/openmicroscopy/ome-documentation/pull/1322

### CODE REVIEW

**Comment by aleksandra-tarkowska** [comment]
We do not have iis file https://github.com/openmicroscopy/openmicroscopy/tree/develop/components/tools/OmeroWeb ?

**Comment by sbesson** [comment]
Works for me. We can decide to use this file in the documentation if we want. @aleksandra-tarkowska: thoughts ?

**Comment by aleksandra-tarkowska** [comment]
I am fine with that, @hflynn is already handling that in the in https://github.com/openmicroscopy/ome-documentation/pull/1322

**Comment by aleksandra-tarkowska** [comment]
Sorry was distructed by something else. Do we need that file at all?

https://github.com/openmicroscopy/ome-documentation/blob/develop/omero/sysadmins/windows/install-web.txt#L37

**Pull request merged**
