### PR TITLE
add a "log" command to RawAccessRequest

### PR DESCRIPTION
**Pull request by mtbc**
# What this PR does

Allow administrative users' clients to add messages to server logs.

# Testing this PR

This is probably easiest from a Python script, e.g.,

```python
from omero.callbacks import CmdCallbackI
from omero.gateway import BlitzGateway
from omero.grid import RawAccessRequest

conn = BlitzGateway('user-6', 'ome', host='eel.openmicroscopy.org', port=4064)
conn.connect()

req = RawAccessRequest(command='log', path='warn', repoUuid='ScriptRepo',
                       args=['Hello from Python!'])

prx = conn.c.sf.submit(req)
CmdCallbackI(conn.c, prx).loop(100, 100)

conn._closeSession()
```

then take a look in eel's `/opt/hudson/workspace/OMERO-DEV-merge-deploy/src/dist/var/log/Blitz-0.log` for your message. You may need to adjust `etc/logback.xml` if you wish test log levels that are "lighter" than those ordinarily logged.

# Related reading

https://trello.com/c/0Vyj8lkE/55-omeroserver-omeroweb-test-error
https://trello.com/c/68WQAvXr/51-allow-creating-entries-in-server-logs

### CODE REVIEW

**Comment by waxenegger** [comment]
That worked nicely.

```
 2017-10-12 14:47:24,709 INFO  [        ome.services.util.ServiceHandler] (2-thread-4)  Executor.doWork -- omero.cmd.HandleI.run[f4af04fd-b0b6-42bc-891f-525b03056d7f/IHandle6e14e234-5647-448b-aa7a-ae2f9427c878, ome.services.blitz.repo.RawAccessRequestI@261e563f]
2017-10-12 14:47:24,709 INFO  [        ome.services.util.ServiceHandler] (2-thread-4)  Args:	[null, InternalSF@2071153776]
2017-10-12 14:47:24,729 INFO  [         ome.security.basic.EventHandler] (2-thread-4)  Auth:	user=7,group=9,event=2026263(User),sess=f4af04fd-b0b6-42bc-891f-525b03056d7f
2017-10-12 14:47:24,731 INFO  [        ome.services.blitz.fire.Registry] (2-thread-4) Found 3 repo(s) : [InternalRepository-ScriptRepo -t -e 1.1:tcp -h eel.openmicroscopy.org -p 36598, InternalRepository-2f380e85-ec59-4f51-99ea-3901ad7e359d -t -e 1.1:tcp -h eel.openmicroscopy.org -p 36598, InternalRepository-a5a2b4b3-d146-4ccc-98fa-7353a1ba023b -t -e 1.1:tcp -h eel.openmicroscopy.org -p 36598]
2017-10-12 14:47:24,732 ERROR [o.s.blitz.repo.RawAccessRequestI log cmd] (.Server-24) Testing PR #5538!
2017-10-12 14:47:24,732 INFO  [                 org.perf4j.TimingLogger] (2-thread-4) start[1507816044731] time[0] tag[omero.request.step.0]
2017-10-12 14:47:24,732 INFO  [                 org.perf4j.TimingLogger] (2-thread-4) start[1507816044729] time[2] tag[omero.request]
2017-10-12 14:47:24,769 INFO  [                 org.perf4j.TimingLogger] (2-thread-4) start[1507816044709] time[59] tag[omero.call.success.omero.cmd.HandleI$1.doWork]
2017-10-12 14:47:24,769 INFO  [        ome.services.util.ServiceHandler] (2-thread-4)  Rslt:	(omero.cmd.OK@d257e44)
```

**Comment by joshmoore** [comment]
re: 

```
prx = conn.c.sf.submit(req)
CmdCallbackI(conn.c, prx).loop(100, 100)
```

Note https://github.com/openmicroscopy/openmicroscopy/blob/develop/components/tools/OmeroPy/src/omero/clients.py#L892 which would simplify this to `cb = conn.c.submit(req)`

Also: depending on potential other uses of the enum, I'm not sure it's worth adding to Ice.

**Comment by dominikl** [comment]
Hm, is any user allowed to do that or admin only?

**Comment by joshmoore** [comment]
`RawAccess` is admin-only.

**Comment by mtbc** [comment]
I think it's worth adding the enum as it makes it easier to write clients where the compiler checks you are passing a legal value so you can be sure you are providing an recognized one. (Trying to eliminate problems from mismatches here is why this PR's server code uses the same enum.) It also generalizes to anything else that might do anything log-related and comes at little cost.

**Comment by mtbc** [comment]
See discussion at https://github.com/mtbc/openmicroscopy/pull/16 for further context.

**Comment by joshmoore** [comment]
> It also generalizes to anything else that might do anything log-related and comes at little cost.

Yes, but in the `Repositories.ice` namespace. See the mess I made with `Collections.ice` in a previous life :)

> the repo argument

Unfortunate, but probably one that's easier to live with.

> I'd originally thought maybe just an IAdmin method because it seems odd to wheel in a whole new async class for a single operation that is both fast and trivial.

Yes, if it weren't for the overhead of Ice symbols, I'd likely agree with you. I'm trying to avoid those at the moment.

----

I've been hemming and hawing over the above for sometime. Sorry for keeping you waiting. If we need to get this into our integration branch, it's certainly a nice to have, and in a post-Ice world, I wouldn't have had any issues.

**Comment by mtbc** [comment]
> but in the `Repositories.ice` namespace

Good point, it's an awkward file to define it in. Shame to lose the enum because we don't have a good place to put it! Not sure how subsequently breaking it would be to leave it in `omero::grid::*` while moving it to a different source file but I'd guess maybe enough especially if people quietly do strange things.

> in a post-Ice world

Could certainly make raw access requests an early candidate for porting to microservices post-training. Also happy to learn more about where/how we need to avoid Ice symbols.

If this PR causes more trouble than it fixes then not upset if better to close than merge.

**Comment by joshmoore** [comment]
* Perhaps move to `Constants.ice` ?
 * re: moving to microservice. Nice idea. Perhaps we put put "deprecated" on all the Ice definitions so we can get rid of them ASAP.

**Review by joshmoore — APPROVED** [review]
The modifications to the code make me feel much better about this. Thank you. https://web-proxy.openmicroscopy.org/next-ci/job/OMERO-test-integration/lastCompletedBuild/testReport/OmeroPy.test.integration.clitest.test_admin/TestAdmin/test_log/ is nicely green. (It will need a `@local_only` tag to function as is. A `RawAccess` command for parsing the log would be another option.)

**Pull request merged**
