### PR TITLE
ticket 13018

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
This PR fixes access to image when share is inactive or expired.

To test:
 - log in as ``user-1`` and share image with ``user-5``
 - log in as ``user-5`` check if image is visible in the viewer, copy the image URL ``http://host/webclient/img_detail/IMAGE_ID/``
 - log in back to ``user-1`` and deactivate share (uncheck enable in share edit form)
 - log in back to ``user-5`` and check if share is greyed out, you should also not being able to click on it. Go to the URL ``http://host/webclient/img_detail/IMAGE_ID/``, you should get 404
 - as it is impossible to create expired share check if image in ``share 17754`` (owned by ``user-1``) is not visible by ``user-5``

cc: @will-moore

### CODE REVIEW

**Comment by will-moore** [comment]
Disabling of the viewer works fine (get 404). However, when I try to expand the newly disabled share in the tree, I get:
```
Traceback (most recent call last):

  File "/opt/hudson/workspace/OMERO-5.1-merge-deploy/src/dist/lib/python/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/opt/hudson/workspace/OMERO-5.1-merge-deploy/src/dist/lib/python/omeroweb/decorators.py", line 477, in wrapped
    retval = f(request, *args, **kwargs)

  File "/opt/hudson/workspace/OMERO-5.1-merge-deploy/src/dist/lib/python/omeroweb/decorators.py", line 527, in wrapper
    context = f(request, *args, **kwargs)

  File "/opt/hudson/workspace/OMERO-5.1-merge-deploy/src/dist/lib/python/omeroweb/webclient/views.py", line 2787, in load_public
    controller = BaseShare(conn, share_id)

  File "/opt/hudson/workspace/OMERO-5.1-merge-deploy/src/dist/lib/python/omeroweb/webclient/controller/share.py", line 73, in __init__
    " information." % self.share.getShareType())

AttributeError: Share is not active and cannot be visible. Please contact the user you think might own this share for more information.
```

When I try to expand the expired share 17754 in the tree, I get a different exception:
```
  File "/opt/hudson/workspace/OMERO-5.1-merge-deploy/src/dist/lib/python/omeroweb/webclient/views.py", line 2788, in load_public
    controller.loadShareContent()

  File "/opt/hudson/workspace/OMERO-5.1-merge-deploy/src/dist/lib/python/omeroweb/webclient/controller/share.py", line 201, in loadShareContent
    for ex in content:

  File "/opt/hudson/workspace/OMERO-5.1-merge-deploy/src/dist/lib/python/omeroweb/webclient/webclient_gateway.py", line 1690, in getContents
    obj = omero.gateway.ImageWrapper(self, e)

  File "/opt/hudson/workspace/OMERO-5.1-merge-deploy/src/dist/lib/python/omero/gateway/__init__.py", line 203, in __init__
    self._conn.SERVICE_OPTS)

  File "/opt/hudson/workspace/OMERO-5.1-merge-deploy/src/dist/lib/python/omero/gateway/__init__.py", line 4136, in __call__
    return self.handle_exception(e, *args, **kwargs)

  File "/opt/hudson/workspace/OMERO-5.1-merge-deploy/src/dist/lib/python/omeroweb/webclient/webclient_gateway.py", line 2106, in handle_exception
    e, *args, **kwargs)

  File "/opt/hudson/workspace/OMERO-5.1-merge-deploy/src/dist/lib/python/omero/gateway/__init__.py", line 4133, in __call__
    return self.f(*args, **kwargs)

  File "/opt/hudson/workspace/OMERO-5.1-merge-deploy/src/dist/lib/python/omero_api_IQuery_ice.py", line 142, in get
    return _M_omero.api.IQuery._op_get.invoke(self, ((klass, id), _ctx))

SecurityViolation: exception ::omero::SecurityViolation
```

**Comment by aleksandra-tarkowska** [comment]
@will-moore now toggling node should be disabled along side with selecting disabled share

**Comment by aleksandra-tarkowska** [comment]
@will-moore the difference between these two is expected. Expired share means that you cannot join expired session, while disabling share is a different flag.

**Comment by pwalczysko** [comment]
Went through the whole workflow here. This includes also the expanding of the two shares which did not work for Will. Now the expansion of the shares (the newly disabled one as well as the old one) is not possible at all, as expected.

All seems good here.

**Comment by pwalczysko** [comment]
Good to merge

**Comment by sbesson** [comment]
Thanks

**Comment by joshmoore** [comment]
@aleksandra-tarkowska : why is this marked `no-rebase`? What's the plan for 5.2?

**Comment by aleksandra-tarkowska** [comment]
@joshmoore jstree incompatibility. I am working on the new PR and will cherry-pick what is possible.

**Comment by joshmoore** [comment]
Sounds good. (But for readers, `--no-rebase` is confusing)

**Comment by mtbc** [comment]
Note the tag still works if you write stuff after it, "--no-rebase because the aliens are coming" or whatever.

**Comment by aleksandra-tarkowska** [comment]
--rebased-to #4208

**Pull request merged**
