### PR TITLE
Roi table improvements

### PR DESCRIPTION
**Pull request by dominikl**
Some more improvements/bug fixes with respect to ROI Folders handling, see [Trello - ROI Folders Insight Bugs/RFEs](https://trello.com/c/XUI38KAp/27-roi-folders-insight-bugs-rfes).

* Enable Drag/Drop only on the first column of the ROI table
* If a Folder name matches the filter expression, don't filter the sub folders, always show them.

### CODE REVIEW

**Comment by gusferguson** [comment]
@dominikl 
Tested using regions-omero.docker.openmicroscopy.org DB: user-14:
OMERO.insight-5.3.0-m2-344-3a2679e-ice35-b132-mac
and
OMERO.insight-5.3.0-m2-344-3a2679e-ice35-b132-win

Behaves as expected.
Note - Drag and Drop does not work for moving ROIs/folders inside folders —> orphaned - presume this is intended behaviour.
Filtering works as expected.
Good to merge.

**Comment by gusferguson** [comment]
@dominikl @pwalczysko 

Just noticed that filtering is disabled if Show All ROIs is checked.
This is contrary to the workflow described in Petr's scenario https://www.openmicroscopy.org/private/ome-internal/testing_scenarios/ROIFolders.html Point 5.

I think you should be able to filter when Show All ROIs is checked - i.e. as per scenario.

id- 18 20110209_region1_1505_atp zvi

**Comment by gusferguson** [comment]
@dominikl @pwalczysko 

Sorry - I see that I have misunderstood the scenario. The behaviour is the same as the  scenario.

Probably better to leave as it is and I will see if I can suggest a clarification for the scenario.

**Comment by dominikl** [comment]
DnD moving of ROIs and folders inside folders should work, too. They should only become orphaned when dropped into the empty space of the ROI table. I'll check that again.

**Comment by gusferguson** [comment]
@dominikl - you are correct - it does work - I was not dragging far enough. Sorry!

Good to merge.

**Pull request merged**
