### PR TITLE
Batch remove tags

### PR DESCRIPTION
**Pull request by will-moore**
Fixes https://trac.openmicroscopy.org/ome/ticket/12665
To test:
 - Select 2 or more objects and add Tags dialog.
 - Any tags that are on all selected objects should be shown in right 'selected' column.
 - E.g. try adding a tag to all selected objects. When the dialog is opened again this Tag should be in the right column.
 - Removing a Tag from the right column should remove it from all selected objects.

Permissions test (fails in Insight: https://trello.com/c/43AhivR0/325-insight-tag-dialog-for-admins)
 - In the case where an Admin is removing tags using the Tag dialog, he/she should not be able to remove Tags that another user has added.
 - Tags should only show up in the right column if Admin themselves has added that Tag to all selected objects.
 - If Admin has added Tag to all selected objects and Tag shows up in right column, removing it should not remove that Tag from selected objects where linked by other users. Is that clear!?

--no-rebase

### CODE REVIEW

**Comment by pwalczysko** [comment]
@will-moore advised that he found a bug. Holding up the testing.

**Comment by gusferguson** [comment]
@will-moore 

Tested using  https://trout.openmicroscopy.org/merge/webclient/ Safari - trout user-3 read-only-1 and user-6

Behaves as expected when owner of tags dealing with batch tagging/removal.
Behaves as described when admin doing batch tagging/removal.
I would note however that the batch tag removal is inconsistent with the individual tag removal - Admin can remove other user’s tags on individual images. I presume it is handled differently to prevent Admin inadvertently deleting tags added by others along with ones added by admin.
Small note - the yellow tooltip style alert to completion of actions is pretty incongruous - have put up Trello card for discussion of this in UX > Inbox https://trello.com/c/J0iau68b/326-yellow-tooltip-type-alert-to-completed-actions-in-web.

Good to merge.

**Comment by will-moore** [comment]
Also note that the new Tagging Robot test passed for Chrome today https://ci.openmicroscopy.org/view/Failing/job/OMERO-5.1-merge-robotframework/162/console
(although all tests failed for FF)
However, I just noticed that the doc-string for this test could do with tweaking (copy/paste error).
```
05:28:17 ==============================================================================
05:28:17 Web.Tagging Test :: Tests submission of forms.                                
05:28:17 ==============================================================================
05:28:58 Test Tag :: Test Batch Annotation of 2 Projects that we create        | PASS |
05:28:58 ------------------------------------------------------------------------------
05:28:58 Web.Tagging Test :: Tests submission of forms.                        | PASS |
05:28:58 1 critical test, 1 passed, 0 failed
05:28:58 1 test total, 1 passed, 0 failed
05:28:58 ==============================================================================
```

**Comment by will-moore** [comment]
OK, doc string updated. Should be good to merge now.

**Pull request merged**
