### PR TITLE
Url suffix check

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
# What this PR does

Following https://github.com/openmicroscopy/openmicroscopy/pull/4728 this pr parse templates o identify lack of versioning. `src` attribute has to either contain version in a minimum format like `0.0` or `|add:url_suffix`

examples:

```
<link rel="stylesheet" href="{% static 'webgateway/css/ome.table.css'|add:url_suffix %}" ...
<link rel="stylesheet" href="{% static '3rdparty/jquery.tablesorter-2.0.3/jquery.tablesorter.css' %}"...

<script type="text/javascript" src="{% static '3rdparty/jquery.jstree-3.0.8/jstree.js' %}"...
<script type="text/javascript" src="{% static 'webclient/javascript/ome.tree.js'|add:url_suffix %}"...
```

# Testing this PR

- add `<script>` and `<link>` 
  - `<link rel="stylesheet" href="{% static 'webadmin/css/drivespace.css' %}" type="text/css"/>` missing `|add:url_suffix`
  - `<link rel="stylesheet" href="{% static '3rdparty/your_file.css' %}" type="text/css" media="screen"/>` missing version in a minimum format like `0.0`
- run `./build.py -f components/tools/OmeroWeb/build.xml findbugs`

# Related reading

how error works:
```
./build.py -f components/tools/OmeroWeb/build.xml findbugs
...
findbugs:
Template error.
./omeroweb/webgateway/templates/webgateway/base/includes/shortcut_icon.html:21 {% static '/favicon.ico' %}

BUILD FAILED
```

--exclude

### CODE REVIEW

**Comment by joshmoore** [comment]
Can this be re-included?

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#426](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/426/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/426/consoleText) for more details.
Possible conflicts:
  - PR #4703 will-moore 'histograms'
    - components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/base/base.html
    - components/tools/OmeroWeb/omeroweb/webgateway/templates/webgateway/viewport/omero_image.html
    - components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/base/base_container.html

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#427](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/427/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/427/consoleText) for more details.
Possible conflicts:
  - PR #4703 will-moore 'histograms'
    - components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/base/base.html
    - components/tools/OmeroWeb/omeroweb/webgateway/templates/webgateway/viewport/omero_image.html
    - components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/base/base_container.html

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#428](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/428/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/428/consoleText) for more details.
Possible conflicts:
  - PR #4703 will-moore 'histograms'
    - components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/base/base.html
    - components/tools/OmeroWeb/omeroweb/webgateway/templates/webgateway/viewport/omero_image.html
    - components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/base/base_container.html

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#429](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/429/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/429/consoleText) for more details.
Possible conflicts:
  - PR #4703 will-moore 'histograms'
    - components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/base/base.html
    - components/tools/OmeroWeb/omeroweb/webgateway/templates/webgateway/viewport/omero_image.html
    - components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/base/base_container.html

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#430](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/430/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/430/consoleText) for more details.
Possible conflicts:
  - PR #4703 will-moore 'histograms'
    - components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/base/base.html
    - components/tools/OmeroWeb/omeroweb/webgateway/templates/webgateway/viewport/omero_image.html
    - components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/base/base_container.html

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#431](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/431/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/431/consoleText) for more details.
Possible conflicts:
  - PR #4703 will-moore 'histograms'
    - components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/base/base.html
    - components/tools/OmeroWeb/omeroweb/webgateway/templates/webgateway/viewport/omero_image.html
    - components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/base/base_container.html

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#432](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/432/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/432/consoleText) for more details.
Possible conflicts:
  - PR #4703 will-moore 'histograms'
    - components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/base/base.html
    - components/tools/OmeroWeb/omeroweb/webgateway/templates/webgateway/viewport/omero_image.html
    - components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/base/base_container.html

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#433](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/433/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/433/consoleText) for more details.
Possible conflicts:
  - PR #4703 will-moore 'histograms'
    - components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/base/base.html
    - components/tools/OmeroWeb/omeroweb/webgateway/templates/webgateway/viewport/omero_image.html
    - components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/base/base_container.html

**Comment by joshmoore** [comment]
Added `--exclude` to the description.

**Comment by jburel** [comment]
@aleksandra-tarkowska: close this PR?

**Pull request closed without merging**
