### PR TITLE
Right panel annotation tabs

### PR DESCRIPTION
**Pull request by will-moore**
This PR updates the right panel annotations panes so that they don't load data unless expanded.
Also data is loaded via json instead of html.
Batch annotation has not been changed yet.

This will need a lot of testing with all the different annotations and permissions. Not ready for full testing yet. More cleanup work to do, but this is stable enough to open a PR now...

 - [x] Handle all "custom" types of annotation (boolean, xml, long, etc)
 - [x] Remove listAnnotations() from container.py. Leave for now - used by annotate_tags()
 - [x] Tests for tree.py marshal_annotations()
 - [x] Split ome.general_tab.js into separate files for each Annotation Pane.
 - [x] Move js for each annotation Pane out of metadata_general.html into separate classes for each Pane.
 - [x] Filter annotations by user (also in batch_annotation)
 - [x] Date formatting
 - [ ] Long text E.g. ns on tooltips.

To test, compare what's shown in web with Insight - to check correct annotations / permissions etc.
**For all panes**:
 - Check annotations are same as Insight
 - Check tooltips
 - Filter by owner (mine/others)
 - When pane is expanded, it should stay expanded when selecting new P/D/I etc
 - All annotations should take Well-Index into account - E.g. Select Well with index is 2 - add annotations & check that they are shown just on this well & index.
 - Permissions: when can / cannot annotate, check that buttons etc reflect this.
 - Permissions: check you can remove / delete your own / others' annotations as expected.
 - Add and remove annotations - check that display is updated as expected.
 - As discussed with @pwalczysko: test if fast selection changes can load incorrect content into an Annotation pane. E.g. Expand 'tag' pane, select a "slow-to-load" pane (object with lots of tags) followed rapidly by a "fast-to-load" pane. IF the slow content arrives AFTER the fast content, it *might* replace it (incorrectly) and be displayed for the second object.

**Batch annotate**
 - Same panes should stay expanded/collapsed when switching between singe/batch annotate.
 - Tags summarised as before (details in tooltip) - Clicking X removes all links that you can unlink, including those linked by others.

**Specific annotations**
 - Tags:
    - NB: we still show separate tags for each user (as before) instead of summarise them like Insight.
    - Now use a '-' icon for remove instead of 'x' [see ticket](https://trac.openmicroscopy.org/ome/ticket/12867)
 - Key Value Pairs
    - Create & Edit
    - Check display of non "client-editable" map annotations
 - Attachments
    - Check 'scripts' button works (run script with checked files)
 - Rating
    - No-longer have to start with + button. Start with blank 5 stars.
 - Others
    - I will add some to image on eel.
    - Tooltip on values.

### CODE REVIEW

**Comment by mtbc** [comment]
`./components/tools/OmeroWeb/omeroweb/webclient/tree.py:1704:80: E501 line too long (98 > 79 characters)`

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#300](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/300/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/300/consoleText) for more details.
Possible conflicts:
  - PR #4482 will-moore 'Hide empty column data develop'
    - components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/metadata_general.html

**Comment by will-moore** [comment]
Last commit fixes https://trello.com/c/fkEgcmXD/56-omero-web-can-t-resize-image-information-box
Couldn't open this in a new PR since it would clash with this one.

screen shot 2016-04-22 at 12 50 26

**Comment by pwalczysko** [comment]
regression bug: I do not seem to be able to collapse the ``Dataset details`` tab. This is perfectly possible on eel latest. (tested on cowfish connected to eel merge as user-10 on dataset 1689).
screen shot 2016-04-25 at 10 31 22

**Comment by pwalczysko** [comment]
Bug: A layout mistake on Comments, note that the ``user-10`` string is cut off display.
Firefox, user-10, dataset comment by the owner of the dataset (user-10)
screen shot 2016-04-25 at 10 34 52

**Comment by pwalczysko** [comment]
Bug:  ``Show all`` vs ``Show added by me`` on tags.
The ``Show added by me`` is hiding 1.  tags, 2. file attachments **added by me**. ``Show all`` shows them.
screen shot 2016-04-25 at 10 39 11

**Comment by pwalczysko** [comment]
> All annotations should take Well-Index into account - E.g. Select Well with index is 2 - add annotations & check that they are shown just on this well & index.

@will-moore : Please explain in more detail what you mean by ``Well-index`` - is that the ``Field`` ? If yes, then this does not work for me.

**Comment by will-moore** [comment]
I've added some custom "others" annotations and custom map annotations to Project at https://eel.openmicroscopy.org/merge/webclient/?show=project-4402 for user-3 and user-6. Annotations are duplicated since I repeated the script for each user.

**Comment by pwalczysko** [comment]
The data under ``Others`` and ``Key value pairs`` as described in https://github.com/openmicroscopy/openmicroscopy/pull/4579#issuecomment-214289534 are visible as expected for user-3 and user-6 and both are being filtered correctly by ``added by me`` etc. filters, but see https://github.com/openmicroscopy/openmicroscopy/pull/4579#issuecomment-214235517 - obviously this is a per-tab problem.

**Comment by gusferguson** [comment]
Tested using cowfish-webclient eel.openmicroscopy.org  and OMERO.insight-5.2.2-393-e464f65-ice36-b292-mac user-3 read-only-1 Safari

Issues found:

- “Details” tab - open by default - does not collapse for any of Project, Dataset, Image - does in Insight
- broken image link instead of user avatar in Comments - screenshot 1
- Admin/group owner on another user’s data - shows “X" - “Delete File” and “-" - “Remove File” for removing attachments - screenshot 2
- Read-only - non-owner/admin on other user’s data - shows only “X" - “Delete File” - screenshot 3
- Read-only - non-owner/admin on other user’s data - Web: Select files for scripts button not present - Insight: Select files for scripts button present and works - Web correct approach

Tooltips:
- Edit Name button - Web: Web: “edit” - should be same as Insight: “Edit the name”
- Add Description button - Web: “edit” - should be same as Insight: “Edit the description”
- Add Tag - Web: no tooltip - Insight: “Add Tags” - should both be “Add tags"
- KVP - add row - Web: “Insert rows" -  Insight: “Insert Row”  - should both be “Insert row"
- Attachments - select files for scripts button - Web: “Select Files for Scripts" -  Insight: “Select Files for Scripts”  - should both be “Select files for scripts"
- Attachments - add attachment button - Web: no tooltip - Insight: “Attach a document” - should both be “Attach a file"
- Attachments - Web: “X" - “Delete File” - Insight “Remove Attachments” - should both be “Remove attachment"
- Rating - Web: “-“ -  “Delete rating” - Insight:  “Unrate.” Insight needs to change to “Delete rating”

1 webclient

2 webclient

3 webclient

**Comment by gusferguson** [comment]
@dominikl 

Have opened Trello card with changes needed to Insight tooltips and one other issue arising from this. Would be nice to schedule it so that it is sorted at the same time these Web changes are released.

https://trello.com/c/POjkfKpE/392-insight-right-hand-pane-tooltip-changes

**Comment by pwalczysko** [comment]
Tags belonging to user-5 in RA group are causing a crash https://eel.openmicroscopy.org/merge/webclient/api/annotations/?type=tag&image=9245 if added by user-3 to his own image.

**Comment by will-moore** [comment]
@pwalczysko User-5 tag error https://github.com/openmicroscopy/openmicroscopy/pull/4579#issuecomment-214341225 is fixed by last commit.

**Comment by pwalczysko** [comment]
Bug: select 2 images. Comment both of them (in batch annotation mode, both of them are selected).
Then, when you check the images one-by-one, the comment is on each of them as expected. Now, again select both of the images. Remove the comment (both of the images still selected). Observe that the comment was removed just from one of them.

**Comment by pwalczysko** [comment]
There is a harmonica item ``Tables`` on the plates. Shouldn't we test this one as well ? How to get some data into this tab ? @will-moore

**Comment by pwalczysko** [comment]
Managed to populate the Tables harmonica on wells of Plate ID 1203 user-2 on eel merge. 
screen shot 2016-04-25 at 16 37 12

**Comment by will-moore** [comment]
Bugs addressed:
 - Collapse of "Details" pane
 - Filter annotations Added by me/others
 - Avatar image on Comments
 - Fixed switching of Field when Plate selected
 - Select files for scripts is shown even if user can't annotate
 - Tooltips fixed as suggested
 - Crash with User-5 tags (fixed loading of tag owner)
 - Removal of Comment from all objects in batch annotate panel

@gusferguson I think that Remove (-) and Delete (x) on File annotations for Admin is correct? Also Delete is available on Attachment if it is owned, even if you can't remove it. The "Delete File" tooltip is correct for X.

**Comment by gusferguson** [comment]
@will-moore @pwalczysko 

Tested using cowfish-webclient eel.openmicroscopy.org  and OMERO.insight-5.2.2-393-e464f65-ice36-b292-mac user-4 read-only-1 Safari

Previous issues:
Fixed - “Details” tab - open by default - does not collapse for any of Project, Dataset, Image - does in Insight
Fixed - broken image link instead of user avatar in Comments - screenshot 1

I am not sure what the permissions are with respect to Deleting attachments are.
Currently for read-only:
- for own attachments on own data: Insight - only offers Remove i.e. break link - Web - offers Remove and Delete (presume delete from server)
- other user's data: both Insight and Web don't allow anything
- admin user on another user's data: Insight - only offers Remove i.e. break link - Web - offers Remove and Delete

I am not sure which is correct.

Still inconsistent capitalisation in some tooltips - following should be in sentence case:
Publishing Options
Edit Channel Names
Remove Tag
Delete File --> "Delete attachment" would be better
Remove File --> “Remove attachment" would be better

**Comment by will-moore** [comment]
The webclient allows Delete of attachments in the right panel because there's not Attachments tab on the left (as in Insight) which allows you to browse and Delete files, so the only way to delete files is when they are attached to something in the right panel. However, it may be useful for users to be able to do that in Insight too, since finding the file in the Attachments tab on the left is not very intuitive and may lead to many files being orphaned but not deleted?

**Comment by pwalczysko** [comment]
2 Bugs connected to the KVPairs harmonica
    - 1. the ``+`` (Plus) does not work in any situation (should be adding rows)
    - 2. the toolbar of the KVP should be filtered as ``Show added by others`` is selected (disable the icons in situations where you cannot edit, like the Paste icon, the Plus icon, Delete icon) by default. Note that the Copy icon should still work in the moment when I select a row in the KVP table (even if I cannot edit that row)

**Comment by pwalczysko** [comment]
The filtering issue https://github.com/openmicroscopy/openmicroscopy/pull/4579#issuecomment-214235517 is fixed

**Comment by pwalczysko** [comment]
Bug: Comments do not appear after creation in 2 cases
Case 1:
    - go to an image which does not have any comments on it
    - select ``Show added by others``
    - select ``Show all``
    - add a new comment
    - click the button -> observe the comment you just created is not visible

Case 2:
    - go to an image which has some comments
    - delete these comments
    - add a new comment -> observe the comment you just created is not visible.

**Comment by pwalczysko** [comment]
Field switching when plate selected https://github.com/openmicroscopy/openmicroscopy/pull/4579#issuecomment-214257396 works as expected.

**Comment by will-moore** [comment]
@pwalczysko Fixed:
 - The '+' button for map annotations: works now and is disabled when we filter by 'added by others'
 - Comments "Case 2" above: New comment is shown after deleting all previous comments

I couldn't reproduce the Comments "Case 1" bug locally.

**Comment by pwalczysko** [comment]
Crash with user-5 tags https://github.com/openmicroscopy/openmicroscopy/pull/4579#issuecomment-214341225 is fixed

**Comment by pwalczysko** [comment]
> Select files for scripts is shown even if user can't annotate

This works as described.

**Comment by pwalczysko** [comment]
> Removal of Comment from all objects in batch annotate panel

This is https://github.com/openmicroscopy/openmicroscopy/pull/4579#issuecomment-214396326.  This feature works as expected now.

**Comment by pwalczysko** [comment]
The KVP ``+`` button works now and the icons are disabled https://github.com/openmicroscopy/openmicroscopy/pull/4579#issuecomment-214705244 as expected on the KVPs

**Comment by pwalczysko** [comment]
Addition of new Comments https://github.com/openmicroscopy/openmicroscopy/pull/4579#issuecomment-214736929 works as expected now, both case 1 and case 2.

**Comment by will-moore** [comment]
@pwalczysko Script I used for adding Custom Annotations: https://gist.github.com/will-moore/1f8994a12ad9a5608bf7b0b435d86dbc

**Comment by pwalczysko** [comment]
Others tab in Batch annotation mode:
   - the items are not ordered and it is not clear which comes from which selected object
   - compare below the screenshots of 2 projects annotated with identical items under ``Others`` with how the ``Others`` look like when these 2 projects are multiselected

One of the projects selected:
screen shot 2016-04-27 at 12 29 14


Both projects selected:
screen shot 2016-04-27 at 12 29 25

**Comment by will-moore** [comment]
@pwalczysko In the batch annotate panel, the Custom annotations now show which object they're linked to in their tooltip:

screen shot 2016-04-27 at 13 43 40

**Comment by pwalczysko** [comment]
Bug: Some tags are not shown in Batch Annotation mode. 
    - user-3 on cowfish connected to eel merge, https://cowfish.openmicroscopy.org/merge/webclient/?show=dataset-3504
    - inspect the Tags on the Dataset, find 7 Tags
    - note that 3 of the tags cannot be unlinked (permissions, this is expected)
    - select one other Dataset (so that you have multiselection in the tree including the dataset with 7 Tags)
    - observe that the Batch Annotation pane shows only 4 tags, 3 tags are gone (the ones which could not be unlinked in single item view mode)

**Comment by will-moore** [comment]
@pwalczysko As discussed: the issue in https://github.com/openmicroscopy/openmicroscopy/pull/4579#issuecomment-215075232 is a confusing display of individual tag-links on a single Dataset, whereas batch annotate panel shows these together as single tags (making it seem like there are some missing). This will be improved in a future PR, but it's not a regression/bug.

**Comment by pwalczysko** [comment]
The other tested funcionalities (the Batch annotate mode on all attachments, including ``Others``, the ``Table`` tab, permissions partially), worked fine.

ToDos here seem to be:
  - the capitalization in the tooltips https://github.com/openmicroscopy/openmicroscopy/pull/4579#issuecomment-214687693
  - checking the new tooltip line on the ``Others`` tab https://github.com/openmicroscopy/openmicroscopy/pull/4579#issuecomment-215070422
  - permissions 

Re: permissions - I think we should do a round of proper permissions testing with the ``permissions DB``, which will ensure we are checking all the cases of linkage and ownership and also will allow to pick up unexpected bugs

**Comment by jburel** [comment]
@pwalczysko: doing a round of permissions testing is necessary in order to have the PR in,
Do you think you could take care of that tomorrow?

**Comment by pwalczysko** [comment]
@jburel : Yes, starting to work at https://docs.google.com/spreadsheets/d/1lMYznGMmIvwhOS5aW0-nvuqt_4GbKpjyrm5Va5Nz5u8/edit#gid=469737557

**Comment by jburel** [comment]
Thanks

**Comment by pwalczysko** [comment]
Results of the permissions testing see https://docs.google.com/spreadsheets/d/1lMYznGMmIvwhOS5aW0-nvuqt_4GbKpjyrm5Va5Nz5u8/edit#gid=469737557

**Comment by pwalczysko** [comment]
Testing of permissions is finished now. In follow-up, no new bugs  found. All the bugs from the sheet were either declared fixed (see the [testing sheet](https://docs.google.com/spreadsheets/d/1lMYznGMmIvwhOS5aW0-nvuqt_4GbKpjyrm5Va5Nz5u8/edit#gid=1731867412) for appropriate PRs links), or found as invalid or wontfix (no change of behaviour compared to latest, acceptable atm).

**Comment by pwalczysko** [comment]
Comments deletion problem (line 2 of the [report](https://docs.google.com/spreadsheets/d/1lMYznGMmIvwhOS5aW0-nvuqt_4GbKpjyrm5Va5Nz5u8/edit#gid=1731867412) works as expected.

**Comment by pwalczysko** [comment]
comments creation problem on Fields (line 5 of the [report](https://docs.google.com/spreadsheets/d/1lMYznGMmIvwhOS5aW0-nvuqt_4GbKpjyrm5Va5Nz5u8/edit#gid=1731867412) works as expected.

**Comment by pwalczysko** [comment]
Ratings RFE (line 6 of the [report](https://docs.google.com/spreadsheets/d/1lMYznGMmIvwhOS5aW0-nvuqt_4GbKpjyrm5Va5Nz5u8/edit#gid=1731867412) improved things - now I do not have the feeling I can do an action on the rating when in fact I cannot. The Rating workflow still works.

**Comment by pwalczysko** [comment]
Bug: Comment deletion on the Search Result pane.
  - create a comment as a user which belongs to at least 2 groups
  - switch group
  - search for the commented object (which is now in a different group than the one you have switched to)
  - in the search results, select the object you commented and try to delete the comment
  - observe Delete confirm dialog followed by 404 dialog (object is not found)

Note that this bug is NOT a regression (present on eel latest as well). Happy for @will-moore to either fix it here or go ahead with this PR and fix it in a subsequent one.

**Comment by mtbc** [comment]
Re. adjusting delete: also note https://github.com/openmicroscopy/openmicroscopy/pull/4585/commits/eab13c50d1ce122ee0b0a07171047f7a76cc5318 in case we have another to-do when this work and 5.3 work meet.

**Comment by pwalczysko** [comment]
Bug: Delete a file Annotation on an object (single or multiselected, does not matter). Now immediately after that, add another file Annotation. Observe that the Annotation is not displayed immediately at the RHP (but it was added as found by refreshing the page).

**Comment by pwalczysko** [comment]
In summary, all bugs from the [Testing sheet](https://docs.google.com/spreadsheets/d/1lMYznGMmIvwhOS5aW0-nvuqt_4GbKpjyrm5Va5Nz5u8/edit#gid=1731867412) are fixed. 

ToDo on the bugfix front
  - fix bug with addition of File Annotations https://github.com/openmicroscopy/openmicroscopy/pull/4579#issuecomment-215683172
  - (optional) https://github.com/openmicroscopy/openmicroscopy/pull/4579#issuecomment-215677956 (not a regression)

**Comment by will-moore** [comment]
Last commit fixes the FileAnnotations bug from https://github.com/openmicroscopy/openmicroscopy/pull/4579#issuecomment-215683172

**Comment by will-moore** [comment]
The deletion of Comments etc from other groups in Search page can be fixed with https://github.com/openmicroscopy/openmicroscopy/commit/61a796545b60da0efce8d8d614f787b48f6a9377 but this change could have unintended effects and we don't have time to do sufficient testing at this stage. Since this bug has been around a long time, I think it is safer to leave this fix for 5.2.4?

**Comment by jburel** [comment]
we might not have a 5.2.4
I will agree with @will-moore: Better solidify what's in place and not introduce commit with possible unintended effects.

**Comment by pwalczysko** [comment]
The last bug to fix https://github.com/openmicroscopy/openmicroscopy/pull/4579#issuecomment-215683172 (the file annotations refresh failure) is fixed now.

**Comment by pwalczysko** [comment]
Checked shortly once more the workflows leading to the bugs reported and fixed in this PR. No regressions detected. All good on the bugfix front.

**Comment by jburel** [comment]
https://ci.openmicroscopy.org/view/OMERO-DEV/job/OMERO-DEV-merge-integration-python/ is green this am

**Comment by will-moore** [comment]
Only 2 Robot failures now: https://ci.openmicroscopy.org/view/OMERO-DEV/job/OMERO-DEV-merge-robotframework/286/robot/
One is webadmin (not this PR) and the other is just a transient failure (age: 1)

**Comment by jburel** [comment]
Back to something more reasonable with @will-moore's latest commit

**Comment by jburel** [comment]
Thanks all.
@will-moore: you might want to move your last item in the description to a ticket/card so it does not get forgotten

**Comment by will-moore** [comment]
@jburel Will do!
Thanks all for the extensive testing.

**Comment by will-moore** [comment]
Follow-up items listed at https://trello.com/c/MdxCONQY/78-finishing-right-panel-annotation-tabs

**Comment by jburel** [comment]
Thanks @will-moore

**Comment by pwalczysko** [comment]
How about the cross-group search https://github.com/openmicroscopy/openmicroscopy/pull/4579/commits/61a796545b60da0efce8d8d614f787b48f6a9377 ? Do we have a placeholder for this ?

**Comment by will-moore** [comment]
@manics I seem to remember you had a "hack" for IDR to display annotations on a Well alongside those on the Image in the right panel (normally webclient doesn't display Well annotations). I don't know if that ever got into develop branch, but with this PR (in 5.2.3) merged with IDR, that will have been lost, so it will need to be added back in a different way if you still need that functionality in IDR?

**Comment by manics** [comment]
This was the metadata52 PR: https://github.com/openmicroscopy/openmicroscopy/pull/4457

**Comment by will-moore** [comment]
@manics Yes. That code is no-longer used with this PR (it has been cleaned up and removed in https://github.com/openmicroscopy/openmicroscopy/pull/4660)
Unfortunately I don't think there will be such an easy one-liner fix to replicate that functionality in 5.2.3 since we now load annotations for a Well by using image ID, E.g. tags: /webclient/api/annotations/?type=tag&image=1230132. I can have a look at fixing this if needed?

**Comment by joshmoore** [comment]
@will-moore : if you have an idea for a fix, even one that can't make it to the mainline, it would be much appreciated.

**Comment by manics** [comment]
Or we change `omero metadata` to attach annotations to the image instead of well (if it doesn't already, I can't remember if that was another hack that went in).

**Pull request merged**
