### PR TITLE
Error report via feedback

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
This PR fixes https://trac.openmicroscopy.org/ome/ticket/13091

With Django 1.8 ``repr(request)`` is no longer friendly that means we were missing WSGIRequest details in feedback form.

To test on eel (Django 1.6) and cowfish (Django 1.8):
 - go to ``weberror/error_500`` and check if you get WSGIRequest GET, POST, COOKIE and META information along side stacktrace

 ```
Traceback (most recent call last):
...
NameError: global name 'view_raise_500' is not defined

<WSGIRequest
path:/weberror/error_500/,
GET:...
POST:...
COOKIES:...
META:...
```
 - check if admin notification sent exactly the same data (notofication goes to: ci-web-errors).
 - check if log on eel shows WSGIRequest details (this is still broken on cowfish, see https://trac.openmicroscopy.org/ome/ticket/13090)

### CODE REVIEW

**Comment by will-moore** [comment]
On cowfish I see the expected server error page with
```
...
<WSGIRequest
path:/merge/weberror/error_500/,
GET:<QueryDict: {}>,
POST:<QueryDict: {}>,
COOKIES:{
...
```
but on eel I just see plain:
```
Internal Server Error
```

**Comment by will-moore** [comment]
eel OMEROweb.log has
```
2015-11-17 16:02:30,952 ERROR [                          django.request] (proc.11584) handle_uncaught_exception():224 Internal Server Error: /merge/weberror/error_500/
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 112, in get_response
...
NameError: global name 'view_raise_500' is not defined
```
and the OMEROweb_brokenrequest.log has wsgi details:
```
2015-11-17 16:05:12,856 ERROR [                          django.request] (proc.11583) handle_uncaught_exception():224 HTTP 500 <WSGIRequest
path:/merge/weberror/error_500/,
GET:<QueryDict: {}>,
POST:<QueryDict: {}>,
COOKIES:{'
...
```

**Comment by will-moore** [comment]
e-mail notification works for eel:
```
<WSGIRequest
path:/merge/weberror/error_500/,
GET:<QueryDict: {}>,
POST:<QueryDict: {}>,
COOKIES:{'
```
and cowfish
```
Request repr(): 
<WSGIRequest
path:/merge/weberror/error_500/,
GET:<QueryDict: {}>,
POST:<QueryDict: {}>,
COOKIES:{'
```
So, apart from eel showing ```Internal Server Error``` instead of feedback page, this is good to merge.

**Comment by aleksandra-tarkowska** [comment]
@will-moore eel now shows feedback page

**Comment by aleksandra-tarkowska** [comment]
@will-moore eel now shows feedback page, would you like to have a final go ?

**Comment by will-moore** [comment]
Feedback page on eel now working, with request details:
```
<WSGIRequest
path:/merge/weberror/error_500/,
GET:<QueryDict: {}>,
POST:<QueryDict: {}>,
COOKIES:{'_
```
Good to merge.

**Pull request merged**
