### PR TITLE
Minor version links

### PR DESCRIPTION
**Pull request by sbesson**
Following https://github.com/openmicroscopy/openmicroscopy/pull/3648#discussion_r27014605 and a discussion with @hflynn and @joshmoore, this PR:

- adds a script for bumping all encoded major.minor doc versions within the existing code
- runs this script on the existing repository with ``./components/tools/bump_version.py 5.1```

### CODE REVIEW

**Comment by ximenesuk** [comment]
This looks fine. According to my links I am now running OMERO 5.2 so the script (is there a better location for it?) works fine. Good to merge.

**Comment by sbesson** [comment]
@ximenesuk: thoughts about rebasing this to `dev_5_0` ?

**Comment by ximenesuk** [comment]
It depends whether we expect more point releases I guess? Maybe add to the Trello card for this?

**Comment by sbesson** [comment]
--no-rebase

**Pull request merged**
