### PR TITLE
Re-organise lut directory

### PR DESCRIPTION
**Pull request by jburel**
# What this PR does

Proposal:
Re-organize the repository
Similar organisation that the image commons one

# Testing this PR

Make sure that the LUT are still available in the clients

# Related reading

https://trello.com/c/9iAe3Sg9/95-lut-support

cc @joshmoore @will-moore @dominikl

### CODE REVIEW

**Comment by jburel** [comment]
any comment on the proposed re-organisation?

**Comment by jburel** [comment]
excluding for now

**Comment by jburel** [comment]
removing exclude

**Comment by will-moore** [comment]
I think this PR may be breaking LUT thumbnails?

**Comment by jburel** [comment]
Still?

**Comment by will-moore** [comment]
Sorry - seems to be working on merge build - I was using an old local build. 😡

**Comment by jburel** [comment]
merging this PR, if we need to revisit we can open another PR

**Pull request merged**
