### PR TITLE
LuceneQuerybuilder Mapannotations

### PR DESCRIPTION
**Pull request by dominikl**
This PR adds the colon character to the preserved characters when building the lucene query. This is needed for the specific MapAnnotation searches to work. On this occassion I also removed the LuceneQueryBuilder class and test from Insight, because the class has already been moved to the ome commons package.

To Test:
- Make sure that the search still works like before.
- Test the MapAnnotation specific searches: Add a Key-Value pair to a MapAnnotation, e. g. "foo"-"bar". Now add the term "foo" also to other MapAnnotations either as key or value and also to other kinds of Annotations (e. g. comment). Wait a bit for the search indexer been run. Now search for "foo:bar" and make sure you **only** see results which have the Key-Value pair "foo"-"bar" in the MapAnnotation. Then search for "has_key:foo" and make sure you **only** see results with a key "foo" in the MapAnnotation.
- Additional test: Because there was a merge conflict with #3506 , it would be good to check again, that connecting via Session ID still works.

--no-rebase

### CODE REVIEW

**Comment by joshmoore** [comment]
@dominikl : my previous unit test will need updating:
```
[nomemorytestng] junit.framework.ComparisonFailure: Failed on query: has_key:foo expected:<... ...> but was:<...:...>
[nomemorytestng] 	at junit.framework.Assert.assertEquals(Assert.java:81)
[nomemorytestng] 	at ome.util.search.LuceneQueryBuilderTest.checkQuery(LuceneQueryBuilderTest.java:191)
```

**Comment by dominikl** [comment]
Thanks @joshmoore , missed that.

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#797](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/797/). See the [console output](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/797/consoleText) for more details.
Possible conflicts:
  - PR #3506 jburel 'Connect with session ID'
    - components/insight/SRC/org/openmicroscopy/shoola/env/data/OMEROGateway.java

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#798](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/798/). See the [console output](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/798/consoleText) for more details.
Possible conflicts:
  - PR #3506 jburel 'Connect with session ID'
    - components/insight/SRC/org/openmicroscopy/shoola/env/data/OMEROGateway.java

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#799](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/799/). See the [console output](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/799/consoleText) for more details.
Possible conflicts:
  - PR #3506 jburel 'Connect with session ID'
    - components/insight/SRC/org/openmicroscopy/shoola/env/data/OMEROGateway.java

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#800](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/800/). See the [console output](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/800/consoleText) for more details.
Possible conflicts:
  - PR #3506 jburel 'Connect with session ID'
    - components/insight/SRC/org/openmicroscopy/shoola/env/data/OMEROGateway.java

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#801](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/801/). See the [console output](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/801/consoleText) for more details.
Possible conflicts:
  - PR #3506 jburel 'Connect with session ID'
    - components/insight/SRC/org/openmicroscopy/shoola/env/data/OMEROGateway.java

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#802](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/802/). See the [console output](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/802/consoleText) for more details.
Possible conflicts:
  - PR #3506 jburel 'Connect with session ID'
    - components/insight/SRC/org/openmicroscopy/shoola/env/data/OMEROGateway.java

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#803](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/803/). See the [console output](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/803/consoleText) for more details.
Possible conflicts:
  - PR #3506 jburel 'Connect with session ID'
    - components/insight/SRC/org/openmicroscopy/shoola/env/data/OMEROGateway.java

**Comment by joshmoore** [comment]
Hi @dominikl. I don't see any tests for the behavior when "Annotation" is checked. Discussing with @pwalczysko in devteam this evening, it looks like when that box is checked, the map annotations are no longer appropriately checked. What precisely drives that behavior? Is that something to add here or elsewhere?

**Comment by dominikl** [comment]
@joshmoore What do you mean be an Annotation is checked?

**Comment by dominikl** [comment]
Ah sorry, you mean the Annotations checkbox in the search panel. I have a suspicion, I think what happens is, that if you enter a search term like has_key:foo and tick the Annotations checkbox, the lucene expressions TextAnnotation:has_key:foo, FileAnnotation:has_key:foo, ... are created, which don't work of course. 
Shall I fix this within this PR? But what does that mean for the MapAnnotation search testing tomorrow? Are you going to test with the merge build, or are you going to build an rc/milestone?

**Comment by pwalczysko** [comment]
cc @joshmoore : In case I tick the Annotation box in Search UI in Insight, I will NOT get the results which I have got with this box NOT-ticked, in case I did NOT use the colon.
If I use the colon, the Annotations box ticked works fine.

I think this must be fixed in other PR. The main features here (colcon and Annotations box with colon) work.

**Comment by dominikl** [comment]
@joshmoore @pwalczysko Is it possible that the search restriction "Annotation" does not include the MapAnnotation content. E. g. like the problems with the FileAnnotation content, see workaround https://github.com/openmicroscopy/openmicroscopy/blob/44dc04b3b643287dbe329d4316704f0a7b40ee6a/components/insight/SRC/org/openmicroscopy/shoola/env/data/OMEROGateway.java#L5164

**Comment by joshmoore** [comment]
```
                if (scopeId == SearchParameters.ANNOTATION) {
                    // TODO: adding file.xyz is a workaround for these things not 
                    // being part of the annotation index, can be removed again for > 5.0
                    result += "annotation, file.name, file.path, file.contents, file.format";
                }
```

We can certainly move that clause to the server-side LuceneQueryBuilder, but it may be enough to add a call like https://github.com/openmicroscopy/openmicroscopy/blob/v5.1.0-m4/components/server/src/ome/services/fulltext/FullTextBridge.java#L207 to https://github.com/openmicroscopy/openmicroscopy/blob/v5.1.0-m4/components/server/src/ome/services/fulltext/FullTextBridge.java#L377

**Pull request merged**
