### PR TITLE
Fixing broken links email notification

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
This PR fixed ```SEND_BROKEN_LINK_EMAILS``` that was removed in Django 1.6 infavour of ```django.middleware.common.BrokenLinkEmailsMiddleware```.

To test it:
 - set ```bin/omero config set omero.web.debug False```
 - set mail config https://www.openmicroscopy.org/site/support/omero5.1/sysadmins/mail.html
  - locally SMTP mock (you will not get real email):
    - set ```bin/omero config set omero.mail.from "your@email``` and ```bin/omero config set omero.mail.host "localhost"```
    - start SMTP mock ```sudo python -m smtpd -n -c DebuggingServer localhost:25```. *Email message will be shown as a plane text on your console.*
 - set your email in ```bin/omero config set omero.web.admins '[["Username", "your@email"]]'```
 - try to get HTTP500 and 404 (must come from broken link in template, do not access random url) and see if you received both errors by email

### CODE REVIEW

**Comment by joshmoore** [comment]
@aleksandra-tarkowska : is a mgmt_tools PR needed/suggestible as well?

**Comment by aleksandra-tarkowska** [comment]
@joshmoore do you volunteer your email address? ;-)

**Comment by joshmoore** [comment]
Chatting it through with @kennethgillen, "ci-web-errors@" as an alias sounds like it makes sense. Let's continue this discussion on the internal mgmt PR when/if.

**Comment by aleksandra-tarkowska** [comment]
@joshmoore still travis error, could you fix it please?

**Comment by joshmoore** [comment]
```
[ivy:resolve] 	Server access Error: Connection timed out url=http://artifacts.openmicroscopy.org/artifactory/maven/ome/appbundler/1.0.0/appbundler-1.0.0.jar
```
Relaunched. You can always close/re-open yourself if no one is around to restart.

**Comment by sbesson** [comment]
Tested on a CI server with mail configured (was able to send an email via the Webadmin route) and `omero.web.admins` configured to an alias email tested independently. Tried to access a 404 page using an URL of type `/webclient/img_detail/nonexistingid/` however no email was sent to the admins alias.

**Comment by aleksandra-tarkowska** [comment]
@sbesson sorry forgot to mention you have to have broken link in a template. Just random access won't work :-)

Go to feedback page that has broken css and you will get 2 x broken links email.

I will fix them once this is in

**Comment by aleksandra-tarkowska** [comment]
@sbesson sorry forgot to mention you have to have broken link in a template, during rendering. Just random access won't work and has no really sense :-)
The best is to test it locally by crashing web and then adding fake {% static "foo.css" %}. @will-moore could you help with testing that? Full instraction how to run local mail server listener is above

**Comment by sbesson** [comment]
Thanks for the clarification. Once tested locally, we still need to find a way to test this in a non-local environment especially since the testing setup is not straightforward. Would it be sensible to add some broken links in templates of a testing webapp (webtest?) and deploy it on CI? That way we could have a reproducible testing setup? Any other alternative/suggestion?

**Comment by aleksandra-tarkowska** [comment]
@sbesson the simplest way is to remove 
```
location /omero/static {
        alias /path/to/dist/lib/python/omeroweb/static;
    }
```

then all statics are broken and when you go to login page you will receive tones of emails ;-)

**Comment by pwalczysko** [comment]
```
---------- MESSAGE FOLLOWS ----------
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Subject: [OMERO.web - admin notification]Broken INTERNAL link on 127.0.0.1:4080
From: pwalczysko@dundee.ac.uk
To: your@email
Date: Wed, 01 Jul 2015 09:47:52 -0000
Message-ID: <20150701094752.69600.75506@LS25165.local>
X-Peer: 127.0.0.1

Referrer: http://127.0.0.1:4080/webclient/login/?url=%2Fwebclient%2F
Requested URL: /static/petr.css
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:33.0) Gecko/20100101 Firefox/33.0
IP address: 127.0.0.1
------------ END MESSAGE ------------
```
Was sent from the local server mockup after following the workflow on this PR and additionally fiddling with ``/lib/python/omeroweb/webclient/templates/webclient/login.html`` file, copying the line 27 and pasting it underneath and then changing the pasted line the output in following way:
``<link rel="stylesheet" href="{% static "petr.css" %}" type="text/css" />``

The local test passed.

**Comment by aleksandra-tarkowska** [comment]
It took me sometime to get that we won't get ever 404 notification because statics are handled by webserver and we will have to set apache to redirect to django when it gets a request that results in a 404. I think we can leave it as it is. It is working for development server when django handle statics by itself.

**Comment by aleksandra-tarkowska** [comment]
if that is ok with @joshmoore and @sbesson I would be happy to merge it as it is improvement.

**Comment by sbesson** [comment]
Will do a quick retest tomorrow for the last commit using the new [weberror](https://github.com/openmicroscopy/weberror) OMERO.web app for 500 errors. If this passes, no veto to getting this merged from my side.

**Comment by sbesson** [comment]
Retested on trout/merge and trout/latest (without this PR). Works as expected i.e. no regression. Some concern was expressed about the potential of email flooding especially now we remove the opt-out option /cc @joshmoore @manics. I propose we merge this as it is and investigate throttling/opt-out in a separate PR/create a card?

**Comment by aleksandra-tarkowska** [comment]
to opt out you need to remove emails from omero.web.admins, that's all.

**Comment by aleksandra-tarkowska** [comment]
https://github.com/openmicroscopy/openmicroscopy/pull/3901#issuecomment-118025066 updated

**Comment by aleksandra-tarkowska** [comment]
BTW: it will definitely speed up fixing bugs :)

**Comment by sbesson** [comment]
Assuming we'll make sure the corresponding documentation section will be reviewed for 5.1.3 /cc @hflynn, merging.

**Pull request merged**
