### PR TITLE
File name

### PR DESCRIPTION
**Pull request by jburel**
Fix the display of the file name when dragging the divider of the split pane

To test:
 * Log in as user-1
 * Expand the "archived dv " dataset
 * Dragging the divider of the split pane. Check that the name displayed is adjusted.

This might require some screenshots update since I have removed the "nebulous" full name icon (abc)
cc @gusferguson 

ref https://www.openmicroscopy.org/community/viewtopic.php?f=4&t=7596&p=14469#p14469

### CODE REVIEW

**Comment by pwalczysko** [comment]
Works as expected. Also for P/Ds.

 The only minor issue is that if you edit and change the name of P/D/I in the right-hand pane to a long name, it does not immediately display in the tree with the full name, but in ``...middle-of-name...`` form (see screenshot) also if you click the Save icon after you have done the edit. The display in the tree gets fixed next time when you refresh the tree though.


screen shot 2015-04-30 at 11 01 54

**Comment by joshmoore** [comment]
@jburel working on further commits.

**Comment by jburel** [comment]
@pwalczysko: note that the problem already exists in the current version.

**Comment by pwalczysko** [comment]
@jburel : Definitely, this is a bit advanced workflow, the long names are displayed as expected here. Happy to move on with this PR.

**Comment by jburel** [comment]
@pwalczysko: last commit should fix the issue reported.

**Comment by gusferguson** [comment]
@jburel 

Tested using OMERO.insight-5.1.1-153-383152c-ice35-b493-mac_Java7+ gus daily_testing_group.

Cannot reduce the width of the right hand pane below 444 px.
At this minimum width have to have very long P/D/I names and there is no truncation/adjustment, even if pane reduced to below size of name - screenshot 1.
This minimum size is too wide to allow flexibility.
@mtbc also found the large fixed minimum to be inflexible.
The names are updating in data pane when edited to longer name.

gus gus connected to trout openmicroscopy org

**Comment by jburel** [comment]
@gusferguson: right hand pane? I have not touched that.

**Comment by gusferguson** [comment]
@jburel - sorry - left hand - mixing up my hands.

**Comment by mtbc** [comment]
Thank goodness it's not just a Linux problem. I found that if I resized the window vertically, the left pane kept getting wider!

**Comment by jburel** [comment]
The problem seems to come from https://github.com/openmicroscopy/openmicroscopy/pull/3738.
I will exclude it so this PR can be tested.

**Comment by gusferguson** [comment]
@jburel 

OMERO.insight-5.1.1-223-ba45f23-ice35-b496-mac_Java7+ trout user-1 daily-testing

The issue with the left hand pane not resizing has resolved so must have been due to #3738.

The truncation of names in the left hand pane behaves a bit strangely.
Start with long names fully display - screenshot 1
Reducing the width of LH pane - no truncation takes place for quite a time - screenshot 2
When the truncation starts it is at the start of the name, but the end of the name is still obscured by the right edge of the LH pane - screenshot 3.
I think that the truncation should start as soon as the right side of the LH pane hits the end of the name - otherwise it really defeats the object of this strategy.
As has been discussed before, the end of the name is important for the users as this often has a unique identifier when all the images have the same e.g. the name of the experiment/run, as well as the file type suffix.

user-1 user-1 connected to trout openmicroscopy org

user-1 user-1 connected to trout openmicroscopy org

user-1 user-1 connected to trout openmicroscopy org

**Comment by jburel** [comment]
@gusferguson: The last commit should improve the display.

**Comment by gusferguson** [comment]
@jburel 

Tested using OMERO.insight-5.1.1-265-7b13a10-ice34-b498-mac_Java7+ and OMERO.insight-5.1.1-265-7b13a10-ice34-b498-win trout user-1.

The behaviour of the truncation is better now - truncation occurring when LH pane is reduced in size as end of name reached.

There are a few issues though:
- when a project or dataset is truncated the number of child objects in square brackets at the end disappears - see screenshots 1 (before) and 2 (after)
- when the name of an image is truncated as the LH pane reduces in size - it jumps to a much shorter length which seems unnecessary - the truncation should be a smooth transition  (Mac) - screenshot 3 (before) - and 4 - arrowed
- with Windows, this is smoother (without the jump) but even more marked - leaving a wide empty space to the right of the names - screenshot 5 - arrowed.

Summary: working as a whole but some tweaking desirable if possible within library and time constraints.

main

main

main

image

parallels_desktop

**Comment by jburel** [comment]
The number of child objects is now preserved
For the rest, it might be tricky since the same component is used by the renderer

**Comment by gusferguson** [comment]
@jburel 

The display of the number of child objects behaves as expected and the truncation is working a bitt smoother. Screenshot 1

The behaviour of the elements on truncation is still pretty weird.
On narrowing of pane, it appears that the text of the name is actually shortening, but the label length is not.
The effective size of the pane seems to be staying the same as a scroll bar is appearing unnecessarily and if you look at the highlight of the long name, you can see what appears to be the size of the label staying the same with the text truncating within in it. Screenshot 2 - arrowed.

Accepting the difficulty of sorting out such things with the existing components, I leave it up to you whether to merge this and look at the issues in 5.1.3 or delay this to sort them out. The issues are not really affecting the interaction in any significant way.

omero insight

omero_insight

**Comment by gusferguson** [comment]
@jburel 

Tested using OMERO.insight-5.1.1-399-3afd8dc-ice35-b505-mac_Java7+ and OMERO.insight-5.1.1-399-3afd8dc-ice35-b505-win trout merge user-3 read-write.

Working much better now.
No scroll bars, the highlight issue is much reduced and everything else behaving as expected.
Good to merge.

user-3 user-3 connected to trout openmicroscopy org

parallels desktop

**Comment by jburel** [comment]
@gusferguson: thanks for your patience.
screenshots in help might have to be updated since I removed the "abc" icon in this PR.

**Comment by gusferguson** [comment]
@jburel - thanks - I will have a look but it may not be worth the hassle just for that - can probably wait for the next change. Redoing some of the screenshots is a bit difficult at this stage as I still don't have a Help server so am having to do quite a bit of photoshopping.

**Comment by jburel** [comment]
Agree. It can be done later on, not really a key update
As long as you have it listed.

**Pull request merged**
