### PR TITLE
Import integration test

### PR DESCRIPTION
**Pull request by joshmoore**
This PR builds on top of https://github.com/openmicroscopy/openmicroscopy/pull/5645 in order to:

 * provide a developer Dockerfile that provides an `omero-server-docker` view on the local checkout
 * run the (Python) integration tests that have been modified in a given PR in travis

### CODE REVIEW

**Comment by joshmoore** [comment]
from https://travis-ci.org/openmicroscopy/openmicroscopy/jobs/341933322

```
============================= test session starts ==============================
platform linux2 -- Python 2.7.5, pytest-2.9.2, py-1.5.2, pluggy-0.3.1
rootdir: /src/components/tools, inifile: pytest.ini
plugins: django-3.1.2
collected 152 items

test/integration/clitest/test_import.py ......................................................................................................................................................

=================== 2 tests deselected by "-m 'not broken'" ====================
```

**Comment by joshmoore** [comment]
I'll rebase this onto `develop`. Time to decide if we want a development Dockerfile (and/or integration tests run in Travis)

**Comment by jburel** [comment]
I like the idea of a development docker file
Running the integration tests by default will take a very long time (probably ~3h)

**Comment by joshmoore** [comment]
For the one file listed here it was 47m:

screen shot 2018-02-23 at 13 01 44

screen shot 2018-02-23 at 13 04 12


So certainly a cost but *only* if you modify an integration test.

**Comment by joshmoore** [comment]
There were no changes between my `integration` branch and master, so I've bumped to the official location. If this is still green, then we might consider merging for 5.4.6.

**Comment by joshmoore** [comment]
```
    from pip import main
ImportError: cannot import name main
```

Looks like omero-test-infra needs some PyPi love as well.

Edit: No, that's a Python issue in this Dockerfile.

**Comment by jburel** [comment]
Merging
This will help us identifying test failure earlier

**Pull request merged**
