### PR TITLE
Data loading

### PR DESCRIPTION
**Pull request by jburel**
This PR fixes the loading issues of "orphaned" datasets or plates.
Some datasets (resp. plates) were returned as orphaned even if they were linked to a project (resp. screen)
This was the cases when
 * user 1 has a project p1 and add dataset d2. d2 is owned by user-2
 * user-2 logs in and d2 was returned as "orphaned" since it was not linked to any project owned by p1
See https://trello.com/c/6IztFNAq/29-orphaned-dataset-in-another-s-project

Tests have been added to cover that use case and all integration tests (PojosService) should remain green

cc @will-moore @pwalczysko

### CODE REVIEW

**Comment by jburel** [comment]
Travis restarted

**Comment by dominikl** [comment]
Tests are green, also tested the workflow mentioned in the PR description, code looks plausible: Good to merge.

**Comment by jburel** [comment]
--rebased-to #4105

**Comment by sbesson** [comment]
One of the integration tests added as part of this PR seems to have failed intermittently on CI (https://ci.openmicroscopy.org/job/OMERO-DEV-merge-integration-java/62/testngreports/integration/PojosServiceTest/testLoadContainerHierarchyScreenWithOtherMembersPlate/) and I can reproduce the failure systematically locally.

**Comment by jburel** [comment]
@sbesson: will have a look, strange that it got missed

**Pull request merged**
