### PR TITLE
Added isThumbnailCached to retrieveThumbnail

### PR DESCRIPTION
**Pull request by rgozim**
### What this PR does

Adds `ctx.isThumbnailCached` to `retrieveThumbnail` function. `ctx.isThumbnailCached` checks if 
the rendering settings have changed for a particular image and is useful for figuring out whether to
regenerate an images thumbnail.

### Testing this PR

1. Change an images rendering settings 
2. Refresh and view the dataset with that image present
3. Check to see if the thumbnail of the image you edited, matches

### CODE REVIEW

**Comment by mtbc** [comment]
From Insight this certainly doesn't seem to be working. The image in the preview tab shows the new rendering settings but the thumbnail remains unchanged even after refresh.

**Comment by joshmoore** [comment]
@mtbc : I'm not sure I follow. Can you contrast the behavior in 5.4.7, rc1, and with this PR?

**Comment by mtbc** [comment]
Oh doh, sorry, this PR isn't in pub-omero is it? Will retest.

**Comment by mtbc** [comment]
Yeah, this works great on eel merge, :+1:

**Comment by joshmoore** [comment]
Great. Thanks. Merging for rc2 then.

**Pull request merged**
