### PR TITLE
adjust OMERO for OME-XML Shape changes

### PR DESCRIPTION
**Pull request by mtbc**
Updates OMERO to match the changes introduced by https://github.com/openmicroscopy/bioformats/pull/2286 and in accordance with,

* https://github.com/openmicroscopy/design/issues/17#issuecomment-189236477: drop `strokeLineCap`
* https://github.com/openmicroscopy/design/issues/18#issuecomment-189241559: add `markerStart`, `markerEnd`
* https://github.com/openmicroscopy/design/issues/19#issuecomment-189240552: drop `fontStretch`, `fontVariant`, `fontWeight`

Introduces database patch no. 3.

### CODE REVIEW

**Comment by mtbc** [comment]
Maybe it needs the new regions BF merge artifact to be pushed in order to pass Travis?

**Comment by sbesson** [comment]
@mtbc: correct, in this case Travis should be ignored as it will only turn green once the low-level BF PR is merged and the latest SNAPSHOT is pushed to the artifactory (might require the Travis Maven cache to be cleaned as well for the `regions` branch).

**Comment by dominikl** [comment]
Code changes look fine. ROI tool in Insight also works fine. But it didn't make use of most of these options beforehand anyway, at least I'm not aware of a way to modify line cap, marker, font stretch etc. in Insight.

**Comment by sbesson** [comment]
Looks good for the code perspective. All references to `fontStretch`, fontVariant` and `fontWeight` have been dropped and the only remaining place mentioning `strokeLineCap` seems to be the `components/insight/SRC/org/openmicroscopy/shoola/util/roi/io/OutputStrategy.java` and `components/insight/SRC/org/openmicroscopy/shoola/util/roi/io/InputStrategy.java` which I read as mostly SVG-related @jburel?

Testing the upgrade script on the copy of a production DB as we speak. Assuming this works without issue and changes make sense to @dgault, this looks good to merge.

**Comment by mtbc** [comment]
Well-spotted. On the topic of those input/output strategies, followup PRs may want to work on now adding better `markerStart` and `markerEnd` to those and also to this `ShapeSettingsData` stuff in the gateway. We could also probably do with adding the markers in to `ROI_utils.py`. I wasn't sure how best to do all that -- people like @dominikl or @will-moore may know -- but it's quite separable, probably easy for those who know that code, and possibly not even breaking.

**Comment by dgault** [comment]
Certainly from a code perspective this all makes sense and looks good to me too.

**Comment by sbesson** [comment]
Tested the DB upgrade on a nightly dump of the nightshade production database /cc @kennethgillen . After dropping the ROI namespaces/keywords following the instructions in http://lists.openmicroscopy.org.uk/pipermail/ome-devel/2016-January/003556.html, the upgrade completed successfully with 

```
$ time psql -U omero nightshade -f OMERO.server-5.3.0-m1-130-2395f73-ice35-b73/sql/psql/OMERO5.3DEV__3/OMERO5.2__0.sql
...
UPDATE 1
                                 status                                 
------------------------------------------------------------------------
                                                                       +
                                                                       +
                                                                       +
 YOU HAVE SUCCESSFULLY UPGRADED YOUR DATABASE TO VERSION OMERO5.3DEV__3+
                                                                       +
                                                                       +
 
(1 row)

COMMIT

real    0m38.590s
user    0m0.004s
sys     0m0.005s
```

Are the corresponding client todos captured in follow-up card(s)? Once this is done, this PR should be ready to merge.

**Comment by mtbc** [comment]
The to-do's I'm aware of are captured somewhat in comments on https://trello.com/c/9ZsIFHcJ/38-discrepancies. Happy for that to be split out in Trello however makes sense.

**Comment by sbesson** [comment]
Thanks. Splitting the card makess sense but we can discuss it separately. Merging this.

**Comment by mtbc** [comment]
Regarding `markerStart`, `markerEnd` client-side work, added https://trello.com/c/sh86TLSl/53-add-markerstart-markerend-for-java-clients and https://trello.com/c/LHdfcA8d/52-add-markerstart-markerend-to-roi-utils to https://trello.com/b/1t6i9daP/omero-5-3-0.

**Pull request merged**
