### PR TITLE
Check for FileAnnotations when looking for bulk-annotations

### PR DESCRIPTION
**Pull request by manics**
See https://trello.com/c/S302zihJ/52-web-crashes-if-plate-nsbulkannotations-isn-t-a-fileannotation

This follows on from https://github.com/openmicroscopy/openmicroscopy/pull/3875/files#diff-fc3a666f42c5099bec2593d6f4b4cf2dR2312

### CODE REVIEW

**Comment by manics** [comment]
Once this is reviewed I'll look at rebasing all three(?) related PRs onto develop.

**Comment by joshmoore** [comment]
Assuming @will-moore is ok with the name change, the changes look good to me. It would probably be most appropriate for this PR to contain an integration test that shows the problem, especially for rebasing to `develop`.

**Comment by will-moore** [comment]
Looks fine by me.

**Comment by manics** [comment]
@joshmoore @will-moore integration web test added

**Comment by joshmoore** [comment]
Locally:
```
test/integration/test_metadata.py::TestBulkAnnotations::test_nsbulkannotations_file[True] PASSED
test/integration/test_metadata.py::TestBulkAnnotations::test_nsbulkannotations_file[False] PASSED
test/integration/test_metadata.py::TestBulkAnnotations::test_nsbulkannotations_not_file PASSED
``` 
:thumbsup:

**Comment by will-moore** [comment]
Still seeing this error on IDR, e.g. https://idr.openmicroscopy.org/webgateway/table/Plate.wells/1003942/query/?query=Well-1003942

**Pull request merged**
