### PR TITLE
RenderingEngine: lookupTable getters/setters

### PR DESCRIPTION
**Pull request by joshmoore**
These methods will properly set the lookupTable
field on ChannelBinding. For the moment, that is
the extent of implementation for 5.1.0. A next
step will be to teach the RenderingEngine how to
make use of these properties.

### CODE REVIEW

**Comment by joshmoore** [comment]
Passing test pushed, but the value isn't being persisted. :/ cc: @jburel

**Comment by jburel** [comment]
string will indicate a known look-up, Do we want to handle the case, where we pass a file, i.e. tmp upload of the file and use its value. Probably too much for now

**Comment by joshmoore** [comment]
Definitely. I think even having the value stored in the DB is a plus at this point. Certainly don't intended to try to interpret that string at all. Any ideas on why it's not being saved? If not (and it's important), I'll dig later.

**Comment by jburel** [comment]
@joshmoore: I will have a look

**Comment by will-moore** [comment]
Looks good.

**Comment by joshmoore** [comment]
Thanks, guys. Merging and we can fix the save in a follow-up if we decide it's worth it.

**Pull request merged**
