### PR TITLE
read-only server

### PR DESCRIPTION
**Pull request by mtbc**
# What this PR does

Gives OMERO.server limited functionality even when it cannot write to the database or binary repository.

# Testing this PR

Expects a binary repository in which a read-write server has previously started even if it is no longer running.

```
omero.cluster.read_only.db=true
omero.cluster.read_only.repo=true
omero.pixeldata.memoizer.dir.local=/tmp/BioFormatsCache
```

Also one can usefully,

* configure the server to use a database user who has no UPDATE/INSERT privilege
* mount the binary repository filesystem read-only

and can read,

- `omero.cluster.read_only.runtime.db`
- `omero.cluster.read_only.runtime.repo`

For read-only servers there may be regressions in actions that require reading [events](https://docs.openmicroscopy.org/latest/omero5.4/developers/Model/EveryObject.html#event), [nodes](https://docs.openmicroscopy.org/latest/omero5.4/developers/Model/EveryObject.html#node) or [sessions](https://docs.openmicroscopy.org/latest/omero5.4/developers/Model/EveryObject.html#session) such as [CurrentSessionsRequest](http://downloads.openmicroscopy.org/latest/omero5.4/api/slice2html/omero/cmd/CurrentSessionsRequest.html). Also check that stores such as for [pixels](http://downloads.openmicroscopy.org/latest/omero5.4/api/slice2html/omero/api/RawPixelsStore.html) and [thumbnails](http://downloads.openmicroscopy.org/latest/omero5.4/api/slice2html/omero/api/ThumbnailStore.html) still reasonably allow read operations. Other read operations should be tested if their other test coverage is light.

Even in read-write mode read-only-ness is now more greatly enforced. This particularly affects requests like,

- LegalGraphTargets
- DiskUsage and DiskUsage2
- FindParents and  FindChildren
- FindPyramids
- SendEmailRequest
- OriginalMetadataRequest and UsedFilesRequest.

It also affects,

- the [dry-run mode](http://downloads.openmicroscopy.org/latest/omero5.4/api/slice2html/omero/cmd/GraphModify2.html#dryRun) of the graph requests that do writes
- the requests that can wrap others such as [DoAll](http://downloads.openmicroscopy.org/latest/omero5.4/api/slice2html/omero/cmd/DoAll.html) and [SkipHead](http://downloads.openmicroscopy.org/latest/omero5.4/api/slice2html/omero/cmd/SkipHead.html)
- the [config service](http://downloads.openmicroscopy.org/latest/omero5.4/api/slice2html/omero/api/IConfig.html) and the [types service](http://downloads.openmicroscopy.org/latest/omero5.4/api/slice2html/omero/api/ITypes.html).

Look through the diff to see what else received non-trivial changes, e.g., repository operations, especially scripts, so also check for regressions in places like the [script service](http://downloads.openmicroscopy.org/latest/omero5.4/api/slice2html/omero/api/IScript.html). Also note [[trello] test secvuln paths](https://trello.com/c/0K7SaVei/38-test-secvuln-paths).

Much of the above checking can probably be done quite effectively via the existing clients.

# Related reading

https://github.com/openmicroscopy/bioformats/pull/3102
https://github.com/openmicroscopy/bioformats/pull/3115
https://github.com/openmicroscopy/ome-documentation/pull/1864

The "read-only" and "doing" columns on the [IDR: 0.5.0](https://trello.com/b/Z3y5ty8o/idr-050) board track some of this thrust. Some of the cards report problems that may already be fixed in this branch.

The earlier part of this PR is largely adapted from #5271.

### CODE REVIEW

**Comment by mtbc** [comment]
Looks like some Python tables unit tests to fix for Travis.

**Comment by joshmoore** [comment]
Currently testing against a copy of the IDR database modified only with:

```
GRANT SELECT ON ALL TABLES IN SCHEMA public TO omeroreadonly;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
   GRANT SELECT ON TABLES TO omeroreadonly;
```

```
      - CONFIG_omero_cluster_read__only=true
```

allows the openmicroscopy/omero-server:east image to startup though:

```
      - CONFIG_omero_cluster_read__only.db=true
      - CONFIG_omero_cluster_read__only.repo=true
```
does not.

**Comment by mtbc** [comment]
Very strange. Locally,
```shell
(omero) mtbc@ls28101:~/src/openmicroscopy$ omero config get | grep read
omero.cluster.read_only=true
(omero) mtbc@ls28101:~/src/openmicroscopy$ grep ReadOnly dist/var/log/Blitz-0.log
2018-03-19 08:40:15,262 INFO  [        ome.services.util.ReadOnlyStatus] (      main) read-only status: db=true, repo=true
```
and under those circumstances,
```python
iConfig = conn.getConfigService()
print(iConfig.getConfigValue("omero.cluster.read_only.runtime.db"))
print(iConfig.getConfigValue("omero.cluster.read_only.runtime.repo"))
```
gives me,
```
true
true
```
so why that would be any different from using the other configuration settings I've no idea. Though for me the read-only server starts fine without `omero.cluster.read_only` set.

The failed startup: is it getting to start up in a repo that previously had a read-write server create the usual directories and files it does during startup?

**Comment by mtbc** [comment]
Would be great to keep an eye out for any NPE's from `BasicACLVoter.allowLoad` re. [[trello] NPE on login](https://trello.com/c/Fi0peNgq/37-npe-on-login).

**Comment by joshmoore** [comment]
> Very strange. Locally,

I take it back. A rebuild this morning _does_ work with the individual settings. The only NPEs I see are:

```
java.lang.NullPointerException: No repository to open!
```

This may be a combination of my stopping & restarting with differing configurations and whether or not `/OMERO` exists.

**Comment by joshmoore** [comment]
> This may be a combination ...

Apparently so:

 * mounting _nothing_ at `/OMERO`: starts up but NPE
 * mounting the _wrong_ directory at `/OMERO`: doesn't start up, "can't find FullText"
 * mounting the _right_ directory: starts up and no NPEs

**Comment by mtbc** [comment]
The latest commits require https://github.com/openmicroscopy/bioformats/pull/3102 in order to build. Further, on a read-only server it is helpful to set `omero.pixeldata.memoizer.dir.local` to even just `/tmp/BioFormatsCache` or somesuch.

**Comment by joshmoore** [comment]
Testing https://github.com/IDR/deployment/pull/103 on test50 I see no exceptions (neither web nor server) other than the usual "query took longer than X seconds". :+1: I'll keep testing, but I assume we're in quite good shape.

**Comment by joshmoore** [comment]
Testing from jupyter-docker (https://github.com/IDR/jupyter-docker/pull/28) we will likely want to make the runtime properties readable by non-root users.

**Comment by mtbc** [comment]
Will do. (I figured it was less breaking to loosen later than tighten later!) *Update:* Done.

**Comment by joshmoore** [comment]
No objections there. Happy to get the naming correct before we open it up if desired. I was just noticing that from the notebook setup, I don't have admin and therefore am not sure if the server is read-only. In fact, for the client-side, propagating the values to the `canEdit` methods may actually be more user-friendly.

**Comment by mtbc** [comment]
Renaming is of low technical risk so happy to accept last-minute rename requests before merging.

`canEdit` should already reflect read-only status.

**Comment by joshmoore** [comment]
```

Tag @link: can't find BlitzConfiguration(Ring, ome.services.sessions.SessionManager, SecuritySystem, Executor, int) in ome.services.blitz.util.BlitzConfiguration

```

in [build 930](https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-merge-build/930/warnings41Result/module.1453757448/package.-1564896846/) along with a few other javadoc issues.

**Comment by joshmoore** [comment]
All looks like there are some lingering integration tests: see 
 * https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-merge-integration-java/839/testngreports/integration/PermissionsTestAll/test/
 * https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-merge-integration-python/841/testReport/OmeroPy.test.integration.test_chgrp/TestChgrp/testChgrpImage/

Adding exclude to description until Mark is around to look into the issues.

**Comment by mtbc** [comment]
An interesting side effect of sprinkling more read-only transactions around is that some of them introduce data protection for read-write servers when they run operations that *ought to be* read-only.

**Comment by joshmoore** [comment]
Merging for 5.4.6-rc1

**Pull request merged**
