### PR TITLE
Offical scripts test

### PR DESCRIPTION
**Pull request by jburel**
# What this PR does

Add tests for officials scripts
This round of tests only deals with scripts manipulating images

# Testing this PR

Make sure the tests are green

# Related reading
Initial work done in https://github.com/openmicroscopy/openmicroscopy/pull/4914

### CODE REVIEW

**Comment by will-moore** [comment]
Failing at https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-merge-integration-Python27/383/testReport/OmeroPy.test.integration.scriptstest.test_analysis_scripts/TestAnalysisScripts/test_kymograph/
and
https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-merge-integration-Python27/383/testReport/OmeroPy.test.integration.scriptstest.test_analysis_scripts/TestAnalysisScripts/test_plot_profile/

**Comment by will-moore** [comment]
Also failing: https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-merge-integration-Python27/383/testReport/OmeroPy.test.integration.scriptstest.test_export_scripts/TestExportScripts/test_make_movie/

**Comment by jburel** [comment]
As mentioned previously  `mencoder` is not installed on cowfish => Python27 `make_movie` will fail until this is installed
I have created a new ansible role https://github.com/openmicroscopy/infrastructure/pull/174

**Comment by jburel** [comment]
@will-moore: the 2 failures for `analysis script` were due to a change in https://github.com/ome/scripts/pull/120
The tests should now pass

**Comment by jburel** [comment]
https://ci.openmicroscopy.org/job/OMERO-DEV-merge-integration-python/422/ are now green

**Comment by will-moore** [comment]
All passing today too https://ci.openmicroscopy.org/job/OMERO-DEV-merge-integration-python/423/ Good to merge.

**Comment by jburel** [comment]
last commit removed comments: ready to merge when travis is green

**Pull request merged**
