### PR TITLE
Fix broken link to the SpringFramework API in the Javadoc

### PR DESCRIPTION
**Pull request by sbesson**
This should fix the remaining warning of https://ci.openmicroscopy.org/view/DEV/job/OMERO-DEV-merge-build/

### CODE REVIEW

**Comment by sbesson** [comment]
See https://ci.openmicroscopy.org/view/DEV/job/OMERO-DEV-merge-build/130/

**Comment by sbesson** [comment]
A good way to view the output of this PR is to look at the signature of the `ThumbnailBean.setInProgressImageResource` method. Without this PR, the argument should be `org.springframework.core.io.Resource`. With this PR it should be an hyperlink to the relevant Spring Javadoc page.

**Comment by sbesson** [comment]
See https://ci.openmicroscopy.org/view/DEV/job/OMERO-DEV-merge-build/131/

**Comment by jburel** [comment]
looking good.

**Comment by mtbc** [comment]
:+1: Good to merge.

**Pull request merged**
