### PR TITLE
Make sure the same pixelsize unit is used for all dimensions

### PR DESCRIPTION
**Pull request by dominikl**
Bugfix: [Ticket 13034](http://trac.openmicroscopy.org/ome/ticket/13034)

Test: Check the pixelsizes for a few images (e.g. *.dv), especially the image mentioned in the ticket (nightshade image id: 4045578 ) Make sure the pixel size uses the same unit for all dimensions XYZ (it's shown in the tooltip when you hover over the pixelsize label), and make sure the values are correct (especially for Z dimension) by looking at the original meta data (unit can differ from the original meta data that's expected).

Note: The problem (wrong Z dimension unit) occured, when there was a two figure number for X, like in the example 66nm, but a three figure number for Z (200nm).

--no-rebase

### CODE REVIEW

**Comment by jburel** [comment]
minor formatting issue: ```if(unit == null)``` => ```if (unit == null)```

**Comment by jburel** [comment]
it works as expected. 
Matching changes to be implemented in web cc @will-moore 
I will add them to a card.

**Comment by jburel** [comment]
Card for "units" related work. https://trello.com/c/glNCdpXF/70-units-display

**Comment by jburel** [comment]
@pwalczysko: noticed the legacy "red" color when viewing the following image: user-4 23455
This can probably be fixed in this PR

**Comment by dominikl** [comment]
Another commit to come (removing the red color), not ready for merge yet.

**Comment by dominikl** [comment]
Test: 
- Select image 23455 (user-4), font showing pixels size should be same color as anything else (was previously red for this image).
- Tooltip when hovering over pixels size label in general tab should now use the unit symbol (not the name).
- Central panel: Tooltip should now use the same format (two decimal places) like the general metadata tab.

**Comment by pwalczysko** [comment]
Works as expected (both the unit is okay from the header of this PR as well as the red color is gone and the tooltip is as expected).
Ready to merge

**Pull request merged**
