### PR TITLE
Make movie web

### PR DESCRIPTION
**Pull request by will-moore**
This adds "Make Movie" functionality to the web client.
It should replicate the Insight functionality.

Test on images with sizeT > 1 or sizeZ > 1 or both.

 - Test that Make Movie option is enabled ONLY when a single image with sizeT > 1 or sizeZ > 1 is selected.
 - Check that the Make Movie dialog corresponds to Insight's when the same image is selected.
 - Check that edits to parameters in the UI have the expected effect in the exported movie (check it's the same as Insight).

### CODE REVIEW

**Comment by will-moore** [comment]
I think we should stick with spelling "Scalebar" as one word, but happy to change if this isn't the consensus.
I've fixed the handling of images named with path/to/image.tiff. Now we just use the last name in the path. This provides a name that can be safely used without having to subsequently handle the path. Insight should probably change to doing the same. However, the change to make the script actually use this value will have to come in a different PR (scripts repo).

**Comment by gusferguson** [comment]
@will-moore 

Tested using http://trout.openmicroscopy.org/merge/webclient/?# user-3 read-only-1

Downloaded file now saved with name from script text box.

**Comment by will-moore** [comment]
@jburel If you're happy with this, could you merge please? Thanks.

**Comment by jburel** [comment]
Adding comment to https://trello.com/c/ll8b4rFP/62-script-improvement
so we remember to unify/

**Comment by joshmoore** [comment]
Do any of the JS function renamings here need to be documented? /cc @hflynn

**Comment by will-moore** [comment]
I don't know of any JS documentation or external use of these methods, but it is possible that @aleksandra-tarkowska 's embedding of the viewer might use some of these. I'll check...

**Comment by gusferguson** [comment]
@will-moore @jburel - testing https://github.com/openmicroscopy/openmicroscopy/pull/3518
- still Scalebar in Web and Scale Bar in Insight

**Pull request merged**
