### PR TITLE
Lut repo 2

### PR DESCRIPTION
**Pull request by jburel**
# What this PR does
This PR replaces https://github.com/openmicroscopy/openmicroscopy/pull/4719
 * LUT folder is now under /scripts (i.e. we can see it as script for channels display0
 * ``getScripts`` method will not return the LUT. This implies that the clients displaying the available scripts do not need to be modified.
 *  New method ``getScriptsByMimetype``. This is the method to use to load the LUT (or any script e.g. ``matlab`` scripts). To load the luts, ``scriptingService.getScriptsByMimetype("text/x-lut")``
 * Also possible to upload official luts.

# Testing this PR
Integration tests added/adjusted.

# Related reading

Link to cards, tickets, other PRs:

### CODE REVIEW

**Comment by joshmoore** [comment]
I generally feel far more comfortable with the suggestion in this PR as opposed to gh-4719 at least without further scoping. The only suggestion that I'd either have for this PR or at least pre-5.3.0, would be to re-examine the metadata associated with each `FileType`. I think the explicit check at https://github.com/openmicroscopy/openmicroscopy/pull/4723/files#diff-daa1f148aedd13886dee7960c7a0cb50R468 could be removed in favor of explicitly marking LUTs as "inert" or similar. It *might* also be possible at the same time to differentiate "admin-only" scripts if that would be useful. (Perhaps by making use of https://github.com/openmicroscopy/openmicroscopy/blob/v5.2.4/components/blitz/resources/omero/api/IScript.ice#L241)

**Comment by jburel** [comment]
@joshmoore:
 * retrieve the scripts by mimetype instead of extension to match the rest of the methods
 * consider a ScriptFileType as ``inert`` if no processor and no launcher (we can review that)
This means that LUT files will fall into that category. I have debating introducing a specific flag for that
This means that the static field has been removed.

**Comment by jburel** [comment]
@joshmoore: I have opted for a new method ``loadScript`` (see 2ee6f3a) with ``Principal`` as a parameter.
I can now inject ``ScriptRepoHelper`` in the ``renderingbean`` and load the luts

**Comment by jburel** [comment]
https://ci.openmicroscopy.org/view/Breaking/job/OMERO-DEV-breaking-integration-python/573/ is green

**Comment by jburel** [comment]
Now that tests are green, I will probably remove the breaking flag.
@joshmoore: I had to introduce a new ``service-scripts.xml`` for the ``ScriptRepoFolder`` bean

**Comment by joshmoore** [comment]
> @joshmoore: I had to introduce a new service-scripts.xml for the ScriptRepoFolder bean

Makes good sense.

**Comment by dominikl** [comment]
I can't get the test run, always fails with database connection failures. I'm pretty sure, that's just a issue with my local test/server setup. The PR itself looks alright, and the script methods work fine, see #4746 .

**Comment by dominikl** [comment]
Not really necessary, I just added a `getLookupTables()` method to the `BrowseFacility` in the Java Gateway d12a8b67f9c .

**Comment by jburel** [comment]
Perfect this is actually better

**Comment by jburel** [comment]
For the tests, did you do a clean, build, test-compile before running the test?

**Comment by dominikl** [comment]
Oh, and I should add an integration test for `getLookupTables()`, forgot about that. Hm, I might have missed the `test-compile` before running the test, I'll try again.

**Comment by dominikl** [comment]
Still get the database connection issue... Where does the database information for the test actually come from?

```
Caused by: org.postgresql.util.PSQLException: FATAL: database "omero" does not exist
	at org.postgresql.core.v3.ConnectionFactoryImpl.readStartupMessages(ConnectionFactoryImpl.java:684) ~[postgresql-9.4-1200-jdbc4.jar:9.4]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:199) ~[postgresql-9.4-1200-jdbc4.jar:9.4]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[postgresql-9.4-1200-jdbc4.jar:9.4]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:127) ~[postgresql-9.4-1200-jdbc4.jar:9.4]
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29) ~[postgresql-9.4-1200-jdbc4.jar:9.4]
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21) ~[postgresql-9.4-1200-jdbc4.jar:9.4]
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:41) ~[postgresql-9.4-1200-jdbc4.jar:9.4]
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24) ~[postgresql-9.4-1200-jdbc4.jar:9.4]
	at org.postgresql.Driver.makeConnection(Driver.java:414) ~[postgresql-9.4-1200-jdbc4.jar:9.4]
	at org.postgresql.Driver.connect(Driver.java:282) ~[postgresql-9.4-1200-jdbc4.jar:9.4]
	at bitronix.tm.resource.jdbc.lrc.LrcXADataSource.getXAConnection(LrcXADataSource.java:104) ~[btm-2.1.3.jar:2.1.3]
	... 116 common frames omitted
2016-07-08 09:46:14,097 ERROR [          ome.services.util.DBPatchCheck] (      main) 
***************************************************************************************
Error connecting to database table dbpatch. You may need to bootstrap.
See http://www.openmicroscopy.org/site/support/omero5.2/sysadmins/server-upgrade.html
***************************************************************************************
```

The `omero` database definitely exists and the integration tests also run without problems.

**Comment by jburel** [comment]
what is the patch version of your local db?
all info will be in ``omero.properties`` file

**Comment by dominikl** [comment]
Sorry for the hassle, my fault, the problem was `omero` db existed, but was a very old one, as I usually use `omero_dev`, didn't notice because I always copy/paste the various db creation/update commands.
After upgrading my local `omero` db, the tests work fine! Good to merge. 👍

**Comment by jburel** [comment]
So when this PR is merged, you can re-open yours and I can open another one with changes of the rendering engine (probably against breaking) so you could test the client logic against a server with RE changes

**Comment by dominikl** [comment]
👍

**Comment by jburel** [comment]
@joshmoore: are you okay with the strategy in place? if yes, could you merge this PR, so I can "unlock" @dominikl

**Comment by joshmoore** [comment]
Merging with @jburel away so that @dominikl can proceed. Biggest (minor) concerns which can still be discussed:

 * naming of `luts/` directory (future proofing)
 * 3 separate uses of `isBlank` when defining "inert"

**Pull request merged**
