### PR TITLE
Decoupling

### PR DESCRIPTION
**Pull request by jburel**
Replaces gh-3952
Testing: Check basic functionality of Insight client; especially perform actions which trigger parallel requests to the server. See [Trello card, Test section](https://trello.com/c/2WY5iyS7/8-java-gateway)

### CODE REVIEW

**Comment by jburel** [comment]
not to be listed yet. 
I will try to fix the issue reported on gh-4021

**Comment by pwalczysko** [comment]
Tests:
Mac OS X Java 1.8.0u51 (done by Petr) with this PR in: short sleep test passes 
Win7 Java 1.8.0u51 (done by Petr) with this PR in short sleep test PASSES
Win7 java 1.8.0u35 (done by JM) with this PR in short sleep test Fails.

Previous tests by Petr on Win7 which failed were done on 1.8.0u45 - probably a Java dependent issue.

**Comment by pwalczysko** [comment]
Sorry, my previous comment was irrelevant, because I have used a client from a wrong build, without this PR all the way.

Retest shows that the sleep on Win7 with java 1.8.0u51 fails with this PR in. Interestingly, it passed yesterday though with the Insight from 5.1 merge line. It really looks like this PR is at fault...

**Comment by jburel** [comment]
@pwalczysko: The reconnect issue has now been fixed.
As discussed it still seems to be a problem with the "empty" and the reloading after reconnect
Depending on your testing report, we might consider fixing the "small" issue(s) in follow-up PRs.

**Comment by jburel** [comment]
@bramalingam: to test the "sleep" issue reported by @pwalczysko 
Test on Windows
 * Log in to OMERO.
 * Put the computer to sleep i.e. bottom left corner (where you can find options sleep, shutdown restart,etc.)
 * Re-login to laptop
 * Expand a dataset for example. The "Lost connection" Dialog should pop up and no error dialog
 *  After a bit, the connection should be re-established. You can then carry your work as normal

**Comment by bramalingam** [comment]
Tested teh workflow and an import post that. Everything works as expected and the connection seems to be stable. Good to merge (if this is the only blocker).

**Comment by jburel** [comment]
Waiting for next build, if https://ci.openmicroscopy.org/view/DEV/job/OMERO-DEV-merge-training/ is green, we can merge

**Comment by jburel** [comment]
@sbesson: https://ci.openmicroscopy.org/view/DEV/job/OMERO-DEV-merge-training/ is green
so I suggest that we merge today

**Comment by sbesson** [comment]
Given the state of the CI jobs (training + Java) as well as the testing performed here and on https://github.com/openmicroscopy/openmicroscopy/pull/3952, merging.

**Comment by jburel** [comment]
--no-rebase

**Pull request merged**
