### PR TITLE
removing examples as they are pushed now to webtest

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
examples are now live in webtest:

- https://github.com/openmicroscopy/webtest/pull/1
- https://github.com/openmicroscopy/webtest/pull/2

### CODE REVIEW

**Comment by sbesson** [comment]
Note this causes borken links in https://ci.openmicroscopy.org/job/OMERO-5.1-merge-docs/614/warnings3Result/ so a doc PR should also be opened.

**Comment by sbesson** [comment]
Is it sensible to add `README` under `examples/Web` or editing the `README.txt` under `examples` to link to the webtest Webapp as the placeholder for examples? /cc @hflynn

**Comment by aleksandra-tarkowska** [comment]
@sbesson would it be possible to get @snoopycrimecop to place these files from webtest instead. Then all will remain as it was before it will be just automated and we do not need to maintain it in 2 places.

**Comment by sbesson** [comment]
Generally related to https://trello.com/c/pd5ckwuZ/22-examples-files-followup for the placeholder for examples. I am not personally keen on duplicating code across non-documentation repositories. Happy to hear other's thoughts on it.

**Comment by aleksandra-tarkowska** [comment]
We already have examples moved to webtest and doc is pointing to the new location. Could we merge that PR to remove them from the main repo?

**Comment by sbesson** [comment]
Merging since the templates are actively migrated to webtest.

**Comment by aleksandra-tarkowska** [comment]
--rebased-to #4101

**Pull request merged**
