### PR TITLE
Short url

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
Original work started in #4401, this replace #4420

-----

This PR is a proposal for https://trello.com/c/sJCSdD7P/174-redirect-service

To test:

- create short url for ``/webclient/?show=image-1`` (stored as omero.model.Alias)

 ```
c=omero.client('localhost', 4064)
sess=c.createSession('root', 'secret')
conn=omero.gateway.BlitzGateway(client_obj=c)
update = conn.getUpdateService()
ns = "host/port/prefix" #or referrer
short = omero.model.AliasI()
short.setNs(omero.rtypes.rstring(ns))
short.origin = omero.rtypes.rstring("/webclient/?show=image-1")
short.details.permissions = omero.model.PermissionsI("rwr-r-")
short = update.saveAndReturnObject(short)
print short.id.val, short.origin.val
print 'short', base62.from_decimal(short.id.val)
 ```

- go to https://host:port/prefix/url/_SHORT_
- check if you were redirected to the expected location

Example: Alias:ID = 1
```
$ curl -I http://localhost:4080/url/B
HTTP/1.0 302 FOUND
Date: Wed, 20 Jan 2016 13:40:14 GMT
Server: WSGIServer/0.1 Python/2.7.10
Vary: Cookie
Content-Type: text/html; charset=utf-8
Location: http://localhost:4080/webclient/?show=image-1
```

Future work:
- storing *referrer*
- custom *name*
- UI

### CODE REVIEW

**Comment by aleksandra-tarkowska** [comment]
@joshmoore there were already some work started with 5.2dev db patch, could you please clarify how to continue?

**Comment by joshmoore** [comment]
Integration tests are failing with:

```
E       Caused by: org.postgresql.util.PSQLException: ERROR: relation "aliasannotationlink" does not exist
```

Excluding this more the moment, while I get the integration tests passing in general. We can continue the discussion while that works ongoing.

**Comment by aleksandra-tarkowska** [comment]
was db upgarded or you created new one? As mentioned above I wasn;t sure how to continue with https://github.com/openmicroscopy/openmicroscopy/pull/4435/files#diff-8634c58fd389f5664512938c925f4857

**Comment by aleksandra-tarkowska** [comment]
Was db upgraded or you created new one? It passes for me locally with freshly created db. Could you please clarify how patch should be generated to make sure we will be able to backport to develop?

**Comment by joshmoore** [comment]
It should have been a new DB (purge=true), but I'm still looking in to the build. I'll let you know ASAP.

**Comment by aleksandra-tarkowska** [comment]
I regenerated db patch, could we retry? Is build now stable?

**Comment by sbesson** [comment]
Without knowing much about the overall DB strategy adopted on the `metadata` front, I would simply warn against reusing a `db.version` and a `db.patch` which has been already merged into the breaking OMERO line (https://github.com/openmicroscopy/openmicroscopy/pull/4232).

**Comment by aleksandra-tarkowska** [comment]
closing as seems to be not needed

**Pull request closed without merging**
