### PR TITLE
Change permissions

### PR DESCRIPTION
**Pull request by jburel**
Cleanup
Make sure that the 40 tests still run.
i.e. Make sure https://ci.openmicroscopy.org/job/OMERO-5.1-merge-integration-java/ is green

### CODE REVIEW

**Comment by dominikl** [comment]
Just found one more place where assertEquals could be used: 
https://github.com/jburel/openmicroscopy/blob/change-permissions/components/tools/OmeroJava/test/integration/AdminServiceTest.java#L394

**Comment by jburel** [comment]
@dominikl: done

**Comment by dominikl** [comment]
Looks fine, Tests are passing, too. Good to merge.

**Comment by jburel** [comment]
--no-rebase

**Pull request merged**
