### PR TITLE
improve graph operation performance (rebased from develop)

### PR DESCRIPTION
**Pull request by mtbc**
With thanks to @joshmoore, adjust how graph traversal uses Hibernate to determine the exact class of model objects.

--rebased-from #4398 to `metadata` to assist testing

### CODE REVIEW

**Comment by mtbc** [comment]
Do we expect travis to pass on the `metadata` branch?

**Comment by jburel** [comment]
flake8 issue in the tests, that should be fixed so we have no problem when it is ported to the main line.

**Comment by joshmoore** [comment]
Happy to have someone try, but if it were only flake8, I'm pretty sure I would have gone ahead and done it. If there isn't an immediate fix, it might be simpler to wait on the rebasing which will be ongoing throughout January.

**Comment by mtbc** [comment]
Now #4398 is merged feel free to close or merge this as desired.

**Comment by joshmoore** [comment]
I think I'll merge this to `metadata`, but won't rebase to `metadata52` since it will be based on 5.2.2

**Pull request merged**
