### PR TITLE
Don't use Decimal for percent_fraction formatting

### PR DESCRIPTION
**Pull request by will-moore**
This removes the use of Decimal for formatting of percent fraction values (from #3309) for ND filter and attenuation.

Formatting should be as follows:
```
100 -> "100"
80.5 -> "81"
20 -> "20"
1.0 -> "1"
0.5 -> "0.5"
0.25 -> "0.3"
0 -> "0.0"
```

### CODE REVIEW

**Comment by chris-allan** [comment]
Technically looks great and is much improved over the #3309 implementation.

**Comment by joshmoore** [comment]
@gusferguson : look ok to you?

**Comment by gusferguson** [comment]
@joshmoore 
Looks fine from my POV.

**Comment by chris-allan** [comment]
The only additional suggestion I can think of right now would be to put this in a method or function called `format_for_display()` or similar so that you can use the same logic wherever it's required. That would also allow you to set up some unit tests to explicitly check for and implicitly document the desired numeric to string representation translation. But, that's nitpicking. Not required for a merge.

**Comment by dominikl** [comment]
Viewing alternate.ome (read-annotate-1/user-3/0801) I noticed two flaws:
- Attenuation is shown as 2 digits, but with different color (black instead of grey like the other properties)
- Rounding issues for Transmittance property

screen shot 2015-01-15 at 10 14 53

**Comment by chris-allan** [comment]
Then it's probably time to add the utility method outlined above @dominikl and apply it more thoroughly. Every floating point number has the possibility of displaying representation error (https://docs.python.org/2/tutorial/floatingpoint.html#representation-error) when converting to a string.

**Comment by will-moore** [comment]
Fixed a few things here.
I created a utils method for formatting percent fraction values.
This is in webclient_utils.py and is being tested by a new unit test.
The Transmittance field was not being formatted as a percent fraction.
Also fixed the appearance of the Attenuation field (wasn't being disabled before).

Unit test run like:
```
OmeroWeb wmoore$ ./setup.py test -t test/unit/test_util.py
....
test/unit/test_util.py
...
============== 1 passed in 0.01 seconds ===========
```

screen shot 2015-01-15 at 11 48 25

**Comment by chris-allan** [comment]
Looks great @will-moore. As long as Travis is happy, I am.

**Comment by mtbc** [comment]
Travis is happy. :smiley:

**Pull request merged**
