### PR TITLE
Add chown web test

### PR DESCRIPTION
**Pull request by will-moore**
Adds tests for new Chown functionality: https://github.com/ome/omero-web/pull/149/

Could maybe add more tests where we are starting with a mixed-ownership tree.
Also, the test only tests dry-run workflow, not the actual `chown`.

### CODE REVIEW

**Comment by will-moore** [comment]
Pushed that last commit yesterday but it doesn't show up in today's test - still failing at https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/502/testReport/OmeroWeb.test.integration.test_chown/TestChown/test_chown_dry_run_admin_/

**Comment by will-moore** [comment]
Yesterday this test passed (https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/507/testReport/junit/OmeroWeb.test.integration.test_chown/TestChown/test_chown_dry_run_admin_/) but today it's failing again: https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/508/testReport/junit/OmeroWeb.test.integration.test_chown/TestChown/test_chown_dry_run_admin_/

and the failing test doesn't include the last commit above:

```
        rsp = doDryRun(data)
        projs = [{'id': p.id.val, 'name': p.name.val} for p in pdit]
        assert rsp['includedObjects'] == {'Datasets': [dataset.id.val],
                                          'Images': [image.id.val]}
        assert rsp['unlinkedAnnotations'] == {'Files': [], 'Tags': [],
                                              'Comments': [], 'Others': 0}
        assert rsp['unlinkedChildren'] == {}
>       assert rsp['unlinkedParents'] == {'Projects': projs}
E       AssertionError: assert {'Projects': ...2fe781d653'}]} == {'Projects': ...3a0a2b27cc'}]}
```

Although it was merged into merge-ci branch: https://github.com/snoopycrimecop/openmicroscopy/commit/04a19aa092dc231626a090700e35985b73f722f1

Any ideas?
cc @sbesson @joshmoore

**Comment by sbesson** [comment]
@will-moore https://github.com/ome/openmicroscopy/pull/6247/commits/cc871992e59020fd5980009d9e6b40104e24bfd8 is sorting projects for the `test_chgrp` tests but the failure happens in the `test_chown` tests, no? Should the same logic as cc87199  be applied to `test_chown` ?

**Comment by will-moore** [comment]
Since https://github.com/ome/omero-web/pull/149 was excluded, tests are failing https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/535/
So need to exclude this until that PR is included again...

UPDATE - merged now... Test failed without this PR https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/654/testReport/junit/OmeroWeb.test.integration.test_chgrp/TestChgrp/test_chgrp_dry_run_user_/

**Comment by sbesson** [comment]
Merging as https://github.com/ome/omero-web/pull/149 has been integrated

**Pull request merged**
