### PR TITLE
Remove open Astex viewer

### PR DESCRIPTION
**Pull request by will-moore**
This removes all of the broken Open Astex Viewer that has not worked for sometime due to the limitations of running Java applets in modern browsers.

To test, check that a suitable image E.g. ```test_images_good/EM-data/EMD-2225.map``` and check that you **don't** get the Volume Viewer button (as in screenshot).

screen shot 2016-01-20 at 13 31 15

### CODE REVIEW

**Comment by gusferguson** [comment]
@will-moore 

Tested using cowfish - as per standup link - user-3 read-only-1

Behaves as expected.
Good to merge.

**Comment by jburel** [comment]
Still some ref e.g lib/licenses/README, OpenAstexViewer.jar will have to be removed

**Comment by will-moore** [comment]
Thanks @jburel. Fixed README and removed jar.

**Comment by jburel** [comment]
Also 
@hflynn do we want to archive this pagehttps://www.openmicroscopy.org/site/products/omero/volume-viewer-in-omero.web?
since the only version Open Astex works will be on version we no longer support

**Comment by hflynn** [comment]
Okay, I have seriously archived that before - I have it on a card and everything https://trello.com/c/vZd4hVug/300-update-or-remove-other-omero-product-pages!
I'll redo it, must have been restored by accident at some point.

**Comment by jburel** [comment]
@will-moore, @hflynn: thanks
I will try not to re-open the page ;-)
Merging

**Pull request merged**
