### PR TITLE
Repository: spring cleanup

### PR DESCRIPTION
**Pull request by sbesson**
See https://trello.com/c/2qw5o7PL/27-clean-lib-repository

This PR removes the Spring JARs from the local repository. To test it, check the build passes and review the dependencies under `share/{server,client}` in the server.

### CODE REVIEW

**Comment by mtbc** [comment]
Do we still need the `repository/org.springframework.*.jar` exclusion for release-javadoc?

**Comment by sbesson** [comment]
I would think so as this was introduced in https://github.com/openmicroscopy/openmicroscopy/pull/4177 to remove Javadoc warnings. This PR does not bump any spring framework version so I expect these warnings to be still present. That being said, one could try to remove the exclusion line and check the output of the `release-javadoc` target.

**Comment by mtbc** [comment]
That makes sense, thank you.

**Comment by mtbc** [comment]
The changes seem to make sense and a completely clean build -- no local caches anywhere -- even gets build-dev building fine. CI looks fine too, nice cleanup. Good to merge.

**Pull request merged**
