### PR TITLE
Pojos migration

### PR DESCRIPTION
**Pull request by jburel**
Rename pojos to omero.gateway.model

Make sure the build still works

Corresponding doc PR will follow

doc PR https://github.com/openmicroscopy/ome-documentation/pull/1276

--no-rebase

### CODE REVIEW

**Comment by jburel** [comment]
Travis is now happy :-)

**Comment by joshmoore** [comment]
Relaunched travis due to a new and unrelated error:

```
[nomemorytestng] FAILED: testInMemoryAndOnDiskAreProperlyDisposed on null(ome.server.utests.sessions.SessionCacheTest)
[nomemorytestng] org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.testInMemoryAndOnDiskAreProperlyDisposed() didn't finish within the time-out 5000
[nomemorytestng] 	at java.io.RandomAccessFile.open(Native Method)
[nomemorytestng] 	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:241)
[nomemorytestng] 	at net.sf.ehcache.store.compound.factories.DiskStorageFactory.<init>(DiskStorageFactory.java:99)
[nomemorytestng] 	at net.sf.ehcache.store.compound.factories.DiskOverflowStorageFactory.<init>(DiskOverflowStorageFactory.java:71)
[nomemorytestng] 	at net.sf.ehcache.store.compound.impl.OverflowToDiskStore.create(OverflowToDiskStore.java:63)
[nomemorytestng] 	at net.sf.ehcache.Cache.initialise(Cache.java:969)
[nomemorytestng] 	at net.sf.ehcache.CacheManager.addCacheNoCheck(CacheManager.java:967)
[nomemorytestng] 	at net.sf.ehcache.CacheManager.addCache(CacheManager.java:925)
[nomemorytestng] 	at org.springframework.cache.ehcache.EhCacheFactoryBean.afterPropertiesSet(EhCacheFactoryBean.java:302)
```

**Comment by jburel** [comment]
Merge develop to avoid conflicts later on due to javadoc cleaning

**Comment by jburel** [comment]
Any objection to remove breaking label for tomorrow.
cc @dominikl

**Comment by dominikl** [comment]
Ah, I forgot about this PR... No objections. I just have to add exclude comments to my develop PRs.

**Comment by jburel** [comment]
removing breaking label
hopefully everything should be stable so we can move forward with the rest
@dominikl you probably noticed the number of changes.

**Comment by jburel** [comment]
cc @pwalczysko major migration
hopefully everything should work as normal

**Comment by dominikl** [comment]
Looks good. Integration and training jobs completed without errors, also checked them with a local build; did some basic Insight workflows. If nobody else reports problems in today's PR review, good to merge from my point of view.

**Comment by sbesson** [comment]
Discussed with @jburel, given the size of the changes and since everything seems to be passing, merging this and we can tackle issues in a follow-up PRs.

**Comment by jburel** [comment]
@dominikl: you can move forward!!

**Pull request merged**
