### PR TITLE
Preview rdef start end ints

### PR DESCRIPTION
**Pull request by will-moore**
# What this PR does

Fixes an error loading Preview panel when the rendering setting channel start/end values are floats, not integers. Although we only see this error on web-dev-integration (doesn't fail locally, maybe different Python version).

```
Internal Server Error: /webclient/metadata_preview/image/5595/
Traceback (most recent call last):
...
 File "/opt/hudson/workspace/WEB-DEV-integration-deploy/OMERO.py/lib/python/omeroweb/webclient/views.py", line 1585, in load_metadata_preview
   % (act, i+1, c['start'], c['end'], reverse, color))
TypeError: %d format: a number is required, not float
```

However, this also highlighted that we shouldn't be casting start/end to Integer because some float images have very small ranges and it's important to use float start/end values.
Fixed another example of casting these to Integer in the JavaScript viewer.

# Testing this PR

1. Find/import a floating point image with small dynamic range, e.g. /test_images_good/EM-data/EMD-2225.map 
1. Adjust rendering settings, save them.
1. Re-load the Preview panel, adjust settings again then click the thumbnail showing your rendering settings to re-load the saved settings.
1. These actions should all support floating values for start/end.

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#790](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/790/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/790/consoleText) for more details.
Possible conflicts:
  - PR #5315 will-moore 'Api experimenters groups'
    - components/tools/OmeroWeb/omeroweb/webclient/views.py
  - PR #5470 will-moore 'Reverse invert webclient'
    - components/tools/OmeroWeb/omeroweb/webclient/views.py
  - Upstream changes
    - components/tools/OmeroWeb/omeroweb/webclient/views.py

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#791](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/791/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/791/consoleText) for more details.
Possible conflicts:
  - PR #5315 will-moore 'Api experimenters groups'
    - components/tools/OmeroWeb/omeroweb/webclient/views.py
  - PR #5470 will-moore 'Reverse invert webclient'
    - components/tools/OmeroWeb/omeroweb/webclient/views.py
  - Upstream changes
    - components/tools/OmeroWeb/omeroweb/webclient/views.py

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#792](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/792/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/792/consoleText) for more details.
Possible conflicts:
  - PR #5470 will-moore 'Reverse invert webclient'
    - components/tools/OmeroWeb/omeroweb/webclient/views.py
  - Upstream changes
    - components/tools/OmeroWeb/omeroweb/webclient/views.py

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#793](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/793/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/793/consoleText) for more details.
Possible conflicts:
  - PR #5470 will-moore 'Reverse invert webclient'
    - components/tools/OmeroWeb/omeroweb/webclient/views.py
  - Upstream changes
    - components/tools/OmeroWeb/omeroweb/webclient/views.py

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#794](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/794/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/794/consoleText) for more details.
Possible conflicts:
  - PR #5470 will-moore 'Reverse invert webclient'
    - components/tools/OmeroWeb/omeroweb/webclient/views.py
  - Upstream changes
    - components/tools/OmeroWeb/omeroweb/webclient/views.py

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#796](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/796/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/796/consoleText) for more details.
Possible conflicts:
  - PR #5470 will-moore 'Reverse invert webclient'
    - components/tools/OmeroWeb/omeroweb/webclient/views.py
  - Upstream changes
    - components/tools/OmeroWeb/omeroweb/webclient/views.py

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#797](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/797/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/797/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - components/tools/OmeroWeb/omeroweb/webclient/views.py

**Comment by will-moore** [comment]
@rgozim Did you get a chance to look at this?

**Comment by rgozim** [comment]
Tested on web-dev-merge. Works as described.

**Comment by jburel** [comment]
Could a robot test be doable in that case?
i.e. import a float image and open the preview panel

**Comment by will-moore** [comment]
Updated robot test to check that rdef settings (floats) are copied, pasted & applied correctly.

**Comment by jburel** [comment]
I think you should keep a mix of int and floats not all floats in the tests

**Comment by will-moore** [comment]
Why?

**Comment by will-moore** [comment]
They are both testing different actions (Copy -> 'Paste & Save'  and  click rdef thumbnail)

**Comment by jburel** [comment]
To be sure handle both correctly

**Comment by will-moore** [comment]
Added testing of copy & paste of start/end Integers into another test.

**Comment by jburel** [comment]
@will-moore thanks

**Comment by dominikl** [comment]
PR works as described, the `Test Rdef Copy Paste Save` test passed, too. But `Test Owners Rdef` failed today. Can't really rule out that this is not related to this PR. Rerun the robot tests maybe?

**Comment by dominikl** [comment]
Argh, that was yesterday's robot tests, today's not finished yet. Will check again later.

**Comment by dominikl** [comment]
Finally dev-merge-robot job ran again. There are a couple of Rdef related failed tests. I guess that might have been caused by this PR. https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-merge-robotframework/718/robot/

**Comment by will-moore** [comment]
Hmmm - All Rdef tests are passing for me locally on this branch... Let's see what test result we get today...

**Comment by will-moore** [comment]
Rdef tests all passing today: https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-merge-robotframework/719/robot/

**Comment by dominikl** [comment]
Good to merge then. Manual testing of the PR worked as described. 👍

**Pull request merged**
