### PR TITLE
move more uses of legacy Chmod to new Chmod2

### PR DESCRIPTION
**Pull request by mtbc**
Integration tests should still pass. Change of group permissions should still work from all clients.

Also adds a host of Java convenience methods for constructing Chmod2 requests.

--no-rebase as the 5.1.0 server does not offer Chmod2

### CODE REVIEW

**Comment by pwalczysko** [comment]
Downgrade in Insight from rw to private of fairly large and intricate group (read-write-1 of chown chmod db) passes.

**Comment by pwalczysko** [comment]
@ximenesuk : Unfortunately, it does not seem possible to chmod on even moderately large groups (basically just one user having data slightly cross-linked with another user) using CLI client:
```
[petr@LS25165 ~/Downloads/OMERO.server-5.1.3-42-5ade1e6-ice35-b584]$ bin/omero group perms --name read-write-3b --type private
Using session 60d63471-7906-4067-a55c-894518391b8d (owner3b@trout.openmicroscopy.org:4064). Idle timeout: 10 min. Current group: read-write-3b
Traceback (most recent call last):
  File "bin/omero", line 125, in <module>
    rv = omero.cli.argv()
  File "/Users/petr/Downloads/OMERO.server-5.1.3-42-5ade1e6-ice35-b584/lib/python/omero/cli.py", line 1431, in argv
    cli.invoke(args[1:])
  File "/Users/petr/Downloads/OMERO.server-5.1.3-42-5ade1e6-ice35-b584/lib/python/omero/cli.py", line 945, in invoke
    stop = self.onecmd(line, previous_args)
  File "/Users/petr/Downloads/OMERO.server-5.1.3-42-5ade1e6-ice35-b584/lib/python/omero/cli.py", line 1022, in onecmd
    self.execute(line, previous_args)
  File "/Users/petr/Downloads/OMERO.server-5.1.3-42-5ade1e6-ice35-b584/lib/python/omero/cli.py", line 1104, in execute
    args.func(args)
  File "/Users/petr/Downloads/OMERO.server-5.1.3-42-5ade1e6-ice35-b584/lib/python/omero/plugins/group.py", line 197, in perms
    c.submit(chmod)
  File "/Users/petr/Downloads/OMERO.server-5.1.3-42-5ade1e6-ice35-b584/lib/python/omero/clients.py", line 882, in submit
    closehandle=True)
  File "/Users/petr/Downloads/OMERO.server-5.1.3-42-5ade1e6-ice35-b584/lib/python/omero/clients.py", line 901, in waitOnCmd
    callback.loop(loops, ms)  # Throw LockTimeout
  File "/Users/petr/Downloads/OMERO.server-5.1.3-42-5ade1e6-ice35-b584/lib/python/omero/callbacks.py", line 256, in loop
    5000L, int(waited))
omero.LockTimeout: exception ::omero::LockTimeout
{
    serverStackTrace = None
    serverExceptionClass = None
    message = Command unfinished after 5.0 seconds
    backOff = 5000
    seconds = 5
}
[petr@LS25165 ~/Downloads/OMERO.server-5.1.3-42-5ade1e6-ice35-b584]$ 
```
cc @joshmoore

**Comment by mtbc** [comment]
You should find this to be so with or without this PR.

**Comment by pwalczysko** [comment]
created https://trello.com/c/GZCqaV5D/35-chmod-on-cli-not-usable

**Comment by pwalczysko** [comment]
Downgrade of read-write-3b went fine in Insight.

**Comment by pwalczysko** [comment]
Downgrade of read-write3 went fine in Web.

**Comment by mtbc** [comment]
Luckily for testing this PR it suffices to use smaller groups or to not downgrade all the way to private, so long as you can still tell that the right thing actually happened.

**Comment by pwalczysko** [comment]
Downgrade of read-write3c failed with nice message in Web as expected (Projections on others' images)

**Comment by pwalczysko** [comment]
Downgrade from read-annotate to read-only using CLI went fine as well.

**Comment by pwalczysko** [comment]
All good here. Integration tests passing as well, the problems encountered on CLI are not due to this PR, as the less-heavy downgrade passed even on CLI. 
Ready to merg.e

**Comment by mtbc** [comment]
@pwalczysko accidentally tested on trout, not eel, but the descriptions of his tests above should be helpful.

**Comment by pwalczysko** [comment]
Downgrade of read-write-1, read-only-1 and read-annotate-1 in Insight (fairly large and intricate groups) passes.

**Comment by pwalczysko** [comment]
Downgrade of read-write-3 in web (cross-linked annotations) passes.

**Comment by pwalczysko** [comment]
Downgraded of read-write-3b to read-only passes in CLI. Failure of CLI to downgrade to private was reported above, this is unchanged, but has nothing to do with this PR. @ximenesuk

**Comment by pwalczysko** [comment]
Dowgrade of read-write-3c to private fails in web with nice message as expected.

**Comment by pwalczysko** [comment]
And downgrade of read-write-3b from (now) read-only to private in Web passes.

**Comment by pwalczysko** [comment]
All good here. Ready to merge.

**Comment by pwalczysko** [comment]
(I mean now really, tested with the right artifacts on eel)

**Comment by jburel** [comment]
Thanks @pwalczysko

**Pull request merged**
