### PR TITLE
fix typo in Insight dialog

### PR DESCRIPTION
**Pull request by mtbc**
This dialog appears for the load ROI button in the measurement tool. See the diff for the change.

### CODE REVIEW

**Comment by pwalczysko** [comment]
Tested on latest (typo present) as well as merge (typo fixed). 
This PR is ready to merge.


An aside here: Was actually surprised by this half-forgotten dialog/workflow. As we are now rolling out new features, this might help to offer a UI-y way to import them, see also testing of https://github.com/openmicroscopy/bioformats/pull/2319 and the folders workflows:

   - would I be able to have masks in an xml and upload them like this ?
   - would I be able to have folders in an xml and upload them like this ?

screen shot 2016-05-13 at 10 11 59

@dgault @sbesson @dominikl @jburel

**Comment by jburel** [comment]
@pwalczysko:
The loading of ROI using XML will only handle standard shapes so no folder/masks.
Note that the format of that XML file won't follow the model, this was from the time when rois generated by the measurement tool could not be saved server side. 
This feature should be turned off unless we want people to upload "external ROIs"
but that will require the introduction of "ROIReader"

**Comment by pwalczysko** [comment]
Maybe we should turn it off then ? Obviously it elicites too much hopes ...

**Comment by jburel** [comment]
Better yes

**Comment by jburel** [comment]
@mtbc: do you want to take care of that in this PR?

**Comment by mtbc** [comment]
Would it suffice to just track the button down and do a `setVisible(false)`?

**Comment by jburel** [comment]
yes, since we may want later on to add support for "external rois"

**Comment by mtbc** [comment]
Okay, will do.

**Comment by mtbc** [comment]
Unfortunately I really don't know how to get this past travis. (Overrides in `OMEROMetadataStoreClient`.)

**Comment by dominikl** [comment]
Could build the PR locally without problem, no idea what's going on with Travis. "Load ROIs" button is removed from the toolbar, good to merge 👍

**Comment by mtbc** [comment]
--depends-on #4675

**Comment by jburel** [comment]
remove depends on to check travis again

**Pull request merged**
