### PR TITLE
Clean up VM installation folder

### PR DESCRIPTION
**Pull request by sbesson**
Following migration of the Virtual Appliance scripts to a standalone repository, this commit cleans up the duplicate scripts under the main source code repository.

/cc @manics

### CODE REVIEW

**Comment by manics** [comment]
Could `python_deps.sh` be moved into the homebrew repo? Or do non-spec files have to be outside the repo?

**Comment by sbesson** [comment]
Arguably, `python_deps.sh` should live under `omero-install`. Is there any other installation process using it apart from homebrew?

**Comment by manics** [comment]
I'd ask you the same question...

**Comment by sbesson** [comment]
Not to the best of my knowledge. Separate PR ?

**Comment by manics** [comment]
Whatever works for you, I brought it up now because if there's nothing else under `docs/install` the readme could move up a directory.

**Comment by manics** [comment]
Build looks fine, good to merge

**Comment by sbesson** [comment]
--rebased-to #4068

**Pull request merged**
