### PR TITLE
Bump to Bio-Formats 5.9.0

### PR DESCRIPTION
**Pull request by joshmoore**
Migrate to the recent Bio-Formats release. Investigatory PR.

### CODE REVIEW

**Comment by dgault** [comment]
Importing QA-21538 from https://github.com/openmicroscopy/bioformats/pull/3169 would be a good 
 simple test for the 5.9.0 features

**Comment by mtbc** [comment]
From the release announcement the formats to especially check for memoizer breakage seem to me to be in these subdirectories of `ome/data_repo/curated/`:

- cellomics
- gel
- imspector
- inveon
- leica-lif
- metamorph
- nd2
- olympus-oir
- tiff
- trestle
- volocity
- zeiss-czi

**Comment by sbesson** [comment]
Tested functionally by importing the image discussed in https://github.com/openmicroscopy/bioformats/pull/3163 in an OMERO 5.4.6 server, upgrading to the daily build including this PR. The changes are correctly propagated as the new pixels load as expected.

Unexpectedly, the memo files are invalidated during the `setId` call post-upgrade. I  tried to reproduce the invalidation by generating and loading cache files using the Bio-Formats command line tools (5.8.2 and 5.9.0) against the same Gel file with the following command:

```
./bftools/showinf -nopix -cache  -expand -separate  
```

I am able to generate a 5.8 memo file that can be reloaded by Bio-Formats 5.9 and vice-versa. 

```
[sbesson@ome-c6100-2 ~]$ ./bftools-5.8.2/showinf -nopix -cache -expand -separate -debug test.gel | grep bfmemo 
saved to temp file: /fc/homes/sbesson/.test.gel.bfmemo6994633395930931244
saved memo file: /fc/homes/sbesson/.test.gel.bfmemo (43287 bytes)
[sbesson@ome-c6100-2 ~]$ ./bftools-5.8.2/showinf -nopix -cache -expand -separate -debug test.gel | grep bfmemo 
loaded memo file: /fc/homes/sbesson/.test.gel.bfmemo (43287 bytes)
[sbesson@ome-c6100-2 ~]$ ./bftools-5.9.0/showinf -nopix -cache -expand -separate -debug test.gel | grep bfmemo
loaded memo file: /fc/homes/sbesson/.test.gel.bfmemo (43287 bytes)
[sbesson@ome-c6100-2 ~]$ head -c 8 .test.gel.bfmemo 
5.8.?[sbesson@ome-c6100-2 ~]$ rm .test.gel.bfmemo 
[sbesson@ome-c6100-2 ~]$ ./bftools-5.9.0/showinf -nopix -cache -expand -separate -debug test.gel | grep bfmemo
saved to temp file: /fc/homes/sbesson/.test.gel.bfmemo8810029097884656232
saved memo file: /fc/homes/sbesson/.test.gel.bfmemo (43287 bytes)
[sbesson@ome-c6100-2 ~]$ ./bftools-5.9.0/showinf -nopix -cache -expand -separate -debug test.gel | grep bfmemo
loaded memo file: /fc/homes/sbesson/.test.gel.bfmemo (43287 bytes)
[sbesson@ome-c6100-2 ~]$ ./bftools-5.8.2/showinf -nopix -cache -expand -separate -debug test.gel | grep bfmemo 
loaded memo file: /fc/homes/sbesson/.test.gel.bfmemo (43287 bytes)
[sbesson@ome-c6100-2 ~]$ head -c 8 .test.gel.bfmemo 
5.9.?[sbesson@ome-c6100-2 ~]$
```

I will try and pursue my investigation tomorrow on what makes the OMERO Bio-Formats stack different.

**Comment by melissalinkert** [comment]
I'm a little confused, as I'm unable to duplicate the invalidated memo file inside of OMERO that @sbesson mentions.  Steps followed:

1. Check out and build current develop (e1553954c4e702d0ff872e361e76070890f4e619)
2. ```bin/omero admin start && bin/omero import 'qa-21519/20180413 Denaturing PAGE Nuf1_M & Nuf1_M_D173A cut double stranded DNA with Mn & Annealing buffer-[FAM].gel'```
3. Back up the .bfmemo file in ```/OMERO/BioFormatsCache```:

```
melissa@hera:/OMERO/BioFormatsCache/OMERO/ManagedRepository/root_0/2018-07/10/13-58-26.773$ ls -ahl
total 80K
drwxrwxr-x 2 melissa melissa 4.0K Jul 10 14:00 .
drwxrwxr-x 3 melissa melissa 4.0K Jul 10 14:00 ..
-rw-rw-r-- 1 melissa melissa  34K Jul 10 13:58 .20180413 Denaturing PAGE Nuf1_M & Nuf1_M_D173A cut double stranded DNA with Mn & Annealing buffer-[FAM].gel.bfmemo
-rw-rw-r-- 1 melissa melissa  34K Jul 10 14:00 .20180413 Denaturing PAGE Nuf1_M & Nuf1_M_D173A cut double stranded DNA with Mn & Annealing buffer-[FAM].gel.bfmemo.582-backup
```
4. Start OMERO.web
5. Log in to web and open the full viewer for the imported image; wait a few minutes until the rendering completes.  The image is dark with white gel bands.
6. Check the output of ```ls -ahl /OMERO/BioFormatsCache/OMERO/ManagedRepository/root_0/2018-07/10/13-58-26.773``` and ```md5sum /OMERO/BioFormatsCache/OMERO/ManagedRepository/root_0/2018-07/10/13-58-26.773/.*.bfmemo``` to verify that the memo file was unchanged and the timestamp is not updated.
7. Stop OMERO.web and shutdown server
8. Check out and build the current daily merge branch including this PR (7ba39e34a7c7bd17069c118e6bfb9970038f5b48)
9. Start server and OMERO.web
10. Repeat steps 5 and 6; the image is white with dark gel bands.
11. ```grep "loaded memo file" dist/var/log/*``` to verify that the server logs show that memo files are loaded 

The memo file is never changed from what it was at import time, which makes sense given the reported ```showinf -cache``` behavior (and the goal of not breaking in 5.9.0).  For good measure, I repeated the same steps 1-11 with the only change being to use v5.4.6 (be2754b18570ea97ee4e122116304461470181df) in step 1, and still did not see any change in the memo file after import or anything else to indicate invalidation.

At the end of all tests, the server's ```BioFormatsCache``` looks like:

```
melissa@hera:/OMERO/BioFormatsCache/OMERO/ManagedRepository/root_0/2018-07/10$ ls -al *
13-58-26.773:
total 80
drwxrwxr-x 2 melissa melissa  4096 Jul 10 14:00 .
drwxrwxr-x 4 melissa melissa  4096 Jul 10 15:12 ..
-rw-rw-r-- 1 melissa melissa 34698 Jul 10 13:58 .20180413 Denaturing PAGE Nuf1_M & Nuf1_M_D173A cut double stranded DNA with Mn & Annealing buffer-[FAM].gel.bfmemo
-rw-rw-r-- 1 melissa melissa 34698 Jul 10 14:00 .20180413 Denaturing PAGE Nuf1_M & Nuf1_M_D173A cut double stranded DNA with Mn & Annealing buffer-[FAM].gel.bfmemo.582-backup

15-12-34.786:
total 80
drwxrwxr-x 2 melissa melissa  4096 Jul 10 15:14 .
drwxrwxr-x 4 melissa melissa  4096 Jul 10 15:12 ..
-rw-rw-r-- 1 melissa melissa 34698 Jul 10 15:12 .20180413 Denaturing PAGE Nuf1_M & Nuf1_M_D173A cut double stranded DNA with Mn & Annealing buffer-[FAM].gel.bfmemo
-rw-rw-r-- 1 melissa melissa 34698 Jul 10 15:14 .20180413 Denaturing PAGE Nuf1_M & Nuf1_M_D173A cut double stranded DNA with Mn & Annealing buffer-[FAM].gel.bfmemo.582-backup
melissa@hera:/OMERO/BioFormatsCache/OMERO/ManagedRepository/root_0/2018-07/10$ md5sum **/.*bfmemo*
6c62dc4b8ac63074629b49cb4d4e92e4  13-58-26.773/.20180413 Denaturing PAGE Nuf1_M & Nuf1_M_D173A cut double stranded DNA with Mn & Annealing buffer-[FAM].gel.bfmemo
6c62dc4b8ac63074629b49cb4d4e92e4  13-58-26.773/.20180413 Denaturing PAGE Nuf1_M & Nuf1_M_D173A cut double stranded DNA with Mn & Annealing buffer-[FAM].gel.bfmemo.582-backup
13a55aa3693c2fa2d19a863f0cc87dae  15-12-34.786/.20180413 Denaturing PAGE Nuf1_M & Nuf1_M_D173A cut double stranded DNA with Mn & Annealing buffer-[FAM].gel.bfmemo
13a55aa3693c2fa2d19a863f0cc87dae  15-12-34.786/.20180413 Denaturing PAGE Nuf1_M & Nuf1_M_D173A cut double stranded DNA with Mn & Annealing buffer-[FAM].gel.bfmemo.582-backup
```

The difference in md5sums between the two imports is expected, since the imports are not in-place so the file paths are different.

**Comment by sbesson** [comment]
@melissalinkert many thanks for taking the time to reproduce my steps and infirm my conclusions. I tried to reproduce using a local upgrade set up based on https://github.com/openmicroscopy/omero-test-infra/ and I reached the same behavior as described in https://github.com/openmicroscopy/openmicroscopy/pull/5804#issuecomment-403504345.

Looking at your testing procedure, I was however able to identify what differed. I used the merge build generated by https://ci.openmicroscopy.org/view/DEV/job/OMERO-DEV-merge-build/ while you built locally. Looking at the details of the JAR manifest in the CI build, it turns out the JAR is actually a merge build rather than the official release build:

```
bash-4.2$ unzip -qc  /opt/omero/server/OMERO.server-5.4.6-130-3ec8310-ice36-b1020/lib/server/formats-gpl.jar META-INF/MANIFEST.MF
Manifest-Version: 1.0
Ant-Version: Apache Ant 1.9.9
Created-By: 1.8.0_131-b11 (Oracle Corporation)
Main-Class: loci.formats.gui.ImageViewer
Implementation-Title: formats-gpl
Implementation-Version: 5.9.0
Implementation-Vendor-Id: ome
Implementation-Date: 3 July 2018
Implementation-Vendor: Open Microscopy Environment
Implementation-Build: 54cb48525c45a8d1705a009b61c6323901bd9915
Implementation-URL: https://www.openmicroscopy.org/bio-formats/
Class-Path: ome-common-5.3.2.jar kryo-2.24.0.jar minlog-1.2.jar objene
 sis-2.1.jar joda-time-2.2.jar guava-17.0.jar slf4j-api-1.7.6.jar seri
 alizer-2.7.2.jar xml-apis-1.3.04.jar xalan-2.7.2.jar ome-xml-5.5.4.ja
 r formats-bsd-5.9.0.jar specification-5.5.4.jar formats-api-5.9.0.jar
  ome-codecs-0.2.0.jar ome-jai-0.1.0.jar turbojpeg-5.9.0.jar native-li
 b-loader-2.1.4.jar jgoodies-forms-1.7.2.jar jgoodies-common-1.7.0.jar
  perf4j-0.9.13.jar metadata-extractor-2.6.2.jar xmpcore-5.1.2.jar xer
 cesImpl-2.8.1.jar ome-mdbtools-5.3.0.jar metakit-5.3.0.jar ome-poi-5.
 3.1.jar commons-logging-1.1.1.jar jxrlib-all-0.2.1.jar netcdf-4.3.22.
 jar JWlz-1.4.0.jar jhdf5-14.12.0.jar json-
```

Looking at the history is https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-build/1056/ included the version bump PR together and generated local `5.9.0` artifacts that were not invalidated.

The immediate workaround is probably to clear the content `~/.m2/repository/ome` so that the next build downloads official artifacts from our Artifactory.

In the mid-term, this raises some question, I can see a couple of ways to mitigate these types of issues:
- at the code/PR level, always exclude the version bump PR so that it does not get included in a build. Related, this means the snapshot PR should be opened straight away
- move the BIOFORMATS-DEV-merge-build job to a separate CI node so that their Maven artifacts do not get installed in the shared Maven repository used by OMERO-DEV-merge-build
- force BIOFORMATS-DEV-merge-build and/or OMERO-DEV-merge-build to use a local Maven repository rather than a shared one
- drop BIOFORMATS-DEV-merge-build https://ci.openmicroscopy.org/. Might need to review all the logic is covered by the devspace jobs ([west-ci](https://web-proxy.openmicroscopy.org/west-ci/) and/or [east-ci](https://web-proxy.openmicroscopy.org/east-ci/)) where most of the testing happens these days

**Review by sbesson — APPROVED** [review]
Retested with the following process:
- downgrading the CI server to 5.4.6
- imported the Gel image mentioned above
- upgrading the CI server to the latest merge build
- viewing the Gel image via the clients and checking the memo files via `head -c 8` and the log
Unfortunately, the memo files were *still* deleted although the latest build includes the correct version of Bio-Formats 5.9.0.

Digging into the details, the problem is that the official OMERO 5.4.6 artifacts do ship a merge build of Bio-Formats for the same reasons as the one described in https://github.com/openmicroscopy/openmicroscopy/pull/5804#issuecomment-404093358:

```
$ unzip -qc OMERO.server-5.4.6-ice35-b87/lib/server/formats-gpl.jar META-INF/MANIFEST.MF
Manifest-Version: 1.0
Ant-Version: Apache Ant 1.9.9
Created-By: 1.7.0_80-b15 (Oracle Corporation)
Main-Class: loci.formats.gui.ImageViewer
Implementation-Title: formats-gpl
Implementation-Version: 5.8.2
Implementation-Vendor-Id: ome
Implementation-Date: 18 April 2018
Implementation-Vendor: Open Microscopy Environment
Implementation-Build: 6bc10be63e934ed12e76c3ffd83ecd2bca6312a1
Implementation-URL: https://www.openmicroscopy.org/bio-formats/
Class-Path: ome-common-5.3.2.jar kryo-2.24.0.jar minlog-1.2.jar objene
 sis-2.1.jar joda-time-2.2.jar guava-17.0.jar slf4j-api-1.7.6.jar seri
 alizer-2.7.2.jar xml-apis-1.3.04.jar xalan-2.7.2.jar ome-xml-5.5.4.ja
 r formats-bsd-5.8.2.jar specification-5.5.4.jar formats-api-5.8.2.jar
  ome-codecs-0.2.0.jar ome-jai-0.1.0.jar turbojpeg-5.8.2.jar native-li
 b-loader-2.1.4.jar jgoodies-forms-1.7.2.jar jgoodies-common-1.7.0.jar
  perf4j-0.9.13.jar metadata-extractor-2.6.2.jar xmpcore-5.1.2.jar xer
 cesImpl-2.8.1.jar ome-mdbtools-5.3.0.jar metakit-5.3.0.jar ome-poi-5.
 3.1.jar commons-logging-1.1.1.jar jxrlib-all-0.2.1.jar netcdf-4.3.22.
 jar JWlz-1.4.0.jar jhdf5-14.12.0.jar json-20090211.jar
```

Short summary:
- the Bio-Formats 5.9.0 functionalities are working as expected (tested on a few formats like Cellomics, Gel and OIR files)
- I do not see a way we can enforce memo compatibility between  OMERO 5.4.6 and any future version  if Bio-Formats gets upgraded to any version
- I strongly vote for accepting the memo files cost (which is not what we initially planned) but ship the Bio-Formats 5.9.0 library in OMERO 5.4.7.
- I will take a look at what needs to happen regarding my last comments in https://github.com/openmicroscopy/openmicroscopy/pull/5804#issuecomment-404093358 for the scope of 5.4.7

**Comment by mtbc** [comment]
In response to the above, pushed https://github.com/openmicroscopy/omero_private/pull/85/commits/0cb3aaa8e4077785adcafdf87042fdc4bcaeb715.

**Pull request merged**
