### PR TITLE
specify python3

### PR DESCRIPTION
**Pull request by jburel**
# What this PR does

replace python by python3 
this is required when running on rocky9 (new CI)

### CODE REVIEW

**Comment by pwalczysko** [comment]
Is it worth to fix other occurrences of ``"python"`` to ``"python3"`` such as https://github.com/ome/openmicroscopy/blob/2db65a97ebbe80058faf5c60a4b35c693370008d/components/tools/python.xml#L27 as well here ?

**Review by pwalczysko — CHANGES_REQUESTED** [review]
Please see https://github.com/ome/openmicroscopy/pull/6363#issuecomment-1832445939

**Comment by jburel** [comment]
> Is it worth to fix other occurrences of `"python"` to `"python3"` such as
> 
> https://github.com/ome/openmicroscopy/blob/2db65a97ebbe80058faf5c60a4b35c693370008d/components/tools/python.xml#L27
> 
> as well here ?

This looks like legacy, but it does not hurt to adjust

**Comment by jburel** [comment]
@pwalczysko adjustment made

**Review by pwalczysko — APPROVED** [review]
Thank you

**Pull request merged**
