### PR TITLE
Draw empty histogram if there's no data

### PR DESCRIPTION
**Pull request by dominikl**
Tiny fix for Ticket [12994](http://trac.openmicroscopy.org/ome/ticket/12994).

- Draw a ROI
- Open Intensity view
- Deselect all channels and make sure an empty histogram plot is shown when no channel is selected (before: Insight crashed)

### CODE REVIEW

**Comment by gusferguson** [comment]
@dominikl 

Tested with OMERO.insight-5.2.0-m0-443-bf9d1d3-ice35-b64-mac eel user-3 read-only-1

Behaves as expected with redrawing after toggling off channels.
Empty histogram when no channel selected.
No crashes.
Good to merge.

Note: Refresh of histogram after moving or adjusting line can be a bit laggy or not happen at all, but that is entirely another issue - not for this PR.

**Comment by jburel** [comment]
Rebase candidate since it is a bug fix.

**Comment by jburel** [comment]
@dominikl: Can ```data``` be ```null```, if yes, better to use ```CollectionUtils.isEmpty```

**Comment by dominikl** [comment]
Thanks for the hint @jburel . Replaced isEmpty() with the appropriate CollectionUtils method, don't think a re-review is necessary for this.

**Comment by dominikl** [comment]
--rebased-to #4069

**Pull request merged**
