### PR TITLE
Chgrp not owner

### PR DESCRIPTION
**Pull request by will-moore**
This fixes https://trac.openmicroscopy.org.uk/ome/ticket/12198, https://trac.openmicroscopy.org.uk/ome/ticket/10588 and
https://trac.openmicroscopy.org.uk/ome/ticket/12305 as requested on forums: https://www.openmicroscopy.org/community/viewtopic.php?f=4&t=7484

To test:
 - Login as root (or any Admin).
 - Browse to another user's data (possibly in a group that root is not a member of).
 - Choose data in tree and right-click -> Move to Group...
 - Should see list of groups that the data owner belongs to (not including current group).
 - Click on a group. Now you should see list of containers (same as existing behaviour).
 - Can choose an existing container OR click "New" to create a new container (if moving Dataset/Images/Plates)
 - Click "New..." and enter name... Click OK.
 - Data should be moved to the chosen group and placed in new container.

 Also:
 - Test that the workflow above works when trying to move split MIFs.
 - Test workflow as owner of the data.
 - Chgrp shouldn't be enabled for group owners (only data owners or Admins).

### CODE REVIEW

**Comment by jburel** [comment]
@will-moore: Some tests will be required for the new methods e.g. new one added to view.py

**Comment by will-moore** [comment]
Ooops - flake8:
```
./components/tools/OmeroPy/src/omero/gateway/__init__.py:594:30: E261 at least two spaces before inline comment
./components/tools/OmeroPy/src/omero/gateway/__init__.py:594:31: E262 inline comment should start with '# '
```

**Comment by will-moore** [comment]
Failed unit tests:
```
test/unit/test_tree.py::TestTree::test_marshal_plate_acquisition_not_owner FAILED
test/unit/test_tree.py::TestTree::test_parse_permissions_css FAILED
etc... with...
>       if ownerid == conn.getUserId() or conn.isAdmin():
E       AttributeError: 'MockConnection' object has no attribute 'isAdmin'
omeroweb/webclient/tree.py:77: AttributeError
```

**Comment by pwalczysko** [comment]
Loading of the groups to populate the menu in top-left corner for the root takes very long on trout, but is almost instantaneous on octopus. What is the reason ?

**Comment by sbesson** [comment]
@pwalczysko can you reproduce the issue on latest?

**Comment by sbesson** [comment]
Actually scratch this comment - I can reproduce the issue on `latest` so I don't think this PR is the reason for that.

**Comment by pwalczysko** [comment]
@sbesson : Yes, absolutely can reproduce it on trout/latest. It takes 2 minutes 30 seconds for root to load the groups there.

**Comment by pwalczysko** [comment]
Agree, not a fault of this PR. But still, this single thing makes the workflow suggested by this PR a bit of a pain.

**Comment by pwalczysko** [comment]
Bug:
  - login as root to trout merge
  - go to data of user-4 in read-only-1
  - select one of the images in ``Beta catenin.liff``
  - try to move it 
  - a warning appears that you cannot split a MIF
  - use the ``Move All`` butoon
  - the dialog appears, choose the Test Group
  - in the dialog choose pre-existing dataset in the Test Group named ``rrrr``
  - click OK -> at first, nothing happens, just the button ``New`` in the bottom left corner vanishes
  - click OK again -> this time, the dialog disappears, the Activities pop up with the spinner
  - move ends up in error

```
model object graph operation failed stacktrace: ome.services.graphs.GraphException(message=may not split Fileset[1672])
at ome.services.graphs.GraphPolicyRule.recordChanges(GraphPolicyRule.java:1043)
at ome.services.graphs.GraphPolicyRule.reviewWithManyMatches(GraphPolicyRule.java:991)
at ome.services.graphs.GraphPolicyRule.access$200(GraphPolicyRule.java:56)
at ome.services.graphs.GraphPolicyRule$CleanGraphPolicy.review(GraphPolicyRule.java:826)
at ome.services.graphs.GraphTraversal.reviewObject(GraphTraversal.java:1030)
at ome.services.graphs.GraphTraversal.planOperation(GraphTraversal.java:610)
at ome.services.graphs.GraphTraversal.planOperation(GraphTraversal.java:471)
at omero.cmd.graphs.Chgrp2I.step(Chgrp2I.java:167)
at omero.cmd.graphs.ChgrpFacadeI.step(ChgrpFacadeI.java:116)
at omero.cmd.basic.DoAllI$X.step(DoAllI.java:108)
at omero.cmd.basic.DoAllI.step(DoAllI.java:325)
at omero.cmd.HandleI.steps(HandleI.java:436)
at omero.cmd.HandleI$1.doWork(HandleI.java:365)
at omero.cmd.HandleI$1.doWork(HandleI.java:361)
at sun.reflect.GeneratedMethodAccessor292.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:307)
at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
at ome.services.util.Executor$Impl$Interceptor.invoke(Executor.java:566)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
at ome.security.basic.EventHandler.invoke(EventHandler.java:154)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
at org.springframework.orm.hibernate3.HibernateInterceptor.invoke(HibernateInterceptor.java:111)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:108)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
at ome.tools.hibernate.ProxyCleanupFilter$Interceptor.invoke(ProxyCleanupFilter.java:241)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
at ome.services.util.ServiceHandler.invoke(ServiceHandler.java:116)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
at com.sun.proxy.$Proxy72.doWork(Unknown Source)
at ome.services.util.Executor$Impl.execute(Executor.java:447)
at omero.cmd.HandleI.run(HandleI.java:359)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
at ome.services.util.Executor$Impl$1.call(Executor.java:488)
at java.util.concurrent.FutureTask.run(FutureTask.java:262)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:744)
, message: 
```

**Comment by pwalczysko** [comment]
Similar setup as in the above comment. The only difference is that I did not try to split the MIF. Moved images were ``test_images_good/bruker/`` -> tried to move the whole dataset.
Got

```
ailed stacktrace: ome.conditions.ReadOnlyGroupSecurityViolation: Cannot link to ome.model.containers.Dataset:Id_2753
Current user (root) is an admin or the owner of
the private group (Test Group=rw----). It is not allowed to
link to users' data.
at ome.security.basic.OmeroInterceptor.evaluateLinkages(OmeroInterceptor.java:513)
at ome.security.basic.OmeroInterceptor.onSave(OmeroInterceptor.java:160)
at org.hibernate.event.def.AbstractSaveEventListener.substituteValuesIfNecessary(AbstractSaveEventListener.java:414)
at org.hibernate.event.def.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:293)
at org.hibernate.event.def.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:204)
at org.hibernate.event.def.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:144)
at org.hibernate.event.def.DefaultMergeEventListener.saveTransientEntity(DefaultMergeEventListener.java:415)
at org.hibernate.event.def.DefaultMergeEventListener.mergeTransientEntity(DefaultMergeEventListener.java:341)
at org.hibernate.event.def.DefaultMergeEventListener.entityIsTransient(DefaultMergeEventListener.java:303)
at org.springframework.orm.hibernate3.support.IdTransferringMergeEventListener.entityIsTransient(IdTransferringMergeEventListener.java:59)
at ome.security.basic.MergeEventListener.entityIsTransient(MergeEventListener.java:161)
at org.hibernate.event.def.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:258)
at ome.security.basic.MergeEventListener.onMerge(MergeEventListener.java:94)
at org.hibernate.event.def.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:84)
at ome.security.basic.MergeEventListener.onMerge(MergeEventListener.java:80)
at org.hibernate.impl.SessionImpl.fireMerge(SessionImpl.java:861)
at org.hibernate.impl.SessionImpl.merge(SessionImpl.java:845)
at org.hibernate.impl.SessionImpl.merge(SessionImpl.java:849)
at ome.logic.UpdateImpl.internalMerge(UpdateImpl.java:274)
at ome.logic.UpdateImpl$2.run(UpdateImpl.java:121)
at ome.logic.UpdateImpl$2.run(UpdateImpl.java:118)
at ome.logic.UpdateImpl.doAction(UpdateImpl.java:312)
at ome.logic.UpdateImpl.doAction(UpdateImpl.java:303)
at ome.logic.UpdateImpl.saveAndReturnObject(UpdateImpl.java:118)
at ome.services.blitz.impl.commands.SaveI.step(SaveI.java:61)
at omero.cmd.basic.DoAllI$X.step(DoAllI.java:108)
at omero.cmd.basic.DoAllI.step(DoAllI.java:325)
at omero.cmd.HandleI.steps(HandleI.java:436)
at omero.cmd.HandleI$1.doWork(HandleI.java:365)
at omero.cmd.HandleI$1.doWork(HandleI.java:361)
at sun.reflect.GeneratedMethodAccessor292.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:307)
at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
at ome.services.util.Executor$Impl$Interceptor.invoke(Executor.java:566)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
at ome.security.basic.EventHandler.invoke(EventHandler.java:154)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
at org.springframework.orm.hibernate3.HibernateInterceptor.invoke(HibernateInterceptor.java:111)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:108)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
at ome.tools.hibernate.ProxyCleanupFilter$Interceptor.invoke(ProxyCleanupFilter.java:241)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
at ome.services.util.ServiceHandler.invoke(ServiceHandler.java:116)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
at com.sun.proxy.$Proxy72.doWork(Unknown Source)
at ome.services.util.Executor$Impl.execute(Executor.java:447)
at omero.cmd.HandleI.run(HandleI.java:359)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
at ome.services.util.Executor$Impl$1.call(Executor.java:488)
at java.util.concurrent.FutureTask.run(FutureTask.java:262)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:744)
, message: Cannot link to ome.model.containers.Dataset:Id_2753
Current user (root) is an admin or the owner of
the private group (Test Group=rw----). It is not allowed to
link to users' data., obj: omero.model.ProjectDatasetLinkI@4db5b9db
```

**Comment by pwalczysko** [comment]
Additional info to the bug https://github.com/openmicroscopy/openmicroscopy/pull/3420#issuecomment-72884815 - root is NOT an owner of the Test Group, see below.


screen shot 2015-02-04 at 16 20 40

**Comment by pwalczysko** [comment]
Note that the bruker move from https://github.com/openmicroscopy/openmicroscopy/pull/3420#issuecomment-72884815 was successfull when the owner of the data was performing the move.

**Comment by pwalczysko** [comment]
Move is disabled for a group owner (which is NOT an admin). This is as expected.

In summary, 2 bugs found.

**Comment by mtbc** [comment]
So, is the failure when moving images to a dataset in a private group where the owner of the images is not the owner of the dataset?

**Comment by will-moore** [comment]
@pwalczysko Thanks for the testing. Looks like I need to disable choosing or creating a target container when Admin moves someone else's data to a private group.
The slow loading times of the group list for Admins is a known issue and is only noticeable when you have a large number of groups (E.g. several hundred, usually on a server that has has automated tests run). I have discussed this with @aleksandra-tarkowska - we'll look at it ASAP.

**Comment by pwalczysko** [comment]
@will-moore : As just discussed, to restrict the behaviour in private group is not necessary. See Import As feature in Insight as an example, where the admin HAS the power to create P/D (which BELONGS to DATA OWNER, NOT ADMIN) at the import stage.

**Comment by will-moore** [comment]
@joshmoore @mtbc Seems that the bug above is when Admin moves a user's Dataset to a user's Private group and tries to link it to an existing user's Project.
Failing test is in the previous commit:

```
$ cd OmeroWeb
$ ./setup.py test -t test/integration/test_chgrp.py -k test_chgrp_old_container
....
>               assert o['status'] == 'finished'
E               assert 'failed' == 'finished'
E                 - failed
E                 + finished

test/integration/test_chgrp.py:243: AssertionError
------------------------------------------------------------------------------------------------------------ Captured stdout call ------------------------------------------------------------------------------------------------------------
failed stacktrace: ome.conditions.ReadOnlyGroupSecurityViolation: Cannot link to ome.model.containers.Dataset:Id_3902
Current user (root) is an admin or the owner of
the private group (f3a3a7b1-a281-41f8-aa70-5f7ad5aedd8a=rw----). It is not allowed to
link to users' data.
	at ome.security.basic.OmeroInterceptor.evaluateLinkages(OmeroInterceptor.java:513)
	at ome.security.basic.OmeroInterceptor.onSave(OmeroInterceptor.java:160)
	at org.hibernate.event.def.AbstractSaveEventListener.substituteValuesIfNecessary(AbstractSaveEventListener.java:414)
```

**Comment by mtbc** [comment]
So the project and dataset pre-exist and are both owned by the same user? And then there is a chgrp of the Dataset and a save of the project-dataset link within the one doall? I wonder if we have an existing integration test anything close to this.

**Comment by will-moore** [comment]
I don't think we have integration tests of Admin on another user's data. But I'm happy to write one if that is preferable to web integration tests?

**Comment by mtbc** [comment]
Integration tests are great. I haven't actually much touched the security stuff yet but I can definitely investigate!

Possible interim workaround: Does it work if you put it in the project entirely separately from the chgrp, so no doall?

**Comment by will-moore** [comment]
Failing integration test added for Admin moving user's Dataset to a user's Project in a private group.

**Comment by will-moore** [comment]
Previous commit is trying to address failure in Robot 'Test Channel Rename' https://ci.openmicroscopy.org/view/Failing/job/OMERO-5.1-merge-robotframework/147/console

**Comment by will-moore** [comment]
Fixed the first MIF error above. Main blocker for this PR is now the SecurityViolation bug. Created a ticket http://trac.openmicroscopy.org/ome/ticket/12723 and integration test https://github.com/will-moore/openmicroscopy/commit/2615f1af31ad397d7e8d2e0a95adcfb0fe9ec93c @joshmoore any idea how long this might take to address? If it's not easily fixable then I'll probably need to disable Admin moving user's data to user's existing P/D in private group before we can merge this PR.

**Comment by joshmoore** [comment]
@will-moore: If I'm understanding correctly, I'd [also](http://trac.openmicroscopy.org/ome/ticket/12723#comment:2) say that I wouldn't expect this to work. But if you set the owner of the link at https://github.com/will-moore/openmicroscopy/commit/2615f1af31ad397d7e8d2e0a95adcfb0fe9ec93c#diff-9b2f5789b1ddafb92cb7c1509d307f1cR1211 then this should work, e.g:

```
link.details.owner = user
```

**Comment by pwalczysko** [comment]
All works fine here, all the moves from comments above work fine. Also tried to move to read-write, Orphaned, new P/D, etc.

**Comment by knabar** [comment]
@joshmoore quick look at the code did not raise any flags

**Comment by sbesson** [comment]
Note at least one chgrp test was failing in https://ci.openmicroscopy.org/view/Failing/job/OMERO-5.1-merge-robotframework/150/

**Comment by joshmoore** [comment]
Sorry, @sbesson, loaded from @knabar's email and didn't see yours. @will-moore, I'll leave looking at the robot tests with you.

**Pull request merged**
