### PR TITLE
Training advanced

### PR DESCRIPTION
**Pull request by jburel**
# What this PR does

Review training examples
Some of the work started https://github.com/openmicroscopy/openmicroscopy/pull/4914
More cleaning done

Delete some duplicate examples since they are already in  https://github.com/openmicroscopy/omero-example-scripts

# Testing this PR

Check that the examples pass

# Related reading

see https://github.com/openmicroscopy/openmicroscopy/pull/4914

1. background for understanding this PR

2. what this PR assists, fixes, or otherwise affects

### CODE REVIEW

**Comment by will-moore** [comment]
Unfortunately tests failing with

```
  File "/opt/hudson/workspace/OMERO-DEV-merge-training/src/examples/Training/python/Tables.py", line 130, in <module>
    saved_table = conn.c.sf.sharedResources().open_table(orig_table_file._obj)
AttributeError: 'SharedResourcesPrx' object has no attribute 'open_table'
```

**Comment by jburel** [comment]
Too much cleaning :-)

**Comment by jburel** [comment]
https://ci.openmicroscopy.org/job/OMERO-DEV-merge-training/456/ is green

**Comment by will-moore** [comment]
Looks good. Tests ✅. Good to merge.

**Pull request merged**
