### PR TITLE
Mask python training example

### PR DESCRIPTION
**Pull request by joshmoore**
Carry-on from:

 * gh-4412
 * http://lists.openmicroscopy.org.uk/pipermail/ome-users/2016-January/005804.html

Thanks to @emilroz

### CODE REVIEW

**Comment by will-moore** [comment]
@joshmoore https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-merge-training/214/console failed with
```
File "/opt/hudson/workspace/OMERO-DEV-merge-training/src/examples/Training/python/ROIs.py", line 141, in <module>
    mask_array = mask_array.tobytes()
AttributeError: 'numpy.ndarray' object has no attribute 'tobytes'
```

**Comment by sbesson** [comment]
@will-moore: reading the commit history, I suspect 69c1e50e0afe7ee96de114806a1b8e2c145334f6 will fix this failure in tomorrow's build

**Comment by will-moore** [comment]
This seems to be working fine.
I'd really like to try and display the mask in web (as on https://trello.com/c/H1MePy2A/124-mask-support-in-web) and wondered if @emilroz had the "reverse" code in hand to get from OMERO into a PIL image (mask) ideally. Otherwise I should be able to work something out, but didn't want to duplicate effort etc.

**Comment by emilroz** [comment]
@will-moore we've have never looked into doing it the other way round (it should be rather straight forward), since the rendering engine has the ability to render the masks. In principle you can request an image with a mask on it from the server. The only problem doing it this way is the fact that it supports only the masks that match the image plane size.

**Comment by will-moore** [comment]
@joshmoore I wonder if it's slightly nicer to use something like this instead of random array, since then if you're doing some subsequent work with the mask, you have some idea if it's working/looking right?
```
# Create [0, 1] mask
def f(x, y):
    return (x * y) % 2
mask_array = numpy.fromfunction(f, (mask_w, mask_h))
```

**Comment by joshmoore** [comment]
Rebased and force pushed on top of 4412 and added @will-moore's non-random mask suggestion.

**Comment by will-moore** [comment]
Working fine. Good to merge.

**Pull request merged**
