### PR TITLE
Add parents and children to omero obj

### PR DESCRIPTION
**Pull request by ximenesuk**
This PR is a side-effect of creating a CLI command to test gh-4531 but rather than throw it away I have tidied it up and added some tests. It may or may not be useful!

The PR adds subcommands to `omero obj` to find `parents` and `children` of specific objects. The type(s) of the relatives must be specified.

Testing
-------
Create come Datasets, import an Image, add it to the Datasets. Tag and Annotate the Image.
```
$ omero obj children Image:101 TagAnnotation
TagAnnotation:101,102
$ omero obj children Image:101 Annotation
TagAnnotation:101,102
FileAnnotation:103
$ omero obj parents Image:101 Dataset
Dataset:1,2
$ omero obj parents Image:101 Dataset Fileset
Fileset:101
Dataset:1,2
$ omero obj parents Image:101 Annotation

$
```

### CODE REVIEW

**Comment by manics** [comment]
Just so you're aware, the annotations bit partially overlaps with `omero metadata`:
```
$ OMERO.py/bin/omero metadata allanns Image:179693 --parents
MapAnnotation:2501962
MapAnnotation:2502052
WARNING: Failed to get annotations for WellSample:165988
MapAnnotation:2502052
MapAnnotation:2501962
MapAnnotation:364213
FileAnnotation:1554813
FileAnnotation:1997102
FileAnnotation:2281412
```
```
$ OMERO.py/bin/omero metadata allanns Image:179693 --parents --report
WARNING: Failed to get annotations for WellSample:165988
Image:179693
  MapAnnotation:2501962
    ns: openmicroscopy.org/mapr/gene
    description: 
    date: 2016-08-08T23:24:41
    value:
      Gene Identifier=ENSG00000117399
      Gene Identifier URL=http://www.ensembl.org/id/ENSG00000117399
      Gene Symbol=CDC20
  MapAnnotation:2502052
    ns: openmicroscopy.org/omero/bulk_annotations
    description: 
    date: 2016-08-08T23:24:44
    value:
      Organism=Homo sapiens
      Cell Line=HeLa
      siRNA Identifier=s2748
      Sense Sequence=CGAAAUGACUAUUACCUGATT
      Antisense Sequence=UCAGGUAAUAGUCAUUUCGGA
      Reagent Design Gene Annotation Build=GRCh37, Ensembl release 61, Feb 2011
      Analysis Gene Annotation Build=GRCh37, Ensembl release 61, Feb 2011
      Control Type=positive control
      Control Comments=early mitotic phenotype
      Quality Control=fail
      Channels=H2B- mCherry/Cy3:chromatin;eGFP:nuclear lamina and report on nuclear envelope breakdown
  WellSample:165988
    Well:67070
      MapAnnotation:2502052
        ns: openmicroscopy.org/omero/bulk_annotations
        description: 
        date: 2016-08-08T23:24:44
        value:
          Organism=Homo sapiens
          Cell Line=HeLa
          siRNA Identifier=s2748
          Sense Sequence=CGAAAUGACUAUUACCUGATT
          Antisense Sequence=UCAGGUAAUAGUCAUUUCGGA
          Reagent Design Gene Annotation Build=GRCh37, Ensembl release 61, Feb 2011
          Analysis Gene Annotation Build=GRCh37, Ensembl release 61, Feb 2011
          Control Type=positive control
          Control Comments=early mitotic phenotype
          Quality Control=fail
          Channels=H2B- mCherry/Cy3:chromatin;eGFP:nuclear lamina and report on nuclear envelope breakdown
      MapAnnotation:2501962
        ns: openmicroscopy.org/mapr/gene
        description: 
        date: 2016-08-08T23:24:41
        value:
          Gene Identifier=ENSG00000117399
          Gene Identifier URL=http://www.ensembl.org/id/ENSG00000117399
          Gene Symbol=CDC20
      Plate:422
        Screen:102
          MapAnnotation:364213
            ns: openmicroscopy.org/omero/client/mapAnnotation
            description: 
            date: 2015-10-07T07:27:26
            value:
              PubMed ID=24943848
              PubMed URL=http://www.ncbi.nlm.nih.gov/pubmed/24943848
              PMC ID=PMC4142622
              PMC URL=http://europepmc.org/search?query=PMC4142622
              Publication DOI=http://dx.doi.org/10.1091/mbc.E13-04-0221
          FileAnnotation:1554813
            ns: openmicroscopy.org/omero/bulk_annotations
            description: bulk_annotations
            date: 2016-07-25T23:43:09
            file: OriginalFile:8069296
              name: bulk_annotations
              size: 796984
          FileAnnotation:1997102
            ns: openmicroscopy.org/omero/features/0.2
            description: 
            date: 2016-07-26T11:53:03
            file: OriginalFile:8069317
              name: idr0002-heriche-condensation-screenA-plate-all.h5
              size: 1065853300065
          FileAnnotation:2281412
            ns: openmicroscopy.org/omero/bulk_annotations/config
            description: 
            date: 2016-08-08T18:46:40
            file: OriginalFile:8072483
              name: idr0002-screenA-bulkmap-config.yml
              size: 3289
```

**Comment by ximenesuk** [comment]
Yes, a knew there was an overlap. (We can also create and link Tags using `obj`) This was more of a prospective PR before I trash the branch altogether?  Does it add anything? Is it just confusing? Etc. Comments welcome!

**Comment by manics** [comment]
Rename it `tree`? https://github.com/openmicroscopy/design/blob/master/cli_tree.md

**Comment by manics** [comment]
It should be useful, only question is whether this is the right home for it.

**Comment by ximenesuk** [comment]
Yes, https://github.com/openmicroscopy/openmicroscopy/pull/4777#issuecomment-238626475 makes sense, the commands (or the same functionality should sit under https://github.com/openmicroscopy/design/blob/master/cli_tree.md

**Comment by joshmoore** [comment]
btw, I'd think handling this naming discussion is what it would take to put https://github.com/openmicroscopy/openmicroscopy/pull/4765 on the mainline.

**Comment by joshmoore** [comment]
I just found https://github.com/ximenesuk/design/blob/5bac59ef6fa544c380aa764d6f4c8f42a45b8ad0/cli_tree.md -- :+1:

**Comment by jburel** [comment]
This has been merged to master
https://github.com/openmicroscopy/design/blob/master/cli_tree.md

**Pull request closed without merging**
