### PR TITLE
Newimage

### PR DESCRIPTION
**Pull request by jburel**
Fix issue https://github.com/openmicroscopy/openmicroscopy/issues/4033

To Test:
 * Open any image an save it to TIFF. 
 * Open the newly created TIff image
 * Save that image to OMERO (Plugins > OMERO > Save Image(s) to OMERO).

cc @stelfrich, @bramalingam 

Also test the parsing of the string with @bramalingam macro

### CODE REVIEW

**Comment by bramalingam** [comment]
Both the macro and the 'File-->Open" of tiff images, work as expected. Good to merge.

**Comment by stelfrich** [comment]
I find the handling of the issue a bit misleading, tbh.

With this PR, the SAXParseException is logged and everything continues as usual. As an unexperienced user, if you haven't had the log window open before, it will popup and show you an error but the import can continue. On first sight of the Exception, I killed Fiji because I thought the import wasn't possible..

**Comment by jburel** [comment]
@stelfrich: we can certainly check before building the Document if the string "looks like" XML so we won't mislead the user.

**Comment by stelfrich** [comment]
@jburel I have made some slight changes based on this PR. But I do I proceed now? I can't directly push to the PR, can I?

**Comment by jburel** [comment]
@stelfrich: You will have to open a PR against this PR. Then I will merge your changes and they will be included in the build

**Comment by stelfrich** [comment]
@jburel Do have an idea where this error is logged during the parsing process:
```[Fatal Error] :1:1: Content is not allowed in prolog.```

I am a bit lost but I think we should get rid of the too, to not confuse users..

**Comment by jburel** [comment]
@stelfrich: This is due to the creation of the Document, it might be better to actually check before creating the Document if the description "looks like " some XML.
I will look at that today

**Comment by bramalingam** [comment]
No errors found in the log. Both workflows : opening tiff from local disk (using file-->open) and change of image properties using the macro, work as expected. Good to merge, according to me.!

**Comment by sbesson** [comment]
@jburel: no more commit coming on this PR?

**Comment by jburel** [comment]
That one is done.

**Comment by jburel** [comment]
--rebased-to #4138

**Pull request merged**
