### PR TITLE
Show image in well develop

### PR DESCRIPTION
**Pull request by will-moore**
This is https://github.com/openmicroscopy/openmicroscopy/pull/4241/ rebased onto develop (with extra changes to work with new jsTree).

Fixes ```webclient/?show=image-123``` when the image is in a well.

 - To test, pick ID of an image in a Well and use it in the link above.
 - This will browse to the well containing the image - Not necessarily the correct well-index (just first index).

### CODE REVIEW

**Comment by joshmoore** [comment]
```
./components/tools/OmeroWeb/test/integration/test_show.py:1569:80: E501 line too long (80 > 79 characters)
```

**Comment by gusferguson** [comment]
@will-moore 

Tested using https://cowfish.openmicroscopy.org/merge/webclient/ user-3 read-annotate-1

Copied Image ID from well A4 - 14383 - screenshot 1
Tried URL https://cowfish.openmicroscopy.org/merge/webclient/show=?image-14383 - 404 error message - screenshot 2
Also tried well ID - 307282 - also 404 - screenshot 3

Doesn’t work in Safari, Chrome or Firefox. No useful feedback from Firefox developer tools.

webclient

omero web - support

omero web - support

**Comment by will-moore** [comment]
Apologies @gusferguson - my mistake. I got the url wrong in the description. Fixed now, sorry!

**Comment by will-moore** [comment]
https://cowfish.openmicroscopy.org/merge/webclient/?show=image-14383 seems to be working for user-3

**Comment by gusferguson** [comment]
@will-moore 

Tested with https://cowfish.openmicroscopy.org/merge/ user-3 read-annotate-1

Behaves as expected for both image ID and well ID.
Good to merge.

**Pull request merged**
