### PR TITLE
Importer ConcurrentModificationExceptions

### PR DESCRIPTION
**Pull request by dominikl**
# What this PR does

Fixes some rare, randomly occurring `ConcurrentModificationException`s in the Importer component.

# Testing this PR

Make sure the Importer component still works. I couldn't find a way to trigger the initial bug, it's a random timing issue, so there's not really a specific test to perform to make sure the bug is fixed.

# Related reading

https://trac.openmicroscopy.org/ome/ticket/13266

### CODE REVIEW

**Comment by jburel** [comment]
Did you notice some performance issue when working with a large number of items?

**Comment by jburel** [comment]
Importer works. 
one thing I noticed see screenshot, in one case the thumbnail was not updated (folder)
folder

files
.
I don't think it is related to this PR.

**Comment by dominikl** [comment]
Thanks @jburel . I've not tested it with hundreds of files. I'll do so, to check if there are performance issues.

**Comment by dominikl** [comment]
Imported a folder with 1800 images, noticed no problems. Well, the UI struggles a bit at the end, but same without the PR.

**Comment by jburel** [comment]
The UI struggles mainly due to the number of components to paint
Thanks for the fix

**Pull request merged**
