### PR TITLE
Testlib

### PR DESCRIPTION
**Pull request by atarkowska**
# What this PR does

OMERO.py should provide basic testing helpers as a part of the package to simplify writing OMERO.web apps tests. 

# Testing this PR

check if integration jobs are green 
- https://ci.openmicroscopy.org/job/OMERO-DEV-merge-integration-python/
- https://ci.openmicroscopy.org/job/OMERO-DEV-merge-integration-Python27/

if that PR is considered on breaking, jobs should be green as well

# Related reading

This will be consumed by https://github.com/ome/omero-mapr/pull/4 once is at least in a merge build

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#509](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/509/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/509/consoleText) for more details.
Possible conflicts:
- Conflict detection failed
  - components/tools/OmeroPy/test/integration/scriptstest/test_figure_export_scripts.py
- PR #4914 jburel 'Remove Image.fromarray'
  - components/tools/OmeroPy/test/integration/test_bigImages.py
  - components/tools/OmeroPy/test/integration/scriptstest/test_make_movie.py

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#510](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/510/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/510/consoleText) for more details.
Possible conflicts:
- Conflict detection failed
  - components/tools/OmeroPy/test/integration/scriptstest/test_figure_export_scripts.py
- PR #4914 jburel 'Remove Image.fromarray'
  - components/tools/OmeroPy/test/integration/test_bigImages.py
  - components/tools/OmeroPy/test/integration/scriptstest/test_make_movie.py

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#511](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/511/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/511/consoleText) for more details.
Possible conflicts:
- Conflict detection failed
  - components/tools/OmeroPy/test/integration/scriptstest/test_figure_export_scripts.py
- PR #4914 jburel 'Remove Image.fromarray'
  - components/tools/OmeroPy/test/integration/test_bigImages.py
  - components/tools/OmeroPy/test/integration/scriptstest/test_make_movie.py

**Comment by atarkowska** [comment]
PR included in today's build
- https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/512/console
- https://ci.openmicroscopy.org/job/OMERO-DEV-breaking-push/851/console

all the tests are passing:
- https://ci.openmicroscopy.org/job/OMERO-DEV-merge-integration-python/417/testReport/
- https://ci.openmicroscopy.org/job/OMERO-DEV-merge-integration-Python27/379/testReport/
- https://ci.openmicroscopy.org/job/OMERO-DEV-breaking-integration-Python27/89/testReport/
- https://ci.openmicroscopy.org/job/OMERO-DEV-breaking-integration/878/console is broken!

**Comment by jburel** [comment]
Conceptually, the changes make sense and will make things easier to develop clients, and also could be used as documentation, show good practise
This will have to be treated like "public API"
Do we have a card that we can describe the various steps and which milestone they will be done
naming, granularity of package?

**Comment by atarkowska** [comment]
we have one now https://trello.com/c/ECAKLbUr/224-omero-testlib :)

**Comment by atarkowska** [comment]
What is blocking this PR from being merged? I thought was agreed to get it in, as is blocking mapr testing. It is really bad practice to put app on production server without testing on CI

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#513](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/513/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/513/consoleText) for more details.
Possible conflicts:
- Conflict detection failed
  - components/tools/OmeroPy/test/integration/scriptstest/test_figure_export_scripts.py
- PR #4914 jburel 'Remove Image.fromarray'
  - components/tools/OmeroPy/test/integration/test_bigImages.py
  - components/tools/OmeroPy/test/integration/scriptstest/test_make_movie.py

**Comment by jburel** [comment]
I am tagging m5 today I did not want to include it in the tagged version

**Comment by jburel** [comment]
Merging so that @aleksandra-tarkowska can add tests for mapr
Added points to the card above, key points to go over before the release:
- name
- existing methods since this will now have to be treated as any "API"

**Pull request merged**
