### PR TITLE
plate_grid

### PR DESCRIPTION
**Pull request by jburel**
check subset

This should fix
https://py3-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/lastCompletedBuild/testReport/OmeroWeb.test.integration.test_plategrid/TestScreenPlateTables/test_get_plate_table/

Related  https://github.com/ome/omero-web/pull/54

cc @will-moore

### CODE REVIEW

**Comment by will-moore** [comment]
I think the test is failing because the omero-web PR https://github.com/ome/omero-web/pull/3 was closed (to avoid merge conflict with https://github.com/ome/omero-web/pull/54), but the tests added for that PR are still open:
https://github.com/ome/openmicroscopy/pull/6055

I can close the tests PR too, to get things green again...

**Comment by will-moore** [comment]
So, this PR shouldn't be needed.

**Comment by jburel** [comment]
Looking at the code, I see the addition in the response
Either we look for a subset or we update the test(s) when the response return more contents

**Comment by will-moore** [comment]
The test is failing with
```
E         Right contains 1 more item:
E         {'column_types': ['WellColumn', 'StringColumn']}
```
These are missing from the response ```rspJson['data']``` because the PR that adds them is closed https://github.com/ome/omero-web/pull/3 but the PR that updates the test to expect them is still open: https://github.com/ome/openmicroscopy/pull/6055/files#diff-5661a8e1af9aa43c758c60b186a7e50fR429

Either we need to close both PRs or open both PRs, but we don't need to update the comparison code since that's working just fine.

**Comment by will-moore** [comment]
If you could close this, then I'll also close #6055 which should make the tests green.

**Comment by sbesson** [comment]
Closing as per https://github.com/ome/openmicroscopy/pulls#issuecomment-551020023, let's see if the next build is green.

**Comment by will-moore** [comment]
https://py3-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/47/testReport/OmeroWeb.test.integration.test_plategrid/TestScreenPlateTables/test_get_plate_table/ passing now

**Pull request closed without merging**
