### PR TITLE
log parameters and results of graph requests

### PR DESCRIPTION
**Pull request by mtbc**
Adjust ` etc/logback.xml` such that `omero.cmd.graphs` is logged at `DEBUG`, then try some graph requests (delete, move, whatever you like) and see that the request parameters and the response values are logged in `Blitz-0.log`.

--no-rebase

### CODE REVIEW

**Comment by ximenesuk** [comment]
This looks good, I can see requests and response logged for simple commands and skiphead commands. (Very useful too!). Good to merge.

**Comment by sbesson** [comment]
Thanks @mtbc, merging this. Follow-up question is whether the `omero.cmd.*` requests/responses should be logged at the `INFO` level like other server methods?

**Comment by mtbc** [comment]
Not sure. There *is* the usual logging from `HandleI`, etc., available already, so you already see a bit of what happened, the steps going by, etc. I suppose the question is, if that's enough. Would want to avoid the full parameter values at INFO as some of them may include tens of thousands of integers.

**Comment by joshmoore** [comment]
Yeah, 10K integers (longs!) sounds bad. What `ServiceHandler` does is to elide anything beyond 3 entries. I've missed the old-service-style logging, so I guess my main question is whether or not we could get `omero.cmd.*` logging to a place where in the general case, we're happy gleaming information from the log *without* needing to restort to `s/DEBUG/INFO/`

**Comment by mtbc** [comment]
It certainly might be worth a card if you have an idea what you'd like to see. Anything that helps us understand what's going on when the server does something undesirable is welcome!

**Comment by joshmoore** [comment]
@mtbc : coming back to this, thoughts on using a method like https://github.com/openmicroscopy/openmicroscopy/blob/v5.2.1/components/server/src/ome/services/util/ServiceHandler.java#L344 for reducing the output

**Comment by mtbc** [comment]
@joshmoore: I definitely want to be able to get to see the full output. But perhaps it could truncate the long lists only if debug level isn't TRACE, would that make sense?

**Pull request merged**
