### PR TITLE
Fix ice.config modification when using bin/omero admin ports --prefix

### PR DESCRIPTION
**Pull request by sbesson**
Without this PR, calling `admin ports` appends `omero.port=PORT` to the `ice.config`. This results in the following calls:

```
bin/omero admin ports --prefix=1
bin/omero admin ports --prefix=1 --revert
```

will append the following tow lines

```
omero.port=14064
omero.port=4064
```

This PR fixes the `ice.config` modification logic in `bin/omero admin ports` by:
1- looking for an `omero.port=xxx` line in ICE_CONFIG and replacing it using the new port (as for the other configuration files)
2- if not present, looking for the `## omero.port=xxx` line which ships with the default `ice.config` and uncommenting it
3- if 2 is not applicable, appending `omero.port=xxx` as done previously

--no-rebase

### CODE REVIEW

**Comment by mtbc** [comment]
This seems to work fine and the tests pass.

If I try a few `--revert`s for wrong prefixes, then I get a growing number of `omero.port=4064` lines; want to fix that here too? Otherwise good to merge.

**Comment by sbesson** [comment]
@mtbc: you mean the following scenario?

```
bin/omero admin ports --prefix=1
bin/omero admin ports --prefix=2 --revert
```
No this is not covered as we speak and it may be a good occasion to do so (with tests). Will push additional commits.

**Comment by mtbc** [comment]
Right, that one. :+1:

**Comment by sbesson** [comment]
Pushed.

**Comment by mtbc** [comment]
Tests look good, e.g.,
```
test/unit/clitest/test_admin.py::TestAdminPorts::testRevert[True-None] PASSED
test/unit/clitest/test_admin.py::TestAdminPorts::testRevert[True-1] PASSED
test/unit/clitest/test_admin.py::TestAdminPorts::testRevert[True-2] PASSED
test/unit/clitest/test_admin.py::TestAdminPorts::testRevert[False-None] PASSED
test/unit/clitest/test_admin.py::TestAdminPorts::testRevert[False-1] PASSED
test/unit/clitest/test_admin.py::TestAdminPorts::testRevert[False-2] PASSED
test/unit/clitest/test_admin.py::TestAdminPorts::testFailingRevert[True] PASSED
test/unit/clitest/test_admin.py::TestAdminPorts::testFailingRevert[False] PASSED
```

**Comment by mtbc** [comment]
That is working great. Only complaint now is RFE,
```
bin/omero admin ports --prefix=2
bin/omero admin ports --prefix=3
```
leaves them prefixed with 2. As far as I'm concerned, this is already good to merge.

**Comment by sbesson** [comment]
Agreed, switching between prefixes requires an intermediate `--revert` step at the moment. We can always improve this behavior but its impact is quite limited.

**Comment by joshmoore** [comment]
Assuming the `--revert` improvement has been captured, merging.

**Pull request merged**
