### PR TITLE
Delete rois docs

### PR DESCRIPTION
**Pull request by will-moore**
This improves our documentation & examples of deleting ROIs with conn.deleteObjects() and gives an example of using the ```wait=True``` parameter.

See http://lists.openmicroscopy.org.uk/pipermail/ome-users/2016-January/005822.html

Check that tests are passing for these examples and the code changes & comments make sense.

### CODE REVIEW

**Comment by joshmoore** [comment]
One other option here that I've used recently when testing your and my example PRs is:

```
bin/omero delete /Image/Roi:$IMAGEID
```

**Comment by will-moore** [comment]
@joshmoore That's useful for sure, but should probably go under CLI docs rather than here.

**Comment by ximenesuk** [comment]
This looks good to merge unless @joshmoore has a strong reason for a `skiphead` delet being used.

**Comment by joshmoore** [comment]
Yeah, I'll merge since adding another example would require a code change, but I was thinking less of that for the CLI docs, but that such an example would also be useful for the gateway.

**Pull request merged**
