### PR TITLE
Store last CLI session port

### PR DESCRIPTION
**Pull request by sbesson**
Fixes https://trac.openmicroscopy.org.uk/ome/ticket/12609

This PR mostly adds a session file storing the last port used while connecting with the CLI (without modifying the file storage logic). The `SessionStore.set_current()/SessionStore.get_current()` logic is modified to store/return this value and the corresponding unit tests are modified to document these new inputs.

To test this PR, try to connect to the same server on different ports, e.g.
```
$ bin/omero login user@localhost:14064
$ bin/omero logout
$ bin/omero login
```

The last call should output `Previously logged in to localhost:14064 as user-1` before prompting the user for connection information.

### CODE REVIEW

**Comment by ximenesuk** [comment]
Running a local server on 14064, I get
```
$ omero login user-0@localhost:14064
Previously logged in to localhost:4064 as user-0
$ omero sessions list
 Server          | User   | Group | Session                              | Active    | Started
-----------------+--------+-------+--------------------------------------+-----------+--------------------------
 localhost:14064 | user-0 | pg-0  | c4a9f3a0-28ae-47f9-b7e8-9f752ab519e4 | Logged in | Thu Jan 22 14:18:33 2015
(1 row)
$ omero logout
$ omero login
Previously logged in to localhost:14064 as user-0
Server: [localhost]
Username: [user-0]
Password:
Ice.ConnectionRefusedException: localhost isn't running
```
I have to then explicitly use the port to log-in.

**Comment by sbesson** [comment]
@ximenesuk: correct. In the absence of concrete specification in the ticket linked above, this PR maintains the statu quo, i.e. assume the port is `4064` if the latter is not specified in the input
To reconnect to the `14064` server, the following would work in the current state of the PR:
```
$ omero login -p 14064
$ omero login localhost:14064
$ omero login
Previously logged in to localhost:14064 as user-0
Server: [localhost] localhost:14064
```

**Comment by ximenesuk** [comment]
Looks good to merge.

**Comment by sbesson** [comment]
Will push a round of unit test tidying up if that's okay (this should not affect the logic of the PR).

**Comment by sbesson** [comment]
See https://s3.amazonaws.com/archive.travis-ci.org/jobs/48034026/log.txt

```
test/unit/clitest/test_sess.py::TestStore::testReport PASSED
test/unit/clitest/test_sess.py::TestStore::testAdd[None-None] PASSED
test/unit/clitest/test_sess.py::TestStore::testAdd[None-4064] PASSED
test/unit/clitest/test_sess.py::TestStore::testAdd[None-14064] PASSED
test/unit/clitest/test_sess.py::TestStore::testAdd[root-None] PASSED
test/unit/clitest/test_sess.py::TestStore::testAdd[root-4064] PASSED
test/unit/clitest/test_sess.py::TestStore::testAdd[root-14064] PASSED
test/unit/clitest/test_sess.py::TestStore::testDefaults PASSED
test/unit/clitest/test_sess.py::TestStore::testSetCurrent[None-None-None] PASSED
test/unit/clitest/test_sess.py::TestStore::testSetCurrent[None-None-usr] PASSED
test/unit/clitest/test_sess.py::TestStore::testSetCurrent[None-uuid-None] PASSED
test/unit/clitest/test_sess.py::TestStore::testSetCurrent[None-uuid-usr] PASSED
test/unit/clitest/test_sess.py::TestStore::testSetCurrent[4064-None-None] PASSED
test/unit/clitest/test_sess.py::TestStore::testSetCurrent[4064-None-usr] PASSED
test/unit/clitest/test_sess.py::TestStore::testSetCurrent[4064-uuid-None] PASSED
test/unit/clitest/test_sess.py::TestStore::testSetCurrent[4064-uuid-usr] PASSED
test/unit/clitest/test_sess.py::TestStore::testSetCurrent[14064-None-None] PASSED
test/unit/clitest/test_sess.py::TestStore::testSetCurrent[14064-None-usr] PASSED
test/unit/clitest/test_sess.py::TestStore::testSetCurrent[14064-uuid-None] PASSED
test/unit/clitest/test_sess.py::TestStore::testSetCurrent[14064-uuid-usr] PASSED
test/unit/clitest/test_sess.py::TestStore::testContents PASSED
test/unit/clitest/test_sess.py::TestStore::testCount PASSED
test/unit/clitest/test_sess.py::TestStore::testGet PASSED
test/unit/clitest/test_sess.py::TestStore::testConflicts PASSED
test/unit/clitest/test_sess.py::TestSessions::testLoginWithNoArgumentsRequests PASSED
test/unit/clitest/test_sess.py::TestSessions::testLoginWithConnectionArguments[string] PASSED
test/unit/clitest/test_sess.py::TestSessions::testLoginWithConnectionArguments[prefixed_string] PASSED
test/unit/clitest/test_sess.py::TestSessions::testLoginWithConnectionArguments[options] PASSED
test/unit/clitest/test_sess.py::TestSessions::testPasswordArgument[string] PASSED
test/unit/clitest/test_sess.py::TestSessions::testPasswordArgument[prefixed_string] PASSED
test/unit/clitest/test_sess.py::TestSessions::testPasswordArgument[options] PASSED
test/unit/clitest/test_sess.py::TestSessions::testKeyArgument[string] PASSED
test/unit/clitest/test_sess.py::TestSessions::testKeyArgument[prefixed_string] PASSED
test/unit/clitest/test_sess.py::TestSessions::testKeyArgument[options] PASSED
test/unit/clitest/test_sess.py::TestSessions::testReuseWorks[string] PASSED
test/unit/clitest/test_sess.py::TestSessions::testReuseWorks[prefixed_string] PASSED
test/unit/clitest/test_sess.py::TestSessions::testReuseWorks[options] PASSED
test/unit/clitest/test_sess.py::TestSessions::testReuseFromDifferentGroupDoesntWork[string] PASSED
test/unit/clitest/test_sess.py::TestSessions::testReuseFromDifferentGroupDoesntWork[prefixed_string] PASSED
test/unit/clitest/test_sess.py::TestSessions::testReuseFromDifferentGroupDoesntWork[options] PASSED
test/unit/clitest/test_sess.py::TestSessions::testReuseFromSameGroupDoesWork[string] PASSED
test/unit/clitest/test_sess.py::TestSessions::testReuseFromSameGroupDoesWork[prefixed_string] PASSED
test/unit/clitest/test_sess.py::TestSessions::testReuseFromSameGroupDoesWork[options] PASSED
test/unit/clitest/test_sess.py::TestSessions::testReuseFromDifferentPortDoesntWork[string] PASSED
test/unit/clitest/test_sess.py::TestSessions::testReuseFromDifferentPortDoesntWork[prefixed_string] PASSED
test/unit/clitest/test_sess.py::TestSessions::testReuseFromDifferentPortDoesntWork[options] PASSED
test/unit/clitest/test_sess.py::TestSessions::testReuseFromSamePortDoesWork[string] PASSED
test/unit/clitest/test_sess.py::TestSessions::testReuseFromSamePortDoesWork[prefixed_string] PASSED
test/unit/clitest/test_sess.py::TestSessions::testReuseFromSamePortDoesWork[options] PASSED
test/unit/clitest/test_sess.py::TestSessions::testInteractiveLoginNonDefaultPort PASSED
test/unit/clitest/test_sess.py::TestSessions::testLogicOfConflictsOnNoLocalhostRequested PASSED
test/unit/clitest/test_sess.py::TestSessions::testPortThenNothingShouldReuse PASSED
test/unit/clitest/test_sess.py::TestSessions::testBadSessionKeyDies[string] PASSED
test/unit/clitest/test_sess.py::TestSessions::testBadSessionKeyDies[prefixed_string] PASSED
test/unit/clitest/test_sess.py::TestSessions::testBadSessionKeyDies[options] PASSED
test/unit/clitest/test_sess.py::TestSessions::testCopiedSessionWorks[string] PASSED
test/unit/clitest/test_sess.py::TestSessions::testCopiedSessionWorks[prefixed_string] PASSED
test/unit/clitest/test_sess.py::TestSessions::testCopiedSessionWorks[options] PASSED
test/unit/clitest/test_sess.py::TestSessions::test5975[string] PASSED
test/unit/clitest/test_sess.py::TestSessions::test5975[prefixed_string] PASSED
test/unit/clitest/test_sess.py::TestSessions::test5975[options] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testEmptyString[None] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testEmptyString[default_user] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testBadPort[bad_port-None] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testBadPort[bad_port-default_user] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testBadPort[12323414232-None] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testBadPort[12323414232-default_user] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testConnectionString[localhost-None] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testConnectionString[localhost-default_user] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testConnectionString[localhost-user@-None] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testConnectionString[localhost-user@-default_user] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testConnectionString[localhost-Ã¼ser-1Â£@-None] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testConnectionString[localhost-Ã¼ser-1Â£@-default_user] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testConnectionString[localhost-user:4@email@-None] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testConnectionString[localhost-user:4@email@-default_user] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testConnectionString[server.domain-None] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testConnectionString[server.domain-default_user] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testConnectionString[server.domain-user@-None] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testConnectionString[server.domain-user@-default_user] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testConnectionString[server.domain-Ã¼ser-1Â£@-None] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testConnectionString[server.domain-Ã¼ser-1Â£@-default_user] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testConnectionString[server.domain-user:4@email@-None] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testConnectionString[server.domain-user:4@email@-default_user] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testConnectionString[:4064-localhost-None] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testConnectionString[:4064-localhost-default_user] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testConnectionString[:4064-localhost-user@-None] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testConnectionString[:4064-localhost-user@-default_user] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testConnectionString[:4064-localhost-Ã¼ser-1Â£@-None] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testConnectionString[:4064-localhost-Ã¼ser-1Â£@-default_user] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testConnectionString[:4064-localhost-user:4@email@-None] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testConnectionString[:4064-localhost-user:4@email@-default_user] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testConnectionString[:4064-server.domain-None] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testConnectionString[:4064-server.domain-default_user] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testConnectionString[:4064-server.domain-user@-None] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testConnectionString[:4064-server.domain-user@-default_user] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testConnectionString[:4064-server.domain-Ã¼ser-1Â£@-None] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testConnectionString[:4064-server.domain-Ã¼ser-1Â£@-default_user] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testConnectionString[:4064-server.domain-user:4@email@-None] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testConnectionString[:4064-server.domain-user:4@email@-default_user] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testConnectionString[:14064-localhost-None] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testConnectionString[:14064-localhost-default_user] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testConnectionString[:14064-localhost-user@-None] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testConnectionString[:14064-localhost-user@-default_user] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testConnectionString[:14064-localhost-Ã¼ser-1Â£@-None] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testConnectionString[:14064-localhost-Ã¼ser-1Â£@-default_user] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testConnectionString[:14064-localhost-user:4@email@-None] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testConnectionString[:14064-localhost-user:4@email@-default_user] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testConnectionString[:14064-server.domain-None] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testConnectionString[:14064-server.domain-default_user] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testConnectionString[:14064-server.domain-user@-None] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testConnectionString[:14064-server.domain-user@-default_user] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testConnectionString[:14064-server.domain-Ã¼ser-1Â£@-None] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testConnectionString[:14064-server.domain-Ã¼ser-1Â£@-default_user] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testConnectionString[:14064-server.domain-user:4@email@-None] PASSED
test/unit/clitest/test_sess.py::TestParseConn::testConnectionString[:14064-server.domain-user:4@email@-default_user] PASSED
```

**Comment by joshmoore** [comment]
Showoff :smile:

**Comment by sbesson** [comment]
--no-rebase

**Pull request merged**
