### PR TITLE
script to work with test-infra

### PR DESCRIPTION
**Pull request by jburel**
# What this PR does

Move upstream methods required to work with test-infra
Changes needed to handle non official script

# Testing this PR

Check that travis is green

# Related reading

See https://github.com/ome/omero-figure/pull/259

cc @joshmoore

### CODE REVIEW

**Comment by joshmoore** [comment]
No immediate objections. I begin to wonder if these should be pip installable though so we don't tie ourselves so tightly to the OMERO version.

cc: @sbesson

**Comment by jburel** [comment]
having things pip installable will be certainly be better.
For now the same changes are in the figure repo (similar to scripts and CLI plugins)

**Comment by sbesson** [comment]
Is anything within the OMERO repository still consuming these classes? If the only place where we are using this test API are the downstream components, I can totally conceive:

OMERO (ITest) -> {omero-test-{script,...}} -> omero-test-infra -> omero-figure, scripts

to allowing ourselves to make backwards-compatible test API additions as needed without the need to release a full OMERO stack.

**Comment by joshmoore** [comment]
@jburel : is having OMERO **not** depend on `omero-dev-pytest` (or whatever it's named) ok with you?

**Comment by jburel** [comment]
@joshmoore that will work.

**Comment by jburel** [comment]
Closing this PR since we will be looking into other option

**Pull request closed without merging**
