### PR TITLE
OMERO_Matlab:Fix the casting from *unit8 to int8

### PR DESCRIPTION
**Pull request by bramalingam**
# What this PR does

ref:
https://www.openmicroscopy.org/community/viewtopic.php?f=6&t=8117

# Testing this PR

1. Test the Matlab toolbox with the code snippet given in the forum post.

2. Check if the test-code runs without any errors.

### CODE REVIEW

**Comment by sbesson** [comment]
I wonder if it would make sense here to take advantage of the minimal example provided by the user in the forum post and extend the `WriteData` training example to upload a mask created with `imread`, retrieve it and compare both input and output are equal?

**Comment by bramalingam** [comment]
Yes that makes sense, will add that minimal test to the writeData training example.

**Comment by jburel** [comment]
This is a candidate PR for 5.2.6.  see https://trello.com/c/oWtA5Pod/9-omero-matlab-regression#

**Comment by imunro** [comment]
PR Looks Good to me. FYI I've been doing some testing locally and it looks as if any string starting with '*' is invalid and therefore Matlab (Silently) uses the default which is uint8. Writing test data to a file it seems as if 0-7F hex  are written fine but anything outside this range is written , to the file, as 00.  The results will be unpredictable depending on the original data type.

**Comment by jburel** [comment]
@bramalingam could you rebase this PR to dev_5_2?

**Comment by bramalingam** [comment]
--rebased-to #4849

**Comment by jburel** [comment]
@imunro's comment: see card https://trello.com/c/Wq0xVNHc/191-matlab-invalid-string

**Pull request merged**
