### PR TITLE
merge roles into mainline develop for OMERO 5.4 series

### PR DESCRIPTION
**Pull request by mtbc**
# What this PR does

Merges commits back from `roles` into `develop`.

# Testing this PR

CI jobs should not show regressions.

### CODE REVIEW

**Comment by mtbc** [comment]
I am happy to sign a milestone tag but how I do so *usefully* I forget. I can do the `git tag -s v5.4.0-m1 -m ...` locally but what next? Once this is merged I could fetch and sign `develop`'s HEAD and push the tag to my fork.

**Comment by jburel** [comment]
you can also use ``scc tag-release -s release`` (no v)

**Comment by jburel** [comment]
when ready one of us can tag and push to origin 
cc @sbesson @joshmoore

**Comment by mtbc** [comment]
Not merged due to conflicts. Should we turn off the thing where non-breaking PRs also get included? I think that usually causes more trouble than it's worth.

**Comment by mtbc** [comment]
Now that @will-moore has kindly excluded #5347 the next obstacle is,
```
ERROR:  PostgreSQL database server version 9.3.15 is less than OMERO prerequisite 9.4.0
```
This does have the pleasing side-effect of testing @rleigh-codelibre's version number pretty-printing.

**Comment by mtbc** [comment]
CI failures seem largely unrelated to this PR, "breaking" is broken. Leaving for either @jburel or @joshmoore to decide to remove `--breaking` once they are back and able to check in with @sbesson.

**Comment by mtbc** [comment]
After discussion, removed from breaking ready to test in mainline.

**Comment by mtbc** [comment]
This breaks OMERO-DEV-merge-cpp but I expect we can live with that briefly. #5358 fixes the C++ build for me locally so I'll run that through devspace CI once Travis passes (especially as it adds to `test_permissions.py`) then switch the base branch to `develop` once this PR is in.

**Comment by jburel** [comment]
Merging this PR so we can move forward, I will tag when the PR fixing the c++ issue is in

**Pull request merged**
