### PR TITLE
Import tests 3

### PR DESCRIPTION
**Pull request by joshmoore**
# What this PR does

Reactivates integration tests on travis. Again, only those tests which have been modified should be run.

# Testing this PR

1. check that `test_import_bulk.py` is run in travis and passes.
2. check that the time for the tests is not too significant.

### CODE REVIEW

**Comment by joshmoore** [comment]
💚 🎉

**Comment by joshmoore** [comment]
screen shot 2018-08-23 at 16 50 43

**Comment by sbesson** [comment]
As expected in this PR, the detection logic works and the only executed tests are the ones modified in the PR.

```
+ python setup.py test -t test/integration/clitest/test_import_bulk.py -m 'not broken'
ez_setup.py is deprecated and when using it setuptools will be pinned to 33.1.1 since it's the last version that supports setuptools self upgrade/installation, check https://github.com/pypa/setuptools/issues/581 for more info; use pip to install setuptools
WARNING: '' not a valid package name; please use only .-separated package names in setup.py
/usr/lib/python2.7/site-packages/setuptools/dist.py:407: UserWarning: The version specified ('5.4.8-ice36-SNAPSHOT') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  "details." % self.metadata.version
running test
False
Searching for pytest<3
Reading https://pypi.org/simple/pytest/
Downloading https://files.pythonhosted.org/packages/24/05/b6eaf80746a2819327207825e3dd207a93d02a9f63e01ce48562c143ed82/pytest-2.9.2-py2.py3-none-any.whl#sha256=ccc23b4aab3ef3e19e731de9baca73f3b1a7e610d9ec65b28c36a5a3305f0349
Best match: pytest 2.9.2
Processing pytest-2.9.2-py2.py3-none-any.whl
Installing pytest-2.9.2-py2.py3-none-any.whl to /src/components/tools/OmeroPy/.eggs
writing requirements to /src/components/tools/OmeroPy/.eggs/pytest-2.9.2-py2.7.egg/EGG-INFO/requires.txt

Installed /src/components/tools/OmeroPy/.eggs/pytest-2.9.2-py2.7.egg
running egg_info
writing target/omero_client.egg-info/PKG-INFO
writing top-level names to target/omero_client.egg-info/top_level.txt
writing dependency_links to target/omero_client.egg-info/dependency_links.txt
reading manifest file 'target/omero_client.egg-info/SOURCES.txt'
writing manifest file 'target/omero_client.egg-info/SOURCES.txt'
running build_ext
============================= test session starts ==============================
platform linux2 -- Python 2.7.5, pytest-2.9.2, py-1.5.4, pluggy-0.3.1
rootdir: /src/components/tools, inifile: pytest.ini
plugins: django-3.1.2
collected 1 items

test/integration/clitest/test_import_bulk.py .

========================== 1 passed in 31.10 seconds ===========================
+ fold end integration
```

Answering the question about build times, looking at the details of the logs, my main unknown is how much redundancy we have between the current phases esp. `integration`, `build-python` and `build-java`. No objection to getting this in especially if this is valuable for validating the current import work.

Probably something to review is:
- the core scripts controlling the default build phases e.g.`components/tools/travis-build` vs `docs/hudson/OMERO.sh`
- whether we can make more usage of features like https://docs.travis-ci.com/user/build-stages and reduce the duplication between various stages

**Comment by joshmoore** [comment]
>  No objection to getting this in especially if this is valuable for validating the current import work.

My vote would be to get it in so we start acquiring data about build times and then we can look to:

 * decrease redundancy
 * add in _Java_ tests
 * etc.

**Review by sbesson — APPROVED** [review]

**Pull request merged**
