### PR TITLE
fix #11084: combine original file deletions into fewer transactions

### PR DESCRIPTION
**Pull request by mtbc**
Fixes http://trac.openmicroscopy.org.uk/ome/ticket/11084. Deletion should still work fine, *including* deleting the files from disk. (Given http://trac.openmicroscopy.org/ome/ticket/12719, best tested from Insight.) Deletion should now be quite fast even when many files are to be deleted.

--no-rebase

### CODE REVIEW

**Comment by joshmoore** [comment]
Did a more thorough read through of the code. Thanks again, @mtbc, for taking over the branch. Just waiting on functional testing (and interested in the reported speed up! :smile:)

**Comment by pwalczysko** [comment]
Tested
1. ``test_images_good/bruker`` (a MIF with tens of Companion files)
2. ``from_skyking/mias/frans/siRNA....``  (16 well plate, but mias)
3. ``public/images/HCS/INCELL2000/INMAC384-DAPI-CM-eGFP_59223_1``  (ca 1000 tiff images in a plate format)

Results of speed:
trout/merge: 
  - 1. 3 sec, 
  - 2. 3 sec, 
  - 3. 13 sec

trout/latest
   - 1. 1 minute
   - 2. 15 sec
   - 3. 18 sec

Great improvement of speed. Even the 9 GB plate with 13-14 sec as the slowest tested is pretty much in the bearable limit.
The files vanished from ManagedRepo on trout/merge as expected.

All fine here.

**Comment by pwalczysko** [comment]
( i think this could be in the release announcement - if we could just pinpopint what is the quality of bruker and mias that improves the performance so drastically in this case.)

**Comment by manics** [comment]
The server now starts up, unlike yesterday.

**Comment by mtbc** [comment]
Anything more to check here?

**Comment by pwalczysko** [comment]
Pretty confusing one. I thought everything was fine after https://github.com/openmicroscopy/openmicroscopy/pull/3399#issuecomment-71854834 - then I see 2 new commits (which do what ?) and a bit nervous-making remark that the server does not start (did not start ?)

**Comment by mtbc** [comment]
@manics saw a problem (reported on devteam, maybe?) that the latest commits ought to have fixed. See chat from 11:52 at https://jabber.openmicroscopy.org/chatlogs/devteam/2015-02-02.html.

**Comment by joshmoore** [comment]
Don't think so. Merging.

**Pull request merged**
