### PR TITLE
Make movie

### PR DESCRIPTION
**Pull request by jburel**
Unify UI for make movie following intro of widget in web https://github.com/openmicroscopy/openmicroscopy/pull/3282

To test:
 * Check that both dialogs (insight, web) have similar display and options.
 * Check in web text for "Scale bar" (instead of scalebar) and "Color" instead of "Colour"

cc @gusferguson

### CODE REVIEW

**Comment by gusferguson** [comment]
@jburel 

Tested using OMERO.insight-5.1.0-m4-195-6567119-ice35-b420-win trout user-3

Both UIs are now aligned apart from the spelling of Scale bar in Insight and Scalebar in web.
See screenshot.
Good to merge.

safari

**Comment by jburel** [comment]
@gusferguson: I might have missed that one in web. I will push a fix.

**Comment by jburel** [comment]
@gusferguson: fixed.

**Comment by gusferguson** [comment]
@jburel 

Tested using OMERO.insight-5.1.0-m4-203-3529393-ice34-b421-mac_Java7+ and https://trout.openmicroscopy.org/merge/webclient/ Safari - trout user-3 read-annotate-1

All looking good apart from inconsistent capitalisation of Scale Bar (Insight) and Scale bar (Web) - screenshot 1.
Also noted that when only 1 z and 1 t in an image - Insight greys out Make Movie in the menu wile Web still keeps it enabled and you can make a single frame movie - screenshot 2. This is probably best left for another day though.

Don’t know how fussy you want to get about the capitalisation.
If not at all - then good to merge.

safari

main

**Comment by jburel** [comment]
@gusferguson: will fix the capitalisation

**Comment by gusferguson** [comment]
@jburel - cool - it should be like Insight to be consistent with rest of dialog.

**Comment by jburel** [comment]
@gusferguson: done

**Comment by gusferguson** [comment]
@jburel - checked in code - do you want to merge it?

**Comment by jburel** [comment]
waiting on travis to be green

**Comment by joshmoore** [comment]
Green. Merging.

**Comment by jburel** [comment]
--no-rebase

**Pull request merged**
