### PR TITLE
Perceptibly uniform luts

### PR DESCRIPTION
**Pull request by Tom-TBT**
# What this PR does

I added perceptibly uniform LUTs. I started with the LUTs from the viridis family that I found in Fiji, but I extended it to other LUTs used in R: https://github.com/sjmgarnier/viridis

* The LUTs `viridis`, `magma`, `inferno`, and `plasma` were created by Stéfan van der Walt ([@stefanv](https://github.com/stefanv)) and Nathaniel Smith ([@njsmith](https://github.com/njsmith)). [presentation of viridis](https://youtu.be/xAoljeRJ3lU) by their authors at SciPy 2015
* The LUT `cividis`, a corrected version of 'viridis' for color vision deficiency (Nuñez, Anderton, Renslow 2018, https://doi.org/10.1371/journal.pone.0199239)
* The LUTs `mako` and `rocket` created for seaborn (https://seaborn.pydata.org/tutorial/color_palettes.html#perceptually-uniform-palettes)
* The LUT `turbo` developed by Anton Mikhailov to address the shortcomings of the Jet rainbow color map such as false detail, banding and color blindness ambiguity. (https://ai.googleblog.com/2019/08/turbo-improved-rainbow-colormap-for.html).

# Testing this PR

1. required setup
An OMERO.server

2. actions to perform
Add the new LUTs to `OMERO.server/lib/scripts/luts`

3. expected observations
The LUTs become available for all tools (but there is no preview of the LUT intensity from the dropdown lists):
* OMERO.iviewer
* OMERO web image viewer + preview tab
* OMERO.insight
* OMERO.figure

# Related reading

Link to cards, tickets, other PRs:
* https://github.com/ome/omero-web/pull/568
* https://github.com/ome/omero-iviewer/pull/481
* https://github.com/ome/omero-figure/pull/579
* https://github.com/ome/omero-insight/pull/443

1. background for understanding this PR
The viridis LUT family have been created with perception uniformity as criterion. They are the standard of matplotlib for some time now and are also packaged with Fiji. I think it would be good for users to find them also by default in OMERO.
The cividis is the colorblind adjusted version of viridis which also has been integrated in Fiji (https://forum.image.sc/t/new-lut-for-fiji-cividis/7467).
Seaborn also offers two perceptually uniform LUT, mako and rocket, part of the "viridis" package for R.
Finally, turbo is an alternative to jet that is also more colorblind-friendly and gradual. 

2. what this PR assists, fixes, or otherwise affects
This will package new LUTs with OMERO.server. The LUTs will become available for other OMERO components (web, iviewer, figure, insight) but will not display preview until related PR are merged and deployed.

### CODE REVIEW

**Comment by will-moore** [comment]
Added the `include` label so this will get included in the server merge-ci deployment for testing...

**Comment by will-moore** [comment]
In webclient Preview panel and webgateway viewer, these LUTs are all showing up (without preview png) and are working fine:

Screenshot 2024-11-07 at 15 02 13

Same in Figure:

Screenshot 2024-11-07 at 15 05 44

**Comment by Tom-TBT** [comment]
Same about the iviewer:
image

And the default omero-web viewer:
image

**Review by will-moore — APPROVED** [review]
LUTs work in clients and don't cause any issues
The preview png is missing as expected - due to be fixed elsewhere

**Pull request merged**
