### PR TITLE
add Jinja2

### PR DESCRIPTION
**Pull request by jburel**
# What this PR does

Add dependencies

See https://trello.com/c/QaxIg0AH/156-jinja-warning

cc @joshmoore

### CODE REVIEW

**Comment by jburel** [comment]
Discussed with @mtbc, the general approach has been to used th package manager see https://docs.openmicroscopy.org/omero/5.4.10/sysadmins/unix/server-centos7-ice36.html
so I will update omeroweb-install instead of the requirements file

**Comment by jburel** [comment]
Re-opening this PR ansible-role-omero-web installed the dependencies using the requirement file
see https://github.com/openmicroscopy/ansible-role-omero-web/blob/master/tasks/web-install.yml
cc @joshmoore

**Comment by joshmoore** [comment]
As long as web.py imports jinja and lives in the server repo, this will also need to be done for server installations as well. cc: @manics

**Comment by jburel** [comment]
Actually  https://github.com/ome/omero-web-docker/blob/master/requirements.yml
and https://github.com/ome/omero-server-docker/blob/master/requirements.yml use https://github.com/openmicroscopy/ansible-role-omero-python-deps
which installed ``python-jinja2`` https://github.com/openmicroscopy/ansible-role-omero-python-deps/blob/master/tasks/main.yml

So this change should not needed.

**Pull request closed without merging**
