### PR TITLE
cecog cleanup

### PR DESCRIPTION
**Pull request by jburel**
Remove cecog

Make sure that all ref have been removed.
Not much to test
No mention in the doc/scripts.

### CODE REVIEW

**Comment by sbesson** [comment]
Is it preferable to drop immediately or should we go through a 5.3.0 deprecation and remove it in the following breaking version?

**Comment by jburel** [comment]
It was not be used since 4.1 
Some scripts like "Run_cecog.py" no longer exists

Same applies for flim so I don't think it is necessary.

**Comment by jburel** [comment]
The ```cecog``` work was initially introduced when @will-moore was working on em data few years ago

**Comment by sbesson** [comment]
The CLI plugin removal is sensible for all the reasons you mention above. Similar to other deprecation strategies, we could even consider filtering it into a separate unmaintained repository. For the other method, we assume no one would have been relying on the `script_utils.uploadCecogObjectDetails` API. Do we know of anyone who consumed this work ?

**Comment by jburel** [comment]
At the time, only @will-moore used it, maybe ingvard?
but that was a long time ago

**Comment by will-moore** [comment]
As I remember @joshmoore added this mostly as a prototype when we were discussing Cecog integration, but it is not related to EM work. Don't know that it was ever used by anyone outside our group.

**Pull request merged**
