### PR TITLE
slack notification (rebased onto develop)

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
This is the same as gh-4698 but rebased onto develop.

----

This PR allows to set up custom notification using slack using http://django-slack.readthedocs.io/

To test:

- `pip install django_slack`
- generate your token https://api.slack.com/web#authentication
- set up config:

 ```
 bin/omero config set omero.web.debug false
 bin/omero config set omero.notify.slack.enabled true
 bin/omero config set omero.notify.slack.token "xoxp-123token..."
 bin/omero config set omero.notify.slack.channel "#logs"
 bin/omero config set omero.notify.slack.username "abc"
 ```
- add weberror app for testing
- start web and test:
  - https://cowfish.openmicroscopy.org/webmerge/weberror/error_404/
  - https://cowfish.openmicroscopy.org/webmerge/weberror/error_500/
- check email errors accordingly

Additional testing: I also cleaned up email notification
-  set the following:

 ```
bin/omero config set omero.web.debug False
bin/omero config set omero.mail.config true
```
 *mail config is not named `enabled` but `config` because property name is matching server side property*

- add weberror app for testing
- set mail config https://www.openmicroscopy.org/site/support/omero5.2/sysadmins/mail.html or use local SMTP mock (you will not get real email, just console output):
    - set ```bin/omero config set omero.mail.from "your@email``` and ```bin/omero config set omero.mail.host "localhost"```
    - run in new console SMTP mock ```sudo python -m smtpd -n -c DebuggingServer localhost:25```. *Email message will be shown as a plane text on your console.*
- set your email in ```bin/omero config set omero.web.admins '[["Username", "your@email"]]'```
- try to get HTTP500 and 404 (must come from broken link in template, do not access random url) and see if you received both errors by email

**NOTE:** property name change `omero.slack.*` to `omero.notify.slack.*`

### CODE REVIEW

**Comment by aleksandra-tarkowska** [comment]
--rebased-from #4698

**Comment by manics** [comment]
internal 404 links work as expected.

`omero.slack.fail_silently=false` doesn't seem to report errors anywhere- I tried setting an incorrect channel name:

```
omero.slack.channel=#nonexistent-channel
omero.slack.enabled=true
omero.slack.fail_silently=false
omero.slack.username="xxx \\ yyy"
```

Also successfully tested email notifications for 404s.

**Comment by aleksandra-tarkowska** [comment]
@manics thanks for testing, if you are mostly happy with the behavior I will open a PR against original lib repo. Hopefully they will maintain it

**Comment by manics** [comment]
One more thing- is `omero.slack` too generic? Is there a possibility of wanting to use slack for more than error notifications?

**Comment by aleksandra-tarkowska** [comment]
we can do `omero.notify.slack` but in general I tried to avoid `omero.web.` as maybe server will send error one day ;-)

**Comment by joshmoore** [comment]
Looking at https://github.com/openmicroscopy/openmicroscopy/pull/4699/files#diff-7e3491c8f527592430b6decfcdc7c4d3R1098 for example, I do wonder if we're not making the hard-coding problem again. I.e. would a tuple of values all under `omero.notify` be more flexible. That being said, I don't know how the Java servers would/will make use of this.

**Comment by aleksandra-tarkowska** [comment]
@joshmoore at the moment we hardcoded `mail_admins` log handler regardless of what is in `omero.mail`. I only added better handler for `omero.mail.config` as we shouldn't add extra logging handlers, nor middleware if it is not in use.

The same for slack. If https://github.com/openmicroscopy/openmicroscopy/pull/4699/files#diff-7e3491c8f527592430b6decfcdc7c4d3R1113 disabled, not in use, shouldn't pollute config.

**Comment by aleksandra-tarkowska** [comment]
closing to let #4689 be tested

**Pull request closed without merging**
