### PR TITLE
HELP link

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
This PR adds HELP link to top bar, as requested in https://trello.com/c/rjmbOCXT/314-add-help-link-to-web-client

CC: @gusferguson @pwalczysko

### CODE REVIEW

**Comment by aleksandra-tarkowska** [comment]
@gusferguson could you or someone provide me with nice envelope matching grey colors icon to replace Lifebuoy?

**Comment by gusferguson** [comment]
@aleksandra-tarkowska 

No problem with the icon - can you maybe send me an example of roughly you want. I will do it tomorrow when I am back at work.

Please can you make sure the Help link is in lower case, not upper case.

**Comment by aleksandra-tarkowska** [comment]
@gusferguson I have created temporary icon. I am sure you can make better one. We need 2 grey (9c9c9c) and white (ffffff) see the example above

**Comment by will-moore** [comment]
I don't think we need the 'Help' link to be 'HELP". This is not consistent with any other top links and looks wrong. It would also be nice to have a useful tooltip, e.g. "Open the OMERO user guide in a new tab".

**Comment by hflynn** [comment]
Hi @aleksandra-tarkowska - while you have this PR open, could you remove the FAQ from components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/help/help_search.html too? Or shall I just open a PR to do it myself?

**Comment by aleksandra-tarkowska** [comment]
@hflynn I removed the whole template as me and @will-moore are not able to identify it anywhere within the app.

**Comment by hflynn** [comment]
Thanks!

**Comment by aleksandra-tarkowska** [comment]
@will-moore @gusferguson @hflynn is there anything else needed?

**Comment by will-moore** [comment]
I'm happy. Good to merge.

**Comment by gusferguson** [comment]
@aleksandra-tarkowska - I am happy but the icons are proving unbelievably troublesome to produce. Is it OK to go with your placeholders until I can work out how to do it properly. I also need to know exactly where they are going to appear.

**Comment by aleksandra-tarkowska** [comment]
@gusferguson whenever you have icon we can open another PR to change it. They should appear as follow:
firefoxscreensnapz007 firefoxscreensnapz006

**Comment by hflynn** [comment]
All good from me too

**Comment by gusferguson** [comment]
@aleksandra-tarkowska - thanks Ola I will do them as soon as I work out how to get them looking decent.

**Pull request merged**
