### PR TITLE
Opengl

### PR DESCRIPTION
**Pull request by jburel**
Remove opengl code and dependencies.
Make sure the build passes.

### CODE REVIEW

**Comment by rleigh-dundee** [comment]
All the removals look OK and the merge job is green, so looks good to merge.  Any specific insight testing required?

**Comment by jburel** [comment]
Maybe open an image to be sure.

**Comment by joshmoore** [comment]
@jburel : what else shall we do here?

**Comment by jburel** [comment]
@rleigh-dundee: to be sure nothing is broken: could you select an image,
 * Go to preview. Check that the image is visible
 * Open the image in the full viewer
 * open the lens

**Comment by rleigh-dundee** [comment]
Tested on Linux.  Seems to work fine for me.

**Comment by jburel** [comment]
@rleigh-dundee: Thanks for testing. Merging so we can move on with further cleanup.

**Comment by jburel** [comment]
--no-rebase

**Pull request merged**
