### PR TITLE
Test figure script dialog

### PR DESCRIPTION
**Pull request by will-moore**
Adds a test for fix at https://github.com/ome/omero-web/pull/73 which was found by manual testing.

New test should be green.

### CODE REVIEW

**Comment by will-moore** [comment]
Travis failing with:

```OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"/opt/omero/server/venv3/bin/python\": stat /opt/omero/server/venv3/bin/python: no such file or directory": unknown```

**Comment by will-moore** [comment]
Not sure why this is failing now. It looks very similar to https://travis-ci.org/ome/openmicroscopy/builds/615013876?utm_source=github_status&utm_medium=notification which just passed

**Comment by joshmoore** [comment]
Test is green now so will be included in the next run.

**Comment by will-moore** [comment]
Test passing at https://py3-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/67/testReport/OmeroWeb.test.integration.test_scripts/TestFigureScripts/

**Comment by joshmoore** [comment]
:+1:

**Pull request merged**
