### PR TITLE
Insight units followup

### PR DESCRIPTION
**Pull request by dominikl**
Fixes the Insight issues mentioned on trello board [Units Client Follow-up](https://trello.com/c/PiLauXgp/47-units-client-follow-up). Also fixes ticket [12620](http://trac.openmicroscopy.org.uk/ome/ticket/12620) 

Test: 
1) Use file with non-default units: [alternate.ome](https://github.com/qidane/bioformats/blob/some-units-samples/components/specification/samples/develop/6x4y1z1t1c8b-swatch-instrument-units-alternate.ome);  check that the units and values are displayed correctly. 
2) Import a file with deltaT but not exposure time data (e. g. the file from [QA 10330](https://www.openmicroscopy.org/qa2/qa/feedback/10330/)), make sure deltaT values are displayed.

### CODE REVIEW

**Comment by dominikl** [comment]
Found another problem (NDFilter value is wrong), will fix that within this PR, too.

**Comment by jburel** [comment]
Values are correctly displayed/
Comment added to https://trello.com/c/OBUND1Za/82-general-pane-client-alignment (not related to this PR)

**Comment by dominikl** [comment]
Yes, also checked again, NDfilter value is displayed correctly; I just got a bit confused.

**Comment by jburel** [comment]
The deltaT/Exposure time are now correctly displayed.
It will be also good to review the display of the deltaT in the main viewer but that should be done in another PR.

**Comment by jburel** [comment]
Everything works as expected. @dominikl any more changes?

**Comment by dominikl** [comment]
No, I don't think so, not for this PR.

**Comment by jburel** [comment]
Thanks, merging

**Pull request merged**
