### PR TITLE
Embed Bio-Formats git version in source archive

### PR DESCRIPTION
**Pull request by sbesson**
Fixes https://trello.com/c/phbzkRzW/406-fix-openmicroscopy-source-zip

Main changes of this PR:
- appends `.py` to `source-archive` and `flake8` the script
- call the Bio-Formats `store-version` target in order to retrieve the Bio-Formats version information
- fixes `source-archive.py` to embed the Git/Cmake version under `components/bioformats`

To test this PR, check the source archive is functional, includes the Git version for both `openmicroscopy` and `bioformats`. For a more thorough testing, reproduce the steps of https://github.com/ome/omero-install/blob/master/homebrew/install_omero51, i.e. download the archive, build the server, start it and import an image. Both OMERO and Bio-Formats version should be correct in the import log.

--depends-on https://github.com/openmicroscopy/bioformats/pull/1598
--no-rebase

### CODE REVIEW

**Comment by manics** [comment]
Built https://ci.openmicroscopy.org/view/5.1/job/OMERO-5.1-merge-build/lastSuccessfulBuild/ICE=3.5,jdk=8_LATEST,label=trout/artifact/src/target/openmicroscopy-5.1.0-m3-1196-48fc421.zip in Docker (https://github.com/ome/ome-docker/tree/92bc3a6d8aadede91f5411edd4785fb8b0c3b639/omero-build-c6-multienv):
```
./build.py build-default
./build.py release-all
```
Installed `target/OMERO.server-5.1.0-m3-1196-48fc421-ice35.zip` to a new system
```
OMERO.server-5.1.0-m3-1196-48fc421-ice35/bin/omero import -d 1 ---file out.log ---errs err.log ...
```
err.log:
```
2015-02-16 11:29:31,737 854        [      main] INFO          ome.formats.importer.ImportConfig - OMERO Version: 5.1.0-m3-1196-48fc421-ice35
2015-02-16 11:29:31,766 883        [      main] INFO          ome.formats.importer.ImportConfig - Bioformats version: 5.1.0-DEV revision: ead693d date: 16 February 2015
```

Comparing with git `scc/merge/develop/latest`:
```
$ git describe
v5.1.0-m3-1196-g48fc421
$ git submodule status components/bioformats
 ead693dc390172672c7173ba957d96ac3f24c968 components/bioformats (v5.1.0-m3-498-gead693d)
```

**Comment by rleigh-dundee** [comment]
Building components/bioformats standalone with ant:

```
% git checkout origin/develop
% git submodule update
% git merge sbesson/source_archive
% cd components/bioformats
% git fetch sbesson
% git merge sbesson/ome_source_archive
% cd ../..
% git add -u
% git commit -m "Update submodule"
% git tag v5.1.0-m4 -m "Testrel"
% ant release-src
[unpack zip]
% cat /tmp/openmicroscopy-5.1.0-m4/components/bioformats/ant/gitversion.xml 
<?xml version="1.0" encoding="utf-8"?>
<project name="gitversion" basedir=".">
    <property name="release.version" value="5.1.0-DEV"/>
    <property name="release.shortversion" value="5.1.0-DEV"/>
    <property name="vcs.revision" value="352ffb5"/>
    <property name="vcs.date" value="2015-02-15 09:01:58 +0000"/>
</project>
% cat /tmp/openmicroscopy-5.1.0-m4/components/bioformats/cpp/cmake/GitVersion.cmake
set(OME_VERSION "5.1.0-DEV")
set(OME_VERSION_SHORT "5.1.0-DEV")
set(OME_VCS_REVISION "352ffb5")
set(OME_VCS_DATE ${vcs.date_unix})
set(OME_VCS_DATE_S "2015-02-15 09:01:58 +0000")
```

Looking at components/formats-api/build/src/loci/formats/version.properties after an ant build:
```
date = 17 February 2015
vcs.revision = 352ffb5
release.version = 5.1.0-DEV
year = 2015
```

This *does* work if you tag the bioformats component.  So this isn't strictly a problem with the PR, but it does mean that it is *essential* for the bioformats submodule to be both up to date and have the release tag present in order to release.

**Comment by rleigh-dundee** [comment]
Bug in C++, with both bioformats and openmicroscopy tagged:

```
% cat /tmp/openmicroscopy-5.1.0-m4/components/bioformats/cpp/cmake/GitVersion.cmake
set(OME_VERSION "5.1.0-m4")
set(OME_VERSION_SHORT "5.1.0-m4")
set(OME_VCS_REVISION "352ffb5")
set(OME_VCS_DATE ${vcs.date_unix})
set(OME_VCS_DATE_S "2015-02-15 09:01:58 +0000")
```

both untagged:

```
% cat /tmp/openmicroscopy-5.1.0-m3-1086-bf63722/components/bioformats/cpp/cmake/GitVersion.cmake 
set(OME_VERSION "5.1.0-DEV")
set(OME_VERSION_SHORT "5.1.0-DEV")
set(OME_VCS_REVISION "352ffb5")
set(OME_VCS_DATE ${vcs.date_unix})
set(OME_VCS_DATE_S "2015-02-15 09:01:58 +0000")
```

Note how `vcs.date_unix` isn't being set.  This needs to be set and passed through properly.

**Comment by sbesson** [comment]
@rleigh-dundee: thanks, yes I forgot to store `vcs.date_unix` in the stored property file. Will fix this in the Bio-Formats PR. 
Regarding your first comment, what is the expectation for `release.version`? Following your workflow, you only tagged the top-level `openmicroscopy` repository, so I would expect the `release.version` to be effectively decoupled unless you tag openmicroscopy and Bio-Formats with the exact same tag.

**Comment by rleigh-dundee** [comment]
@sbesson I wasn't sure if you were planning on having the openmicroscopy tag override the bioformats tag.  If it did, I would expect the bioformats files to contain the openmicroscopy tag version.  If not, then the behaviour is fine, we just need to be sure the tags are set when releasing.

**Comment by rleigh-dundee** [comment]
With both repos tagged, also looks OK with a build from the zip.

```
2015-02-17 14:08:22,421 INFO  [       ome.formats.importer.ImportConfig] (l.Server-7) OMERO Version: 5.1.0-m4-ice35
2015-02-17 14:08:22,421 INFO  [       ome.formats.importer.ImportConfig] (l.Server-7) Bioformats version: 5.1.0-m4 revision: 352ffb5 date: 17 February 2015
```

**Comment by sbesson** [comment]
@rleigh-dundee: understood. I definitely implemented these PRs with the upcoming decoupling in mind, where openmicroscopy and bioformats can both be tagged but with different tags. In this scenario, we do not want the openmicroscopy tag to override the Bio-formats one.

**Comment by rleigh-dundee** [comment]
The last minor remaining issue is being able to run from a clean tree when `components/bioformats/artifacts` does not yet exist.

**Comment by sbesson** [comment]
PR opened to handle the source generation from a clean repository. I will merge this PR once the submodules are bumped (with openmicroscopy/bioformats#1598 included).

**Pull request merged**
