### PR TITLE
Disable delete action if a well field is selected

### PR DESCRIPTION
**Pull request by dominikl**
Fixes ticket: https://trac.openmicroscopy.org/ome/ticket/12795

Test:
Select a well and make sure the "Delete" action is disabled, in the context menu as well as in the "Screens" toolbar. Check that the action is enabled otherwise, e. g. if the Run or the Plate is selected.

--no-rebase

### CODE REVIEW

**Comment by gusferguson** [comment]
@dominikl 

Tested using OMERO.insight-5.1.0-160-e43dd1d-ice34-b464-mac_Java7+ user-3 read-only-1.

Behaves as expected.
Good to merge.

**Comment by jburel** [comment]
Delete is still available from the Data manager menu i.e. Edit>Delete

**Comment by dominikl** [comment]
Forgot about the menu. Fixed with my last commit. 
Updated test instructions: 
Select a well and check that delete action is disabled in:
- Popup menu on the selected well
- "Screens" toolbar
- Main "Edit" menu
Select the Plate or Run and check that the delete action is then enabled again.

**Comment by mtbc** [comment]
Good to merge.

**Pull request merged**
