### PR TITLE
remove deprecated GraphSpec code

### PR DESCRIPTION
**Pull request by mtbc**
Remove the pre-5.0 graphs implementation, the `omero.graphs.wrap` configuration property, and the tests that rely heavily on the old implementation.

--no-rebase as the GraphSpec code should remain in 5.1

### CODE REVIEW

**Comment by mtbc** [comment]
@ximenesuk: re. https://trello.com/c/R3ZYCmDV/549-cli-object-graph-lists this PR probably breaks `--list`.

**Comment by ximenesuk** [comment]
@mtbc Thanks. I'll fis the list option and then open a PR based on this once it is in.

**Comment by mtbc** [comment]
@ximenesuk: This PR shouldn't block your fix.

**Comment by ximenesuk** [comment]
I guess not!

**Comment by mtbc** [comment]
No problem, I can do that!

**Comment by ximenesuk** [comment]
Everything that has been removed or changed looks sensible. I can't vouch that everything that needs to be removed has been! CI tests pass and the graph commands work locally from the CLI for a few simple caeses. Good to merge?

**Comment by mtbc** [comment]
:+1: Thank you for the review.

**Comment by jburel** [comment]
Thanks if we find other instances to clean up we can do in a follow-up PR.
Merging so @ximenesuk can move forward with his work

**Comment by ximenesuk** [comment]
@mtbc I only just saw your update above... https://github.com/ximenesuk/openmicroscopy/commit/8e5635150faa7c5f4694a7986d7d530d6b5634f1

**Pull request merged**
