### PR TITLE
last batch of tidying up headers and imports in Java files

### PR DESCRIPTION
**Pull request by mtbc**
This is the last of a series of PRs that minorly tidy the comments and imports at the start of Java source files. Nothing important should be lost and the code should still build fine. Also test that this PR can merged on top of #4128 without conflicts needing manual fixes.

--no-rebase

### CODE REVIEW

**Comment by jburel** [comment]
@mtbc: As indicated this am, I had to update the ```training``` package in my pojos PR. This will conflict

**Comment by mtbc** [comment]
It should be okay, I tested it locally. :smiley:

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#81](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/81/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/81/consoleText) for more details.
Possible conflicts:
  - PR #4121 mtbc 'improve Server security Javadoc'
    - components/server/src/ome/tools/hibernate/HibernateUtils.java
  - PR #4122 mtbc 'a batch of tidying up headers and imports in Java files'
    - components/server/src/ome/tools/hibernate/HibernateUtils.java

**Comment by sbesson** [comment]
https://ci.openmicroscopy.org/view/DEV/job/OMERO-DEV-merge-integration-java/70/ is green. :+1:

**Pull request merged**
