### PR TITLE
no longer use Django utils library "functional"

### PR DESCRIPTION
**Pull request by mtbc**
# What this PR does

Replaces Django compatibility library with standard one.

# Testing this PR

CI suffices.

### CODE REVIEW

**Comment by joshmoore** [comment]
Wrong target branch?

**Comment by mtbc** [comment]
Want to make sure it doesn't completely break Python testing or web client before I bring it into a merge build right before I ask you to merge a bunch of other PRs for m2. :smiley:

**Review by chris-allan — CHANGES_REQUESTED** [review]
Just in case anyone else is using `omero_ext.functional`, even though I'm not aware of anyone who is, it would probably be a good idea to put a backwards compatibility package in place and then use the built in Python infrastructure to deprecate it.

Such a compatibility `omero_ex.functional` module could just effectively be `from functools import wraps` and a deprecation annotation I believe.

**Review by chris-allan — COMMENTED** [review]
Just need our standard Python header and we should be good to go I think.

**Review by chris-allan — APPROVED** [review]

**Pull request merged**
