### PR TITLE
ROITable code cleanup

### PR DESCRIPTION
**Pull request by dominikl**
This PR is just some refactoring/clean up of the `ROITable` class; it is still quite large, but I can't think of any things which can be easily refactored at the moment.

See [Trello - Measurement tool cleanup](https://trello.com/c/1UeNMTV5/85-measurement-tool-cleanup), respectively @joshmoore 's comment on a previous ROIFolders PR https://github.com/openmicroscopy/openmicroscopy/pull/4595#issuecomment-212787161 .

**Test** : A brief ROI/Folder test should be sufficient, just to check that the PR doesn't break the ROI table: Create some ROIs and Folders and move them around a bit.

### CODE REVIEW

**Comment by gusferguson** [comment]
@dominikl 

Tested using OMERO.insight-5.3.0-m2-464-2912af1-ice36-b319-mac eel user-1

All works as expected except small issue:
- select multiple ROIs
- click to drag and drop
- multi-selection lost and only ROI clicked on to drag moves
Not sure whether this is reversion.

Otherwise good to merge.

**Comment by pwalczysko** [comment]
The DnD multiselection problem https://github.com/openmicroscopy/openmicroscopy/pull/4664#issuecomment-219649402 is not a regression, was always there. I tend to press Shift as I am DnDing.

**Comment by gusferguson** [comment]
+1
Good to merge then.

**Comment by jburel** [comment]
@dominikl: we have tried to avoid 
import package.*

**Comment by jburel** [comment]
``Collection<ROINode> tmp = get(folder);``` could the collection be ``null`` or is it always an empty list if the object is not found.

**Comment by jburel** [comment]
You may want to add some "null" check in the ROIUtil just in case the specified parameters are `` null``

**Comment by jburel** [comment]
This can be done in another PR

**Comment by dominikl** [comment]
Removed the static imports. Ok, will add null checks in ROIUtil in another PR, likely that there will get more methods added to ROIUtil anyway.

**Comment by jburel** [comment]
travis is green. Merging to unlock @dominikl

**Pull request merged**
