### PR TITLE
Mouse wheel Z-frame scrolling

### PR DESCRIPTION
**Pull request by dominikl**
Fixes [Ticket 12829](http://trac.openmicroscopy.org.uk/ome/ticket/12829)

Test: Open an image (not a *big* image) with multiple Z frames. Make sure the mouse wheel scrolling through the Z frames works.

### CODE REVIEW

**Comment by mtbc** [comment]
Good to merge.

**Comment by will-moore** [comment]
@dominikl Certainly the mouse-wheel scrolling works, but it sometimes also zooms the image. I'm not sure exactly what triggers this, but if I scroll up and down repeatedly, I usually end up at a higher zoom level. This happens most reliably at max Z when all scrolling results in zoom, but also can happen at anyt other Z-index too. Also, clicking and dragging of the image with the mouse still changes the z-index instead of panning, but maybe you meant to fix that in a different PR?

**Comment by mtbc** [comment]
Gah, sorry I missed that misfeature.

**Comment by dominikl** [comment]
@will-moore I can't reproduce the mixed scroll/zoom behaviour. There's a difference between small and big images. Small images: Scroll and drag change Z frame, no zoom; big images: scroll zooms in/out, drag moves the image around. I think that's intended.

**Pull request merged**
