### PR TITLE
Import as owner

### PR DESCRIPTION
**Pull request by jburel**
Allow group owner to import data for another member of the group.
Test:
 * Log in as group owner and import data for another. e.g. user-1 and user-3.
 * Check that you can still import as an admin.

### CODE REVIEW

**Comment by jburel** [comment]
@pwalczysko: it looks that I have introduced an issue with refresh (in tree)
I will check that

**Comment by pwalczysko** [comment]
Just as it was reported with the admin Import As workflow (see https://trac.openmicroscopy.org/ome/ticket/12676), this workflow also has a problem when you import for different users in one session. 

  - login as user-1 (owner of private-10
  - Import for user-2
  - while import is running, import for user-12 (create a screen on import stage)

Observe dialog as on screenshot. The spinners will spin forever. Need to shut down Insight. After Insight reopened, only the data for user-1 have been imported.

**Comment by pwalczysko** [comment]
Login to hake, port 4064 as user-1 (=owner of private-1).
Import for user-12 into a pre-created Screen a plate (bd-pathway). 

get
```
java.lang.Exception: Abnormal termination due to an uncaught exception.
java.lang.IllegalArgumentException: No data to load
	at org.openmicroscopy.shoola.agents.fsimporter.ImportResultLoader.<init>(ImportResultLoader.java:96)
	at org.openmicroscopy.shoola.agents.fsimporter.view.ImporterModel.fireImportResultLoading(ImporterModel.java:498)
	at org.openmicroscopy.shoola.agents.fsimporter.view.ImporterComponent.onImportComplete(ImporterComponent.java:878)
	at org.openmicroscopy.shoola.agents.fsimporter.view.ImporterControl.handlePropertyChangedEvent(ImporterControl.java:426)
	at org.openmicroscopy.shoola.agents.fsimporter.view.ImporterControl.access$200(ImporterControl.java:93)
	at org.openmicroscopy.shoola.agents.fsimporter.view.ImporterControl$4.run(ImporterControl.java:383)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Abnormal termination due to an uncaught exception.
java.lang.IllegalArgumentException: No data to load
	at org.openmicroscopy.shoola.agents.fsimporter.ImportResultLoader.<init>(ImportResultLoader.java:96)
	at org.openmicroscopy.shoola.agents.fsimporter.view.ImporterModel.fireImportResultLoading(ImporterModel.java:498)
	at org.openmicroscopy.shoola.agents.fsimporter.view.ImporterComponent.onImportComplete(ImporterComponent.java:878)
	at org.openmicroscopy.shoola.agents.fsimporter.view.ImporterControl.handlePropertyChangedEvent(ImporterControl.java:426)
	at org.openmicroscopy.shoola.agents.fsimporter.view.ImporterControl.access$200(ImporterControl.java:93)
	at org.openmicroscopy.shoola.agents.fsimporter.view.ImporterControl$4.run(ImporterControl.java:383)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0"

	at org.openmicroscopy.shoola.env.ui.UserNotifierImpl.showErrorDialog(UserNotifierImpl.java:191)
	at org.openmicroscopy.shoola.env.ui.UserNotifierImpl.notifyError(UserNotifierImpl.java:291)
	at org.openmicroscopy.shoola.env.AbnormalExitHandler.doTermination(AbnormalExitHandler.java:147)
	at org.openmicroscopy.shoola.env.AbnormalExitHandler.terminate(AbnormalExitHandler.java:85)
	at org.openmicroscopy.shoola.env.RootThreadGroup.uncaughtException(RootThreadGroup.java:69)
	at java.awt.EventDispatchThread.processException(EventDispatchThread.java:223)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:215)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by pwalczysko** [comment]
Repeated https://github.com/openmicroscopy/openmicroscopy/pull/3572#issuecomment-77543764 on trout merge. Import for user-12, in private-1, logged in as user-1 and create a new Screen at import stage - crash and error as above.

**Comment by jburel** [comment]
@pwalczysko: 
 * importing for 2 different users when there is an on-going import. I do not think that is introduced by this PR.
 * No data load. I think I found the issue. Fixed https://github.com/openmicroscopy/openmicroscopy/commit/d1097d72116ef0f4f9ccac62611eb45b988cc5d5

**Comment by pwalczysko** [comment]
@jburel Ad point 1 - yes, I agree, it was there before as the admin worklfow suggests, but it is a bit of a killer for the workflow - maybe fix in another PR ?
Ad point 2 - will retest tomorrow, now everything crashes.

**Comment by jburel** [comment]
@pwalczysko: agree, probably in another PR. I will investigate. Fixing a push for the refresh issue introduced.
An extra step in testing on monday will be: check that you can refresh tree in data manager.

**Comment by jburel** [comment]
@pwalczysko: refresh issue if fixed with the last commit.

**Comment by joshmoore** [comment]
On merge, a comment should be added to https://www.openmicroscopy.org/community/viewtopic.php?f=4&t=7754

**Comment by dominikl** [comment]
I can import images and refresh the browser without problems. But after importing screens I also get the IllegalArgumentException
```
java.lang.IllegalArgumentException: No data to load
	at org.openmicroscopy.shoola.agents.fsimporter.ImportResultLoader.<init>(ImportResultLoader.java:96)
	at org.openmicroscopy.shoola.agents.fsimporter.view.ImporterModel.fireImportResultLoading(ImporterModel.java:501)
```
(Logged in as user-1/private-1, imported for user-2)

**Comment by jburel** [comment]
@dominikl: do you have it after importing in P/D view?

**Comment by dominikl** [comment]
Yes, I was in P/D view.

**Comment by dominikl** [comment]
Just tried again, also got the exception when I'm in Screen/Plate view.

**Comment by dominikl** [comment]
This happens generally on screen/plate import, not just on import for another user.

**Comment by dominikl** [comment]
I still get the "no data" error, see https://qa.staging.openmicroscopy.org/qa/feedback/9582/
But now the file is imported as dataset only, not as plate anymore. This really might just be related to this image. I'll test the PR with another plate/screen.

**Comment by pwalczysko** [comment]
@jburel @dominikl I also get the "no data" error on importing bd-pathway plate into trout merge with today's Insight.

**Comment by pwalczysko** [comment]
Unfortunately, I was able to repeat the same problem on trout / latest with 5.1 latest build ! 
```
ava.lang.Exception: Abnormal termination due to an uncaught exception.
java.lang.IllegalArgumentException: No data to load
	at org.openmicroscopy.shoola.agents.fsimporter.ImportResultLoader.<init>(ImportResultLoader.java:96)
	at org.openmicroscopy.shoola.agents.fsimporter.view.Impor
```
Definitely not a fault of this PR then, but seems like an obvious blocker

**Comment by pwalczysko** [comment]
cc @joshmoore

**Comment by jburel** [comment]
Will have a look over the weekend.

**Comment by dominikl** [comment]
@jburel Created a PR on your branch, that would avoid the error being thrown: https://github.com/jburel/openmicroscopy/pull/7

**Comment by pwalczysko** [comment]
The import As functionality here works as expected. From the UI perspective all imports of plates (bd-pathway) went also as expected. Nevertheless, @sbesson is reporting that there are errors on the server.

**Comment by sbesson** [comment]
Errors server-side at import are likely related to the restrict download effort but are independent of this PR as I could reproduce using the CLI import with the same data.

**Comment by jburel** [comment]
Posted reply to https://www.openmicroscopy.org/community/viewtopic.php?f=4&t=7754&p=15489#p15489

**Comment by jburel** [comment]
--no-rebase

**Pull request merged**
