### PR TITLE
Load format

### PR DESCRIPTION
**Pull request by jburel**
Load the format when loading the image

### CODE REVIEW

**Comment by dominikl** [comment]
Integration tests failed, image.getFormat() is null.

**Comment by jburel** [comment]
I think I will need to add a new test since this image generated in the test probably does not have the format set.

**Comment by mtbc** [comment]
It might be worth adding a setFormat to ModelMockFactory.simpleImage.

**Comment by jburel** [comment]
This image now has the format set.
The tests now pass
```
===============================================
Ant suite
Total tests run: 41, Failures: 0, Skips: 0
===============================================
```

**Comment by dominikl** [comment]
Looks fine, tests passed, too. Good to merge.

**Pull request merged**
