### PR TITLE
Chown tests

### PR DESCRIPTION
**Pull request by will-moore**
# What this PR does

Adds integration tests for existing Chown functionality and new gateway tests for `conn.chownObjects()` in https://github.com/ome/omero-py/pull/195

### CODE REVIEW

**Comment by will-moore** [comment]
Travis build failing like this a couple of times now...
```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by joshmoore** [comment]
Took me 5 or 6 runs for my most recent test PR.

**Comment by will-moore** [comment]
Excluding for now reduce test failures while waiting for https://github.com/ome/omero-py/pull/195 to pass travis.

**Comment by will-moore** [comment]
Removed the 'exclude' since https://github.com/ome/omero-py/pull/195 is now passing travis and should be included...

**Pull request merged**
