### PR TITLE
remove windows support

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
test like https://github.com/openmicroscopy/openmicroscopy/pull/4565, https://github.com/openmicroscopy/openmicroscopy/pull/4589 and https://github.com/openmicroscopy/openmicroscopy/pull/4592 (see https://github.com/openmicroscopy/openmicroscopy/pull/4601 for reference)

All the appropriate plugins should fail with ERROR

That is the end of Windows

### CODE REVIEW

**Comment by jburel** [comment]
I had to update the windows laptop in order to be able to test this PR.
I will finish on Monday

**Comment by jburel** [comment]
You may also want to remove:
``
if platform.system() in ("Windows",):
    LOGGING_CLASS = 'logging.handlers.RotatingFileHandler'
else:
    LOGGING_CLASS = 'omero_ext.cloghandler.ConcurrentRotatingFileHandler'

``
in ``settings.py`` under omeroweb

**Comment by aleksandra-tarkowska** [comment]
good spot, thx

**Comment by jburel** [comment]
I have removed the ref to windows in the comment in the same file.
you can cherry-pick the commit if you want https://github.com/jburel/openmicroscopy/commit/6f99a03f7fb4c0e49bc5ddff677fb477437c2205
or redo the changes.

**Comment by jburel** [comment]
As expected, it dies when running the command:
``bin\omero db script``

``windows_warning.py" line 25 
``self.ctx.die.die(WINDOWS_WARNING)
TypeError: die() takes at least 3 arguments (2 given)
``

**Comment by aleksandra-tarkowska** [comment]
my apology, try now

**Comment by jburel** [comment]
The error message ``OMERO.server support was removed...`` is now correctly displayed when I run ``bin\omero db script``

**Comment by jburel** [comment]
you can probably also delete ```omero_web_iis.py```

**Comment by aleksandra-tarkowska** [comment]
done, I hope that is all

**Comment by joshmoore** [comment]
LGMT.

**Pull request merged**
