### PR TITLE
Fixed ClassCastException

### PR DESCRIPTION
**Pull request by dominikl**
Tiny bugfix for [QA 17191](https://www.openmicroscopy.org/qa2/qa/feedback/17191/) to prevent potential ClassCastException (`result` object is not guaranteed to be an instance of Set, e.g. see https://github.com/openmicroscopy/openmicroscopy/blob/develop/components/blitz/src/omero/gateway/facility/BrowseFacility.java#L1008 ).

**Test**: Code review should be sufficient. Don't know how to easily replicate the bug. Would need an experimenter without user image set, but all experimenters actually have this user icon as default user image.

### CODE REVIEW

**Comment by jburel** [comment]
The change in that section of the code makes sense but the problem is coming from the gateway method itself.
in ``BrowseFacility#getOrphanedImages``: if the user has images, a set is returned, if no images, an empty list is returned.
but the ``getUserImages`` method always returns a list.

**Comment by dominikl** [comment]
Ah yes, sorry, was refering to the wrong method in my comment. Just changed the method to always return a Set (see last commit). Although List would make more sense. Don't know why `PojoMapper.asDataObjects(...)` was implemented to return a Set in first place, as DataObjects don't overwrite `hashCode()` HashSets of DataObjects won't work as expected anyway.

**Comment by jburel** [comment]
@dominikl: it might be a good opportunity to review the ``PojoMapper`` method: deprecated and introduced a new one

**Comment by jburel** [comment]
@dominik: Do you want to review the ``PojoMapper`` in this PR?
Otherwise I will merge it

**Comment by dominikl** [comment]
Ah yes, was originally planning to do it in this PR, but might be cleaner to do it in a separate PR. Just go ahead and merge it. Thanks.

**Comment by jburel** [comment]
Card created https://trello.com/c/ifii0bT2/116-pojomapper-review

**Pull request merged**
