### PR TITLE
Handle new ROI Points string format

### PR DESCRIPTION
**Pull request by manics**
There are (at least) 2 formats for storing Points in ROI Polygons. The webgateway only had one of them.

https://trello.com/c/hJLlf1Xr/47-error-on-preview-rois

Are there any other formats?

### CODE REVIEW

**Comment by manics** [comment]
--rebased-to #3933

**Comment by joshmoore** [comment]
Implementation looks good. Up for cherry-picking https://github.com/joshmoore/openmicroscopy/commit/ac9fea252e9ad5abed60408d6f79781b0fc786e1 ?

As for whether or not there are other legacy formats, I don't know.

**Comment by manics** [comment]
Done

**Comment by jburel** [comment]
There is also some legacy "mask" points see https://github.com/openmicroscopy/openmicroscopy/blob/develop/components/blitz/src/pojos/PolygonData.java

**Comment by manics** [comment]
Looking at the original https://github.com/openmicroscopy/openmicroscopy/blob/673d1c2f11e1cdfc2c28936a0376682b94bdb7c8/components/tools/OmeroWeb/omeroweb/webgateway/views.py#L460

Only the first set of points is taken, so mask would never be used. Is that correct?

**Comment by joshmoore** [comment]
Talking to @jburel, the `masks[]` is legacy. Merging.

**Comment by manics** [comment]
--no-rebase

**Comment by manics** [comment]
--rebased-from #3933

**Pull request merged**
