### PR TITLE
Rendering issue dev_5_1

### PR DESCRIPTION
**Pull request by jburel**
Fix problem related to floating point rendering (and 32-bit)
See ticket https://trac.openmicroscopy.org/ome/ticket/12912

To test:
 * import image from QA 11111 and check https://www.openmicroscopy.org/community/viewtopic.php?f=4&t=7825  for details of problem
 * also image ​https://trout.openmicroscopy.org/merge/webclient/img_detail/24054/ under user-1 should be fixed.

cc @sbesson

### CODE REVIEW

**Comment by sbesson** [comment]
Tested using the 3 files mentioned above (Deltavision QA + the 2 map files from the ome-devel thread). Rendering issues are reproduced without this PR and are fixed 
screen shot 2015-08-28 at 10 32 38
screen shot 2015-08-28 at 10 32 42
screen shot 2015-08-28 at 10 32 45
screen shot 2015-08-28 at 10 32 52

From a client point of view, the fix is working as expected. From a maintenance point of view, I have not a clear view of the cost of starting adding unit tests for the `omeis.providers.re.quantum` package. Any thought on this?

**Comment by jburel** [comment]
We have already some units tests for re under server. Will see what we can do to track such problems

**Comment by sbesson** [comment]
Merging for now so we can move forward.

**Comment by jburel** [comment]
--rebased-to #4144

**Pull request merged**
