### PR TITLE
Don't close session test

### PR DESCRIPTION
**Pull request by dominikl**
Integration test for https://github.com/ome/omero-gateway-java/pull/11

### CODE REVIEW

**Comment by joshmoore** [comment]
Do the tests need to call `disconnect`?

**Comment by dominikl** [comment]
Not necessarily, as the Gateway is created in the `try` block `disconnect` is called automatically (via `AutoCloseable`).

**Comment by joshmoore** [comment]
Of course, _smacks head_. Nice!

**Comment by joshmoore** [comment]
Tests green in https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/72/

**Pull request merged**
