### PR TITLE
Polygon/polyline parsing

### PR DESCRIPTION
**Pull request by jburel**
# What this PR does

Fix an issue when opening polygon or polyline created in viewer

# Testing this PR

* Open an image in iviewer
* create polygon and polyline
* Save the shapes
* Install insight-ij plugin in fiji
* Open the image with the rois using B-F importer

Repeat the same workflow but this time create polygon and polyline in insight

# Related reading
https://trello.com/c/5xRX0hea/69-reading-polygon-polyline-omeroreader

cc @bramalingam

### CODE REVIEW

**Comment by bramalingam** [comment]
Tested:
1) Polygons created in ImageJ
2) Polygons and polylines created manually in Insight
3) Polygons and poly lines created manually in iViewer

And in all cases the ROI's opened in ImageJ without any issues.
**Looks good to merge.**

Example screenshots:

ROI's in Grey(Created with Insight), ROI's in Magenta (Created with iViewer)
screen shot 2017-12-11 at 17 04 05

ROI's created using ImageJ and Imported into OMERO (Via the manual ImageJ workflow)
screen shot 2017-12-11 at 17 04 22

**Comment by jburel** [comment]
@bramalingam could you double-check with web-latest/eel-latest?
I am expecting it to fail

**Comment by bramalingam** [comment]
Tested with the latest download version as well, and the image with Polygon and Polylines drawn via iViewer fails to open via the OMERO.IJ plugin in Fiji.  So the current fix, fixes an existing bug for sure.

**Comment by joshmoore** [comment]
Note: the history here looks surprising. I didn't dig into _why_ yet.

**Comment by jburel** [comment]
PR was initially opened against develop.

**Comment by joshmoore** [comment]
Ok. Guess let's look into force-pushing when unexpected PRs show up after changing the target branch of a PR. Following the lineage here could get quickly intractable.

**Comment by jburel** [comment]
I forgot to mention that I forced pushed few days ago and there is only one commit on top 5.4.1 on the workflows branch
```
Author: Jean-Marie Burel <j.burel@dundee.ac.uk>
Date:   Sat Dec 9 16:01:34 2017 +0000

    support polygon/polyline created by iviewer

commit 5510466f59073079ef7bfb92f8a88386607d39a3 (tag: v5.4.1)
Merge: 42eb7b422f 46becf9c51
Author: jean-marie burel <j.burel@dundee.ac.uk>
Date:   Wed Nov 22 19:48:32 2017 +0000

    Merge pull request #5581 from dgault/bump-bf-5.7.2
    
    BF bump to 5.7.2

```

**Comment by hflynn** [comment]
Can you remove the 5.4.2 milestone from this PR please?

**Comment by joshmoore** [comment]
Done.

**Pull request merged**
