### PR TITLE
Download_as closes RE

### PR DESCRIPTION
**Pull request by will-moore**
This fixes http://trac.openmicroscopy.org/ome/ticket/12794 which is due to a couple of bugs in webgateway/download_as for batch exporting images as PNG, JPG etc. See https://www.openmicroscopy.org/community/viewtopic.php?f=5&t=7766

We were using ``` @login_required(doConnectionCleanup=False) ``` incorrectly here, since we are not streaming data from OMERO directly (don't need to keep services open once the request returns and streaming starts). This meant that open Rendering Engines were not getting closed.

We were also failing to call image._re.close() for each image after rendering and saving into the zip folder. For each image, a new ProxyObjectWrapper for each rendering engine was getting created but the underlying rendering engines were not getting closed each time.

Both these issues are fixed now.
Need to test that all "Export As" functionality is still working.

Potential backport https://trello.com/c/tgJwB05l/188-5-0-9-potential-backports

--no-rebase

### CODE REVIEW

**Comment by joshmoore** [comment]
Thanks for this, @will-moore. The only thing I would add for these close statements would be that having them in a try/finally would be double-plus-good.

**Comment by will-moore** [comment]
@joshmoore Is that what you meant?

**Comment by gusferguson** [comment]
@will-moore 

Tested with https://trout.openmicroscopy.org/merge/webclient/ user-3 read-only-1 and user-12 on user-3 data.

Behaves as expected.
Good to merge.

**Comment by joshmoore** [comment]
@will-moore : exactly. Thanks. If we could slowly but consistently move to having that everywhere, it'd be great.

**Comment by will-moore** [comment]
@joshmoore OK. For most web uses we only access an image at a time, so we don't get a ton of open REs, but certainly Batch_Image_Export script and OMERO.figure export script need this.

**Comment by will-moore** [comment]
PR for Batch_Image_Export: https://github.com/ome/scripts/pull/100

**Comment by joshmoore** [comment]
Great, thanks, @will-moore!

**Pull request merged**
