### PR TITLE
Clean up VM installation folder (rebased onto dev_5_1)

### PR DESCRIPTION
**Pull request by sbesson**
This is the same as gh-4058 but rebased onto dev_5_1.

----

Following migration of the Virtual Appliance scripts to a standalone repository, this commit cleans up the duplicate scripts under the main source code repository.

/cc @manics

### CODE REVIEW

**Comment by sbesson** [comment]
--rebased-from #4058

**Comment by sbesson** [comment]
@jburel: did you have time to check this?

**Comment by jburel** [comment]
@sbesson: sorry did not manage yesterday.

**Comment by jburel** [comment]
The target  ```build-vm``` in the ``build.xml``` needs to be removed too

**Comment by sbesson** [comment]
definitely. I can push to this PR or open a separate one?

**Comment by jburel** [comment]
Push to this one so we have everything in one location, and cherry-pick the commit

**Comment by sbesson** [comment]
Pushed

**Comment by jburel** [comment]
Looks good. The last commit will have to be cherry-picked.

**Comment by sbesson** [comment]
Yes i'll rebase

**Comment by sbesson** [comment]
@jburel want to merge this in the meantime?

**Comment by sbesson** [comment]
--rebased-to #4095

**Pull request merged**
