### PR TITLE
small adjustments to server code/doc

### PR DESCRIPTION
**Pull request by mtbc**
This gets some small server code/doc adjustments into 5.2.1. They're from branches of larger work that will go into later versions, but we may as well avoid making releases without these small improvements in. Everything should remain green.

--no-rebase

### CODE REVIEW

**Comment by jburel** [comment]
changes work, 
If a class uses the "old way" (object instead of generic), there will probably be only a warning.
Not sure if we have a good way to represent that case.

**Comment by mtbc** [comment]
As far as I can tell, one can even write a non-generic subclass of `Work` overriding `doWork` and the code still compiles.

**Comment by mtbc** [comment]
Does anything further need doing here?

**Comment by joshmoore** [comment]
If `DummyExecutor` *required* updating to make this compile, then this would count as a breaking change for anyone who had subclassed `Executor`.

**Comment by mtbc** [comment]
Definitely seems best not to touch `Work` so I can get this in before disappearing for the holiday, so have force-pushed that bit away. :smiley:

**Comment by joshmoore** [comment]
https://ci.openmicroscopy.org/view/DEV/job/OMERO-DEV-merge-integration/176/ :thumbsup:

**Pull request merged**
