### PR TITLE
robotframework : Test default (edit) behaviour of Administrator's groups list

### PR DESCRIPTION
**Pull request by bramalingam**
To Test:
```
./build.py -f components/tests/ui/build.xml web-chrome -DTEST=webadmin_create_group_and_user.txt
```
And check if all tests pass. 

Note: Please follow set-up instructions given in "openmicroscopy/components/tests/ui/README.md", before running the test. Please install google chrome as well.

### CODE REVIEW

**Comment by sbesson** [comment]
From https://ci.openmicroscopy.org/view/Failing/job/OMERO-5.1-merge-robotframework/181/console, test seems to be passing on `chrome` but not `firefox`

**Comment by will-moore** [comment]
Seems to me that this is failing on both Firefox and Chrome.

**Comment by will-moore** [comment]
We're using the ```robot_user``` name here not root's full name. Need to hard code a config like:
```
${FULL ROOT NAME} 		root root
```

**Comment by sbesson** [comment]
@bramalingam: the place to add @will-moore's suggestion would be https://github.com/openmicroscopy/openmicroscopy/blob/develop/components/tests/ui/resources/robot.template

**Comment by bramalingam** [comment]
@sbesson @will-moore : Hopefully those two commits should address the issue.

**Comment by sbesson** [comment]
See https://ci.openmicroscopy.org/view/Failing/job/OMERO-5.1-merge-robotframework/182/console. Failure on Firefox but passing on Chrome.

**Comment by bramalingam** [comment]
test pases locally:

```
ls29010:openmicroscopy bramalingam$ ./build.py -f components/tests/ui/build.xml web-firefox -DTEST=webadmin_create_group_and_user.txt
Buildfile: /Users/bramalingam/OME/openmicroscopy/components/tests/ui/build.xml
Entering /Users/bramalingam/OME/openmicroscopy/components/tests/ui...

web-firefox:
==============================================================================
Webadmin Create Group And User :: A test suite with a single test for valid...
==============================================================================
Check Group Form :: Tests elements on the create group page           | PASS |
------------------------------------------------------------------------------
Check User Form :: Tests elements on the create user page             | PASS |
------------------------------------------------------------------------------
Create Edit Group :: Tests group creation                             | PASS |
------------------------------------------------------------------------------
Create Edit User                                                      | PASS |
------------------------------------------------------------------------------
Check Admin Edit Self                                                 | PASS |
------------------------------------------------------------------------------
Webadmin Create Group And User :: A test suite with a single test ... | PASS |
5 critical tests, 5 passed, 0 failed
5 tests total, 5 passed, 0 failed
==============================================================================
Output:  /Users/bramalingam/OME/openmicroscopy/components/tests/ui/target/reports/web/firefox/output.xml
Log:     /Users/bramalingam/OME/openmicroscopy/components/tests/ui/target/reports/web/firefox/log.html
Report:  /Users/bramalingam/OME/openmicroscopy/components/tests/ui/target/reports/web/firefox/report.html

BUILD SUCCESSFUL
Total time: 14 seconds
```

**Comment by sbesson** [comment]
Both tests pass on https://ci.openmicroscopy.org/view/Failing/job/OMERO-5.1-merge-robotframework/183/. Merging. We can review the  stability of the test over several iteration of the CI job and extend the sleep if necessary.

**Comment by bramalingam** [comment]
--no-rebase

**Pull request merged**
