### PR TITLE
Improving robot (rebased onto develop)

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
This is the same as gh-4112 but rebased onto develop.

----

This fixes delete tests. It removes sleep and set timeout now to 60 sec.

### CODE REVIEW

**Comment by aleksandra-tarkowska** [comment]
--rebased-from #4112

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#76](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/76/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/76/consoleText) for more details.
Possible conflicts:
  - PR #3995 will-moore 'Jstree 2015'
    - components/tests/ui/testcases/web/delete_test.txt

**Comment by will-moore** [comment]
I just merged this into jstree_2015 #3995 (before you removed a couple of commits): https://github.com/will-moore/openmicroscopy/commit/923b08c44e47eedea97d32645138ae8d3d90c652

**Comment by aleksandra-tarkowska** [comment]
Sorry @will-moore I removed the part we discussed to keep rebase consistent.

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#80](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/80/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/80/consoleText) for more details.
Possible conflicts:
  - PR #3995 will-moore 'Jstree 2015'
    - components/tests/ui/testcases/web/delete_test.txt

**Comment by will-moore** [comment]
@aleksandra-tarkowska Probably best just to close this PR and mark #4112 as #no-rebase?

**Pull request closed without merging**
