### PR TITLE
Reduce likelihood of test_inputs failing intermittently 

### PR DESCRIPTION
**Pull request by ximenesuk**
`test_inputs` uses a callback block time of 500ms while a similar test, `test_rand`, has 2000ms. Increasing the former to 2000 seems to make the test reproducibly pass locally. (Conversely, decreasing the latter to 500 causes that test to fail intermittently.)The only test here is whether this test passes in the CI builds.

—no-rebase
(though this could well be rebased if necessary)

### CODE REVIEW

**Comment by ximenesuk** [comment]
While checking the modified test I noticed that it and `test_rand` could not be run repeatedly using the `pytest` option `—repeat`. While the first test would pass, any subsequent runs would fail:
```
$ py.test test/integration/scriptstest/test_inputs.py --repeat 2
=========================================================================================== test session starts ============================================================================================
platform darwin -- Python 2.7.8 -- py-1.4.26 -- pytest-2.6.4
plugins: rerunfailures, xdist
collected 2 items

test/integration/scriptstest/test_inputs.py .F

================================================================================================= FAILURES =================================================================================================
_________________________________________________________________________________________ TestInputs.testInputs[1] _________________________________________________________________________________________

self = <test_inputs.TestInputs object at 0x113a28c90>

    @pytest.mark.intermittent(reason="Process still running.",
                              ticket="12314")
    def testInputs(self):
        import logging
        logging.basicConfig(level=10)
        scripts = self.root.getSession().getScriptService()
        sendfile = SENDFILE % self.omeropydir()
        id = scripts.uploadScript(
            "/tests/inputs_py/%s.py" % self.uuid(), sendfile)
        input = {"a": rint(100)}
        impl = omero.processor.usermode_processor(self.root)
        try:
>           process = scripts.runScript(id, input, None)

test/integration/scriptstest/test_inputs.py:108:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = 1a8bc9dc-83fe-49b3-96d2-05b43e1f9516/2dad948b-899a-4c89-96a0-d69b7e4078f9omero...IScript -t -e 1.0:tcp -h 10.128.209.127 -p 61793:tcp -h 134.36.162.223 -p 61793, scriptID = 685L
inputs = {'a': object #0 (::omero::RInt)
{
    _val = 100
}}, waitSecs = None, _ctx = None

    def runScript(self, scriptID, inputs, waitSecs, _ctx=None):
>       return _M_omero.api.IScript._op_runScript.invoke(self, ((scriptID, inputs, waitSecs), _ctx))

    '''If [ResourceError] is thrown, then no [Processor] is available. Use [scheduleJob]
    to create a [omero::model::ScriptJob] in the "Waiting" state. A [Processor] may
    become available.

    try:
    proc = scriptService.runScript(1, {}, None)
    except ResourceError:
    job = scriptService.scheduleScript(1, {}, None)

    The [ScriptProcess] proxy MUST be closed before exiting.
    If you would like the script execution to continue in the
    background, pass "True" as the argument.

    try:
    proc.poll()         # See if process is finished
    finally:
    proc.close(True)    # Detach and execution can continue
E   InternalException: exception ::omero::InternalException
E   {
E       serverStackTrace = Traceback (most recent call last):
E     File "/Users/cblackburn/Work/repos/ome/dist/lib/python/omero/util/decorators.py", line 68, in exc_handler
E       rv = func(*args, **kwargs)
E     File "/Users/cblackburn/Work/repos/ome/dist/lib/python/omero/processor.py", line 937, in processJob
E       client, session, job, current, params, iskill=True)
E     File "/Users/cblackburn/Work/repos/ome/dist/lib/python/omero/util/decorators.py", line 28, in handler
E       return func(*args, **kwargs)
E     File "/Users/cblackburn/Work/repos/ome/dist/lib/python/omero/processor.py", line 985, in process
E       self.resources.add(process)
E   AttributeError: 'NoneType' object has no attribute 'add'
E
E       serverExceptionClass =
E       message = Internal exception
E   }

../../../dist/lib/python/omero_api_IScript_ice.py:762: InternalException
------------------------------------------------------------------------------------------- Captured stderr call -------------------------------------------------------------------------------------------
WARNING:omero.remote:<function parseJob at 0x113704488> raised a non-ServerError (<type 'exceptions.AttributeError'>): 'NoneType' object has no attribute 'add'
WARNING:omero.remote:<function processJob at 0x113704578> raised a non-ServerError (<type 'exceptions.AttributeError'>): 'NoneType' object has no attribute 'add'
=================================================================================== 1 failed, 1 passed in 14.96 seconds ====================================================================================
$
```
/cc @sbesson @joshmoore

**Comment by ximenesuk** [comment]
This second commit fixes the issue above. See https://github.com/sbesson/openmicroscopy/commit/4cd91d9dafee31ba96f93d864572ab4695b09c87

All non-broken tests are now repeatable:

```
$ py.test test/integration/scriptstest/ --repeat 2 -m "not broken"
=========================================================================================== test session starts ============================================================================================
platform darwin -- Python 2.7.8 -- py-1.4.26 -- pytest-2.6.4
plugins: rerunfailures, xdist
collected 50 items

test/integration/scriptstest/test_coverage.py ......
test/integration/scriptstest/test_inputs.py ..
test/integration/scriptstest/test_make_movie.py ..
test/integration/scriptstest/test_ping.py ....................
test/integration/scriptstest/test_rand.py ..
test/integration/scriptstest/test_repo.py ..............

================================================================================= 4 tests deselected by "-m 'not broken'" ==================================================================================
================================================================================ 46 passed, 4 deselected in 196.65 seconds =================================================================================
```

**Comment by ximenesuk** [comment]
See https://trello.com/c/a51Okibq/376-investigate-scripts-integration-tests

**Comment by joshmoore** [comment]
Based on https://ci.openmicroscopy.org/job/OMERO-5.1-merge-integration-python/393/, merging.

**Pull request merged**
