### PR TITLE
Rename and deprecated ReverseIntensityMap/Context

### PR DESCRIPTION
**Pull request by dominikl**
# What this PR does

Deprecates 'ReverseIntensityMap' and ReverseIntensityContext' and adds the equivalents 'InverseIntensityMap'  and 'InverseIntensityContext'.
Replaces #5435 

# Testing this PR

# Related reading
https://trello.com/c/AN7eXyM3/19-rename-in-viewers-reverse-intensity

--exclude  **!! Does not work !!**

For some reason this breaks imports and rendering settings. Any ideas why @mtbc / @jburel ?
E. g. import:
```
java.lang.RuntimeException: Failure response on import!
Category: ::omero::grid::ImportRequest
Name: import-request-failure
Parameters: {stacktrace=java.lang.RuntimeException: omero.ApiUsageException
    serverStackTrace = "ome.conditions.ApiUsageException: could not execute query; SQL [select renderingd0_.id as id124_0_, experiment1_.id as id34_1_, quantumdef2_.id as id121_2_, renderingm3_.id as id125_3_, waverender4_.id as id11_4_, family5_.id as id39_5_, spatialdom6_.id as id13_6_, projection7_.id as id118_7_, projection8_.id as id117_8_, projection9_.id as id119_9_, renderingd0_.compression as compress2_124_0_, renderingd0_.defaultT as defaultT124_0_, renderingd0_.defaultZ as defaultZ124_0_, renderingd0_.creation_id as creation8_124_0_, renderingd0_.external_id as external9_124_0_, renderingd0_.group_id as group10_124_0_, renderingd0_.owner_id as owner11_124_0_, renderingd0_.permissions as permissi5_124_0_, renderingd0_.update_id as update12_124_0_, renderingd0_.model as model124_0_, renderingd0_.name as name124_0_, renderingd0_.pixels as pixels124_0_, renderingd0_.quantization as quantiz15_124_0_, renderingd0_.version as version124_0_, experiment1_.external_id as external11_34_1_, experiment1_.permissions as permissi2_34_1_, experiment1_.email as email34_1_, experiment1_.firstName as firstName34_1_, experiment1_.institution as institut5_34_1_, experiment1_.lastName as lastName34_1_, experiment1_.ldap as ldap34_1_, experiment1_.middleName as middleName34_1_, experiment1_.omeName as omeName34_1_, experiment1_.version as version34_1_, quantumdef2_.bitResolution as bitResol2_121_2_, quantumdef2_.cdEnd as cdEnd121_2_, quantumdef2_.cdStart as cdStart121_2_, quantumdef2_.creation_id as creation7_121_2_, quantumdef2_.external_id as external8_121_2_, quantumdef2_.group_id as group9_121_2_, quantumdef2_.owner_id as owner10_121_2_, quantumdef2_.permissions as permissi5_121_2_, quantumdef2_.update_id as update11_121_2_, quantumdef2_.version as version121_2_, renderingm3_.external_id as external4_125_3_, renderingm3_.permissions as permissi2_125_3_, renderingm3_.value as value125_3_, waverender4_.active as active11_4_, waverender4_.alpha as alpha11_4_, waverender4_.blue as blue11_4_, waverender4_.coefficient as coeffici5_11_4_, waverender4_.creation_id as creation14_11_4_, waverender4_.external_id as external15_11_4_, waverender4_.group_id as group16_11_4_, waverender4_.owner_id as owner17_11_4_, waverender4_.permissions as permissi6_11_4_, waverender4_.update_id as update18_11_4_, waverender4_.family as family11_4_, waverender4_.green as green11_4_, waverender4_.inputEnd as inputEnd11_4_, waverender4_.inputStart as inputStart11_4_, waverender4_.lookupTable as lookupT10_11_4_, waverender4_.noiseReduction as noiseRe11_11_4_, waverender4_.red as red11_4_, waverender4_.renderingDef as renderi20_11_4_, waverender4_.version as version11_4_, waverender4_.renderingDef as renderi20_124_0__, waverender4_.id as id0__, waverender4_.renderingDef_index as renderi21_0__, family5_.external_id as external4_39_5_, family5_.permissions as permissi2_39_5_, family5_.value as value39_5_, spatialdom6_.channelBinding as channelB4_13_6_, spatialdom6_.creation_id as creation5_13_6_, spatialdom6_.external_id as external6_13_6_, spatialdom6_.group_id as group7_13_6_, spatialdom6_.owner_id as owner8_13_6_, spatialdom6_.permissions as permissi2_13_6_, spatialdom6_.update_id as update9_13_6_, spatialdom6_.version as version13_6_, spatialdom6_1_.xend as xend15_6_, spatialdom6_1_.xstart as xstart15_6_, spatialdom6_1_.yend as yend15_6_, spatialdom6_1_.ystart as ystart15_6_, spatialdom6_2_.inverse as inverse70_6_, spatialdom6_3_."constant" as constant1_109_6_, spatialdom6_3_.lowerLimit as lowerLimit109_6_, spatialdom6_3_.planePrevious as planePre3_109_6_, spatialdom6_3_.planeSelected as planeSel4_109_6_, spatialdom6_3_.upperLimit as upperLimit109_6_, spatialdom6_4_."reverse" as reverse1_126_6_, case when spatialdom6_1_.codomainmapcontext_id is not null then 1 when spatialdom6_2_.codomainmapcontext_id is not null then 2 when spatialdom6_3_.codomainmapcontext_id is not null then 3 when spatialdom6_4_.codomainmapcontext_id is not null then 4 when spatialdom6_.id is not null then 0 end as clazz_6_, spatialdom6_.channelBinding as channelB4_11_1__, spatialdom6_.id as id1__, spatialdom6_.channelBinding_index as channel10_1__, projection7_.active as active118_7_, projection7_.axis as axis118_7_, projection7_.creation_id as creation9_118_7_, projection7_.external_id as external10_118_7_, projection7_.group_id as group11_118_7_, projection7_.owner_id as owner12_118_7_, projection7_.permissions as permissi3_118_7_, projection7_.update_id as update13_118_7_, projection7_.endPlane as endPlane118_7_, projection7_.renderingDef as renderi14_118_7_, projection7_.startPlane as startPlane118_7_, projection7_.stepping as stepping118_7_, projection7_.type as type118_7_, projection7_.version as version118_7_, projection7_.renderingDef as renderi14_124_2__, projection7_.id as id2__, projection7_.renderingDef_index as renderi16_2__, projection8_.external_id as external4_117_8_, projection8_.permissions as permissi2_117_8_, projection8_.value as value117_8_, projection9_.external_id as external4_119_9_, projection9_.permissions as permissi2_119_9_, projection9_.value as value119_9_ from renderingdef renderingd0_ left outer join experimenter experiment1_ on renderingd0_.owner_id=experiment1_.id left outer join quantumdef quantumdef2_ on renderingd0_.quantization=quantumdef2_.id left outer join renderingmodel renderingm3_ on renderingd0_.model=renderingm3_.id left outer join channelbinding waverender4_ on renderingd0_.id=waverender4_.renderingDef and (
                        
                          ( waverender4_.group_id = ? AND 
                             ( 1 = ? OR 
                               1 = ? OR 
                               waverender4_.owner_id = ?
                             )
                          ) OR
                          waverender4_.group_id = 1 OR 
                         1 = ?
                        ) left outer join family family5_ on waverender4_.family=family5_.id left outer join codomainmapcontext spatialdom6_ on waverender4_.id=spatialdom6_.channelBinding and (
                        
                          ( spatialdom6_.group_id = ? AND 
                             ( 1 = ? OR 
                               1 = ? OR 
                               spatialdom6_.owner_id = ?
                             )
                          ) OR
                          spatialdom6_.group_id = 1 OR 
                         1 = ?
                        )
                         left outer join contraststretchingcontext spatialdom6_1_ on spatialdom6_.id=spatialdom6_1_.codomainmapcontext_id left outer join inverseintensitycontext spatialdom6_2_ on spatialdom6_.id=spatialdom6_2_.codomainmapcontext_id left outer join planeslicingcontext spatialdom6_3_ on spatialdom6_.id=spatialdom6_3_.codomainmapcontext_id left outer join reverseintensitycontext spatialdom6_4_ on spatialdom6_.id=spatialdom6_4_.codomainmapcontext_id left outer join projectiondef projection7_ on renderingd0_.id=projection7_.renderingDef and (
                        
                          ( projection7_.group_id = ? AND 
                             ( 1 = ? OR 
                               1 = ? OR 
                               projection7_.owner_id = ?
                             )
                          ) OR
                          projection7_.group_id = 1 OR 
                         1 = ?
                        ) left outer join projectionaxis projection8_ on projection7_.axis=projection8_.id left outer join projectiontype projection9_ on projection7_.type=projection9_.id where (
                        
                          ( renderingd0_.group_id = ? AND 
                             ( 1 = ? OR 
                               1 = ? OR 
                               renderingd0_.owner_id = ?
                             )
                          ) OR
                          renderingd0_.group_id = 1 OR 
                         1 = ?
                        ) and (renderingd0_.pixels in (?)) and renderingd0_.owner_id=?]; nested exception is org.hibernate.exception.SQLGrammarException: could not execute query
                        	at org.springframework.orm.hibernate3.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:629)
                        	at org.springframework.orm.hibernate3.HibernateAccessor.convertHibernateAccessException(HibernateAccessor.java:412)
                        	at org.springframework.orm.hibernate3.HibernateTemplate.doExecute(HibernateTemplate.java:411)
                        	at org.springframework.orm.hibernate3.HibernateTemplate.execute(HibernateTemplate.java:339)
                        	at ome.logic.QueryImpl.execute(QueryImpl.java:142)
                        	at ome.logic.QueryImpl.findAllByQuery(QueryImpl.java:371)
                        	at ome.logic.RenderingSettingsImpl.loadRenderingSettings(RenderingSettingsImpl.java:440)
                        	at ome.logic.RenderingSettingsImpl.loadRenderingSettings(RenderingSettingsImpl.java:396)
                        	at ome.logic.RenderingSettingsImpl.resetDefaultsInSet(RenderingSettingsImpl.java:634)
                        	at ome.logic.RenderingSettingsImpl.resetDefaultsInSet(RenderingSettingsImpl.java:1455)
                        	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                        	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                        	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                        	at java.lang.reflect.Method.invoke(Method.java:498)
                        	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:307)
                        	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
                        	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
                        	at ome.security.basic.EventHandler.invoke(EventHandler.java:153)
                        	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
                        	at org.springframework.orm.hibernate3.HibernateInterceptor.invoke(HibernateInterceptor.java:111)
                        	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
                        	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:108)
                        	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
                        	at ome.tools.hibernate.ProxyCleanupFilter$Interceptor.invoke(ProxyCleanupFilter.java:249)
                        	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
                        	at ome.services.util.ServiceHandler.invoke(ServiceHandler.java:121)
                        	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
                        	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
                        	at com.sun.proxy.$Proxy99.resetDefaultsInSet(Unknown Source)
                        	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                        	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                        	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                        	at java.lang.reflect.Method.invoke(Method.java:498)
                        	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:307)
                        	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
                        	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
                        	at ome.security.basic.BasicSecurityWiring.invoke(BasicSecurityWiring.java:93)
                        	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
                        	at ome.services.blitz.fire.AopContextInitializer.invoke(AopContextInitializer.java:43)
                        	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
                        	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
                        	at com.sun.proxy.$Proxy99.resetDefaultsInSet(Unknown Source)
                        	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                        	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                        	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                        	at java.lang.reflect.Method.invoke(Method.java:498)
                        	at ome.services.blitz.util.IceMethodInvoker.invoke(IceMethodInvoker.java:172)
                        	at ome.services.throttling.Callback.run(Callback.java:56)
                        	at ome.services.throttling.InThreadThrottlingStrategy.callInvokerOnRawArgs(InThreadThrottlingStrategy.java:56)
                        	at ome.services.blitz.impl.AbstractAmdServant.callInvokerOnRawArgs(AbstractAmdServant.java:140)
                        	at ome.services.blitz.impl.RenderingSettingsI.resetDefaultsInSet_async(RenderingSettingsI.java:138)
                        	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                        	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                        	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                        	at java.lang.reflect.Method.invoke(Method.java:498)
                        	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:307)
                        	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
                        	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
                        	at omero.cmd.CallContext.invoke(CallContext.java:78)
                        	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
                        	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
                        	at com.sun.proxy.$Proxy100.resetDefaultsInSet_async(Unknown Source)
                        	at omero.api._IRenderingSettingsTie.resetDefaultsInSet_async(_IRenderingSettingsTie.java:144)
                        	at omero.api._IRenderingSettingsDisp.___resetDefaultsInSet(_IRenderingSettingsDisp.java:604)
                        	at omero.api._IRenderingSettingsDisp.__dispatch(_IRenderingSettingsDisp.java:970)
                        	at IceInternal.Incoming.invoke(Incoming.java:221)
                        	at Ice.ConnectionI.invokeAll(ConnectionI.java:2536)
                        	at Ice.ConnectionI.dispatch(ConnectionI.java:1145)
                        	at Ice.ConnectionI.message(ConnectionI.java:1056)
                        	at IceInternal.ThreadPool.run(ThreadPool.java:395)
                        	at IceInternal.ThreadPool.access$300(ThreadPool.java:12)
                        	at IceInternal.ThreadPool$EventHandlerThread.run(ThreadPool.java:832)
                        	at java.lang.Thread.run(Thread.java:748)
                        "
```

### CODE REVIEW

**Comment by mtbc** [comment]
Goodness, I didn't expect the ambition of adjusting the mappings file at this stage too. :smiley: @joshmoore may see some clear Hibernate-related issues.

**Comment by joshmoore** [comment]
I respect the impressive ambition as well. Note: though it should be possible to correct the `omero.api.*` usages, we'd still likely be stuck with the `omero.model.*` ones.

**Comment by dominikl** [comment]
Uhm, ok, will close this PR again then and only keep #5435 (only deprecate 'ReverseIntensityMap'). Although it's a bit strange to deprecate something without being able to offer an alternative.

**Comment by jburel** [comment]
we have done that recently with ``ROIService`` or ``OMEROReader``

**Comment by jburel** [comment]
@dominikl I think you were nearly there
you are missing:
 ``import omeis.providers.re.codomain.InverseIntensityContext;`` in `` components/rendering/src/omeis/providers/re/Renderer.java`` and in ``components/server/src/ome/services/RenderingBean.java``

and you will also need a db_patch and add support to inverseintensity
I have locally made the following changes directly to schema (for convenience)
``
    alter table inverseintensitycontext 
        add constraint FKinverseintensitycontext_codomainmapcontext_id_codomainmapcontext 
        foreign key (codomainmapcontext_id) 
        references codomainmapcontext  ;;
``
``
    create table inverseintensitycontext (
        "inverse" bool not null,
        codomainmapcontext_id int8 not null,
        primary key (codomainmapcontext_id)
    );;
``

The DB patch will conflict with @manics patch

With the change above I can import and view images w/o problems

**Comment by jburel** [comment]
web url should handle both in that case reverse and invert

**Pull request closed without merging**
