### PR TITLE
Save imagej

### PR DESCRIPTION
**Pull request by jburel**
To test
 * Open a mif in imageJ
 * draw a roi on one image. Save as overlay
 * Click on the plugins>OMERO>Save to OMERO (not Upload and Save)
 * Check that the image are imported and the rois saved on the correct ones.

### CODE REVIEW

**Comment by gusferguson** [comment]
@jburel  - do I use ImageJ1 or ImageJ2?

**Comment by jburel** [comment]
ImageJ1 for now

**Comment by jburel** [comment]
Discussed with @pwalczysko and @gusferguson, the change works fine for ```Beta Catenin.lif``` but not with the lei. 
So the problem seems to be at the series reading level.

**Comment by jburel** [comment]
@gusferguson, @pwalczysko: the problem was actually due to the fact the series value was not preserved see https://github.com/openmicroscopy/bioformats/pull/1627
To test:
 * use ```leica/tropo/tropo.lei```

**Comment by pwalczysko** [comment]
Tested with ``test_images_metadata/tropo/tropo.lei`` and ``test_images_good/leica-liff/Beta catenin``. For both MIFs
The ``Upload and Save to OMERO`` workflow works as expected.
The ``Save to OMERO`` workflow does not work, again, the region on the last selected image is on every image.

**Comment by jburel** [comment]
Did you upgrade b-f package?

**Comment by jburel** [comment]
@pwalczysko: ignore my comment. The index is correctly set but the roi is linked to all the images when using the Save option only.
investigating

**Comment by jburel** [comment]
@pwalczysko: retested again with new B-F, I cannot reproduce the error. I deleted my previous comment I was on the wrong branch

**Comment by pwalczysko** [comment]
Retest today with ``tropo.lei`` - works as expected on ``Save...`` as well as ``Upload...`` options.
Ready to merge.

**Comment by jburel** [comment]
B-F has been merged, merging

**Comment by jburel** [comment]
--no-rebase

**Pull request merged**
