### PR TITLE
have import calculate the uploaded file checksum only once, not twice

### PR DESCRIPTION
**Pull request by mtbc**
# What this PR does

@joshmoore discovered that import calculates each file checksum twice over. This PR reduces that to being only once.

# Testing this PR

Import should still work fine with no regressions. To try to break it: In the CLI you can try the `--checksum-algorithm` option and with the server configuration you can adjust `omero.checksum.supported` to force selection of different algorithms.

# Related reading

https://trello.com/c/BPrkScBc/36-file-upload-should-be-faster

### CODE REVIEW

**Comment by joshmoore** [comment]
Is it safe to assume that the algorithm is the same at this point?

**Comment by mtbc** [comment]
That's my reading of the code. It's set when the fileset is created then respected by the raw file bean.

**Comment by mtbc** [comment]
(At least in my own testing I haven't managed to cause a checksum mismatch!)

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#1082](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/1082/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/1082/consoleText) for more details.
Possible conflicts:
  - PR #5821 joshmoore 'perf4j: log import timings in import log'
    - components/blitz/src/ome/services/blitz/repo/ManagedImportProcessI.java

--conflicts

**Comment by mtbc** [comment]
No hurry to address conflict, this PR still needs work anyway. *Update:* Said work now done.

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#1083](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/1083/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/1083/consoleText) for more details.
Possible conflicts:
  - PR #5821 joshmoore 'perf4j: log import timings in import log'
    - components/blitz/src/ome/services/blitz/repo/ManagedImportProcessI.java

--conflicts

**Comment by mtbc** [comment]
Once https://github.com/openmicroscopy/openmicroscopy/pull/5821 is in applying Perf4J to `omero.import.process.checksum` should confirm that this is now fast.

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#1087](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/1087/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/1087/consoleText) for more details.
Possible conflicts:
  - PR #5821 joshmoore 'perf4j: log import timings in import log'
    - components/blitz/src/ome/services/blitz/repo/ManagedImportProcessI.java

~~--conflicts~~ Conflict resolved in build [OMERO-push#163](https://web-proxy.openmicroscopy.org/west-ci/job/OMERO-push/163/). See the [console output](https://web-proxy.openmicroscopy.org/west-ci/job/OMERO-push/163/consoleText) for more details.

**Comment by joshmoore** [comment]
Testing 300 1G files in a single dataset:

```
301 files uploaded, 1 fileset created, 1 image imported, 0 errors in 0:14:02.450
```

```
   upload time of 814.57s for 301 files (2.706s/file)
    setId time of  16.20s
 metadata time of   0.07s
   pixels time of   9.86s for 300 planes (0.033s/plane)
    rdefs time of   0.43s for 1 rendering setting (0.433s/rdef)
thumbnail time of   0.60s for 1 thumbnail (0.605s/thumbnail)
```

```
omero.import.process.checksum                            2.3           2           9         0.7         301
omero.services.file.checksum                          5297.0           1       28389      2621.8         301
```

:+1:

**Comment by joshmoore** [comment]
Only questions remaining in my head:

 * would querying ever be slower than calculating?
 * could the query ever return null?

**Comment by mtbc** [comment]
I expect that querying should at least be fast enough that we never notice and care.

I don't see how the querying could return null but I could catch and log.

**Comment by mtbc** [comment]
Logged at ERROR because this really is unexpected.

**Comment by mtbc** [comment]
After hacking the server to make the query fail:
```
2018-08-30 08:41:58,784 ERROR [    o.s.blitz.repo.ManagedImportProcessI] (.Server-10) no server checksum on imported file cf4b0d48-0998-491e-94c7-0a8fa7c53240_556/2018-08/30/08-41-57.762/image.fake
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[na:1.8.0_181]
	at java.util.ArrayList.get(ArrayList.java:433) ~[na:1.8.0_181]
	at ome.services.blitz.repo.ManagedImportProcessI.verifyUpload(ManagedImportProcessI.java:350) ~[blitz.jar:na]
...
```

**Comment by joshmoore** [comment]
10GB file symlinked with no skips:

```
omero.import.process.checksum                           10.0          10          10         0.0           1
omero.services.file.checksum                         20381.0           1       40761     20380.0           2
```

:+1: (I'm not going to try to hack the server)

**Pull request merged**
