### PR TITLE
Downgrade

### PR DESCRIPTION
**Pull request by jburel**
Reactivate the tests validating the OME-XML and OME-TIFF export and downgrade
Previously limited to the latest stylesheet (hard-coded)
All possible downgrades are now read from the catalog file.
Few tests are still failing i.e. going back to schema 2008-09 and prior.
Still some work to do i.e. review certain stylesheets conversion

to run test
```
./build.py -f components/tools/OmeroJava/build.xml test -DTEST=integration/ExporterTest
```
Related PR https://github.com/openmicroscopy/bioformats/pull/1668
cc @qidane @joshmoore @pwalczysko 

--no-rebase

### CODE REVIEW

**Comment by sbesson** [comment]
See failures in https://ci.openmicroscopy.org/view/Failing/job/OMERO-5.1-breaking-integration-java/lastCompletedBuild/testngreports/

**Comment by jburel** [comment]
@sbesson: failures are expected. I am down to 6 now. I hope to have the PR out of breaking for monday

**Comment by jburel** [comment]
removing breaking label, all the tests now pass locally.

**Comment by jburel** [comment]
Ant suite
Total tests run: 76, Failures: 0, Skips: 0

**Comment by jburel** [comment]
Now that we have the stylesheets to downgrade working, I have added upgrade tests i.e.
generate a 2003-FC and upgrade it back to 2015-01
Entries read from ome-transforms.

**Comment by jburel** [comment]
--depends-on https://github.com/openmicroscopy/bioformats/pull/1668

**Pull request merged**
