### PR TITLE
Insight offline

### PR DESCRIPTION
**Pull request by jburel**
# What this PR does

Bring to the mainline the customization made to the client so it can work with omero-smuggler

This PR depends on https://github.com/openmicroscopy/omero-ms-queue/pull/18

# Testing this PR
* You will need to deploy locally omero-smuggler. See https://github.com/openmicroscopy/omero-ms-queue/pull/18
* the user used for testing needs to have an email address set
* in container.xml replace
``
<entry name="omero.client.import.offline.enabled" type="boolean">false</entry>
``
by
``
<entry name="omero.client.import.offline.enabled" type="boolean">true</entry>
``
* Import an image
* Check that it imports correctly

# Related reading

https://trello.com/c/sgiFlGNk/27-integrate-offline-import-to-mainline

cc @c0c0n3 @dominikl

### CODE REVIEW

**Comment by dominikl** [comment]
A dataset is created but the image isn't imported. 
Exception:
```
org.openmicroscopy.shoola.svc.transport.TransportException: Failed to submit files for offline import: invalid import submission
	at org.openmicroscopy.shoola.svc.proxy.ImportReply.error(ImportReply.java:14)
	at org.openmicroscopy.shoola.svc.proxy.ImportReply.unmarshal(ImportReply.java:32)
	at org.openmicroscopy.shoola.svc.transport.HttpChannel.exchange(HttpChannel.java:105)
	at org.openmicroscopy.shoola.svc.proxy.CommunicatorProxy.enqueueImport(CommunicatorProxy.java:148)
	at org.openmicroscopy.shoola.env.data.views.calls.OfflineImagesImporter.submit(OfflineImagesImporter.java:147)
	at org.openmicroscopy.shoola.env.data.views.calls.OfflineImagesImporter.enqueueImportBatch(OfflineImagesImporter.java:167)
	at org.openmicroscopy.shoola.env.data.views.calls.OfflineImagesImporter.access$000(OfflineImagesImporter.java:51)
	at org.openmicroscopy.shoola.env.data.views.calls.OfflineImagesImporter$1.doCall(OfflineImagesImporter.java:173)
	at org.openmicroscopy.shoola.env.data.views.BatchCall.doStep(BatchCall.java:144)
	at org.openmicroscopy.shoola.util.concur.tasks.CompositeTask.doStep(CompositeTask.java:226)
	at org.openmicroscopy.shoola.env.data.views.CompositeBatchCall.doStep(CompositeBatchCall.java:126)
	at org.openmicroscopy.shoola.util.concur.tasks.ExecCommand.exec(ExecCommand.java:165)
	at org.openmicroscopy.shoola.util.concur.tasks.ExecCommand.run(ExecCommand.java:276)
	at org.openmicroscopy.shoola.util.concur.tasks.AsyncProcessor$Runner.run(AsyncProcessor.java:91)
	at java.lang.Thread.run(Thread.java:748)

	at org.openmicroscopy.shoola.env.data.util.Status.notifyOfflineImportFailure(Status.java:696)
	at org.openmicroscopy.shoola.agents.fsimporter.util.FileImportComponent.propagateOfflineImportFailureStatus(FileImportComponent.java:1497)
	at org.openmicroscopy.shoola.agents.fsimporter.view.ImporterUIElement.handleOfflineImportOutcome(ImporterUIElement.java:241)
	at org.openmicroscopy.shoola.agents.fsimporter.view.ImporterUIElement.uploadComplete(ImporterUIElement.java:641)
	at org.openmicroscopy.shoola.agents.fsimporter.view.ImporterUIElement.uploadComplete(ImporterUIElement.java:621)
	at org.openmicroscopy.shoola.agents.fsimporter.view.ImporterComponent.uploadComplete(ImporterComponent.java:427)
	at org.openmicroscopy.shoola.agents.fsimporter.ImagesImporter.update(ImagesImporter.java:121)
	at org.openmicroscopy.shoola.env.data.events.DSCallAdapter.eventFired(DSCallAdapter.java:75)
	at org.openmicroscopy.shoola.env.data.views.BatchCallMonitor$1.run(BatchCallMonitor.java:124)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: org.openmicroscopy.shoola.svc.transport.TransportException: Failed to submit files for offline import: invalid import submission
	at org.openmicroscopy.shoola.svc.proxy.ImportReply.error(ImportReply.java:14)
	at org.openmicroscopy.shoola.svc.proxy.ImportReply.unmarshal(ImportReply.java:32)
	at org.openmicroscopy.shoola.svc.transport.HttpChannel.exchange(HttpChannel.java:105)
	at org.openmicroscopy.shoola.svc.proxy.CommunicatorProxy.enqueueImport(CommunicatorProxy.java:148)
	at org.openmicroscopy.shoola.env.data.views.calls.OfflineImagesImporter.submit(OfflineImagesImporter.java:147)
	at org.openmicroscopy.shoola.env.data.views.calls.OfflineImagesImporter.enqueueImportBatch(OfflineImagesImporter.java:167)
	at org.openmicroscopy.shoola.env.data.views.calls.OfflineImagesImporter.access$000(OfflineImagesImporter.java:51)
	at org.openmicroscopy.shoola.env.data.views.calls.OfflineImagesImporter$1.doCall(OfflineImagesImporter.java:173)
	at org.openmicroscopy.shoola.env.data.views.BatchCall.doStep(BatchCall.java:144)
	at org.openmicroscopy.shoola.util.concur.tasks.CompositeTask.doStep(CompositeTask.java:226)
	at org.openmicroscopy.shoola.env.data.views.CompositeBatchCall.doStep(CompositeBatchCall.java:126)
	at org.openmicroscopy.shoola.util.concur.tasks.ExecCommand.exec(ExecCommand.java:165)
	at org.openmicroscopy.shoola.util.concur.tasks.ExecCommand.run(ExecCommand.java:276)
	at org.openmicroscopy.shoola.util.concur.tasks.AsyncProcessor$Runner.run(AsyncProcessor.java:91)
	at java.lang.Thread.run(Thread.java:748)
```

On the smuggler side there's only:
```
2018-11-02 15:51:52.721  INFO 47177 --- [  XNIO-2 task-1] ome.smuggler.web.RequestLoggingFilter    : After request [uri=/ome/import;client=127.0.0.1;payload=[{"targetUri":"/Users/dlindner/Testing/TestImages/ACA1-1000_AF594_03_R3D.dv","omeroHost":"localhost","omeroPort":"4064","sessionKey:•e-c5c5-4a08-8ee1-cd2cc962e34c","datasetId":"5"}]]
```

Not much in the Blitz.log, just that the dataset was created, etc. no warnings/errors.

Using a local insight and server build from this PR and a local smuggler build from jburel/omero-ms-queue/smuggler-5.4 .

**Comment by jburel** [comment]
Could you describe your exact workflow?
I imported an image selecting an existing dataset

**Comment by jburel** [comment]
I have tried the following:
* Select an image and select New from Folder
* The dataset is created and the image is imported

**Comment by jburel** [comment]
Does your user have an e-mail address? it will not work without

**Comment by dominikl** [comment]
Ah sorry, I thought only in smuggler the email config needs to be set up, didn't set an email address for the user. I'll try again with the user email set.

**Comment by jburel** [comment]
Actually you don't need to set up email config in smuggler in order to work, only an email address for user is required.

**Comment by dominikl** [comment]
👍  Works now. Yes, only forgot to set an email address for the user. Will have a look through the code as well, although I have no idea how the "smuggler" works.

**Comment by jburel** [comment]
Javadoc is now green

**Comment by jburel** [comment]
@dominikl Did you have a chance to look at the code?

**Comment by dominikl** [comment]
Not yet, thought there might be some more changes coming. But that was only javadoc related. I'll have a look over the code now!

**Comment by dominikl** [comment]
Looks good! Relieved that apparently it wasn't too complicated to fit into my "lightweight importer" changes. From my point of view, good to merge 👍

**Pull request merged**
