### PR TITLE
Mapr annotations

### PR DESCRIPTION
**Pull request by manics**
# What this PR does

Implements the grouping of MapAnnotations in separate namespaces required for https://trello.com/c/VVUqCeZC/467-populate-map-annotations

The processing of existing bulkmap configuration files is unchanged.

New support is added for a `group` column type in the configuration file, which must contain `groupname` indicating the namespace for the MapAnnotation and `columns` indicating the columns to be converted into the MapAnnotation. See

- `test/integration/metadata/bulk_to_map_annotation_context_ns.csv`
- `test/integration/metadata/bulk_to_map_annotation_context_ns2.yml`

For examples.

Currently this implements deduplication of MapAnnotations within a single invocation only. This means if existing MapAnnotations are already present `omero metadata populate` may create a duplicate.

# Testing this PR

Import a plate:
- `bioformats/tools/mkfake -rows 2 -columns 3 test-plate.fake`
- `omero import test-plate.fake`

Add a bulk annotation to the plate:
- `omero metadata populate --file openmicroscopy/components/tools/OmeroPy/test/integration/metadata/bulk_to_map_annotation_context_ns.csv Plate:ID`

Copy the bulk-map-annotation config file `components/tools/OmeroPy/test/integration/metadata/bulk_to_map_annotation_context_ns2.yml` and add the following at the end:
```
advanced:
    well_to_images: yes
```
This is a hack to get annotations on wells to display in the webclient.

Convert to MapAnnotations:
- `omero metadata populate --context bulkmap --cfg bulk_to_map_annotation_context_ns2.yml Plate:ID`

The table data should be formatted as described by `bulk_to_map_annotation_context_ns.yml`

i.e. some key-value pairs should go into a MapAnnotation with a custom namespace, the remainder should go into the bulk-annotations namespace

screen shot 2016-08-08 at 13 48 51

# Related reading

- https://trello.com/c/VVUqCeZC/467-populate-map-annotations
- https://github.com/eleanorwilliams/idr-metadata/pull/17
- https://github.com/eleanorwilliams/idr-metadata/pull/18

## Edits

- **Only** map annotations with a primary key defined are de-duplicated

### CODE REVIEW

**Comment by jburel** [comment]
failure
``
/home/travis/build/openmicroscopy/openmicroscopy/components/romio/src/ome/io/nio/PixelsService.java:832: error: cannot find symbol
[nomemoryjava]         memoizer.setFailIfMissing(failIfMissing);
[nomemoryjava]                 ^
[nomemoryjava]   symbol:   method setFailIfMissing(boolean)
[nomemoryjava]   location: variable memoizer of type Memoizer
``

**Comment by manics** [comment]
@jburel That's a known problem with the `metadata52` branch, it's using the BF `metadata` branch which isn't downloadable from artifcatory(?)

**Comment by jburel** [comment]
@manics: As long as it is a known issue, thanks

**Comment by aleksandra-tarkowska** [comment]
@manics in order to build omero I always have to build BF. Maybe we could fix it by teachign travis to build bf first?

**Comment by aleksandra-tarkowska** [comment]
@manics but python is fialign becuse of ```./components/tools/OmeroPy/test/integration/metadata/test_populate.py:269:18: E126 continuation line over-indented for hanging indent```

**Comment by manics** [comment]
@aleksandra-tarkowska I forgot to run flake8 before pushing my last commit.

**Comment by manics** [comment]
For a real-life test get the latest idr-clone:
- delete existing map-annotations on `idr0002-heriche-condensation`: `omero metadata populate --context deletemap Screen:102`
- recreate map-annotations using `idr0002-screenA-bulkmap-config.yml` from https://github.com/eleanorwilliams/idr-metadata/pull/17: `omero metadata populate --context bulkmap --attach --cfg idr0002-screenA-bulkmap-config.yml Screen:102`
To delete all map-annotations you will have to use `--context deletemap --cfg idr0002-screenA-bulkmap-config.yml` so that the plugin knows which namespaces to delete.

**Comment by aleksandra-tarkowska** [comment]
tested with idr clone

```
$ bin/omero metadata populate --context deletemap Screen:102
Created session 7079141f-71d5-44d3-ac4b-f2e574f04f66 (demo@localhost:4064). Idle timeout: 10 min. Current group: demo
INFO:omero.util.populate_metadata:Total: 1152 MapAnnotation(s) in ['openmicroscopy.org/omero/bulk_annotations']
INFO:omero.util.populate_metadata:Deleted 1000 MapAnnotation(s)
INFO:omero.util.populate_metadata:Deleted 152 MapAnnotation(s)
$ Using session ef8a35ca-1b28-4175-983b-c4a512a0108a (demo@localhost:4064). Idle timeout: 10 min. Current group: demo
WARNING:omero.util.populate_metadata:PlateColumn is unimplemented
INFO:omero.util.populate_metadata:Missing image name column, skipping.
INFO:omero.util.populate_metadata:Missing image name column, skipping.
...
INFO:omero.util.populate_metadata:Missing image name column, skipping.
INFO:omero.util.populate_metadata:Created new table OriginalFile:8072686
INFO:omero.util.populate_metadata:Table initialized with 37 columns.
INFO:omero.util.populate_metadata:Added 1000 rows of column data (batch 1)
INFO:omero.util.populate_metadata:Added 152 rows of column data (batch 2)
bash-4.2$ bin/omero metadata populate --context bulkmap --attach --cfg /tmp/idr-maps/idr0002-heriche-condensation/screenA/idr0002-screenA-bulkmap-config.yml  Screen:102
Using session ef8a35ca-1b28-4175-983b-c4a512a0108a (demo@localhost:4064). Idle timeout: 10 min. Current group: demo
primary:('openmicroscopy.org/mapr/gene', frozenset([('Gene Identifier', 'ENSG00000117399')])) keyvalues:[('Gene Identifier', 'ENSG00000117399'), ('Gene Identifier URL', 'http://www.ensembl.org/id/ENSG00000117399'), ('Gene Symbol', 'CDC20')] parents:set([('Image', 179693L), ('Well', 67070L)])
...
primary:None keyvalues:[('Organism', 'Homo sapiens'), ('Cell Line', 'HeLa'), ('Control Type', 'empty'), ('Quality Control', 'fail'), ('Channels', 'H2B- mCherry/Cy3:chromatin;eGFP:nuclear lamina and report on nuclear envelope breakdown')] parents:set([('Image', 1938578L), ('Well', 1046872L)])
INFO:omero.util.populate_metadata:Created/linked 992 MapAnnotations (total 992)
INFO:omero.util.populate_metadata:Created/linked 992 MapAnnotations (total 1984)
INFO:omero.util.populate_metadata:Created/linked 1000 MapAnnotations (total 2984)
INFO:omero.util.populate_metadata:Created/linked 1000 MapAnnotations (total 3984)
INFO:omero.util.populate_metadata:Created/linked 656 MapAnnotations (total 4640)
```

**Comment by aleksandra-tarkowska** [comment]
tested also with the existing csv without groups

```
bash-4.2$ bin/omero metadata populate --context deletemap Screen:1351
bash-4.2$ bin/omero metadata populate --file /tmp/idr-maps/idr0010-doil-dnadamage/screenA/idr0010-screenA-annotation.csv Screen:1351
Previous session expired for demo on localhost:4064
Server: [localhost:4064]
Username: [demo]
Password:
Created session 4f52926c-a7c1-437c-8fcc-201938afff12 (demo@localhost:4064). Idle timeout: 10 min. Current group: demo
WARNING:omero.util.populate_metadata:Screen is missing plate: 2-60
...
INFO:omero.util.populate_metadata:Missing image name column, skipping.
INFO:omero.util.populate_metadata:Created new table OriginalFile:8072688
INFO:omero.util.populate_metadata:Table initialized with 28 columns.
INFO:omero.util.populate_metadata:Added 1000 rows of column data (batch 1)
INFO:omero.util.populate_metadata:Added 1000 rows of column data (batch 2)
INFO:omero.util.populate_metadata:Added 1000 rows of column data (batch 3)
INFO:omero.util.populate_metadata:Added 1000 rows of column data (batch 4)
INFO:omero.util.populate_metadata:Added 608 rows of column data (batch 5)
!! 08/09/16 14:40:23.163 error: communicator not destroyed during global destruction.bash-4.2$ 
bash-4.2$ bin/omero metadata populate --context bulkmap --attach --cfg /tmp/idr-maps/idr0010-doil-dnadamage/screenA/idr0010-screenA-bulkmap-config.yml Screen:1351      
Using session 4f52926c-a7c1-437c-8fcc-201938afff12 (demo@localhost:4064). Idle timeout: 10 min. Current group: demo
primary:None keyvalues:[('Gene Identifier', 'ENSG00000149503'), ('Gene Identifier URL', 'http://www.ensembl.org/id/ENSG00000149503'), ('Gene Symbol', 'INCENP')] parents:set([('Image', 1921251L), ('Well', 1033384L)])
...
primary:None keyvalues:[('Gene Identifier', 'no match in Ensembl 27'), ('Gene Identifier URL', 'http://www.ensembl.org/id/no match in Ensembl 27'), ('Gene Symbol', 'no match in Ensembl 27')] parents:set([('Well', 1050333L), ('Image', 1945534L)])
INFO:omero.util.populate_metadata:Created/linked 1000 MapAnnotations (total 1000)
INFO:omero.util.populate_metadata:Created/linked 1000 MapAnnotations (total 2000)
INFO:omero.util.populate_metadata:Created/linked 1000 MapAnnotations (total 3000)
INFO:omero.util.populate_metadata:Created/linked 1000 MapAnnotations (total 4000)
INFO:omero.util.populate_metadata:Created/linked 1000 MapAnnotations (total 5000)
INFO:omero.util.populate_metadata:Created/linked 1000 MapAnnotations (total 6000)
INFO:omero.util.populate_metadata:Created/linked 1000 MapAnnotations (total 7000)
INFO:omero.util.populate_metadata:Created/linked 1000 MapAnnotations (total 8000)
INFO:omero.util.populate_metadata:Created/linked 952 MapAnnotations (total 8952)
```

http://10.0.51.133/web/webclient/?show=well-1033384

**Comment by pwalczysko** [comment]
All worked for me as described in the header of the PR.

**Comment by aleksandra-tarkowska** [comment]
just deleted all the existing maps on IDR and repopulated them. Unfortunately duplicated are created as before

**Comment by manics** [comment]
Note a primary key must be defined de-duplication, e.g. https://github.com/manics/idr-metadata/blob/44344d3d1b6d7ea51370da0e92caca540fca66dc/idr0002-heriche-condensation/screenA/idr0002-screenA-bulkmap-config.yml

```
...

- group:
      groupname: openmicroscopy.org/mapr/gene
      columns:
      - name: Gene Identifier
include: yes

...

advanced:
    ignore_missing_primary_key: yes
    primary_group_keys:
    - groupname: openmicroscopy.org/mapr/gene
      keys:
      - Gene Identifier
```

**Comment by aleksandra-tarkowska** [comment]
@manics thanks for the explanation. Looks like deleting custom ns doesn't work I tried

```
bash-4.2$ bin/omero metadata populate --context deletemap --cfg /tmp/idr-maps/idr0010-doil-dnadamage/screenA/idr0010-screenA-bulkmap-config.yml Screen:102              
Previous session expired for demo on localhost:4064
Server: [localhost:4064]
Username: [demo]
Password:
Created session 34a2c2a6-066d-4cfa-b168-4d6884176655 (demo@localhost:4064). Idle timeout: 10 min. Current group: demo
INFO:omero.util.populate_metadata:Total: 1152 MapAnnotation(s) in ['openmicroscopy.org/omero/bulk_annotations']
INFO:omero.util.populate_metadata:Deleted 1000 MapAnnotation(s)
INFO:omero.util.populate_metadata:Deleted 152 MapAnnotation(s)
```

even shows 0 now

```
bash-4.2$ bin/omero metadata populate --context deletemap Screen:102                                                                                                     
Using session 34a2c2a6-066d-4cfa-b168-4d6884176655 (demo@localhost:4064). Idle timeout: 10 min. Current group: demo
INFO:omero.util.populate_metadata:Total: 0 MapAnnotation(s) in ['openmicroscopy.org/omero/bulk_annotations']
bash-4.2$ bin/omero metadata populate --context deletemap --cfg /tmp/idr-maps/idr0010-doil-dnadamage/screenA/idr0010-screenA-bulkmap-config.yml Screen:102
Using session 34a2c2a6-066d-4cfa-b168-4d6884176655 (demo@localhost:4064). Idle timeout: 10 min. Current group: demo
INFO:omero.util.populate_metadata:Total: 0 MapAnnotation(s) in ['openmicroscopy.org/omero/bulk_annotations']
bash-4.2$ 
```

custom http://10.0.51.133/web/webclient/?show=well-67070 are still in here

**Comment by aleksandra-tarkowska** [comment]
@manics thanks for the explanation. Looks like deleting custom ns doesn't work I tried

```
bash-4.2$ bin/omero metadata populate --context deletemap --cfg /tmp/idr-maps/idr0010-doil-dnadamage/screenA/idr0010-screenA-bulkmap-config.yml Screen:102              
Previous session expired for demo on localhost:4064
Server: [localhost:4064]
Username: [demo]
Password:
Created session 34a2c2a6-066d-4cfa-b168-4d6884176655 (demo@localhost:4064). Idle timeout: 10 min. Current group: demo
INFO:omero.util.populate_metadata:Total: 1152 MapAnnotation(s) in ['openmicroscopy.org/omero/bulk_annotations']
INFO:omero.util.populate_metadata:Deleted 1000 MapAnnotation(s)
INFO:omero.util.populate_metadata:Deleted 152 MapAnnotation(s)
```

even shows 0 

```
bash-4.2$ bin/omero metadata populate --context deletemap Screen:102                                                                                                     
Using session 34a2c2a6-066d-4cfa-b168-4d6884176655 (demo@localhost:4064). Idle timeout: 10 min. Current group: demo
INFO:omero.util.populate_metadata:Total: 0 MapAnnotation(s) in ['openmicroscopy.org/omero/bulk_annotations']
bash-4.2$ bin/omero metadata populate --context deletemap --cfg /tmp/idr-maps/idr0010-doil-dnadamage/screenA/idr0010-screenA-bulkmap-config.yml Screen:102
Using session 34a2c2a6-066d-4cfa-b168-4d6884176655 (demo@localhost:4064). Idle timeout: 10 min. Current group: demo
INFO:omero.util.populate_metadata:Total: 0 MapAnnotation(s) in ['openmicroscopy.org/omero/bulk_annotations']
bash-4.2$ 
```

custom are still in http://10.0.51.133/web/webclient/?show=well-67070 

It looks that if there is already map with custom namespace, reruning script will create duplicate even they have the same PK. Ideally would be if not.

**Comment by manics** [comment]
Can you paste the content of `/tmp/idr-maps/idr0010-doil-dnadamage/screenA/idr0010-screenA-bulkmap-config.yml`?

> It looks to me, that if there is already map with custom namespace, reruning script will create duplicate even they have the same PK. Ideally would be if not.

Yes, I'm saving that for a later PR since it requires database queries to find out what already exists.

**Comment by manics** [comment]
Do you think the `groupname` key should be renamed `namespace`?

**Comment by aleksandra-tarkowska** [comment]
Initial testing went well. All works as expected, just minor comment about rerunning script https://github.com/openmicroscopy/openmicroscopy/pull/4775#issuecomment-238682184 but that is file as it is possible to delete them all

**Comment by aleksandra-tarkowska** [comment]
Good to merge

**Comment by aleksandra-tarkowska** [comment]
> https://github.com/openmicroscopy/openmicroscopy/pull/4775#issuecomment-238702188

maybe `groupnamespace` or `groupns`

**Comment by manics** [comment]
I've got some additional commits in https://github.com/manics/openmicroscopy/tree/mapr-annotations-query
but since they involve loading multiple map-annotations, which may lead to performance issues, I think it's better to keep them separate.

@pwalczysko Just noticed your 👍 on https://github.com/openmicroscopy/openmicroscopy/pull/4775#issuecomment-238702188. I'll add that in the next PR if everyone's happy to sign-off on this.

**Comment by pwalczysko** [comment]
I am happy with this PR.

**Comment by atarkowska** [comment]
--rebased-to #5222

**Pull request merged**
