### PR TITLE
Organize information under share/ folder of OMERO.server

### PR DESCRIPTION
**Pull request by sbesson**
See https://github.com/openmicroscopy/openmicroscopy/pull/3871#issuecomment-118274227

This PR creates a new top-level folder share in the OMERO.server bundle which includes:
- the various licenses under lib/licenses
- the server/client dependencies generated by Ivy

### CODE REVIEW

**Comment by joshmoore** [comment]
Barring any references we have in the documentation to `$OMERO_HOME/licenses` or similar, this works for me.

**Comment by sbesson** [comment]
Waiting for @hflynn to chime in regarding the licenses front (and thoughts about moving `LICENSE.txt` under `share` as well?).

**Comment by hflynn** [comment]
I vote to leave LICENSE.txt at the top level. 
Git grep suggests the only /licenses reference in the docs is tools/licenses/resources/omero/Licenses.API.ice in /developers/Modules/ExceptionHandling.txt - I can easily correct that if it's been moved (has it?)

**Comment by sbesson** [comment]
So LGTM?

**Comment by hflynn** [comment]
:+1:

**Pull request merged**
