### PR TITLE
Newimage (rebased onto develop)

### PR DESCRIPTION
**Pull request by jburel**
This is the same as gh-4034 but rebased onto develop.

----

Fix issue https://github.com/openmicroscopy/openmicroscopy/issues/4033

To Test:
 * Open any image an save it to TIFF. 
 * Open the newly created TIff image
 * Save that image to OMERO (Plugins > OMERO > Save Image(s) to OMERO).

cc @stelfrich, @bramalingam 

Also test the parsing of the string with @bramalingam macro

### CODE REVIEW

**Comment by jburel** [comment]
--rebased-from #4034

**Comment by jburel** [comment]
@pwalczysko @bramalingam: was this PR ever reviewed?

**Comment by sbesson** [comment]
Looking at the standup history, it looks like this PR was never listed for review. Want to relist for tomorrow?

**Comment by jburel** [comment]
Will do, need to check if it will not conflict with other work on imagej front.
Will open another PR later today

**Comment by pwalczysko** [comment]
@jburel @sbesson : If the PR was in the merge builds recently, then indirectly it was reviewed. The workflow described above is a part of other workflows we were testing on IJ front and was passing.

**Comment by jburel** [comment]
it has been. Final check tomorrow in that case.

**Comment by sbesson** [comment]
@pwalczysko: was the last check successful?

**Comment by jburel** [comment]
@bramalingam has been busy with his presentation this can be reviewed on monday

**Comment by bramalingam** [comment]
I can do this post the practice round today.! Which would be post lunch.

**Comment by jburel** [comment]
--rebased-from #4034

**Pull request closed without merging**
