### PR TITLE
Java UI test: library cleanup

### PR DESCRIPTION
**Pull request by sbesson**
See https://trello.com/c/2qw5o7PL/27-clean-lib-repository and https://trello.com/c/RpJxX7S7/35-javadoc-cleanup

This PR removes the uber JAR `swinglibrary-1.6.0a.jar` under `lib/repository` and uses Maven central instead. Modifications are brought `ivysettings.xml` to retrieve the dependencies from the laugingpanda Maven repository. The Java classes are modified to import the `abbot` classes from the `abbot` JAR instead of the uber-JAR.

Additionally, this should remove the Javadoc warnings when building the `components/test/ui/library/java` component.

--no-rebase

### CODE REVIEW

**Comment by jburel** [comment]
* w/o this PR
```
components/tests/ui/library/java/target/libs/swinglibrary.jar(org/robotframework/abbot/script/ComponentReference.java):14: error: package org.jdom.input does not exist
05:15:35 import org.jdom.input.SAXBuilder;
```
* with this PR
```
03:38:53 Constructing Javadoc information...
03:38:53 Standard Doclet version 1.8.0_51
03:38:53 Building tree for all the packages and classes...
03:38:53 Building index for all the packages and classes...
03:38:53 Building index for all classes...
```

**Comment by jburel** [comment]
the README under ```components/test/ui``` will have to be updated

**Comment by sbesson** [comment]
Pushed the README update. The reference to the adjustement script as well as the issues has been conserved for the day we reactivate the Insight Robot tests.

**Comment by sbesson** [comment]
Fixed

**Comment by jburel** [comment]
travis is happy Merging

**Pull request merged**
