### PR TITLE
Tagging ome tiff

### PR DESCRIPTION
**Pull request by jburel**
Fix problems when tagging ome-tiff at import see https://trac.openmicroscopy.org.uk/ome/ticket/12164
Images were not tagged
To test:
 * Select an ome-tiff
 * Select or create a new tag.
 * Import the image.
 * Check that the image is tagged.

### CODE REVIEW

**Comment by pwalczysko** [comment]
Works as expected.

**Comment by joshmoore** [comment]
@jburel : a quick question -- why is this OME-TIFF specific?

**Comment by jburel** [comment]
it was not ome-tiff specific, just it happens to be highlighted with that specific format due to the check.

**Comment by joshmoore** [comment]
Gotcha. Thanks.

**Pull request merged**
