### PR TITLE
Add ability to run scripts against fa's from OMERO.Insight

### PR DESCRIPTION
**Pull request by dominikl**
Same as #3993 just for Insight

Test:
- Install @emilroz  's script which uses file annotations: https://github.com/emilroz/omero-user-scripts/blob/populate_metadata_fa_additions/util_scripts/Populate_Metadata.py 
- Add some file annotations to a plate
- Select the plate and some file annotations and run the script, which should open the script dialog
- Make sure the Plate ID and the the file annotations IDs are set in the dialog
- Run the script. Will fail, but in 'Info' in the activities popup you should see, that the parameters were passed correctly to the script.
- Additional test: Run some other scripts, to make sure the changes didn't break the script dialog for other scripts.

### CODE REVIEW

**Comment by will-moore** [comment]
@dominikl Sorry I missed this yesterday. All works fine.
Minor issue: If I click the button to show the checkboxes, then I browse to a different Object, the checkboxes are already shown. I would expect them to be returned to the 'hidden' state whenever a new object is loaded.
One trivial suggestion: 
I wonder if you could reduce the prominence of the "Select Files For Scripts" button by removing the blue & red window from the icon, and just go for the plain script icon. With the current icon, the button is about the most eye-catching button in the right panel which is inconsistent with it's niche use-case.

screen shot 2015-08-18 at 11 11 46

**Comment by dominikl** [comment]
Thanks @will-moore , added your suggestions.

**Comment by will-moore** [comment]
Looks good @dominikl, thanks. Good to merge.

**Comment by jburel** [comment]
@gusferguson: this is the PR discussed yesterday during group meeting,
The corresponding web one is gh-3993

**Comment by dominikl** [comment]
This should also be rebased to dev_5_1, right?

**Comment by jburel** [comment]
@dominikl: to avoid major rebasing issues, both PRs will be rebased to 5.1 (cc @emilroz @chris-allan) as discussed yesterday

**Comment by dominikl** [comment]
--exclude until #4092 is merged

**Comment by jburel** [comment]
More testing required @dominikl?

**Comment by dominikl** [comment]
I don't think so. I just had to solve a merge conflict after #4092 was merged.

**Comment by jburel** [comment]
@gusferguson: PR to be added to your list of "screenshots" required for help

**Comment by gusferguson** [comment]
@jburel - thanks

**Comment by jburel** [comment]
--rebased-to #4129

**Pull request merged**
