### PR TITLE
Roi read

### PR DESCRIPTION
**Pull request by jburel**
Problem highlighted while testing https://github.com/openmicroscopy/openmicroscopy/pull/3329

To test this PR
 * Draw a polygon or polyline in imageJ
 * Import it to OMERO
 * Open the image in insight and view the ROI.

### CODE REVIEW

**Comment by mtbc** [comment]
(Are we still updating copyright headers?)

**Comment by jburel** [comment]
one more commit was coming..

**Comment by mtbc** [comment]
:smile:

**Comment by pwalczysko** [comment]
Atm, no regions are being drawn, polyline, rectangle, elipse - nothing is there when the original image is imported -> unable to test this.

**Comment by pwalczysko** [comment]
Re https://github.com/openmicroscopy/openmicroscopy/pull/3349#issuecomment-70649211 - this is image specific. I was trying following images which do not work:
  - ``test_images_good/tiff/Hoechst...``
  - ``test_images_good/tiff/Alx-488-pk.tif``

Other images work like
  - ``test_images_good/jpeg/DMSOHigh_001.jpg``
  - ``test_images_good/zeiss-zvi/BY4741NQ2.zvi``

**Comment by pwalczysko** [comment]
``test_images_good/zeiss-lsm/2chZT.lsm`` works fine as well, also with the segmented line and polygon - so I think this PR is fine, and I was hitting some strange problem which is ``.tiff`` specific. Will check ``ome-tiff`` when opened from original as well.

**Comment by pwalczysko** [comment]
Also
``test_images_good/ome-tiff/multi-channel.ome.tif`` does behave like the ``.tiff`` images - no regions on it at all.

**Comment by jburel** [comment]
@pwalczysko: found the reason why it does not work for "tiff" images, problem will be fixed in https://github.com/openmicroscopy/openmicroscopy/pull/3329

**Comment by jburel** [comment]
@pwalczysko: happy with this PR?

**Comment by pwalczysko** [comment]
Yes, happy, tested as part of the https://github.com/openmicroscopy/openmicroscopy/pull/3329.

**Comment by jburel** [comment]
--no-rebase

**Pull request merged**
