### PR TITLE
Set namespace of fileannoation of omero.table - test

### PR DESCRIPTION
**Pull request by dominikl**
Adjust integration test for https://github.com/ome/omero-gateway-java/pull/18

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-push#1386](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-push/1386/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-push/1386/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - components/tools/OmeroJava/test/integration/gateway/TablesFacilityTest.java

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-push#1387](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-push/1387/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-push/1387/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - components/tools/OmeroJava/test/integration/gateway/TablesFacilityTest.java

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-push#1388](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-push/1388/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-push/1388/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - components/tools/OmeroJava/test/integration/gateway/TablesFacilityTest.java

~~--conflicts~~ Conflict resolved in build [OMERO-push#1406](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-push/1406/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-push/1406/consoleText) for more details.

**Comment by jburel** [comment]
https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/1306/testngreports/integration.gateway/TablesFacilityTest/testNameSpace/ is green

**Pull request merged**
