### PR TITLE
Lut selection insight

### PR DESCRIPTION
**Pull request by dominikl**
# What this PR does

Adds Lookup Tables support to Insight.

# Testing this PR

Select an Image. Go to right hand side Preview panel. Make sure you can select the lookup tables in the Channel color picker. This won't have an effect yet, because it's not implemented server side.

# Still ToDo

~~For now I just used the same icon for the 'lookup table' entry as the 'color list' entry in the tool bar. We'd need a new icon for that~~ /cc @gusferguson  -- **Done**
screen shot 2016-07-07 at 11 30 06

# Related reading

This PR is based on #4723

### CODE REVIEW

**Comment by gusferguson** [comment]
@dominikl 

This is made using 4 of the imageJ standard LUTs. 32 x 32 px.

What do you think?

icons6

**Comment by dominikl** [comment]
Looks good! Can you make a 24px one? I think the toolbar icons are 24x24.

**Comment by gusferguson** [comment]
24 x 24 px

lut-icon-24

**Comment by dominikl** [comment]
👍

**Pull request closed without merging**
