### PR TITLE
Rename shape properties

### PR DESCRIPTION
**Pull request by mtbc**
https://trello.com/c/9ZsIFHcJ/38-discrepancies calls for renaming `cx`, `cy`, `rx`, `ry` on `Ellipse` and `Point` in OMERO. This PR introduces DB patch `OMERO5.3DEV__2` in order to do so.

Testing: mostly, see if Ellipse or Point have developed any new problems, from whichever clients and scripts you can think of. Also, add some points and ellipses and other shapes to an image on an older OMERO, upgrade to this patch, then see if your ROIs survived intact.

### CODE REVIEW

**Comment by dominikl** [comment]
Looks good. Tested with Insight (also upgrade from `OMERO5.3DEV__1` to `OMERO5.3DEV__2` ). Good to merge from my point of view.

**Comment by dgault** [comment]
Based on the descrpeancies doc these renames all look good to me too

**Comment by sbesson** [comment]
Also tested the upgrade of the reference testing DB using this script:

```
$ psql -U omero OMERO-upgrade -f sql/psql/OMERO5.3DEV__2/OMERO5.2__0.sql 
BEGIN
CREATE FUNCTION
 omero_assert_db_version 
-------------------------
 
(1 row)

DROP FUNCTION
CREATE FUNCTION
CREATE FUNCTION
 assert_db_server_prerequisites 
--------------------------------
 
(1 row)

DROP FUNCTION
DROP FUNCTION
INSERT 0 1
CREATE FUNCTION
 assert_no_roi_keywords_namespaces 
-----------------------------------
 
(1 row)

DROP FUNCTION
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE SEQUENCE
INSERT 0 1
CREATE SEQUENCE
INSERT 0 1
CREATE SEQUENCE
INSERT 0 1
CREATE SEQUENCE
INSERT 0 1
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE VIEW
CREATE VIEW
CREATE VIEW
CREATE VIEW
CREATE VIEW
CREATE FUNCTION
CREATE TRIGGER
CREATE FUNCTION
UPDATE 3379
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
UPDATE 1
                                 status                                 
------------------------------------------------------------------------
                                                                       +
                                                                       +
                                                                       +
 YOU HAVE SUCCESSFULLY UPGRADED YOUR DATABASE TO VERSION OMERO5.3DEV__2+
                                                                       +
                                                                       +
 
(1 row)

COMMIT
```

Everything worked as expected. Will run the Python examples against the integration server before merging.

**Comment by sbesson** [comment]
Python examples run as expected against the server. Merging for the first milestone.

A related cleanup question that likely requires more discussion is whether the variable names should also be updated to match the renamed attributes for consistency. While this is fairly harmless for internal-only variables, such changes in public API like `marshal.py`, `ROIUtils` or even `omero-marshal` might have breaking impact on consumers. In this case, could we preserve both deprecated and updated attributes at the cost of duplication and drop the deprecated ones in the next breaking release? Or is it something we should consider deprecating immediately on the 5.2.x line? /cc @chris-allan @will-moore @jburel

**Comment by mtbc** [comment]
@sbesson: Absolutely. As that is largely code I don't know I tried to keep my own changes minimal but it's certainly an issue.

**Pull request merged**
