### PR TITLE
Decoupled

### PR DESCRIPTION
**Pull request by joshmoore**
This PR removes the component jars and their build systems in favor of https://github.com/ome/omero-build

 * [x] server-jars
 * [x] Python: see https://github.com/ome/omero-blitz/issues/3 and https://github.com/ome/omero-blitz/issues/4
 * [x] Insight
 * [x] tests

### CODE REVIEW

**Comment by joshmoore** [comment]
Currently looking into getting the server jars properly copied.

**Comment by joshmoore** [comment]
🎉 Running locally though I see:

```
omero_1  | err:Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory
omero_1  |      at ome.services.util.JvmSettingsCheck.<clinit>(JvmSettingsCheck.java:45)
omero_1  | Caused by: java.lang.ClassNotFoundException: org.apache.commons.logging.LogFactory
omero_1  |      at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
omero_1  |      at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
omero_1  |      at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
omero_1  |      at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
omero_1  |      ... 1 more
```
which leads to: 
```
JVM Settings:
============
blitz=-Xmx600m -XX:MaxPermSize=256m -XX:+IgnoreUnrecognizedVMOptions
indexer=-Xmx400m -XX:MaxPermSize=256m -XX:+IgnoreUnrecognizedVMOptions
pixeldata=-Xmx600m -XX:MaxPermSize=256m -XX:+IgnoreUnrecognizedVMOptions
repository=-Xmx400m -XX:MaxPermSize=256m -XX:+IgnoreUnrecognizedVMOptions
```

**Comment by joshmoore** [comment]
Now one should see:
```blitz=-Xmx7200m -XX:MaxPermSize=1g -XX:+IgnoreUnrecognizedVMOptions
indexer=-Xmx4800m -XX:MaxPermSize=1g -XX:+IgnoreUnrecognizedVMOptions
pixeldata=-Xmx7200m -XX:MaxPermSize=1g -XX:+IgnoreUnrecognizedVMOptions
repository=-Xmx4800m -XX:MaxPermSize=1g -XX:+IgnoreUnrecognizedVMOptions```

**Comment by joshmoore** [comment]
And the next issue (apparently docker-compose starts, but not the server. cc: @manics ):

```
Server:     icegridnode                    running
Server:     Blitz-0                        inactive (disabled)
```

```
Error: Unable to access jarfile lib/server/blitz.jar
Failed to instantiate [ch.qos.logback.classic.LoggerContext]
Reported exception:
java.lang.NoClassDefFoundError: org/codehaus/janino/ScriptEvaluator
...
        at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:85)
```

Underlying cause seems to be missing runtime dependencies from dsl/ivy.xml. Testing a fix locally.

**Comment by joshmoore** [comment]
Currently failing on:
```2019-01-11 09:51:42,822 ERROR [                ome.services.blitz.Entry] (      main) Error on startup.
org.springframework.beans.factory.access.BootstrapException: Unable to return specified BeanFactory instance: factory key [OMERO.blitz], from group with resource name [classpath*:beanRefContext.xml]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'OMERO.blitz' defined in URL [jar:file:/opt/omero/server/OMERO.server/lib/server/omero-blitz.jar!/beanRefContext.xml]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [ome.system.OmeroContext]: Constructor threw exception; nested exception is org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException: Line 34 in XML document from URL [jar:file:/opt/omero/server/OMERO.server/lib/server/omero-blitz.jar!/ome/services/blitz-servantDefinitions.xml] is invalid; nested exception is org.xml.sax.SAXParseException; lineNumber: 34; columnNumber: 74; Attribute "singleton" must be declared for element type "bean".
```

**Comment by jburel** [comment]
Now error is at omero-blitz
```
omero-blitz.jar!/ome/services/blitz-servantDefinitions.xml] is invalid; nested exception is org.xml.sax.SAXParseException; lineNumber: 34; columnNumber: 74; Attribute "singleton" must be declared for element type "bean".
```

**Comment by jburel** [comment]
With the last set of changes in omero-model, omero-common, omero-blitz and omero-server 
the server starts!!
Everything looks good in the Bliz.log

**Comment by jburel** [comment]
I cannot log in:
```
 Failed to connect: exception ::omero::InternalException
{
    serverStackTrace = 
    serverExceptionClass = org.springframework.beans.factory.BeanCreationException
    message = Error creating bean with name 'omero.api.IAdmin' defined in URL [jar:file:/Users/jmarie/Documents/git-repo/openmicroscopy/dist/lib/server/omero-blitz.jar!/ome/services/blitz-servantDefinitions.xml]: Cannot create inner bean 'ome.services.blitz.impl.AdminI#3f6906f4' of type [ome.services.blitz.impl.AdminI] while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ome.services.blitz.impl.AdminI#3f6906f4' defined in URL [jar:file:/Users/jmarie/Documents/git-repo/openmicroscopy/dist/lib/server/omero-blitz.jar!/ome/services/blitz-servantDefinitions.xml]: Initialization of bean failed; nested exception is ome.services.blitz.util.ApiConsistencyException: 
Return type mismatch in public abstract ome.api.IRoles ome.api.IAdmin.getSecurityRoles(): interface ome.api.IRoles <> class omero.sys.Roles
Return type mismatch in public abstract ome.api.IEventContext ome.api.IAdmin.getEventContext(): interface ome.api.IEventContext <> class omero.sys.EventContext
```

**Comment by joshmoore** [comment]
That's likely caused by https://trello.com/c/XmONQu76/39-omero-common-revert-ieventcontext-iroles

Since we already have a PR opened for every jar repo, I'd say let's push that fix now before merging.

**Comment by jburel** [comment]
New error when attempting to log in 
```
Return type mismatch in public abstract ome.system.EventContext ome.api.IAdmin.getEventContext(): interface ome.system.EventContext <> class omero.sys.EventContext
```

**Comment by jburel** [comment]
The error is now https://github.com/ome/omero-blitz/pull/8#issuecomment-453653084

**Comment by jburel** [comment]
https://github.com/ome/omero-model/pull/6/commits/3e1e245b8cdcb1fd9a497f01f11582bfabbe4f35 fixes the login issue

**Comment by manics** [comment]
https://github.com/openmicroscopy/openmicroscopy/pull/5934/commits/45e2f573ad86c42e5d18f697932809ad346ab5d5 builds for me following https://docs.google.com/presentation/d/1pgvj2aWlhSvloVlyt0yLMl2aBGWbOJogKULiXMA7e0Q/edit#slide=id.p

I can start the server and login. Haven't tested OMERO.web.

**Comment by mtbc** [comment]
```
Created session for user-2@localhost:4064. Idle timeout: 10 min. Current group: private-1
```

**Comment by mtbc** [comment]
I can log in via Web but I needed `omero.web.check_version=false` otherwise,
```
check_version():237 Client version: '['5', '5', '0']'; Server version: '['5', '4', '10']'
```

**Comment by jburel** [comment]
We have test failure due to the version mismatch. This is a known fact

**Comment by joshmoore** [comment]
Running through ci master for the first time momentarily...

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#1255](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/1255/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/1255/consoleText) for more details.
Possible conflicts:
  - PR #5792 kouichi-c-nakamura ' strToMapAnnotation.m components\tools\OmeroM\src\helper'
    - components/tools/OmeroM/src/annotations/writeMapAnnotation.m
  - PR #5799 kouichi-c-nakamura 'Link annotation'
    - components/tools/OmeroM/src/annotations/linkAnnotation.m

~~--conflicts~~ Conflict resolved in build [OMERO-DEV-merge-push#1256](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/1256/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/1256/consoleText) for more details.

**Comment by joshmoore** [comment]
Currently running into:

```
[ivy:retrieve] :: problems summary ::
[ivy:retrieve] :::: WARNINGS
[ivy:retrieve] 		[NOT FOUND  ] org.openmicroscopy#omero-blitz;5.5.0-m3!omero-blitz.zip(jar) (1ms)
[ivy:retrieve] 	==== user-maven: tried
[ivy:retrieve] 	  /home/omero/.m2/repository/org/openmicroscopy/omero-blitz/5.5.0-m3/omero-blitz-5.5.0-m3-python.zip
```

Perhaps due to https://stackoverflow.com/questions/24943065/ivyinstall-from-maven-with-classifiers

Re-adding `exclude` until I figure out a fix. (One option would be to have Jenkins build the plugins and components locally)

**Review by sbesson — APPROVED** [review]
I have been reviewing the latest diff of this PR locally using ` git diff --diff-filter=M` to remove the deleted files. I did not notice anything in the diff that I would flag as a blocker. Overnight builds show that the coupling work, consuming the milestone JARs published to the OME Artifactory.

Only question is that `omero.version` is now set to `5.5.0-SNAPSHOT` instead of `UNKNOWN`. This means the tag-based versioning logic from `components/antlib/resources/version.xml` will not apply and build artifacts will be simply called OMERO.(component)-5.5.0-SNAPSHOT(.suffix) - see [this morning build](https://ci.openmicroscopy.org/view/DEV/job/OMERO-DEV-merge-build/ICE=3.6,jdk=8_LATEST,label=octopus/1217/).

The above is not a blocker and can be carded/discussed/documented separately. As discussed this morning with the rest of the team, given the investment in this work and the fact we are able to produce a running server, I vote for merging this. Next actions will include work on the CI system and documentation to work on the daily review process of the new build as well as an announcement to the community.

**Comment by joshmoore** [comment]
After discussing with @jburel, I'm looking into how to remove the hard-coding of `omero.versions=5.5.0-SNAPSHOT`.

**Comment by joshmoore** [comment]
Green! Merging and emailing ome-devel. The latest jobs will be triggered and we can review their status.

**Pull request merged**
