### PR TITLE
Fixed wrong file count

### PR DESCRIPTION
**Pull request by dominikl**
See [Ticket 12905](https://trac.openmicroscopy.org/ome/ticket/12905)

Test: Check the File path info dialog shows the correct number of files (compare with OMERO.Web)

### CODE REVIEW

**Comment by gusferguson** [comment]
@dominikl 

Tested using OMERO.insight-5.2.0-m0-479-f740b93-ice35-b65-mac user-3 read-only 1

Same file counts shown in Insight and Web.
Behaves as expected.
Good to merge.

main

safari

main

safari

**Comment by jburel** [comment]
minor comment: 
if number of image files > 1 we should have X image files (not s in bracket) and no s if x <=1

**Comment by dominikl** [comment]
--rebased-to #4078

**Comment by dominikl** [comment]
Ah sorry, rebased it before the original PR was merged... Shall I correct it here and open a separate PR for dev_5_1 (because the rebased PR #4078 has been merged)?

**Comment by jburel** [comment]
you can correct it here and open a PR for 5.1

**Comment by dominikl** [comment]
Ok, done (although I suppose the case <1 shouldn't happen anyway).

**Comment by dominikl** [comment]
--exclude until #4092 is merged

**Comment by dominikl** [comment]
Can this be merged? Then I could rebase it to dev_5_1.

**Comment by mtbc** [comment]
You can rebase this even before. :smiley:

**Comment by jburel** [comment]
@dominikl: done thanks

**Comment by dominikl** [comment]
--rebased-to #4103

**Pull request merged**
