### PR TITLE
travis test failure

### PR DESCRIPTION
**Pull request by jburel**
# What this PR does

Attempt to fix the test timeout failure encountered when building using travis
Increase timeout value

# Testing this PR
Check that the test is green

### CODE REVIEW

**Comment by mtbc** [comment]
Might be useful for people to --depends-on before merge. :smiley:

**Comment by jburel** [comment]
First need to check if travis passes :smiley:

**Comment by jburel** [comment]
@mtbc: I have restarted travis to check if we were lucky the first time

**Comment by mtbc** [comment]
Passed again! Maybe it's indeed working.

**Pull request merged**
