### PR TITLE
web virtual env

### PR DESCRIPTION
**Pull request by jburel**
This allows to run in virtual env
to be tested with https://github.com/ome/omero-install/pull/64

### CODE REVIEW

**Comment by joshmoore** [comment]
When ready, the expected output files will need to be updated to have unit tests passing. E.g.
```
     [exec] E       assert not '--- \n\n+++ \n\n@@ -1,6 +1,11 @@\n\n ###\n ### Apache 2.4+ stanza for OMERO.web created 0000-00-00 00:00:00.000000\n ###\n+\n+#...ome pathToVirtualenv\n+#WSGIPythonPath pathToVirtualenv/lib64/python2.7/site-packages\n \n <VirtualHost _default_:1234>\n '
     [exec] 
     [exec] test/unit/clitest/test_web.py:452: AssertionError
```

**Comment by aleksandra-tarkowska** [comment]
In demon mode you have to add to the existing "python-path" parameter https://docs.djangoproject.com/en/1.8/howto/deployment/wsgi/modwsgi/#using-mod-wsgi-daemon-mode. This PR is not needed.

**Comment by jburel** [comment]
going to test it with docker file
Might still be good to add a comment to the file.

**Comment by jburel** [comment]
adding to the path to the virtual env to python-path works.
Unless we want to add a comment to the template, I will close this PR
@hflynn: what is your pref in terms of documentation? The comment will be added to the general doc

**Comment by hflynn** [comment]
comment in the sphinx docs works for me

**Comment by jburel** [comment]
Thanks closing in that case. I have updated the readme in https://github.com/ome/omero-install/pull/64

**Pull request closed without merging**
